/home/eleclhcb/LHCb/lbcat-cmake/CatBcn/src/Python.cpp File Reference
#include <vector>
#include <list>
#include `Processus.h`
#include `Element.h`
#include `LSDelayChipV1.h`
#include `ICECALv3.h`
#include `MSOxxxx.h`
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
Functions
BOOST_PYTHON_MODULE (libCatBcn)
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (libCatBcn)
class_<A3PE, bases <Element> >(`A3PE`) .def(`ctrlReg` ,&A3PE::ctrlReg,return_value_policy<reference_existing_object>()) .def(`resetReg` ,&A3PE::resetReg,return_value_policy<reference_existing_object>()) .def(`setupReg` ,&A3PE::setupReg,return_value_policy<reference_existing_object>()) .def(`statusReg` ,&A3PE::statusReg,return_value_policy<reference_existing_object>()) .def(`acqReg` ,&A3PE::acqReg,return_value_policy<reference_existing_object>()) .def(`latencyReg` ,&A3PE::acqReg,return_value_policy<reference_existing_object>()) .def(`writeLengthFifoReg` ,&A3PE::writeLengthFifoReg,return_value_policy<reference_existing_object>()) .def(`clockDivisionReg` ,&A3PE::clockDivisionReg,return_value_policy<reference_existing_object>()) .def(`triggerReg` ,&A3PE::triggerReg,return_value_policy<reference_existing_object>()) .def(`toAXReg` ,&A3PE::toAXReg,return_value_policy<reference_existing_object>()) .def(`fromAXReg` ,&A3PE::fromAXReg,return_value_policy<reference_existing_object>()) .def(`spare3Reg` ,&A3PE::spare3Reg,return_value_policy<reference_existing_object>()) .def(`storageRam` ,&A3PE::storageRam,return_value_policy<reference_existing_object>()) .def(`patternRam` ,&A3PE::patternRam,return_value_policy<reference_existing_object>()) .def(`triggerRam` ,&A3PE::triggerRam,return_value_policy<reference_existing_object>()) .def(`toAXRam` ,&A3PE::toAXRam,return_value_policy<reference_existing_object>()) .def(`fromAXRam` ,&A3PE::fromAXRam,return_value_policy<reference_existing_object>()) .def(`testRam` ,&A3PE::testRam,return_value_policy<reference_existing_object>()) .def(`reset` ,&A3PE::reset) .def(`resetStorageFifo` ,&A3PE::resetStorageFifo) .def(`resetTriggerFifo` ,&A3PE::resetTriggerFifo) .def(`resetPatternFifo` ,&A3PE::resetPatternFifo) .def(`resetFromAXRam` ,&A3PE::resetFromAXRam) .def(`resetToAXRam` ,&A3PE::resetToAXRam) .def(`resetSequenceFromToAX` ,&A3PE::resetSequenceFromToAX) .def(`resetUsbPhasers` ,&A3PE::resetUsbPhasers) .def(`resetLatencyCounter` ,&A3PE::resetLatencyCounter) .def(`resetAcquisitionWriteCounter` ,&A3PE::resetAcquisitionWriteCounter) .def(`setEnableADC` ,&A3PE::setEnableADC) .def(`enableADC` ,&A3PE::enableADC) .def(`setWriteStorageFifoUsb` ,&A3PE::setWriteStorageFifoUsb) .def(`writeStorageFifoUsb` ,&A3PE::writeStorageFifoUsb) .def(`setReadPatternFifoUsb` ,&A3PE::setReadPatternFifoUsb) .def(`readPatternFifoUsb` ,&A3PE::readPatternFifoUsb) .def(`setReadTriggerFifoUsb` ,&A3PE::setReadTriggerFifoUsb) .def(`readTriggerFifoUsb` ,&A3PE::readTriggerFifoUsb) .def(`setReadToAXRamUsb` ,&A3PE::setReadToAXRamUsb) .def(`readToAXRamUsb` ,&A3PE::readToAXRamUsb) .def(`setWriteFromAXRamUsb` ,&A3PE::setWriteFromAXRamUsb) .def(`writeFromAXRamUsb` ,&A3PE::writeFromAXRamUsb) .def(`setSoftwareTrigger` ,&A3PE::setSoftwareTrigger) .def(`softwareTrigger` ,&A3PE::softwareTrigger) .def(`setClockDivision` ,&A3PE::setClockDivision) .def(`clockDivision` ,&A3PE::clockDivision) .def(`setTriggerDelay` ,&A3PE::setTriggerDelay) .def(`triggerDelay` ,&A3PE::triggerDelay) .def(`setTriggerRate` ,&A3PE::setTriggerRate) .def(`triggerRate` ,&A3PE::triggerRate) .def(`setNTrigger` ,&A3PE::setNTrigger) .def(`nTrigger` ,&A3PE::nTrigger) .def(`setFifoLatency` ,&A3PE::setFifoLatency) .def(`fifoLatency` ,&A3PE::fifoLatency) .def(`setFifoDepth`, &A3PE::setFifoDepth) .def(`fifoDepth`, &A3PE::fifoDepth) .def(`acquisition`, &A3PE::acquisition) .def(`trigger`, &A3PE::trigger) .def(`enableStorage`, &A3PE::enableStorage) .def(`dataReady`, &A3PE::dataReady) .def(`dumpStorage`, &A3PE::dumpStorage) .def(`dumpPattern`, &A3PE::dumpPattern) .def(`dumpTrigger`, &A3PE::dumpTrigger) .def(`dumpToAX`, &A3PE::dumpToAX) .def(`dumpFromAX`, &A3PE::dumpFromAX) .def(`loadStorage`, &A3PE::loadStorage) .def(`loadPattern`, &A3PE::loadPattern) .def(`loadTrigger`, &A3PE::loadTrigger) .def(`loadToAX`, &A3PE::loadToAX) .def(`loadFromAX`, &A3PE::loadFromAX) .def(`setInternalAXSequence`, &A3PE::setInternalAXSequence) .def(`internalAXSequence`, &A3PE::internalAXSequence) .def(`setLengthAX`, &A3PE::setLengthAX) .def(`lengthAX`, &A3PE::lengthAX) .def(`setLatencyAX`, &A3PE::setLatencyAX) .def(`latencyAX`, &A3PE::latencyAX) .def(`setAddFromAXRam`, &A3PE::setAddFromAXRam) .def(`setAddToAXRam`, &A3PE::setAddToAXRam) .def(`startSequenceAX`, &A3PE::startSequenceAX) .def(`setPipeline`, &A3PE::setPipeline) .def(`pipeline`, &A3PE::pipeline) ;
class_<Proto40MHz_v1, bases <Element> >(`Proto40MHz_v1`) .def(`usb`,&Proto40MHz_v1::usb,return_value_policy<reference_existing_object>()) .def(`phaser0`,&Proto40MHz_v1::phaser0,return_value_policy<reference_existing_object>()) .def(`phaser1`,&Proto40MHz_v1::phaser1,return_value_policy<reference_existing_object>()) .def(`phaser2`,&Proto40MHz_v1::phaser2,return_value_policy<reference_existing_object>()) .def(`a3pe`, &Proto40MHz_v1::a3pe,return_value_policy<reference_existing_object>()) ;
class_<Acquisition,bases <Processus> >(`Acquisition`) .def(`initialize`,&Acquisition::initialize) .def(`execute`,&Acquisition::execute) .def(`finalize`,&Acquisition::finalize) .def(`setDepth`,&Acquisition::setDepth) .def(`depth`,&Acquisition::depth) .def(`setChannels`,&Acquisition::setChannels) .def(`channels`,&Acquisition::channels) .def(`setTrigger`,&Acquisition::setTrigger) .def(`trigger`,&Acquisition::trigger) .def(`setStoreTree`,&Acquisition::setStoreTree) .def(`setStoreTrend`,&Acquisition::setStoreTrend) .def(`setStoreSample`,&Acquisition::setStoreSample) .def(`storeTree`,&Acquisition::storeTree) .def(`storeTrend`,&Acquisition::storeTrend) .def(`storeSample`,&Acquisition::storeSample) .def(`setDeadTime`,&Acquisition::setDeadTime) .def(`deadTime`,&Acquisition::deadTime) .def(`setSample`,&Acquisition::setSample) .def(`sample`,&Acquisition::sample) .def(`setNBins`,&Acquisition::setNBins) .def(`nBins`,&Acquisition::nBins) .def(`setMinRange`,&Acquisition::setMinRange) .def(`minRange`,&Acquisition::minRange) .def(`setMaxRange`,&Acquisition::setMaxRange) .def(`maxRange`,&Acquisition::maxRange) ;
class_<A3PE_BitFlip,bases <Processus> >(`A3PE_BitFlip`) .def(`initialize`,&A3PE_BitFlip::initialize) .def(`execute`,&A3PE_BitFlip::execute) .def(`finalize`,&A3PE_BitFlip::finalize) .def(`setFile`,&A3PE_BitFlip::setFile) .def(`file`,&A3PE_BitFlip::file) ;
void (ICPhaser::*setPhasex2)(unsigned char, unsigned char) = (&ICPhaser::setPhase); void (ICPhaser::*setPhasex4)(unsigned char, unsigned char, unsigned char, unsigned char) = (&ICPhaser::setPhase);
class_<ICPhaser, bases <Element> >(`ICPhaser`) .def(`setPhase`,setPhasex2) .def(`setPhase`,setPhasex4) .def(`setAddress`,&ICPhaser::setAddress) .def(`address`,&ICPhaser::address) .def(`status`,&ICPhaser::status) .def(`reset`,&ICPhaser::reset) .def(`read` ,&ICPhaser::read) .def(`write`,&ICPhaser::write) .def(`regConfig` ,&ICPhaser::regConfig, return_value_policy<reference_existing_object>()) .def(`regStatus` ,&ICPhaser::regStatus, return_value_policy<reference_existing_object>()) ;
Definition at line 24 of file Python.cpp.
References LSDelayChipV1::bypassMisoMosi(), MSOxxxx::channelDisplay(), MSOxxxx::channelDisplayName(), MSOxxxx::channelOffset(), MSOxxxx::channelScale(), MSOxxxx::closeConnection(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), MSOxxxx::configTCPIP(), ICECALv3::dumpConfig(), ICECALv3::getAnalogCh(), LSDelayChipV1::getConfigReg(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), MSOxxxx::getStatistics(), MSOxxxx::id(), MSOxxxx::labelDisplay(), ICECALv3::loadConfig(), MSOxxxx::open(), LSDelayChipV1::reset(), MSOxxxx::run(), ICECALv3::setAddress(), LSDelayChipV1::setAddress(), ICECALv3::setAnalogCh(), LSDelayChipV1::setConfigReg(), LSDelayChipV1::setConfigRegDebugMode(), LSDelayChipV1::setConfigRegLOCUS(), LSDelayChipV1::setConfigRegLVDSOutEn(), LSDelayChipV1::setConfigRegPhaseADC(), LSDelayChipV1::setConfigRegPhaseINT(), LSDelayChipV1::setConfigRegPhaseTH(), LSDelayChipV1::setConfigRegVControlOutEn(), MSOxxxx::setDebugMode(), ICECALv3::setDelayLineCh(), ICECALv3::setMainReg(), ICECALv3::setNRetries(), MSOxxxx::setupAvgVoltage(), MSOxxxx::setupDeltaTime(), MSOxxxx::setupJitter(), LSDelayChipV1::showConfig(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), MSOxxxx::stop(), MSOxxxx::timeBaseOffset(), MSOxxxx::timeBaseScale(), MSOxxxx::triggerAuto(), MSOxxxx::triggerConfig(), and MSOxxxx::waveformCapture().
{
  class_<LSDelayChipV1, bases <Element> >("LSDelayChipV1")
    .def("configRegBulkRead" ,&LSDelayChipV1::configRegBulkRead)
    .def("configRegBulkWrite" ,&LSDelayChipV1::configRegBulkWrite)
    .def("getConfigReg" ,&LSDelayChipV1::getConfigReg)
    .def("setConfigReg" ,&LSDelayChipV1::setConfigReg)
    
    .def("setConfigRegPhaseADC" ,&LSDelayChipV1::setConfigRegPhaseADC
      )
    .def("setConfigRegPhaseTH " ,&LSDelayChipV1::setConfigRegPhaseTH)
    .def("setConfigRegPhaseINT" ,&LSDelayChipV1::setConfigRegPhaseINT
      )
    .def("setConfigRegLVDSOutEn" ,&LSDelayChipV1::setConfigRegLVDSOutEn
      )
    .def("setConfigRegDebugMode" ,&LSDelayChipV1::setConfigRegDebugMode
      )
    .def("setConfigRegVControlOutEn",&LSDelayChipV1::setConfigRegVControlOutEn
      )
    .def("setConfigRegLOCUS" ,&LSDelayChipV1::setConfigRegLOCUS)
    
    .def("resetPumps" ,&LSDelayChipV1::setConfigRegVControlOutEn
      )
    .def("bypassMisoMosi" ,&LSDelayChipV1::bypassMisoMosi)
    .def("spiBERTest" ,&LSDelayChipV1::spiBERTest)
    
    .def("showConfig" ,&LSDelayChipV1::showConfig)
    .def("reset" ,&LSDelayChipV1::reset)
    
    .def("setAddress",&LSDelayChipV1::setAddress)
    ;
  class_<ICECALv3, bases <Element> >("ICECALv3")
    .def("setAddress" ,&ICECALv3::setAddress)
    .def("setNRetries" ,&ICECALv3::setNRetries)
    .def("getDelayLineCh" ,&ICECALv3::getDelayLineCh)
    .def("setDelayLineCh" ,&ICECALv3::setDelayLineCh)
    .def("getAnalogCh" ,&ICECALv3::getAnalogCh)
    .def("setAnalogCh" ,&ICECALv3::setAnalogCh)
    .def("getMainReg" ,&ICECALv3::getMainReg)
    .def("setMainReg" ,&ICECALv3::setMainReg)
    .def("loadConfig" ,&ICECALv3::loadConfig)
    .def("dumpConfig" ,&ICECALv3::dumpConfig)
    .def("spiFERTest" ,&ICECALv3::spiFERTest)
    ;
  class_<MSOxxxx, bases <Element> >("MSOxxxx")
    //Communications:
    .def("configTCPIP" ,&MSOxxxx::configTCPIP)
    .def("open" ,&MSOxxxx::open)
    .def("stop" ,&MSOxxxx::closeConnection)
    //Debug mode:
    .def("setDebugMode" ,&MSOxxxx::setDebugMode)
    //Oscilloscope commands:
    .def("channelScale" ,&MSOxxxx::channelScale)
    .def("channelOffset" ,&MSOxxxx::channelOffset)
    .def("channelDisplay" ,&MSOxxxx::channelDisplay)
    .def("channelDisplayName" ,&MSOxxxx::channelDisplayName)
    .def("timeBaseScale" ,&MSOxxxx::timeBaseScale)
    .def("timeBaseOffset" ,&MSOxxxx::timeBaseOffset)
    .def("triggerAuto" ,&MSOxxxx::triggerAuto)
    .def("triggerConfig" ,&MSOxxxx::triggerConfig)
    .def("labelDisplay" ,&MSOxxxx::labelDisplay)
    //Measurements:
    .def("setupJitter" ,&MSOxxxx::setupJitter)
    .def("setupAvgVoltage" ,&MSOxxxx::setupAvgVoltage)
    .def("setupDeltaTime" ,&MSOxxxx::setupDeltaTime)
    .def("getStatistics" ,&MSOxxxx::getStatistics)
    //Acquisition:
    .def("waveformCapture" ,&MSOxxxx::waveformCapture)
    //Tools:
    .def("id" ,&MSOxxxx::id)
    .def("run" ,&MSOxxxx::run)
    .def("stop" ,&MSOxxxx::stop)
    ;
  /*
  class_<A11713B, bases <Element> >("A11713B")
    .def("setGpibAddr" ,&A11713B::setGpibAddr)
    .def("getGpibAddr" ,&A11713B::getGpibAddr)
    .def("gpibOpen" ,&A11713B::gpibOpen)
    .def("getDeviceName" ,&A11713B::getDeviceName)
    .def("setAttenuation" ,&A11713B::setAttenuation)
    .def("getAttenuation" ,&A11713B::getAttenuation)
    .def("printConfig" ,&A11713B::printConfig)
    .def("reset" ,&A11713B::reset)
    ;
  */
}