/home/eleclhcb/LHCb/lbcat-cmake/CatCore/src/Python.cpp File Reference
#include <vector>
#include <list>
#include `IOobject.h`
#include `IOdata.h`
#include `Interface.h`
#include `RAM.h`
#include `Register.h`
#include `UsbI2cBus.h`
#include `UsbSpiBus.h`
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
Classes
struct InterfaceWrap
Functions
BOOST_PYTHON_MODULE (libCatCore)
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (libCatCore)
Definition at line 27 of file Python.cpp.
References IOdata::address(), IOobject::address(), UsbSpiBus::aSS(), IOdata::block(), IOdata::bus(), UsbSpiBus::clockDivider(), IOdata::dataU16(), IOdata::dataU32(), IOdata::dataU8(), IOdata::defDataU16(), IOdata::defDataU32(), IOdata::defDataU8(), IOobject::dump(), IOdata::dump(), Register::getBit(), IOdata::header(), Interface::help(), UsbI2cBus::help(), UsbSpiBus::help(), IOobject::help(), Interface::init(), UsbI2cBus::init(), UsbSpiBus::init(), IOobject::init(), IOobject::io(), IOdata::length(), UsbSpiBus::lSBFirst(), IOdata::mode(), IOdata::outputSelect(), RAM::raz(), Interface::read(), IOobject::read(), UsbI2cBus::regAddress(), UsbSpiBus::regClockDivider(), UsbSpiBus::regCtrl(), UsbI2cBus::regData(), UsbSpiBus::regRxData(), UsbSpiBus::regSlaveSelect(), UsbSpiBus::regTxData(), IOobject::reset(), Interface::reset(), UsbI2cBus::reset(), UsbSpiBus::reset(), UsbSpiBus::rxNeg(), IOdata::setAddress(), IOobject::setAddress(), UsbSpiBus::setASS(), Register::setBit(), IOdata::setBlock(), IOdata::setBus(), UsbSpiBus::setClockDivider(), IOdata::setHeader(), IOdata::setLength(), UsbSpiBus::setLSBFirst(), IOdata::setMode(), IOdata::setOutputSelect(), UsbSpiBus::setRxNeg(), RAM::setSize(), IOdata::setSubAddress(), UsbSpiBus::setTxNeg(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), IOdata::setWordSize(), IOdata::subAddress(), UsbSpiBus::txNeg(), Interface::update(), IOobject::update(), UsbI2cBus::update(), UsbSpiBus::update(), IOdata::wordSize(), Interface::write(), and IOobject::write().
{
  class_< std::vector<unsigned long> >("ULongVec")
    .def(vector_indexing_suite< std::vector<unsigned long> >())
    ;
  class_<InterfaceWrap, boost::noncopyable, bases<Element> >("Interface")
    .def("help",pure_virtual(&Interface::help))
    .def("init",pure_virtual(&Interface::init))
    .def("reset",pure_virtual(&Interface::reset))
    .def("update",pure_virtual(&Interface::update))
    .def("read",pure_virtual(&Interface::read))
    .def("write",pure_virtual(&Interface::write))
  ;
  class_<UsbI2cBus, bases<Interface> >("UsbI2cBus")
    .def("help" ,&UsbI2cBus::help)
    .def("init" ,&UsbI2cBus::init)
    .def("reset" ,&UsbI2cBus::reset)
    .def("update" ,&UsbI2cBus::update)
    .def("regData" ,&UsbI2cBus::regData,return_value_policy<reference_existing_object>(
      ))
    .def("regAddress",&UsbI2cBus::regAddress,
      return_value_policy<reference_existing_object>())
  ;
  class_<UsbSpiBus, bases<Interface> >("UsbSpiBus")
    .def("help" ,&UsbSpiBus::help)
    .def("init" ,&UsbSpiBus::init)
    .def("reset" ,&UsbSpiBus::reset)
    .def("update" ,&UsbSpiBus::update)
    .def("setTxNeg" ,&UsbSpiBus::setTxNeg)
    .def("txNeg" ,&UsbSpiBus::txNeg)
    .def("setRxNeg" ,&UsbSpiBus::setRxNeg)
    .def("rxNeg" ,&UsbSpiBus::rxNeg)
    .def("setASS" ,&UsbSpiBus::setASS)
    .def("aSS" ,&UsbSpiBus::aSS)
    .def("setLSBFirst" ,&UsbSpiBus::setLSBFirst)
    .def("lSBFirst" ,&UsbSpiBus::lSBFirst)
    .def("setClockDivider",&UsbSpiBus::setClockDivider)
    .def("clockDivider" ,&UsbSpiBus::clockDivider)
    .def("regCtrl" ,&UsbSpiBus::regCtrl,
      return_value_policy<reference_existing_object>())
    .def("regClockDivider",&UsbSpiBus::regClockDivider,
      return_value_policy<reference_existing_object>())
    .def("regSlaveSelect",&UsbSpiBus::regSlaveSelect,
      return_value_policy<reference_existing_object>())
    .def("regRxData" ,&UsbSpiBus::regRxData,
      return_value_policy<reference_existing_object>())
    .def("regTxData" ,&UsbSpiBus::regTxData,
      return_value_policy<reference_existing_object>())
  ;
  unsigned long int (IOdata::*dataU8x) (unsigned long int) = (&
      IOdata::dataU8);
  unsigned long int (IOdata::*dataU16x)(unsigned long int) = (&
      IOdata::dataU16);
  unsigned long int (IOdata::*dataU32x)(unsigned long int) = (&
      IOdata::dataU32);
  class_<IOdata, bases<Object> >("IOdata")
    .def("setAddress" ,&IOdata::setAddress)
    .def("setHeader" ,&IOdata::setHeader)
    .def("setSubAddress" ,&IOdata::setSubAddress)
    .def("setOutputSelect" ,&IOdata::setOutputSelect)
    .def("setMode" ,&IOdata::setMode)
    .def("setWordSize" ,&IOdata::setWordSize)
    .def("setLength" ,&IOdata::setLength)
    .def("setBlock" ,&IOdata::setBlock)
    .def("setBus" ,&IOdata::setBus)
    .def("address" ,&IOdata::address)
    .def("header" ,&IOdata::header)
    .def("subAddress" ,&IOdata::subAddress)
    .def("outputSelect" ,&IOdata::outputSelect)
    .def("mode" ,&IOdata::mode)
    .def("wordSize" ,&IOdata::wordSize)
    .def("length" ,&IOdata::length)
    .def("block" ,&IOdata::block)
    .def("bus" ,&IOdata::bus)
    .def("dump" ,&IOdata::dump)
    .def("defU8" ,&IOdata::defDataU8)
    .def("detU16" ,&IOdata::defDataU16)
    .def("detU32" ,&IOdata::defDataU32)
    .def("setU8" ,&IOdata::setU8)
    .def("setU16" ,&IOdata::setU16)
    .def("setU32" ,&IOdata::setU32)
    .def("dataU8" ,dataU8x)
    .def("dataU16" ,dataU16x)
    .def("dataU32" ,dataU32x)
  ;
  class_<IOobject, bases <Element> >("IOobject")
    .def("help", &IOobject::help)
    .def("init", &IOobject::init)
    .def("reset", &IOobject::reset)
    .def("update",&IOobject::update)
    .def("setAddress",&IOobject::setAddress)
    .def("address" ,&IOobject::address)
    .def("io", &IOobject::io,return_value_policy<reference_existing_object>())
    .def("read", &IOobject::read)
    .def("write", &IOobject::write)
    .def("dump" , &IOobject::dump)
    ;
  class_<Register, bases <IOobject> >("Register")
    .def("setBit", &Register::setBit)
    .def("getBit", &Register::getBit)
    ;
  class_<RAM, bases <IOobject> >("RAM")
    .def("setSize", &RAM::setSize)
    .def("raz", &RAM::raz)
    ;
  ;
}