/home/eleclhcb/LHCb/lbcat-cmake/CatCalo/src/Python.cpp File Reference
#include <vector>
#include <list>
#include `Processus.h`
#include `Phaser.h`
#include `PhaserRampExec.h`
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
Functions
BOOST_PYTHON_MODULE (libCatCalo)
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (libCatCalo)
Definition at line 15 of file Python.cpp.
References PhaserRampExec::execute(), PhaserRampExec::finalize(), PhaserRampExec::initialize(), Phaser::phase(), Phaser::read(), Phaser::reg(), Phaser::setPhase(), and Phaser::write().
{
  void (Phaser::*setPhasex2)(unsigned char, unsigned char) = (&
      Phaser::setPhase);
  void (Phaser::*setPhasex4)(unsigned char, unsigned char,
                             unsigned char, unsigned char) = (&Phaser::setPhase);
 
  class_<Phaser, bases <Element> >("Phaser")
    .def("setPhase",setPhasex2)
    .def("setPhase",setPhasex4)
    .def("phase",&Phaser::phase)
    .def("read" ,&Phaser::read)
    .def("write",&Phaser::write)
    .def("reg" ,&Phaser::reg,return_value_policy<reference_existing_object>())
    ;
  class_<PhaserRampExec,bases <Processus> >("PhaserRampExec")
    .def("initialize",&PhaserRampExec::initialize)
    .def("execute",&PhaserRampExec::execute)
    .def("finalize",&PhaserRampExec::finalize)
    ;
}