/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/src/Python.cpp File Reference
#include <vector>
#include <list>
#include `Processus.h`
#include `Element.h`
#include `A3PE.h`
#include `Proto40MHz_v1.h`
#include `Acquisition.h`
#include `A3PE_BitFlip.h`
#include `UsbFTInterface.h`
#include `RegisterTest.h`
#include `UsbFTInterfaceTest.h`
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
Functions
BOOST_PYTHON_MODULE (libCatCaloProto40MHz)
Function Documentation
BOOST_PYTHON_MODULE (libCatCaloProto40MHz)
Definition at line 22 of file Python.cpp.
References Proto40MHz_v1::a3pe(), A3PE::acqReg(), A3PE::acquisition(), Acquisition::channels(), A3PE::clockDivision(), A3PE::clockDivisionReg(), UsbFTInterface::close(), A3PE::ctrlAnaMezzReg(), A3PE::ctrlReg(), A3PE::dataReady(), Acquisition::deadTime(), Acquisition::depth(), UsbFTInterface::deviceDesc(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), A3PE::enableADC(), A3PE::enableStorage(), A3PE_BitFlip::execute(), Acquisition::execute(), A3PE::fifoDepth(), A3PE::fifoLatency(), A3PE_BitFlip::file(), A3PE_BitFlip::finalize(), Acquisition::finalize(), A3PE::fromAXRam(), A3PE::fromAXReg(), UsbFTInterface::init(), A3PE_BitFlip::initialize(), Acquisition::initialize(), A3PE::internalAXSequence(), A3PE::latencyAX(), UsbFTInterface::latencyTimer(), A3PE::lengthAX(), A3PE::loadFromAX(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Acquisition::maxRange(), UsbFTInterfaceTest::mean(), Acquisition::minRange(), Acquisition::nBins(), A3PE::nTrigger(), A3PE::patternRam(), Proto40MHz_v1::phaser0(), Proto40MHz_v1::phaser1(), Proto40MHz_v1::phaser2(), A3PE::pipeline(), UsbFTInterface::read(), A3PE::readPatternFifoUsb(), A3PE::readToAXRamUsb(), A3PE::readTriggerFifoUsb(), A3PE::reset(), A3PE::resetFE(), A3PE::resetFromAXRam(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetReg(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), A3PE::resetUsbPhasers(), UsbFTInterface::rxBuffer(), UsbFTInterface::rxTimeOut(), Acquisition::sample(), UsbFTInterface::serialNum(), A3PE::setAddFromAXRam(), UsbFTInterfaceTest::setAddress(), A3PE::setAddToAXRam(), UsbFTInterface::setBuffer(), Acquisition::setChannels(), A3PE::setClockDivision(), Acquisition::setDeadTime(), Acquisition::setDepth(), UsbFTInterface::setDeviceDesc(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE_BitFlip::setFile(), A3PE::setInternalAXSequence(), A3PE::setLatencyAX(), UsbFTInterface::setLatencyTimer(), A3PE::setLengthAX(), Acquisition::setMaxRange(), Acquisition::setMinRange(), Acquisition::setNBins(), A3PE::setNTrigger(), UsbFTInterfaceTest::setParam(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), Acquisition::setSample(), UsbFTInterface::setSerialNum(), A3PE::setSoftwareTrigger(), Acquisition::setStoreSample(), Acquisition::setStoreTree(), Acquisition::setStoreTrend(), UsbFTInterface::setTimeOut(), Acquisition::setTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setupReg(), UsbFTInterface::setWordSize(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), UsbFTInterfaceTest::sigma(), A3PE::softwareTrigger(), A3PE::spare3Reg(), A3PE::startSequenceAX(), A3PE::statusReg(), A3PE::storageRam(), Acquisition::storeSample(), Acquisition::storeTree(), Acquisition::storeTrend(), A3PE::testRam(), A3PE::toAXRam(), A3PE::toAXReg(), Acquisition::trigger(), A3PE::trigger(), A3PE::triggerDelay(), A3PE::triggerRam(), A3PE::triggerRate(), A3PE::triggerReg(), UsbFTInterface::txBuffer(), UsbFTInterface::txTimeOut(), Proto40MHz_v1::usb(), UsbFTInterface::wordSize(), UsbFTInterface::write(), A3PE::writeFromAXRamUsb(), A3PE::writeLengthFifoReg(), A3PE::writeStorageFifoUsb(), UsbFTInterface::WS_Byte, UsbFTInterface::WS_DWord, and UsbFTInterface::WS_Word.
  class_<A3PE, bases <Element> >("A3PE")
    .def("ctrlReg" ,&A3PE::ctrlReg,return_value_policy<reference_existing_obje
      ct>())
    .def("resetReg" ,&A3PE::resetReg,return_value_policy<reference_existing_ob
      ject>())
    .def("setupReg" ,&A3PE::setupReg,return_value_policy<reference_existing_ob
      ject>())
    .def("statusReg" ,&A3PE::statusReg,return_value_policy<reference_existing_
      object>())
    .def("acqReg" ,&A3PE::acqReg,return_value_policy<reference_existing_object
      >())
    .def("latencyReg" ,&A3PE::acqReg,return_value_policy<reference_existing_ob
      ject>())
    .def("writeLengthFifoReg" ,&A3PE::writeLengthFifoReg,return_value_policy<r
      eference_existing_object>())
    .def("ctrlAnaMezzReg" ,&A3PE::ctrlAnaMezzReg,return_value_policy<reference
      _existing_object>())
    .def("clockDivisionReg" ,&A3PE::clockDivisionReg,return_value_policy<referen
      ce_existing_object>())
    .def("triggerReg" ,&A3PE::triggerReg,return_value_policy<reference_existing_
      object>())
    .def("toAXReg" ,&A3PE::toAXReg,return_value_policy<reference_existing_object
      >())
    .def("fromAXReg" ,&A3PE::fromAXReg,return_value_policy<reference_existing_ob
      ject>())
    .def("spare3Reg" ,&A3PE::spare3Reg,return_value_policy<reference_existing_ob
      ject>())
    .def("storageRam" ,&A3PE::storageRam,return_value_policy<reference_existing
      _object>())
    .def("patternRam" ,&A3PE::patternRam,return_value_policy<reference_existing
      _object>())
    .def("triggerRam" ,&A3PE::triggerRam,return_value_policy<reference_existing
      _object>())
    .def("toAXRam" ,&A3PE::toAXRam,return_value_policy<reference_existing_ob
      ject>())
    .def("fromAXRam" ,&A3PE::fromAXRam,return_value_policy<reference_existing_
      object>())
    .def("testRam" ,&A3PE::testRam,return_value_policy<reference_existing_obje
      ct>())
    .def("reset" ,&A3PE::reset)
    .def("resetStorageFifo" ,&A3PE::resetStorageFifo)
    .def("resetTriggerFifo" ,&A3PE::resetTriggerFifo)
    .def("resetPatternFifo" ,&A3PE::resetPatternFifo)
    .def("resetFromAXRam" ,&A3PE::resetFromAXRam)
    .def("resetToAXRam" ,&A3PE::resetToAXRam)
    .def("resetSequenceFromToAX" ,&A3PE::resetSequenceFromToAX)
    .def("resetUsbPhasers" ,&A3PE::resetUsbPhasers)
    .def("resetLatencyCounter" ,&A3PE::resetLatencyCounter)
    .def("resetFE" ,&A3PE::resetFE)
    .def("resetSPI" ,&A3PE::resetSPI)
    .def("setEnableADC" ,&A3PE::setEnableADC)
    .def("enableADC" ,&A3PE::enableADC)
    .def("setWriteStorageFifoUsb" ,&A3PE::setWriteStorageFifoUsb)
    .def("writeStorageFifoUsb" ,&A3PE::writeStorageFifoUsb)
    .def("setReadPatternFifoUsb" ,&A3PE::setReadPatternFifoUsb)
    .def("readPatternFifoUsb" ,&A3PE::readPatternFifoUsb)
    .def("setReadTriggerFifoUsb" ,&A3PE::setReadTriggerFifoUsb)
    .def("readTriggerFifoUsb" ,&A3PE::readTriggerFifoUsb)
    .def("setReadToAXRamUsb" ,&A3PE::setReadToAXRamUsb)
    .def("readToAXRamUsb" ,&A3PE::readToAXRamUsb)
    .def("setWriteFromAXRamUsb" ,&A3PE::setWriteFromAXRamUsb)
    .def("writeFromAXRamUsb" ,&A3PE::writeFromAXRamUsb)
    .def("setSoftwareTrigger" ,&A3PE::setSoftwareTrigger)
    .def("softwareTrigger" ,&A3PE::softwareTrigger)
    .def("setClockDivision" ,&A3PE::setClockDivision)
    .def("clockDivision" ,&A3PE::clockDivision)
    .def("setTriggerDelay" ,&A3PE::setTriggerDelay)
    // .def("setSeqPulseDelay" ,&A3PE::setSeqPulseDelay)
    .def("triggerDelay" ,&A3PE::triggerDelay)
    // .def("seqPulseDelay" ,&A3PE::seqPulseDelay)
    .def("setTriggerRate" ,&A3PE::setTriggerRate)
    .def("triggerRate" ,&A3PE::triggerRate)
    .def("setNTrigger" ,&A3PE::setNTrigger)
    .def("nTrigger" ,&A3PE::nTrigger)
    .def("setFifoLatency" ,&A3PE::setFifoLatency)
    .def("fifoLatency" ,&A3PE::fifoLatency)
    .def("setFifoDepth", &A3PE::setFifoDepth)
    .def("fifoDepth", &A3PE::fifoDepth)
    .def("acquisition", &A3PE::acquisition)
    .def("trigger", &A3PE::trigger)
    .def("enableStorage", &A3PE::enableStorage)
    .def("dataReady", &A3PE::dataReady)
    .def("dumpStorage", &A3PE::dumpStorage)
    .def("dumpPattern", &A3PE::dumpPattern)
    .def("dumpTrigger", &A3PE::dumpTrigger)
    .def("dumpToAX", &A3PE::dumpToAX)
    .def("dumpFromAX", &A3PE::dumpFromAX)
    .def("loadStorage", &A3PE::loadStorage)
    .def("loadPattern", &A3PE::loadPattern)
    .def("loadTrigger", &A3PE::loadTrigger)
    .def("loadToAX", &A3PE::loadToAX)
    .def("loadFromAX", &A3PE::loadFromAX)
    .def("setInternalAXSequence", &A3PE::setInternalAXSequence)
    .def("internalAXSequence", &A3PE::internalAXSequence)
    .def("setLengthAX", &A3PE::setLengthAX)
    .def("lengthAX", &A3PE::lengthAX)
    .def("setLatencyAX", &A3PE::setLatencyAX)
    .def("latencyAX", &A3PE::latencyAX)
    .def("setAddFromAXRam", &A3PE::setAddFromAXRam)
    .def("setAddToAXRam", &A3PE::setAddToAXRam)
    .def("startSequenceAX", &A3PE::startSequenceAX)
    .def("setPipeline", &A3PE::setPipeline)
    .def("pipeline", &A3PE::pipeline)
    ;
  class_<Proto40MHz_v1, bases <Element> >("Proto40MHz_v1")
    .def("usb",&Proto40MHz_v1::usb,return_value_policy<reference_existing_object>
      ())
    .def("phaser0",&Proto40MHz_v1::phaser0,return_value_policy<reference_existing
      _object>())
    .def("phaser1",&Proto40MHz_v1::phaser1,return_value_policy<reference_existing
      _object>())
    .def("phaser2",&Proto40MHz_v1::phaser2,return_value_policy<reference_existing
      _object>())
    .def("a3pe", &Proto40MHz_v1::a3pe,return_value_policy<reference_existing_ob
      ject>())
  ;
  class_<Acquisition,bases <Processus> >("Acquisition")
    .def("initialize",&Acquisition::initialize)
    .def("execute",&Acquisition::execute)
    .def("finalize",&Acquisition::finalize)
    .def("setDepth",&Acquisition::setDepth)
    .def("depth",&Acquisition::depth)
    .def("setChannels",&Acquisition::setChannels)
    .def("channels",&Acquisition::channels)
    .def("setTrigger",&Acquisition::setTrigger)
    .def("trigger",&Acquisition::trigger)
    .def("setStoreTree",&Acquisition::setStoreTree)
    .def("setStoreTrend",&Acquisition::setStoreTrend)
    .def("setStoreSample",&Acquisition::setStoreSample)
    .def("storeTree",&Acquisition::storeTree)
    .def("storeTrend",&Acquisition::storeTrend)
    .def("storeSample",&Acquisition::storeSample)
    .def("setDeadTime",&Acquisition::setDeadTime)
    .def("deadTime",&Acquisition::deadTime)
    .def("setSample",&Acquisition::setSample)
    .def("sample",&Acquisition::sample)
    .def("setNBins",&Acquisition::setNBins)
    .def("nBins",&Acquisition::nBins)
    .def("setMinRange",&Acquisition::setMinRange)
    .def("minRange",&Acquisition::minRange)
    .def("setMaxRange",&Acquisition::setMaxRange)
    .def("maxRange",&Acquisition::maxRange)
    ;
  class_<A3PE_BitFlip,bases <Processus> >("A3PE_BitFlip")
    .def("initialize",&A3PE_BitFlip::initialize)
    .def("execute",&A3PE_BitFlip::execute)
    .def("finalize",&A3PE_BitFlip::finalize)
    .def("setFile",&A3PE_BitFlip::setFile)
    .def("file",&A3PE_BitFlip::file)
    ;
  enum_<UsbFTInterface::WordSize>("WordSize")
    .value("U8", UsbFTInterface::WS_Byte)
    .value("U16", UsbFTInterface::WS_Word)
    .value("U32", UsbFTInterface::WS_DWord)
    ;
  StatusCode (UsbFTInterface::*write_1)(unsigned long int, boost::python::list) =
       (&UsbFTInterface::write);
  StatusCode (UsbFTInterface::*write_2)(IOdata*) = (&UsbFTInterface::write);
  StatusCode (UsbFTInterface::*read_1)(unsigned long int,unsigned long int, boost
      ::python::list&) = (&UsbFTInterface::read);
  StatusCode (UsbFTInterface::*read_2)(IOdata*) = (&UsbFTInterface::read);
  class_<UsbFTInterface, bases <Element> > ("UsbFTInterface")
    .def("init" ,&UsbFTInterface::init)
    .def("setSerialNum" ,&UsbFTInterface::setSerialNum)
    .def("setDeviceDesc" ,&UsbFTInterface::setDeviceDesc)
    .def("serialNum" ,&UsbFTInterface::serialNum)
    .def("deviceDesc" ,&UsbFTInterface::deviceDesc)
    .def("setWordSize" ,&UsbFTInterface::setWordSize)
    .def("wordSize" ,&UsbFTInterface::wordSize)
    .def("close" ,&UsbFTInterface::close)
    .def("setLatencyTimer",&UsbFTInterface::setLatencyTimer)
    .def("latencyTimer" ,&UsbFTInterface::latencyTimer)
    .def("setTimeOut" ,&UsbFTInterface::setTimeOut)
    .def("txTimeOut" ,&UsbFTInterface::txTimeOut)
    .def("rxTimeOut" ,&UsbFTInterface::rxTimeOut)
    .def("setBuffer" ,&UsbFTInterface::setBuffer)
    .def("txBuffer" ,&UsbFTInterface::txBuffer)
    .def("rxBuffer" ,&UsbFTInterface::rxBuffer)
    .def("write" ,write_1)
    .def("write" ,write_2)
    .def("read" ,read_1)
    .def("read" ,read_2)
    ;
  class_<UsbFTInterfaceTest, bases<Processus> > ("UsbFTInterfaceTest")
    .def("setAddress", &UsbFTInterfaceTest::setAddress)
    .def("setParam", &UsbFTInterfaceTest::setParam)
    .def("mean", &UsbFTInterfaceTest::mean)
    .def("sigma", &UsbFTInterfaceTest::sigma)
    ;
  class_<RegisterTest, bases<Processus> > ("RegisterTest")
    .def("setAddress", &UsbFTInterfaceTest::setAddress)
    .def("setParam", &UsbFTInterfaceTest::setParam)
    .def("mean", &UsbFTInterfaceTest::mean)
    .def("sigma", &UsbFTInterfaceTest::sigma)
    ;