/home/eleclhcb/LHCb/lbcat-cmake/CatNI/src/Python.cpp File Reference
#include <vector>
#include <list>
#include `Processus.h`
#include `NI6008.h`
#include `CurrentMeasurement.h`
#include `ADCMeasurement.h`
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
Functions
BOOST_PYTHON_MODULE (libCatNI)
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (libCatNI)
Definition at line 14 of file Python.cpp.
References NI6008::addDevice(), NI6008::clearDevice(), NI6008::cmd(), NI6008::device(), ADCMeasurement::frequency(), CurrentMeasurement::frequency(), NI6008::help(), NI6008::hostname(), NI6008::init(), CurrentMeasurement::numberOfDevices(), NI6008::numberOfDevices(), NI6008::port(), NI6008::reset(), ADCMeasurement::setFrequency(), CurrentMeasurement::setFrequency(), NI6008::setHostname(), NI6008::setPort(), and NI6008::update().
{
// def("createTask", DAQmxBaseCreateTask);
// int32 (createTask)(TaskHandle) (int32) = (&DAQmxBaseCreateTask);
  class_<NI6008, bases <Element> >("NI6008")
    .def("help" ,&NI6008::help)
    .def("init" ,&NI6008::init)
    .def("reset" ,&NI6008::reset)
    .def("update" ,&NI6008::update)
    .def("setPort" ,&NI6008::setPort)
    .def("port" ,&NI6008::port)
    .def("addDevice", &NI6008::addDevice)
    .def("device", &NI6008::device) //
      ,return_value_policy<reference_existing_object>())
    .def("numberOfDevices",&NI6008::numberOfDevices)
    .def("clearDevice", &NI6008::clearDevice)
    // .def("setDevice" ,&NI6008::setDevice)
    // .def("device" ,&NI6008::device)
    .def("setHostname" ,&NI6008::setHostname)
    .def("hostname" ,&NI6008::hostname)
    .def("cmd" ,&NI6008::cmd)
    // .def("ai" ,&NI6008::ai)
    // .def("di" ,&NI6008::di)
    ;
  class_<CurrentMeasurement, bases<Processus> > ("CurrentMeasurement")
    // .def("addDevice", &CurrentMeasurement::addDevice)
    // .def("device", &CurrentMeasurement::device,return_value_policy<reference_existing_object>())
    .def("numberOfDevices", &CurrentMeasurement::numberOfDevices)
    // .def("clearDevice", &CurrentMeasurement::clearDevice)
    .def("setFrequency", &CurrentMeasurement::setFrequency)
    .def("frequency", &CurrentMeasurement::frequency)
    ;
  class_<ADCMeasurement, bases<Processus> > ("ADCMeasurement")
    // .def("addDevice", &ADCMeasurement::addDevice)
    // .def("device", &ADCMeasurement::device,return_value_policy<reference_existing_object>())
    //.def("numberOfDevices",&ADCMeasurement::numberOfDevices)
    // .def("clearDevice", &ADCMeasurement::clearDevice)
    .def("setFrequency", &ADCMeasurement::setFrequency)
    .def("frequency", &ADCMeasurement::frequency)
    ;
}