/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/src/Python.cpp File Reference
#include <vector>
#include <list>
#include `Element.h`
#include `Interface.h`
#include `SpecsInterface.h`
#include `SpecsParallelBus.h`
#include `SpecsI2c.h`
#include `SpecsBus.h`
#include `SpecsMaster.h`
#include `SpecsSlave.h`
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
Functions
BOOST_PYTHON_MODULE (libCatSpecs)
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (libCatSpecs)
Definition at line 21 of file Python.cpp.
References SpecsSlave::addI2c(), SpecsInterface::address(), SpecsSlave::detect(), SpecsMaster::help(), SpecsInterface::help(), SpecsSlave::init(), SpecsMaster::init(), SpecsInterface::init(), SpecsMaster::masterDevID(), SpecsInterface::outputSelect(), SpecsMaster::pciDevID(), SpecsMaster::reset(), SpecsInterface::reset(), SpecsSlave::resetInternal(), SpecsSlave::setAddress(), SpecsInterface::setAddress(), SpecsMaster::setMasterDevID(), SpecsInterface::setOutputSelect(), SpecsMaster::setPciDevID(), SpecsMaster::setSpeed(), SpecsInterface::specsMaster(), SpecsInterface::specsSlave(), SpecsMaster::speed(), SpecsMaster::update(), and SpecsInterface::update().
{
  class_<SpecsMaster, bases <Element> >("SpecsMaster")
    .def("setPciDevID",&SpecsMaster::setPciDevID)
    .def("pciDevID", &SpecsMaster::pciDevID)
    .def("setMasterDevID",&SpecsMaster::setMasterDevID)
    .def("masterDevID",&SpecsMaster::masterDevID)
    .def("setSpeed",&SpecsMaster::setSpeed)
    .def("speed",&SpecsMaster::speed)
    .def("help",&SpecsMaster::help)
    .def("init",&SpecsMaster::init)
    .def("reset",&SpecsMaster::reset)
    .def("update",&SpecsMaster::update)
    ;
  class_<SpecsInterface, bases <Interface> >("SpecsInterface")
    .def("help", &SpecsInterface::help)
    .def("init", &SpecsInterface::init)
    .def("reset", &SpecsInterface::reset)
    .def("update",&SpecsInterface::update)
    .def("setAddress",&SpecsInterface::setAddress)
    .def("address", &SpecsInterface::address)
    .def("setOutputSelect",&SpecsInterface::setOutputSelect)
    .def("outputSelect", &SpecsInterface::outputSelect)
    .def("specsMaster", &SpecsInterface::specsMaster,
         return_value_policy<reference_existing_object>())
    .def("specsSlave", &SpecsInterface::specsSlave
         ,return_value_policy<reference_existing_object>())
    ;
  
  // class_<SpecsParallelBus, bases <SpecsInterface> >("SpecsParallelBus")
  // ;
    // class_<SpecsI2c, bases <SpecsInterface> >("SpecsI2c")
  // ;
  class_<SpecsSlave, bases <SpecsInterface> >("SpecsSlave")
    .def("setAddress",&SpecsSlave::setAddress)
    .def("addI2c",&SpecsSlave::addI2c)
    .def("detect",&SpecsSlave::detect)
    .def("init",&SpecsSlave::init)
    .def("resetInternal",&SpecsSlave::resetInternal)
    ;
}