Application Class Reference
#include <Application.h>
Public Types
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
Application ()
Standard constructor.
virtual ~Application ()
Destructor.
StatusCode initialize ()
StatusCode run (std::string procName, Element *element=0, int nEvt=1)
StatusCode finalize ()
Options * options ()
Computer * computer ()
DLLMgr * dllMgr ()
ProcDataBase * procDb ()
StatusCode loadHistoryFile ()
StatusCode bookkeeping ()
void banner ()
void exit ()
void setCurrent (Hierarchy *current)
Hierarchy * current ()
StatusCode cd (std::string path)
std::string hostname ()
void treeRecursive (Hierarchy *, std::string)
StatusCode create (std::string, std::string)
StatusCode makeDir (std::string)
State * state ()
Config * config ()
void setState (std::string state=std::string(``))
void setConfig ()
char * status ()
void network (std::string)
void server ()
void setProcessus (Processus *processus)
Processus * processus ()
StatusCode runSvc ()
void setRunSvc (RunSvc svc)
StatusCode plotSvc ()
void setPlotSvc (PlotSvc svc)
void setVersion (std::string version)
std::string version ()
void setCtrl (std::string control)
std::string ctrl ()
StatusCode svcRunning ()
StatusCode prepare (std::string procName, Element *element=0, int nEvt=1)
StatusCode loop ()
StatusCode terminate ()
StatusCode svcPlot ()
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
std::string m_accountName
std::string m_hostName
std::string m_osName
std::string m_osVersion
std::string m_prompt
std::string m_version
bool m_isRunning
Hierarchy * m_current
std::string m_attribString [10]
Private Attributes
Options * m_options
DLLMgr * m_dllMgr
ProcDataBase * m_procDb
Computer * m_computer
Processus * m_processus
State * m_state
Config * m_config
RunSvc m_runSvc
PlotSvc m_plotSvc
Server * m_server
bool m_network
std::string m_ctrl
Detailed Description
Application main class
Author
Frederic Machefert
Date
2006-10-23
Definition at line 58 of file Application.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
Constructor & Destructor Documentation
Application()
Application::Application ()
Standard constructor.
Definition at line 29 of file Application.cpp.
References System::accountName(), System::hostName(), m_accountName, m_computer, m_config, m_dllMgr, m_hostName, m_options, m_osName, m_osVersion, m_procDb, m_state, System::osName(), System::osVersion(), setApplication(), and setCurrent().
                           :
  m_options (0),
  m_dllMgr (0),
  m_procDb (0),
  m_computer (0),
  m_processus(0),
  m_state (0),
  m_config (0),
  m_server (0)
{
  setApplication(this);
  m_options = new Options ();
  m_accountName = System::accountName();
  m_hostName = System::hostName();
  m_osName = System::osName();
  m_osVersion = System::osVersion();
  m_dllMgr = new DLLMgr ();
  m_procDb = new ProcDataBase ();
  m_computer = new Computer ();
  m_state = new State();
  m_config = new Config();
  setCurrent ((Hierarchy*) (m_computer));
}
 Application()
Application::~Application () [virtual]
Destructor.
Definition at line 56 of file Application.cpp.
References m_config, m_dllMgr, m_options, m_procDb, m_server, and m_state.
                          {
  if (0!=m_server) {
    delete m_server;
    m_server = 0;
  }
  delete m_state;
  delete m_config;
  delete m_options;
  delete m_dllMgr;
  delete m_procDb;
  // delete m_computer;
}
Member Function Documentation
add()
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), TestI2C::setAddress(), TestSPI::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
banner()
void Application::banner ()
Banner of the Application
Definition at line 103 of file Application.cpp.
References m_accountName, m_hostName, m_osName, m_osVersion, and Object::msgSvc().
Referenced by initialize().
                           {
#ifdef _WIN32
  // system("cls");
#else
  // system("clear");
#endif
  msgSvc(0,"","");
  msgSvc(0," ***********************************************","");
  msgSvc(0," * C A T *","");
  msgSvc(0," * *","");
  msgSvc(0," * |\\-''-/|.___..--''\"`-._ *","");
  msgSvc(0," * `6_ 6) `-. ().`-.__.`) *","");
  msgSvc(0," * (_Y_.)' ._) `._ `. ``-..-' *","");
  msgSvc(0," * _..`--'_..- _/ /--'_.' ,' *","");
  msgSvc(0," * (il),-'' (li),' ((!.-' *","");
  msgSvc(0," ***********************************************","");
  msgSvc(0,"","");
  msgSvc(0,"Application running on "+
     m_accountName+"@"+
     m_hostName+" ("+
     m_osName+" - "+
     m_osVersion+")","");
}
bookkeeping()
StatusCode Application::bookkeeping ()
write bookkeeping file
Returns
StatusCode
Definition at line 170 of file Application.cpp.
References application(), StatusCode::FAILURE, System::getEnv(), options(), Options::runNumber(), StatusCode::SUCCESS, and Object::warning().
Referenced by prepare().
                                      {
  std::string filename = System::getEnv("CATPATH");
  filename.append("/.cathist");
  std::ofstream last;
  last.open(filename.c_str());
  if (last.fail()) {
    warning("Cannot do the bookkeeping","Application::bookkeeping");
    return StatusCode::FAILURE;
  }
  else {
    last << application()->options()->runNumber();
  }
  last.close();
  return StatusCode::SUCCESS;
}
cd()
StatusCode Application::cd (std::string path) [inline]
Definition at line 158 of file Application.h.
References Hierarchy::child(), StatusCode::FAILURE, and StatusCode::SUCCESS.
Referenced by export_obj().
                                 {
    Hierarchy* newcurrent = m_current->child(path);
    if (0!=newcurrent) {
      setCurrent(newcurrent);
      return StatusCode::SUCCESS;
    }
    else {
      return StatusCode::FAILURE;
    }
  }
computer()
Computer* Application::computer () [inline]
Get accessor to member m_computer
Returns
the current value of m_computer
Definition at line 94 of file Application.h.
Referenced by export_obj().
                        {
    // info("Computer"+ itos((int)(m_computer)));
    return m_computer;
  }
config()
Config * Application::config ()
return current Application State
Definition at line 214 of file Application.cpp.
References m_config.
Referenced by Server::start().
                              {
  return m_config;
}
create()
StatusCode Application::create (std::string name, std::string type)
Definition at line 326 of file Application.cpp.
References Hierarchy::addChild(), DLLMgr::createElement(), StatusCode::FAILURE, m_current, m_dllMgr, shell::obj(), setCurrent(), Object::setName(), Hierarchy::setParent(), StatusCode::SUCCESS, and Object::warning().
Referenced by export_obj().
{
  Element *obj = m_dllMgr->createElement(type);
  if (!obj) {
    warning("Type '" + type + "' not understood");
    return StatusCode::FAILURE;
  }
  obj->setName(name);
  obj->setParent(m_current);
  m_current->addChild(obj);
  setCurrent(obj);
  return StatusCode::SUCCESS;
}
ctrl()
std::string Application::ctrl () [inline]
Definition at line 314 of file Application.h.
Referenced by export_obj(), and svcRunning().
                   {
    return m_ctrl;
  }
current()
Hierarchy* Application::current () [inline]
Get accessor to member m_current
Returns
the current value of m_current
Definition at line 149 of file Application.h.
Referenced by export_obj(), and setConfig().
                        {
    return m_current;
  }
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), A3PE::internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), CU_v1::reset(), FEB_v1::reset(), Proto40MHz_v1::reset(), SpecsMaster::reset(), SpecsSlave::reset(), FEB_v1::resetUsb(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
dllMgr()
DLLMgr* Application::dllMgr () [inline]
Get accessor to member m_dllMgr
Returns
the current value of m_dllMgr
Definition at line 103 of file Application.h.
Referenced by export_obj().
                    {
    return m_dllMgr;
  }
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
exit()
void Application::exit ()
exit the Application
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
finalize()
StatusCode Application::finalize ()
Finalize the application
Definition at line 142 of file Application.cpp.
References StatusCode::SUCCESS.
Referenced by export_obj().
                                   {
  return StatusCode::SUCCESS;
}
hostname()
std::string Application::hostname () [inline]
get the hostname of the computer
Definition at line 173 of file Application.h.
References shell::create().
Referenced by export_obj(), initialize(), and NI6008::NI6008().
                      {
    return m_hostName;
  }
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTInterface::close(), UsbFTMLInterface::close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), UsbFTMLInterface::help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), MSOxxxx::id(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), loop(), FEB_v1::maskLLT(), network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbI2cBus::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), FePGA::reset(), SeqPGA::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), FEB_v1::resetFifoSpyFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), SeqPGA::resetUsb(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), svcRunning(), terminate(), FEB_v1::testDuration(), SeqPGA::testSequence(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
initialize()
StatusCode Application::initialize ()
Initialize the Application
Definition at line 72 of file Application.cpp.
References Attrib::add(), banner(), hostname(), loadHistoryFile(), m_config, m_ctrl, m_network, m_server, m_state, setConfig(), Object::setName(), setState(), Object::setType(), Attrib::SOFTWARE, and StatusCode::SUCCESS.
Referenced by export_obj().
                                     {
  setType("SOFTWARE");
  add(Attrib::SOFTWARE);
  setName (hostname());
  m_network=false;
  m_server=0;
  m_ctrl=std::string("");
  m_state = new State();
  m_config = new Config();
  /*
    setRunSvc (*svcRunning);
    setPlotSvc (*svcPlot);
  */
  setState ("READY");
  setConfig();
  banner ();
  loadHistoryFile();
  return StatusCode::SUCCESS;
}
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
loadHistoryFile()
StatusCode Application::loadHistoryFile ()
Load History file if it exists
Returns
StatusCode
Definition at line 149 of file Application.cpp.
References application(), StatusCode::FAILURE, System::getEnv(), Object::info(), itos(), options(), Options::setRunNumber(), and StatusCode::SUCCESS.
Referenced by initialize().
                                       {
  // Load last session parameters
  std::string filename = System::getEnv("CATPATH");
  filename.append("/.cathist");
  std::ifstream last;
  last.open(filename.c_str());
  if (!last.fail()) {
    int nrun;
    last >> nrun;
    info("Recovering last run number : "+itos(nrun)+". Will start from "+
      itos(nrun+1)+".","Application:loadHistoryFile");
    application()->options()->setRunNumber(nrun+1);
  }
  else {
    info("No history file found.","Application:loadHistoryFile");
    return StatusCode::FAILURE;
  }
  last.close();
  return StatusCode::SUCCESS;
}
loop()
StatusCode Application::loop ()
Definition at line 460 of file Application.cpp.
References Processus::execute(), StatusCode::FAILURE, Options::incNErrors(), Options::incNEvt(), Object::info(), itos(), m_options, m_processus, Options::nErrors(), State::nEvent, Options::nEvt(), Options::printFreq(), state(), Options::stopOnError(), StatusCode::SUCCESS, and Object::warning().
Referenced by export_obj(), and svcRunning().
                               {
  m_options->incNEvt();
  unsigned long currentNEvt = m_options->nEvt();
  state()->nEvent++;
  if(m_options->printFreq()>0) {
    if (0 == currentNEvt % m_options->printFreq()) {
      info("[Processing evt "+itos(currentNEvt)+"]","Application::loop");
    }
  }
  if ((m_processus->execute()).isFailure()) {
    warning("An Error occured ["+itos(m_options->nErrors())+"].","
      Application::loop");
    m_options->incNErrors();
    if (m_options->stopOnError()) {
      warning("Program automatically Stopped after " +
          itos (currentNEvt) + " event(s).","Application::loop");
      // m_options->setNEvt(m_options->nEvtMax());
      return StatusCode::FAILURE;
    }
  }
  return StatusCode::SUCCESS;
}
makeDir()
StatusCode Application::makeDir (std::string directory)
Definition at line 189 of file Application.cpp.
References StatusCode::FAILURE, StatusCode::SUCCESS, and Object::warning().
Referenced by prepare().
                                                     {
  if (mkdir(directory.c_str(), 0777) == -1) { // Create the directory
    warning("Could not create directory "+directory+". Error "+strerror(errno),"Application:makeDir"
      );
    return(StatusCode::FAILURE);
  }
  return StatusCode::SUCCESS;
}
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), UsbFTInterface::help(), UsbFTMLInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), Data::hist2d(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), UsbSpiBus::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), SpecsSlave::resetInternal(), FEB_v1::resetUsb(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), Object::setName(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
network()
void Application::network (std::string name = std::string(``))
Definition at line 282 of file Application.cpp.
References application(), Object::info(), m_network, m_server, Object::name(), setConfig(), Object::setName(), setState(), and Server::start().
                                                          {
  if (name.compare("")==0) {
    application()->setName (name);
  }
  if (!m_network) {
    m_network = true;
    m_server = new Server (this);
    m_server->start();
    if (m_network) {
      info("Update server information.","Application::network");
      setConfig ();
      setState ("READY");
    }
  }
  else {
    info("Stop network connection.","Application::network");
    m_network = false;
    delete m_server;
    m_server = 0;
  }
}
options()
Options* Application::options () [inline]
Get accessor to member m_options
Returns
the current value of m_options
Definition at line 86 of file Application.h.
Referenced by bookkeeping(), Acquisition::execute(), ADCMeasurement::execute(), CurrentMeasurement::execute(), export_obj(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), loadHistoryFile(), and MsgSvc::msgSvc().
                      {
    return m_options;
  }
plotSvc()
StatusCode Application::plotSvc () [inline]
Execute plot service
Returns
the result
Definition at line 273 of file Application.h.
                        {
    PlotSvc svc = m_plotSvc;
    return svc();
  }
prepare()
StatusCode Application::prepare (std::string procName, Element * element = 0, int nEvt = 1)
Definition at line 393 of file Application.cpp.
References bookkeeping(), Processus::clean(), Processus::clone(), Options::dataStorage(), StatusCode::FAILURE, Options::logStorage(), m_current, m_options, m_processus, makeDir(), procDb(), shell::process(), ProcDataBase::procList(), Processus::setElement(), Options::setNErrors(), Options::setNEvt(), Options::setNEvtMax(), setState(), Options::setStorageFile(), Options::setStream(), Options::setTimeMax(), Processus::startProcessing(), Processus::storage(), Options::storageFile(), Options::storageFullPath(), StatusCode::SUCCESS, Object::verbose(), and Object::warning().
Referenced by export_obj(), and run().
                                               {
  verbose("Prepare for a new run.","Application::prepare");
  if (0==element) element = dynamic_cast<Element*>(m_current);
  std::list<Processus*> listproc = procDb()->procList (element);
  std::list<Processus*>::iterator proc;
  Processus *process = 0;
  for (proc=listproc.begin(); proc!=listproc.end(); ++proc) {
    if (procName.compare((*proc)->name()) == 0) {
      process = (*proc)->clone();
      //--------------------
      // Did not chose to make copies : use original processus !
      // info("orig="+itos((int)(*proc)));
      // process = (*proc)->clone();
      // info("orig="+itos((int)(process)));
      break;
    }
  }
  if (0==process) {
    warning("Processus " + procName + " not found.","Application::prepare");
    setState ("READY");
    return StatusCode::FAILURE;
  }
  if (0!=m_processus) {
    m_processus->clean();
    //--------------------
    // did not chose to make copies
    // delete m_processus;
  }
  m_processus = process;
  m_options->setNErrors (0);
  m_options->setNEvt (0);
  // unsigned long currentNEvtMax = m_options->nEvtMax();
  m_options->setNEvtMax (nEvent);
  if (nEvent<0) {
    m_options->setTimeMax(int(((double)(CLOCKS_PER_SEC))/1.e11*(clock()-nEvent)));
    // info("Time max is ", itos(m_options->timeMax()));
  }
  bookkeeping();
  if (m_options->dataStorage() || m_options->
      logStorage()) {
    if (makeDir(m_options->storageFullPath()).isFailure()) {
      warning("Could not create storage directory "+m_options->
      storageFullPath(),"Application::prepare");
      return StatusCode::FAILURE;
    }
  }
  if (m_options->dataStorage() || m_options->
      logStorage()) {
    m_options->setStorageFile (m_processus->
      storage());
    if (m_options->logStorage()) {m_options->
      setStream(m_options->storageFile()); }
  }
  m_processus->setElement(element);
  if ((m_processus->startProcessing()).isFailure()) {
    warning("Program initialization interrupted.","Application::prepare");
    return StatusCode::FAILURE;
  }
  setState ("RUNNING");
  return StatusCode::SUCCESS;
}
procDb()
ProcDataBase* Application::procDb () [inline]
Get accessor to member m_procDb
Returns
the current value of m_procDb
Definition at line 111 of file Application.h.
Referenced by Computer::Computer(), export_obj(), DLL::init(), prepare(), DLL::print(), setConfig(), Server::start(), and Computer::~Computer().
                          {
    return m_procDb;
  }
processus()
Processus* Application::processus () [inline]
Get accessor to member m_processus
Returns
the current value of m_processus
Definition at line 248 of file Application.h.
                          {
    return m_processus;
  }
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
run()
StatusCode Application::run (std::string procName, Element * element = 0, int nEvt = 1)
Execute the Application
Definition at line 130 of file Application.cpp.
References StatusCode::FAILURE, prepare(), status(), svcRunning(), and terminate().
Referenced by export_obj().
                                           {
  if (prepare(procName, element, nEvent).isFailure()) return
      StatusCode::FAILURE;
  StatusCode status = svcRunning();
  if (terminate().isFailure()) return StatusCode::FAILURE;
  return status;
}
runSvc()
StatusCode Application::runSvc () [inline]
Execute processing service
Returns
the result of the processing
Definition at line 256 of file Application.h.
                       {
    RunSvc svc = m_runSvc;
    return svc();
  }
server()
void Application::server ()
Definition at line 308 of file Application.cpp.
References Object::info(), m_server, setConfig(), setState(), and Server::start().
                            {
  if (0 != m_server) {
    info("Delete CAT server.","Application::server");
    delete m_server;
    m_server = 0;
  }
  else {
    m_server = new Server (this);
    m_server->start();
    info("Update server information.","Application::server");
    setConfig ();
    setState ();
  }
}
setConfig()
void Application::setConfig ()
Set accessor to member m_config and perform network publication
Definition at line 236 of file Application.cpp.
References Hierarchy::children(), Config::config, current(), m_config, m_current, m_server, Object::name(), procDb(), ProcDataBase::procList(), Object::type(), Server::updateConfig(), and Object::warning().
Referenced by initialize(), network(), and server().
                             {
  if (0 != m_server) {
    // current element
    Element* element=dynamic_cast<Element*>(m_current);
    if (0==element)
      {
    warning("Cannot find the Element at the current position of the Hierarchy",
        "Application::setConfig");
      }
    std::string current=m_current->name();
    current.append("[");
    current.append(m_current->type());
    current.append("] ");
    // strcpy(m_config->currentElement,current.c_str());
    // reachable processus list
    std::list<Processus*> listproc = procDb()->procList (element);
    std::list<Processus*>::iterator proc;
    for (proc=listproc.begin(); proc!=listproc.end(); ++proc) {
      if (proc!=listproc.begin()) { current.append(":"); }
      current.append((*proc)->name());
    }
    current.append(" ");
    // strcpy(m_config->procList,process.c_str());
    // list of children
    std::vector<Hierarchy*> list = m_current->children ();
    std::vector<Hierarchy*>::iterator iter;
    for (iter=list.begin(); iter!=list.end(); ++iter) {
      if (iter!=list.begin()) { current.append(":"); }
      current.append((*iter)->name());
      current.append("[");
      current.append((*iter)->type());
      current.append("]");
    }
    // finally ...update !
    strcpy(m_config->config,current.c_str());
    m_server->updateConfig();
  }
}
setCtrl()
void Application::setCtrl (std::string control) [inline]
Definition at line 306 of file Application.h.
Referenced by export_obj().
                                   {
    m_ctrl = control;
  }
setCurrent()
void Application::setCurrent (Hierarchy * current) [inline]
Set accessor to member m_current
Parameters
current the new value for m_current
Definition at line 141 of file Application.h.
Referenced by Application(), create(), and export_obj().
                                       {
    m_current = current;
  }
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setPlotSvc()
void Application::setPlotSvc (PlotSvc svc) [inline]
Set accessor to plot service
Parameters
svc the new value for service
Definition at line 282 of file Application.h.
                                 {
    m_plotSvc = svc;
  }
setProcessus()
void Application::setProcessus (Processus * processus) [inline]
Set accessor to member m_processus
Parameters
processus the new value for m_processus
Definition at line 240 of file Application.h.
                                           {
    m_processus = processus;
  }
setRunSvc()
void Application::setRunSvc (RunSvc svc) [inline]
Set accessor to processing service instance
Parameters
svc the new value for service
Definition at line 265 of file Application.h.
                               {
    m_runSvc = svc;
  }
setState()
void Application::setState (std::string state = std::string(``))
Set accessor to member m_state and perform network publication
Parameters
status the new value for m_status
Definition at line 221 of file Application.cpp.
References m_options, m_server, m_state, State::nErrors, Options::nErrors(), State::nEvent, State::nEventMax, Options::nEvt(), Options::nEvtMax(), State::nRun, Options::runNumber(), State::status, and Server::updateState().
Referenced by initialize(), network(), prepare(), server(), svcRunning(), and terminate().
                                            {
  if (0 != m_server) {
    m_state->nRun = m_options->runNumber();
    m_state->nEventMax = m_options->nEvtMax();
    m_state->nEvent = m_options->nEvt();
    m_state->nErrors = m_options->nErrors();
    if (status.compare("")!=0) strcpy(m_state->status,status.c_str());
    // and ... update !
    m_server->updateState();
  }
}
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
setVersion()
void Application::setVersion (std::string version) [inline]
Set accessor to member m_version
Parameters
version the new value for m_version
Definition at line 290 of file Application.h.
                                      {
    m_version = version;
  }
state()
State * Application::state ()
return current Application State
Definition at line 200 of file Application.cpp.
References m_state.
Referenced by loop(), and Server::start().
                            {
  /*
    info("nRun "+itos(m_state->nRun),"Application::state");
    info("nEvtMax "+itos(m_state->nEventMax),"Application::state");
    info("nEvt "+itos(m_state->nEvent),"Application::state");
    info("nErrors "+itos(m_state->nErrors),"Application::state");
    info("status "+std::string(m_state->status) ,"Application::state");
  */
  return m_state;
}
status()
char* Application::status () [inline]
Get accessor to member m_status
Returns
the current value of m_status
Definition at line 220 of file Application.h.
References shell::network().
Referenced by run().
                  {
    return m_state->status;
  }
svcPlot()
StatusCode Application::svcPlot ()
Definition at line 384 of file Application.cpp.
References StatusCode::FAILURE, and Object::warning().
                                  {
  warning("No implementation in cmd mode yet.","Application::svcPlot");
  return StatusCode::FAILURE;
}
svcRunning()
StatusCode Application::svcRunning ()
Definition at line 343 of file Application.cpp.
References ctrl(), StatusCode::FAILURE, Object::info(), StatusCode::isFailure(), loop(), m_options, Options::nEvt(), Options::nEvtMax(), setState(), StatusCode::SUCCESS, and Object::warning().
Referenced by run().
                                     {
  while (m_options->nEvt() < m_options->nEvtMax()) {
    if (loop().isFailure())
      {
    return StatusCode::FAILURE;
    break;
      }
    std::string control = ctrl();
    if (0 == control.compare("pause")) {
      setState ("PAUSE");
      warning("Pause.","Application::svcRunning");
      bool pause = true;
      while (pause) {
    std::string newctrl = ctrl();
    int delay = 1000; // delay in loop in ms
    usleep(1000 * delay);
    if (0==newctrl.compare ("stop")) {
      pause = false;
    }
    if (0==newctrl.compare ("resume")) {
      setState ("RUNNING");
      pause = false;
    }
    newctrl.clear();
      }
      control.clear();
    }
    if (0 == control.compare("stop")) {
      info("User interruption.","Application::svcRunning");
      control.clear();
      return StatusCode::SUCCESS;
      break;
    }
  }
  return StatusCode::SUCCESS;
}
terminate()
StatusCode Application::terminate ()
Definition at line 485 of file Application.cpp.
References Processus::endProcessing(), Options::incRunNumber(), Object::info(), itos(), Options::logStorage(), m_options, m_processus, Object::name(), Options::nEvt(), Options::runNumberManagement(), Options::setNEvt(), setState(), Options::setStream(), StatusCode::SUCCESS, and Object::title().
Referenced by export_obj(), and run().
                                    {
  m_processus->endProcessing();
  info("Processus " + m_processus->name() +" '" +
       std::string(m_processus->title().c_str()) +
       "' completed [" +
       itos(m_options->nEvt()) + " events]",
       "Application::svcRunning");
  if (m_options->logStorage()) {
    m_options->setStream();
  }
  // graphSvc();
  // m_options->setNEvtMax (currentNEvtMax);
  if (m_options->runNumberManagement()) m_options->
      incRunNumber ();
  m_options->setNEvt (0);
  setState ("READY");
#ifdef _NETWORK_
  m_processus->updateServices();
#endif
  return StatusCode::SUCCESS;
}
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestSPI::Plot(), TestUSB::Plot(), TestI2C::Plot(), Object::setTitle(), and terminate().
{ return m_title; } // < Get Object m_title
treeRecursive()
void Application::treeRecursive (Hierarchy * , std::string)
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), prepare(), UsbFTInterface::read(), UsbFTMLInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), wait(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
version()
std::string Application::version () [inline]
Get accessor to member m_version
Returns
the current value of m_version
Definition at line 298 of file Application.h.
                       {
    return m_version;
  }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), Acquisition::execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), TestI2C::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), A3PE::loadTrigger(), loop(), makeDir(), Data::name(), prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsSlave::reset(), SpecsMaster::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), svcPlot(), svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
Member Data Documentation
m_accountName
std::string Application::m_accountName [protected]
Definition at line 351 of file Application.h.
Referenced by Application(), and banner().
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_computer
Computer* Application::m_computer [private]
Definition at line 364 of file Application.h.
Referenced by Application().
m_config
Config* Application::m_config [private]
Definition at line 369 of file Application.h.
Referenced by Application(), config(), initialize(), setConfig(), and ~Application().
m_ctrl
std::string Application::m_ctrl [private]
Definition at line 376 of file Application.h.
Referenced by initialize().
m_current
Hierarchy* Application::m_current [protected]
Definition at line 358 of file Application.h.
Referenced by create(), prepare(), and setConfig().
m_dllMgr
DLLMgr* Application::m_dllMgr [private]
Definition at line 362 of file Application.h.
Referenced by Application(), create(), and ~Application().
m_hostName
std::string Application::m_hostName [protected]
Definition at line 352 of file Application.h.
Referenced by Application(), and banner().
m_isRunning
bool Application::m_isRunning [protected]
Definition at line 357 of file Application.h.
m_network
bool Application::m_network [private]
Definition at line 375 of file Application.h.
Referenced by initialize(), and network().
m_options
Options* Application::m_options [private]
Definition at line 361 of file Application.h.
Referenced by Application(), loop(), prepare(), setState(), svcRunning(), terminate(), and ~Application().
m_osName
std::string Application::m_osName [protected]
Definition at line 353 of file Application.h.
Referenced by Application(), and banner().
m_osVersion
std::string Application::m_osVersion [protected]
Definition at line 354 of file Application.h.
Referenced by Application(), and banner().
m_plotSvc
PlotSvc Application::m_plotSvc [private]
Definition at line 372 of file Application.h.
m_procDb
ProcDataBase* Application::m_procDb [private]
Definition at line 363 of file Application.h.
Referenced by Application(), and ~Application().
m_processus
Processus* Application::m_processus [private]
Definition at line 366 of file Application.h.
Referenced by loop(), prepare(), and terminate().
m_prompt
std::string Application::m_prompt [protected]
Definition at line 355 of file Application.h.
m_runSvc
RunSvc Application::m_runSvc [private]
Definition at line 371 of file Application.h.
m_server
Server* Application::m_server [private]
Definition at line 374 of file Application.h.
Referenced by initialize(), network(), server(), setConfig(), setState(), and ~Application().
m_state
State* Application::m_state [private]
Definition at line 368 of file Application.h.
Referenced by Application(), initialize(), setState(), state(), and ~Application().
m_version
std::string Application::m_version [protected]
Definition at line 356 of file Application.h.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Application.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Application.cpp