Server_NI6008 Class Reference
#include <inc/Server_NI6008.h>
Public Types
enum MsgLevel {
VERBOSE =-6,
DEBUG,
INFO,
WARNING,
ERR,
FATAL,
NONE
 }
enum MsgColor {
BLUE,
GREEN,
WHITE,
MAGENTA,
YELLOW,
RED,
CYAN
 }
Public Member Functions
Server_NI6008 (int)
virtual ~Server_NI6008 ()
Standard constructor.
void error (const char *)
void start ()
int cmd ()
int AI (const char *, double[])
int AO (const char *, double[])
int AO0 (double)
int AO1 (double)
int DI (const char *, unsigned char[])
int Reset ()
void status ()
int send (std::string word)
void msgSvc (MsgLevel, std::string, std::string call=std::string(``))
void setLineLength (int length)
void setCallSize (int size)
void log (MsgLevel, std::string, std::string)
void setAIRange (double min=-10., double max=10.)
void setAORange (double min=0., double max=5.)
void setTimeout (double timeout=10.0)
Private Member Functions
std::string logtime ()
Private Attributes
int sockfd
int newsockfd
int portno
std::string ni6008
socklen_t clilen
char buffer [256]
struct sockaddr_in serv_addr cli_addr
int n
std::vector< std::string > colors
int callSize
int lineLength
double m_aiMin
double m_aiMax
double m_aoMin
double m_aoMax
double m_timeout
Detailed Description
Author
Frédéric Machefert
Date
2016-05-28
Definition at line 103 of file Server_NI6008.h.
Member Enumeration Documentation
MsgColor
enum Server_NI6008::MsgColor
Enumerator
BLUE
GREEN
WHITE
MAGENTA
YELLOW
RED
CYAN
Definition at line 130 of file Server_NI6008.h.
{BLUE, GREEN, WHITE, MAGENTA, YELLOW, RED, CYAN};
MsgLevel
enum Server_NI6008::MsgLevel
Enumerator
VERBOSE
DEBUG
INFO
WARNING
ERR
FATAL
NONE
Definition at line 129 of file Server_NI6008.h.
{VERBOSE=-6, DEBUG, INFO, WARNING, ERR, FATAL,
      NONE};
Constructor & Destructor Documentation
Server_NI6008()
Server_NI6008::Server_NI6008 (int port)
Definition at line 25 of file Server_NI6008.cpp.
References accountName(), colors, hostName(), INFO, itos(), msgSvc(), osName(), osVersion(), portno, start(), and WARNING.
                                    :
  callSize (18),
  lineLength (200),
  m_aiMin(-10.0),
  m_aiMax(10.0),
  m_aoMin(0.0),
  m_aoMax(5.0),
  m_timeout(10.0)
{
  portno = port;
  
  colors.push_back(std::string("\033[94m"));
  colors.push_back(std::string("\033[92m"));
  colors.push_back(std::string("\033[93m"));
  colors.push_back(std::string("\033[95m"));
  colors.push_back(std::string("\033[33m"));
  colors.push_back(std::string("\033[91m"));
  colors.push_back(std::string("\033[0m"));
  std::string _accountName = accountName();
  std::string _hostName = hostName();
  std::string _osName = osName();
  std::string _osVersion = osVersion();
  msgSvc(INFO,"","");
  msgSvc(INFO," ***********************************************","");
  msgSvc(INFO," * C A T *","");
  msgSvc(INFO," * *","");
  msgSvc(INFO," * |\\-''-/|.___..--''\"`-._ *","");
  msgSvc(INFO," * `6_ 6) `-. ().`-.__.`) *","");
  msgSvc(INFO," * (_Y_.)' ._) `._ `. ``-..-' *","");
  msgSvc(INFO," * _..`--'_..- _/ /--'_.' ,' *","");
  msgSvc(INFO," * (il),-'' (li),' ((!.-' *","");
  msgSvc(INFO," ***********************************************","");
  msgSvc(INFO,"","");
  msgSvc(INFO,"Application running on "+
         _accountName+"@"+
         _hostName+" ("+
         _osName+" - "+
         _osVersion+")","");
  
  msgSvc(INFO, "Connecting port "+itos(port),"Server_NI6008");
#ifdef NODAQ
  msgSvc(WARNING,"NO HARDWARE - FAKE ACQUISITION");
#endif
  start();
}
 Server_NI6008()
Server_NI6008::~Server_NI6008 () [virtual]
Standard constructor.
Destructor
Definition at line 77 of file Server_NI6008.cpp.
                             {
}
Member Function Documentation
AI()
int Server_NI6008::AI (const char * , double [])
Definition at line 368 of file Server_NI6008.cpp.
References DAQmxErrChk, error(), and m_timeout.
Referenced by cmd().
                                                    {
    // Task parameters
    int32 error = 0;
    TaskHandle taskHandle = 0;
    char errBuff[2048]={'\0'};
    char chan[80];
    sprintf(chan,"%s/ai0,%s/ai1,%s/ai2,%s/ai3", dev, dev, dev, dev);
    // std::cout<<chan<<std::endl;
    // Channel parameters
    float64 min = -10.0;
    float64 max = 10.0;
    // Timing parameters
    uInt64 samplesPerChan = 4;
    // Data read parameters
    int32 pointsToRead = 1;
    int32 pointsRead;
    float64 timeout = m_timeout;
#ifndef NODAQ
    
    DAQmxErrChk (DAQmxBaseCreateTask("",&taskHandle));
    DAQmxErrChk (
         DAQmxBaseCreateAIVoltageChan(taskHandle,
                          chan,
                          "",
                          DAQmx_Val_Cfg_Default,
                          min,max,
                          DAQmx_Val_Volts,
                          NULL));
    DAQmxErrChk (DAQmxBaseStartTask(taskHandle));
    DAQmxErrChk (DAQmxBaseReadAnalogF64(taskHandle,
                    pointsToRead,
                    timeout,
                    DAQmx_Val_GroupByChannel,
                    data,
                    samplesPerChan,
                    &pointsRead,
                    NULL));
Error:
    if(DAQmxFailed(error))
        DAQmxBaseGetExtendedErrorInfo(errBuff,2048);
    if(taskHandle!=0) {
        DAQmxBaseStopTask(taskHandle);
        DAQmxBaseClearTask(taskHandle);
    }
    if(DAQmxFailed(error))
    printf ("DAQmxBase Error %ld: %s\n", error, errBuff);
#endif
    sprintf(errBuff,"Readout AI: Ch %s - Val = %2.4f %2.4f %2.4f %2.4f", chan,
      data[0], data[1], data[2], data[3]);
    std::cout<<errBuff<<std::endl;
    return 0;
}
AO()
int Server_NI6008::AO (const char * , double [])
Definition at line 428 of file Server_NI6008.cpp.
References DAQmxErrChk, error(), m_aoMax, m_aoMin, and m_timeout.
Referenced by cmd().
                                                    {
  // Task parameters
  int code = 0;
  int32 error = 0;
  TaskHandle taskHandle = 0;
  char errBuff[2048]={'\0'};
  char chan[80];
  sprintf(chan,"%s/ao0,%s/ao1", dev, dev);
  // char chan[] = "Dev1/ao0,Dev1/ao1";
  
  // Channel parameters
  float64 min = m_aoMin;
  float64 max = m_aoMax;
  // Timing parameters
  uInt64 samplesPerChan = 1;
  // Data write parameters
  int32 pointsWritten;
#ifndef NODAQ
  
  DAQmxErrChk (DAQmxBaseCreateTask("",&taskHandle));
  DAQmxErrChk (DAQmxBaseCreateAOVoltageChan(taskHandle,
                        chan,
                        "",
                        min,max,
                        DAQmx_Val_Volts,
                        NULL));
  DAQmxErrChk (DAQmxBaseStartTask(taskHandle));
  
  DAQmxErrChk (DAQmxBaseWriteAnalogF64(taskHandle,
                       samplesPerChan,
                       0,
                       m_timeout,
                       DAQmx_Val_GroupByChannel,
                       data,
                       &pointsWritten,NULL)
           );
Error:
    if(DAQmxFailed(error))
        DAQmxBaseGetExtendedErrorInfo(errBuff,2048);
    if(taskHandle!=0) {
        DAQmxBaseStopTask(taskHandle);
        DAQmxBaseClearTask(taskHandle);
    }
    if(DAQmxFailed(error))
        printf ("DAQmxBase Error %ld: %s\n", error, errBuff);
#endif
    sprintf(errBuff,"Setting AO: Ch %s - Val = %2.2f %2.2f", chan, data[0],
      data[1]);
    std::cout<<errBuff<<std::endl;
    return 0;
}
AO0()
int Server_NI6008::AO0 (double data)
Definition at line 554 of file Server_NI6008.cpp.
References DAQmxErrChk, error(), INFO, m_aoMax, m_aoMin, m_timeout, and msgSvc().
                                 {
  // Task parameters
  int code = 0;
  int32 error = 0;
  TaskHandle taskHandle = 0;
  char errBuff[2048]={'\0'};
  char chan[] = "Dev1/ao0\0";
  // Channel parameters
  float64 min = m_aoMin;
  float64 max = m_aoMax;
  // Timing parameters
  uInt64 samplesPerChan = 1;
  // Data write parameters
  int32 pointsWritten;
#ifndef NODAQ
  
  DAQmxErrChk (DAQmxBaseCreateTask("",&taskHandle));
  DAQmxErrChk (DAQmxBaseCreateAOVoltageChan(taskHandle,
                        chan,
                        "",
                        min,max,
                        DAQmx_Val_Volts,
                        NULL));
  DAQmxErrChk (DAQmxBaseStartTask(taskHandle));
  
  DAQmxErrChk (DAQmxBaseWriteAnalogF64(taskHandle,
                       samplesPerChan,
                       0,
                       m_timeout,
                       DAQmx_Val_GroupByChannel,
                       &data,
                       &pointsWritten,NULL)
           );
  msgSvc(INFO,"Processing AO "+std::string(chan)+".");
  return code;
Error:
    if(DAQmxFailed(error))
        DAQmxBaseGetExtendedErrorInfo(errBuff,2048);
    if(taskHandle!=0) {
        DAQmxBaseStopTask(taskHandle);
        DAQmxBaseClearTask(taskHandle);
    }
    if(DAQmxFailed(error))
        printf ("DAQmxBase Error %ld: %s\n", error, errBuff);
#endif
    return 0;
}
AO1()
int Server_NI6008::AO1 (double data)
Definition at line 607 of file Server_NI6008.cpp.
References DAQmxErrChk, error(), INFO, m_aoMax, m_aoMin, m_timeout, and msgSvc().
                                 {
  // Task parameters
  int code = 0;
  int32 error = 0;
  TaskHandle taskHandle = 0;
  char errBuff[2048]={'\0'};
  char chan[] = "Dev1/ao1";
  // Channel parameters
  float64 min = m_aoMin;
  float64 max = m_aoMax;
  // Timing parameters
  uInt64 samplesPerChan = 1;
  // Data write parameters
  int32 pointsWritten;
  #ifndef NODAQ
  DAQmxErrChk (DAQmxBaseCreateTask("",&taskHandle));
  DAQmxErrChk (DAQmxBaseCreateAOVoltageChan(taskHandle,
                        chan,
                        "",
                        min,max,
                        DAQmx_Val_Volts,
                        NULL));
  DAQmxErrChk (DAQmxBaseStartTask(taskHandle));
  
  DAQmxErrChk (DAQmxBaseWriteAnalogF64(taskHandle,
                       samplesPerChan,
                       0,
                       m_timeout,
                       DAQmx_Val_GroupByChannel,
                       &data,
                       &pointsWritten,NULL)
           );
  msgSvc(INFO,"Processing AO1 "+std::string(chan)+".");
#endif
  return code;
#ifndef NODAQ
Error:
    if(DAQmxFailed(error))
        DAQmxBaseGetExtendedErrorInfo(errBuff,2048);
    if(taskHandle!=0) {
        DAQmxBaseStopTask(taskHandle);
        DAQmxBaseClearTask(taskHandle);
    }
    if(DAQmxFailed(error))
        printf ("DAQmxBase Error %ld: %s\n", error, errBuff);
    return 0;
#endif
}
cmd()
int Server_NI6008::cmd ()
Definition at line 223 of file Server_NI6008.cpp.
References AI(), AO(), buffer, shell::data(), DI(), error(), msgSvc(), n, newsockfd, Reset(), send(), setAIRange(), setAORange(), setTimeout(), cat::size, sockfd, and WARNING.
Referenced by start().
                      {
  n = read(newsockfd,buffer,255);
  if (n < 0) {
    error("ERROR reading from socket");
  }
 
  char result[4096];
  int size = 0 ;
  
  std::string newcmd = std::string(buffer);
  std::string delimiter = " ";
  size_t pos = 0;
  int cmdsize = 0;
  std::vector<std::string> cmdvec;
  while ((pos = newcmd.find(delimiter)) != std::string::npos) {
    cmdvec.push_back(newcmd.substr(0, pos));
    newcmd.erase(0, pos + delimiter.length());
    cmdsize++;
  }
  cmdvec.push_back(newcmd);
  cmdsize++;
  // for (int i =0 ; i<cmdsize; i++) std::cout<<" command: "<<cmdvec[i]<<" "<<cmdsize<<std::endl;
  
  bool understood = false;
  std::string instr = cmdvec[1];
  std::transform(instr.begin(), instr.end(),instr.begin(), ::tolower);
  size = -1 ;
  // Server status
  if (instr=="status"){
    // status();
    understood = true;
  }
  // Time out
  if (instr=="timeout" && cmdsize==2){
    setTimeout(atof(cmdvec[2].c_str()));
    // status();
    understood = true;
  }
  // AI
  if (instr=="ai" && cmdsize==2){
    const char* dev = cmdvec[0].c_str();
    double data[4];
    AI(dev, data);
    size = sprintf(result,"%f %f %f %f", data[0], data[1], data[2], data[3]);
    if (write(newsockfd, result, size)<0) error("ERROR writing to socket");
    understood = true;
  }
  // AI range
  if (instr=="airange" && cmdsize==4){
    setAIRange(atof(cmdvec[2].c_str()), atof(cmdvec[3].c_str()));
    // status();
    understood = true;
  }
  // AO
  if (instr=="ao" && cmdsize==4){
    const char* dev = cmdvec[0].c_str();
    double data[2];
    data[0]=atof(cmdvec[2].c_str());
    data[1]=atof(cmdvec[3].c_str());
    // std::cout<<data[0]<<" "<<data[1]<<std::endl;
    AO(dev, data);
    size = sprintf(result,"AO set.");
    if (write(newsockfd, result, size)<0) error("ERROR writing to socket");
    understood = true;
  }
  // // AO0
  // if (instr=="ao0" && cmdsize==1){
  // double data;
  // data=atof(cmdvec[1].c_str());
  // AO0(data);
  // size = sprintf(result,"AO0 set.");
  // if (write(newsockfd, result, size)<0) error("ERROR writing to socket");
  // }
  // // AO1
  // if (instr=="ao1" && cmdsize==1){
  // double data;
  // data=atof(cmdvec[1].c_str());
  // AO1(data);
  // size = sprintf(result,"AO1 set.");
  // if (write(newsockfd, result, size)<0) error("ERROR writing to socket");
  // }
  // AO range
  if (instr=="aorange" && cmdsize==4){
    setAORange(atof(cmdvec[2].c_str()), atof(cmdvec[3].c_str()));
    // status();
    understood = true;
  }
  // DI
  if (instr=="di"){
    const char* dev = cmdvec[0].c_str();
    unsigned char idata[2];
    DI(dev, idata);
    unsigned int data = idata[0]+256*idata[1];
    unsigned int data2 =
      (data>>3&1)+2*(data>>2&1)+4*(data>>1&1)+8*(data&1)+
      16*(data>>11&1)+32*(data>>10&1)+64*(data>>9&1)+128*(data>>8&1)+
      256*(data>>7&1)+512*(data>>6&1)+1024*(data>>5&1)+2048*(data>>4&1);
    size = sprintf(result,"%d %d - %d / %d -> %i%i%i%i%i%i%i%i%i%i%i%i ", idata[0], idata[1], data, data2,
       
           data>>11&1, data>>10& 1, data>>9&1, data>>8&1,
           data>>7&1, data>>6&1, data>>5&1, data>>4&1,
           data>>3&1, data>>2&1, data>>1&1, data&1
           );
    std::cout<< "digit :" << result<< std::endl;
    if (write(newsockfd, result, size)<0) error("ERROR writing to socket");
    understood = true;
  }
  // DI
  if (instr=="reset"){
    Reset();
    if (write(newsockfd, result, size)<0) error("ERROR writing to socket");
    understood = true;
  }
  // Stop
  if (instr=="stop"){
    msgSvc(WARNING, "Closing the server connection.");
    n = send("exit");
    if (n < 0) error("ERROR writing to socket");
    close(newsockfd);
    close(sockfd);
    exit(0);
  }
  if (!understood){
    size = sprintf(result,"Instruction not understood.");
    if (write(newsockfd, result, size)<0) error("ERROR writing to socket");
  }
  return 0;
}
DI()
int Server_NI6008::DI (const char * , unsigned char [])
Definition at line 483 of file Server_NI6008.cpp.
References DAQmxErrChk, error(), and m_timeout.
Referenced by cmd().
                                                               {
  // Task parameters
  int code = 0;
  int32 error = 0;
  TaskHandle taskHandle = 0;
  int32 i;
  const uInt32 num_ports = 2;
  char errBuff[2048];
  // Channel parameters
  char chan1[32];
  char chan2[32];
  sprintf(chan1,"%s/port0", dev);
  sprintf(chan2,"%s/port1", dev);
  // char chan1[] = "Dev1/port0";
  // char chan2[] = "Dev1/port1";
  // Read parameters
  int32 read;
#ifndef NODAQ
  // Create Digital Input (DI) Task and Channel
  DAQmxErrChk (DAQmxBaseCreateTask ("", &taskHandle));
  DAQmxErrChk (DAQmxBaseCreateDIChan(taskHandle,chan1,"",DAQmx_Val_ChanForAllLines));
  DAQmxErrChk (DAQmxBaseCreateDIChan(taskHandle,chan2,"",DAQmx_Val_ChanForAllLines));
  // Start Task (configure port)
  DAQmxErrChk (DAQmxBaseStartTask (taskHandle));
  // Read from port
  DAQmxErrChk (
    code = DAQmxBaseReadDigitalU8(
      taskHandle,
      1,
      m_timeout,
      DAQmx_Val_GroupByChannel,
      r_data,
      num_ports,
      &read,
      NULL)
  );
  // msgSvc(INFO,"Processing DI "+std::string(chan1)+"/"+std::string(chan2)+
  // " ->"+ itos(r_data[0])+", "+itos(r_data[1]));
Error:
   if (DAQmxFailed (error))
      DAQmxBaseGetExtendedErrorInfo (errBuff, 2048);
   if (taskHandle != 0){
      DAQmxBaseStopTask (taskHandle);
      DAQmxBaseClearTask (taskHandle);
   }
   if (error)printf ("DAQmxBase Error %ld: %s\n", error, errBuff);
#endif
   sprintf(errBuff,"Reading DI: Ch %s %s - Val = %3i %3i", chan1, chan2, r_data[0], r_data[1]);
    std::cout<<errBuff<<std::endl;
   return 0;
}
error()
void Server_NI6008::error (const char * msg)
Definition at line 83 of file Server_NI6008.cpp.
Referenced by AI(), AO(), AO0(), AO1(), cmd(), DI(), and start().
{
    perror(msg);
    exit(1);
}
log()
void Server_NI6008::log (MsgLevel level, std::string msg, std::string call)
Definition at line 118 of file Server_NI6008.cpp.
References BLUE, callSize, colors, CYAN, DEBUG, ERR, FATAL, GREEN, INFO, logtime(), MAGENTA, RED, VERBOSE, WARNING, WHITE, and YELLOW.
Referenced by msgSvc(), and setCallSize().
                                  {
  bool isFatal=false;
  
  //#ifndef WIN32
  std::string output(colors[BLUE]);
  output+=std::string(call,0,callSize);
  //#else
  // std::string output=std::string(call,0,callSize);
  //#endif
  int clen=call.length();
  if (clen>0)
  {
    if (clen>callSize) output.replace(callSize+5-3,3,"...");
    if (clen<callSize) output.insert (clen+5,callSize-clen,' ');
  }
  
  std::string color;
  
  switch(level) {
  case VERBOSE:
    color=colors[BLUE];
    output+=color;
    output+=" VERBOSE ";
    break;
  case DEBUG:
    color=colors[BLUE];
    output+=color;
    output+=" DEBUG ";
    break;
  case INFO:
    color=colors[GREEN];
    output+=color;
    output+=" INFO ";
    break;
  case WARNING:
    color=colors[YELLOW];
    output+=color;
    output+=" WARNING ";
    break;
  case ERR:
    color=colors[MAGENTA];
    output+=color;
    output+=" ERROR ";
    break;
  case FATAL:
    color=colors[RED];
    output+=color;
    output+=" FATAL ";
    isFatal=true;
    break;
  default:
    color = colors[CYAN];
    output+=color;
    output = call;
    break;
  }
  output+=colors[WHITE];
  output+=logtime();
  output+=color;
  output+=msg;
  output+=colors[WHITE];
  
  std::cout << output << std::endl;
  if (isFatal) {exit(0);}
}
logtime()
std::string Server_NI6008::logtime () [private]
Definition at line 103 of file Server_NI6008.cpp.
Referenced by log().
                                {
  time_t rawtime;
  struct tm * timeinfo;
  
  time (&rawtime);
  timeinfo = localtime (&rawtime);
  char* timechar = asctime (timeinfo) ;
  std::string timing = std::string(timechar,24) + " ";
  return timing;
}
msgSvc()
void Server_NI6008::msgSvc (MsgLevel level, std::string msg, std::string call = std::string(``))
Definition at line 92 of file Server_NI6008.cpp.
References DEBUG, and log().
Referenced by AO0(), AO1(), cmd(), Reset(), Server_NI6008(), setAIRange(), and setAORange().
                                     {
  const int OUTLEVEL = DEBUG;
  if (level<OUTLEVEL) return;
  log (level, msg, call);
}
Reset()
int Server_NI6008::Reset ()
Definition at line 546 of file Server_NI6008.cpp.
References INFO, and msgSvc().
Referenced by cmd().
                        {
  msgSvc(INFO,"Reset has not been implemented yet.");
  return 0;
}
send()
int Server_NI6008::send (std::string word) [inline]
Definition at line 117 of file Server_NI6008.h.
Referenced by cmd(), and status().
                             {
    /*
    char buffer[]=word.c_str());
    std::cout<<"sending : "<<buffer<<" "<<sizeof(buffer)<<std::endl;
    int size = -1;
    size = write(newsockfd, buffer, sizeof(buffer));
    if (size<0) error("ERROR writing to socket");
    return size;
    */
    return 0;
  }
setAIRange()
void Server_NI6008::setAIRange (double min = -10., double max = 10.) [inline]
Definition at line 138 of file Server_NI6008.h.
References FATAL, ftos(), m_aiMax, m_aiMin, and msgSvc().
Referenced by cmd().
                                                  {
    if (min<-10.0&&max>10.0){
    msgSvc(FATAL,"Cannot set such range: "+ftos(min)+","+ftos(max),"setAORange");
    }
    m_aiMin = min;
    m_aiMax = max;
  }
setAORange()
void Server_NI6008::setAORange (double min = 0., double max = 5.) [inline]
Definition at line 146 of file Server_NI6008.h.
References FATAL, ftos(), m_aoMax, m_aoMin, and msgSvc().
Referenced by cmd().
                                               {
    if (min<-10.0&&max>10.0){
    msgSvc(FATAL,"Cannot set such range: "+ftos(min)+","+ftos(max),"setAORange");
    }
    m_aoMin = min;
    m_aoMax = max;
  }
setCallSize()
void Server_NI6008::setCallSize (int size) [inline]
Definition at line 135 of file Server_NI6008.h.
References callSize, log(), and cat::size.
{ callSize = size ; } //< Set Msg call field size
setLineLength()
void Server_NI6008::setLineLength (int length) [inline]
Definition at line 134 of file Server_NI6008.h.
References lineLength.
{ lineLength = length ; } //< Set Msg line length
setTimeout()
void Server_NI6008::setTimeout (double timeout = 10.0) [inline]
Definition at line 154 of file Server_NI6008.h.
References m_timeout.
Referenced by cmd().
                                        {
    m_timeout = timeout;
  }
start()
void Server_NI6008::start ()
Definition at line 195 of file Server_NI6008.cpp.
References buffer, cli_addr, clilen, cmd(), error(), newsockfd, portno, and sockfd.
Referenced by Server_NI6008().
                         {
  sockfd = socket(AF_INET, SOCK_STREAM, 0);
  if (sockfd < 0)
    error("ERROR opening socket");
  bzero((char *) &serv_addr, sizeof(serv_addr));
  serv_addr.sin_family = AF_INET;
  serv_addr.sin_addr.s_addr = INADDR_ANY;
  serv_addr.sin_port = htons(portno);
  if (bind(sockfd, (struct sockaddr *) &serv_addr,
       sizeof(serv_addr)) < 0)
    error("ERROR on binding");
  listen(sockfd,5);
  clilen = sizeof(cli_addr);
  newsockfd = accept(sockfd,
             (struct sockaddr *) &cli_addr,
             &clilen);
  if (newsockfd < 0) error("ERROR on accept");
     while(1) {
       bzero(buffer,256);
       cmd();
     }
  close(newsockfd);
  close(sockfd);
}
status()
void Server_NI6008::status ()
Definition at line 355 of file Server_NI6008.cpp.
References ftos(), itos(), m_aiMax, m_aiMin, m_aoMax, m_aoMin, m_timeout, portno, and send().
                           {
  send(std::string("Port : "+itos(portno)));
  send(std::string(" - Timeout = "+ftos(m_timeout)));
  send(std::string(" - AI"));
  send(std::string(" . min = "+ftos(m_aiMin)));
  send(std::string(" . max = "+ftos(m_aiMax)));
  send(std::string(" - AO"));
  send(std::string(" . min = "+ftos(m_aoMin)));
  send(std::string(" . max = "+ftos(m_aoMax)));
}
Member Data Documentation
buffer
char Server_NI6008::buffer[256] [private]
Definition at line 162 of file Server_NI6008.h.
Referenced by cmd(), and start().
callSize
int Server_NI6008::callSize [private]
Definition at line 166 of file Server_NI6008.h.
Referenced by log(), and setCallSize().
cli_addr
struct sockaddr_in serv_addr Server_NI6008::cli_addr [private]
Definition at line 163 of file Server_NI6008.h.
Referenced by start().
clilen
socklen_t Server_NI6008::clilen [private]
Definition at line 161 of file Server_NI6008.h.
Referenced by start().
colors
std::vector<std::string> Server_NI6008::colors [private]
Definition at line 165 of file Server_NI6008.h.
Referenced by log(), and Server_NI6008().
lineLength
int Server_NI6008::lineLength [private]
Definition at line 167 of file Server_NI6008.h.
Referenced by setLineLength().
m_aiMax
double Server_NI6008::m_aiMax [private]
Definition at line 170 of file Server_NI6008.h.
Referenced by setAIRange(), and status().
m_aiMin
double Server_NI6008::m_aiMin [private]
Definition at line 170 of file Server_NI6008.h.
Referenced by setAIRange(), and status().
m_aoMax
double Server_NI6008::m_aoMax [private]
Definition at line 171 of file Server_NI6008.h.
Referenced by AO(), AO0(), AO1(), setAORange(), and status().
m_aoMin
double Server_NI6008::m_aoMin [private]
Definition at line 171 of file Server_NI6008.h.
Referenced by AO(), AO0(), AO1(), setAORange(), and status().
m_timeout
double Server_NI6008::m_timeout [private]
Definition at line 172 of file Server_NI6008.h.
Referenced by AI(), AO(), AO0(), AO1(), DI(), setTimeout(), and status().
n
int Server_NI6008::n [private]
Definition at line 164 of file Server_NI6008.h.
Referenced by cmd().
newsockfd
int Server_NI6008::newsockfd [private]
Definition at line 159 of file Server_NI6008.h.
Referenced by cmd(), and start().
ni6008
std::string Server_NI6008::ni6008 [private]
Definition at line 160 of file Server_NI6008.h.
portno
int Server_NI6008::portno [private]
Definition at line 159 of file Server_NI6008.h.
Referenced by Server_NI6008(), start(), and status().
sockfd
int Server_NI6008::sockfd [private]
Definition at line 159 of file Server_NI6008.h.
Referenced by cmd(), and start().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatNI/inc/Server_NI6008.h
/home/eleclhcb/LHCb/lbcat-cmake/CatNI/src/Server_NI6008.cpp