CU_v1 Class Reference
#include <inc/CU_v1.h>
Public Member Functions
CU_v1 ()
Standard constructor.
virtual ~CU_v1 ()
Destructor.
void help ()
StatusCode init ()
void reset ()
void update ()
FePGA * fePga ()
void readFifo (int, int, unsigned int *)
Private Attributes
int m_fifoDepth
int m_gbtAddress [1]
int m_fifoInjectAddress [3]
FePGA * m_fePga
unsigned int * m_fifo [3]
Data * m_data
RAM * m_ramInj [3]
RAM * m_fifoUsbTest
Additional Inherited Members
Detailed Description
Author
Date
2006-10-23
Definition at line 19 of file CU_v1.h.
Constructor & Destructor Documentation
CU_v1()
CU_v1::CU_v1 ()
Standard constructor.
Definition at line 17 of file CU_v1.cpp.
References Attrib::add(), Hierarchy::addChild(), Attrib::ELEMENT, Attrib::HARDWARE, m_fePga, m_fifoDepth, Object::setName(), and Object::setType().
               {
  setName("CU_v1");
  setType("CU_v1");
  add(Attrib::ELEMENT); add (Attrib::HARDWARE);
  m_fifoDepth = 1024;
  
  //m_seqAddress = 17 ; // c'est l'addresse du FPGA
  //m_fifoInjectAddress[0] = 23; // What should I do here?
  m_fePga =new FePGA();
  m_fePga->setName("FePGA");
  addChild(m_fePga);
  /*
  m_fifo[0] = new unsigned int[m_fifoDepth];
  for (int i = 0; i<3; ++i){ // Do I loop up to 3 too? Car Frederic a besoin de plus de place dans les RAM
    m_ramInj[i] = new RAM();
    // m_ramSpy[i] = new RAM();
    fePga()->usb()->addChild(m_ramInj[i]); // What should I do here ?
    // FePga()->usb()->addChild(m_ramSpy[i]);
    m_ramInj[i]->setAddress(13); // for debug // What should I do here ?
    //m_ramSpy[i]->setAddress(m_fifoSpyAddress[i]);
    m_ramInj[i]->setSize(16, m_fifoDepth); // What should I do here ?
    // m_ramSpy[i]->setSize(16, m_fifoDepth);
  }
  m_fifoUsbTest = new RAM();
  m_fifoUsbTest->setAddress(3); // WARNING I NEED TO CHANGE THE ADDRESS
  m_fifoUsbTest->setSize(16,256); // WHAT SIZE FOR I NNED
  m_fifoUsbTest->setName("FifoUsbTest");
  fePga()->usb()->addChild(m_fifoUsbTest);
*/
}
 CU_v1()
CU_v1::~CU_v1 () [virtual]
Destructor.
Definition at line 60 of file CU_v1.cpp.
              {
}
Member Function Documentation
fePga()
FePGA* CU_v1::fePga () [inline]
Definition at line 56 of file CU_v1.h.
References m_fePga, and readFifo().
Referenced by BOOST_PYTHON_MODULE().
                {
    return m_fePga;
  }
help()
void CU_v1::help () [inline], [virtual]
printout help for the element
Implements Element.
Definition at line 29 of file CU_v1.h.
References Object::info(), and Object::name().
{ info("CU_v1 "+name()+". No help.","CU_v1::help"); };
init()
StatusCode CU_v1::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 35 of file CU_v1.h.
References StatusCode::SUCCESS.
                    {
    return StatusCode::SUCCESS;
  };
readFifo()
void CU_v1::readFifo (int add, int subadd, unsigned int * fifo)
Definition at line 64 of file CU_v1.cpp.
References m_fePga, m_fifoDepth, and FePGA::spiRead().
Referenced by BOOST_PYTHON_MODULE(), and fePga().
                                                             {
m_fePga->spiRead(subadd, m_fifoDepth, fifo); // Question why do we read the fifo
       with spi? /
}
reset()
void CU_v1::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 46 of file CU_v1.h.
References Object::debug(), m_fePga, Object::name(), and FePGA::reset().
               {
    m_fePga->reset();
    debug("CU_v1 "+name()+" reset.","CU_v1::reset");
  };
update()
void CU_v1::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 54 of file CU_v1.h.
References Object::info(), and Object::name().
Referenced by AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
{info("CU_v1 "+name()+". Nothing to do.","CU_v1::update");};
Member Data Documentation
m_data
Data* CU_v1::m_data [private]
Definition at line 70 of file CU_v1.h.
m_fePga
FePGA* CU_v1::m_fePga [private]
Definition at line 68 of file CU_v1.h.
Referenced by CU_v1(), fePga(), readFifo(), and reset().
m_fifo
unsigned int* CU_v1::m_fifo[3] [private]
Definition at line 69 of file CU_v1.h.
m_fifoDepth
int CU_v1::m_fifoDepth [private]
Definition at line 65 of file CU_v1.h.
Referenced by CU_v1(), and readFifo().
m_fifoInjectAddress
int CU_v1::m_fifoInjectAddress[3] [private]
Definition at line 67 of file CU_v1.h.
m_fifoUsbTest
RAM* CU_v1::m_fifoUsbTest [private]
Definition at line 72 of file CU_v1.h.
m_gbtAddress
int CU_v1::m_gbtAddress[1] [private]
Definition at line 66 of file CU_v1.h.
m_ramInj
RAM* CU_v1::m_ramInj[3] [private]
Definition at line 71 of file CU_v1.h.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/CU_v1.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/CU_v1.cpp