Histo1D Class Reference
#include <Histo1D.h>
Public Types
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
Histo1D (TH1D *histo)
~Histo1D ()
void def ()
void fill (double x, double value=1.)
double minY ()
double maxY ()
double maxX ()
double minX ()
std::vector< double > bins ()
std::vector< double > centers ()
std::vector< double > edges ()
unsigned long nBin ()
double bin (double x)
double binEdgeMin (unsigned int)
double binEdgeMax (unsigned int)
double binContent (int i)
double overflow ()
double underflow ()
void statistics (double &, double &, double &)
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
std::string m_attribString [10]
Private Attributes
double m_zero
double m_infini
unsigned long m_nbins
std::vector< double > m_bins
std::vector< double > m_centers
std::vector< double > m_edges
double m_minX
double m_maxX
double m_minY
double m_maxY
double m_delta
double m_overflow
double m_underflow
double m_content
double m_mean
double m_rms
Detailed Description
Definition at line 28 of file Histo1D.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
Constructor & Destructor Documentation
Histo1D()
Histo1D::Histo1D (TH1D * histo)
Definition at line 22 of file Histo1D.cpp.
References m_bins, m_centers, m_content, m_delta, m_edges, m_maxX, m_maxY, m_mean, m_minX, m_minY, m_nbins, m_overflow, m_rms, m_underflow, and Object::setTitle().
                              : m_zero (1.e-30) , m_infini(1.e30) {
  //m_histo = histo;
  
  m_nbins = histo->GetNbinsX();
  setTitle(std::string(histo -> GetTitle()));
  m_bins.resize (m_nbins,0.);
  m_centers.resize (m_nbins,0.);
  m_edges.resize (m_nbins+1,0.);
  unsigned long nbin=0;
  for (nbin=0;nbin<m_nbins; ++nbin){
    m_bins[nbin]=histo->GetBinContent(nbin+1);
    m_centers[nbin]=histo->GetBinCenter(nbin+1);
  }
  m_delta = histo->GetBinWidth(0);
  for (nbin=0;nbin<m_nbins+1; ++nbin){
    m_edges[nbin]=histo->GetBinLowEdge(1)+nbin*m_delta;
  }
  m_underflow = histo->GetBinContent(0);
  m_overflow = histo->GetBinContent(histo->GetNbinsX()+1);
  m_minX = histo->GetBinLowEdge(1);
  m_maxX = histo->GetBinLowEdge(histo->GetNbinsX()+1);
  m_minY = histo->GetMinimum();
  m_maxY = histo->GetMaximum();
  m_content = histo->GetEntries();
  m_mean = histo->GetMean();
  m_rms = histo->GetRMS();
}
 Histo1D()
Histo1D::~Histo1D () [inline]
Definition at line 32 of file Histo1D.h.
References def(), fill(), maxY(), and minY().
{ }
Member Function Documentation
add()
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), TestI2C::setAddress(), TestSPI::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
bin()
double Histo1D::bin (double x)
Definition at line 59 of file Histo1D.cpp.
References m_bins, m_delta, m_maxX, m_minX, m_nbins, m_overflow, and m_underflow.
Referenced by nBin().
                           {
    if (x>=m_maxX) {return m_overflow;}
    else if(x<m_minX) {return m_underflow;}
    unsigned long bin=(unsigned long)(floor(m_nbins*(x-m_minX)/
      m_delta));
    return m_bins[bin];
}
binContent()
double Histo1D::binContent (int i) [inline]
Definition at line 71 of file Histo1D.h.
References m_bins.
                          {
    return m_bins[i];
  }
binEdgeMax()
double Histo1D::binEdgeMax (unsigned int bin)
Definition at line 78 of file Histo1D.cpp.
References m_delta, and m_minX.
Referenced by nBin().
                                             {
  return m_minX+(bin+1)*(m_delta);
}
binEdgeMin()
double Histo1D::binEdgeMin (unsigned int bin)
Definition at line 74 of file Histo1D.cpp.
References m_delta, and m_minX.
Referenced by nBin().
                                            {
  return m_minX+bin*(m_delta);
}
bins()
std::vector<double> Histo1D::bins () [inline]
Definition at line 49 of file Histo1D.h.
References m_bins.
Referenced by export_proc().
                          {
    return m_bins;
  }
centers()
std::vector<double> Histo1D::centers () [inline]
Definition at line 53 of file Histo1D.h.
References m_centers.
Referenced by export_proc().
                             {
    return m_centers;
  }
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), A3PE::internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), FEB_v1::readFifoSpyFE(), CU_v1::reset(), FEB_v1::reset(), Proto40MHz_v1::reset(), SpecsMaster::reset(), SpecsSlave::reset(), FEB_v1::resetFifoSpyFE(), FEB_v1::resetUsb(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), FEB_v1::testDuration(), SeqPGA::testSequence(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
def()
void Histo1D::def ()
Referenced by ~Histo1D().
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
edges()
std::vector<double> Histo1D::edges () [inline]
Definition at line 57 of file Histo1D.h.
References m_edges.
Referenced by export_proc().
                           {
    return m_edges;
  }
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
fill()
void Histo1D::fill (double x, double value = 1.)
Referenced by ~Histo1D().
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), ICECALv3::bxidResynchStatus(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTInterface::close(), UsbFTMLInterface::close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), UsbFTMLInterface::help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), MSOxxxx::id(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), EmulateFE::initialize(), ADCMeasurement::initialize(), CurrentMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbMLI2cBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), FePGA::reset(), SeqPGA::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), UsbFTInterface::reset(), UsbFTMLInterface::reset(), A3PE::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), SeqPGA::resetUsb(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), ICECALv3::version(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
maxX()
double Histo1D::maxX () [inline]
Definition at line 42 of file Histo1D.h.
References m_maxX.
Referenced by export_proc().
               {
    return m_maxX;
  }
maxY()
double Histo1D::maxY ()
Definition at line 70 of file Histo1D.cpp.
References m_maxY.
Referenced by export_proc(), and ~Histo1D().
                    {
  return m_maxY;
}
minX()
double Histo1D::minX () [inline]
Definition at line 45 of file Histo1D.h.
References m_minX.
Referenced by export_proc().
               {
    return m_minX;
  }
minY()
double Histo1D::minY ()
Definition at line 66 of file Histo1D.cpp.
References m_minY.
Referenced by export_proc(), and ~Histo1D().
                    {
    return m_minY;
}
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), SeqPGA::help(), NI6008::help(), Computer::help(), SpecsParallelBus::help(), UsbFTInterface::help(), UsbFTMLInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), Data::hist2d(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), CU_v1::reset(), UsbSpiBus::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), SpecsSlave::resetInternal(), FEB_v1::resetUsb(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), Object::setName(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTMLInterface::update(), UsbFTInterface::update(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
nBin()
unsigned long Histo1D::nBin () [inline]
Definition at line 61 of file Histo1D.h.
References bin(), binEdgeMax(), binEdgeMin(), and m_nbins.
Referenced by export_proc().
                      {
    return m_nbins;
  }
overflow()
double Histo1D::overflow () [inline]
Definition at line 75 of file Histo1D.h.
References m_overflow.
Referenced by export_proc().
                   {
    return m_overflow;
  }
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
statistics()
void Histo1D::statistics (double & content, double & mean, double & rms)
Definition at line 82 of file Histo1D.cpp.
References m_content, m_mean, and m_rms.
Referenced by underflow().
                                     {
  content=m_content;
  mean =m_mean;
  rms =m_rms;
}
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestUSB::Plot(), TestSPI::Plot(), TestI2C::Plot(), Object::setTitle(), and Application::terminate().
{ return m_title; } // < Get Object m_title
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
underflow()
double Histo1D::underflow () [inline]
Definition at line 78 of file Histo1D.h.
References m_underflow, and statistics().
Referenced by export_proc().
                    {
    return m_underflow;
  }
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTInterface::read(), UsbFTMLInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), wait(), UsbFTInterface::write(), and UsbFTMLInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), Acquisition::execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), TestI2C::initialize(), EmulateFE::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsMaster::reset(), SpecsSlave::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
Member Data Documentation
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_bins
std::vector<double> Histo1D::m_bins [private]
Definition at line 89 of file Histo1D.h.
Referenced by bin(), binContent(), bins(), and Histo1D().
m_centers
std::vector<double> Histo1D::m_centers [private]
Definition at line 90 of file Histo1D.h.
Referenced by centers(), and Histo1D().
m_content
double Histo1D::m_content [private]
Definition at line 102 of file Histo1D.h.
Referenced by Histo1D(), and statistics().
m_delta
double Histo1D::m_delta [private]
Definition at line 97 of file Histo1D.h.
Referenced by bin(), binEdgeMax(), binEdgeMin(), and Histo1D().
m_edges
std::vector<double> Histo1D::m_edges [private]
Definition at line 91 of file Histo1D.h.
Referenced by edges(), and Histo1D().
m_infini
double Histo1D::m_infini [private]
Definition at line 86 of file Histo1D.h.
m_maxX
double Histo1D::m_maxX [private]
Definition at line 94 of file Histo1D.h.
Referenced by bin(), Histo1D(), and maxX().
m_maxY
double Histo1D::m_maxY [private]
Definition at line 96 of file Histo1D.h.
Referenced by Histo1D(), and maxY().
m_mean
double Histo1D::m_mean [private]
Definition at line 103 of file Histo1D.h.
Referenced by Histo1D(), and statistics().
m_minX
double Histo1D::m_minX [private]
Definition at line 93 of file Histo1D.h.
Referenced by bin(), binEdgeMax(), binEdgeMin(), Histo1D(), and minX().
m_minY
double Histo1D::m_minY [private]
Definition at line 95 of file Histo1D.h.
Referenced by Histo1D(), and minY().
m_nbins
unsigned long Histo1D::m_nbins [private]
Definition at line 88 of file Histo1D.h.
Referenced by bin(), Histo1D(), and nBin().
m_overflow
double Histo1D::m_overflow [private]
Definition at line 99 of file Histo1D.h.
Referenced by bin(), Histo1D(), and overflow().
m_rms
double Histo1D::m_rms [private]
Definition at line 104 of file Histo1D.h.
Referenced by Histo1D(), and statistics().
m_underflow
double Histo1D::m_underflow [private]
Definition at line 100 of file Histo1D.h.
Referenced by bin(), Histo1D(), and underflow().
m_zero
double Histo1D::m_zero [private]
Definition at line 85 of file Histo1D.h.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Histo1D.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Histo1D.cpp