Run Class Reference
#include <include/Run.h>
Public Member Functions
Run ()
Standard constructor.
Run (std::vector< short >)
Run (int, std::vector< short >)
virtual ~Run ()
Destructor.
void decodeInfo ()
unsigned long number ()
unsigned long date ()
void setNumber (unsigned long run)
void setSpy (std::vector< short >)
void setDate (unsigned long date)
std::vector< int > spyEvt ()
std::vector< int > spyChannel ()
std::vector< short > spyRaw ()
Public Attributes
ClassDef(Run, 1) protected unsigned long m_date
std::vector< short > m_spyRaw
int m_spySize
std::vector< int > m_spyEvt
std::vector< int > m_spyChannel
Detailed Description
Author
Frederic Machefert
Date
2004-10-04
Definition at line 17 of file Run.h.
Constructor & Destructor Documentation
Run() [1/3]
Run::Run ()
Standard constructor.
Run() [2/3]
Run::Run (std::vector< short > spyInfo)
Definition at line 31 of file Run.cpp.
References m_date, and setSpy().
                                        {
  setSpy (spyInfo);
  m_run = 0;
  TDatime today;
  m_date = today.GetDate();
}
Run() [3/3]
Run::Run (int run, std::vector< short > spyInfo)
Definition at line 41 of file Run.cpp.
References m_date, shell::run(), and setSpy().
                                                 {
  setSpy (spyInfo);
  m_run = run ;
  TDatime today;
  m_date = today.GetDate();
}
 Run()
Run::~Run () [virtual]
Destructor.
Definition at line 52 of file Run.cpp.
{}
Member Function Documentation
date()
unsigned long Run::date () [inline]
Definition at line 33 of file Run.h.
References m_date.
Referenced by setDate().
                      {
    return m_date;
  }
decodeInfo()
void Run::decodeInfo ()
Definition at line 66 of file Run.cpp.
References images::index, m_spyChannel, m_spyEvt, m_spyRaw, and m_spySize.
Referenced by setSpy().
                     {
  m_spyEvt.reserve(m_spySize);
  m_spyChannel.reserve(m_spySize);
  m_spyEvt.clear();
  m_spyChannel.clear();
  for (int index = 0 ; index < m_spySize ; ++index){
    m_spyEvt.push_back(((m_spyRaw[index]>>0xF)&0xFF));
    m_spyChannel.push_back(m_spyRaw[index]&0xF);
  }
}
number()
unsigned long Run::number () [inline]
Definition at line 29 of file Run.h.
                        {
    return m_run;
  }
setDate()
void Run::setDate (unsigned long date) [inline]
Definition at line 44 of file Run.h.
References date(), and m_date.
                                  {
    m_date=date;
  }
setNumber()
void Run::setNumber (unsigned long run) [inline]
Definition at line 37 of file Run.h.
References shell::run(), and setSpy().
                                   {
    m_run=run;
  }
setSpy()
void Run::setSpy (std::vector< short > spyInfo)
Definition at line 57 of file Run.cpp.
References decodeInfo(), m_spyRaw, and m_spySize.
Referenced by Run(), and setNumber().
                                             {
  m_spyRaw = spyInfo ;
  m_spySize= m_spyRaw.size();
  decodeInfo();
}
spyChannel()
std::vector< int > Run::spyChannel () [inline]
Get accessor to member m_spyChannel
Returns
the current value of m_spyChannel
Definition at line 60 of file Run.h.
References m_spyChannel.
                                 {
    return m_spyChannel;
  }
spyEvt()
std::vector< int > Run::spyEvt () [inline]
Get accessor to member m_spyEvt
Returns
the current value of m_spyEvt
Definition at line 52 of file Run.h.
References m_spyEvt.
                             {
    return m_spyEvt;
  }
spyRaw()
std::vector< short > Run::spyRaw () [inline]
Definition at line 64 of file Run.h.
References m_spyRaw.
                               {
    return m_spyRaw;
  }
Member Data Documentation
m_date
ClassDef (Run,1) protected unsigned long Run::m_date
Definition at line 68 of file Run.h.
Referenced by ClassImp(), date(), Run(), and setDate().
m_spyChannel
std::vector< int > Run::m_spyChannel
Definition at line 78 of file Run.h.
Referenced by decodeInfo(), and spyChannel().
m_spyEvt
std::vector< int > Run::m_spyEvt
Definition at line 77 of file Run.h.
Referenced by decodeInfo(), and spyEvt().
m_spyRaw
std::vector<short> Run::m_spyRaw
Definition at line 75 of file Run.h.
Referenced by decodeInfo(), setSpy(), and spyRaw().
m_spySize
int Run::m_spySize
Definition at line 76 of file Run.h.
Referenced by ClassImp(), decodeInfo(), and setSpy().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloEvent/inc/Run.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloEvent/src/Run.cpp