progressbar.ProgressBar Class Reference
Public Member Functions
def __init__ (self, process=` `, start=0, end=10, width=12, fill='=', blank='.', format='running %(process) s [%(fill) s%(blank) s] %(progress) s%%', incremental=True)
def __add__ (self, increment)
def __str__ (self)
def set (self, value)
def reset (self)
Public Attributes
start
end
width
fill
blank
format
incremental
step
process
progress
Private Member Functions
def _get_progress (self, increment)
Static Private Attributes
def __repr__ = __str__
Detailed Description
ProgressBar class holds the options of the progress bar.
The options are:
    start   State from which start the progress. For example, if start is
            5 and the end is 10, the progress of this state is 50%
    end     State in which the progress has terminated.
    width   --
    fill    String to use for "filled" used to represent the progress
    blank   String to use for "filled" used to represent remaining space.
    format  Format
    incremental
Definition at line 4 of file progressbar.py.
Constructor & Destructor Documentation
__init__()
def progressbar.ProgressBar.__init__ (self, process = ` `, start = 0, end = 10, width = 12, fill = '=', blank = '.', format = 'running %(process)s [%(fill)s%(blank)s] %(progress)s%%', incremental = True)
Definition at line 16 of file progressbar.py.
    def __init__(self, process=" ", start=0, end=10, width=12, fill='=', blank='.',
      format='running %(process)s [%(fill)s%(blank)s] %(progress)s%%', incremental=True): super(ProgressBar, self).
      __init__()
        self.start = start
        self.end = end
        self.width = width
        self.fill = fill
        self.blank = blank
        self.format = format
        self.incremental = incremental
        self.step = 100 / float(width) #fix
        self.process = process
        self.reset()
Member Function Documentation
__add__()
def progressbar.ProgressBar.__add__ (self, increment)
Definition at line 30 of file progressbar.py.
References progressbar.ProgressBar._get_progress(), and progressbar.ProgressBar.progress.
    def __add__(self, increment):
        increment = self._get_progress(increment)
        if 100 > self.progress + increment:
            self.progress += increment
        else:
            self.progress = 100
        return self
    
__str__()
def progressbar.ProgressBar.__str__ (self)
Definition at line 38 of file progressbar.py.
References progressbar.ProgressBar.blank, progressbar.ProgressBar.fill, progressbar.ProgressBar.format, progressbar.ProgressBar.process, progressbar.ProgressBar.progress, progressbar.ProgressBar.step, and progressbar.ProgressBar.width.
    def __str__(self):
        progressed = int(self.progress / self.step) #fix
        fill = progressed * self.fill
        proc = self.process
        blank = (self.width - progressed) * self.blank
        return self.format % {'process': proc, 'fill': fill, 'blank': blank, 'progress': int(self.progress)
      }
_get_progress()
def progressbar.ProgressBar._get_progress (self, increment) [private]
Definition at line 47 of file progressbar.py.
References progressbar.ProgressBar.end.
Referenced by progressbar.ProgressBar.__add__(), progressbar.ProgressBar.reset(), and progressbar.ProgressBar.set().
    def _get_progress(self, increment):
        return float(increment * 100) / self.end
reset()
def progressbar.ProgressBar.reset (self)
Resets the current progress to the start point
Definition at line 58 of file progressbar.py.
References progressbar.ProgressBar._get_progress(), progressbar.ProgressBar.progress, and progressbar.ProgressBar.start.
    def reset(self):
        """Resets the current progress to the start point"""
        self.progress = self._get_progress(self.start)
        return self
set()
def progressbar.ProgressBar.set (self, value)
Definition at line 50 of file progressbar.py.
References progressbar.ProgressBar._get_progress(), and progressbar.ProgressBar.progress.
    def set(self, value):
        value = self._get_progress(value)
        if 100 > value:
            self.progress = value
        else:
            self.progress = 100
        return self
Member Data Documentation
__repr__
def progressbar.ProgressBar.__repr__ = __str__ [static], [private]
Definition at line 45 of file progressbar.py.
blank
progressbar.ProgressBar.blank
Definition at line 23 of file progressbar.py.
Referenced by progressbar.ProgressBar.__str__().
end
progressbar.ProgressBar.end
Definition at line 20 of file progressbar.py.
Referenced by progressbar.ProgressBar._get_progress().
fill
progressbar.ProgressBar.fill
Definition at line 22 of file progressbar.py.
Referenced by progressbar.ProgressBar.__str__().
format
progressbar.ProgressBar.format
Definition at line 24 of file progressbar.py.
Referenced by progressbar.ProgressBar.__str__().
incremental
progressbar.ProgressBar.incremental
Definition at line 25 of file progressbar.py.
process
progressbar.ProgressBar.process
Definition at line 27 of file progressbar.py.
Referenced by progressbar.ProgressBar.__str__().
progress
progressbar.ProgressBar.progress
Definition at line 35 of file progressbar.py.
Referenced by progressbar.ProgressBar.__add__(), progressbar.ProgressBar.__str__(), progressbar.ProgressBar.reset(), and progressbar.ProgressBar.set().
start
progressbar.ProgressBar.start
Definition at line 19 of file progressbar.py.
Referenced by progressbar.ProgressBar.reset().
step
progressbar.ProgressBar.step
Definition at line 26 of file progressbar.py.
Referenced by progressbar.ProgressBar.__str__().
width
progressbar.ProgressBar.width
Definition at line 21 of file progressbar.py.
Referenced by progressbar.ProgressBar.__str__().
The documentation for this class was generated from the following file:
/home/eleclhcb/LHCb/lbcat-cmake/CatPython/python/progressbar.py