TestSPI Class Reference
#include <include/TestSPI.h>
Classes
class TestSPI
Public Member Functions
TestSPI ()
Standard constructor.
virtual ~TestSPI ()
virtual StatusCode initialize ()
Destructor.
virtual StatusCode execute ()
virtual StatusCode finalize ()
void setAddress (int)
void setSubAddress (int)
Public Attributes
p7 = fig.add_subplot(2,3,6)
plot examples
p6=fig.add_subplot(4,3,6) p6.set_title('axes title') p6.set_xlabel('xlabel') p6.set_ylabel('ylabel') p6.text(3, 8, 'boxed italics text in data coords', style='italic', bbox={'facecolor':'red', 'alpha':0.5, 'pad':10}) p6.text(2, 6, r'an equation: $E=mc^2$', fontsize=15) p6.text(3, 2, unicode('unicode: Institut f\374r Festk\366rperphysik', 'latin-1')) p6.text(0.95, 0.01, 'colored text in axes coords', verticalalignment='bottom', horizontalalignment='right', transform=p6.transAxes, color='green', fontsize=15) p6.plot([2], [1], 'o') p6.annotate('annotate', xy=(2, 1), xytext=(3, 4), arrowprops=dict(facecolor='black', shrink=0.05)) p6.axis([0, 10, 0, 10])
h7 = obj.hist1d(0)
color
Protected Member Functions
TestSPI * clone ()
Private Attributes
FEB_v1 * m_board
SeqPGA * m_seqPga
TRandom * m_rnd
int m_add
int m_subadd
Additional Inherited Members
Detailed Description
Author
Frederic Machefert
Date
2010-01-07
Definition at line 20 of file TestSPI.h.
Constructor & Destructor Documentation
TestSPI()
TestSPI::TestSPI ()
Standard constructor.
Definition at line 23 of file TestSPI.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
{
  setName ("TestSPI");
  setType ("FEB_v1");
  setTitle("SPI interface test");
}
 TestSPI()
virtual TestSPI::~TestSPI () [inline], [virtual]
Definition at line 25 of file TestSPI.h.
References execute(), finalize(), initialize(), setAddress(), and setSubAddress().
{};
Member Function Documentation
clone()
TestSPI* TestSPI::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 35 of file TestSPI.h.
References TestSPI().
                  {
    return new TestSPI (*this);
  };
execute()
StatusCode TestSPI::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 61 of file TestSPI.cpp.
References Processus::dataFill(), m_rnd, m_seqPga, m_subadd, SeqPGA::spiRead(), SeqPGA::spiWrite(), and StatusCode::SUCCESS.
Referenced by ~TestSPI().
                              {
  int value = (0xFF)*m_rnd->Uniform();
  dataFill(0, value);
  m_seqPga->spiWrite(m_subadd, value);
  int tmp = m_seqPga->spiRead(m_subadd);
  dataFill(1, tmp);
  if (tmp!=value){
    dataFill(2, value);
    dataFill(3, tmp);
  }
  return StatusCode::SUCCESS;
}
finalize()
StatusCode TestSPI::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 77 of file TestSPI.cpp.
References StatusCode::SUCCESS.
Referenced by ~TestSPI().
                               {
  return StatusCode::SUCCESS;
}
initialize()
StatusCode TestSPI::initialize () [virtual]
Destructor.
Implements Processus.
Definition at line 33 of file TestSPI.cpp.
References Processus::addDataStream(), Processus::element(), m_add, m_board, m_rnd, m_seqPga, FEB_v1::seqPga(), SeqPGA::setSpiAdd(), StatusCode::SUCCESS, and Object::warning().
Referenced by ~TestSPI().
                                 {
  m_board=dynamic_cast<FEB_v1*>(element());
  
  if (!m_board){
    warning("TestSPI","No FEB_v1 board found. Interrupt.");
    return false;
  }
  m_seqPga = m_board->seqPga();
  if (!m_seqPga){
    warning("TestSPI","No SeqPga found. Interrupt.");
    return false;
  }
  m_rnd =new TRandom();
  m_seqPga->setSpiAdd(m_add);
  
  addDataStream("Input","Input value");
  addDataStream("Output","Output value");
  addDataStream("Errors","Error input value");
  addDataStream("Errors","Error output value");
  return StatusCode::SUCCESS;
}
setAddress()
void TestSPI::setAddress (int add)
Definition at line 84 of file TestSPI.cpp.
References Attrib::add(), and m_add.
Referenced by BOOST_PYTHON_MODULE(), and ~TestSPI().
                               {
  m_add = add;
}
setSubAddress()
void TestSPI::setSubAddress (int subadd)
Definition at line 88 of file TestSPI.cpp.
References m_subadd.
Referenced by BOOST_PYTHON_MODULE(), and ~TestSPI().
                                     {
  m_subadd = subadd;
}
Member Data Documentation
color
TestSPI.color
Definition at line 149 of file TestSPI.py.
h7
TestSPI.h7 = obj.hist1d(0)
Definition at line 147 of file TestSPI.py.
m_add
int TestSPI::m_add [private]
Definition at line 43 of file TestSPI.h.
Referenced by initialize(), and setAddress().
m_board
FEB_v1* TestSPI::m_board [private]
Definition at line 37 of file TestSPI.h.
Referenced by initialize().
m_rnd
TRandom* TestSPI::m_rnd [private]
Definition at line 42 of file TestSPI.h.
Referenced by execute(), and initialize().
m_seqPga
SeqPGA* TestSPI::m_seqPga [private]
Definition at line 41 of file TestSPI.h.
Referenced by execute(), and initialize().
m_subadd
int TestSPI::m_subadd [private]
Definition at line 44 of file TestSPI.h.
Referenced by execute(), and setSubAddress().
p7
TestSPI.p7 = fig.add_subplot(2,3,6)
plot examples
p6=fig.add_subplot(4,3,6) p6.set_title('axes title') p6.set_xlabel('xlabel') p6.set_ylabel('ylabel') p6.text(3, 8, 'boxed italics text in data coords', style='italic', bbox={'facecolor':'red', 'alpha':0.5, 'pad':10}) p6.text(2, 6, r'an equation: $E=mc^2$', fontsize=15) p6.text(3, 2, unicode('unicode: Institut f\374r Festk\366rperphysik', 'latin-1')) p6.text(0.95, 0.01, 'colored text in axes coords', verticalalignment='bottom', horizontalalignment='right', transform=p6.transAxes, color='green', fontsize=15) p6.plot([2], [1], 'o') p6.annotate('annotate', xy=(2, 1), xytext=(3, 4), arrowprops=dict(facecolor='black', shrink=0.05)) p6.axis([0, 10, 0, 10])
Definition at line 146 of file TestSPI.py.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/proc/TestSPI.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/python/proc/TestSPI.py
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/proc/TestSPI.cpp