ICPhaser Class Reference
#include <ICPhaser.h>
Public Types
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
Public Member Functions
ICPhaser ()
~ICPhaser ()
void setPhase (unsigned char channel, unsigned char value)
void setPhase (unsigned char ch0, unsigned char ch1, unsigned char ch2, unsigned char ch3)
unsigned int phase (unsigned int ch)
void read ()
void write ()
void status ()
void help ()
StatusCode init ()
void reset ()
void update ()
Register * regConfig ()
Register * regStatus ()
void setAddress (U8 address)
U8 address ()
Private Attributes
U8 m_address
unsigned char m_phase [4]
Register * m_regConfig
Register * m_regStatus
Additional Inherited Members
Detailed Description
Definition at line 19 of file ICPhaser.h.
Member Typedef Documentation
U16
typedef unsigned short ICPhaser::U16
Definition at line 22 of file ICPhaser.h.
U32
typedef unsigned long ICPhaser::U32
Definition at line 21 of file ICPhaser.h.
U8
typedef unsigned char ICPhaser::U8
Definition at line 23 of file ICPhaser.h.
Constructor & Destructor Documentation
ICPhaser()
ICPhaser::ICPhaser () [inline]
Definition at line 24 of file ICPhaser.h.
References Attrib::add(), Hierarchy::addChild(), IOdata::Byte, Object::debug(), IOdata::defDataU8(), Attrib::ELEMENT, Attrib::HARDWARE, IOobject::io(), m_phase, m_regConfig, m_regStatus, Object::setId(), Object::setName(), IOdata::setSubAddress(), Object::setType(), and IOdata::setWordSize().
            {
    setType("ICPhaser");
    setId(0);
    add(Attrib::ELEMENT); add (Attrib::HARDWARE);
    debug("ICPhaser built.","ICPhaser::ICPhaser");
    m_phase[0]=99;
    m_phase[1]=99;
    m_phase[2]=99;
    m_phase[3]=99;
    m_regConfig=new Register();
    m_regStatus=new Register();
    m_regConfig->setName("ConfigRegister");
    m_regStatus->setName("StatusRegister");
    m_regConfig->io()->setSubAddress(9);
    m_regStatus->io()->setSubAddress(19);
    m_regConfig->io()->defDataU8(3);
    m_regStatus->io()->defDataU8(2);
    m_regConfig->io()->setWordSize(IOdata::Byte);
    m_regStatus->io()->setWordSize(IOdata::Byte);
    addChild(m_regConfig);
    addChild(m_regStatus);
  }
 ICPhaser()
ICPhaser::~ICPhaser () [inline]
Definition at line 55 of file ICPhaser.h.
             {
  }
Member Function Documentation
address()
U8 ICPhaser::address () [inline]
Definition at line 133 of file ICPhaser.h.
References m_address.
Referenced by BOOST_PYTHON_MODULE(), read(), setAddress(), and status().
              {
    return m_address;
  }
help()
void ICPhaser::help () [inline], [virtual]
printout help for the element
Implements Element.
Definition at line 92 of file ICPhaser.h.
References Object::info(), and Object::name().
{ info("ICPhaser "+name()+". No help.","ICPhaser::help"); };
init()
StatusCode ICPhaser::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 99 of file ICPhaser.h.
References reset(), and StatusCode::SUCCESS.
                    {
    return StatusCode::SUCCESS;
  };
phase()
unsigned int ICPhaser::phase (unsigned int ch) [inline]
Definition at line 80 of file ICPhaser.h.
References m_phase, read(), status(), and write().
                                     {
    read() ;
    return m_phase[ch];
  }
read()
void ICPhaser::read ()
Definition at line 16 of file ICPhaser.cpp.
References address(), IOdata::dataU8(), Object::debug(), IOobject::io(), StatusCode::isFailure(), itos(), m_phase, m_regConfig, Object::name(), IOobject::read(), IOdata::setAddress(), IOdata::subAddress(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), phase(), and update().
                    {
  m_regConfig->io()->setAddress(address());
  U8* buffer=m_regConfig->io()->dataU8();
  buffer[2]=((m_regConfig->io()->subAddress())&0x1F)+(128);
  buffer[1]=0;
  buffer[0]=0;
  if (m_regConfig->read().isFailure()){
    warning("ICPhaser configuration register read failure.","ICPhaser::read");
  }
  else {
    U8* buffer=m_regConfig->io()->dataU8();
    m_phase[0] = buffer[0];
    m_phase[1] = buffer[1];
    debug("reading "+name()+" phases : "+
        itos(m_phase[0])+" "+
        itos(m_phase[1])+" "+
        itos(m_phase[2])+" "+
        itos(m_phase[3]),
        "ICPhaser::read");
  }
}
regConfig()
Register* ICPhaser::regConfig () [inline]
Definition at line 119 of file ICPhaser.h.
References m_regConfig.
Referenced by BOOST_PYTHON_MODULE().
                       {
    return m_regConfig;
  }
regStatus()
Register* ICPhaser::regStatus () [inline]
Definition at line 123 of file ICPhaser.h.
References m_regStatus.
Referenced by BOOST_PYTHON_MODULE().
                       {
    return m_regStatus;
  }
reset()
void ICPhaser::reset () [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 49 of file ICPhaser.cpp.
References IOdata::dataU8(), IOobject::io(), StatusCode::isFailure(), m_regConfig, Object::warning(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and init().
                    {
  U8* buffer=m_regConfig->io()->dataU8();
  buffer[2]=64;
  buffer[1]=0;
  buffer[0]=0;
  if (m_regConfig->write().isFailure()){
    warning("ICPhaser configuration register write failure. Cannot reset ICPhaser",
        "ICPhaser::write");
  }
}
setAddress()
void ICPhaser::setAddress (U8 address) [inline]
Definition at line 127 of file ICPhaser.h.
References address(), m_address, m_regConfig, m_regStatus, and IOobject::setAddress().
Referenced by BOOST_PYTHON_MODULE().
                             {
    m_address=address;
    m_regConfig->setAddress(m_address);
    m_regStatus->setAddress(m_address);
  }
setPhase() [1/2]
void ICPhaser::setPhase (unsigned char channel, unsigned char value) [inline]
Definition at line 58 of file ICPhaser.h.
References Object::info(), itos(), m_phase, and write().
Referenced by BOOST_PYTHON_MODULE().
                                                           {
    info("Set Phase "+itos(channel)+" to "
     +itos(value),"ICPhaser::setPhase");
    m_phase[channel]=value;
    write();
  }
setPhase() [2/2]
void ICPhaser::setPhase (unsigned char ch0, unsigned char ch1, unsigned char ch2, unsigned char ch3) [inline]
Definition at line 65 of file ICPhaser.h.
References Object::info(), itos(), m_phase, and write().
       {
    m_phase[0]=ch0;
    m_phase[1]=ch1;
    m_phase[2]=ch2;
    m_phase[3]=ch3;
    info("Set Phases to "+itos(ch0)+" "+itos(ch1)+" "
     +itos(ch2)+" "+itos(ch3));
    write();
  }
status()
void ICPhaser::status ()
Definition at line 38 of file ICPhaser.cpp.
References address(), IOdata::dataU8(), IOdata::dump(), IOobject::io(), StatusCode::isFailure(), m_regStatus, IOobject::read(), IOdata::setAddress(), IOdata::subAddress(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), and phase().
                      {
  m_regStatus->io()->setAddress(address());
  U8* buffer=m_regStatus->io()->dataU8();
  buffer[1]=((m_regStatus->io()->subAddress())&0x1F)+(160);
  buffer[0]=0;
  if (m_regStatus->read().isFailure()){
    warning("ICPhaser status register read failure.","ICPhaser::read");
  }
  m_regStatus->io()->dump(1);
}
update()
void ICPhaser::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 115 of file ICPhaser.h.
References read().
Referenced by AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
                 {
    read();
  };
write()
void ICPhaser::write ()
Definition at line 60 of file ICPhaser.cpp.
References IOdata::dataU8(), Object::debug(), IOdata::dump(), IOobject::io(), StatusCode::isFailure(), itos(), m_phase, m_regConfig, Object::name(), IOdata::subAddress(), Object::warning(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), phase(), and setPhase().
                    {
  U8* buffer=m_regConfig->io()->dataU8();
  buffer[2]=(m_regConfig->io()->subAddress())&0x1F;
  buffer[1]=m_phase[0]&0xff;
  buffer[0]=m_phase[1]&0xff;
  // phase[2] and phase[3] not implemented - only for test purpose
  debug("Setting "+name()+" phases : "+itos(m_phase[0])+" "+
      itos(m_phase[1])+" "+itos(m_phase[2])+" "+itos(
      m_phase[3]),
      "ICPhaser::write");
  m_regConfig->io()->dump(0);
  if (m_regConfig->write().isFailure()){
    warning("ICPhaser configuration register write failure.",
        "ICPhaser::write");
  }
}
Member Data Documentation
m_address
U8 ICPhaser::m_address [private]
Definition at line 138 of file ICPhaser.h.
Referenced by address(), and setAddress().
m_phase
unsigned char ICPhaser::m_phase[4] [private]
Definition at line 139 of file ICPhaser.h.
Referenced by ICPhaser(), phase(), read(), setPhase(), and write().
m_regConfig
Register* ICPhaser::m_regConfig [private]
Definition at line 140 of file ICPhaser.h.
Referenced by ICPhaser(), read(), regConfig(), reset(), setAddress(), and write().
m_regStatus
Register* ICPhaser::m_regStatus [private]
Definition at line 141 of file ICPhaser.h.
Referenced by ICPhaser(), regStatus(), setAddress(), and status().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/ICPhaser.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/ICPhaser.cpp