StorageFifo Class Reference
#include <inc/StorageFifo.h>
Classes
class StorageFifo
Public Member Functions
StorageFifo ()
Standard constructor.
virtual ~StorageFifo ()
Destructor.
virtual StatusCode initialize ()
virtual StatusCode execute ()
virtual StatusCode finalize ()
Protected Member Functions
StorageFifo * clone ()
Private Attributes
Proto40MHz_v1 * m_board
A3PE * m_pga
RAM * m_fifo
TH1D * m_h1
TH1D * m_h2
TH1D * m_h3
TH1D * m_h4
TH1D * m_h5
TH1D * m_h6
TH1D * m_h7
TH1D * m_h8
int m_depth
Additional Inherited Members
Detailed Description
Author
Date
2006-10-23
Definition at line 18 of file StorageFifo.h.
Constructor & Destructor Documentation
StorageFifo()
StorageFifo::StorageFifo ()
Standard constructor.
Definition at line 20 of file StorageFifo.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
                           :
  m_h1(0),
  m_h2(0),
  m_h3(0),
  m_h4(0),
  m_h5(0),
  m_h6(0),
  m_h7(0),
  m_h8(0)
{
  setName ("StorageFifo");
  setType ("Proto40MHz_v1");
  setTitle("Proto40MHz_v1 Storage Fifo");
}
 StorageFifo()
StorageFifo::~StorageFifo () [virtual]
Destructor.
Definition at line 37 of file StorageFifo.cpp.
{}
Member Function Documentation
clone()
StorageFifo* StorageFifo::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 29 of file StorageFifo.h.
References StorageFifo().
                      {
    return new StorageFifo (*this);
  }
execute()
StatusCode StorageFifo::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 94 of file StorageFifo.cpp.
References A3PE::acquisition(), IOdata::dataU8(), Object::debug(), IOobject::io(), m_depth, m_fifo, m_h1, m_h2, m_h3, m_h4, m_h5, m_h6, m_h7, m_h8, m_pga, IOobject::read(), and StatusCode::SUCCESS.
                                  {
  debug("StorageFifo" , "execute");
  
  m_pga->acquisition();
  m_fifo->read();
  
  int val[12];
  
  for (int d=0; d<m_depth; ++d){
    val[0] =m_fifo->io()->dataU8(0+12*d);
    val[1] =m_fifo->io()->dataU8(1+12*d);
    val[2] =m_fifo->io()->dataU8(2+12*d);
    val[3] =m_fifo->io()->dataU8(3+12*d);
    val[4] =m_fifo->io()->dataU8(4+12*d);
    val[5] =m_fifo->io()->dataU8(5+12*d);
    val[6] =m_fifo->io()->dataU8(6+12*d);
    val[7] =m_fifo->io()->dataU8(7+12*d);
    val[8] =m_fifo->io()->dataU8(8+12*d);
    val[9] =m_fifo->io()->dataU8(9+12*d);
    val[10]=m_fifo->io()->dataU8(10+12*d);
    val[11]=m_fifo->io()->dataU8(11+12*d);
    
    m_h1->Fill(d+0.5,val[0]+((val[1]&0xf)<<8));
    m_h2->Fill(d+0.5,(val[1]>>4)+(val[2]<<4));
    m_h3->Fill(d+0.5,val[3]+((val[4]&0xf)<<8));
    m_h4->Fill(d+0.5,(val[4]>>4)+(val[5]<<4));
    m_h5->Fill(d+0.5,val[6]+((val[7]&0xf)<<8));
    m_h6->Fill(d+0.5,(val[7]>>4)+(val[8]<<4));
    m_h7->Fill(d+0.5,val[9]+((val[10]&0xf)<<8));
    m_h8->Fill(d+0.5,(val[10]>>4)+(val[11]<<4));
  }
  
  return StatusCode::SUCCESS;
}
finalize()
StatusCode StorageFifo::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 132 of file StorageFifo.cpp.
References StatusCode::SUCCESS.
                                   {
  return StatusCode::SUCCESS;
}
initialize()
StatusCode StorageFifo::initialize () [virtual]
processus initialisation virtual function
Implements Processus.
Definition at line 44 of file StorageFifo.cpp.
References Proto40MHz_v1::a3pe(), Processus::addHisto1d(), Object::debug(), Processus::element(), A3PE::fifoDepth(), Object::info(), m_board, m_depth, m_fifo, m_h1, m_h2, m_h3, m_h4, m_h5, m_h6, m_h7, m_h8, m_pga, Object::name(), A3PE::setEnableADC(), A3PE::setSoftwareTrigger(), A3PE::setWriteStorageFifoUsb(), A3PE::storageRam(), StatusCode::SUCCESS, Object::type(), and Object::warning().
                                     {
  debug("StorageFifo" , "initialize");
  info("");
  info("____________________________");
  info("Proto 40 MHZ - Fifo dump");
  info(" =>" + element()->path() + " " +
      element()->name() + " " + element()->type());
  m_board=dynamic_cast<Proto40MHz_v1*>(element());
  if (!m_board){
    warning("StorageFifo","No Proto40MHz_v1 board found. Interrupt.");
    return false;
  }
  m_pga=m_board->a3pe();
  m_pga->setSoftwareTrigger(true);
  m_pga->setWriteStorageFifoUsb(false);
  
  m_fifo = m_pga->storageRam();
  
  for (int i=0; i<8; ++i) m_pga->setEnableADC(i,true);
  
  m_depth=m_pga->fifoDepth();
  
  m_h1=new TH1D("Channel1" , "Data values channel 1" , m_depth , 0. , float(
      m_depth));
  m_h2=new TH1D("Channel2" , "Data values channel 2" , m_depth , 0. , float(
      m_depth));
  m_h3=new TH1D("Channel3" , "Data values channel 3" , m_depth , 0. , float(
      m_depth));
  m_h4=new TH1D("Channel4" , "Data values channel 4" , m_depth , 0. , float(
      m_depth));
  m_h5=new TH1D("Channel5", "Data values channel 5" , m_depth , 0. , float(
      m_depth));
  m_h6=new TH1D("Channel6" , "Data values channel 6" , m_depth , 0. , float(
      m_depth));
  m_h7=new TH1D("Channel7" , "Data values channel 7" , m_depth , 0. , float(
      m_depth));
  m_h8=new TH1D("Channel8" , "Data values channel 8" , m_depth , 0. , float(
      m_depth));
  addHisto1d(m_h1);
  addHisto1d(m_h2);
  addHisto1d(m_h3);
  addHisto1d(m_h4);
  addHisto1d(m_h5);
  addHisto1d(m_h6);
  addHisto1d(m_h7);
  addHisto1d(m_h8);
  return StatusCode::SUCCESS;
}
Member Data Documentation
m_board
Proto40MHz_v1* StorageFifo::m_board [private]
Definition at line 34 of file StorageFifo.h.
Referenced by initialize().
m_depth
int StorageFifo::m_depth [private]
Definition at line 38 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_fifo
RAM* StorageFifo::m_fifo [private]
Definition at line 36 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_h1
TH1D* StorageFifo::m_h1 [private]
Definition at line 37 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_h2
TH1D * StorageFifo::m_h2 [private]
Definition at line 37 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_h3
TH1D * StorageFifo::m_h3 [private]
Definition at line 37 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_h4
TH1D * StorageFifo::m_h4 [private]
Definition at line 37 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_h5
TH1D * StorageFifo::m_h5 [private]
Definition at line 37 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_h6
TH1D * StorageFifo::m_h6 [private]
Definition at line 37 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_h7
TH1D * StorageFifo::m_h7 [private]
Definition at line 37 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_h8
TH1D * StorageFifo::m_h8 [private]
Definition at line 37 of file StorageFifo.h.
Referenced by execute(), and initialize().
m_pga
A3PE* StorageFifo::m_pga [private]
Definition at line 35 of file StorageFifo.h.
Referenced by execute(), and initialize().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/inc/proc/StorageFifo.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/src/proc/StorageFifo.cpp