EmulateFE Class Reference
#include <inc/EmulateFE.h>
Public Types
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
Public Member Functions
EmulateFE ()
Standard constructor.
virtual ~EmulateFE ()
Destructor.
virtual StatusCode initialize ()
virtual StatusCode execute ()
virtual StatusCode finalize ()
StatusCode setFile (std::string filename)
std::string file ()
StatusCode setNTriggers (int ntriggersMax)
int nTriggers ()
StatusCode setGenerationType (bool type)
bool generationType ()
StatusCode setSignalRate (float signalRate)
float signalRate ()
StatusCode setPedestal (float pedestal)
float pedestal ()
StatusCode setNoise (float noise)
float noise ()
Protected Member Functions
EmulateFE * clone ()
StatusCode generateValues ()
StatusCode generateFile ()
StatusCode processingFE ()
Private Attributes
TRandom m_random
FEB_v1 * m_board
std::string m_filename
int m_nFile
Options * m_options
int m_typeGeneration
float m_signalRate
float m_pedestal
float m_noise
int m_adcin [16384]
int m_ntriggersMax
int m_ntriggers
Additional Inherited Members
Detailed Description
Author
Date
2012-07-12
Definition at line 18 of file EmulateFE.h.
Member Typedef Documentation
U16
typedef unsigned short EmulateFE::U16
Definition at line 21 of file EmulateFE.h.
U32
typedef unsigned long EmulateFE::U32
Definition at line 20 of file EmulateFE.h.
U8
typedef unsigned char EmulateFE::U8
Definition at line 22 of file EmulateFE.h.
Constructor & Destructor Documentation
EmulateFE()
EmulateFE::EmulateFE ()
Standard constructor.
Definition at line 25 of file EmulateFE.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
                       :
  m_filename(std::string("")),
  m_typeGeneration (0),
  m_signalRate(0.05),
  m_pedestal(128),
  m_noise(30),
  m_ntriggersMax(0),
  m_ntriggers(0),
  m_options(application()->options())
{
  setName ("EmulateFE");
  setType ("FEB_v1");
  setTitle("FEB_v1 EmulateFE processing");
}
 EmulateFE()
EmulateFE::~EmulateFE () [virtual]
Destructor.
Definition at line 42 of file EmulateFE.cpp.
{}
Member Function Documentation
clone()
EmulateFE* EmulateFE::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 87 of file EmulateFE.h.
References EmulateFE(), generateFile(), generateValues(), and processingFE().
                    {
    return new EmulateFE (*this);
  }
execute()
StatusCode EmulateFE::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 76 of file EmulateFE.cpp.
References Options::dataStorage(), Object::debug(), generateFile(), generateValues(), m_filename, m_ntriggersMax, m_options, processingFE(), and StatusCode::SUCCESS.
                                {
  debug("EmulateFE" , "execute");
  generateValues();
  if (m_filename!=std::string("") & m_options->dataStorage()){
    generateFile();
  }
  if (m_ntriggersMax>0){
    processingFE();
  }
  return StatusCode::SUCCESS;
}
file()
std::string EmulateFE::file () [inline]
Definition at line 36 of file EmulateFE.h.
References m_filename.
                  {
    return m_filename;
  }
finalize()
StatusCode EmulateFE::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 91 of file EmulateFE.cpp.
References StatusCode::SUCCESS.
                                 {
  return StatusCode::SUCCESS;
}
generateFile()
StatusCode EmulateFE::generateFile () [protected]
Definition at line 133 of file EmulateFE.cpp.
References itos(), m_adcin, m_filename, m_nFile, m_noise, m_options, m_pedestal, m_signalRate, m_typeGeneration, Options::storageFullPath(), and StatusCode::SUCCESS.
Referenced by clone(), and execute().
                                    {
  std::string filename = m_options->storageFullPath();
  filename.append("/");
  filename.append(m_filename);
  filename.append("_");
  filename.append(itos(m_nFile));
  filename.append(".data");
  std::ofstream inputData;
  inputData.open(filename.c_str());
  time_t rawtime;
  struct tm * timeinfo;
  time (&rawtime);
  timeinfo = localtime (&rawtime);
  char* timechar = asctime (timeinfo) ;
  std::string timing = std::string(timechar,24) + " ";
  if (!inputData.fail()){
    inputData<<"#################################################"<<std::endl;
    inputData<<"# Date : "<<timing<<std::endl;
    inputData<<"# Type of Generation : "<<m_typeGeneration<<std::endl;
    inputData<<"# 0 : Flat generation "<<std::endl;
    inputData<<"# 1 : Gaussian noise + Flat signal "<<std::endl;
    inputData<<"# Signal rate : "<<m_signalRate<<std::endl;
    inputData<<"# Pedestal : "<<m_pedestal<<std::endl;
    inputData<<"# Noise width : "<<m_noise<<std::endl;
    inputData<<"#################################################"<<std::endl;
    for (int i=0; i<4096; ++i){
      char buffer[50];
      sprintf (buffer, "%5i %5i %5i %5i \n",m_adcin[4*i], m_adcin[4*i+1],
      m_adcin[4*i+2], m_adcin[4*i+3]);
      inputData<<buffer;
    }
  }
  m_nFile++;
  return StatusCode::SUCCESS;
}
generateValues()
StatusCode EmulateFE::generateValues () [protected]
Definition at line 98 of file EmulateFE.cpp.
References m_adcin, m_noise, m_pedestal, m_random, m_signalRate, m_typeGeneration, and StatusCode::SUCCESS.
Referenced by clone(), and execute().
                                      {
  if (m_typeGeneration==0){
    for (int i=0; i<4096; ++i){
      m_adcin[4*i] = m_random.Rndm()*4096;
      m_adcin[4*i+1] = m_random.Rndm()*4096;
      m_adcin[4*i+2] = m_random.Rndm()*4096;
      m_adcin[4*i+3] = m_random.Rndm()*4096;
    }
  }
  else {
    for (int i=0; i<4096; ++i){
      float noise0 = m_random.Gaus(m_pedestal, m_noise);
      float noise1 = m_random.Gaus(m_pedestal, m_noise);
      float noise2 = m_random.Gaus(m_pedestal, m_noise);
      float noise3 = m_random.Gaus(m_pedestal, m_noise);
      float sig0 = m_random.Rndm();
      float sig1 = m_random.Rndm();
      float sig2 = m_random.Rndm();
      float sig3 = m_random.Rndm();
      if (m_random.Rndm()<m_signalRate){ m_adcin[4*i]=noise0+(
      m_random.Rndm()*(4096-noise0)); }
      else m_adcin[4*i]=noise0;
      if (m_random.Rndm()<m_signalRate){ m_adcin[4*i+1]=noise1+(
      m_random.Rndm()*(4096-noise1)); }
      else m_adcin[4*i+1]=noise1;
      if (m_random.Rndm()<m_signalRate){ m_adcin[4*i+2]=noise2+(
      m_random.Rndm()*(4096-noise2)); }
      else m_adcin[4*i+2]=noise2;
      if (m_random.Rndm()<m_signalRate){ m_adcin[4*i+3]=noise3+(
      m_random.Rndm()*(4096-noise3)); }
      else m_adcin[4*i+3]=noise3;
    }
  }
  return StatusCode::SUCCESS;
}
generationType()
bool EmulateFE::generationType () [inline]
Definition at line 54 of file EmulateFE.h.
References m_typeGeneration.
                       {
    return m_typeGeneration;
  }
initialize()
StatusCode EmulateFE::initialize () [virtual]
processus initialisation virtual function
Implements Processus.
Definition at line 49 of file EmulateFE.cpp.
References Options::dataStorage(), Object::debug(), Processus::element(), StatusCode::FAILURE, Object::info(), m_board, m_filename, m_nFile, m_ntriggersMax, m_options, Object::name(), StatusCode::SUCCESS, Object::type(), and Object::warning().
                                   {
  debug("EmulateFE" , "initialize");
  info("");
  info("____________________________");
  info("FE emulation");
  info(" =>" + element()->path() + " " +
      element()->name() + " " + element()->type());
  if (m_filename==std::string("")){
    warning("No ADC output data storage.");
    if (m_ntriggersMax<1){
      warning("No output file storage and no trigger. There is no processing to perform. Bad
       configuration.");
      return StatusCode::FAILURE;
    }
  }
  if ((m_filename!=std::string(""))&(m_options->dataStorage())){
    info("Input data will be stored in files "+m_filename);
  }
  m_nFile = 0;
  m_board=dynamic_cast<FEB_v1*>(element());
  return StatusCode::SUCCESS;
}
noise()
float EmulateFE::noise () [inline]
Definition at line 81 of file EmulateFE.h.
References m_noise.
Referenced by setNoise().
               {
    return m_noise;
  }
nTriggers()
int EmulateFE::nTriggers () [inline]
Definition at line 45 of file EmulateFE.h.
References m_ntriggersMax.
                 {
    return m_ntriggersMax;
  }
pedestal()
float EmulateFE::pedestal () [inline]
Definition at line 72 of file EmulateFE.h.
References m_pedestal.
Referenced by setPedestal().
                  {
    return m_pedestal;
  }
processingFE()
StatusCode EmulateFE::processingFE () [protected]
Definition at line 173 of file EmulateFE.cpp.
References StatusCode::SUCCESS.
Referenced by clone(), and execute().
                                    {
  return StatusCode::SUCCESS;
}
setFile()
StatusCode EmulateFE::setFile (std::string filename) [inline]
Definition at line 31 of file EmulateFE.h.
References m_filename, and StatusCode::SUCCESS.
                                         {
    m_filename=filename;
    return StatusCode::SUCCESS;
  };
setGenerationType()
StatusCode EmulateFE::setGenerationType (bool type) [inline]
Definition at line 49 of file EmulateFE.h.
References m_typeGeneration, StatusCode::SUCCESS, and Object::type().
                                          {
    m_typeGeneration=type;
    return StatusCode::SUCCESS;
  };
setNoise()
StatusCode EmulateFE::setNoise (float noise) [inline]
Definition at line 76 of file EmulateFE.h.
References m_noise, noise(), and StatusCode::SUCCESS.
                                   {
    m_noise=noise;
    return StatusCode::SUCCESS;
  };
setNTriggers()
StatusCode EmulateFE::setNTriggers (int ntriggersMax) [inline]
Definition at line 40 of file EmulateFE.h.
References m_ntriggersMax, and StatusCode::SUCCESS.
                                            {
    m_ntriggersMax = ntriggersMax;
    return StatusCode::SUCCESS;
  };
setPedestal()
StatusCode EmulateFE::setPedestal (float pedestal) [inline]
Definition at line 67 of file EmulateFE.h.
References m_pedestal, pedestal(), and StatusCode::SUCCESS.
                                         {
    m_pedestal=pedestal;
    return StatusCode::SUCCESS;
  };
setSignalRate()
StatusCode EmulateFE::setSignalRate (float signalRate) [inline]
Definition at line 58 of file EmulateFE.h.
References m_signalRate, signalRate(), and StatusCode::SUCCESS.
                                             {
    m_signalRate=signalRate;
    return StatusCode::SUCCESS;
  };
signalRate()
float EmulateFE::signalRate () [inline]
Definition at line 63 of file EmulateFE.h.
References m_signalRate.
Referenced by setSignalRate().
                    {
    return m_signalRate;
  }
Member Data Documentation
m_adcin
int EmulateFE::m_adcin[16384] [private]
Definition at line 106 of file EmulateFE.h.
Referenced by generateFile(), and generateValues().
m_board
FEB_v1* EmulateFE::m_board [private]
Definition at line 97 of file EmulateFE.h.
Referenced by initialize().
m_filename
std::string EmulateFE::m_filename [private]
Definition at line 98 of file EmulateFE.h.
Referenced by execute(), file(), generateFile(), initialize(), and setFile().
m_nFile
int EmulateFE::m_nFile [private]
Definition at line 99 of file EmulateFE.h.
Referenced by generateFile(), and initialize().
m_noise
float EmulateFE::m_noise [private]
Definition at line 105 of file EmulateFE.h.
Referenced by generateFile(), generateValues(), noise(), and setNoise().
m_ntriggers
int EmulateFE::m_ntriggers [private]
Definition at line 108 of file EmulateFE.h.
m_ntriggersMax
int EmulateFE::m_ntriggersMax [private]
Definition at line 107 of file EmulateFE.h.
Referenced by execute(), initialize(), nTriggers(), and setNTriggers().
m_options
Options* EmulateFE::m_options [private]
Definition at line 101 of file EmulateFE.h.
Referenced by execute(), generateFile(), and initialize().
m_pedestal
float EmulateFE::m_pedestal [private]
Definition at line 104 of file EmulateFE.h.
Referenced by generateFile(), generateValues(), pedestal(), and setPedestal().
m_random
TRandom EmulateFE::m_random [private]
Definition at line 96 of file EmulateFE.h.
Referenced by generateValues().
m_signalRate
float EmulateFE::m_signalRate [private]
Definition at line 103 of file EmulateFE.h.
Referenced by generateFile(), generateValues(), setSignalRate(), and signalRate().
m_typeGeneration
int EmulateFE::m_typeGeneration [private]
Definition at line 102 of file EmulateFE.h.
Referenced by generateFile(), generateValues(), generationType(), and setGenerationType().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/proc/EmulateFE.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/proc/EmulateFE.cpp