Event Class Reference
#include <include/Event.h>
Public Member Functions
Event ()
Standard constructor.
virtual ~Event ()
Destructor.
void setRun (unsigned long irun)
void Clear (Option_t *option=``)
void newEvt ()
void addData (int, int, int)
TClonesArray * getData ()
Public Attributes
ClassDef(Event, 1) protected unsigned long nData
TClonesArray * raw
TRef fLastData
Static Public Attributes
static TClonesArray * fgData
Detailed Description
Author
Frédéric Machefert
Date
2004-10-04
Definition at line 23 of file Event.h.
Constructor & Destructor Documentation
Event()
Event::Event ()
Standard constructor.
 Event()
Event::~Event () [virtual]
Destructor.
Definition at line 35 of file Event.cpp.
References Clear().
              {
  Clear();
}
Member Function Documentation
addData()
void Event::addData (int evt, int chl, int value)
Definition at line 40 of file Event.cpp.
References fLastData, nData, and raw.
Referenced by setRun().
                                                   {
  TClonesArray &rawdata = *raw;
   Data *val = new(rawdata[nData++]) Data(evt , chl , value);
   //Save reference to last Data in the collection of Datas
   fLastData = val;
}
Clear()
void Event::Clear (Option_t * option = ``)
Definition at line 48 of file Event.cpp.
References raw.
Referenced by setRun(), and ~Event().
{
  raw->Clear("C"); //will also call Data::Clear
}
getData()
TClonesArray* Event::getData () [inline]
Definition at line 34 of file Event.h.
References fgData.
{ return fgData;}
newEvt()
void Event::newEvt ()
Definition at line 54 of file Event.cpp.
Referenced by setRun().
{
   EvtHdr.newEvt();
   /*
   data->Clear("C"); //will also call Data::Clear
   nData = 0 ;
  */
}
setRun()
void Event::setRun (unsigned long irun) [inline]
Definition at line 28 of file Event.h.
References addData(), Clear(), and newEvt().
                                     {
    EvtHdr.setRun (irun);
  }
Member Data Documentation
fgData
TClonesArray* Event::fgData [static]
Definition at line 42 of file Event.h.
Referenced by getData().
fLastData
TRef Event::fLastData
Definition at line 43 of file Event.h.
Referenced by addData().
nData
ClassDef (Event,1) protected unsigned long Event::nData
Definition at line 35 of file Event.h.
Referenced by addData().
raw
TClonesArray* Event::raw
Definition at line 41 of file Event.h.
Referenced by addData(), and Clear().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloEvent/inc/Event.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloEvent/src/Event.cpp