Acquisition Class Reference
#include <inc/Acquisition.h>
Classes
class Acquisition
Public Types
enum states { ERR =-1,
NOT_OK,
OK
 }
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
Acquisition ()
Standard constructor.
virtual ~Acquisition ()
Destructor.
virtual StatusCode initialize ()
virtual StatusCode execute ()
virtual StatusCode finalize ()
StatusCode setDepth (unsigned int)
unsigned int depth ()
StatusCode setChannels (unsigned int)
unsigned int channels ()
StatusCode setTrigger (bool trig)
bool trigger ()
void setStoreTree (bool store_tree)
bool storeTree ()
void setStoreTrend (bool store_hist)
bool storeTrend ()
void setStoreSample (bool store_sample)
bool storeSample ()
void setDeadTime (int deadtime)
int deadTime ()
void setSample (int nsample)
int sample ()
void setNBins (int nbins)
int nBins ()
void setMinRange (float minrange)
float minRange ()
void setMaxRange (float maxrange)
float maxRange ()
A3PE * a3pe ()
Acquisition ()
Standard constructor.
virtual ~Acquisition ()
Destructor.
virtual StatusCode initialize ()
virtual StatusCode execute ()
virtual StatusCode finalize ()
StatusCode setDepth (unsigned int)
unsigned int depth ()
StatusCode setChannels (unsigned int)
unsigned int channels ()
StatusCode setTrigger (bool trig)
bool trigger ()
void setStoreTree (bool store_tree)
bool storeTree ()
void setStoreTrend (bool store_hist)
bool storeTrend ()
void setStoreSample (bool store_sample)
bool storeSample ()
void setDeadTime (int deadtime)
int deadTime ()
void setSample (int nsample)
int sample ()
void setNBins (int nbins)
int nBins ()
void setMinRange (float minrange)
float minRange ()
void setMaxRange (float maxrange)
float maxRange ()
StatusCode startProcessing ()
StatusCode endProcessing ()
void clean ()
void setStorage (std::string storage)
Data * data ()
std::vector< double > data (unsigned int row)
std::vector< double > data (std::string name)
Histo1D * hist1d (unsigned int row)
Histo2D * hist2d (unsigned int row)
void addDataStream (std::string name, std::string title)
void addHisto1d (TH1D *h)
void addHisto2d (TH2D *h)
StatusCode dataFill (int i, double val)
StatusCode dataFill (std::string name, double val)
std::string storage ()
void setElement (Element *element)
Element * element ()
void incNErrors ()
void setNErrors (unsigned int)
unsigned int nErrors ()
TFile * rootFile ()
void openRootFile ()
void closeRootFile ()
void startChrono ()
void setLogMsg (std::string logMsg)
std::string logMsg ()
void setState (int state)
double elapsedTime ()
double elapsedTime (time_t start)
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Member Functions
Acquisition * clone ()
unsigned int decodeFormat (unsigned int, unsigned int, RAM *)
Acquisition * clone ()
unsigned int decodeFormat (unsigned int, unsigned int, RAM *)
Protected Attributes
Element * m_element
std::string m_attribString [10]
Private Attributes
bool m_store_tree
bool m_store_hist
bool m_store_sample
TTree * m_tree
Int_t m_runNumber
Int_t m_evtNumber
Int_t m_sample
Int_t m_channel [8]
Int_t m_chEnable [8]
Int_t m_nch
double m_timestamp
int m_channels
int m_depth
Proto40MHz_v1 * m_board
A3PE * m_pga
RAM * m_fifo
bool m_trig
TH1D * m_a [8]
TH1D * m_s [8]
TH1D * m_hsample [8]
double v [8 *m_depthmax]
double v2 [8 *m_depthmax]
unsigned int m_nsample
unsigned int m_nbins
float m_minRange
float m_maxRange
int m_deadtime
FEB_v1 * m_board
Static Private Attributes
static const unsigned int m_depthmax = 512
Detailed Description
Author
Date
2006-10-23
Definition at line 20 of file Acquisition.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
states
enum Processus::states [inherited]
Enumerator
ERR
NOT_OK
OK
Definition at line 34 of file Processus.h.
{ ERR=-1 , NOT_OK , OK };
Constructor & Destructor Documentation
Acquisition() [1/2]
Acquisition::Acquisition ()
Standard constructor.
Definition at line 22 of file Acquisition.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
                           :
  m_store_tree(true),
  m_store_hist(false),
  m_store_sample(true),
  m_channels(0xFF),
  m_depth(5),
  m_trig(true),
  m_nsample(0),
  m_nbins(100),
  m_minRange(0.),
  m_maxRange(4096.),
  m_deadtime(1000.)
{
  setName ("Acquisition");
  setType ("Proto40MHz_v1");
  setTitle("Proto40MHz_v1 data acquisition");
}
 Acquisition() [1/2]
Acquisition::~Acquisition () [virtual]
Destructor.
Definition at line 42 of file Acquisition.cpp.
{}
Acquisition() [2/2]
Acquisition::Acquisition ()
Standard constructor.
 Acquisition() [2/2]
virtual Acquisition::~Acquisition () [virtual]
Destructor.
Member Function Documentation
a3pe()
A3PE* Acquisition::a3pe () [inline]
Definition at line 93 of file Acquisition.h.
References m_pga.
{return m_pga;}
add()
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), TestI2C::setAddress(), TestSPI::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
addDataStream()
void Processus::addDataStream (std::string name, std::string title) [inline], [inherited]
Definition at line 153 of file Processus.h.
Referenced by RegisterTest::initialize(), TestSuite::initialize(), TestUSB::initialize(), TestI2C::initialize(), TestSPI::initialize(), UsbFTInterfaceTest::initialize(), ADCMeasurement::initialize(), and CurrentMeasurement::initialize().
                                                       {
    m_data->addDataStream(name, title);
  }
addHisto1d()
void Processus::addHisto1d (TH1D * h) [inline], [inherited]
Definition at line 160 of file Processus.h.
Referenced by StorageFifo::initialize(), StorageFifoAcquisition::initialize(), TestSuite::initialize(), A3PE_BitFlip::initialize(), and initialize().
                           {
    m_data->addHisto1d(h);
  }
addHisto2d()
void Processus::addHisto2d (TH2D * h) [inline], [inherited]
Definition at line 167 of file Processus.h.
Referenced by TestSuite::initialize().
                           {
    m_data->addHisto2d(h);
  }
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
channels() [1/2]
unsigned int Acquisition::channels () [inline]
Definition at line 32 of file Acquisition.h.
References m_channels.
{return m_channels;};
channels() [2/2]
unsigned int Acquisition::channels () [inline]
Definition at line 34 of file Acquisition.h.
References m_channels.
Referenced by BOOST_PYTHON_MODULE(), setChannels(), and Acquisition.Acquisition::update().
{return m_channels;};
clean()
void Processus::clean () [inline], [inherited]
Definition at line 85 of file Processus.h.
Referenced by Application::prepare().
  {
    m_element=0;
    if (0!=m_state) {
      delete m_state;
      m_state=0;
    }
#ifdef _NETWORK_
    warning("Cleaning state service : should it be done ?","Processus::clean")
      if (0!=m_stateService)
      {
        delete m_stateService;
      }
#endif
  }
clone() [1/2]
Acquisition* Acquisition::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 94 of file Acquisition.h.
References Acquisition(), decodeFormat(), m_channel, m_channels, m_chEnable, m_depth, m_depthmax, m_evtNumber, m_nch, m_runNumber, m_sample, m_store_hist, m_store_sample, m_store_tree, m_timestamp, and m_tree.
                      {
    return new Acquisition (*this);
  }
clone() [2/2]
Acquisition* Acquisition::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 96 of file Acquisition.h.
References Acquisition(), and decodeFormat().
                      {
    return new Acquisition (*this);
  }
closeRootFile()
void Processus::closeRootFile () [inherited]
Close Root file if already opened and requested
Definition at line 160 of file Processus.cpp.
References Options::dataFileFullName(), Options::dataStorage(), Object::info(), Processus::m_options, and Processus::m_rootFile.
Referenced by Processus::endProcessing(), RegisterTest::finalize(), UsbFTInterfaceTest::finalize(), and PhaserRampExec::finalize().
                                {
  if (0!= m_rootFile && m_options->dataStorage()){
    m_rootFile->Write();
        std::string mess=std::string("Closing root file ");
        mess.append(m_options->dataFileFullName());
        info(mess,"closeRootFile");
    m_rootFile->Delete();
    m_rootFile = 0;
  }
}
data() [1/3]
Data* Processus::data () [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 114 of file Processus.h.
Referenced by StorageFifoAcquisition::execute(), and export_proc().
              {
    return m_data;
  }
data() [2/3]
std::vector<double> Processus::data (unsigned int row) [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 122 of file Processus.h.
                                          {
    return m_data->vector(row);
  }
data() [3/3]
std::vector<double> Processus::data (std::string name) [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 130 of file Processus.h.
                                        {
    return m_data->vector(name);
  }
dataFill() [1/2]
StatusCode Processus::dataFill (int i, double val) [inline], [inherited]
Set data stream with value
Returns
the StatusCode
Definition at line 175 of file Processus.h.
References StatusCode::FAILURE, and StatusCode::SUCCESS.
Referenced by TestSuite::execute(), TestI2C::execute(), TestSPI::execute(), TestUSB::execute(), UsbFTInterfaceTest::execute(), CurrentMeasurement::execute(), and ADCMeasurement::execute().
                                        {
    if (m_data->vectorPtr(i)!=0){
      m_data->vectorPtr(i)->push_back(val);
      return StatusCode::SUCCESS;
    }
    else {
      return StatusCode::FAILURE;
    }
  }
dataFill() [2/2]
StatusCode Processus::dataFill (std::string name, double val) [inline], [inherited]
Set data stream with value
Returns
the StatusCode
Definition at line 189 of file Processus.h.
References StatusCode::FAILURE, and StatusCode::SUCCESS.
                                                 {
    int row=m_data->rowFromName(name);
    if (row<0) return StatusCode::FAILURE;
    if (m_data->vectorPtr(row)!=0){
      m_data->vectorPtr(row)->push_back(val);
      return StatusCode::SUCCESS;
    }
    else {
      return StatusCode::FAILURE;
    }
  }
deadTime() [1/2]
int Acquisition::deadTime () [inline]
Definition at line 65 of file Acquisition.h.
References m_deadtime.
{return m_deadtime;}
deadTime() [2/2]
int Acquisition::deadTime () [inline]
Definition at line 67 of file Acquisition.h.
References m_deadtime.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
{return m_deadtime;}
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), initialize(), EmulateFE::initialize(), A3PE::internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), FEB_v1::readFifoSpyFE(), CU_v1::reset(), FEB_v1::reset(), Proto40MHz_v1::reset(), SpecsMaster::reset(), SpecsSlave::reset(), FEB_v1::resetFifoSpyFE(), FEB_v1::resetUsb(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), FEB_v1::testDuration(), SeqPGA::testSequence(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
decodeFormat() [1/2]
unsigned int Acquisition::decodeFormat (unsigned int, unsigned int, RAM *) [protected]
decodeFormat() [2/2]
unsigned int Acquisition::decodeFormat (unsigned int channel, unsigned int evt, RAM * ram) [protected]
Definition at line 226 of file Acquisition.cpp.
References IOdata::dataU8(), and IOobject::io().
Referenced by clone(), and execute().
                                                                                       {
  unsigned int val=0;
  switch (channel) {
  case 0:
    val=ram->io()->dataU8(0+12*evt)+((ram->io()->dataU8(1+12*evt)&0xf)<<8);
    break;
  case 1:
    val=(ram->io()->dataU8(1+12*evt)>>4)+(ram->io()->dataU8(2+12*evt)<<4);
    break;
  case 2:
    val=ram->io()->dataU8(3+12*evt)+((ram->io()->dataU8(4+12*evt)&0xf)<<8);
    break;
  case 3:
    val=(ram->io()->dataU8(4+12*evt)>>4)+(ram->io()->dataU8(5+12*evt)<<4);
    break;
  case 4:
    val=ram->io()->dataU8(6+12*evt)+((ram->io()->dataU8(7+12*evt)&0xf)<<8);
    break;
  case 5:
    val=(ram->io()->dataU8(7+12*evt)>>4)+(ram->io()->dataU8(8+12*evt)<<4);
    break;
  case 6:
    val=ram->io()->dataU8(9+12*evt)+((ram->io()->dataU8(10+12*evt)&0xf)<<8);
    break;
  case 7:
    val=(ram->io()->dataU8(10+12*evt)>>4)+(ram->io()->dataU8(11+12*evt)<<4);
    break;
  }
  return val;
}
depth() [1/2]
unsigned int Acquisition::depth () [inline]
Definition at line 29 of file Acquisition.h.
References m_depth, and setChannels().
{return m_depth;};
depth() [2/2]
unsigned int Acquisition::depth () [inline]
Definition at line 31 of file Acquisition.h.
References m_depth, and setChannels().
Referenced by BOOST_PYTHON_MODULE(), setDepth(), and Acquisition.Acquisition::update().
{return m_depth;};
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
elapsedTime() [1/2]
double Processus::elapsedTime () [inline], [inherited]
Definition at line 340 of file Processus.h.
References ProcState::time.
Referenced by Processus::endProcessing(), UsbFTInterfaceTest::execute(), PhaserRampExec::finalize(), and Processus::setState().
                       {
    return difftime(time(0),m_start);
  }
elapsedTime() [2/2]
double Processus::elapsedTime (time_t start) [inline], [inherited]
Definition at line 343 of file Processus.h.
References ProcState::time.
                                   {
    return ((time(0)-start));
  }
element()
Element* Processus::element () [inline], [inherited]
Get accessor to member m_element
Returns
the current value of m_element
Definition at line 231 of file Processus.h.
Referenced by UsbFTInterfaceTest::execute(), export_proc(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), initialize(), TestSPI::initialize(), TestUSB::initialize(), EmulateFE::initialize(), TestI2C::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), and PhaserRampExec::initialize().
                      {
    return m_element;
  }
endProcessing()
StatusCode Processus::endProcessing () [inherited]
processus standard termination function
Definition at line 115 of file Processus.cpp.
References Data::buildHistos(), Processus::closeRootFile(), Processus::elapsedTime(), Data::empty(), Processus::finalize(), ftos(), Object::info(), itos(), Processus::m_data, Processus::m_options, Processus::nErrors(), Options::nErrors(), Options::nEvt(), Processus::NOT_OK, Data::print(), Options::runNumber(), and Processus::setState().
Referenced by export_proc(), and Application::terminate().
                                    {
  setState(NOT_OK);
  //
  info("--------------------------------------------------------------------------");
  info("Processed Run Number : " + itos (m_options->
      runNumber()) , "finalize");
  info("Number of events processed : " + itos (m_options->nEvt()) , "finalize");
  info("Number of Errors : " + itos (nErrors()) , "finalize");
  info("Number of App errors : " + itos (m_options->
      nErrors()) , "finalize");
  info("Elapsed time : " + ftos (elapsedTime()) , "finalize");
  info("--------------------------------------------------------------------------");
  if (!m_data->empty())
    m_data->print();
  else
    info("No data Stored.","finalize");
  info("--------------------------------------------------------------------------");
#ifdef _NETWORK_
  if (0 != m_timerService){
    m_timerService->setRunning (false);
  }
#endif
  StatusCode sc = finalize();
  m_data->buildHistos();
  closeRootFile();
  return sc;
}
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
execute() [1/2]
virtual StatusCode Acquisition::execute () [virtual]
processus execution virtual function
Implements Processus.
execute() [2/2]
StatusCode Acquisition::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 118 of file Acquisition.cpp.
References application(), A3PE::dataReady(), Object::debug(), decodeFormat(), A3PE::enableStorage(), StatusCode::FAILURE, itos(), m_channel, m_chEnable, m_deadtime, m_depth, m_evtNumber, m_fifo, m_hsample, m_nch, m_nsample, m_pga, m_sample, m_store_hist, m_store_sample, m_store_tree, m_timestamp, m_tree, m_trig, Options::nEvt(), Application::options(), IOobject::read(), StatusCode::SUCCESS, A3PE::trigger(), v, v2, and Object::warning().
Referenced by BOOST_PYTHON_MODULE().
                                  {
  debug("Acquisition" , "execute");
  m_pga->enableStorage();
  m_evtNumber=application()->options()->nEvt()-1;
#ifdef WIN32
    double time_unit=1000000.;
#else
    double time_unit=1.e8;
#endif
  clock_t start=clock();
  double deadtime=(float)(m_deadtime);
  double elapsed=0.;
  if (m_trig) {m_pga->trigger();}
  bool dataready=false;
  while ((!dataready)&&(deadtime-elapsed>0)){
      m_timestamp=(double)(clock());
// wait(1);
      elapsed++;
// elapsed=((double)(CLOCKS_PER_SEC))/time_unit*(m_timestamp-(double)(start));
      dataready=m_pga->dataReady();
// if (0==((int(elapsed/10000.))%10)) warning("Waiting for the acknowledge");
  }
  if (!dataready){
    warning("Acquisition deadtime reached ("+
        itos(m_deadtime)+"). Execution stopped.");
    return StatusCode::FAILURE;
  }
  m_fifo->read();
  int nch, c;
  for (int d=0; d<m_depth; ++d){
    m_sample=d;
    nch=0; c=0;
    while (nch<m_nch) {
      if(m_chEnable[c]>0){
        m_channel[c]=decodeFormat(c,d,m_fifo);
// info("sample "+itos(d)+"- channel "+itos(c)+" - value="+itos(m_channel[c]));
        if (m_store_hist) {
          v[c+8*d]+=m_channel[c];
          v2[c+8*d]+=m_channel[c]*m_channel[c];
        }
        if (m_nsample==d){
          if (m_store_sample) m_hsample[c]->Fill(
      m_channel[c]);
        }
        nch++;
      }
      c++;
    }
    if (m_store_tree) m_tree->Fill();
  }
  return StatusCode::SUCCESS;
}
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
finalize() [1/2]
virtual StatusCode Acquisition::finalize () [virtual]
processus termination virtual function
Implements Processus.
finalize() [2/2]
StatusCode Acquisition::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 173 of file Acquisition.cpp.
References m_a, m_channels, m_depth, m_evtNumber, m_nch, m_s, m_store_hist, m_store_tree, m_tree, StatusCode::SUCCESS, v, and v2.
Referenced by BOOST_PYTHON_MODULE().
                                   {
  int nch; int c;
  double val,tmp;
  if (m_store_tree) m_tree->Print();
  if (m_store_hist){
    for (int d=0; d<m_depth; ++d){
      nch=0; c=0;
      while (nch<m_nch){
        if((m_channels>>c)&1){
          tmp=v[c+8*d]/(m_evtNumber+1);
          m_a[c]->Fill(d,tmp);
          if (m_evtNumber>0){
            val=(v2[c+8*d]
                 -v[c+8*d]*tmp
                 )/(m_evtNumber);
            m_s[c]->Fill(d,val>0.?sqrt(val):0.);
          }
          nch++;
        }
        c++;
      }
    }
  }
  return StatusCode::SUCCESS;
}
hist1d()
Histo1D* Processus::hist1d (unsigned int row) [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 138 of file Processus.h.
Referenced by export_proc().
                                   {
    return m_data->hist1d(row);
  }
hist2d()
Histo2D* Processus::hist2d (unsigned int row) [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 146 of file Processus.h.
Referenced by export_proc().
                                   {
    return m_data->hist2d(row);
  }
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
incNErrors()
void Processus::incNErrors () [inherited]
Increment the number of Errors for that process
Definition at line 72 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
                           {
  m_state->nerrors++;
}
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), ICECALv3::bxidResynchStatus(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTInterface::close(), UsbFTMLInterface::close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), UsbFTMLInterface::help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), MSOxxxx::id(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), initialize(), A3PE_BitFlip::initialize(), EmulateFE::initialize(), ADCMeasurement::initialize(), CurrentMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbMLI2cBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), FePGA::reset(), SeqPGA::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), SeqPGA::resetUsb(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), ICECALv3::version(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
initialize() [1/2]
virtual StatusCode Acquisition::initialize () [virtual]
processus initialisation virtual function
Implements Processus.
initialize() [2/2]
StatusCode Acquisition::initialize () [virtual]
processus initialisation virtual function
Implements Processus.
Definition at line 49 of file Acquisition.cpp.
References Proto40MHz_v1::a3pe(), Processus::addHisto1d(), application(), Object::debug(), Processus::element(), Object::info(), m_a, m_board, m_channel, m_channels, m_chEnable, m_depth, m_evtNumber, m_fifo, m_hsample, m_maxRange, m_minRange, m_nbins, m_nch, m_nsample, m_pga, m_runNumber, m_s, m_sample, m_store_hist, m_store_sample, m_store_tree, m_timestamp, m_tree, m_trig, Object::name(), Application::options(), Options::runNumber(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setSoftwareTrigger(), A3PE::setWriteStorageFifoUsb(), A3PE::storageRam(), StatusCode::SUCCESS, Object::title(), Object::type(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE().
                                     {
  debug("Acquisition" , "initialize");
  info("");
  info("____________________________");
  info("Acquisition run");
  info(" =>" + element()->path() + " " +
      element()->name() + " " + element()->type());
  m_board=dynamic_cast<Proto40MHz_v1*>(element());
  if (!m_board){
    warning("Acquisition","No Proto40MHz_v1 board found. Interrupt.");
    return false;
  }
  m_pga=m_board->a3pe();
  m_fifo = m_pga->storageRam();
  m_pga->setFifoDepth(m_depth);
  m_pga->setSoftwareTrigger(m_trig);
  m_pga->setWriteStorageFifoUsb(false);
  m_nch=0;
  char hname[25];
  char title[50];
  for (int c=0; c<8; c++){
    m_chEnable[c]=0;
    m_channel[c]=-1;
    if ((m_channels>>c)&1) {
      m_pga->setEnableADC(c,true);
      if (m_store_hist){
        sprintf(hname,"Average_Ch_%1i",c);
        sprintf(title,"Average Ch %1i",c);
        m_a[c]=new TH1D(hname, title, m_depth , -0.5, (float)(m_depth)-0.5);
        sprintf(hname,"RMS_Ch_%1i",c);
        sprintf(title,"RMS Ch %1i",c);
        m_s[c]=new TH1D(hname, title, m_depth , -0.5, (float)(m_depth)-0.5);
        addHisto1d(m_a[c]);
        addHisto1d(m_s[c]);
      }
      if (m_store_sample){
        sprintf(hname,"Acquisition_Ch_%1i_%1i",c,m_nsample);
        sprintf(title,"Acquisition Ch %1i - Sample %1i",c,m_nsample);
        m_hsample[c]=new TH1D(hname, title, m_nbins, m_minRange,
      m_maxRange);
        addHisto1d(m_hsample[c]);
      }
      m_chEnable[c]=1;
      m_nch++;
    }
    else {
      // m_channel[c]=-1.;
      m_pga->setEnableADC(c,false);
    }
  }
  if (m_store_tree){
    m_tree = new TTree("Acquisition",name().c_str());
    m_tree->Branch("Run",&m_runNumber,"Run/I");
    m_tree->Branch("Event",&m_evtNumber,"Event/I");
    m_tree->Branch("Time",&m_timestamp,"Time/D");
    m_tree->Branch("Sample",&m_sample,"Sample/I");
    m_tree->Branch("Channel",m_channel,"Channel[8]/I");
    m_tree->Branch("ChEnable",m_chEnable,"ChEnable[8]/I");
  }
  m_runNumber=application()->options()->runNumber();
  return StatusCode::SUCCESS;
}
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
logMsg()
std::string Processus::logMsg () [inline], [inherited]
Get accessor to member m_logMsg
Returns
the current value of m_logMsg
Definition at line 291 of file Processus.h.
References ProcState::state.
                      {
    return m_logMsg;
  }
maxRange() [1/2]
float Acquisition::maxRange () [inline]
Definition at line 89 of file Acquisition.h.
References m_maxRange.
{return m_maxRange;}
maxRange() [2/2]
float Acquisition::maxRange () [inline]
Definition at line 91 of file Acquisition.h.
References m_maxRange.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
{return m_maxRange;}
minRange() [1/2]
float Acquisition::minRange () [inline]
Definition at line 83 of file Acquisition.h.
References m_minRange.
{return m_minRange;}
minRange() [2/2]
float Acquisition::minRange () [inline]
Definition at line 85 of file Acquisition.h.
References m_minRange.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
{return m_minRange;}
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), UsbFTInterface::help(), UsbFTMLInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), Data::hist2d(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), UsbSpiBus::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), SpecsSlave::resetInternal(), FEB_v1::resetUsb(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), Object::setName(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
nBins() [1/2]
int Acquisition::nBins () [inline]
Definition at line 77 of file Acquisition.h.
References m_nbins.
{return m_nbins;}
nBins() [2/2]
int Acquisition::nBins () [inline]
Definition at line 79 of file Acquisition.h.
References m_nbins.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
{return m_nbins;}
nErrors()
unsigned int Processus::nErrors () [inherited]
Get accessor to member m_nErrors
Returns
the current value of m_nErrors
Definition at line 86 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
Referenced by Processus::endProcessing().
                                {
  return (m_state->nerrors++);
}
openRootFile()
void Processus::openRootFile () [inherited]
Open Root file if needed
Definition at line 146 of file Processus.cpp.
References Options::dataFileFullName(), Options::dataStorage(), Object::info(), Processus::m_options, Processus::m_rootFile, and Object::name().
Referenced by RegisterTest::initialize(), UsbFTInterfaceTest::initialize(), PhaserRampExec::initialize(), and Processus::startProcessing().
                               {
  if (m_options->dataStorage()){
    m_rootFile = new TFile(m_options->dataFileFullName().c_str(),
                           "RECREATE",name().c_str());
        std::string mess=std::string("Opening root file ");
        mess.append(m_options->dataFileFullName());
        info(mess,"openRootFile");
  }
}
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
rootFile()
TFile* Processus::rootFile () [inline], [inherited]
Get accessor to member m_rootFile
Returns
the current value of m_rootFile
Definition at line 258 of file Processus.h.
                     {
    return m_rootFile;
  }
sample() [1/2]
int Acquisition::sample () [inline]
Definition at line 71 of file Acquisition.h.
References m_nsample.
{return m_nsample;}
sample() [2/2]
int Acquisition::sample () [inline]
Definition at line 73 of file Acquisition.h.
References m_nsample.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
{return m_nsample;}
setChannels() [1/2]
StatusCode Acquisition::setChannels (unsigned int)
setChannels() [2/2]
StatusCode Acquisition::setChannels (unsigned int channels)
Definition at line 214 of file Acquisition.cpp.
References channels(), m_channels, StatusCode::SUCCESS, and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), depth(), and Acquisition.Acquisition::onApply().
                                                         {
  if (channels>0xFF){
    channels=(channels&0xFF);
    warning("Channels coding not appropriate. Truncated at 0xFF.");
  }
  m_channels=channels;
  return StatusCode::SUCCESS;
}
setDeadTime() [1/2]
void Acquisition::setDeadTime (int deadtime) [inline]
Definition at line 61 of file Acquisition.h.
References m_deadtime.
                                {
    m_deadtime=deadtime;
  }
setDeadTime() [2/2]
void Acquisition::setDeadTime (int deadtime) [inline]
Definition at line 63 of file Acquisition.h.
References m_deadtime.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onDeadtime().
                                {
    m_deadtime=deadtime;
  }
setDepth() [1/2]
StatusCode Acquisition::setDepth (unsigned int)
setDepth() [2/2]
StatusCode Acquisition::setDepth (unsigned int depth)
Definition at line 202 of file Acquisition.cpp.
References depth(), StatusCode::FAILURE, m_depth, StatusCode::SUCCESS, and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onDepth().
                                                    {
  if (depth>512){
    warning("Cannot acquire more than 512 consecutive events. Interrupt.");
    return StatusCode::FAILURE;
  }
  m_depth=depth;
  return StatusCode::SUCCESS;
}
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setElement()
void Processus::setElement (Element * element) [inline], [inherited]
Set accessor to member m_element
Parameters
element the new value for m_element
Definition at line 217 of file Processus.h.
Referenced by export_proc(), and Application::prepare().
                                     {
    m_state = new ProcState ();
    m_state->nevent = 0;
    m_state->nerrors = 0;
    m_state->time = 0;
    strcpy(m_state->state,"");
    // setState(OK);
    m_element = element;
  }
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setLogMsg()
void Processus::setLogMsg (std::string logMsg) [inline], [inherited]
Set accessor to member m_logMsg
Parameters
logMsg the new value for m_logMsg
Definition at line 283 of file Processus.h.
                                    {
    m_logMsg = logMsg;
  }
setMaxRange() [1/2]
void Acquisition::setMaxRange (float maxrange) [inline]
Definition at line 85 of file Acquisition.h.
References m_maxRange.
                                  {
    m_maxRange=maxrange;
  }
setMaxRange() [2/2]
void Acquisition::setMaxRange (float maxrange) [inline]
Definition at line 87 of file Acquisition.h.
References m_maxRange.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onMax().
                                  {
    m_maxRange=maxrange;
  }
setMinRange() [1/2]
void Acquisition::setMinRange (float minrange) [inline]
Definition at line 79 of file Acquisition.h.
References m_minRange.
                                  {
    m_minRange=minrange;
  }
setMinRange() [2/2]
void Acquisition::setMinRange (float minrange) [inline]
Definition at line 81 of file Acquisition.h.
References m_minRange.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onMin().
                                  {
    m_minRange=minrange;
  }
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setNBins() [1/2]
void Acquisition::setNBins (int nbins) [inline]
Definition at line 73 of file Acquisition.h.
References m_nbins.
                          {
    m_nbins=nbins;
  }
setNBins() [2/2]
void Acquisition::setNBins (int nbins) [inline]
Definition at line 75 of file Acquisition.h.
References m_nbins.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onNBins().
                          {
    m_nbins=nbins;
  }
setNErrors()
void Processus::setNErrors (unsigned int nerr) [inherited]
Set accessor to member m_nErrors
Parameters
nErrors the new value for m_nErrors
Definition at line 79 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
Referenced by Processus::startProcessing().
                                             {
  m_state->nerrors = nerr ;
}
setSample() [1/2]
void Acquisition::setSample (int nsample) [inline]
Definition at line 67 of file Acquisition.h.
References m_nsample.
                             {
    m_nsample=nsample;
  }
setSample() [2/2]
void Acquisition::setSample (int nsample) [inline]
Definition at line 69 of file Acquisition.h.
References m_nsample.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onNSample().
                             {
    m_nsample=nsample;
  }
setState()
void Processus::setState (int state) [inherited]
Set accessor to member m_state.state
Parameters
state the new value for m_state.state
Definition at line 174 of file Processus.cpp.
References application(), Processus::elapsedTime(), Processus::ERR, Object::info(), Processus::m_options, Processus::m_state, Object::msgSvc(), Object::name(), ProcState::nerrors, Options::nErrors(), ProcState::nevent, Options::nEvt(), Processus::NOT_OK, Processus::OK, ProcState::state, and ProcState::time.
Referenced by Processus::endProcessing().
                                     {
  m_state->nevent = m_options->nEvt();
  m_state->nerrors = m_options->nErrors();
  m_state->time = (float) (elapsedTime());
  switch (state){
  case OK:
    strcpy(m_state->state,"OK");
    break;
  case NOT_OK:
    strcpy(m_state->state,"NOT_OK");
    break;
  case ERR:
    strcpy(m_state->state,"ERROR");
  }
}
setStorage()
void Processus::setStorage (std::string storage) [inline], [inherited]
Set accessor to member m_storage
Parameters
storage the new value for m_storage
Definition at line 106 of file Processus.h.
Referenced by export_proc().
                                      {
    m_storage = storage;
  }
setStoreSample() [1/2]
void Acquisition::setStoreSample (bool store_sample) [inline]
Definition at line 55 of file Acquisition.h.
References m_store_sample.
                                        {
    m_store_sample=store_sample;
  }
setStoreSample() [2/2]
void Acquisition::setStoreSample (bool store_sample) [inline]
Definition at line 57 of file Acquisition.h.
References m_store_sample.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onSample().
                                        {
    m_store_sample=store_sample;
  }
setStoreTree() [1/2]
void Acquisition::setStoreTree (bool store_tree) [inline]
Definition at line 43 of file Acquisition.h.
References m_store_tree.
                                    {
    m_store_tree=store_tree;
  }
setStoreTree() [2/2]
void Acquisition::setStoreTree (bool store_tree) [inline]
Definition at line 45 of file Acquisition.h.
References m_store_tree.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onTree().
                                    {
    m_store_tree=store_tree;
  }
setStoreTrend() [1/2]
void Acquisition::setStoreTrend (bool store_hist) [inline]
Definition at line 49 of file Acquisition.h.
References m_store_hist.
                                     {
    m_store_hist=store_hist;
  }
setStoreTrend() [2/2]
void Acquisition::setStoreTrend (bool store_hist) [inline]
Definition at line 51 of file Acquisition.h.
References m_store_hist.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onTrend().
                                     {
    m_store_hist=store_hist;
  }
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setTrigger() [1/2]
StatusCode Acquisition::setTrigger (bool trig) [inline]
Definition at line 34 of file Acquisition.h.
References m_trig, and StatusCode::SUCCESS.
                                   {
    m_trig=trig;
    return StatusCode::SUCCESS;
  };
setTrigger() [2/2]
StatusCode Acquisition::setTrigger (bool trig) [inline]
Definition at line 36 of file Acquisition.h.
References m_trig, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::onSoftTrig().
                                   {
    m_trig=trig;
    return StatusCode::SUCCESS;
  };
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
startChrono()
void Processus::startChrono () [inline], [inherited]
Start processus time measurement
Definition at line 275 of file Processus.h.
References ProcState::time.
Referenced by PhaserRampExec::initialize(), and Processus::startProcessing().
                    {
    m_start = time(0);
  }
startProcessing()
StatusCode Processus::startProcessing () [inherited]
processus cmdline function processus virtual command function processus standard initialize function
Definition at line 93 of file Processus.cpp.
References Object::info(), Processus::initialize(), Processus::m_data, Processus::m_options, Object::name(), Processus::openRootFile(), Data::purge(), Processus::setNErrors(), Options::setNErrors(), and Processus::startChrono().
Referenced by export_proc(), and Application::prepare().
                                      {
  info("==========================================================================");
  info(" * " + name() + " *");
  m_options->setNErrors (0);
  setNErrors (0);
  m_data->purge();
#ifdef _NETWORK_
  if (0 != m_timerService){
    m_timerService->setRunning (true);
    m_timerService->timeHandler() ;
  }
#endif
  // start measuring processus duration
  
  startChrono();
  openRootFile();
  return initialize();
}
storage()
std::string Processus::storage () [inline], [inherited]
Get accessor to member m_storage
Returns
the current value of m_storage
Definition at line 205 of file Processus.h.
Referenced by export_proc(), and Application::prepare().
                       {
    if (0 == m_storage.compare(""))
    {
      return name();
    }
    return m_storage;
  }
storeSample() [1/2]
bool Acquisition::storeSample () [inline]
Definition at line 59 of file Acquisition.h.
References m_store_sample.
{return m_store_sample;}
storeSample() [2/2]
bool Acquisition::storeSample () [inline]
Definition at line 61 of file Acquisition.h.
References m_store_sample.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
{return m_store_sample;}
storeTree() [1/2]
bool Acquisition::storeTree () [inline]
Definition at line 47 of file Acquisition.h.
References m_store_tree.
{return m_store_tree;}
storeTree() [2/2]
bool Acquisition::storeTree () [inline]
Definition at line 49 of file Acquisition.h.
References m_store_tree.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
{return m_store_tree;}
storeTrend() [1/2]
bool Acquisition::storeTrend () [inline]
Definition at line 53 of file Acquisition.h.
References m_store_hist.
{return m_store_hist;}
storeTrend() [2/2]
bool Acquisition::storeTrend () [inline]
Definition at line 55 of file Acquisition.h.
References m_store_hist.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
{return m_store_hist;}
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestSPI::Plot(), TestUSB::Plot(), TestI2C::Plot(), Object::setTitle(), and Application::terminate().
{ return m_title; } // < Get Object m_title
trigger() [1/2]
bool Acquisition::trigger () [inline]
Definition at line 39 of file Acquisition.h.
References m_trig.
                 {
    return m_trig;
  };
trigger() [2/2]
bool Acquisition::trigger () [inline]
Definition at line 41 of file Acquisition.h.
References m_trig.
Referenced by BOOST_PYTHON_MODULE(), and Acquisition.Acquisition::update().
                 {
    return m_trig;
  };
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTInterface::read(), UsbFTMLInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), wait(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), initialize(), TestI2C::initialize(), EmulateFE::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsMaster::reset(), SpecsSlave::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
Member Data Documentation
m_a
TH1D * Acquisition::m_a [private]
Definition at line 123 of file Acquisition.h.
Referenced by finalize(), and initialize().
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_board [1/2]
FEB_v1* Acquisition::m_board [private]
Definition at line 117 of file Acquisition.h.
m_board [2/2]
Proto40MHz_v1* Acquisition::m_board [private]
Definition at line 119 of file Acquisition.h.
Referenced by initialize().
m_channel
Int_t Acquisition::m_channel [private]
Definition at line 112 of file Acquisition.h.
Referenced by clone(), execute(), and initialize().
m_channels
int Acquisition::m_channels [private]
Definition at line 117 of file Acquisition.h.
Referenced by channels(), clone(), finalize(), initialize(), and setChannels().
m_chEnable
Int_t Acquisition::m_chEnable [private]
Definition at line 113 of file Acquisition.h.
Referenced by clone(), execute(), and initialize().
m_deadtime
int Acquisition::m_deadtime [private]
Definition at line 132 of file Acquisition.h.
Referenced by deadTime(), execute(), and setDeadTime().
m_depth
int Acquisition::m_depth [private]
Definition at line 118 of file Acquisition.h.
Referenced by clone(), depth(), execute(), finalize(), initialize(), and setDepth().
m_depthmax
static const unsigned int Acquisition::m_depthmax = 512 [static], [private]
Definition at line 102 of file Acquisition.h.
Referenced by clone().
m_element
Element* Processus::m_element [protected], [inherited]
Definition at line 348 of file Processus.h.
Referenced by Processus::~Processus().
m_evtNumber
Int_t Acquisition::m_evtNumber [private]
Definition at line 110 of file Acquisition.h.
Referenced by clone(), execute(), finalize(), and initialize().
m_fifo
RAM* Acquisition::m_fifo [private]
Definition at line 121 of file Acquisition.h.
Referenced by execute(), and initialize().
m_hsample
TH1D * Acquisition::m_hsample [private]
Definition at line 125 of file Acquisition.h.
Referenced by execute(), and initialize().
m_maxRange
float Acquisition::m_maxRange [private]
Definition at line 131 of file Acquisition.h.
Referenced by initialize(), maxRange(), and setMaxRange().
m_minRange
float Acquisition::m_minRange [private]
Definition at line 130 of file Acquisition.h.
Referenced by initialize(), minRange(), and setMinRange().
m_nbins
unsigned int Acquisition::m_nbins [private]
Definition at line 129 of file Acquisition.h.
Referenced by initialize(), nBins(), and setNBins().
m_nch
Int_t Acquisition::m_nch [private]
Definition at line 114 of file Acquisition.h.
Referenced by clone(), execute(), finalize(), and initialize().
m_nsample
unsigned int Acquisition::m_nsample [private]
Definition at line 128 of file Acquisition.h.
Referenced by execute(), initialize(), sample(), and setSample().
m_pga
A3PE* Acquisition::m_pga [private]
Definition at line 120 of file Acquisition.h.
Referenced by a3pe(), execute(), and initialize().
m_runNumber
Int_t Acquisition::m_runNumber [private]
Definition at line 109 of file Acquisition.h.
Referenced by clone(), and initialize().
m_s
TH1D * Acquisition::m_s [private]
Definition at line 124 of file Acquisition.h.
Referenced by finalize(), and initialize().
m_sample
Int_t Acquisition::m_sample [private]
Definition at line 111 of file Acquisition.h.
Referenced by clone(), execute(), and initialize().
m_store_hist
bool Acquisition::m_store_hist [private]
Definition at line 105 of file Acquisition.h.
Referenced by clone(), execute(), finalize(), initialize(), setStoreTrend(), and storeTrend().
m_store_sample
bool Acquisition::m_store_sample [private]
Definition at line 106 of file Acquisition.h.
Referenced by clone(), execute(), initialize(), setStoreSample(), and storeSample().
m_store_tree
bool Acquisition::m_store_tree [private]
Definition at line 104 of file Acquisition.h.
Referenced by clone(), execute(), finalize(), initialize(), setStoreTree(), and storeTree().
m_timestamp
double Acquisition::m_timestamp [private]
Definition at line 116 of file Acquisition.h.
Referenced by clone(), execute(), and initialize().
m_tree
TTree * Acquisition::m_tree [private]
Definition at line 108 of file Acquisition.h.
Referenced by clone(), execute(), finalize(), and initialize().
m_trig
bool Acquisition::m_trig [private]
Definition at line 122 of file Acquisition.h.
Referenced by execute(), initialize(), setTrigger(), and trigger().
v
double Acquisition::v [private]
Definition at line 126 of file Acquisition.h.
Referenced by execute(), and finalize().
v2
double Acquisition::v2 [private]
Definition at line 127 of file Acquisition.h.
Referenced by execute(), and finalize().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/inc/proc/Acquisition.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/src/proc/Acquisition.cpp