Computer Class Reference
#include <Computer.h>
Classes
class Computer
Public Member Functions
Computer ()
Standard constructor.
virtual ~Computer ()
Destructor.
void help ()
StatusCode init ()
void reset ()
void update ()
Private Attributes
TestSuite * m_testSuite
Additional Inherited Members
Detailed Description
Author
Frédéric Machefert
Date
2006-10-26
Definition at line 26 of file Computer.h.
Constructor & Destructor Documentation
Computer()
Computer::Computer ()
Standard constructor.
Definition at line 17 of file Computer.cpp.
References ProcDataBase::add(), Attrib::add(), application(), Attrib::ELEMENT, Attrib::HARDWARE, System::hostName(), m_testSuite, Application::procDb(), Object::setName(), Hierarchy::setParent(), and Object::setType().
                     {
  setName (System::hostName());
  setType ("Computer");
  add(Attrib::ELEMENT); add(Attrib::HARDWARE);
  m_testSuite=new TestSuite();
  application()->procDb()->add(m_testSuite);
  setParent((Hierarchy*)0);
}
 Computer()
Computer::~Computer () [virtual]
Destructor.
Definition at line 28 of file Computer.cpp.
References application(), m_testSuite, Application::procDb(), and ProcDataBase::remove().
                    {
  application()->procDb()->remove(m_testSuite);
}
Member Function Documentation
help()
void Computer::help () [inline], [virtual]
printout help for the element
Implements Element.
Definition at line 37 of file Computer.h.
References Object::info(), and Object::name().
Referenced by export_obj().
{ info("Computer "+name()+". No help.","Computer::help"); };
init()
StatusCode Computer::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 43 of file Computer.h.
References Object::info(), Object::name(), and StatusCode::SUCCESS.
Referenced by export_obj().
                    {
    info("Computer "+name()+" initialization.","Computer::init");
    return StatusCode::SUCCESS;
  };
reset()
void Computer::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 55 of file Computer.h.
References Object::info(), and Object::name().
Referenced by export_obj().
{ info("Computer "+name()+" reset.","Computer::reset");};
update()
void Computer::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 60 of file Computer.h.
References Object::info(), m_testSuite, and Object::name().
Referenced by AppFrame.AppFrame::deleteHardware(), export_obj(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
{info("Computer "+name()+". Nothing to do.","Computer::update");};
Member Data Documentation
m_testSuite
TestSuite* Computer::m_testSuite [private]
Definition at line 60 of file Computer.h.
Referenced by Computer(), update(), and ~Computer().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Computer.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Computer.cpp