NI6008 Class Reference
#include <inc/NI6008.h>
Public Member Functions
NI6008 ()
Standard constructor.
virtual ~NI6008 ()
Destructor.
void help ()
StatusCode init ()
void reset ()
void update ()
std::string cmd (std::string, std::string)
int port ()
void setPort (int portno)
std::string hostname ()
void setHostname (std::string host)
std::vector< double > ai ()
int di ()
StatusCode addDevice (std::string path)
std::string device (unsigned int dev)
StatusCode clearDevice ()
unsigned int numberOfDevices ()
Protected Attributes
int m_portno
std::string m_host
std::vector< std::string > m_device
int m_sockfd
struct sockaddr_in m_serv_addr
struct hostent * m_server
char buffer [256]
Additional Inherited Members
Detailed Description
Author
NI6008
Date
2006-10-23
Definition at line 26 of file NI6008.h.
Constructor & Destructor Documentation
NI6008()
NI6008::NI6008 ()
Standard constructor.
Definition at line 22 of file NI6008.cpp.
References application(), Application::hostname(), m_host, Object::setName(), and Object::setType().
                 {
  setName("NI6008");
  setType("NI6008");
  m_host = application()->hostname();
}
 NI6008()
NI6008::~NI6008 () [virtual]
Destructor.
Definition at line 30 of file NI6008.cpp.
References Object::info(), and m_sockfd.
                {
  info("Closing the NI6008 socket.");
  close(m_sockfd);
}
Member Function Documentation
addDevice()
StatusCode NI6008::addDevice (std::string path) [inline]
Definition at line 114 of file NI6008.h.
References Object::info(), m_device, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                       {
    m_device.push_back(path);
    info("Device associated.");
    return StatusCode::SUCCESS;
  };
ai()
std::vector<double> NI6008::ai ()
Referenced by setHostname().
clearDevice()
StatusCode NI6008::clearDevice () [inline]
Definition at line 128 of file NI6008.h.
References m_device, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                          {
    m_device.clear();
    return StatusCode::SUCCESS;
  }
cmd()
std::string NI6008::cmd (std::string dev, std::string mess)
Definition at line 38 of file NI6008.cpp.
References buffer, Object::error(), and m_sockfd.
Referenced by BOOST_PYTHON_MODULE(), CurrentMeasurement::execute(), ADCMeasurement::execute(), and update().
                                                  {
  int n;
  std::string cmd = dev + std::string(" ") + mess;
  std::copy(cmd.begin(), cmd.end(), buffer);
  // strcat(buffer, " ");
  // strcat(buffer, mess.c_str());
  buffer[cmd.size()] = '\0';
  // std::cout<<"sending:"<<buffer<<" length="<<strlen(buffer)<<std::endl;
  n = write(m_sockfd,buffer,strlen(buffer));
  if (n < 0) error("ERROR writing to socket");
  bzero(buffer,256);
  n = read(m_sockfd,buffer,255);
  if (n < 0) error("ERROR reading from socket");
  // printf("%s\n",buffer);
  return std::string(buffer);
}
device()
std::string NI6008::device (unsigned int dev) [inline]
Definition at line 120 of file NI6008.h.
References m_device, and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), CurrentMeasurement::execute(), and CurrentMeasurement::initialize().
                                        {
    if (dev>m_device.size()-1){
      warning("Device not defined.");
      return NULL;
    }
    return m_device[dev];
  }
di()
int NI6008::di ()
Referenced by setHostname().
help()
void NI6008::help () [inline], [virtual]
printout help for the element
Implements Element.
Definition at line 37 of file NI6008.h.
References Object::info(), and Object::name().
Referenced by BOOST_PYTHON_MODULE().
{ info("NI6008 "+name()+". No help.","NI6008::help"); };
hostname()
std::string NI6008::hostname () [inline]
Define/get device Define/get server hostname
Definition at line 108 of file NI6008.h.
References m_host.
Referenced by BOOST_PYTHON_MODULE().
{ return m_host; }
init()
StatusCode NI6008::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 43 of file NI6008.h.
References Object::error(), StatusCode::FAILURE, Object::info(), itos(), m_host, m_portno, m_serv_addr, m_server, m_sockfd, Object::name(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                    {
    info("NI6008 "+name()+" initialization.","NI6008:init");
    /* if (m_device==std::string("")){ */
    /* error("Device has not been device before opening the server connection. Interrupt."); */
    /* } */
    m_sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (m_sockfd < 0) {
      error("ERROR opening socket");
      return StatusCode::FAILURE;
    }
    m_server = gethostbyname(m_host.c_str());
    if (m_server == NULL) {
      error("ERROR connecting to host "+m_host+".");
      return StatusCode::FAILURE;
    }
    bzero((char *) &m_serv_addr, sizeof(m_serv_addr));
    m_serv_addr.sin_family = AF_INET;
    bcopy((char *)m_server->h_addr,
          (char *)&m_serv_addr.sin_addr.s_addr,
          m_server->h_length);
    m_serv_addr.sin_port = htons(m_portno);
    if (connect(m_sockfd,(struct sockaddr *) &m_serv_addr,sizeof(m_serv_addr)) < 0) {
      error("ERROR connecting to the socket.");
      return StatusCode::FAILURE;
    }
    info("Starting client, connecting to host "+m_host+" on port "+
      itos(m_portno));
    return StatusCode::SUCCESS;
  }
numberOfDevices()
unsigned int NI6008::numberOfDevices () [inline]
Definition at line 133 of file NI6008.h.
References m_device.
Referenced by BOOST_PYTHON_MODULE(), CurrentMeasurement::execute(), CurrentMeasurement::initialize(), and ADCMeasurement::numberOfDevices().
                                {
    return m_device.size();
  }
port()
int NI6008::port () [inline]
Define/get server port number
Definition at line 96 of file NI6008.h.
References m_portno.
Referenced by BOOST_PYTHON_MODULE().
{ return m_portno; }
reset()
void NI6008::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 81 of file NI6008.h.
References Object::info(), and Object::name().
Referenced by BOOST_PYTHON_MODULE().
{ info("NI6008 "+name()+" reset.","NI6008::reset");};
setHostname()
void NI6008::setHostname (std::string host) [inline]
Definition at line 109 of file NI6008.h.
References ai(), di(), and m_host.
Referenced by BOOST_PYTHON_MODULE().
{ m_host = host; }
setPort()
void NI6008::setPort (int portno) [inline]
Definition at line 97 of file NI6008.h.
References m_portno.
Referenced by BOOST_PYTHON_MODULE().
{ m_portno = portno; }
update()
void NI6008::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 86 of file NI6008.h.
References cmd(), Object::info(), and Object::name().
Referenced by BOOST_PYTHON_MODULE(), AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
{info("NI6008 "+name()+". Nothing to do.","NI6008::update");};
Member Data Documentation
buffer
char NI6008::buffer[256] [protected]
Definition at line 144 of file NI6008.h.
Referenced by cmd().
m_device
std::vector<std::string> NI6008::m_device [protected]
Definition at line 140 of file NI6008.h.
Referenced by addDevice(), clearDevice(), device(), and numberOfDevices().
m_host
std::string NI6008::m_host [protected]
Definition at line 139 of file NI6008.h.
Referenced by hostname(), init(), NI6008(), and setHostname().
m_portno
int NI6008::m_portno [protected]
Definition at line 138 of file NI6008.h.
Referenced by init(), port(), and setPort().
m_serv_addr
struct sockaddr_in NI6008::m_serv_addr [protected]
Definition at line 142 of file NI6008.h.
Referenced by init().
m_server
struct hostent* NI6008::m_server [protected]
Definition at line 143 of file NI6008.h.
Referenced by init().
m_sockfd
int NI6008::m_sockfd [protected]
Definition at line 141 of file NI6008.h.
Referenced by cmd(), init(), and ~NI6008().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatNI/inc/NI6008.h
/home/eleclhcb/LHCb/lbcat-cmake/CatNI/src/NI6008.cpp