ProcDataBase Class Reference
#include <inc/ProcDataBase.h>
Public Member Functions
ProcDataBase ()
Standard constructor.
virtual ~ProcDataBase ()
Destructor.
void update ()
std::list< Processus *> procList (Element *)
std::vector< Processus * > list (Element *)
std::vector< Processus * > list ()
Processus * processus (std::string)
StatusCode add (Processus *)
StatusCode remove (Processus *)
Private Attributes
std::list< Processus *> m_procList
std::list< std::string > m_types
Detailed Description
Author
Frederic Machefert
Date
2005-01-03
Definition at line 20 of file ProcDataBase.h.
Constructor & Destructor Documentation
ProcDataBase()
ProcDataBase::ProcDataBase ()
Standard constructor.
Definition at line 25 of file ProcDataBase.cpp.
References application(), and Object::info().
                             {
  application()->info("Building Processus DataBase.","ProcDataBase");
}
 ProcDataBase()
ProcDataBase::~ProcDataBase () [virtual]
Destructor.
Definition at line 32 of file ProcDataBase.cpp.
                            {
}
Member Function Documentation
add()
StatusCode ProcDataBase::add (Processus * proc)
Definition at line 101 of file ProcDataBase.cpp.
References m_procList, StatusCode::SUCCESS, and update().
Referenced by Computer::Computer(), and DLL::init().
                                               {
  m_procList.push_back (proc);
  update();
  return StatusCode::SUCCESS;
}
list() [1/2]
std::vector< Processus * > ProcDataBase::list (Element * element)
Definition at line 63 of file ProcDataBase.cpp.
References list(), m_procList, and Object::type().
                                                            {
  std::vector<Processus*> list;
  std::list<Processus*>::const_iterator iter;
  for (iter=m_procList.begin();iter!=m_procList.end();++iter){
    if ((*iter)->type().compare(element->type())==0){
      list.push_back(*iter);
    }
  }
  return list;
}
list() [2/2]
std::vector< Processus * > ProcDataBase::list ()
Definition at line 76 of file ProcDataBase.cpp.
References m_procList.
Referenced by export_base(), export_proc(), list(), and procList().
                                           {
  std::vector<Processus*> list;
  std::list<Processus*>::const_iterator iter;
  for (iter=m_procList.begin();iter!=m_procList.end();++iter){
    list.push_back(*iter);
  }
  return list;
}
processus()
Processus * ProcDataBase::processus (std::string procName)
Definition at line 88 of file ProcDataBase.cpp.
References m_procList.
Referenced by DLL::print().
                                                        {
  std::list< Processus* >::const_iterator iter;
  for (iter=m_procList.begin();iter!=m_procList.end();++iter){
    if ((*iter)->name().compare(procName) == 0) {
      return (*iter);
    }
  }
  return NULL;
}
procList()
std::list< Processus * > ProcDataBase::procList (Element * element)
Definition at line 49 of file ProcDataBase.cpp.
References list(), m_procList, and Object::type().
Referenced by Application::prepare(), and Application::setConfig().
                                                              {
  std::list<Processus*> list;
  std::list<Processus*>::const_iterator iter;
  for (iter=m_procList.begin();iter!=m_procList.end();++iter){
    if ((*iter)->type().compare(element->type())==0){
      list.push_back(*iter);
    }
  }
  return list;
}
remove()
StatusCode ProcDataBase::remove (Processus * proc)
Erase a processus to the db
Definition at line 110 of file ProcDataBase.cpp.
References m_procList, and StatusCode::SUCCESS.
Referenced by Computer::~Computer().
                                                  {
  m_procList.remove(proc);
  return StatusCode::SUCCESS;
}
update()
void ProcDataBase::update ()
Definition at line 38 of file ProcDataBase.cpp.
References m_procList, and m_types.
Referenced by add(), AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
                            {
  std::list<Processus*>::const_iterator iter;
  for (iter=m_procList.begin();iter!=m_procList.end();++iter){
    m_types.push_back((*iter)->type());
  }
  m_types.unique();
}
Member Data Documentation
m_procList
std::list< Processus* > ProcDataBase::m_procList [private]
Definition at line 55 of file ProcDataBase.h.
Referenced by add(), list(), processus(), procList(), remove(), and update().
m_types
std::list< std::string > ProcDataBase::m_types [private]
Definition at line 56 of file ProcDataBase.h.
Referenced by update().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/ProcDataBase.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/ProcDataBase.cpp