IOdata Class Reference
#include <inc/IOdata.h>
Public Types
enum Mode { Rd,
Wr,
RdWr
 }
enum WordSize { Byte,
Word,
DWord
 }
enum Bus {
USB,
SPECS,
I2C,
PARALLEL,
JTAG
 }
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
IOdata ()
Standard constructor.
virtual ~IOdata ()
Destructor.
StatusCode setAddress (U32 address)
U32 address ()
StatusCode setHeader (U32 header)
U32 header ()
StatusCode setSubAddress (U32 subAddress)
U32 subAddress ()
StatusCode setOutputSelect (U32 outputSelect)
U32 outputSelect ()
StatusCode setMode (IOdata::Mode mode)
IOdata::Mode mode ()
StatusCode setWordSize (IOdata::WordSize wordSize)
IOdata::WordSize wordSize ()
StatusCode setBus (IOdata::Bus bus)
IOdata::Bus bus ()
StatusCode setLength (U32 length)
U32 block ()
StatusCode setBlock (U32 block)
U32 length ()
void defDataU8 (unsigned long size)
void defDataU16 (unsigned long size)
void defDataU32 (unsigned long size)
void clearDataU8 ()
void clearDataU16 ()
void clearDataU32 ()
U8 * dataU8 ()
U16 * dataU16 ()
U32 * dataU32 ()
unsigned long int dataU8 (unsigned long int i)
unsigned long int dataU16 (unsigned long int i)
unsigned long int dataU32 (unsigned long int i)
void setDataU8 (U8 *data, U32 length)
void setDataU16 (U16 *data, U32 length)
void setDataU32 (U32 *data, U32 length)
StatusCode setU8 (unsigned long int, U8)
StatusCode setU16 (unsigned long int, U16)
StatusCode setU32 (unsigned long int, U32)
void dump (unsigned int printout=0)
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
std::string m_attribString [10]
Private Attributes
unsigned long m_address
unsigned long m_header
unsigned long m_subAddress
unsigned long m_outputSelect
IOdata::Mode m_mode
IOdata::WordSize m_wordSize
IOdata::Bus m_bus
unsigned long m_length
unsigned long m_block
U8 * m_dataU8
U16 * m_dataU16
U32 * m_dataU32
Detailed Description
Author
IOdata
Date
2006-10-23
Definition at line 17 of file IOdata.h.
Member Typedef Documentation
U16
typedef unsigned short IOdata::U16
Definition at line 20 of file IOdata.h.
U32
typedef unsigned long IOdata::U32
Definition at line 19 of file IOdata.h.
U8
typedef unsigned char IOdata::U8
Definition at line 21 of file IOdata.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
Bus
enum IOdata::Bus
Enumerator
USB
SPECS
I2C
PARALLEL
JTAG
Definition at line 35 of file IOdata.h.
          {
    USB,
    SPECS,
    I2C,
    PARALLEL,
    JTAG
  };
Mode
enum IOdata::Mode
Enumerator
Rd
Wr
RdWr
Definition at line 23 of file IOdata.h.
            {
    Rd,
    Wr,
    RdWr
  };
WordSize
enum IOdata::WordSize
Enumerator
Byte
Word
DWord
Definition at line 29 of file IOdata.h.
               {
    Byte,
    Word,
    DWord
  };
Constructor & Destructor Documentation
IOdata()
IOdata::IOdata ()
Standard constructor.
Definition at line 17 of file IOdata.cpp.
References Attrib::add(), Byte, Attrib::IODATA, m_address, m_block, m_dataU16, m_dataU32, m_dataU8, m_header, m_length, m_subAddress, m_wordSize, Object::setName(), and Object::setType().
                 {
  setName("IO");
  setType("IOdata");
  add(Attrib::IODATA);
  m_dataU8=0;
  m_dataU16=0;
  m_dataU32=0;
  m_address=0;
  m_header=0;
  m_subAddress=0;
  m_length =0;
  m_block =1;
  m_wordSize=IOdata::Byte;
}
 IOdata()
IOdata::~IOdata () [virtual]
Destructor.
Definition at line 34 of file IOdata.cpp.
References clearDataU16(), clearDataU32(), and clearDataU8().
                {
  clearDataU8();
  clearDataU16();
  clearDataU32();
}
Member Function Documentation
add()
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), TestI2C::setAddress(), TestSPI::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
address()
U32 IOdata::address () [inline]
Get IOdata address
Definition at line 59 of file IOdata.h.
References m_address.
Referenced by IOobject::address(), BOOST_PYTHON_MODULE(), UsbI2cBus::read(), UsbSpiBus::read(), UsbFTInterface::read(), UsbFTMLInterface::read(), setAddress(), UsbI2cBus::write(), UsbSpiBus::write(), UsbFTInterface::write(), and UsbFTMLInterface::write().
               {
    return m_address;
  }
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
block()
U32 IOdata::block () [inline]
Get IOdata length
Definition at line 162 of file IOdata.h.
References m_block.
Referenced by BOOST_PYTHON_MODULE(), and setBlock().
             {
    return m_block;
  }
bus()
IOdata::Bus IOdata::bus () [inline]
Get IOdata bus
Definition at line 147 of file IOdata.h.
References m_bus.
Referenced by BOOST_PYTHON_MODULE(), and setBus().
                 {
    return m_bus;
  }
clearDataU16()
void IOdata::clearDataU16 () [inline]
Definition at line 205 of file IOdata.h.
References m_dataU16.
Referenced by defDataU16(), and ~IOdata().
                     {
    if (0!=m_dataU16) delete [] m_dataU16;
    m_dataU16=0;
  }
clearDataU32()
void IOdata::clearDataU32 () [inline]
Definition at line 209 of file IOdata.h.
References m_dataU32.
Referenced by defDataU32(), and ~IOdata().
                     {
    if (0!=m_dataU32) delete [] m_dataU32;
    m_dataU32=0;
  }
clearDataU8()
void IOdata::clearDataU8 () [inline]
Definition at line 200 of file IOdata.h.
References m_dataU8.
Referenced by defDataU8(), and ~IOdata().
                    {
    if (0!=m_dataU8) delete [] m_dataU8;
    m_dataU8=0;
  }
dataU16() [1/2]
U16* IOdata::dataU16 () [inline]
Definition at line 218 of file IOdata.h.
References m_dataU16.
Referenced by BOOST_PYTHON_MODULE(), A3PE::enableStorage(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), A3PE::lengthAX(), A3PE::pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), Register::setBit(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setPipeline(), UsbFTInterface::write(), and UsbFTMLInterface::write().
                {
    return m_dataU16;
  }
dataU16() [2/2]
unsigned long int IOdata::dataU16 (unsigned long int i) [inline]
Definition at line 231 of file IOdata.h.
References m_dataU16.
                                                {
    return m_dataU16[i];
  }
dataU32() [1/2]
U32* IOdata::dataU32 () [inline]
Definition at line 222 of file IOdata.h.
References m_dataU32.
Referenced by BOOST_PYTHON_MODULE(), A3PE::clockDivision(), Register::getBit(), A3PE::latencyAX(), A3PE::nTrigger(), UsbFTInterface::read(), UsbFTMLInterface::read(), Register::setBit(), A3PE::setClockDivision(), A3PE::setNTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTInterface::write(), and UsbFTMLInterface::write().
                {
    return m_dataU32;
  }
dataU32() [2/2]
unsigned long int IOdata::dataU32 (unsigned long int i) [inline]
Definition at line 235 of file IOdata.h.
References m_dataU32.
                                                {
    return m_dataU32[i];
  }
dataU8() [1/2]
U8* IOdata::dataU8 () [inline]
Definition at line 214 of file IOdata.h.
References m_dataU8.
Referenced by BOOST_PYTHON_MODULE(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), UsbSpiBus::ctrlWd(), Acquisition::decodeFormat(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), StorageFifo::execute(), StorageFifoAcquisition::execute(), TestUSB::execute(), SeqPGA::extTrig(), Register::getBit(), FePGA::i2cAdd(), SeqPGA::i2cAdd(), FePGA::i2cData(), SeqPGA::i2cData(), FePGA::i2cGBTSCA(), SeqPGA::i2cGBTSCA(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), A3PE_BitFlip::initialize(), A3PE::loadFromAX(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), RAM::raz(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), UsbFTInterface::read(), UsbFTMLInterface::read(), ICPhaser::reset(), Register::setBit(), UsbSpiBus::setClockDivider(), SeqPGA::setExtTrig(), FePGA::setI2cGBTSCA(), SeqPGA::setI2cGBTSCA(), SeqPGA::setSpiGBTSCA(), FePGA::setSpiGBTSCA(), SeqPGA::spiAdd(), SeqPGA::spiGBTSCA(), FePGA::spiGBTSCA(), FePGA::spiRead(), SeqPGA::spiRead(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICPhaser::status(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), UsbFTInterface::write(), and UsbFTMLInterface::write().
              {
    return m_dataU8;
  }
dataU8() [2/2]
unsigned long int IOdata::dataU8 (unsigned long int i) [inline]
Definition at line 227 of file IOdata.h.
References m_dataU8.
                                               {
    return m_dataU8[i];
  }
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), A3PE::internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), SpecsMaster::reset(), SpecsSlave::reset(), FEB_v1::resetUsb(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
defDataU16()
void IOdata::defDataU16 (unsigned long size) [inline]
Definition at line 186 of file IOdata.h.
References clearDataU16(), m_dataU16, m_length, m_wordSize, cat::size, and Word.
Referenced by A3PE::A3PE(), and BOOST_PYTHON_MODULE().
                                     {
    m_length=size;
    clearDataU16();
    m_dataU16=new U16[size];
    m_wordSize=IOdata::Word;
  }
defDataU32()
void IOdata::defDataU32 (unsigned long size) [inline]
Definition at line 193 of file IOdata.h.
References clearDataU32(), DWord, m_dataU32, m_length, m_wordSize, and cat::size.
Referenced by A3PE::A3PE(), and BOOST_PYTHON_MODULE().
                                     {
    m_length=size;
    clearDataU32();
    m_dataU32=new U32[size];
    m_wordSize=IOdata::DWord;
  }
defDataU8()
void IOdata::defDataU8 (unsigned long size) [inline]
Definition at line 179 of file IOdata.h.
References Byte, clearDataU8(), m_dataU8, m_length, m_wordSize, and cat::size.
Referenced by BOOST_PYTHON_MODULE(), FePGA::FePGA(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Phaser::Phaser(), Proto40MHz_v1::Proto40MHz_v1(), SeqPGA::SeqPGA(), RAM::setSize(), UsbI2cBus::UsbI2cBus(), and UsbSpiBus::UsbSpiBus().
                                    {
    m_length=size;
    clearDataU8();
    m_dataU8=new U8[size];
    m_wordSize=IOdata::Byte;
  }
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
dump()
void IOdata::dump (unsigned int printout = 0)
Definition at line 94 of file IOdata.cpp.
References btos(), Byte, DWord, Object::info(), itob(), itos(), m_address, m_dataU16, m_dataU32, m_dataU8, m_length, m_subAddress, m_wordSize, Object::name(), Object::type(), and Word.
Referenced by BOOST_PYTHON_MODULE(), IOobject::dump(), UsbSpiBus::read(), setDataU32(), ICPhaser::status(), ICPhaser::write(), and UsbSpiBus::write().
                                      {
  if (printout==0||printout>m_length) printout=m_length;
  info("IO: "+name()+" ["+type()+"]","IOdata::dump");
  info(" Address:"+itos(m_address)+
       " SubAddress:"+itos(m_subAddress),
       "IOdata::dump");
  if (IOdata::Byte==m_wordSize&&0!=m_dataU8){
    info(" Wordsize: Byte Length: "+itos(m_length),"IOdata::dump");
    for (int i=0; i<printout; ++i){
      info(itos(i)+": "+btos(itob(m_dataU8[i],8))+" -> "+
          itos(m_dataU8[i]),"IOdata::dump");
    }
  }
  if (IOdata::Word==m_wordSize&&0!=m_dataU16){
    info(" Wordsize: Word Length: "+itos(m_length),"IOdata::dump");
    for (int i=0; i<printout; ++i){
      info(itos(i)+": "+btos(itob(m_dataU16[i],16))+" -> "+
          itos(m_dataU16[i]),"IOdata::dump");
    }
  }
  if (IOdata::DWord==m_wordSize&&0!=m_dataU32){
    info(" Wordsize: DWord Length: "+itos(m_length),"IOdata::dump");
    for (int i=0; i<printout; ++i){
      info(itos(i)+": "+btos(itob(m_dataU32[i],32))+" -> "+
          itos(m_dataU32[i]),"IOdata::dump");
    }
  }
}
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
header()
U32 IOdata::header () [inline]
Get IOdata header
Definition at line 74 of file IOdata.h.
References m_header.
Referenced by BOOST_PYTHON_MODULE(), and setHeader().
              {
    return m_header;
  }
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTMLInterface::close(), UsbFTInterface::close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), UsbFTMLInterface::help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), MSOxxxx::id(), Croc::init(), NI6008::init(), Computer::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbI2cBus::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), FePGA::reset(), SeqPGA::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), FEB_v1::resetFifoSpyFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), SeqPGA::resetUsb(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FEB_v1::testDuration(), SeqPGA::testSequence(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
length()
U32 IOdata::length () [inline]
Get IOdata length
Definition at line 175 of file IOdata.h.
References m_length.
Referenced by BOOST_PYTHON_MODULE(), UsbI2cBus::read(), UsbSpiBus::read(), UsbFTMLInterface::read(), UsbFTInterface::read(), setDataU16(), setDataU32(), setDataU8(), setLength(), UsbI2cBus::write(), UsbSpiBus::write(), UsbFTInterface::write(), and UsbFTMLInterface::write().
              {
    return m_length;
  }
mode()
IOdata::Mode IOdata::mode () [inline]
Get IOdata mode
Definition at line 119 of file IOdata.h.
References m_mode.
Referenced by BOOST_PYTHON_MODULE(), and setMode().
                   {
    return m_mode;
  }
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), SeqPGA::help(), NI6008::help(), Computer::help(), SpecsParallelBus::help(), UsbFTInterface::help(), UsbFTMLInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), Data::hist2d(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), CU_v1::reset(), UsbSpiBus::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), SpecsSlave::resetInternal(), FEB_v1::resetUsb(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), Object::setName(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTMLInterface::update(), UsbFTInterface::update(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
outputSelect()
U32 IOdata::outputSelect () [inline]
Get IOdata output select
Definition at line 104 of file IOdata.h.
References m_outputSelect.
Referenced by BOOST_PYTHON_MODULE(), and setOutputSelect().
                    {
    return m_outputSelect;
  }
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
setAddress()
StatusCode IOdata::setAddress (U32 address) [inline]
Define IOdata address
Definition at line 51 of file IOdata.h.
References address(), m_address, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), FePGA::FePGA(), ICPhaser::read(), SeqPGA::SeqPGA(), IOobject::setAddress(), ICPhaser::status(), UsbI2cBus::UsbI2cBus(), and UsbSpiBus::UsbSpiBus().
                                    {
    m_address=address;
    return StatusCode::SUCCESS;
  }
setBlock()
StatusCode IOdata::setBlock (U32 block) [inline]
Define IOdata block
Definition at line 168 of file IOdata.h.
References block(), m_block, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                {
    m_block=block;
    return StatusCode::SUCCESS;
  }
setBus()
StatusCode IOdata::setBus (IOdata::Bus bus) [inline]
Define IOdata bus
Definition at line 140 of file IOdata.h.
References bus(), m_bus, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                  {
    m_bus=bus;
    return StatusCode::SUCCESS;
  }
setDataU16()
void IOdata::setDataU16 (U16 * data, U32 length) [inline]
Definition at line 246 of file IOdata.h.
References shell::data(), length(), m_dataU16, m_length, m_wordSize, and Word.
                                        {
// clearDataU16();
    m_dataU16=data;
    m_length=length;
    m_wordSize=IOdata::Word;
  }
setDataU32()
void IOdata::setDataU32 (U32 * data, U32 length) [inline]
Definition at line 253 of file IOdata.h.
References shell::data(), dump(), DWord, length(), m_dataU32, m_length, m_wordSize, setU16(), setU32(), and setU8().
                                        {
// clearDataU32();
    m_dataU32=data;
    m_length=length;
    m_wordSize=IOdata::DWord;
  }
setDataU8()
void IOdata::setDataU8 (U8 * data, U32 length) [inline]
Definition at line 239 of file IOdata.h.
References Byte, shell::data(), length(), m_dataU8, m_length, and m_wordSize.
Referenced by UsbI2cBus::read(), and UsbI2cBus::write().
                                      {
// clearDataU8();
    m_dataU8=data;
    m_length=length;
    m_wordSize=IOdata::Byte;
  }
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setHeader()
StatusCode IOdata::setHeader (U32 header) [inline]
Define IOdata header
Definition at line 66 of file IOdata.h.
References header(), m_header, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                  {
    m_header=header;
    return StatusCode::SUCCESS;
  }
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setLength()
StatusCode IOdata::setLength (U32 length) [inline]
Define IOdata length
Definition at line 154 of file IOdata.h.
References length(), m_length, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                  {
    m_length=length;
    return StatusCode::SUCCESS;
  }
setMode()
StatusCode IOdata::setMode (IOdata::Mode mode) [inline]
Define IOdata mode
Definition at line 111 of file IOdata.h.
References m_mode, mode(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                     {
    m_mode=mode;
    return StatusCode::SUCCESS;
  }
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata(), IOobject::IOobject(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setOutputSelect()
StatusCode IOdata::setOutputSelect (U32 outputSelect) [inline]
Define IOdata output select
Definition at line 96 of file IOdata.h.
References m_outputSelect, outputSelect(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                              {
    m_outputSelect=outputSelect;
    return StatusCode::SUCCESS;
  }
setSubAddress()
StatusCode IOdata::setSubAddress (U32 subAddress) [inline]
Define IOdata subaddress
Definition at line 81 of file IOdata.h.
References m_subAddress, subAddress(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), ICECALv3::ICECALv3(), and ICPhaser::ICPhaser().
                                          {
    m_subAddress=subAddress;
    return StatusCode::SUCCESS;
  }
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
setU16()
StatusCode IOdata::setU16 (unsigned long int position, U16 value)
Definition at line 60 of file IOdata.cpp.
References StatusCode::FAILURE, itos(), m_dataU16, m_length, StatusCode::SUCCESS, and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), A3PE::enableStorage(), A3PE::reset(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), setDataU32(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLengthAX(), and A3PE::setPipeline().
                                                              {
  if (position>m_length-1){
    warning("You cannot write at position "+itos(position)+".",
        "IOdata::setU16");
    return StatusCode::FAILURE;
  }
  if (0==m_dataU16){
    warning("Data buffer not allocated. Data not stored.","IOdata::setU16");
    return StatusCode::FAILURE;
  }
  m_dataU16[position]=value;
  return StatusCode::SUCCESS;
}
setU32()
StatusCode IOdata::setU32 (unsigned long int position, U32 value)
Definition at line 77 of file IOdata.cpp.
References StatusCode::FAILURE, itos(), m_dataU32, m_length, StatusCode::SUCCESS, and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), Register::setBit(), A3PE::setClockDivision(), setDataU32(), A3PE::setLatencyAX(), A3PE::setNTrigger(), A3PE::setTriggerDelay(), and A3PE::setTriggerRate().
                                                              {
  if (position>m_length-1){
    warning("You cannot write at position "+itos(position)+".",
        "IOdata::setU32");
    return StatusCode::FAILURE;
  }
  if (0==m_dataU32){
    warning("Data buffer not allocated. Data not stored.","IOdata::setU32");
    return StatusCode::FAILURE;
  }
  m_dataU32[position]=value;
  return StatusCode::SUCCESS;
}
setU8()
StatusCode IOdata::setU8 (unsigned long int position, U8 value)
Definition at line 43 of file IOdata.cpp.
References StatusCode::FAILURE, itos(), m_dataU8, m_length, StatusCode::SUCCESS, and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), TestUSB::execute(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), SeqPGA::reset(), FePGA::reset(), SeqPGA::resetUsb(), FePGA::resetUsb(), Register::setBit(), setDataU32(), SeqPGA::setExtTrig(), FePGA::setI2cAdd(), SeqPGA::setI2cAdd(), FePGA::setI2cGBTSCA(), SeqPGA::setI2cGBTSCA(), SeqPGA::setSpiAdd(), SeqPGA::setSpiGBTSCA(), FePGA::setSpiGBTSCA(), FePGA::spiRead(), SeqPGA::spiRead(), FePGA::spiWrite(), and SeqPGA::spiWrite().
                                                            {
  if (position>m_length-1){
    warning("You cannot write at position "+itos(position)+".",
        "IOdata::setU8");
    return StatusCode::FAILURE;
  }
  if (0==m_dataU8){
    warning("Data buffer not allocated. Data not stored.","IOdata::setU8");
    return StatusCode::FAILURE;
  }
  m_dataU8[position]=value;
  return StatusCode::SUCCESS;
}
setWordSize()
StatusCode IOdata::setWordSize (IOdata::WordSize wordSize) [inline]
Define IOdata word size
Definition at line 126 of file IOdata.h.
References m_wordSize, StatusCode::SUCCESS, and wordSize().
Referenced by BOOST_PYTHON_MODULE(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SeqPGA::SeqPGA(), UsbI2cBus::UsbI2cBus(), and UsbSpiBus::UsbSpiBus().
                                                 {
    m_wordSize=wordSize;
    return StatusCode::SUCCESS;
  }
subAddress()
U32 IOdata::subAddress () [inline]
Get IOdata subaddress
Definition at line 89 of file IOdata.h.
References m_subAddress.
Referenced by BOOST_PYTHON_MODULE(), ICPhaser::read(), setSubAddress(), ICPhaser::status(), and ICPhaser::write().
                  {
    return m_subAddress;
  }
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestUSB::Plot(), TestSPI::Plot(), TestI2C::Plot(), Object::setTitle(), and Application::terminate().
{ return m_title; } // < Get Object m_title
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTInterface::read(), UsbFTMLInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), wait(), UsbFTInterface::write(), and UsbFTMLInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), Acquisition::execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), EmulateFE::initialize(), TestI2C::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsSlave::reset(), SpecsMaster::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), setU16(), setU32(), setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
wordSize()
IOdata::WordSize IOdata::wordSize () [inline]
Get IOdata word size
Definition at line 133 of file IOdata.h.
References m_wordSize.
Referenced by BOOST_PYTHON_MODULE(), UsbFTInterface::read(), UsbFTMLInterface::read(), setWordSize(), UsbFTInterface::write(), and UsbFTMLInterface::write().
                           {
    return m_wordSize;
  }
Member Data Documentation
m_address
unsigned long IOdata::m_address [private]
Definition at line 271 of file IOdata.h.
Referenced by address(), dump(), IOdata(), and setAddress().
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_block
unsigned long IOdata::m_block [private]
Definition at line 279 of file IOdata.h.
Referenced by block(), IOdata(), and setBlock().
m_bus
IOdata::Bus IOdata::m_bus [private]
Definition at line 277 of file IOdata.h.
Referenced by bus(), and setBus().
m_dataU16
U16* IOdata::m_dataU16 [private]
Definition at line 281 of file IOdata.h.
Referenced by clearDataU16(), dataU16(), defDataU16(), dump(), IOdata(), setDataU16(), and setU16().
m_dataU32
U32* IOdata::m_dataU32 [private]
Definition at line 282 of file IOdata.h.
Referenced by clearDataU32(), dataU32(), defDataU32(), dump(), IOdata(), setDataU32(), and setU32().
m_dataU8
U8* IOdata::m_dataU8 [private]
Definition at line 280 of file IOdata.h.
Referenced by clearDataU8(), dataU8(), defDataU8(), dump(), IOdata(), setDataU8(), and setU8().
m_header
unsigned long IOdata::m_header [private]
Definition at line 272 of file IOdata.h.
Referenced by header(), IOdata(), and setHeader().
m_length
unsigned long IOdata::m_length [private]
Definition at line 278 of file IOdata.h.
Referenced by defDataU16(), defDataU32(), defDataU8(), dump(), IOdata(), length(), setDataU16(), setDataU32(), setDataU8(), setLength(), setU16(), setU32(), and setU8().
m_mode
IOdata::Mode IOdata::m_mode [private]
Definition at line 275 of file IOdata.h.
Referenced by mode(), and setMode().
m_outputSelect
unsigned long IOdata::m_outputSelect [private]
Definition at line 274 of file IOdata.h.
Referenced by outputSelect(), and setOutputSelect().
m_subAddress
unsigned long IOdata::m_subAddress [private]
Definition at line 273 of file IOdata.h.
Referenced by dump(), IOdata(), setSubAddress(), and subAddress().
m_wordSize
IOdata::WordSize IOdata::m_wordSize [private]
Definition at line 276 of file IOdata.h.
Referenced by defDataU16(), defDataU32(), defDataU8(), dump(), IOdata(), setDataU16(), setDataU32(), setDataU8(), setWordSize(), and wordSize().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/inc/IOdata.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/src/IOdata.cpp