SpecsMezzanine Class Reference
#include <inc/SpecsMezzanine.h>
Public Member Functions
SpecsMezzanine ()
Standard constructor.
virtual ~SpecsMezzanine ()
Standard Desctructor.
void addBus (Element *)
void help ()
bool led ()
int date ()
void setLed (bool)
bool cmdline (std::vector< std::string >)
Private Attributes
SpecsBus * m_bus
DCU * m_dcu
Additional Inherited Members
Detailed Description
Author
Frédéric Machefert
Date
2005-05-25
Definition at line 18 of file SpecsMezzanine.h.
Constructor & Destructor Documentation
SpecsMezzanine()
SpecsMezzanine::SpecsMezzanine ()
Standard constructor.
Definition at line 22 of file SpecsMezzanine.cpp.
References Hierarchy::addChild(), SpecsSlave::addI2c(), Object::debug(), m_bus, m_dcu, SpecsSlave::setAddress(), DCU::setAddress(), Object::setName(), DCU::setOutputSelect(), Hierarchy::setParent(), and Object::setType().
                                 {
  debug("SpecsMezzanine::SpecsMezzanine","SpecsMezzanine built.");
  setAddress(0x0);
  setName("SpecsMezzanine");
  setType("SpecsMezzanine");
  m_bus = new SpecsBus();
  m_bus->setParent(this);
  addChild(m_bus);
  m_dcu=new DCU();
  m_dcu->setName("DCU");
  m_dcu->setOutputSelect (0xF) ; // i2c short distance for DCU
  m_dcu->setAddress (0) ;
  addI2c(m_dcu);
}
 SpecsMezzanine()
SpecsMezzanine::~SpecsMezzanine () [virtual]
Standard Desctructor.
Destructor
Definition at line 43 of file SpecsMezzanine.cpp.
{}
Member Function Documentation
addBus()
void SpecsMezzanine::addBus (Element * element)
Add o device on the parallel bus of the specs mezzanine
Definition at line 48 of file SpecsMezzanine.cpp.
References Hierarchy::addChild(), Object::debug(), m_bus, Object::name(), and Hierarchy::setParent().
                                           {
  element->setParent(m_bus);
  m_bus->addChild(element);
  debug("SpecsMezzanine::addBus",
    element->name()+" added to the bus child tree.");
}
cmdline()
bool SpecsMezzanine::cmdline (std::vector< std::string > cmd)
access to the command line function
Definition at line 58 of file SpecsMezzanine.cpp.
References Attrib::add(), SpecsInterface::address(), shell::data(), date(), help(), Object::info(), itos(), SpecsSlave::reset(), SpecsSlave::resetInternal(), SpecsSlave::setAddress(), setLed(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), and SpecsInterface::specsWriteRegister().
                                                     {
  if (cmd.size()==0){
    info("cmdline","Date : "+itos(date()));
    return true;
    info("cmdline","Address [Address] : "+itos(address()));
    return true;
  }
  transform(cmd[0].begin(),cmd[0].end(),cmd[0].begin(),tolower);
  if (cmd[0].compare("address")==0){
    this->setAddress(atoi(cmd[1].c_str()));
    return true;
  }
  if (cmd[0].compare("address")==0){
    this->setAddress(atoi(cmd[1].c_str()));
    return true;
  }
  if (cmd[0].compare("reset")==0){
    this->reset();
    return true;
  }
  if (cmd[0].compare("internalreset")==0){
    this->resetInternal();
    return true;
  }
  if (cmd[0].compare("led")==0){
    if (0==atoi(cmd[1].c_str())) {
      setLed (false);
    }
    else {
      setLed (true);
    }
    return true;
  }
  if (cmd[0].compare("regwrite")==0){
    info("cmdline",
       "Register "+ cmd[1]+ " -> Write " + cmd[2]);
    this->specsWriteRegister(atoi(cmd[1].c_str()),
                  atoi(cmd[2].c_str()));
    return true;
  }
  if (cmd[0].compare("i2cwritereg")==0){
    int add = atoi(cmd[1].c_str());
    int out = atoi(cmd[2].c_str());
    int ssadd = atoi(cmd[3].c_str());
    int nword = atoi(cmd[4].c_str());
    U8 data[100];
    for (int i = 0 ; i< nword ; ++i) {
      data[i]=(unsigned char) (atoi(cmd[5+i].c_str()));
    }
    info("cmdline",
       "I2C Register "+ cmd[2]+ "/" + itos(add) +
       " -> Write " + cmd[4] + " words.");
    this->specsWriteI2c(add , out , ssadd , nword, data);
    return true;
  }
  if (cmd[0].compare("i2creadreg")==0){
    int add = atoi(cmd[1].c_str());
    int out = atoi(cmd[2].c_str());
    int ssadd = atoi(cmd[3].c_str());
    int nword = atoi(cmd[4].c_str());
    U8 data[100];
    info("cmdline",
       "I2C Register "+ cmd[2]+ "/" + itos(add) +
       " -> Read " + cmd[3] + " words.");
    this->specsReadI2c(add , out , ssadd , nword, data);
    for (int i = 0 ; i< nword ; ++i) {
      info(""," word ["+ itos (i) + "]" + itos(data[i]));
    }
    return true;
  }
  if (cmd[0].compare("regread")==0){
    U16 val;
    this->specsReadRegister(atoi(cmd[1].c_str()),
                 val);
    info("cmdline",
       "Register "+ cmd[1]+ " -> " + itos(val));
    return true;
  }
  if (cmd[0].compare("help")==0){
    this->help();
    return true;
  }
  return false;
}
date()
int SpecsMezzanine::date ()
Get the Specs Slave Date
Definition at line 174 of file SpecsMezzanine.cpp.
References SpecsInterface::specsReadRegister(), and Object::warning().
Referenced by cmdline().
                        {
  unsigned char reg = 8 ;
#ifndef _NODEVICE_
  U16 val ;
  this -> specsReadRegister(reg , val);
  val = (val&0xFF00)*100+(val&0xFF);
  return val;
#else
  warning("" , "Compilation in _NoDevice_ mode.");
#endif
  return 0;
}
help()
void SpecsMezzanine::help () [virtual]
Help message for the Specs Slaves
Reimplemented from SpecsInterface.
Definition at line 159 of file SpecsMezzanine.cpp.
References Object::info(), and Object::msgSvc().
Referenced by cmdline().
                           {
  info("SpecsMezzanine","Specs Mezzanine Element help");
  msgSvc(0,"","");
  msgSvc(0,"","Address # : set slave address at #");
  msgSvc(0,"","Reset : reset of the slave");
  msgSvc(0,"","ResetInternal : internal reset of the slave");
  msgSvc(0,"","RegWrite #0 #1 : write register #0 with value #1");
  msgSvc(0,"","RegRead #0 #1 : read register #");
  msgSvc(0,"","");
}
led()
bool SpecsMezzanine::led ()
Get the state of the LEDs controlled by the Specs Slave
Definition at line 213 of file SpecsMezzanine.cpp.
References Object::debug(), SpecsInterface::specsReadRegister(), and Object::warning().
                           {
  unsigned char reg = 4 ;
#ifndef _NODEVICE_
  U16 val ;
  this -> specsReadRegister(reg , val);
  if (0 != (val & 0x0800)){
    debug("SpecsMezzanine::led","Glue LEDs are OFF");
    return false;
  }
#else
  warning("" , "Compilation in _NoDevice_ mode.");
  return true;
#endif
  debug("SpecsMezzanine::led","Glue LEDs are ON");
  return true;
}
setLed()
void SpecsMezzanine::setLed (bool state)
Set the state of the LEDs controlled by the Specs Slave
Definition at line 190 of file SpecsMezzanine.cpp.
References Object::debug(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteRegister(), and Object::warning().
Referenced by cmdline().
                                        {
  unsigned char reg = 4 ;
#ifndef _NODEVICE_
  U16 val;
  this -> specsReadRegister(reg , val);
  if (state) {
    val = (val & 0xF7FF) ;
    this -> specsWriteRegister(reg, (val>>8));
    debug("SpecsMezzanine::led","setting Glue LEDs On");
  }
  else {
    val = (val | 0x0800) ;
    this -> specsWriteRegister(reg , (val>>8)) ;
    debug("SpecsMezzanine::led","setting Glue LEDs OFF");
  }
#else
  warning("" , "Compilation in _NoDevice_ mode.");
#endif
}
Member Data Documentation
m_bus
SpecsBus* SpecsMezzanine::m_bus [private]
Definition at line 59 of file SpecsMezzanine.h.
Referenced by addBus(), and SpecsMezzanine().
m_dcu
DCU* SpecsMezzanine::m_dcu [private]
Definition at line 60 of file SpecsMezzanine.h.
Referenced by SpecsMezzanine().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/inc/SpecsMezzanine.h
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/src/SpecsMezzanine.cpp