UsbMLSpiBus Class Reference
#include <inc/UsbMLSpiBus.h>
Public Types
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
Public Member Functions
UsbMLSpiBus ()
virtual ~UsbMLSpiBus ()
Standard constructor.
void help ()
virtual StatusCode init ()
void reset ()
void update ()
Additional Inherited Members
Detailed Description
Author
Date
2006-10-23
Definition at line 16 of file UsbMLSpiBus.h.
Member Typedef Documentation
U16
typedef unsigned short UsbMLSpiBus::U16
Definition at line 19 of file UsbMLSpiBus.h.
U32
typedef unsigned long UsbMLSpiBus::U32
Definition at line 18 of file UsbMLSpiBus.h.
U8
typedef unsigned char UsbMLSpiBus::U8
Definition at line 20 of file UsbMLSpiBus.h.
Constructor & Destructor Documentation
UsbMLSpiBus()
UsbMLSpiBus::UsbMLSpiBus ()
Definition at line 17 of file UsbMLSpiBus.cpp.
References Object::setName(), and Object::setType().
                           {
  setName("UsbMLSpiBus");
  setType("UsbMLSpiBus");
}
 UsbMLSpiBus()
UsbMLSpiBus::~UsbMLSpiBus () [virtual]
Standard constructor.
Destructor
Definition at line 24 of file UsbMLSpiBus.cpp.
                          {
// delete m_regData;
// delete m_regAddress;
}
Member Function Documentation
help()
void UsbMLSpiBus::help () [inline], [virtual]
printout help for the element
Implements Element.
Definition at line 28 of file UsbMLSpiBus.h.
References Object::info(), init(), and Object::name().
{ info("UsbMLSpiBus "+name()+". No help.","UsbMLSpiBus::help"); };
init()
StatusCode UsbMLSpiBus::init () [virtual]
init the component
Returns
void
Implements Element.
Definition at line 32 of file UsbMLSpiBus.cpp.
References StatusCode::FAILURE, Object::fatal(), Element::m_connection, Hierarchy::parent(), Element::setConnection(), StatusCode::SUCCESS, and Object::type().
Referenced by help().
                             {
  if (0==m_connection){
    if (0==this->parent()){
      fatal("Cannot define connection for "+type()+". No parent found.",
          "UsbMLSpiBus::init");
        return StatusCode::FAILURE;
    }
    return setConnection(this->parent());
  }
  else return StatusCode::SUCCESS;
}
reset()
void UsbMLSpiBus::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 45 of file UsbMLSpiBus.h.
References Object::info(), and Object::name().
               {
    info("UsbMLSpiBus "+name()+" reset.","UsbMLSpiBus::reset");
  };
update()
void UsbMLSpiBus::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 53 of file UsbMLSpiBus.h.
References Object::info(), and Object::name().
Referenced by AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
                 {
    info("UsbMLSpiBus "+name()+". Nothing to do.","UsbMLSpiBus::update");
  };
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/UsbMLSpiBus.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/UsbMLSpiBus.cpp