Croc Class Reference
#include <inc/Croc.h>
Classes
class Croc
Public Member Functions
Croc ()
Standard constructor.
virtual ~Croc ()
Destructor.
void help ()
StatusCode init ()
void reset ()
void update ()
Additional Inherited Members
Detailed Description
Author
Date
2006-10-23
Definition at line 15 of file Croc.h.
Constructor & Destructor Documentation
Croc()
Croc::Croc ()
Standard constructor.
Definition at line 17 of file Croc.cpp.
References Object::setName(), and Object::setType().
             {
  setName("Croc");
  setType("Croc");
}
 Croc()
Croc::~Croc () [virtual]
Destructor.
Definition at line 24 of file Croc.cpp.
{}
Member Function Documentation
help()
void Croc::help () [inline], [virtual]
printout help for the element
Implements Element.
Definition at line 25 of file Croc.h.
References Object::info(), and Object::name().
{ info("Croc "+name()+". No help.","Croc::help"); };
init()
StatusCode Croc::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 31 of file Croc.h.
References Object::info(), Object::name(), and StatusCode::SUCCESS.
                    {
    info("Croc "+name()+" initialization.","Croc::init");
    return StatusCode::SUCCESS;
  };
reset()
void Croc::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 43 of file Croc.h.
References Object::info(), and Object::name().
{ info("Croc "+name()+" reset.","Croc::reset");};
update()
void Croc::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 48 of file Croc.h.
References Object::info(), and Object::name().
Referenced by A3PE_BitFlip.A3PE_BitFlip::__init__(), Acquisition.Acquisition::__init__(), EmulateFE.EmulateFE::__init__(), AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
{info("Croc "+name()+". Nothing to do.","Croc::update");};
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCalo/inc/Croc.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCalo/src/Croc.cpp