IOobject Class Reference
#include <inc/IOobject.h>
Public Types
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
Public Member Functions
IOobject ()
Standard constructor.
virtual ~IOobject ()
Destructor.
void help ()
void reset ()
void update ()
virtual StatusCode init ()
IOdata * io ()
virtual StatusCode read ()
virtual StatusCode write ()
void setAddress (U32 address)
U32 address ()
void dump ()
Private Attributes
IOdata * m_io
Additional Inherited Members
Detailed Description
Author
Date
2006-10-23
Definition at line 17 of file IOobject.h.
Member Typedef Documentation
U16
typedef unsigned short IOobject::U16
Definition at line 20 of file IOobject.h.
U32
typedef unsigned long IOobject::U32
Definition at line 19 of file IOobject.h.
U8
typedef unsigned char IOobject::U8
Definition at line 21 of file IOobject.h.
Constructor & Destructor Documentation
IOobject()
IOobject::IOobject ()
Standard constructor.
Definition at line 17 of file IOobject.cpp.
References Attrib::add(), Attrib::ELEMENT, Attrib::IO, m_io, Object::setName(), and Object::setType().
                     {
  setName("IOobject");
  setType("IOobject");
  add(Attrib::ELEMENT); add(Attrib::IO);
  m_io=new IOdata();
}
 IOobject()
IOobject::~IOobject () [virtual]
Destructor.
Definition at line 26 of file IOobject.cpp.
References m_io.
                    {
  delete m_io;
}
Member Function Documentation
address()
U32 IOobject::address () [inline]
Definition at line 88 of file IOobject.h.
References IOdata::address(), and m_io.
Referenced by BOOST_PYTHON_MODULE().
               {
    return m_io->address();
  }
dump()
void IOobject::dump () [inline]
Definition at line 92 of file IOobject.h.
References IOdata::dump(), and m_io.
Referenced by BOOST_PYTHON_MODULE(), and FePGA::resetUsb().
             {
    m_io->dump(0);
  }
help()
void IOobject::help () [inline], [virtual]
printout help for the element
Implements Element.
Reimplemented in RAM.
Definition at line 31 of file IOobject.h.
References Object::info(), and Object::name().
Referenced by BOOST_PYTHON_MODULE().
{ info("IOobject "+name()+". No help.","IOobject::help"); };
init()
virtual StatusCode IOobject::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 54 of file IOobject.h.
References StatusCode::FAILURE, Object::fatal(), Element::m_connection, Hierarchy::parent(), Element::setConnection(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                            {
    if (0==m_connection){
      if (0==this->parent()){
        fatal("Cannot define connection for IOobject. No parent found.",
            "IOobject::init");
          return StatusCode::FAILURE;
      }
      return setConnection(this->parent());
    }
    else return StatusCode::SUCCESS;
  };
io()
IOdata* IOobject::io () [inline]
Definition at line 66 of file IOobject.h.
References m_io.
Referenced by A3PE::A3PE(), BOOST_PYTHON_MODULE(), UsbSpiBus::clockDivider(), A3PE::clockDivision(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), UsbSpiBus::ctrlWd(), Acquisition::decodeFormat(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), A3PE::enableStorage(), StorageFifo::execute(), StorageFifoAcquisition::execute(), TestUSB::execute(), SeqPGA::extTrig(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), FePGA::i2cAdd(), SeqPGA::i2cAdd(), FePGA::i2cData(), SeqPGA::i2cData(), FePGA::i2cGBTSCA(), SeqPGA::i2cGBTSCA(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), A3PE_BitFlip::initialize(), A3PE::latencyAX(), SeqPGA::ledEnable(), A3PE::lengthAX(), A3PE::loadFromAX(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), FePGA::MakeRAM(), FePGA::MakeRegister(), A3PE::nTrigger(), Phaser::Phaser(), A3PE::pipeline(), Proto40MHz_v1::Proto40MHz_v1(), RAM::raz(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), FePGA::reset(), SeqPGA::reset(), ICPhaser::reset(), A3PE::reset(), SeqPGA::resetSpi(), FePGA::resetUsb(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), UsbSpiBus::setClockDivider(), A3PE::setClockDivision(), SeqPGA::setExtTrig(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FePGA::setI2cAdd(), SeqPGA::setI2cAdd(), FePGA::setI2cGBTSCA(), SeqPGA::setI2cGBTSCA(), A3PE::setLatencyAX(), SeqPGA::setLedEnable(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), RAM::setSize(), FePGA::setSpiAdd(), SeqPGA::setSpiAdd(), SeqPGA::setSpiEnable(), SeqPGA::setSpiGBTSCA(), FePGA::setSpiGBTSCA(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SeqPGA::spiAdd(), SeqPGA::spiEnable(), SeqPGA::spiGBTSCA(), FePGA::spiGBTSCA(), FePGA::spiRead(), ICECALv3::spiRead(), SeqPGA::spiRead(), FePGA::spiWrite(), ICECALv3::spiWrite(), SeqPGA::spiWrite(), ICPhaser::status(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbI2cBus::UsbI2cBus(), UsbSpiBus::UsbSpiBus(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), and UsbSpiBus::write().
              {
    return m_io;
  }
read()
virtual StatusCode IOobject::read () [inline], [virtual]
Read the IOobject
Definition at line 73 of file IOobject.h.
References Element::connection(), and m_io.
Referenced by BOOST_PYTHON_MODULE(), A3PE::clockDivision(), LSDelayChipV1::configRegBulkRead(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), A3PE::enableStorage(), StorageFifo::execute(), StorageFifoAcquisition::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), TestUSB::execute(), SeqPGA::extTrig(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), FePGA::i2cAdd(), SeqPGA::i2cAdd(), FePGA::i2cGBTSCA(), SeqPGA::i2cGBTSCA(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), A3PE::latencyAX(), SeqPGA::ledEnable(), A3PE::lengthAX(), A3PE::nTrigger(), A3PE::pipeline(), Phaser::read(), ICPhaser::read(), Register::setBit(), A3PE::setClockDivision(), SeqPGA::setExtTrig(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FePGA::setI2cGBTSCA(), SeqPGA::setI2cGBTSCA(), SeqPGA::setLedEnable(), A3PE::setNTrigger(), A3PE::setPipeline(), SeqPGA::setSpiEnable(), SeqPGA::setSpiGBTSCA(), FePGA::setSpiGBTSCA(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SeqPGA::spiAdd(), SeqPGA::spiEnable(), SeqPGA::spiGBTSCA(), FePGA::spiGBTSCA(), FePGA::spiRead(), ICECALv3::spiRead(), SeqPGA::spiRead(), ICPhaser::status(), A3PE::triggerDelay(), and A3PE::triggerRate().
                           {
    return (dynamic_cast<Interface*>(connection()))->read(m_io);
  }
reset()
void IOobject::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 41 of file IOobject.h.
Referenced by BOOST_PYTHON_MODULE().
               {
  };
setAddress()
void IOobject::setAddress (U32 address) [inline]
Definition at line 84 of file IOobject.h.
References m_io, and IOdata::setAddress().
Referenced by A3PE::A3PE(), BOOST_PYTHON_MODULE(), FEB_v1::FEB_v1(), Proto40MHz_v1::Proto40MHz_v1(), SeqPGA::SeqPGA(), and ICPhaser::setAddress().
                              {
    m_io->setAddress(address);
  }
update()
void IOobject::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 47 of file IOobject.h.
Referenced by BOOST_PYTHON_MODULE(), AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
                {
  };
write()
virtual StatusCode IOobject::write () [inline], [virtual]
Write the IOobject
Definition at line 80 of file IOobject.h.
References Element::connection(), and m_io.
Referenced by BOOST_PYTHON_MODULE(), LSDelayChipV1::configRegBulkWrite(), A3PE::enableStorage(), TestUSB::execute(), Register::getBit(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), A3PE::loadFromAX(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), A3PE_BitFlip::randomValues(), RAM::raz(), FePGA::reset(), SeqPGA::reset(), ICPhaser::reset(), A3PE::reset(), SeqPGA::resetSpi(), FePGA::resetUsb(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), SeqPGA::setExtTrig(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FePGA::setI2cAdd(), SeqPGA::setI2cAdd(), FePGA::setI2cGBTSCA(), SeqPGA::setI2cGBTSCA(), A3PE::setLatencyAX(), SeqPGA::setLedEnable(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), FePGA::setSpiAdd(), SeqPGA::setSpiAdd(), SeqPGA::setSpiEnable(), SeqPGA::setSpiGBTSCA(), FePGA::setSpiGBTSCA(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), FePGA::spiRead(), SeqPGA::spiRead(), FePGA::spiWrite(), ICECALv3::spiWrite(), SeqPGA::spiWrite(), SeqPGA::testSequence(), FePGA::testSequence(), FePGA::transmitSpi(), SeqPGA::transmitSpi(), Phaser::write(), and ICPhaser::write().
                             {
    return (dynamic_cast<Interface*>(connection()))->write(m_io);
  };
Member Data Documentation
m_io
IOdata* IOobject::m_io [private]
Definition at line 99 of file IOobject.h.
Referenced by address(), dump(), io(), IOobject(), read(), setAddress(), write(), and ~IOobject().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/inc/IOobject.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/src/IOobject.cpp