SpecsBus Class Reference
#include <include/SpecsBus.h>
Public Member Functions
SpecsBus ()
~SpecsBus ()
Additional Inherited Members
Detailed Description
Class Describes a parallel bus
Author
Frédéric Machefert
Date
2004-01-18
Definition at line 28 of file SpecsBus.h.
Constructor & Destructor Documentation
SpecsBus()
SpecsBus::SpecsBus () [inline]
Definition at line 30 of file SpecsBus.h.
References Object::debug(), Object::name(), Object::setId(), Object::setName(), and Object::setType().
            {
    setName("SpecsBus");
    setType("SpecsBus");
    setId(0);
    debug("SpecsBus::SpecsBus",name()+" built.");
  }
 SpecsBus()
SpecsBus::~SpecsBus () [inline]
Definition at line 36 of file SpecsBus.h.
{}
The documentation for this class was generated from the following file:
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/inc/SpecsBus.h