Factory Class Reference
#include <inc/Factory.h>
Public Member Functions
Factory ()
Standard constructor.
virtual ~Factory ()
Destructor.
void setListDLL (std::string listDLL)
std::string listDLL ()
void setListElement (std::list listElement)
std::list listElement ()
void setListProc (std::string listProc)
std::string listProc ()
Private Attributes
std::string m_listDLL
std::list m_listElement
std::string m_listProc
Detailed Description
Author
Date
2006-10-23
Definition at line 13 of file Factory.h.
Constructor & Destructor Documentation
Factory()
Factory::Factory ()
Standard constructor.
 Factory()
virtual Factory::~Factory () [virtual]
Destructor.
Member Function Documentation
listDLL()
std::string Factory::listDLL () [inline]
Get accessor to member m_listDLL
Returns
the current value of m_listDLL
Definition at line 33 of file Factory.h.
References m_listDLL.
Referenced by setListDLL().
                       {
    return m_listDLL;
  }
listElement()
std::list Factory::listElement () [inline]
Get accessor to member m_listElement
Returns
the current value of m_listElement
Definition at line 50 of file Factory.h.
References m_listElement.
Referenced by setListElement().
                         {
    return m_listElement;
  }
listProc()
std::string Factory::listProc () [inline]
Get accessor to member m_listProc
Returns
the current value of m_listProc
Definition at line 66 of file Factory.h.
References m_listProc.
Referenced by setListProc().
                        {
    return m_listProc;
  }
setListDLL()
void Factory::setListDLL (std::string listDLL) [inline]
Set accessor to member m_listDLL
Parameters
listDLL the new value for m_listDLL
Definition at line 25 of file Factory.h.
References listDLL(), and m_listDLL.
                                      {
    m_listDLL = listDLL;
  }
setListElement()
void Factory::setListElement (std::list listElement) [inline]
Set accessor to member m_listElement
Parameters
listElement the new value for m_listElement
Definition at line 42 of file Factory.h.
References listElement(), and m_listElement.
                                            {
    m_listElement = listElement;
  }
setListProc()
void Factory::setListProc (std::string listProc) [inline]
Set accessor to member m_listProc
Parameters
listProc the new value for m_listProc
Definition at line 58 of file Factory.h.
References listProc(), and m_listProc.
                                        {
    m_listProc = listProc;
  }
Member Data Documentation
m_listDLL
std::string Factory::m_listDLL [private]
Definition at line 73 of file Factory.h.
Referenced by listDLL(), and setListDLL().
m_listElement
std::list Factory::m_listElement [private]
Definition at line 74 of file Factory.h.
Referenced by listElement(), and setListElement().
m_listProc
std::string Factory::m_listProc [private]
Definition at line 75 of file Factory.h.
Referenced by listProc(), and setListProc().
The documentation for this class was generated from the following file:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Factory.h