Plot Class Reference
#include <inc/Plot.h>
Public Types
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
Plot ()
Standard constructor.
Plot (unsigned int, unsigned int)
virtual ~Plot ()
Destructor.
std::vector< std::pair< unsigned int, Histo1D *> > histos ()
std::vector< Histo1D * > histo1d ()
int pos (Histo1D *h)
void setRegion (unsigned int, unsigned int)
std::pair< unsigned int, unsigned int > region ()
int format ()
void add (TH1D *, unsigned int region=0)
void make (std::string script)
std::string draw ()
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
std::string m_attribString [10]
Private Types
typedef std::pair< unsigned int, unsigned int > Pos
typedef std::pair< unsigned int, Histo1D *> Pos1D
Private Attributes
std::pair< unsigned int, unsigned int > m_region
std::vector< std::pair< unsigned int, Histo1D *> > m_histos
std::string m_draw
Detailed Description
Author
Frederic Machefert
Date
2005-01-04
Definition at line 21 of file Plot.h.
Member Typedef Documentation
Pos
typedef std::pair< unsigned int, unsigned int > Plot::Pos [private]
Definition at line 22 of file Plot.h.
Pos1D
typedef std::pair< unsigned int , Histo1D* > Plot::Pos1D [private]
Definition at line 23 of file Plot.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
Constructor & Destructor Documentation
Plot() [1/2]
Plot::Plot ()
Standard constructor.
Definition at line 23 of file Plot.cpp.
References m_draw, and m_region.
             {
  m_region.first = 1;
  m_region.second = 1;
  m_draw=std::string("");
}
Plot() [2/2]
Plot::Plot (unsigned int x, unsigned int y)
Definition at line 31 of file Plot.cpp.
References setRegion().
                            {
  setRegion (x , y);
}
 Plot()
Plot::~Plot () [virtual]
Destructor.
Definition at line 39 of file Plot.cpp.
             {
}
Member Function Documentation
add() [1/2]
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), TestSPI::setAddress(), TestI2C::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
add() [2/2]
void Plot::add (TH1D * histo, unsigned int region = 0)
Definition at line 55 of file Plot.cpp.
References m_histos, m_region, region(), and Object::warning().
Referenced by format().
                                       {
  
  if (region > m_region.first * m_region.second){
    warning("Try plot histogram outside allowed regions.","Processus::plot");
    return;
  }
  std::pair < int , Histo1D* > graph;
  graph.first = region;
  graph.second = new Histo1D(histo);
  m_histos.push_back (graph);
}
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), A3PE::internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), CU_v1::reset(), FEB_v1::reset(), Proto40MHz_v1::reset(), SpecsMaster::reset(), SpecsSlave::reset(), FEB_v1::resetUsb(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
draw()
std::string Plot::draw () [inline]
Definition at line 103 of file Plot.h.
References m_draw.
                  {
    return m_draw;
  }
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
format()
int Plot::format () [inline]
Definition at line 80 of file Plot.h.
References add(), m_region, and region().
  {
    return (m_region.first+m_region.second*100);
  }
histo1d()
std::vector<Histo1D*> Plot::histo1d () [inline]
Definition at line 44 of file Plot.h.
References m_histos.
                               {
    std::vector<Histo1D*> h;
    for (unsigned int i=0; i<m_histos.size(); ++i)
    {
      h.push_back((m_histos[i]).second);
    }
    return h;
  }
histos()
std::vector< std::pair < unsigned int , Histo1D* > > Plot::histos () [inline]
Definition at line 36 of file Plot.h.
References m_histos.
                                                            {
    return m_histos;
  }
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTInterface::close(), UsbFTMLInterface::close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), UsbFTMLInterface::help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), MSOxxxx::id(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbI2cBus::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), FePGA::reset(), SeqPGA::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), FEB_v1::resetFifoSpyFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), SeqPGA::resetUsb(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FEB_v1::testDuration(), SeqPGA::testSequence(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
make()
void Plot::make (std::string script) [inline]
Definition at line 96 of file Plot.h.
References m_draw.
                             {
    m_draw=script;
  }
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), UsbFTInterface::help(), UsbFTMLInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), Data::hist2d(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), UsbSpiBus::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), SpecsSlave::resetInternal(), FEB_v1::resetUsb(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), Object::setName(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
pos()
int Plot::pos (Histo1D * h) [inline]
Definition at line 56 of file Plot.h.
References m_histos, and setRegion().
  {
    for (unsigned int i=0; i<m_histos.size(); ++i)
    {
      if (h==(m_histos[i]).second)
        return ((m_histos[i]).first);
    }
    return -1;
  }
region()
std::pair<unsigned int , unsigned int> Plot::region () [inline]
Definition at line 75 of file Plot.h.
References m_region.
Referenced by add(), and format().
                                                {
    return m_region;
  }
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setRegion()
void Plot::setRegion (unsigned int x, unsigned int y)
Definition at line 45 of file Plot.cpp.
References m_region.
Referenced by Plot(), and pos().
                                        {
  m_region.first = x;
  m_region.second = y;
}
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestSPI::Plot(), TestUSB::Plot(), TestI2C::Plot(), Object::setTitle(), and Application::terminate().
{ return m_title; } // < Get Object m_title
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTInterface::read(), UsbFTMLInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), wait(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), Acquisition::execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), TestI2C::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsSlave::reset(), SpecsMaster::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
Member Data Documentation
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_draw
std::string Plot::m_draw [private]
Definition at line 111 of file Plot.h.
Referenced by draw(), make(), and Plot().
m_histos
std::vector< std::pair < unsigned int , Histo1D* > > Plot::m_histos [private]
Definition at line 110 of file Plot.h.
Referenced by add(), histo1d(), histos(), and pos().
m_region
std::pair< unsigned int, unsigned int > Plot::m_region [private]
Definition at line 109 of file Plot.h.
Referenced by add(), format(), Plot(), region(), and setRegion().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Plot.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Plot.cpp