Server Class Reference
#include <inc/Server.h>
Public Member Functions
Server (Application *)
Standard constructor.
virtual ~Server ()
Destructor.
StatusCode start ()
Start Service.
StatusCode updateState ()
Update State Service.
StatusCode updateConfig ()
Update Config Service.
StatusCode cmdline (std::vector< std::string >)
void setUpdateDelay (int updateDelay)
int updateDelay ()
Private Attributes
Application * m_app
int m_updateDelay
Detailed Description
Author
Frederic Machefert
Date
2005-03-03
Definition at line 22 of file Server.h.
Constructor & Destructor Documentation
Server()
Server::Server (Application * application)
Standard constructor.
Definition at line 26 of file Server.cpp.
References application(), Object::info(), m_app, m_updateDelay, and Object::warning().
                                         {
  m_app = application;
#ifdef _NETWORK_
  m_updateDelay = 1;
  m_app->info("Server built.","Server::Server");
  m_servCmd = new CmndServ (m_app);
  m_servCtrl = new CtrlServ (m_app);
  m_servTimer = 0;
  m_servState = 0;
  m_servConfig = 0;
#else
  m_app->warning("Compilation without NETWORK capabilities","Server::Server");
#endif
}
 Server()
Server::~Server () [virtual]
Destructor.
Definition at line 44 of file Server.cpp.
                {
#ifdef _NETWORK_
  delete m_servCmd;
  delete m_servCtrl;
  if (0 != m_servState) {
    delete m_servState;
  }
  if (0 != m_servTimer) {
    delete m_servTimer;
  }
  if (0 != m_servConfig) {
    delete m_servConfig;
  }
  m_servCmd = 0;
  m_servCtrl = 0;
  m_servTimer = 0;
  m_servState = 0;
  m_servConfig = 0;
#endif
}
Member Function Documentation
cmdline()
StatusCode Server::cmdline (std::vector< std::string > cmd)
Definition at line 128 of file Server.cpp.
References StatusCode::FAILURE, Object::info(), m_app, setUpdateDelay(), StatusCode::SUCCESS, updateConfig(), updateDelay(), and updateState().
                                                        {
  if (cmd.size()==0){
    char line[200];
    std::string tmp;
    sprintf(line,"Timer [timer] : %i", updateDelay());
    m_app->info(line,"Server::cmdline");
    return StatusCode::SUCCESS;
  }
  
  transform(cmd[0].begin(),cmd[0].end(),cmd[0].begin(),tolower);
  if (cmd[0].compare("timer")==0){
    if (cmd.size() == 2) {
      setUpdateDelay (atoi(cmd[1].c_str()));
      this -> updateConfig();
      this -> updateState();
    }
    this -> updateConfig();
    this -> updateState();
    return StatusCode::SUCCESS;
  }
  return StatusCode::FAILURE;
}
setUpdateDelay()
void Server::setUpdateDelay (int updateDelay) [inline]
Set accessor to member m_updateDelay
Parameters
updateDelay the new value for m_updateDelay
Definition at line 41 of file Server.h.
References m_updateDelay, and updateDelay().
Referenced by cmdline().
                                        {
    m_updateDelay = updateDelay;
#ifdef _NETWORK_
    if (0 != m_servTimer){
      m_servTimer->setDelay (m_updateDelay);
    }
#endif
  }
start()
StatusCode Server::start ()
Start Service.
Definition at line 98 of file Server.cpp.
References application(), Application::config(), StatusCode::FAILURE, Object::info(), m_app, Object::name(), Application::procDb(), Application::state(), StatusCode::SUCCESS, updateDelay(), and Object::warning().
Referenced by Application::network(), and Application::server().
                           {
#ifdef _NETWORK_
  m_app->info("Starting CAT server " + application()->name(),"Server::start");
  DimServer::start(m_app->name().c_str());
  std::string str = m_app->name() ;
  str = m_app->name() ;
  str.append ("/state");
  m_servState = new DimService (str.c_str(),"I:4;C",
                                 m_app->state(),
                                 sizeof(*(m_app->state())));
  m_servTimer = new Timer (updateDelay() , m_servState);
  str = application()->name() ;
  str.append ("/config");
  m_servConfig = new DimService (str.c_str(),"C",
                                  m_app->config(),
                                  sizeof(*(m_app->config())));
  m_app->procDb()->startServices();
#else
  m_app->warning("compilation without NETWORK capabilities. Cannot start server.",
                 "Server::star");
  return StatusCode::FAILURE;
#endif
  return StatusCode::SUCCESS;
}
updateConfig()
StatusCode Server::updateConfig ()
Update Config Service.
Definition at line 83 of file Server.cpp.
References Object::debug(), StatusCode::FAILURE, m_app, StatusCode::SUCCESS, and Object::warning().
Referenced by cmdline(), and Application::setConfig().
                                  {
#ifdef _NETWORK_
  m_servConfig->updateService();
  m_app->debug("Updating proc database service.","Server::updateConfig");
#else
  m_app->warning("Updating server services not available (NETWORK mode off).",
                 "Server::updateConfig");
  return StatusCode::FAILURE;
#endif
  return StatusCode::SUCCESS;
}
updateDelay()
int Server::updateDelay () [inline]
Get accessor to member m_updateDelay
Returns
the current value of m_updateDelay
Definition at line 54 of file Server.h.
References m_updateDelay.
Referenced by cmdline(), setUpdateDelay(), and start().
                     {
    return m_updateDelay;
  }
updateState()
StatusCode Server::updateState ()
Update State Service.
Definition at line 68 of file Server.cpp.
References Object::debug(), StatusCode::FAILURE, m_app, StatusCode::SUCCESS, and Object::warning().
Referenced by cmdline(), and Application::setState().
                                 {
#ifdef _NETWORK_
  m_servState->updateService();
  m_app->debug("Updating state service.","Server::updateState");
#else
  m_app->warning("Updating server services not available (NETWORK mode off).",
                 "Server::updateState");
  return StatusCode::FAILURE;
#endif
  return StatusCode::SUCCESS;
}
Member Data Documentation
m_app
Application* Server::m_app [private]
Definition at line 79 of file Server.h.
Referenced by cmdline(), Server(), start(), updateConfig(), and updateState().
m_updateDelay
int Server::m_updateDelay [private]
Definition at line 80 of file Server.h.
Referenced by Server(), setUpdateDelay(), and updateDelay().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Server.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Server.cpp