Register Class Reference
#include <inc/Register.h>
Public Member Functions
Register ()
Standard constructor.
virtual ~Register ()
Destructor.
StatusCode setBit (unsigned int, bool)
bool getBit (unsigned int)
Additional Inherited Members
Detailed Description
Author
Date
2006-10-23
Definition at line 16 of file Register.h.
Constructor & Destructor Documentation
Register()
Register::Register ()
Standard constructor.
Definition at line 18 of file Register.cpp.
References Object::setName(), and Object::setType().
                     {
  setName("Register");
  setType("Register");
}
 Register()
Register::~Register () [virtual]
Destructor.
Definition at line 25 of file Register.cpp.
                    {
}
Member Function Documentation
getBit()
bool Register::getBit (unsigned int bit)
Definition at line 66 of file Register.cpp.
References IOdata::Byte, shell::data(), IOdata::dataU16(), IOdata::dataU32(), IOdata::dataU8(), IOdata::DWord, Object::error(), StatusCode::FAILURE, IOobject::io(), Object::name(), IOobject::read(), StatusCode::SUCCESS, IOdata::Word, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), A3PE::dataReady(), A3PE::enableADC(), A3PE::internalAXSequence(), A3PE::readPatternFifoUsb(), A3PE::readToAXRamUsb(), A3PE::readTriggerFifoUsb(), A3PE::softwareTrigger(), A3PE::writeFromAXRamUsb(), and A3PE::writeStorageFifoUsb().
                                     {
  if (read().isFailure()){
    error("Cannot read register "+name(),"Register::setBit");
    return StatusCode::FAILURE;
  }
  unsigned int data;
  if (IOdata::Byte==io()->wordSize()&&0!=io()->dataU8()&&bit<8){
    data=io()->dataU8()[0];
    return (data >>bit)& 1 ;
  }
  if (IOdata::Word==io()->wordSize()&&0!=io()->dataU16()&&bit<16){
    data=io()->dataU16()[0];
    return (data >>bit)& 1 ;
  }
  if (IOdata::DWord==io()->wordSize()&&0!=io()->dataU32()&&bit<32){
    data=io()->dataU32()[0];
    return (data >>bit)& 1 ;
  }
  if (write().isFailure()){
    error("Cannot write register "+name(),"Register::setBit");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
setBit()
StatusCode Register::setBit (unsigned int bit, bool val)
Definition at line 32 of file Register.cpp.
References IOdata::Byte, shell::data(), IOdata::dataU16(), IOdata::dataU32(), IOdata::dataU8(), IOdata::DWord, Object::error(), StatusCode::FAILURE, IOobject::io(), Object::name(), IOobject::read(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), StatusCode::SUCCESS, IOdata::Word, and IOobject::write().
Referenced by A3PE::acquisition(), BOOST_PYTHON_MODULE(), A3PE::resetAcquisitionWriteCounter(), A3PE::resetFE(), A3PE::resetFromAXRam(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), A3PE::resetUsbPhasers(), A3PE::setAXRamUsb(), A3PE::setEnableADC(), A3PE::setInternalAXSequence(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), A3PE::startSequenceAX(), and A3PE::trigger().
                                                     {
  if (read().isFailure()){
    error("Cannot read register "+name(),"Register::setBit");
    return StatusCode::FAILURE;
  }
  unsigned int data;
  if (IOdata::Byte==io()->wordSize()&&0!=io()->dataU8()&&bit<8){
    data=io()->dataU8()[0];
    if (val) data |= (1 << bit);
    else data &= ~(1 << bit);
    io()->setU8(0,data);
  }
  if (IOdata::Word==io()->wordSize()&&0!=io()->dataU16()&&bit<16){
    data=io()->dataU16()[0];
    if (val) data |= (1 << bit);
    else data &= ~(1 << bit);
    io()->setU16(0,data);
  }
  if (IOdata::DWord==io()->wordSize()&&0!=io()->dataU32()&&bit<32){
    data=io()->dataU32()[0];
    if (val) data |= (1 << bit);
    else data &= ~(1 << bit);
    io()->setU32(0,data);
  }
  if (write().isFailure()){
    error("Cannot write register "+name(),"Register::setBit");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/inc/Register.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/src/Register.cpp