EventHeader Class Reference
#include <include/EventHeader.h>
Public Member Functions
EventHeader ()
Standard constructor.
EventHeader (int, int)
virtual ~EventHeader ()
Destructor.
unsigned long evt ()
unsigned long run ()
unsigned long date ()
void setEvt (unsigned long ievt)
void setRun (unsigned long irun)
void newEvt ()
Public Attributes
ClassDef(EventHeader, 1) protected unsigned long Run
unsigned long Date
Detailed Description
Author
Frédéric Machefert
Date
2004-10-04
Definition at line 20 of file EventHeader.h.
Constructor & Destructor Documentation
EventHeader() [1/2]
EventHeader::EventHeader ()
Standard constructor.
EventHeader() [2/2]
EventHeader::EventHeader (int run, int evt)
Definition at line 26 of file EventHeader.cpp.
References Date, evt(), and run().
                                           {
  Run = run;
  Evt = evt;
  TDatime today;
  Date = today.GetDate();
}
 EventHeader()
EventHeader::~EventHeader () [virtual]
Destructor.
Definition at line 36 of file EventHeader.cpp.
                          {
}
Member Function Documentation
date()
unsigned long EventHeader::date () [inline]
Definition at line 35 of file EventHeader.h.
References Date.
                      {
    return Date;
  }
evt()
unsigned long EventHeader::evt () [inline]
Definition at line 27 of file EventHeader.h.
Referenced by EventHeader().
                     {
    return Evt;
  }
newEvt()
void EventHeader::newEvt ()
Definition at line 42 of file EventHeader.cpp.
References Date.
Referenced by setRun().
                        {
  Evt++;
  TDatime today;
  Date = today.GetDate();
}
run()
unsigned long EventHeader::run () [inline]
Definition at line 31 of file EventHeader.h.
References Run.
Referenced by EventHeader().
                     {
    return Run;
  }
setEvt()
void EventHeader::setEvt (unsigned long ievt) [inline]
Definition at line 39 of file EventHeader.h.
                                  {
    Evt = ievt;
  }
setRun()
void EventHeader::setRun (unsigned long irun) [inline]
Definition at line 43 of file EventHeader.h.
References newEvt().
                                  {
    Run = irun;
  }
Member Data Documentation
Date
unsigned long EventHeader::Date
Definition at line 61 of file EventHeader.h.
Referenced by ClassImp(), date(), EventHeader(), and newEvt().
Run
ClassDef (EventHeader,1) protected unsigned long EventHeader::Run
Definition at line 54 of file EventHeader.h.
Referenced by run().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloEvent/inc/EventHeader.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloEvent/src/EventHeader.cpp