DLL Class Reference
#include <inc/DLL.h>
Public Types
typedef void * ImageHandle
typedef void(* EntryPoint) (DLL *)
typedef Element *(* ConstructorElement) ()
typedef void(* DestructorElement) (Element *)
typedef Processus *(* ConstructorProcessus) ()
typedef void(* DestructorProcessus) (Processus *)
typedef Object *(* ConstructorObject) ()
typedef void(* DestructorObject) (Object *)
typedef std::pair< std::string, std::string > identification
typedef std::vector< identification > listOfElements
typedef std::vector< identification > listOfProcessus
typedef std::vector< identification > listOfObjects
Public Member Functions
DLL ()
Standard constructor.
virtual ~DLL ()
Destructor.
StatusCode load (std::string)
StatusCode unload ()
void setName (std::string name)
std::string name ()
listOfElements listElements ()
listOfProcessus listProcessus ()
listOfObjects listObjects ()
void addElement (std::string element, std::string description=std::string(``))
void addProcessus (std::string proc, std::string description=std::string(``))
void addObject (std::string proc, std::string description=std::string(``))
bool containsObject (std::string)
std::vector< std::string > objectList ()
StatusCode init ()
Element * createElement (std::string)
Processus * createProcessus (std::string)
Object * createObject (std::string)
StatusCode destroy (Element *)
StatusCode destroy (Processus *)
StatusCode destroy (Object *)
void print ()
Private Member Functions
void msg (std::string mymsg)
void verbose (std::string mymsg)
void debug (std::string mymsg)
void info (std::string mymsg)
void warning (std::string mymsg)
void fatal (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg, std::string name)
void fatal (std::string mymsg, std::string name)
Private Attributes
MsgSvc m_log
std::string m_name
ImageHandle m_handle
listOfElements m_listElements
listOfProcessus m_listProcessus
listOfObjects m_listObjects
std::vector< ConstructorElement > m_elementConstructors
std::vector< DestructorElement > m_elementDestructors
std::vector< ConstructorProcessus > m_processusConstructors
std::vector< DestructorProcessus > m_processusDestructors
std::vector< ConstructorObject > m_objectConstructors
std::vector< DestructorObject > m_objectDestructors
Detailed Description
Author
Date
2006-10-24
Definition at line 57 of file DLL.h.
Member Typedef Documentation
ConstructorElement
typedef Element*(* DLL::ConstructorElement) ()
Definition at line 69 of file DLL.h.
ConstructorObject
typedef Object*(* DLL::ConstructorObject) ()
Definition at line 73 of file DLL.h.
ConstructorProcessus
typedef Processus*(* DLL::ConstructorProcessus) ()
Definition at line 71 of file DLL.h.
DestructorElement
typedef void(* DLL::DestructorElement) (Element *)
Definition at line 70 of file DLL.h.
DestructorObject
typedef void(* DLL::DestructorObject) (Object *)
Definition at line 74 of file DLL.h.
DestructorProcessus
typedef void(* DLL::DestructorProcessus) (Processus *)
Definition at line 72 of file DLL.h.
EntryPoint
typedef void(* DLL::EntryPoint) (DLL *)
Definition at line 67 of file DLL.h.
identification
typedef std::pair<std::string,std::string> DLL::identification
Definition at line 76 of file DLL.h.
ImageHandle
typedef void* DLL::ImageHandle
Definition at line 64 of file DLL.h.
listOfElements
typedef std::vector<identification> DLL::listOfElements
Definition at line 77 of file DLL.h.
listOfObjects
typedef std::vector<identification> DLL::listOfObjects
Definition at line 79 of file DLL.h.
listOfProcessus
typedef std::vector<identification> DLL::listOfProcessus
Definition at line 78 of file DLL.h.
Constructor & Destructor Documentation
DLL()
DLL::DLL ()
Standard constructor.
Definition at line 20 of file DLL.cpp.
          :
m_handle (0)
{
}
 DLL()
DLL::~DLL () [virtual]
Destructor.
Definition at line 27 of file DLL.cpp.
{}
Member Function Documentation
addElement()
void DLL::addElement (std::string element, std::string description = std::string (``)) [inline]
Append an Element to the DLL
Definition at line 139 of file DLL.h.
References m_listElements.
  {
    identification id (element , description);
    m_listElements.push_back(id);
  }
addObject()
void DLL::addObject (std::string proc, std::string description = std::string (``)) [inline]
Append a Object to the DLL
Definition at line 159 of file DLL.h.
References containsObject(), createElement(), createObject(), createProcessus(), destroy(), init(), m_listObjects, objectList(), and print().
    {
    identification id (proc , description);
    m_listObjects.push_back(id);
  }
addProcessus()
void DLL::addProcessus (std::string proc, std::string description = std::string (``)) [inline]
Append a Processus to the DLL
Definition at line 149 of file DLL.h.
References m_listProcessus.
    {
    identification id (proc , description);
    m_listProcessus.push_back(id);
  }
containsObject()
bool DLL::containsObject (std::string name)
find if Object belong to the library
Definition at line 32 of file DLL.cpp.
References m_listElements, and m_listProcessus.
Referenced by addObject().
                                          {
  std::vector<identification>::const_iterator iter;
  for (iter=m_listElements.begin() ;
        iter!=m_listElements.end() ;
        ++iter) {
    if (0==name.compare(iter->first)){
      return true;
    }
  }
  for (iter=m_listProcessus.begin() ;
        iter!=m_listProcessus.end() ;
        ++iter) {
    if (0==name.compare(iter->first)){
      return true;
    }
  }
  return false;
}
createElement()
Element * DLL::createElement (std::string name)
Create an Element from its type
Definition at line 278 of file DLL.cpp.
References m_elementConstructors, m_listElements, name(), and Object::setDllName().
Referenced by addObject(), and DLLMgr::createElement().
                                             {
  std::vector<identification>::const_iterator iter;
  std::vector<ConstructorElement>::const_iterator constructor=
      m_elementConstructors.begin();
  for (iter=m_listElements.begin() ;
        iter!=m_listElements.end() ;
        ++iter) {
    if (0==name.compare(iter->first)){
      Element *element = (*constructor)() ;
      element->setDllName(this->name());
      return (element);
    }
    constructor++;
  }
  return NULL;
}
createObject()
Object* DLL::createObject (std::string)
Create a Object from its type
Referenced by addObject().
createProcessus()
Processus * DLL::createProcessus (std::string name)
Create a Processus from its type
Definition at line 297 of file DLL.cpp.
References m_listProcessus, m_processusConstructors, name(), and Object::setDllName().
Referenced by addObject(), DLLMgr::createProcessus(), and init().
                                                 {
  std::vector<identification>::const_iterator iter;
  std::vector<ConstructorProcessus>::const_iterator constructor=
      m_processusConstructors.begin();
  for (iter=m_listProcessus.begin() ;
        iter!=m_listProcessus.end() ;
        ++iter) {
    if (0==name.compare(iter->first)){
      Processus *processus=(*constructor)();
      processus->setDllName(this->name());
      return (processus);
    }
    constructor++;
  }
  return NULL;
}
debug() [1/2]
void DLL::debug (std::string mymsg) [inline], [private]
Definition at line 234 of file DLL.h.
References MsgSvc::DEBUG, and MsgSvc::msgSvc().
Referenced by load().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void DLL::debug (std::string mymsg, std::string name) [inline], [private]
Definition at line 241 of file DLL.h.
References MsgSvc::DEBUG, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
destroy() [1/3]
StatusCode DLL::destroy (Element * ptr)
Destroy an Element from its pointer
Definition at line 316 of file DLL.cpp.
References StatusCode::FAILURE, m_elementDestructors, m_listElements, StatusCode::SUCCESS, and Object::type().
Referenced by addObject(), and DLLMgr::destroy().
                                       {
  std::vector<identification>::const_iterator iter;
  std::vector<DestructorElement>::const_iterator destructor=m_elementDestructors.begin(
      );
  for (iter=m_listElements.begin() ;
        iter!=m_listElements.end() ;
        ++iter) {
    if (0==(ptr->type()).compare(iter->first)){
      ((*destructor)(ptr));
      return StatusCode::SUCCESS;
    }
    destructor++;
  }
  return StatusCode::FAILURE;
}
destroy() [2/3]
StatusCode DLL::destroy (Processus * ptr)
Destroy a Processus from its pointer
Definition at line 334 of file DLL.cpp.
References StatusCode::FAILURE, m_listProcessus, m_processusDestructors, StatusCode::SUCCESS, and Object::type().
                                         {
  std::vector<identification>::const_iterator iter;
  std::vector<DestructorProcessus>::const_iterator destructor=
      m_processusDestructors.begin();
  for (iter=m_listProcessus.begin() ;
        iter!=m_listProcessus.end() ;
        ++iter) {
    if (0==(ptr->type()).compare(iter->first)){
      ((*destructor)(ptr));
      return StatusCode::SUCCESS;
    }
    destructor++;
  }
  return StatusCode::FAILURE;
}
destroy() [3/3]
StatusCode DLL::destroy (Object *)
Destroy a Object from its pointer
fatal() [1/2]
void DLL::fatal (std::string mymsg) [inline], [private]
Definition at line 237 of file DLL.h.
References MsgSvc::FATAL, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void DLL::fatal (std::string mymsg, std::string name) [inline], [private]
Definition at line 244 of file DLL.h.
References MsgSvc::FATAL, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
info() [1/2]
void DLL::info (std::string mymsg) [inline], [private]
Definition at line 235 of file DLL.h.
References MsgSvc::INFO, and MsgSvc::msgSvc().
Referenced by load(), and print().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void DLL::info (std::string mymsg, std::string name) [inline], [private]
Definition at line 242 of file DLL.h.
References MsgSvc::INFO, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
init()
StatusCode DLL::init ()
initialization of the dll
Definition at line 172 of file DLL.cpp.
References ProcDataBase::add(), application(), createProcessus(), StatusCode::FAILURE, m_elementConstructors, m_elementDestructors, m_handle, m_listElements, m_listProcessus, m_processusConstructors, m_processusDestructors, Application::procDb(), StatusCode::SUCCESS, and warning().
Referenced by addObject(), and load().
                        {
  bool initOk = true;
  std::vector<identification>::const_iterator iter;
  for (iter=m_listElements.begin() ;
        iter!=m_listElements.end() ;
        ++iter) {
    ConstructorElement constructor;
    DestructorElement destructor;
#ifdef WIN32
    constructor = (ConstructorElement)GetProcAddress(m_handle,
                                                     (iter->first+
                                                      std::string("_create")).c_str());
    destructor = (DestructorElement)GetProcAddress(m_handle,
                                                   (iter->first+
                                                    std::string("_destroy")).c_str());
#else
    constructor = (ConstructorElement)dlsym(m_handle,
                                           (iter->first+
                                           std::string("_create")).c_str());
    destructor = (DestructorElement)dlsym(m_handle,
                                         (iter->first+
                                         std::string("_destroy")).c_str());
#endif
    if (0 == constructor) {
      warning("Could not find constructor of "+iter->first+std::string(" (_create)"),"DLL::init");
      initOk=false;
    }
    if (0 == destructor) {
      warning("Could not find destructor of "+iter->first+std::string(" (_destroy)"),"DLL::init");
      initOk=false;
    }
    if (initOk) {
      m_elementConstructors.push_back(constructor);
      m_elementDestructors.push_back(destructor);
    }
  }
  if (!initOk){
    return StatusCode::FAILURE;
  }
  initOk=true;
  for (iter=m_listProcessus.begin() ;
        iter!=m_listProcessus.end() ;
        ++iter) {
    ConstructorProcessus constructor;
    DestructorProcessus destructor;
#ifdef WIN32
    constructor = (ConstructorProcessus)GetProcAddress(
      m_handle,
                                                       (iter->first+
                                                        std::string("_create")).c_str());
    destructor = (DestructorProcessus)GetProcAddress(m_handle,
                                                     (iter->first+
                                                      std::string("_destroy")).c_str());
#else
    constructor = (ConstructorProcessus)dlsym(m_handle,
                                             (iter->first+
                                             std::string("_create")).c_str());
    destructor = (DestructorProcessus)dlsym(m_handle,
                                           (iter->first+
                                           std::string("_destroy")).c_str());
#endif
    if (0 == constructor) {
      warning("Could not find constructor of "+iter->first,"DLL::init");
      initOk=false;
    }
    if (0 == destructor) {
      warning("Could not find destructor of "+iter->first,"DLL::init");
      initOk=false;
    }
    if (initOk){
      m_processusConstructors.push_back(constructor);
      m_processusDestructors.push_back(destructor);
      // create the corresponding processus in the database
      Processus* proc = createProcessus (iter->first);
      if (0==proc){
        initOk=false;
      }
      else {
        application()->procDb()->add(proc);
      }
    }
  }
  if (!initOk){
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
listElements()
listOfElements DLL::listElements () [inline]
Get accessor to member m_listElement
Returns
the current value of m_listElement
Definition at line 116 of file DLL.h.
References m_listElements.
                                 {
    return m_listElements;
  }
listObjects()
listOfObjects DLL::listObjects () [inline]
Get accessor to member m_listObjects
Returns
the current value of m_listObjects
Definition at line 132 of file DLL.h.
References m_listObjects.
                               {
    return m_listObjects;
  }
listProcessus()
listOfProcessus DLL::listProcessus () [inline]
Get accessor to member m_listProcessus
Returns
the current value of m_listProcessus
Definition at line 124 of file DLL.h.
References m_listProcessus.
                                   {
    return m_listProcessus;
  }
load()
StatusCode DLL::load (std::string library)
Load the library according to its name
Definition at line 118 of file DLL.cpp.
References debug(), StatusCode::FAILURE, info(), init(), m_handle, name(), print(), setName(), StatusCode::SUCCESS, and warning().
Referenced by DLLMgr::load().
                                         {
  typedef Element* (*func) ();
#ifdef WIN32
  m_handle = LoadLibrary ((library+std::string(".dll")).c_str());
#else
  m_handle = dlopen((std::string("lib")+library+std::string(".so")).c_str() , RTLD_LAZY);
#endif
  if (NULL != m_handle) {
    // get entry point
    setName(library);
    DLL::EntryPoint entryPoint;
#ifdef WIN32
    entryPoint = (DLL::EntryPoint)GetProcAddress(m_handle,
                                                 (library+std::string("_dll")).c_str());
#else
    entryPoint = (DLL::EntryPoint)dlsym(m_handle,
                                       (library+std::string("_dll")).c_str());
#endif
    if (!entryPoint) {
      warning("No entry point found in library "+library+".","DLL::load");
      // could not find entry point
#ifdef WIN32
      FreeLibrary(m_handle);
#else
      dlclose(m_handle);
#endif
      warning("Could not load dll entry point "+name(),"DLL::load");
      return StatusCode::FAILURE;
    }
    else {
      debug("Entry point found in library "+library+".","DLL::load");
      // entry point found : load list of objects
      entryPoint (this);
      // check if we can find constructors/destructors
      if (init().isFailure()) {
    info("Could not find Constructors/Destructors in library "+
         library+".","DLL::load");
        return StatusCode::FAILURE;
      }
      print();
      return StatusCode::SUCCESS;
    }
  }
  else {
    warning("No handle on library "+library+".","DLL::load");
  }
  return StatusCode::FAILURE;
}
msg() [1/2]
void DLL::msg (std::string mymsg) [inline], [private]
Definition at line 232 of file DLL.h.
References MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void DLL::msg (std::string mymsg, std::string name) [inline], [private]
Definition at line 239 of file DLL.h.
References MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
name()
std::string DLL::name () [inline]
Get accessor to member m_name
Returns
the current value of m_name
Definition at line 108 of file DLL.h.
References m_name.
Referenced by createElement(), createProcessus(), load(), print(), and setName().
                    {
    return m_name;
  }
objectList()
std::vector< std::string > DLL::objectList ()
list of Objects
Definition at line 55 of file DLL.cpp.
References m_listElements, and m_listProcessus.
Referenced by addObject(), and DLLMgr::load().
                                       {
  std::vector<std::string> list;
  std::vector<identification>::const_iterator iter;
  for (iter=m_listElements.begin() ;
        iter!=m_listElements.end() ;
        ++iter) {
    list.push_back (iter->first);
  }
  for (iter=m_listProcessus.begin() ;
        iter!=m_listProcessus.end() ;
        ++iter) {
    list.push_back (iter->first);
  }
  return list;
}
print()
void DLL::print ()
print DLL information
Definition at line 74 of file DLL.cpp.
References application(), info(), itos(), m_listElements, m_listProcessus, name(), Application::procDb(), ProcDataBase::processus(), and Object::type().
Referenced by addObject(), export_base(), and load().
                  {
  char line [100];
  info("Symbols found in dll "+name()+": "+
         itos(m_listElements.size())+" Element(s) - "+
         itos(m_listProcessus.size())+" Processus.");
  std::vector<identification>::const_iterator iter;
  if (m_listElements.size()>0) {
    sprintf(line,"
      ============================================================================================");
    info(line,"DLL::print");
    sprintf(line ,"Element Description");
    info(line,"DLL::print");
    for (iter=m_listElements.begin() ;
      iter!=m_listElements.end() ;
      ++iter) {
      sprintf(line," %25s %65s ",
          iter->first.c_str(),
          iter->second.c_str());
      info(std::string(line),"DLL::print");
    }
  }
  if (m_listProcessus.size() > 0) {
    sprintf(line,"
      ============================================================================================");
    info(line,"DLL::print");
    sprintf (line ,"Processus Target Type");
    info(line,"DLL::print");
    for (iter=m_listProcessus.begin() ;
      iter!=m_listProcessus.end() ;
      ++iter) {
      sprintf(line," %25s %25s ",
          iter->first.c_str(),
          application()->procDb()->processus(iter->first)->
      type().c_str()
          // application()->procDb()->processus(iter->first)->title().c_str()
          );
      info(std::string(line),"DLL::print");
    }
  }
  sprintf(line,"
      ============================================================================================");
  info(line,"DLL::print");
}
setName()
void DLL::setName (std::string name) [inline]
Set accessor to member m_name
Parameters
name the new value for m_name
Definition at line 100 of file DLL.h.
References m_name, and name().
Referenced by load().
                                {
    m_name = name;
  }
unload()
StatusCode DLL::unload ()
Unload the library
Definition at line 263 of file DLL.cpp.
References StatusCode::FAILURE, m_handle, and StatusCode::SUCCESS.
                         {
  if (NULL != m_handle){
#ifdef WIN32
    FreeLibrary(m_handle);
#else
    dlclose(m_handle);
#endif
    return StatusCode::SUCCESS;
  }
  return StatusCode::FAILURE;
}
verbose() [1/2]
void DLL::verbose (std::string mymsg) [inline], [private]
Definition at line 233 of file DLL.h.
References MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void DLL::verbose (std::string mymsg, std::string name) [inline], [private]
Definition at line 240 of file DLL.h.
References MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void DLL::warning (std::string mymsg) [inline], [private]
Definition at line 236 of file DLL.h.
References MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by init(), and load().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void DLL::warning (std::string mymsg, std::string name) [inline], [private]
Definition at line 243 of file DLL.h.
References MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
Member Data Documentation
m_elementConstructors
std::vector<ConstructorElement> DLL::m_elementConstructors [private]
Definition at line 225 of file DLL.h.
Referenced by createElement(), and init().
m_elementDestructors
std::vector<DestructorElement> DLL::m_elementDestructors [private]
Definition at line 226 of file DLL.h.
Referenced by destroy(), and init().
m_handle
ImageHandle DLL::m_handle [private]
Definition at line 221 of file DLL.h.
Referenced by init(), load(), and unload().
m_listElements
listOfElements DLL::m_listElements [private]
Definition at line 222 of file DLL.h.
Referenced by addElement(), containsObject(), createElement(), destroy(), init(), listElements(), objectList(), and print().
m_listObjects
listOfObjects DLL::m_listObjects [private]
Definition at line 224 of file DLL.h.
Referenced by addObject(), and listObjects().
m_listProcessus
listOfProcessus DLL::m_listProcessus [private]
Definition at line 223 of file DLL.h.
Referenced by addProcessus(), containsObject(), createProcessus(), destroy(), init(), listProcessus(), objectList(), and print().
m_log
MsgSvc DLL::m_log [private]
Definition at line 219 of file DLL.h.
m_name
std::string DLL::m_name [private]
Definition at line 220 of file DLL.h.
Referenced by name(), and setName().
m_objectConstructors
std::vector<ConstructorObject> DLL::m_objectConstructors [private]
Definition at line 229 of file DLL.h.
m_objectDestructors
std::vector<DestructorObject> DLL::m_objectDestructors [private]
Definition at line 230 of file DLL.h.
m_processusConstructors
std::vector<ConstructorProcessus> DLL::m_processusConstructors [private]
Definition at line 227 of file DLL.h.
Referenced by createProcessus(), and init().
m_processusDestructors
std::vector<DestructorProcessus> DLL::m_processusDestructors [private]
Definition at line 228 of file DLL.h.
Referenced by destroy(), and init().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/DLL.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/DLL.cpp