UsbFTMLInterface Class Reference
#include <include/UsbFTMLInterface.h>
Public Types
enum WordSize { WS_Byte =1,
WS_Word,
WS_DWord
 }
enum IOMode {
USB_IORead,
USB_IOWrite,
USB_IOReadWrite,
USB_WriteReadBurst,
USB_IOExtebdedRead
 }
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
UsbFTMLInterface ()
virtual ~UsbFTMLInterface ()
virtual void help ()
virtual StatusCode init ()
void close ()
virtual void reset ()
virtual void update ()
StatusCode read (IOdata *)
StatusCode write (IOdata *)
StatusCode read (unsigned long int, unsigned long int, boost::python::list &)
StatusCode write (unsigned long int, boost::python::list)
StatusCode usbRead (unsigned long int, unsigned long int, std::vector< U32 > &)
StatusCode usbWrite (unsigned long int, std::vector< U32 >)
StatusCode usbReadU8 (unsigned long int, unsigned long int, unsigned char *)
StatusCode usbReadU16 (unsigned long int, unsigned long int, unsigned short *)
StatusCode usbReadU32 (unsigned long int, unsigned long int, unsigned long *)
StatusCode usbWriteU8 (unsigned long int, unsigned long int, unsigned char *)
StatusCode usbWriteU16 (unsigned long int, unsigned long int, unsigned short *)
StatusCode usbWriteU32 (unsigned long int, unsigned long int, unsigned long *)
StatusCode usbWriteRead (unsigned long int, std::vector< U8 >, std::vector< U8 > &)
void setUsbId (int usbId)
int usbId ()
void setSerialNum (std::string serialNum)
std::string serialNum ()
void setDeviceDesc (std::string deviceDesc)
std::string deviceDesc ()
void setLatencyTimer (unsigned char latencyTimer)
unsigned char latencyTimer ()
void setTimeOut (int txTimeOut, int rxTimeOut)
int txTimeOut ()
int rxTimeOut ()
void setBuffer (int txBuffer, int rxBuffer)
int txBuffer ()
int rxBuffer ()
void setNFrames (long int nFrames)
long int nFrames ()
void setWordCount (unsigned long wordCount)
unsigned long wordCount ()
void setWordSize (unsigned long wordSize)
unsigned long wordSize ()
void setFakeErr (unsigned int fakeErr)
unsigned int fakeErr ()
void setInterrupts (bool interrupts)
bool interrupts ()
void setShowEpromState (bool showEpromState)
bool showEpromState ()
bool wrBlockMax ()
void setWrBlockMax (bool wrBlockMax)
bool rdBlockMax ()
void setRdBlockMax (bool rdBlockMax)
void setPrintout (bool printout)
bool printout ()
void resetMode ()
void purgeBuffers ()
void setSynchronousMode ()
void recursiveInitElement ()
void recursiveInitCommunications ()
StatusCode setConnection (Hierarchy *)
Hierarchy * connection ()
void clear ()
void setParent (Hierarchy *parent)
Hierarchy * parent ()
Hierarchy * parent (std::string)
Hierarchy * origin ()
virtual void addChild (Hierarchy *element)
std::vector< Hierarchy * > children ()
Hierarchy * child (std::string)
Hierarchy * childTyped (std::string)
unsigned long numberOfChildren ()
bool hasChildren ()
void delChild (Hierarchy *)
void delChild (std::string)
std::string path (std::string=std::string(``))
std::string pathTyped (std::string=std::string(``))
void tree (std::string indent=std::string(``))
void tree ()
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
Hierarchy * m_connection
std::string m_attribString [10]
Private Attributes
int m_usbId
std::string m_serialNum
std::string m_deviceDesc
unsigned char m_latencyTimer
int m_txTimeOut
int m_rxTimeOut
int m_txBuffer
int m_rxBuffer
long int m_nFrames
unsigned long m_wordCount
unsigned long m_wordSize
unsigned int m_fakeErr
bool m_interrupts
bool m_showEpromState
bool m_printout
int m_rdBlockMax
int m_wrBlockMax
Detailed Description
Class to describe general electronics object
Author
Frederic Machefert
Date
2004-01-18
Definition at line 41 of file UsbFTMLInterface.h.
Member Typedef Documentation
U16
typedef unsigned short UsbFTMLInterface::U16
Definition at line 44 of file UsbFTMLInterface.h.
U32
typedef unsigned long UsbFTMLInterface::U32
Definition at line 43 of file UsbFTMLInterface.h.
U8
typedef unsigned char UsbFTMLInterface::U8
Definition at line 45 of file UsbFTMLInterface.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
IOMode
enum UsbFTMLInterface::IOMode
Enumerator
USB_IORead
USB_IOWrite
USB_IOReadWrite
USB_WriteReadBurst
USB_IOExtebdedRead
Definition at line 54 of file UsbFTMLInterface.h.
    {
      USB_IORead,
      USB_IOWrite,
      USB_IOReadWrite,
      USB_WriteReadBurst,
      USB_IOExtebdedRead
    };
WordSize
enum UsbFTMLInterface::WordSize
Enumerator
WS_Byte
WS_Word
WS_DWord
Definition at line 47 of file UsbFTMLInterface.h.
    {
      WS_Byte=1,
      WS_Word,
      WS_DWord
    };
Constructor & Destructor Documentation
UsbFTMLInterface()
UsbFTMLInterface::UsbFTMLInterface ()
Definition at line 19 of file UsbFTMLInterface.cpp.
References Object::info(), Object::setName(), and Object::setType().
                                     :
  m_usbId(-1),
  m_serialNum(std::string("None")),
  m_deviceDesc(std::string("None")),
  m_latencyTimer(2),
  m_txTimeOut(1000),
  m_rxTimeOut(1000),
  m_txBuffer(4096),
  m_rxBuffer(32768),
  m_nFrames (0),
  m_wordSize(WS_DWord),
  m_fakeErr (FK_LETSBETRUE),
  m_rdBlockMax(65536),
  m_wrBlockMax(65536),
  m_interrupts(true),
  m_showEpromState(false),
  m_printout(false)
{
  setName("usb");
  setType("UsbFTMLInterface");
  info("Todo : time efficiency by creating the buffer once for all ?");
  // add(Attrib::INTERFACE);
}
 UsbFTMLInterface()
virtual UsbFTMLInterface::~UsbFTMLInterface () [inline], [virtual]
Definition at line 64 of file UsbFTMLInterface.h.
References close().
                              {
    close();
  } //< Destructor
Member Function Documentation
add()
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), TestSPI::setAddress(), TestI2C::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
addChild()
void Hierarchy::addChild (Hierarchy * element) [virtual], [inherited]
Definition at line 83 of file Hierarchy.cpp.
References Object::debug(), Hierarchy::m_children, Object::name(), and Hierarchy::setParent().
Referenced by A3PE::A3PE(), SpecsMezzanine::addBus(), SpecsSlave::addI2c(), Application::create(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Hierarchy::origin(), Phaser::Phaser(), Proto40MHz_v1::Proto40MHz_v1(), SeqPGA::SeqPGA(), SpecsMezzanine::SpecsMezzanine(), UsbI2cBus::UsbI2cBus(), and UsbSpiBus::UsbSpiBus().
                                          {
  element->setParent(this);
  m_children.push_back(element);
  debug(element->name()+" added to the child tree.","Hierarchy::addChild");
}
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
child()
Hierarchy * Hierarchy::child (std::string path) [inherited]
Definition at line 133 of file Hierarchy.cpp.
References Hierarchy::child(), Hierarchy::children(), Object::name(), Hierarchy::origin(), Hierarchy::parent(), Hierarchy::path(), and Object::warning().
Referenced by Application::cd(), Hierarchy::child(), Hierarchy::children(), and export_obj().
                                         {
  std::string newpath = path;
  std::string up("..");
  std::string separator(1,'/');
  Hierarchy * newcurrent = 0;
  // info("path="+path,"Hierarchy::child");
  if (path.compare("")==0 || path.compare("/")==0) {
    // debug("return origin","Hierarchy::child");
    return origin();
  }
  if (path.compare(name())==0){
    // debug("return itself","Hierarchy::child");
    return this;
  }
  if (path.compare("..")==0){
    if (0!=this->parent()) return this->parent();
    else return this;
  }
  if (path.compare("../")==0){
    if (0!=this->parent()) return this->parent();
    else return this;
  }
  int npos=path.find(separator,0);
  // info("find separator in "+itos(npos)+" of "+path,"Hierarchy::child");
  // remove last separator
  if (npos == (int)(path.size()-1)) {
    newpath = std::string(path,0,npos);
    path = newpath;
  }
  if (npos==0){
    // debug("Going back to origin and calling child","Hierarchy::child");
    newpath=std::string(path,1,path.size()-1);
    return origin()->child(newpath);
  }
  else{
    if (npos== (int)(std::string::npos)){
      // debug("Getting chid "+path+" of "+this->name(),"Hierarchy::child");
      std::vector <Hierarchy*> list = children();
      std::vector<Hierarchy*>::iterator iter;
      for (iter=list.begin();iter!=list.end();iter++){
        if ((*iter)->name().compare(path)==0){
          return *iter;
        }
      }
      warning(this->name()+std::string(" has no child '")+path+"'","Hierarchy::child");
      return this;
    }
    else
    {
      int ipos=path.find(separator,0);
      // info("default behaviour "+path+" with separator in "+itos(ipos),"Hierarchy::child");
      std::string newcurrentname=std::string(path,0,ipos);
      newpath=std::string(path,ipos+1,path.size()-1);
      // info("looking now for "+newpath+" from "+newcurrentname,"Hierarchy::child");
      if (0==newcurrentname.compare(origin()->name())){
        // info("current is computer. Looking for children"+newcurrentname,"Hierarchy::child");
        return origin()->child(newpath);
      }
      newcurrent = (Hierarchy*)0;
      std::vector <Hierarchy*> list = children();
      std::vector<Hierarchy*>::iterator iter;
      for (iter=list.begin();iter!=list.end();iter++){
        if ((*iter)->name().compare(newcurrentname)==0){
          newcurrent = (*iter);
        }
      }
      if ((Hierarchy*)0==newcurrent){
        if (newcurrentname.compare("..")==0 && 0!=parent()){
          newcurrent=this->parent();
          // debug("newcurrent was .. -> parent="+parent()->name());
        }
        else
        {
          warning(this->name()+" has no child '"+newcurrentname+"'",
              "Hierarchy::child");
          return this;
        }
      }
      // debug("recurrence call for "+newpath+" on "+newcurrent->name(),"Hierarchy::child");
      return newcurrent -> child (newpath);
    }
  }
}
children()
std::vector<Hierarchy*> Hierarchy::children () [inline], [inherited]
Definition at line 33 of file Hierarchy.h.
References Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::delChild(), Hierarchy::hasChildren(), Hierarchy::m_children, Hierarchy::numberOfChildren(), Hierarchy::path(), Hierarchy::pathTyped(), and Hierarchy::tree().
Referenced by Hierarchy::child(), Hierarchy::childTyped(), export_obj(), SpecsSlave::recursiveInitCommunications(), Element::recursiveInitCommunications(), Element::recursiveInitElement(), Application::setConfig(), and Hierarchy::tree().
{ return m_children; } //< get list of child(ren)
childTyped()
Hierarchy * Hierarchy::childTyped (std::string path) [inherited]
Definition at line 239 of file Hierarchy.cpp.
References Hierarchy::children(), Hierarchy::m_origin, Object::name(), Hierarchy::parent(), Hierarchy::path(), and Object::warning().
Referenced by Hierarchy::children(), and export_obj().
                                              {
  std::string newpath = path;
  std::string up("..");
  std::string separator(1,'/');
  std::string typeopen(1,'[');
  std::string typeclose(1,']');
  Hierarchy * newcurrent = 0;
  unsigned int npos=path.find(separator,0);
  unsigned int opos=path.find(typeopen,0);
  if (npos==std::string::npos || npos == path.size()-1){
    if (path.compare("..")==0) {
      return parent();
    }
    if (npos == path.size()-1) {
      newpath = std::string(path,0,opos);
      path = newpath;
    }
    std::vector < Hierarchy* > list = children();
    std::vector < Hierarchy* >::iterator iter;
    for (iter=list.begin();iter!=list.end();iter++){
      std::string notypepath = std::string(path,0,opos);
      if ((*iter)->name().compare(notypepath)==0){
        return *iter;
      }
    }
    warning(this->name()+std::string(" has no child ") +path,"Hierarchy::child");
    return 0;
  }
  else {
    if (std::string(path,0,3).compare(std::string("../"))==0) {
      newpath=std::string(path,3,path.size()-3);
      newcurrent = parent();
    }
    if (std::string(path,0,1).compare(std::string("/"))==0) {
      newpath=std::string(path,1,path.size()-1);
      newcurrent = (Hierarchy*) m_origin;
    }
    if ((std::string(path,0,3).compare(std::string("../")) !=0) &&
        std::string(path,0,1).compare(std::string("/"))!=0) {
      opos = path.find(typeopen,0);
      int cpos = path.find(typeclose,0);
      std::string name = std::string (path,0,opos);
      newcurrent = childTyped(name);
      if (newcurrent ==0){
        warning(path+": no child found with such a name","Hierarchy::child");
      }
      newpath = std::string (path,cpos+2,path.size()-cpos-1);
    }
    return newcurrent -> childTyped (newpath);
  }
}
clear()
void Hierarchy::clear () [inherited]
Definition at line 35 of file Hierarchy.cpp.
References Hierarchy::delChild(), Object::info(), Hierarchy::m_children, and Object::name().
Referenced by export_obj().
                     {
  std::vector<Hierarchy*> listlocale;
  std::vector<Hierarchy*>::iterator iter;
  info("loop on "+name()+" children.","Hierarchy::clear");
  for (iter=m_children.begin();iter!=m_children.end();iter++){
      info("processing "+(*iter)->name()+".","Hierarchy::clear");
/*
      (*iter)->clear();
// this->delChild((*iter));
      info("obj "+(*iter)->name()+" being cleared.","Hierarchy::clear");
      delete (*iter);
      info("Object deleted.","Hierarchy::clear");
      m_children.erase(iter);
      info("Object removed from the tree.","Hierarchy::clear");
*/
    (*iter)->clear();
    info("Adding object "+(*iter)->name()+" from the Hierarchy to the list of deleted objects.","
      Hierarchy::clear");
    listlocale.push_back((*iter));
  }
  for (iter=listlocale.begin();iter!=listlocale.end();iter++){
    info("Removing object "+(*iter)->name()+".","Hierarchy::clear");
    this->delChild(*iter);
// m_children.erase(iter);
    delete (*iter);
  }
  info("Getting out of "+name());
}
close()
void UsbFTMLInterface::close ()
Close the usb device
Definition at line 727 of file UsbFTMLInterface.cpp.
References CloseUsbDevice(), Object::info(), itos(), m_usbId, and Object::name().
Referenced by BOOST_PYTHON_MODULE(), help(), init(), reset(), and ~UsbFTMLInterface().
                               {
  if (m_usbId>0)
  {
    info("Close USB device "+name()+" [id="+itos(m_usbId)+"]","UsbFTMLInterface::close")
      ;
    CloseUsbDevice(m_usbId);
  }
  m_usbId=-1;
}
connection()
Hierarchy * Element::connection () [inherited]
Get IO interface
Definition at line 84 of file Element.cpp.
References Element::m_connection, Object::name(), and Object::warning().
Referenced by UsbSpiBus::clockDivider(), export_obj(), UsbI2cBus::read(), IOobject::read(), UsbSpiBus::read(), UsbSpiBus::setClockDivider(), Element::setConnection(), UsbI2cBus::write(), IOobject::write(), and UsbSpiBus::write().
                              {
  if (0==m_connection){
    warning("no connection defined for "+name()+".","Element::connection");
    return (Hierarchy*)0;
  }
  return m_connection;
}
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), A3PE::internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), FEB_v1::readFifoSpyFE(), CU_v1::reset(), FEB_v1::reset(), Proto40MHz_v1::reset(), SpecsMaster::reset(), SpecsSlave::reset(), FEB_v1::resetFifoSpyFE(), FEB_v1::resetUsb(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), FEB_v1::testDuration(), SeqPGA::testSequence(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
delChild() [1/2]
void Hierarchy::delChild (Hierarchy * element) [inherited]
Definition at line 92 of file Hierarchy.cpp.
References Object::debug(), and Hierarchy::m_children.
Referenced by Hierarchy::children(), Hierarchy::clear(), export_obj(), and Hierarchy::~Hierarchy().
                                          {
  bool flag=false;
  std::vector<Hierarchy*>::iterator iter,remove;
  for (iter=m_children.begin();(iter!=m_children.end());iter++){
    if (*iter==element){
      remove=iter;
      flag=true;
    }
  }
  if (flag){
    debug("removing "+(*remove)->name()+" from the tree.","Hierarchy::delChild");
    m_children.erase(remove);
  }
}
delChild() [2/2]
void Hierarchy::delChild (std::string n) [inherited]
Definition at line 110 of file Hierarchy.cpp.
References Object::debug(), and Hierarchy::m_children.
                                   {
  bool flag=false;
  std::vector<Hierarchy*>::iterator iter,remove;
  for (iter=m_children.begin();iter!=m_children.end();iter++){
    if ((*iter)->name()==n){ remove=iter; flag=true;}
  }
  if (flag){
    debug("removing "+(*remove)->name()+" from the tree.","Hierarchy::delChild");
    m_children.erase(remove);
  }
}
deviceDesc()
std::string UsbFTMLInterface::deviceDesc () [inline]
Get accessor to member m_deviceDesc
Returns
the current value of m_deviceDesc
Definition at line 273 of file UsbFTMLInterface.h.
References m_deviceDesc.
Referenced by BOOST_PYTHON_MODULE(), and setDeviceDesc().
                          {
    return m_deviceDesc;
  }
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTInterface::read(), read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), usbRead(), UsbFTInterface::usbRead(), usbReadU16(), UsbFTInterface::usbReadU16(), usbReadU32(), UsbFTInterface::usbReadU32(), usbReadU8(), UsbFTInterface::usbReadU8(), usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), usbWriteRead(), usbWriteU16(), UsbFTInterface::usbWriteU16(), usbWriteU32(), UsbFTInterface::usbWriteU32(), usbWriteU8(), UsbFTInterface::usbWriteU8(), write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
fakeErr()
unsigned int UsbFTMLInterface::fakeErr () [inline]
Get accessor to member m_fakeErr
Returns
the current value of m_fakeErr
Definition at line 410 of file UsbFTMLInterface.h.
References m_fakeErr.
Referenced by setFakeErr().
                          {
    return m_fakeErr;
  }
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
hasChildren()
bool Hierarchy::hasChildren () [inherited]
Definition at line 303 of file Hierarchy.cpp.
References Hierarchy::m_children.
Referenced by Hierarchy::children(), and export_obj().
                              {
  return (m_children.size()>0);
}
help()
virtual void UsbFTMLInterface::help () [inline], [virtual]
printout help for the element
Implements Interface.
Definition at line 71 of file UsbFTMLInterface.h.
References close(), Object::info(), init(), and Object::name().
{ info("UsbFTMLInterface "+name()+". No help.","UsbFTMLInterface::help"); };
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), ICECALv3::bxidResynchStatus(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTInterface::close(), close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), MSOxxxx::id(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), EmulateFE::initialize(), ADCMeasurement::initialize(), CurrentMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbMLI2cBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), FePGA::reset(), SeqPGA::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), reset(), UsbFTInterface::reset(), A3PE::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), SeqPGA::resetUsb(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface(), ICECALv3::version(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
init()
StatusCode UsbFTMLInterface::init () [virtual]
init the component
Returns
void
Implements Interface.
Definition at line 47 of file UsbFTMLInterface.cpp.
References close(), Object::error(), Object::fatal(), FT_OK, GetDeviceDesc(), GetDeviceSerNum(), Object::info(), itos(), m_deviceDesc, m_interrupts, m_latencyTimer, m_rxBuffer, m_rxTimeOut, m_serialNum, m_txBuffer, m_txTimeOut, m_usbId, Object::name(), OpenUsbDevice(), StatusCode::SUCCESS, USB_FindDevices(), USB_GetLastError(), USB_GetLatencyTimer(), USB_Init(), USB_Perror(), USB_PurgeBuffers(), USB_ResetDevice(), USB_ResetMode(), USB_SetLatencyTimer(), USB_SetSynchronousMode(), USB_SetTimeouts(), USB_SetXferSize(), UsbSetIntCheckingState(), and wait().
Referenced by BOOST_PYTHON_MODULE(), help(), and reset().
                                    {
  unsigned char msecs=0;
  char desc[256];
  char serial[64];
  strcpy(desc , m_deviceDesc.c_str());
  strcpy(serial, m_serialNum.c_str());
  info("Start USB device initialisation.","UsbFTMLInterface::init");
  if (m_usbId>0)
  {
    error("Usb device already open.","UsbFTMLInterface::init");
    close();
  }
  if (!USB_FindDevices(desc))
  {
    USB_Perror(USB_GetLastError());
    error("Cannot find Usb Device "+name()+" with device description "+
          m_deviceDesc,"UsbFTMLInterface::init");
  }
  else
    {
    info("Device with device description "+m_deviceDesc+" found.","UsbFTMLInterface::init")
      ;
    info("Try to open device with serial number "+m_serialNum+".","UsbFTMLInterface::init");
    m_usbId=OpenUsbDevice(serial);
    if (m_usbId<0)
    {
      error("Could not find device with serial number "+m_serialNum,"UsbFTMLInterface::init
      ");
      if (GetDeviceSerNum(serial,0)!=FT_OK)
      {
        error("Serial number do not match first device found.","UsbFTMLInterface::init");
      }
      else
      {
        info("Extracted serial number "+std::string(serial)+".","UsbFTMLInterface::init");
        if (GetDeviceDesc(desc,0)!=FT_OK)
        {
          USB_Perror(USB_GetLastError());
          fatal("Device description do not match first device either. Abort",
                "UsbFTMLInterface::init");
        }
        else
        {
          info("Device found. Extracted description "+std::string(desc)+".",
               "UsbFTMLInterface::init");
          m_usbId=OpenUsbDevice(serial);
          if (m_usbId<0)
          {
            USB_Perror(USB_GetLastError());
            fatal("Cannot open device. Abort.","UsbFTMLInterface::init");
          }
        }
      }
    }
    
    info("Device opened with UsbId "+itos(m_usbId)+".","UsbFTMLInterface::init");
    m_deviceDesc = std::string(desc);
    m_serialNum = std::string(serial);
    
    UsbSetIntCheckingState(m_interrupts);
    if (!USB_Init(m_usbId,true))
    {
      USB_Perror(USB_GetLastError());
      fatal("Could not initialize the USB device "+name()+". Abort.",
            "UsbFTMLInterface::init");
    }
    info("Usb device initialization done.","UsbFTMLInterface::init");
    USB_SetLatencyTimer(m_usbId,m_latencyTimer);
    USB_SetTimeouts(m_usbId,m_txTimeOut,
      m_rxTimeOut);
    USB_SetXferSize(m_usbId,m_txBuffer ,
      m_rxBuffer);
    USB_GetLatencyTimer(m_usbId, &msecs);
    USB_SetSynchronousMode(m_usbId, 100);
    USB_ResetMode(m_usbId);
    // UsbSetMaxLayer(m_usbId,1);
  }
  USB_PurgeBuffers(m_usbId); // PurgeBuffers aprs le reset cause une erreur lors de
       la premire lecture effectue via le port usb.
  USB_ResetDevice(m_usbId);
  wait(1000);
  USB_PurgeBuffers(m_usbId);
  return StatusCode::SUCCESS;
}
interrupts()
bool UsbFTMLInterface::interrupts () [inline]
Get accessor to member m_interrupts
Returns
the current value of m_interrupts
Definition at line 426 of file UsbFTMLInterface.h.
References m_interrupts.
Referenced by setInterrupts().
                     {
    return m_interrupts;
  }
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
latencyTimer()
unsigned char UsbFTMLInterface::latencyTimer () [inline]
Get accessor to member m_latTimer
Returns
the current value of m_latTimer
Definition at line 290 of file UsbFTMLInterface.h.
References m_latencyTimer, m_usbId, and USB_GetLatencyTimer().
Referenced by BOOST_PYTHON_MODULE(), and setLatencyTimer().
                                {
    USB_GetLatencyTimer(m_usbId,&m_latencyTimer);
    return m_latencyTimer;
  }
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), UsbFTInterface::help(), help(), Phaser::help(), ICPhaser::help(), A3PE::help(), Data::hist2d(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), UsbSpiBus::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), reset(), UsbFTInterface::reset(), A3PE::reset(), SpecsSlave::resetInternal(), FEB_v1::resetUsb(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), Object::setName(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), update(), usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTInterface::usbReadU32(), usbReadU32(), UsbFTInterface::usbReadU8(), usbReadU8(), UsbFTInterface::usbWriteRead(), usbWriteRead(), UsbFTInterface::usbWriteU16(), usbWriteU16(), usbWriteU32(), UsbFTInterface::usbWriteU32(), usbWriteU8(), UsbFTInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
nFrames()
long int UsbFTMLInterface::nFrames () [inline]
Get accessor to member m_nFrames
Returns
the current value of m_nFrames
Definition at line 361 of file UsbFTMLInterface.h.
References m_nFrames.
Referenced by setNFrames().
                      {
    return m_nFrames;
  }
numberOfChildren()
unsigned long Hierarchy::numberOfChildren () [inherited]
Definition at line 125 of file Hierarchy.cpp.
References Hierarchy::m_children.
Referenced by Hierarchy::children(), and export_obj().
                                           {
  return m_children.size();
}
origin()
Hierarchy* Hierarchy::origin () [inline], [inherited]
Definition at line 30 of file Hierarchy.h.
References Hierarchy::addChild(), and Hierarchy::m_origin.
Referenced by Hierarchy::child(), export_obj(), and Hierarchy::setParent().
{ return m_origin; } //< Get the origin of the tree
parent() [1/2]
Hierarchy* Hierarchy::parent () [inline], [inherited]
Definition at line 28 of file Hierarchy.h.
References Hierarchy::m_parent.
Referenced by Hierarchy::child(), Hierarchy::childTyped(), export_obj(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), IOobject::init(), Hierarchy::parent(), Hierarchy::path(), Hierarchy::pathTyped(), Element::setConnection(), Hierarchy::setParent(), SpecsInterface::specsMaster(), SpecsInterface::specsMasterDevice(), SpecsInterface::specsSlave(), SpecsInterface::specsSlaveDevice(), and Hierarchy::~Hierarchy().
{ return m_parent; } //< Get Hierarchy Parent
parent() [2/2]
Hierarchy * Hierarchy::parent (std::string type) [inherited]
Definition at line 327 of file Hierarchy.cpp.
References Hierarchy::parent(), and Object::type().
                                            {
  Hierarchy *parent = this->parent();
  if (0 != parent){
    if (parent->type().compare(type)==0) {
      return parent;
    }
    else
      return parent->parent(type);
  }
  else {
    return (Hierarchy*)NULL;
  }
}
path()
std::string Hierarchy::path (std::string str = std::string(``)) [inherited]
Definition at line 344 of file Hierarchy.cpp.
References Hierarchy::m_parent, Object::name(), Hierarchy::parent(), and Hierarchy::path().
Referenced by Hierarchy::child(), Hierarchy::children(), Hierarchy::childTyped(), export_obj(), Hierarchy::path(), usbReadU16(), usbReadU32(), usbReadU8(), usbWriteRead(), usbWriteU16(), usbWriteU32(), and usbWriteU8().
                                      {
  str="/"+name()+str;
  Hierarchy *m_parent=parent();
  if (0!=m_parent){
    return m_parent->path(str);
  }
  return str;
}
pathTyped()
std::string Hierarchy::pathTyped (std::string str = std::string(``)) [inherited]
Definition at line 356 of file Hierarchy.cpp.
References Hierarchy::m_parent, Object::name(), Hierarchy::parent(), Hierarchy::pathTyped(), and Object::type().
Referenced by Hierarchy::children(), export_obj(), and Hierarchy::pathTyped().
                                           {
  Hierarchy *m_parent=parent();
  if (0!=m_parent){
    str="/"+name()+"["+type()+"]"+str;
    return m_parent->pathTyped(str);
  }
  return str;
}
printout()
bool UsbFTMLInterface::printout () [inline]
Get accessor to member m_printout
Returns
the current value of m_printout
Definition at line 490 of file UsbFTMLInterface.h.
References m_printout.
Referenced by setPrintout().
                   {
    return m_printout;
  }
purgeBuffers()
void UsbFTMLInterface::purgeBuffers () [inline]
Definition at line 496 of file UsbFTMLInterface.h.
References m_usbId, and USB_PurgeBuffers().
Referenced by BOOST_PYTHON_MODULE().
{USB_PurgeBuffers(m_usbId);}
rdBlockMax()
bool UsbFTMLInterface::rdBlockMax () [inline]
Get accessor to member m_rdBlockMax
Returns
the current value of m_rdBlockMax
Definition at line 466 of file UsbFTMLInterface.h.
References m_rdBlockMax.
Referenced by setRdBlockMax().
                     {
    return m_rdBlockMax;
  }
read() [1/2]
StatusCode UsbFTMLInterface::read (IOdata * io) [virtual]
Implements Interface.
Definition at line 739 of file UsbFTMLInterface.cpp.
References IOdata::address(), IOdata::Byte, shell::data(), IOdata::dataU16(), IOdata::dataU32(), IOdata::dataU8(), IOdata::DWord, Object::error(), StatusCode::FAILURE, itos(), IOdata::length(), m_rdBlockMax, usbReadU16(), usbReadU32(), usbReadU8(), Object::verbose(), IOdata::Word, and IOdata::wordSize().
Referenced by BOOST_PYTHON_MODULE(), and update().
                                           {
  unsigned long int address = io->address();
  unsigned long int nWords = io->length();
  StatusCode status;
  switch (io->wordSize())
  {
  case (IOdata::Byte):
    if (nWords<m_rdBlockMax+1){
      verbose("Reading a single block "+itos(nWords)+"/"+itos(
      m_rdBlockMax),
              "UsbFTMLInterface::read");
      status = usbReadU8(address, nWords, io->dataU8());
    }
    else {
      // int nwords=nWords;
      U8* data=io->dataU8();
      int nXfer=(int)(nWords/m_rdBlockMax)+1;
      for (int i=0; i<nXfer ; ++i){
        if (i<nXfer-1){
          verbose("Reading block "+itos(i)+
                  " of size "+itos(m_rdBlockMax),
                  "UsbFTMLInterface::read");
          status = usbReadU8(address,
                              m_rdBlockMax ,
                              data);
          data+=sizeof(U8*)*m_rdBlockMax;
        }
        else {
          verbose("Reading last block "+itos(i)+
                  " of size "+itos(nWords%m_rdBlockMax),
                  "UsbFTMLInterface::read");
          status = usbReadU8(address,
                              nWords%m_rdBlockMax ,
                              data);
          data+=sizeof(U8*)*(nWords%m_rdBlockMax);
        }
      }
    }
    break;
  case (IOdata::Word):
    status = usbReadU16(address, nWords, io->dataU16());
    break;
  case (IOdata::DWord):
    status = usbReadU32(address, nWords, io->dataU32());
    break;
  default:
    error("Wrong word size.","UsbFTMLInterface::read");
    status=StatusCode::FAILURE;
  }
  return status;
}
read() [2/2]
StatusCode UsbFTMLInterface::read (unsigned long int address, unsigned long int nWords, boost::python::list & obj)
Python interpreter wrapping for usb read
Definition at line 137 of file UsbFTMLInterface.cpp.
References shell::data(), Object::error(), StatusCode::FAILURE, Object::info(), itos(), m_wordSize, usbReadU16(), usbReadU32(), usbReadU8(), Object::verbose(), WS_Byte, WS_DWord, and WS_Word.
{
  StatusCode status;
  verbose("USB Reading :","UsbFTMLInterface::read");
  switch (m_wordSize)
  {
  case WS_Byte:
    {
      unsigned char *data=new unsigned char[nWords];
      status = usbReadU8(address, nWords, data);
      info("Data format is "+itos(WS_Byte),"UsbFTMLInterface::read");
      for(unsigned int i = 0; i < nWords; i++){
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::read");
        obj.append(data[i]);
      };
      delete data;
    }
    break;
  case WS_Word:
    {
      unsigned short *data=new unsigned short[nWords];
      status = usbReadU16(address, nWords, data);
      verbose("Data format is "+itos(WS_Word),"UsbFTMLInterface::read");
      for(unsigned int i = 0; i < nWords; i++){
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::read");
        obj.append(data[i]);
      };
      delete data;
    }
    break;
  case WS_DWord:
    {
      unsigned long *data=new unsigned long[nWords];
      status = usbReadU32(address, nWords, data);
      verbose("Data format is "+itos(WS_DWord),"UsbFTMLInterface::read");
      for(unsigned int i = 0; i < nWords; i++){
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::read");
        obj.append(data[i]);
      };
      delete data;
    }
    break;
  default:
    error("Wrong word size.","UsbFTMLInterface::read");
    status=StatusCode::FAILURE;
  }
  return status;
}
recursiveInitCommunications()
void Element::recursiveInitCommunications () [inherited]
Triggers a recursive call to initCommunications() for the full hierarchy
Returns
void
Definition at line 44 of file Element.cpp.
References Hierarchy::children().
Referenced by export_obj().
                                         {
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::const_iterator iter;
  for (iter=list.begin();iter!=list.end();iter++){
    dynamic_cast<Element*>((*iter))->recursiveInitCommunications();
  }
}
recursiveInitElement()
void Element::recursiveInitElement () [inherited]
Triggers a recursive call to init() for the full hierarchy
Returns
void
Definition at line 32 of file Element.cpp.
References Hierarchy::children(), and Element::init().
Referenced by export_obj().
                                  {
  init();
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter){
    dynamic_cast<Element*>((*iter))->recursiveInitElement();
  }
}
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
reset()
virtual void UsbFTMLInterface::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Interface.
Definition at line 91 of file UsbFTMLInterface.h.
References close(), Object::info(), init(), m_usbId, Object::name(), and USB_ResetDevice().
                       {
    USB_ResetDevice(m_usbId);
    info("Reset of the Usb interface "+name(),"UsbFTMLInterface::reset");
    close();
    init();
  };
resetMode()
void UsbFTMLInterface::resetMode () [inline]
Definition at line 494 of file UsbFTMLInterface.h.
References m_usbId, and USB_ResetMode().
Referenced by BOOST_PYTHON_MODULE().
{USB_ResetMode(m_usbId);}
rxBuffer()
int UsbFTMLInterface::rxBuffer () [inline]
Get accessor to member m_rxBuffer
Returns
the current value of m_rxBuffer
Definition at line 345 of file UsbFTMLInterface.h.
References m_rxBuffer.
Referenced by BOOST_PYTHON_MODULE(), and setBuffer().
                  {
    return m_rxBuffer;
  }
rxTimeOut()
int UsbFTMLInterface::rxTimeOut () [inline]
Get accessor to member m_rxTimeOut
Returns
the current value of m_rxTimeOut
Definition at line 318 of file UsbFTMLInterface.h.
References m_rxTimeOut.
Referenced by BOOST_PYTHON_MODULE(), and setTimeOut().
                   {
    // USB_SetTimeouts(m_usbId,&m_txTimeOut,&m_rxTimeOut)
    return m_rxTimeOut;
  }
serialNum()
std::string UsbFTMLInterface::serialNum () [inline]
Get accessor to member m_serialNum
Returns
the current value of m_serialNum
Definition at line 257 of file UsbFTMLInterface.h.
References m_serialNum.
Referenced by BOOST_PYTHON_MODULE(), and setSerialNum().
                         {
    return m_serialNum;
  }
setBuffer()
void UsbFTMLInterface::setBuffer (int txBuffer, int rxBuffer) [inline]
Set accessor to member m_txBuffer
Parameters
txBuffer the new value for m_txBuffer
Definition at line 327 of file UsbFTMLInterface.h.
References m_rxBuffer, m_txBuffer, m_usbId, rxBuffer(), txBuffer(), and USB_SetXferSize().
Referenced by BOOST_PYTHON_MODULE().
                                              {
    m_txBuffer = txBuffer;
    m_rxBuffer = rxBuffer;
    USB_SetXferSize(m_usbId,m_txBuffer ,
      m_rxBuffer);
  }
setConnection()
StatusCode Element::setConnection (Hierarchy * connection) [inherited]
Define IO interface
Definition at line 55 of file Element.cpp.
References Element::connection(), Object::debug(), StatusCode::FAILURE, Object::fatal(), Attrib::INTERFACE, Attrib::is(), Element::m_connection, Object::name(), Hierarchy::parent(), StatusCode::SUCCESS, and Object::type().
Referenced by export_obj(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), and IOobject::init().
                                                      {
  if (0==connection){
    fatal("Try to define a connection with a null pointer.",
        "Element::setConnection");
    return StatusCode::FAILURE;
  }
  if (connection->is(Attrib::INTERFACE)){
    m_connection=dynamic_cast<Hierarchy*>(connection);
    return StatusCode::SUCCESS;
  }
  else {
    debug(connection->name()+
        " is not a Attrib::INTERFACE hardware. Connection refused.",
        "Element::setConnection");
    if (0!=connection->parent()){
      return setConnection(connection->parent());
    }
    else{
      fatal("Could not find a connection for element "+
          name()+"["+type()+"].","element::setConnection");
      return StatusCode::FAILURE;
    }
  }
}
setDeviceDesc()
void UsbFTMLInterface::setDeviceDesc (std::string deviceDesc) [inline]
Set accessor to member m_deviceDesc
Parameters
deviceDesc the new value for m_deviceDesc
Definition at line 265 of file UsbFTMLInterface.h.
References deviceDesc(), and m_deviceDesc.
Referenced by BOOST_PYTHON_MODULE().
                                            {
    m_deviceDesc = deviceDesc;
  }
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setFakeErr()
void UsbFTMLInterface::setFakeErr (unsigned int fakeErr) [inline]
Set accessor to member m_fakeErr
Parameters
fakeErr the new value for m_fakeErr
Definition at line 402 of file UsbFTMLInterface.h.
References fakeErr(), and m_fakeErr.
                                         {
    m_fakeErr = fakeErr;
  }
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setInterrupts()
void UsbFTMLInterface::setInterrupts (bool interrupts) [inline]
Set accessor to member m_interrupts
Parameters
interrupts the new value for m_interrupts
Definition at line 418 of file UsbFTMLInterface.h.
References interrupts(), and m_interrupts.
                                       {
    m_interrupts = interrupts;
  }
setLatencyTimer()
void UsbFTMLInterface::setLatencyTimer (unsigned char latencyTimer) [inline]
Set accessor to member m_latencyTimer
Parameters
latTimer the new value for m_latencyTimer
Definition at line 281 of file UsbFTMLInterface.h.
References latencyTimer(), m_latencyTimer, m_usbId, and USB_SetLatencyTimer().
Referenced by BOOST_PYTHON_MODULE().
                                                    {
    m_latencyTimer = latencyTimer;
    USB_SetLatencyTimer(m_usbId, m_latencyTimer);
  }
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setNFrames()
void UsbFTMLInterface::setNFrames (long int nFrames) [inline]
Set accessor to member m_nFrames
Parameters
nFrames the new value for m_nFrames
Definition at line 353 of file UsbFTMLInterface.h.
References m_nFrames, and nFrames().
                                     {
    m_nFrames = nFrames;
  }
setParent()
void Hierarchy::setParent (Hierarchy * parent) [inherited]
Definition at line 67 of file Hierarchy.cpp.
References Hierarchy::m_origin, Hierarchy::m_parent, Hierarchy::origin(), and Hierarchy::parent().
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Computer::Computer(), Application::create(), export_obj(), and SpecsMezzanine::SpecsMezzanine().
                                              {
  m_parent = parent;
  if ((Hierarchy*)0==parent) return;
  Hierarchy *curr = this;
  Hierarchy *prev = parent;
  while (prev != 0){
    curr = prev;
    prev = curr->parent();
  }
  if (parent->origin()!=0) m_origin=parent->origin();
}
setPrintout()
void UsbFTMLInterface::setPrintout (bool printout) [inline]
Set accessor to member m_printout
Parameters
printout the new value for m_printout
Definition at line 482 of file UsbFTMLInterface.h.
References m_printout, and printout().
                                   {
    m_printout = printout;
  }
setRdBlockMax()
void UsbFTMLInterface::setRdBlockMax (bool rdBlockMax) [inline]
Set accessor to member m_rdBlockMax
Parameters
rdBlockMax the new value for m_rdBlockMax
Definition at line 474 of file UsbFTMLInterface.h.
References m_rdBlockMax, and rdBlockMax().
                                       {
    m_rdBlockMax = rdBlockMax;
  }
setSerialNum()
void UsbFTMLInterface::setSerialNum (std::string serialNum) [inline]
Set accessor to member m_serialNum
Parameters
serialNum the new value for m_serialNum
Definition at line 249 of file UsbFTMLInterface.h.
References m_serialNum, and serialNum().
Referenced by BOOST_PYTHON_MODULE().
                                          {
    m_serialNum = serialNum;
  }
setShowEpromState()
void UsbFTMLInterface::setShowEpromState (bool showEpromState) [inline]
Set accessor to member m_showEpromState
Parameters
showEpromState the new value for m_showEpromState
Definition at line 434 of file UsbFTMLInterface.h.
References m_showEpromState, and showEpromState().
                                               {
    m_showEpromState = showEpromState;
  }
setSynchronousMode()
void UsbFTMLInterface::setSynchronousMode () [inline]
Definition at line 498 of file UsbFTMLInterface.h.
References m_usbId, and USB_SetSynchronousMode().
Referenced by BOOST_PYTHON_MODULE().
{USB_SetSynchronousMode(m_usbId, 100);}
setTimeOut()
void UsbFTMLInterface::setTimeOut (int txTimeOut, int rxTimeOut) [inline]
Set accessor to member m_txTimeOut
Parameters
txTimeOut the new value for m_txTimeOut
Definition at line 299 of file UsbFTMLInterface.h.
References m_rxTimeOut, m_txTimeOut, m_usbId, rxTimeOut(), txTimeOut(), and USB_SetTimeouts().
Referenced by BOOST_PYTHON_MODULE().
                                                {
    m_txTimeOut = txTimeOut;
    m_rxTimeOut = rxTimeOut;
    USB_SetTimeouts(m_usbId, m_txTimeOut,
      m_rxTimeOut);
  }
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
setUsbId()
void UsbFTMLInterface::setUsbId (int usbId) [inline]
Set accessor to member m_usbId
Parameters
usbId the new value for m_usbId
Definition at line 232 of file UsbFTMLInterface.h.
References m_usbId, and usbId().
                            {
    m_usbId = usbId;
  }
setWordCount()
void UsbFTMLInterface::setWordCount (unsigned long wordCount) [inline]
Set accessor to member m_wordCount
Parameters
wordCount the new value for m_wordCount
Definition at line 370 of file UsbFTMLInterface.h.
References m_wordCount, and wordCount().
                                              {
    m_wordCount = wordCount;
  }
setWordSize()
void UsbFTMLInterface::setWordSize (unsigned long wordSize) [inline]
Set accessor to member m_wordSize
Parameters
wordSize the new value for m_wordSize
Definition at line 386 of file UsbFTMLInterface.h.
References m_wordSize, and wordSize().
Referenced by BOOST_PYTHON_MODULE().
                                            {
    m_wordSize = wordSize;
  }
setWrBlockMax()
void UsbFTMLInterface::setWrBlockMax (bool wrBlockMax) [inline]
Set accessor to member m_wrBlockMax
Parameters
wrBlockMax the new value for m_wrBlockMax
Definition at line 458 of file UsbFTMLInterface.h.
References m_wrBlockMax, and wrBlockMax().
                                       {
    m_wrBlockMax = wrBlockMax;
  }
showEpromState()
bool UsbFTMLInterface::showEpromState () [inline]
Get accessor to member m_showEpromState
Returns
the current value of m_showEpromState
Definition at line 442 of file UsbFTMLInterface.h.
References m_showEpromState.
Referenced by setShowEpromState().
                         {
    return m_showEpromState;
  }
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestSPI::Plot(), TestUSB::Plot(), TestI2C::Plot(), Object::setTitle(), and Application::terminate().
{ return m_title; } // < Get Object m_title
tree() [1/2]
void Hierarchy::tree (std::string indent = std::string(``)) [inherited]
Definition at line 310 of file Hierarchy.cpp.
References Hierarchy::children(), Object::info(), Object::msgSvc(), Object::name(), MsgSvc::NONE, and Object::type().
                                    {
  std::string line=indent+" -> "+name()+"["+type()+"] ";
  if (std::string("")==indent){
    info("Hierarchy for Object "+name()+"["+type()+"]","Hierarchy::tree");
  }
  msgSvc(MsgSvc::NONE,line,"");
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter){
    std::string tab=" ";
    (*iter)->tree(indent+tab);
  }
}
tree() [2/2]
void Hierarchy::tree () [inline], [inherited]
Definition at line 46 of file Hierarchy.h.
References Hierarchy::m_parent, and Hierarchy::tree().
Referenced by Hierarchy::children(), export_obj(), and Hierarchy::tree().
{ tree(""); }; // output tree of Hierarchy from object
txBuffer()
int UsbFTMLInterface::txBuffer () [inline]
Get accessor to member m_txBuffer
Returns
the current value of m_txBuffer
Definition at line 337 of file UsbFTMLInterface.h.
References m_txBuffer.
Referenced by BOOST_PYTHON_MODULE(), and setBuffer().
                  {
    return m_txBuffer;
  }
txTimeOut()
int UsbFTMLInterface::txTimeOut () [inline]
Get accessor to member m_txTimeOut
Returns
the current value of m_txTimeOut
Definition at line 309 of file UsbFTMLInterface.h.
References m_txTimeOut.
Referenced by BOOST_PYTHON_MODULE(), and setTimeOut().
                   {
    // USB_SetTimeouts(m_usbId,&m_txTimeOut,&m_rxTimeOut)
    return m_txTimeOut;
  }
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
update()
virtual void UsbFTMLInterface::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Interface.
Definition at line 101 of file UsbFTMLInterface.h.
References Object::info(), Object::name(), read(), usbRead(), usbReadU16(), usbReadU32(), usbReadU8(), usbWrite(), usbWriteRead(), usbWriteU16(), usbWriteU32(), usbWriteU8(), and write().
Referenced by AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
                         {
    info("UsbFTMLInterface "+name()+". Nothing to do.","UsbFTMLInterface::update");
  };
usbId()
int UsbFTMLInterface::usbId () [inline]
Get accessor to member m_usbId
Returns
the current value of m_usbId
Definition at line 240 of file UsbFTMLInterface.h.
References m_usbId.
Referenced by setUsbId().
               {
    return m_usbId;
  }
usbRead()
StatusCode UsbFTMLInterface::usbRead (unsigned long int address, unsigned long int nWords, std::vector< U32 > & words)
Read usb in std::vector format -- Do not use : Only supports U8 ! Write usb in std::vector<U8> format -- Do not use yet : Only supports U8 ! Read usb in std::vector format -- Do not use : Only supports U8 ! Write usb in std::vector<U16> format -- Do not use yet : Only supports U8 ! Read usb in std::vector format -- Do not use : Only supports U8 !
Definition at line 245 of file UsbFTMLInterface.cpp.
References shell::data(), Object::error(), StatusCode::FAILURE, itos(), m_wordSize, usbReadU16(), usbReadU32(), usbReadU8(), Object::verbose(), WS_Byte, WS_DWord, and WS_Word.
Referenced by update().
{
  StatusCode status;
  verbose("USB Reading :","UsbFTMLInterface::read");
  words.clear();
  words.reserve(nWords);
  switch (m_wordSize)
  {
  case WS_Byte:
    {
      unsigned char *data=new unsigned char[nWords];
      status = usbReadU8(address, nWords, data);
      for(unsigned int i = 0; i < nWords; i++){
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::usbRead");
        words.push_back(data[i]);
      };
      delete data;
    }
    break;
  case WS_Word:
    {
      unsigned short *data=new unsigned short[nWords];
      status = usbReadU16(address, nWords, data);
      for(unsigned int i = 0; i < nWords; i++){
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::usbRead");
        words.push_back(data[i]);
      };
      delete data;
    }
    break;
  case WS_DWord:
    {
      unsigned long *data=new unsigned long[nWords];
      status = usbReadU32(address, nWords, data);
      for(unsigned int i = 0; i < nWords; i++){
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::usbRead");
        words.push_back(data[i]);
      };
      delete data;
    }
    break;
  default:
    error("Wrong word size.","UsbFTMLInterface::read");
    status=StatusCode::FAILURE;
  }
  return status;
}
usbReadU16()
StatusCode UsbFTMLInterface::usbReadU16 (unsigned long int address, unsigned long int nWords, unsigned short * data)
Definition at line 397 of file UsbFTMLInterface.cpp.
References Object::error(), StatusCode::FAILURE, itos(), m_usbId, Object::name(), Hierarchy::path(), PrintFrameInfo(), StatusCode::SUCCESS, USB_GetLastError(), USB_INT_FRAME, USB_NoErr, UsbReadML(), and Object::verbose().
Referenced by read(), update(), and usbRead().
                                                               {
  
  USB_Error rdErr=USB_NoErr;
  long int bytecount=0;
  verbose("in UsbReadU16.");
  long int nData = (long int)(2*nWords);
  
  unsigned char *buff=new unsigned char [nData];
  
  verbose("before usbread");
  int path = -1;
  bytecount=UsbReadML(m_usbId, &path, address, buff, nData);
  
  verbose("after usbread");
  
  for (unsigned long word=0; word<nWords; ++word)
  {
    data[word]=buff[2*word+1];
    data[word]=(data[word]<<8)|buff[2*word];
  }
  delete buff;
  if (nData==bytecount){
    verbose(itos(bytecount)+" bytes read from USB Interface "+name(),
            "UsbFTMLInterface::usbReadU16");
    return StatusCode::SUCCESS;
  }
  if (bytecount<0){
    rdErr=USB_GetLastError();
    error("USB error number "+itos(rdErr)+" - USB_INT_FRAME="+itos(
      USB_INT_FRAME),
            " UsbFTMLInterface::usbReadU16");
    if (rdErr==USB_INT_FRAME){
      PrintFrameInfo();
    }
    return StatusCode::FAILURE;
  }
  
  if (0==bytecount){
    error(" O Byte read from USB interface "+name()+".",
          "UsbFTMLInterface::usbReadU16");
    return StatusCode::FAILURE;
  }
  if (nData!=bytecount){
    error(itos(bytecount)+" byte(s) read from USB interface "+name()+
            " out of "+itos(nData)+" bytes expected.",
          "UsbFTMLInterface::usbReadU16");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
usbReadU32()
StatusCode UsbFTMLInterface::usbReadU32 (unsigned long int address, unsigned long int nWords, unsigned long * data)
Definition at line 462 of file UsbFTMLInterface.cpp.
References Object::error(), StatusCode::FAILURE, itos(), m_usbId, Object::name(), Hierarchy::path(), PrintFrameInfo(), StatusCode::SUCCESS, USB_GetLastError(), USB_INT_FRAME, USB_NoErr, UsbReadML(), and Object::verbose().
Referenced by read(), update(), and usbRead().
                                                              {
  
  USB_Error rdErr=USB_NoErr;
  long int bytecount=0;
  long int nData = (long int)(4*nWords);
  
  unsigned char *buff=new unsigned char [nData];
  int path = -1;
  
  bytecount=UsbReadML(m_usbId, &path, address, buff, nData);
  for (unsigned long word=0; word<nWords; ++word)
  {
    data[word]=buff[4*word+3];
    data[word]=(data[word]<<8)|buff[4*word+2];
    data[word]=(data[word]<<8)|buff[4*word+1];
    data[word]=(data[word]<<8)|buff[4*word];
  }
  delete buff;
  if (nData==bytecount){
    verbose(itos(bytecount)+" bytes read from USB Interface "+name(),
            "UsbFTMLInterface::usbRead");
    return StatusCode::SUCCESS;
  }
  if (bytecount<0){
    rdErr=USB_GetLastError();
    error("USB error number "+itos(rdErr)+" - USB_INT_FRAME="+itos(
      USB_INT_FRAME),
            " UsbFTMLInterface::usbRead32");
    if (rdErr==USB_INT_FRAME){
      PrintFrameInfo();
    }
    return StatusCode::FAILURE;
  }
  
  if (0==bytecount){
    error(" O Byte read from USB interface "+name()+".","UsbFTMLInterface::usbRead32");
    return StatusCode::FAILURE;
  }
  if (nData!=bytecount){
    error(itos(bytecount)+" byte(s) read from USB interface "+name()+
            " out of "+itos(nData)+" bytes expected.","UsbFTMLInterface::usbRead32");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
usbReadU8()
StatusCode UsbFTMLInterface::usbReadU8 (unsigned long int address, unsigned long int nWords, unsigned char * data)
Read usb (U8 format)
Definition at line 351 of file UsbFTMLInterface.cpp.
References Object::error(), StatusCode::FAILURE, itos(), m_usbId, Object::name(), Hierarchy::path(), PrintFrameInfo(), StatusCode::SUCCESS, USB_GetLastError(), USB_INT_FRAME, USB_NoErr, UsbReadML(), and Object::verbose().
Referenced by read(), update(), and usbRead().
                                                             {
  
  USB_Error rdErr=USB_NoErr;
  long int bytecount=0;
  long int nData = (long int)(nWords);
  int path = -1;
  
  bytecount=UsbReadML(m_usbId, &path, address, data, nData);
  if (nData==bytecount){
    verbose(itos(bytecount)+" bytes read from USB Interface "+name(),
            "UsbFTMLInterface::usbRead8");
    return StatusCode::SUCCESS;
  }
  if (bytecount<0){
    rdErr=USB_GetLastError();
    error("USB error number "+itos(rdErr)+" - USB_INT_FRAME="+itos(
      USB_INT_FRAME),
            " UsbFTMLInterface::usbRead8");
    if (rdErr==USB_INT_FRAME){
      PrintFrameInfo();
    }
    return StatusCode::FAILURE;
  }
  
  if (0==bytecount){
    error(" O Byte read from USB interface "+name()+".","UsbFTMLInterface::usbRead8");
    return StatusCode::FAILURE;
  }
  if (nData!=bytecount){
    error(itos(bytecount)+" byte(s) read from USB interface "+name()+
            " out of "+itos(nData)+" bytes expected.","UsbFTMLInterface::usbRead8");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
usbWrite()
StatusCode UsbFTMLInterface::usbWrite (unsigned long int address, std::vector< U32 > words)
Write usb in std::vector<U32> format -- Do not use yet : Only supports U8 !
Definition at line 298 of file UsbFTMLInterface.cpp.
References shell::data(), Object::error(), StatusCode::FAILURE, itos(), m_wordSize, usbWriteU16(), usbWriteU32(), usbWriteU8(), Object::verbose(), WS_Byte, WS_DWord, and WS_Word.
Referenced by update().
{
  unsigned long int nWords = words.size();
  StatusCode status;
  verbose("USB Writing :");
  switch (m_wordSize)
  {
  case WS_Byte:
    {
      unsigned char *data=new unsigned char[nWords];
      for(unsigned int i = 0; i < nWords; i++){
        data[i]=words[i];
        verbose("Data format is "+itos(WS_Byte),"UsbFTMLInterface::usbWrite");
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::usbWrite");
      };
      status = usbWriteU8(address, nWords, data);
      delete data;
    }
    break;
  case WS_Word:
    {
      unsigned short *data=new unsigned short[nWords];
      for(unsigned int i = 0; i < nWords; i++){
        data[i]=words[i];
        verbose("Data format is "+itos(WS_Word),"UsbFTMLInterface::usbWrite");
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::usbWrite");
      };
      status = usbWriteU16(address, nWords, data);
      delete data;
    }
    break;
  case WS_DWord:
    {
      unsigned long *data=new unsigned long[nWords];
      for(unsigned int i = 0; i < nWords; i++){
        data[i]=words[i];
        verbose("Data format is "+itos(WS_DWord),"UsbFTMLInterface::usbWrite");
        verbose("wd "+itos(i)+" "+itos(data[i]) ,"UsbFTMLInterface::usbWrite");
      }
      status = usbWriteU32(address, nWords, data);
      delete data;
    }
    break;
  default:
    error("Wrong word size.","read");
    status=StatusCode::FAILURE;
  }
  return status;
}
usbWriteRead()
StatusCode UsbFTMLInterface::usbWriteRead (unsigned long int address, std::vector< U8 > dataWrite, std::vector< U8 > & dataRead)
Write/Read std::vector<U8> format -- Do not use yet : Only supports U8 !
Definition at line 648 of file UsbFTMLInterface.cpp.
References Object::error(), StatusCode::FAILURE, itos(), m_usbId, Object::name(), Hierarchy::path(), PrintFrameInfo(), StatusCode::SUCCESS, USB_GetLastError(), USB_INT_FRAME, USB_NoErr, UsbReadML(), UsbWrtML(), and Object::verbose().
Referenced by update().
                                                                    {
  USB_Error rdErr=USB_NoErr, wrErr=USB_NoErr;
  long int bytecount=0;
  long int nData=dataWrite.size();
  const unsigned long int bufSize=nData+4;
  U8* bufWr=new U8[bufSize];
  U8* bufRd=new U8[bufSize];
  for(int j=0; j<nData; ++j) bufWr[j] = static_cast<unsigned char>(dataWrite[j]);
  int path = -1;
  bytecount=UsbWrtML(m_usbId, &path, address, bufWr, nData);
  if (bytecount<0){
    wrErr=USB_GetLastError();
    error("USB error number "+itos(wrErr)+" - USB_INT_FRAME="+itos(
      USB_INT_FRAME),
            " UsbFTMLInterface::usbWriteRead");
    if (wrErr==USB_INT_FRAME){
      PrintFrameInfo();
    }
    return StatusCode::FAILURE;
  }
  if (nData==bytecount){
    verbose(itos(bytecount)+" bytes written on USB Interface "+name(),
            "UsbFTMLInterface::usbWriteRead");
    int path = -1;
    bytecount=UsbReadML(m_usbId, &path, address, bufRd, nData);
    if (nData==bytecount){
      verbose(itos(bytecount)+" bytes read from USB Interface "+name(),
              "UsbFTMLInterface::usbRead");
      for(int j=0; j<nData; ++j) dataRead[j] = static_cast<unsigned char>(bufRd[j]);
      return StatusCode::SUCCESS;
    }
    if (bytecount<0){
      rdErr=USB_GetLastError();
      error("USB error number "+itos(rdErr)+" - USB_INT_FRAME="+itos(
      USB_INT_FRAME),
              " UsbFTMLInterface::usbWriteRead");
      if (rdErr==USB_INT_FRAME){
        PrintFrameInfo();
      }
      return StatusCode::FAILURE;
    }
  
    if (0==bytecount){
      error(" O Byte read from USB interface "+name()+".","UsbFTMLInterface::usbRead");
      return StatusCode::FAILURE;
    }
    if (nData!=bytecount){
      error(itos(bytecount)+" byte(s) read from USB interface "+name()+
              " out of "+itos(nData)+" bytes expected.","UsbFTMLInterface::usbRead");
      return StatusCode::FAILURE;
    }
  }
  
  
  if (0==bytecount){
    error(" O Byte written n USB interface "+name()+".","UsbFTMLInterface::usbWrite");
    return StatusCode::FAILURE;
  }
  if (nData!=bytecount){
    error(itos(bytecount)+" byte(s) written USB interface "+name()+
            " out of "+itos(nData)+" bytes to be sent.","UsbFTMLInterface::usbWrite");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS; return StatusCode::SUCCESS;
}
usbWriteU16()
StatusCode UsbFTMLInterface::usbWriteU16 (unsigned long int address, unsigned long int nWords, unsigned short * data)
Write usb (U16 format)
Definition at line 562 of file UsbFTMLInterface.cpp.
References Object::error(), StatusCode::FAILURE, itos(), m_usbId, Object::name(), Hierarchy::path(), PrintFrameInfo(), StatusCode::SUCCESS, USB_GetLastError(), USB_INT_FRAME, USB_NoErr, UsbWrtML(), and Object::verbose().
Referenced by update(), usbWrite(), and write().
                                                               {
  USB_Error wrErr=USB_NoErr;
  long int bytecount=0;
  long int nData=(long int)(2*nWords);
  int path = -1;
  bytecount=UsbWrtML(m_usbId, &path, address, data, nData);
  if (bytecount<0){
    wrErr=USB_GetLastError();
    error("USB error number "+itos(wrErr)+" - USB_INT_FRAME="+itos(
      USB_INT_FRAME),
            "UsbFTMLInterface::usbWrite16");
    if (wrErr==USB_INT_FRAME){
      PrintFrameInfo();
    }
    return StatusCode::FAILURE;
  }
  if (nData==bytecount){
    verbose(itos(bytecount)+" bytes written on USB Interface "+name(),
            "UsbFTMLInterface::usbWrite16");
  }
  
  if (0==bytecount){
    error(" O Byte written on USB interface "+name()+".","UsbFTMLInterface::usbWrite16");
    return StatusCode::FAILURE;
  }
  if (nData!=bytecount){
    error(itos(bytecount)+" byte(s) written on USB interface "+name()+
            " out of "+itos(nData)+" bytes to be sent.","UsbFTMLInterface::usbWrite16");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
usbWriteU32()
StatusCode UsbFTMLInterface::usbWriteU32 (unsigned long int address, unsigned long int nWords, unsigned long * data)
Write usb (U32 format)
Definition at line 605 of file UsbFTMLInterface.cpp.
References Object::error(), StatusCode::FAILURE, itos(), m_usbId, Object::name(), Hierarchy::path(), PrintFrameInfo(), StatusCode::SUCCESS, USB_GetLastError(), USB_INT_FRAME, USB_NoErr, UsbWrtML(), and Object::verbose().
Referenced by update(), usbWrite(), and write().
                                                              {
  USB_Error wrErr=USB_NoErr;
  long int bytecount=0;
  long int nData=(long int)(4*nWords);
  int path = -1;
  bytecount=UsbWrtML(m_usbId, &path, address, data, nData);
  if (bytecount<0){
    wrErr=USB_GetLastError();
    error("USB error number "+itos(wrErr)+" - USB_INT_FRAME="+itos(
      USB_INT_FRAME),
            "UsbFTMLInterface::usbWrite32");
    if (wrErr==USB_INT_FRAME){
      PrintFrameInfo();
    }
    return StatusCode::FAILURE;
  }
  if (nData==bytecount){
    verbose(itos(bytecount)+" bytes written on USB Interface "+name(),
            "UsbFTMLInterface::usbWrite32");
  }
  
  if (0==bytecount){
    error(" O Byte written on USB interface "+name()+".","UsbFTMLInterface::usbWrite32");
    return StatusCode::FAILURE;
  }
  if (nData!=bytecount){
    error(itos(bytecount)+" byte(s) written on USB interface "+name()+
            " out of "+itos(nData)+" bytes to be sent.","UsbFTMLInterface::usbWrite32");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
usbWriteU8()
StatusCode UsbFTMLInterface::usbWriteU8 (unsigned long int address, unsigned long int nWords, unsigned char * data)
Write usb (U8 format)
Definition at line 519 of file UsbFTMLInterface.cpp.
References Object::error(), StatusCode::FAILURE, itos(), m_usbId, Object::name(), Hierarchy::path(), PrintFrameInfo(), StatusCode::SUCCESS, USB_GetLastError(), USB_INT_FRAME, USB_NoErr, UsbWrtML(), and Object::verbose().
Referenced by update(), usbWrite(), and write().
                                                             {
  USB_Error wrErr=USB_NoErr;
  long int bytecount=0;
  long int nData=(long int)(nWords);
  int path = -1;
  bytecount=UsbWrtML(m_usbId, &path, address, data, nData);
  if (bytecount<0){
    wrErr=USB_GetLastError();
    error("USB error number "+itos(wrErr)+" - USB_INT_FRAME="+itos(
      USB_INT_FRAME),
            "UsbFTMLInterface::usbWrite8");
    if (wrErr==USB_INT_FRAME){
      PrintFrameInfo();
    }
    return StatusCode::FAILURE;
  }
  if (nData==bytecount){
    verbose(itos(bytecount)+" bytes written on USB Interface "+name(),
            "UsbFTMLInterface::usbWrite8");
  }
  
  if (0==bytecount){
    error(" O Byte written on USB interface "+name()+".","UsbFTMLInterface::usbWrite8");
    return StatusCode::FAILURE;
  }
  if (nData!=bytecount){
    error(itos(bytecount)+" byte(s) written on USB interface "+name()+
            " out of "+itos(nData)+" bytes to be sent.","UsbFTMLInterface::usbWrite8");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTInterface::read(), read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), usbRead(), usbReadU16(), UsbFTInterface::usbReadU16(), usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), usbReadU8(), usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), usbWriteRead(), UsbFTInterface::usbWriteU16(), usbWriteU16(), UsbFTInterface::usbWriteU32(), usbWriteU32(), UsbFTInterface::usbWriteU8(), usbWriteU8(), wait(), write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), Acquisition::execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), TestI2C::initialize(), EmulateFE::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsMaster::reset(), SpecsSlave::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
wordCount()
unsigned long UsbFTMLInterface::wordCount () [inline]
Get accessor to member m_wordCount
Returns
the current value of m_wordCount
Definition at line 378 of file UsbFTMLInterface.h.
References m_wordCount.
Referenced by setWordCount().
                             {
    return m_wordCount;
  }
wordSize()
unsigned long UsbFTMLInterface::wordSize () [inline]
Get accessor to member m_wordSize
Returns
the current value of m_wordSize
Definition at line 394 of file UsbFTMLInterface.h.
References m_wordSize.
Referenced by BOOST_PYTHON_MODULE(), and setWordSize().
                            {
    return m_wordSize;
  }
wrBlockMax()
bool UsbFTMLInterface::wrBlockMax () [inline]
Get accessor to member m_wrBlockMax
Returns
the current value of m_wrBlockMax
Definition at line 450 of file UsbFTMLInterface.h.
References m_wrBlockMax.
Referenced by setWrBlockMax().
                     {
    return m_wrBlockMax;
  }
write() [1/2]
StatusCode UsbFTMLInterface::write (IOdata * io) [virtual]
Implements Interface.
Definition at line 795 of file UsbFTMLInterface.cpp.
References IOdata::address(), IOdata::Byte, shell::data(), IOdata::dataU16(), IOdata::dataU32(), IOdata::dataU8(), IOdata::DWord, Object::error(), StatusCode::FAILURE, itos(), IOdata::length(), m_wrBlockMax, usbWriteU16(), usbWriteU32(), usbWriteU8(), Object::verbose(), IOdata::Word, and IOdata::wordSize().
Referenced by BOOST_PYTHON_MODULE(), and update().
                                            {
  unsigned long int address = io->address();
  unsigned long int nWords = io->length();
  StatusCode status;
  switch (io->wordSize())
  {
  case (IOdata::Byte):
    if (nWords<m_wrBlockMax+1){
      verbose("Writing a single block "+itos(nWords)+"/"+itos(
      m_wrBlockMax),
              "UsbFTMLInterface::write");
      status = usbWriteU8(address, nWords, io->dataU8());
    }
    else {
      // int nwords=nWords;
      U8* data=io->dataU8();
      int nXfer=(int)ceil((float)(nWords)/(float)(m_wrBlockMax));
      verbose("number of Xfer="+itos(nXfer)+
              " "+itos(m_wrBlockMax)+
              " "+itos(nWords),"");
      for (int i=0; i<nXfer ; ++i){
        if (i<nXfer-1){
          verbose("Writing block "+itos(i)+
                  " of size "+itos(m_wrBlockMax),
                  "UsbFTMLInterface::write");
          status = usbWriteU8(address,
                               m_wrBlockMax ,
                               data);
          data+=sizeof(U8)*m_wrBlockMax;
        }
        else {
          //nWords%m_wrBlockMax
          unsigned int nwords=nWords-(nXfer-1)*m_wrBlockMax;
          verbose("Writing last block "+itos(i)+
                  " of size "+itos(nwords),
                  "UsbFTMLInterface::write");
          status = usbWriteU8(address,
                               nwords,
                               data);
          data+=sizeof(U8)*(nwords);
        }
      }
    }
    break;
  case (IOdata::Word):
    status = usbWriteU16(address, nWords, io->dataU16());
    break;
  case (IOdata::DWord):
    status = usbWriteU32(address, nWords, io->dataU32());
    break;
  default:
    error("Wrong word size.","UsbFTMLInterface::read");
    status=StatusCode::FAILURE;
  }
  return status;
}
write() [2/2]
StatusCode UsbFTMLInterface::write (unsigned long int address, boost::python::list obj)
Python interpreter wrapping for usb write
Definition at line 191 of file UsbFTMLInterface.cpp.
References shell::data(), Object::error(), StatusCode::FAILURE, itos(), m_wordSize, usbWriteU16(), usbWriteU32(), usbWriteU8(), Object::verbose(), WS_Byte, WS_DWord, and WS_Word.
{
  unsigned long int nWords = len(obj);
  StatusCode status;
  verbose("USB Writing :");
  switch (m_wordSize)
  {
  case WS_Byte:
    {
      unsigned char *data=new unsigned char[nWords];
      for(unsigned int i = 0; i < nWords; i++){
        data[i]=(boost::python::extract<unsigned char>(obj[i]));
        verbose("Data format is "+itos(WS_Byte),"UsbFTMLInterface::write");
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::write");
      };
      status = usbWriteU8(address, nWords, data);
      delete data;
    }
    break;
  case WS_Word:
    {
      unsigned short *data=new unsigned short[nWords];
      for(unsigned int i = 0; i < nWords; i++){
        verbose("Data format is "+itos(WS_Word),"UsbFTMLInterface::write");
        data[i]=(boost::python::extract<unsigned short>(obj[i]));
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::write");
      };
      status = usbWriteU16(address, nWords, data);
      delete data;
    }
    break;
  case WS_DWord:
    {
      unsigned long *data=new unsigned long[nWords];
      for(unsigned int i = 0; i < nWords; i++){
        data[i]=(boost::python::extract<unsigned long>(obj[i]));
        verbose("Data format is "+itos(WS_DWord),"UsbFTMLInterface::write");
        verbose("wd "+itos(i)+" "+itos(data[i]),"UsbFTMLInterface::write");
      }
      status = usbWriteU32(address, nWords, data);
      delete data;
    }
    break;
  default:
    error("Wrong word size.","read");
    status=StatusCode::FAILURE;
  }
  return status;
}
Member Data Documentation
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_connection
Hierarchy* Element::m_connection [protected], [inherited]
Definition at line 70 of file Element.h.
Referenced by UsbSpiBus::clockDivider(), Element::connection(), Element::Element(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), IOobject::init(), UsbI2cBus::read(), UsbSpiBus::read(), UsbSpiBus::setClockDivider(), Element::setConnection(), UsbI2cBus::write(), and UsbSpiBus::write().
m_deviceDesc
std::string UsbFTMLInterface::m_deviceDesc [private]
Definition at line 503 of file UsbFTMLInterface.h.
Referenced by deviceDesc(), init(), and setDeviceDesc().
m_fakeErr
unsigned int UsbFTMLInterface::m_fakeErr [private]
Definition at line 512 of file UsbFTMLInterface.h.
Referenced by fakeErr(), and setFakeErr().
m_interrupts
bool UsbFTMLInterface::m_interrupts [private]
Definition at line 513 of file UsbFTMLInterface.h.
Referenced by init(), interrupts(), and setInterrupts().
m_latencyTimer
unsigned char UsbFTMLInterface::m_latencyTimer [private]
Definition at line 504 of file UsbFTMLInterface.h.
Referenced by init(), latencyTimer(), and setLatencyTimer().
m_nFrames
long int UsbFTMLInterface::m_nFrames [private]
Definition at line 509 of file UsbFTMLInterface.h.
Referenced by nFrames(), and setNFrames().
m_printout
bool UsbFTMLInterface::m_printout [private]
Definition at line 515 of file UsbFTMLInterface.h.
Referenced by printout(), and setPrintout().
m_rdBlockMax
int UsbFTMLInterface::m_rdBlockMax [private]
Definition at line 516 of file UsbFTMLInterface.h.
Referenced by rdBlockMax(), read(), and setRdBlockMax().
m_rxBuffer
int UsbFTMLInterface::m_rxBuffer [private]
Definition at line 508 of file UsbFTMLInterface.h.
Referenced by init(), rxBuffer(), and setBuffer().
m_rxTimeOut
int UsbFTMLInterface::m_rxTimeOut [private]
Definition at line 506 of file UsbFTMLInterface.h.
Referenced by init(), rxTimeOut(), and setTimeOut().
m_serialNum
std::string UsbFTMLInterface::m_serialNum [private]
Definition at line 502 of file UsbFTMLInterface.h.
Referenced by init(), serialNum(), and setSerialNum().
m_showEpromState
bool UsbFTMLInterface::m_showEpromState [private]
Definition at line 514 of file UsbFTMLInterface.h.
Referenced by setShowEpromState(), and showEpromState().
m_txBuffer
int UsbFTMLInterface::m_txBuffer [private]
Definition at line 507 of file UsbFTMLInterface.h.
Referenced by init(), setBuffer(), and txBuffer().
m_txTimeOut
int UsbFTMLInterface::m_txTimeOut [private]
Definition at line 505 of file UsbFTMLInterface.h.
Referenced by init(), setTimeOut(), and txTimeOut().
m_usbId
int UsbFTMLInterface::m_usbId [private]
Definition at line 501 of file UsbFTMLInterface.h.
Referenced by close(), init(), latencyTimer(), purgeBuffers(), reset(), resetMode(), setBuffer(), setLatencyTimer(), setSynchronousMode(), setTimeOut(), setUsbId(), usbId(), usbReadU16(), usbReadU32(), usbReadU8(), usbWriteRead(), usbWriteU16(), usbWriteU32(), and usbWriteU8().
m_wordCount
unsigned long UsbFTMLInterface::m_wordCount [private]
Definition at line 510 of file UsbFTMLInterface.h.
Referenced by setWordCount(), and wordCount().
m_wordSize
unsigned long UsbFTMLInterface::m_wordSize [private]
Definition at line 511 of file UsbFTMLInterface.h.
Referenced by read(), setWordSize(), usbRead(), usbWrite(), wordSize(), and write().
m_wrBlockMax
int UsbFTMLInterface::m_wrBlockMax [private]
Definition at line 517 of file UsbFTMLInterface.h.
Referenced by setWrBlockMax(), wrBlockMax(), and write().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/UsbFTMLInterface.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/UsbFTMLInterface.cpp