Attrib Class Reference
#include <Attrib.h>
Public Types
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
Attrib ()
Standard constructor.
virtual ~Attrib ()
Destructor.
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
std::string m_attribString [10]
Private Attributes
std::vector< int > m_attributs
Detailed Description
Define the attributs of objects. Define a basic set of attributs for class objects;
Author
Frédéric Machefert
Date
October 27, 2006
Definition at line 27 of file Attrib.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
Constructor & Destructor Documentation
Attrib()
Attrib::Attrib ()
Standard constructor.
Definition at line 31 of file Attrib.cpp.
References add(), m_attribString, m_attributs, and UNDEFINED.
                 {
  m_attribString[0] = std::string("UNDEFINED");
  m_attribString[1] = std::string("PASSIVE");
  m_attribString[2] = std::string("ACTIVE");
  m_attribString[3] = std::string("INTERFACE");
  m_attribString[4] = std::string("IO");
  m_attribString[5] = std::string("IODATA");
  m_attribString[6] = std::string("ELEMENT");
  m_attribString[7] = std::string("HARDWARE");
  m_attribString[8] = std::string("PROCESSUS");
  m_attribString[9] = std::string("SOFTWARE");
  m_attributs.clear();
  add(Attrib::UNDEFINED);
}
 Attrib()
Attrib::~Attrib () [virtual]
Destructor.
Definition at line 49 of file Attrib.cpp.
{}
Member Function Documentation
add()
void Attrib::add (int attribut) [inline]
Add an attribut
Definition at line 67 of file Attrib.h.
References m_attributs, and UNDEFINED.
Referenced by A3PE::A3PE(), Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), FePGA::init(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), remove(), SeqPGA::SeqPGA(), TestSPI::setAddress(), TestI2C::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
attributs()
std::string Attrib::attributs ()
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, m_attribString, and m_attributs.
Referenced by export_obj(), and remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
is()
bool Attrib::is (int attribut) [inline]
Test for an attribut
Definition at line 50 of file Attrib.h.
References m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
remove()
void Attrib::remove (int attribut) [inline]
Remove an attribut
Definition at line 86 of file Attrib.h.
References add(), attributs(), m_attributs, and UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
Member Data Documentation
m_attribString
std::string Attrib::m_attribString[10] [protected]
Definition at line 105 of file Attrib.h.
Referenced by Attrib(), and attributs().
m_attributs
std::vector<int> Attrib::m_attributs [private]
Definition at line 108 of file Attrib.h.
Referenced by add(), Attrib(), attributs(), is(), and remove().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Attrib.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Attrib.cpp