DLLMgr Class Reference
#include <inc/DLLMgr.h>
Public Member Functions
DLLMgr ()
Standard constructor.
virtual ~DLLMgr ()
Destructor.
StatusCode load (std::string)
StatusCode unload (std::string)
DLL * dll (std::string)
std::vector< DLL * > dlls (std::string)
DLL * libraryOfObject (std::string)
Element * createElement (std::string)
StatusCode destroy (Element *)
Processus * createProcessus (std::string)
StatusCode destroy (Processus *)
void print ()
Private Member Functions
void verbose (std::string msg)
void debug (std::string msg)
void info (std::string msg)
void warning (std::string msg)
void fatal (std::string msg)
void verbose (std::string msg, std::string name)
void debug (std::string msg, std::string name)
void info (std::string msg, std::string name)
void warning (std::string msg, std::string name)
void fatal (std::string msg, std::string name)
Private Attributes
MsgSvc m_log
std::vector< DLL * > m_dlls
Detailed Description
Manager of the DLL for the Application
Author
Frederic Machefert
Date
2006-10-25
Definition at line 19 of file DLLMgr.h.
Constructor & Destructor Documentation
DLLMgr()
DLLMgr::DLLMgr ()
Standard constructor.
Definition at line 20 of file DLLMgr.cpp.
                 {
}
 DLLMgr()
DLLMgr::~DLLMgr () [virtual]
Destructor.
Definition at line 26 of file DLLMgr.cpp.
{}
Member Function Documentation
createElement()
Element * DLLMgr::createElement (std::string name)
Build an element from the manager
Definition at line 128 of file DLLMgr.cpp.
References DLL::createElement(), and libraryOfObject().
Referenced by Application::create(), dlls(), and export_base().
                                                {
  DLL* lib = libraryOfObject(name);
  if (0!=lib){
    return lib->createElement(name);
  }
  return NULL;
}
createProcessus()
Processus * DLLMgr::createProcessus (std::string name)
create a processus from the manager
Definition at line 139 of file DLLMgr.cpp.
References DLL::createProcessus(), and libraryOfObject().
Referenced by dlls(), and export_base().
                                                    {
  DLL* lib = libraryOfObject(name);
  if (0!=lib){
    return lib->createProcessus(name);
  }
  return NULL;
}
debug() [1/2]
void DLLMgr::debug (std::string msg) [inline], [private]
Definition at line 85 of file DLLMgr.h.
References MsgSvc::DEBUG, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , msg, std::string("DLL")); }
debug() [2/2]
void DLLMgr::debug (std::string msg, std::string name) [inline], [private]
Definition at line 91 of file DLLMgr.h.
References MsgSvc::DEBUG, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , msg, name); }
destroy() [1/2]
StatusCode DLLMgr::destroy (Element * element)
Delete an element from the manager
Definition at line 150 of file DLLMgr.cpp.
References DLL::destroy(), StatusCode::FAILURE, libraryOfObject(), StatusCode::SUCCESS, and Object::type().
Referenced by dlls(), and export_base().
                                              {
  DLL* mydll = libraryOfObject(element->type ());
  if (0 != mydll) {
    mydll->destroy(element);
    return StatusCode::SUCCESS;
  }
  return StatusCode::FAILURE;
}
destroy() [2/2]
StatusCode DLLMgr::destroy (Processus * proc)
Delete a processus from the manager
Definition at line 162 of file DLLMgr.cpp.
References DLL::destroy(), StatusCode::FAILURE, libraryOfObject(), StatusCode::SUCCESS, and Object::type().
                                             {
  DLL* mydll = libraryOfObject(proc->type());
  if (0 != mydll) {
    mydll->destroy(proc);
    return StatusCode::SUCCESS;
  }
  return StatusCode::FAILURE;
}
dll()
DLL * DLLMgr::dll (std::string lib)
find dll objects from its name
Definition at line 113 of file DLLMgr.cpp.
References m_dlls.
Referenced by export_base(), and load().
                                 {
  std::vector<DLL*>::const_iterator iter ;
  for (iter = m_dlls.begin() ;
        iter != m_dlls.end() ;
        ++iter) {
    if (0==lib.compare((*iter)->name())){
      return (*iter);
    }
  }
  return NULL;
}
dlls()
std::vector<DLL*> DLLMgr::dlls (std::string) [inline]
find dll objects from its name
Definition at line 45 of file DLLMgr.h.
References createElement(), createProcessus(), destroy(), libraryOfObject(), m_dlls, and print().
Referenced by export_base().
  {
    return m_dlls;
  }
fatal() [1/2]
void DLLMgr::fatal (std::string msg) [inline], [private]
Definition at line 88 of file DLLMgr.h.
References MsgSvc::FATAL, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , msg, std::string("DLL")); }
fatal() [2/2]
void DLLMgr::fatal (std::string msg, std::string name) [inline], [private]
Definition at line 94 of file DLLMgr.h.
References MsgSvc::FATAL, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , msg, name); }
info() [1/2]
void DLLMgr::info (std::string msg) [inline], [private]
Definition at line 86 of file DLLMgr.h.
References MsgSvc::INFO, and MsgSvc::msgSvc().
Referenced by load().
{ m_log.msgSvc (MsgSvc::INFO , msg, std::string("DLL")); }
info() [2/2]
void DLLMgr::info (std::string msg, std::string name) [inline], [private]
Definition at line 92 of file DLLMgr.h.
References MsgSvc::INFO, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , msg, name); }
libraryOfObject()
DLL * DLLMgr::libraryOfObject (std::string obj)
find DLL which contains objects type
Definition at line 98 of file DLLMgr.cpp.
References m_dlls.
Referenced by createElement(), createProcessus(), destroy(), dlls(), and export_base().
                                             {
  std::vector<DLL*>::const_iterator iter ;
  for (iter = m_dlls.begin() ;
        iter != m_dlls.end() ;
        ++iter) {
    if ((*iter)->containsObject(obj)){
      return (*iter);
    }
  }
  return NULL;
}
load()
StatusCode DLLMgr::load (std::string library)
load a DLL and stores its entry point
Definition at line 32 of file DLLMgr.cpp.
References dll(), StatusCode::FAILURE, info(), StatusCode::isSuccess(), DLL::load(), m_dlls, DLL::objectList(), StatusCode::SUCCESS, and warning().
Referenced by export_base().
                                            {
  // load library
  info("Loading dll "+library+".","DLLMgr::load");
  DLL *mydll = new DLL ();
  // look if we can load the library
  if (mydll->load (library).isSuccess()){
    info("Library "+library+" loaded.");
    // look for duplication of library
    if (0!=dll(library)){
      warning("DLL "+library+" already loaded. Cannot load library.","DLLMgr::loadDLL");
      delete mydll;
      return StatusCode::FAILURE;
    }
    // look for duplication of objects
    std::vector<std::string> list = mydll->objectList();
    std::vector<DLL*>::const_iterator iter ;
    std::vector<std::string>::const_iterator objs ;
    for (objs=list.begin() ;
          objs!=list.end() ;
          ++objs) {
      for (iter = m_dlls.begin() ;
            iter != m_dlls.end() ;
            ++iter) {
        if ((*iter)->containsObject(*objs)){
          warning("The DLL "+library+" contains an object ("+
                 (*objs) +" which has already been loaded from "+
                 (*iter)->name()+". Cannot load library.",
          "DLLMgr::loadDLL");
          delete mydll;
          return StatusCode::FAILURE;
        }
      }
    }
     // everything is ok. definitely keep the new library in the manager
     m_dlls.push_back (mydll);
     return StatusCode::SUCCESS;
   }
   // could not even find the library
   warning("The DLL "+library+" could not be properly loaded.","DLLMgr::loadDLL");
   delete mydll;
   return StatusCode::FAILURE;
}
print()
void DLLMgr::print ()
Definition at line 174 of file DLLMgr.cpp.
References m_dlls.
Referenced by dlls(), and export_base().
{
  std::vector<DLL*>::iterator iter ;
  for (iter = m_dlls.begin() ;
        iter != m_dlls.end() ;
        ++iter) {(*iter)->print();}
}
unload()
StatusCode DLLMgr::unload (std::string lib)
unload a DLL and removes its entry point from the list
Definition at line 79 of file DLLMgr.cpp.
References m_dlls.
Referenced by export_base().
                                          {
  std::vector<DLL*>::iterator dlltoremove;
  std::vector<DLL*>::iterator iter ;
  for (iter = m_dlls.begin() ;
        iter != m_dlls.end() ;
        ++iter) {
    if (0==lib.compare((*iter)->name())) {
      (*iter)->unload();
      dlltoremove = iter;
    }
    delete *dlltoremove;
    m_dlls.erase(dlltoremove);
  }
  return NULL;
}
verbose() [1/2]
void DLLMgr::verbose (std::string msg) [inline], [private]
Definition at line 84 of file DLLMgr.h.
References MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , msg, std::string("DLL")); }
verbose() [2/2]
void DLLMgr::verbose (std::string msg, std::string name) [inline], [private]
Definition at line 90 of file DLLMgr.h.
References MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , msg, name); }
warning() [1/2]
void DLLMgr::warning (std::string msg) [inline], [private]
Definition at line 87 of file DLLMgr.h.
References MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by load().
{ m_log.msgSvc (MsgSvc::WARNING , msg, std::string("DLL")); }
warning() [2/2]
void DLLMgr::warning (std::string msg, std::string name) [inline], [private]
Definition at line 93 of file DLLMgr.h.
References MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , msg, name); }
Member Data Documentation
m_dlls
std::vector<DLL*> DLLMgr::m_dlls [private]
Definition at line 96 of file DLLMgr.h.
Referenced by dll(), dlls(), libraryOfObject(), load(), print(), and unload().
m_log
MsgSvc DLLMgr::m_log [private]
Definition at line 82 of file DLLMgr.h.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/DLLMgr.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/DLLMgr.cpp