SpecsSlave Class Reference
#include <SpecsSlave.h>
Public Member Functions
SpecsSlave ()
~SpecsSlave ()
void addI2c (Hierarchy *)
void setAddress (unsigned char)
SPECSSLAVE * specsSlaveDevice ()
bool detect ()
StatusCode init ()
void recursiveInitCommunications ()
void resetInternal ()
void reset ()
Protected Attributes
SpecsI2c * i2c
Private Attributes
SPECSSLAVE specsSlave
Additional Inherited Members
Detailed Description
Definition at line 21 of file SpecsSlave.h.
Constructor & Destructor Documentation
SpecsSlave()
SpecsSlave::SpecsSlave ()
Definition at line 32 of file SpecsSlave.cpp.
References Attrib::add(), Object::debug(), Attrib::ELEMENT, Attrib::HARDWARE, setAddress(), Object::setId(), and Object::setType().
                      {
  debug("SpecsSlave built.","SpecsSlave::SpecsSlave");
  setAddress(0x0);
  setType("SpecsSlave");
  setId(0);
  add(Attrib::ELEMENT); add (Attrib::HARDWARE);
}
 SpecsSlave()
SpecsSlave::~SpecsSlave ()
Definition at line 44 of file SpecsSlave.cpp.
                       {
}
Member Function Documentation
addI2c()
void SpecsSlave::addI2c (Hierarchy * element)
Definition at line 175 of file SpecsSlave.cpp.
References Hierarchy::addChild(), Object::debug(), i2c, Object::name(), and Hierarchy::setParent().
Referenced by BOOST_PYTHON_MODULE(), and SpecsMezzanine::SpecsMezzanine().
                                         {
  element->setParent(i2c);
  i2c->addChild(element);
  debug(element->name()+" added to the i2c child tree.","SpecsSlave::addI2c");
}
detect()
bool SpecsSlave::detect ()
Detect connection with the SpecsSlave by trying a register read
detect a SpecsSlave at a certain address
Parameters
add address of the specs slave looked at
Definition at line 119 of file SpecsSlave.cpp.
References SpecsInterface::address(), Object::debug(), Object::info(), itos(), Object::name(), SpecsMaster::reset(), SpecsInterface::specsMaster(), SpecsInterface::specsMasterDevice(), SpecsInterface::specsSlave(), specsSlaveDevice(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE().
                        {
#ifndef _NODEVICE_
  SPECSMASTER* master=specsMasterDevice();
  if (0!=master){
    SpecsError status = specs_slave_open (master, address() , &
      specsSlave);
    if (0!=status){
      info("SpecsSlave "+name()+"could not be initialized correctly [code:"+
           itos(status) + "].","initSpecs");
      return false;
    }
    else{
      SPECSSLAVE *specsSlv=specsSlaveDevice();
      if (0==specsSlv){
        warning("Could not reach proper Specs Master and/or Slave.",
                "SpecsElement::specsWriteI2c");
        return false;
      }
      
      U16 value ;
      U8 reg = 8 ;
      status = specs_register_read (specsSlv , reg , &value);
      
      if (0!=status){
        debug("No SpecsSlave detected at address " +
              itos (address()) + "[code=" + itos(status) + "]",
              "specsSlave::detect");
        specsMaster()->reset();
        return false;
      }
      else {
        info("SpecsSlave detected at address " +
             itos (address()) + "[date=" + itos(value)+"]",
             "specsSlave::detect");
        return true;
      }
    }
  }
#endif
  return false;
}
init()
StatusCode SpecsSlave::init () [virtual]
init the component
Returns
void
Reimplemented from SpecsInterface.
Definition at line 69 of file SpecsSlave.cpp.
References SpecsInterface::address(), Object::debug(), StatusCode::FAILURE, Object::fatal(), Object::info(), itos(), Object::name(), reset(), resetInternal(), SpecsInterface::specsMasterDevice(), SpecsInterface::specsSlave(), StatusCode::SUCCESS, and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), and recursiveInitCommunications().
                           {
#ifndef _NODEVICE_
  SPECSMASTER* master=specsMasterDevice();
  if (0!=master){
    SpecsError status = specs_slave_open (master, address() , &
      specsSlave);
    if (0!=status){
      warning("SpecsSlave " + name() + "could not be initialized correctly [code:" +
              itos(status) + "].","SpecsSlave::initSpecs");
      return StatusCode::FAILURE;
    }
    else{
      int nAttempts = 10;
      for (int i=0 ; i<nAttempts ; ++i){
        U16 rd;
        U16 wr = (U16)(rand()&&0xFFFC);
        // specsWriteRegister(3,wr);
        // specsReadRegister (3,rd);
        rd=wr;
        if (wr!=rd){
          warning("Specs Slave "+name()+" [Add="+itos (address())+"] : wrong
       connection [attempt "+
                  itos(i)+"/"+itos (nAttempts)+"]. Further use of this slave is hazardeous.",
                  "SpecsSlave::init");
          return StatusCode::FAILURE;
        }
      }
      info("SpecsSlave "+name()+" initialized and connected to master.","SpecsSlave::init");
    }
  }
  else{
    fatal("Could not initialize SpecsSlave "+name()+".","SpecsSlave::init");
    return StatusCode::FAILURE;
  }
#else
  debug("Compilation in the _NODEVICE_ mode.","SpecsSlave::init");
#endif
  resetInternal();
  reset();
  return StatusCode::SUCCESS;
}
recursiveInitCommunications()
void SpecsSlave::recursiveInitCommunications ()
Definition at line 163 of file SpecsSlave.cpp.
References Hierarchy::children(), and init().
                                            {
  init();
  std::vector<Hierarchy*> list = this->children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter){
    dynamic_cast<Element*>((*iter))->recursiveInitCommunications();
  }
}
reset()
void SpecsSlave::reset () [virtual]
External Reset of the Slave
Reimplemented from SpecsInterface.
Definition at line 204 of file SpecsSlave.cpp.
References SpecsInterface::address(), Object::debug(), itos(), Object::name(), specsSlaveDevice(), and Object::warning().
Referenced by SpecsMezzanine::cmdline(), and init().
                      {
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  SpecsError status = specs_slave_external_reset (specsSlv);
  if (0!=status){
    warning("SpecsSlave " + name() +
            ": failure in performing the SpecsSlave reset [code:" +
            itos(status) + "].",
            "SpecsSlave::reset"); }
  else{
    debug("reset of the specs slave "+
          name()+" "+" [address="+itos(address())+"]." ,
          "SpecsSlave::reset");
  }
#endif
}
resetInternal()
void SpecsSlave::resetInternal ()
Internal Reset of the Slave
Definition at line 184 of file SpecsSlave.cpp.
References SpecsInterface::address(), Object::info(), itos(), Object::name(), specsSlaveDevice(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), SpecsMezzanine::cmdline(), and init().
                              {
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  SpecsError status = specs_slave_internal_reset (specsSlv);
  if (0!=status){
    warning("SpecsSlave " + name() +
            ": failure in performing the internal reset [code:" +
            itos(status) + "].",
            "SpecsSlave::reset"); }
  else{
    info("internal reset of the specs slave "+
         name()+" "+" [address="+itos(address())+"].",
         "SpecsSlave::resetInternal");
  }
#endif
}
setAddress()
void SpecsSlave::setAddress (unsigned char add)
Definition at line 50 of file SpecsSlave.cpp.
References Attrib::add(), SpecsInterface::m_address, and SpecsInterface::specsSlave().
Referenced by BOOST_PYTHON_MODULE(), SpecsMezzanine::cmdline(), SpecsGlue::SpecsGlue(), SpecsMezzanine::SpecsMezzanine(), and SpecsSlave().
                                            {
  m_address=add;
#ifndef _NODEVICE_
  specsSlave.SpecsslaveAdd=add;
#endif
}
specsSlaveDevice()
SPECSSLAVE * SpecsSlave::specsSlaveDevice () [virtual]
Get the closest slave in the element hierarchy
Returns
SPECSSLAVE*
Reimplemented from SpecsInterface.
Definition at line 61 of file SpecsSlave.cpp.
References SpecsInterface::specsSlave().
Referenced by detect(), reset(), and resetInternal().
                                        {
  return &specsSlave;
}
Member Data Documentation
i2c
SpecsI2c* SpecsSlave::i2c [protected]
Definition at line 28 of file SpecsSlave.h.
Referenced by addI2c().
specsSlave
SPECSSLAVE SpecsSlave::specsSlave [private]
Definition at line 24 of file SpecsSlave.h.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/inc/SpecsSlave.h
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/src/SpecsSlave.cpp