Phaser Class Reference
#include <Phaser.h>
Public Types
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
Public Member Functions
Phaser ()
~Phaser ()
void setPhase (unsigned char channel, unsigned char value)
void setPhase (unsigned char ch0, unsigned char ch1, unsigned char ch2, unsigned char ch3)
unsigned int phase (unsigned int ch)
void read ()
void write ()
void help ()
StatusCode init ()
void reset ()
void update ()
Register * reg ()
Private Attributes
unsigned char m_address
unsigned char m_phase [4]
Register * m_reg
Additional Inherited Members
Detailed Description
Definition at line 19 of file Phaser.h.
Member Typedef Documentation
U16
typedef unsigned short Phaser::U16
Definition at line 22 of file Phaser.h.
U32
typedef unsigned long Phaser::U32
Definition at line 21 of file Phaser.h.
U8
typedef unsigned char Phaser::U8
Definition at line 23 of file Phaser.h.
Constructor & Destructor Documentation
Phaser()
Phaser::Phaser () [inline]
Definition at line 24 of file Phaser.h.
References Attrib::add(), Hierarchy::addChild(), Object::debug(), IOdata::defDataU8(), Attrib::ELEMENT, Attrib::HARDWARE, IOobject::io(), m_phase, m_reg, Object::setId(), and Object::setType().
          {
    setType("Phaser");
    setId(0);
    add(Attrib::ELEMENT); add (Attrib::HARDWARE);
    debug("Phaser built.","Phaser::Phaser");
    m_phase[0]=99;
    m_phase[1]=99;
    m_phase[2]=99;
    m_phase[3]=99;
    m_reg=new Register();
    m_reg->io()->defDataU8(3);
    addChild(m_reg);
  }
 Phaser()
Phaser::~Phaser () [inline]
Definition at line 38 of file Phaser.h.
           {
// delete m_reg;
  }
Member Function Documentation
help()
void Phaser::help () [inline], [virtual]
printout help for the element
Implements Element.
Definition at line 74 of file Phaser.h.
References Object::info(), and Object::name().
{ info("Phaser "+name()+". No help.","Phaser::help"); };
init()
StatusCode Phaser::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 80 of file Phaser.h.
References StatusCode::SUCCESS.
                    {
    return StatusCode::SUCCESS;
  };
phase()
unsigned int Phaser::phase (unsigned int ch) [inline]
Definition at line 63 of file Phaser.h.
References m_phase, read(), and write().
Referenced by BOOST_PYTHON_MODULE(), PhaserRampExec::execute(), and PhaserRampExec::initialize().
                                     {
    read() ;
    return m_phase[ch];
  }
read()
void Phaser::read ()
Definition at line 23 of file Phaser.cpp.
References IOdata::dataU8(), Object::debug(), IOobject::io(), StatusCode::isFailure(), itos(), m_phase, m_reg, Object::name(), IOobject::read(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), PhaserRampExec::execute(), PhaserRampExec::initialize(), phase(), and update().
                  {
  if (m_reg->read().isFailure()){
    warning("Phaser register read failure.","Phaser::read");
  }
  else {
    U8* buffer=m_reg->io()->dataU8();
    unsigned int d0 = (buffer[0] & 0x1F);
    unsigned int d1 = ((buffer[0] & 0xE0) >> 5) | ((buffer[1] & 0x3) << 3);
    unsigned int d2 = ((buffer[1] >> 2) & 0x1F);
    unsigned int d3 = ((buffer[1] >> 7) & 0x1) | ((buffer[2] & 0xF) << 1);
    debug("reading "+name()+" phases : "+
        itos(d0)+" "+
        itos(d1)+" "+
        itos(d2)+" "+
        itos(d3),
        "Phaser::read");
    m_phase[0]=d0;
    m_phase[1]=d1;
    m_phase[2]=d2;
    m_phase[3]=d3;
  }
}
reg()
Register* Phaser::reg () [inline]
Definition at line 101 of file Phaser.h.
References m_reg.
Referenced by BOOST_PYTHON_MODULE(), and Proto40MHz_v1::Proto40MHz_v1().
                 {
    return m_reg;
  }
reset()
void Phaser::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 91 of file Phaser.h.
               {
  };
setPhase() [1/2]
void Phaser::setPhase (unsigned char channel, unsigned char value) [inline]
Definition at line 42 of file Phaser.h.
References Object::info(), itos(), m_phase, and write().
Referenced by BOOST_PYTHON_MODULE(), PhaserRampExec::execute(), and PhaserRampExec::finalize().
                                                           {
    info("Set Phase "+itos(channel)+" to "+itos(value),"Phaser::setPhase");
    m_phase[channel]=value;
    write();
  }
setPhase() [2/2]
void Phaser::setPhase (unsigned char ch0, unsigned char ch1, unsigned char ch2, unsigned char ch3) [inline]
Definition at line 48 of file Phaser.h.
References Object::info(), itos(), m_phase, and write().
       {
    m_phase[0]=ch0;
    m_phase[1]=ch1;
    m_phase[2]=ch2;
    m_phase[3]=ch3;
    info("Set Phases to "+itos(ch0)+" "+itos(ch1)+" "
        +itos(ch2)+" "+itos(ch3));
    write();
  }
update()
void Phaser::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 97 of file Phaser.h.
References read().
Referenced by A3PE_BitFlip.A3PE_BitFlip::__init__(), Acquisition.Acquisition::__init__(), EmulateFE.EmulateFE::__init__(), AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
                 {
    read();
  };
write()
void Phaser::write ()
Definition at line 46 of file Phaser.cpp.
References IOdata::dataU8(), Object::debug(), IOobject::io(), StatusCode::isFailure(), itos(), m_phase, m_reg, Object::name(), Object::warning(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), PhaserRampExec::execute(), PhaserRampExec::finalize(), phase(), and setPhase().
                  {
  U8* buffer=m_reg->io()->dataU8();
  buffer[0]=(m_phase[0] & 0x1F) | ((m_phase[1] & 0x7)<<5);
  buffer[1]=((m_phase[1]>>3)& 0x3) |
      ((m_phase[2]& 0x1F)<<2) |
      ((m_phase[3]&0x1)<<7);
  buffer[2]=(m_phase[3]>>1)&0xF;
  debug("setting "+name()+" phases : "+itos(m_phase[0])+" "+
      itos(m_phase[1])+" "+itos(m_phase[2])+" "+itos(
      m_phase[3]),
      "Phaser::write");
  if (m_reg->write().isFailure()){
    warning("Phaser register write failure.","Phaser::write");
  }
}
Member Data Documentation
m_address
unsigned char Phaser::m_address [private]
Definition at line 106 of file Phaser.h.
m_phase
unsigned char Phaser::m_phase[4] [private]
Definition at line 107 of file Phaser.h.
Referenced by phase(), Phaser(), read(), setPhase(), and write().
m_reg
Register* Phaser::m_reg [private]
Definition at line 108 of file Phaser.h.
Referenced by Phaser(), read(), reg(), and write().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCalo/inc/Phaser.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCalo/src/Phaser.cpp