Histo2D Class Reference
#include <Histo2D.h>Inheritance diagram for Histo2D::
Public Types
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
Histo2D (TH2D *histo)
~Histo2D ()
double minX ()
double maxX ()
double minY ()
double maxY ()
double minZ ()
double maxZ ()
std::vector< double > bins ()
std::vector< double > xbins ()
std::vector< double > ybins ()
unsigned long nxbins ()
unsigned long nybins ()
void statistics (double &, double &, double &)
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
std::string m_attribString [10]
Private Attributes
double m_zero
double m_infini
unsigned long m_nxbins
unsigned long m_nybins
std::vector< double > m_bins
std::vector< double > m_xcenters
std::vector< double > m_ycenters
double m_minX
double m_maxX
double m_minY
double m_maxY
double m_minZ
double m_maxZ
double m_overflow
double m_underflow
double m_content
double m_mean
double m_rms
Detailed Description
Definition at line 28 of file Histo2D.h.
Member Enumeration Documentation
enum Attrib::Attribut [inherited]
Enumerator:
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  ; // array m_attribString must be changed into Attrib::Attrib if this enu is m
      odified.
Constructor & Destructor Documentation
Histo2D::Histo2D (TH2D * histo)
Definition at line 22 of file Histo2D.cpp.
References m_bins, m_content, m_maxX, m_maxY, m_maxZ, m_mean, m_minX, m_minY, m_minZ, m_nxbins, m_nybins, m_rms, m_xcenters, m_ycenters, and Object::setTitle().
                              : m_zero (1.e-30) , m_infini(1.e30)
  //m_histo = histo;
  
  m_nxbins = histo->GetNbinsX();
  m_nybins = histo->GetNbinsY();
  setTitle(std::string(histo -> GetTitle()));
  
  m_minX = histo->GetXaxis()->GetXmin();
  m_maxX = histo->GetXaxis()->GetXmax();
  m_minY = histo->GetYaxis()->GetXmin();
  m_maxY = histo->GetYaxis()->GetXmax();
  m_minZ = histo->GetMinimum();
  m_maxZ = histo->GetMaximum();
  unsigned long nxbin=0;
  unsigned long nybin=0;
  for (nybin=0;nxbin<m_nybins; ++nybin)
    /*
      std::vector<double> tmpbins;
      std::vector<double> tmpxbin;
      std::vector<double> tmpybin;
    */
    for (nxbin=0;nxbin<m_nxbins; ++nxbin)
      m_bins.push_back(histo->GetBinContent(nybin*nxbin+1+2*(nybin-1)));
      m_xcenters.push_back(histo->GetXaxis()->GetBinCenter(nxbin+1));
      m_ycenters.push_back(histo->GetYaxis()->GetBinCenter(nybin+1));
    
    /*
      m_bins.push_back(tmpbins);
      m_xcenters.push_back(tmpxbin);
      m_ycenters.push_back(tmpybin);
    */
  
  
  /*
  m_underflow = histo->GetBinContent(0);
  m_overflow = histo->GetBinContent(histo->GetNbinsX()+1);
  */
  m_content = histo->GetEntries();
  m_mean = histo->GetMean();
  m_rms = histo->GetRMS();
Histo2D::~Histo2D () [inline]
Definition at line 31 of file Histo2D.h.
Member Function Documentation
void Attrib::add (int attribut) [inline, inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        duplicate = true ;
      
    
    if (!duplicate)
      m_attributs.push_back(attribut);
    
  
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj().
                            
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++index)
    if (m_attributs.size() - index > 1)
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    
    else
      output.append(m_attribString[m_attributs[index]]);
    
  
  return output;
std::vector<double> Histo2D::bins () [inline]
Definition at line 72 of file Histo2D.h.
References m_bins.
Referenced by export_proc().
                          
    return m_bins;
  
void Object::debug (std::string mymsg, std::string name) [inline, inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::DEBUG , mymsg, name);
void Object::debug (std::string mymsg) [inline, inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::checkConfigAddr(), LSDelayChipV1::checkStatusAddr(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), EmulateFE::execute(), StorageFifoAcquisition::execute(), StorageFifo::execute(), Acquisition::execute(), A3PE_BitFlip::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), SeqPGA::i2cRead(), FePGA::i2cRead(), SeqPGA::i2cWrite(), FePGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), A3PE::internalAXSequence(), SpecsMezzanine::led(), SpecsGlue::led(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), ICPhaser::read(), Phaser::read(), FEB_v1::readFifoSpyFE(), SpecsSlave::reset(), SpecsMaster::reset(), FEB_v1::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::resetFifoSpyFE(), SeqPGA::resetSpi(), FEB_v1::resetSpi(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsMezzanine::setLed(), SpecsGlue::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), FEB_v1::testDuration(), SeqPGA::testSequence(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), ICPhaser::write(), Phaser::write(), and Hierarchy::~Hierarchy().
 m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name);
std::string Object::dllName () [inline, inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj().
                       
    return m_dllName;
  
void Object::error (std::string mymsg, std::string name) [inline, inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::ERR , mymsg, name);
void Object::error (std::string mymsg) [inline, inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by ICECALv3::checkChNumber(), A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), SpecsMaster::init(), NI6008::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTMLInterface::read(), UsbFTInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
 m_log.msgSvc (MsgSvc::ERR , mymsg, m_name);
void Object::fatal (std::string mymsg, std::string name) [inline, inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::FATAL , mymsg, name);
void Object::fatal (std::string mymsg) [inline, inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), SpecsSlave::init(), UsbSpiBus::init(), UsbI2cBus::init(), IOobject::init(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
 m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name);
unsigned char Object::id () [inline, inherited]
Reimplemented in MSOxxxx.
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj().
 return m_id; //< Get Object m_id
void Object::info (std::string mymsg, std::string name) [inline, inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::INFO , mymsg, name);
void Object::info (std::string mymsg) [inline, inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), ICECALv3::bxidResynchStatus(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTMLInterface::close(), UsbFTInterface::close(), MSOxxxx::closeConnection(), Processus::closeRootFile(), SpecsMezzanine::cmdline(), Server::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), SpecsMezzanine::help(), SpecsMaster::help(), SpecsGlue::help(), SpecsParallelBus::help(), SpecsInterface::help(), NI6008::help(), Computer::help(), UsbSpiBus::help(), UsbI2cBus::help(), RAM::help(), IOobject::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbFTMLInterface::help(), SeqPGA::help(), ICPhaser::help(), FePGA::help(), FEB_v1::help(), CU_v1::help(), UsbFTInterface::help(), Proto40MHz_v1::help(), A3PE::help(), Phaser::help(), Croc::help(), MSOxxxx::help(), LSDelayChipV1::help(), ICECALv3::help(), MSOxxxx::id(), SpecsSlave::init(), SpecsMaster::init(), SpecsParallelBus::init(), SpecsInterface::init(), NI6008::init(), Computer::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), Croc::init(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), SpecsMaster::reset(), SpecsParallelBus::reset(), SpecsInterface::reset(), NI6008::reset(), Computer::reset(), UsbSpiBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbMLI2cBus::reset(), UsbFTMLInterface::reset(), SeqPGA::reset(), FePGA::reset(), UsbFTInterface::reset(), A3PE::reset(), Croc::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), ICPhaser::setPhase(), Phaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), SpecsParallelBus::update(), SpecsInterface::update(), NI6008::update(), Computer::update(), UsbSpiBus::update(), UsbI2cBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), UsbFTMLInterface::update(), FEB_v1::update(), CU_v1::update(), UsbFTInterface::update(), Proto40MHz_v1::update(), Croc::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), ICECALv3::version(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
 m_log.msgSvc (MsgSvc::INFO , mymsg, m_name);
bool Attrib::is (int attribut) [inline, inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        return true;
      
    
    return false;
  
double Histo2D::maxX () [inline]
Definition at line 39 of file Histo2D.h.
References m_maxX.
Referenced by export_proc().
               
    return m_maxX;
  
double Histo2D::maxY () [inline]
Definition at line 47 of file Histo2D.h.
References m_maxY.
Referenced by export_proc().
               
    return m_maxY;
  
double Histo2D::maxZ () [inline]
Definition at line 55 of file Histo2D.h.
References m_maxZ.
Referenced by export_proc().
               
    return m_maxZ;
  
double Histo2D::minX () [inline]
Definition at line 35 of file Histo2D.h.
References m_minX.
Referenced by export_proc().
               
    return m_minX;
  
double Histo2D::minY () [inline]
Definition at line 43 of file Histo2D.h.
References m_minY.
Referenced by export_proc().
               
    return m_minY;
  
double Histo2D::minZ () [inline]
Definition at line 51 of file Histo2D.h.
References m_minZ.
Referenced by export_proc().
               
    return m_minZ;
  
void Object::msg (std::string mymsg, std::string name) [inline, inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
 m_log.msgSvc (MsgSvc::NONE , mymsg, name);
void Object::msg (std::string mymsg) [inline, inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
 m_log.msgSvc (MsgSvc::NONE , mymsg, m_name);
void Object::msgSvc (int level, std::string msg, std::string name) [inline, inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), and Hierarchy::tree().
 m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg, name);
std::string Object::name () const [inline, inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), SpecsParallelBus::help(), SpecsInterface::help(), NI6008::help(), Computer::help(), UsbSpiBus::help(), UsbI2cBus::help(), RAM::help(), IOobject::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbFTMLInterface::help(), SeqPGA::help(), ICPhaser::help(), FePGA::help(), FEB_v1::help(), CU_v1::help(), UsbFTInterface::help(), Proto40MHz_v1::help(), A3PE::help(), Phaser::help(), Croc::help(), MSOxxxx::help(), LSDelayChipV1::help(), ICECALv3::help(), SpecsSlave::init(), SpecsMaster::init(), SpecsParallelBus::init(), SpecsInterface::init(), NI6008::init(), Computer::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), Croc::init(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), ICPhaser::read(), Phaser::read(), SpecsSlave::reset(), SpecsMaster::reset(), SpecsParallelBus::reset(), SpecsInterface::reset(), NI6008::reset(), Computer::reset(), UsbSpiBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbMLI2cBus::reset(), UsbFTMLInterface::reset(), FEB_v1::reset(), CU_v1::reset(), UsbFTInterface::reset(), Proto40MHz_v1::reset(), A3PE::reset(), Croc::reset(), SpecsSlave::resetInternal(), FEB_v1::resetSpi(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Processus::storage(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), SpecsParallelBus::update(), SpecsInterface::update(), NI6008::update(), Computer::update(), UsbSpiBus::update(), UsbI2cBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), UsbFTMLInterface::update(), FEB_v1::update(), CU_v1::update(), UsbFTInterface::update(), Proto40MHz_v1::update(), Croc::update(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), ICPhaser::write(), Phaser::write(), and Hierarchy::~Hierarchy().
 return m_name; //< Get Object m_name
unsigned long Histo2D::nxbins () [inline]
Definition at line 84 of file Histo2D.h.
References m_nxbins.
Referenced by export_proc().
                        
    return m_nxbins;
  
unsigned long Histo2D::nybins () [inline]
Definition at line 88 of file Histo2D.h.
References m_nybins.
Referenced by export_proc().
                        
    return m_nybins;
  
void Attrib::remove (int attribut) [inline, inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        toremove = iter;
      
    
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  
void Object::setDllName (std::string dllName) [inline, inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      
    m_dllName = dllName;
  
void Object::setId (unsigned char id) [inline, inherited]
Definition at line 53 of file Object.h.
References Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
 m_id = id ; //< Set Object m_id
void Object::setName (std::string name) [inline, inherited]
Definition at line 51 of file Object.h.
References Object::m_name.
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), FePGA::MakeRAM(), FePGA::MakeRegister(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
 m_name = name ; //< Set Object m_name
void Object::setTitle (std::string title) [inline, inherited]
Definition at line 54 of file Object.h.
References Object::m_title.
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
 m_title = title ; //< Set Object m_title
void Object::setType (std::string type) [inline, inherited]
Definition at line 52 of file Object.h.
References Object::m_type.
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
 m_type = type ; //< Set Object m_type
void Histo2D::statistics (double & content, double & mean, double & rms)
Definition at line 77 of file Histo2D.cpp.
References m_content, m_mean, and m_rms.
                                     
  content=m_content;
  mean =m_mean;
  rms =m_rms;
std::string Object::title () [inline, inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), and Application::terminate().
 return m_title; // < Get Object m_title
std::string Object::type () [inline, inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbSpiBus::init(), UsbI2cBus::init(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), and Hierarchy::tree().
 return m_type; //< Get Object m_type
void Object::verbose (std::string mymsg, std::string name) [inline, inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
 m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name);
void Object::verbose (std::string mymsg) [inline, inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTMLInterface::read(), UsbFTInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), wait(), UsbFTMLInterface::write(), and UsbFTInterface::write().
 m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name);
void Object::warning (std::string mymsg, std::string name) [inline, inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
 m_log.msgSvc (MsgSvc::WARNING , mymsg, name);
void Object::warning (std::string mymsg) [inline, inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), Processus::clean(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsMezzanine::date(), SpecsGlue::date(), SpecsSlave::detect(), NI6008::device(), UsbFTInterfaceTest::execute(), Acquisition::execute(), A3PE_BitFlip::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), SpecsSlave::init(), DCU::init(), TestUSB::initialize(), TestSPI::initialize(), TestI2C::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), SpecsMezzanine::led(), SpecsGlue::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbSpiBus::read(), UsbI2cBus::read(), ICPhaser::read(), Phaser::read(), DCU::readMode(), SpecsSlave::reset(), SpecsMaster::reset(), DCU::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbSpiBus::write(), UsbI2cBus::write(), ICPhaser::write(), Phaser::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
 m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name);
std::vector<double> Histo2D::xbins () [inline]
Definition at line 76 of file Histo2D.h.
References m_xcenters.
Referenced by export_proc().
                           
    return m_xcenters;
  
std::vector<double> Histo2D::ybins () [inline]
Definition at line 80 of file Histo2D.h.
References m_ycenters.
Referenced by export_proc().
                           
    return m_ycenters;
  
Member Data Documentation
std::string Attrib::m_attribString[10] [protected, inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
std::vector<double> Histo2D::m_bins [private]
Definition at line 118 of file Histo2D.h.
Referenced by bins(), and Histo2D().
double Histo2D::m_content [private]
Definition at line 132 of file Histo2D.h.
Referenced by Histo2D(), and statistics().
double Histo2D::m_infini [private]
Definition at line 107 of file Histo2D.h.
double Histo2D::m_maxX [private]
Definition at line 123 of file Histo2D.h.
Referenced by Histo2D(), and maxX().
double Histo2D::m_maxY [private]
Definition at line 125 of file Histo2D.h.
Referenced by Histo2D(), and maxY().
double Histo2D::m_maxZ [private]
Definition at line 127 of file Histo2D.h.
Referenced by Histo2D(), and maxZ().
double Histo2D::m_mean [private]
Definition at line 133 of file Histo2D.h.
Referenced by Histo2D(), and statistics().
double Histo2D::m_minX [private]
Definition at line 122 of file Histo2D.h.
Referenced by Histo2D(), and minX().
double Histo2D::m_minY [private]
Definition at line 124 of file Histo2D.h.
Referenced by Histo2D(), and minY().
double Histo2D::m_minZ [private]
Definition at line 126 of file Histo2D.h.
Referenced by Histo2D(), and minZ().
unsigned long Histo2D::m_nxbins [private]
Definition at line 109 of file Histo2D.h.
Referenced by Histo2D(), and nxbins().
unsigned long Histo2D::m_nybins [private]
Definition at line 110 of file Histo2D.h.
Referenced by Histo2D(), and nybins().
double Histo2D::m_overflow [private]
Definition at line 129 of file Histo2D.h.
double Histo2D::m_rms [private]
Definition at line 134 of file Histo2D.h.
Referenced by Histo2D(), and statistics().
double Histo2D::m_underflow [private]
Definition at line 130 of file Histo2D.h.
std::vector<double> Histo2D::m_xcenters [private]
Definition at line 119 of file Histo2D.h.
Referenced by Histo2D(), and xbins().
std::vector<double> Histo2D::m_ycenters [private]
Definition at line 120 of file Histo2D.h.
Referenced by Histo2D(), and ybins().
double Histo2D::m_zero [private]
Definition at line 106 of file Histo2D.h.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Histo2D.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Histo2D.cpp