ADCMeasurement Class Reference
#include <include/ADCMeasurement.h>
Classes
class CurrentMeasurement
Public Types
enum states { ERR =-1,
NOT_OK,
OK
 }
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
ADCMeasurement ()
Standard constructor.
virtual ~ADCMeasurement ()
virtual StatusCode initialize ()
Destructor.
virtual StatusCode execute ()
virtual StatusCode finalize ()
StatusCode setFrequency (unsigned int frequency)
unsigned int frequency ()
unsigned int numberOfDevices ()
StatusCode startProcessing ()
StatusCode endProcessing ()
void clean ()
void setStorage (std::string storage)
Data * data ()
std::vector< double > data (unsigned int row)
std::vector< double > data (std::string name)
Histo1D * hist1d (unsigned int row)
Histo2D * hist2d (unsigned int row)
void addDataStream (std::string name, std::string title)
void addHisto1d (TH1D *h)
void addHisto2d (TH2D *h)
StatusCode dataFill (int i, double val)
StatusCode dataFill (std::string name, double val)
std::string storage ()
void setElement (Element *element)
Element * element ()
void incNErrors ()
void setNErrors (unsigned int)
unsigned int nErrors ()
TFile * rootFile ()
void openRootFile ()
void closeRootFile ()
void startChrono ()
void setLogMsg (std::string logMsg)
std::string logMsg ()
void setState (int state)
double elapsedTime ()
double elapsedTime (time_t start)
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Member Functions
ADCMeasurement * clone ()
Protected Attributes
Element * m_element
std::string m_attribString [10]
Private Attributes
TRandom * m_rnd
NI6008 * m_device
unsigned int m_frequency
TTree * m_tree
Int_t m_runNumber
Int_t m_evtNumber
Int_t m_timestamp
Int_t m_duration
time_t m_startTime
Float_t m_ai0
Float_t m_ai1
Float_t m_ao0
Float_t m_ao1
Int_t m_diA
Int_t m_diB
Float_t m_minRamp
Float_t m_maxRamp
Int_t m_stepRamp
Float_t m_ramp
Int_t m_baseline
Detailed Description
Author
Frederic Machefert
Date
2010-01-07
Definition at line 23 of file ADCMeasurement.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
states
enum Processus::states [inherited]
Enumerator
ERR
NOT_OK
OK
Definition at line 34 of file Processus.h.
{ ERR=-1 , NOT_OK , OK };
Constructor & Destructor Documentation
ADCMeasurement()
ADCMeasurement::ADCMeasurement ()
Standard constructor.
Definition at line 26 of file ADCMeasurement.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
                                {
  setName ("ADCMeasurement");
  setType ("NI6008");
  setTitle("NI6008 ADC measurement");
}
 ADCMeasurement()
virtual ADCMeasurement::~ADCMeasurement () [inline], [virtual]
Definition at line 28 of file ADCMeasurement.h.
References execute(), finalize(), and initialize().
{};
Member Function Documentation
add()
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), FePGA::init(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), TestI2C::setAddress(), TestSPI::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
addDataStream()
void Processus::addDataStream (std::string name, std::string title) [inline], [inherited]
Definition at line 153 of file Processus.h.
Referenced by RegisterTest::initialize(), TestSuite::initialize(), TestI2C::initialize(), TestSPI::initialize(), TestUSB::initialize(), UsbFTInterfaceTest::initialize(), initialize(), and CurrentMeasurement::initialize().
                                                       {
    m_data->addDataStream(name, title);
  }
addHisto1d()
void Processus::addHisto1d (TH1D * h) [inline], [inherited]
Definition at line 160 of file Processus.h.
Referenced by StorageFifo::initialize(), StorageFifoAcquisition::initialize(), TestSuite::initialize(), A3PE_BitFlip::initialize(), and Acquisition::initialize().
                           {
    m_data->addHisto1d(h);
  }
addHisto2d()
void Processus::addHisto2d (TH2D * h) [inline], [inherited]
Definition at line 167 of file Processus.h.
Referenced by TestSuite::initialize().
                           {
    m_data->addHisto2d(h);
  }
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
clean()
void Processus::clean () [inline], [inherited]
Definition at line 85 of file Processus.h.
Referenced by Application::prepare().
  {
    m_element=0;
    if (0!=m_state) {
      delete m_state;
      m_state=0;
    }
#ifdef _NETWORK_
    warning("Cleaning state service : should it be done ?","Processus::clean")
      if (0!=m_stateService)
      {
        delete m_stateService;
      }
#endif
  }
clone()
ADCMeasurement* ADCMeasurement::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 48 of file ADCMeasurement.h.
References ADCMeasurement().
                         {
    return new ADCMeasurement (*this);
  };
closeRootFile()
void Processus::closeRootFile () [inherited]
Close Root file if already opened and requested
Definition at line 160 of file Processus.cpp.
References Options::dataFileFullName(), Options::dataStorage(), Object::info(), Processus::m_options, and Processus::m_rootFile.
Referenced by Processus::endProcessing(), RegisterTest::finalize(), UsbFTInterfaceTest::finalize(), and PhaserRampExec::finalize().
                                {
  if (0!= m_rootFile && m_options->dataStorage()){
    m_rootFile->Write();
        std::string mess=std::string("Closing root file ");
        mess.append(m_options->dataFileFullName());
        info(mess,"closeRootFile");
    m_rootFile->Delete();
    m_rootFile = 0;
  }
}
data() [1/3]
Data* Processus::data () [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 114 of file Processus.h.
Referenced by StorageFifoAcquisition::execute(), and export_proc().
              {
    return m_data;
  }
data() [2/3]
std::vector<double> Processus::data (unsigned int row) [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 122 of file Processus.h.
                                          {
    return m_data->vector(row);
  }
data() [3/3]
std::vector<double> Processus::data (std::string name) [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 130 of file Processus.h.
                                        {
    return m_data->vector(name);
  }
dataFill() [1/2]
StatusCode Processus::dataFill (int i, double val) [inline], [inherited]
Set data stream with value
Returns
the StatusCode
Definition at line 175 of file Processus.h.
References StatusCode::FAILURE, and StatusCode::SUCCESS.
Referenced by TestSuite::execute(), TestI2C::execute(), TestUSB::execute(), TestSPI::execute(), UsbFTInterfaceTest::execute(), CurrentMeasurement::execute(), and execute().
                                        {
    if (m_data->vectorPtr(i)!=0){
      m_data->vectorPtr(i)->push_back(val);
      return StatusCode::SUCCESS;
    }
    else {
      return StatusCode::FAILURE;
    }
  }
dataFill() [2/2]
StatusCode Processus::dataFill (std::string name, double val) [inline], [inherited]
Set data stream with value
Returns
the StatusCode
Definition at line 189 of file Processus.h.
References StatusCode::FAILURE, and StatusCode::SUCCESS.
                                                 {
    int row=m_data->rowFromName(name);
    if (row<0) return StatusCode::FAILURE;
    if (m_data->vectorPtr(row)!=0){
      m_data->vectorPtr(row)->push_back(val);
      return StatusCode::SUCCESS;
    }
    else {
      return StatusCode::FAILURE;
    }
  }
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), A3PE::internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), FEB_v1::readFifoSpyFE(), CU_v1::reset(), FEB_v1::reset(), Proto40MHz_v1::reset(), SpecsSlave::reset(), SpecsMaster::reset(), FEB_v1::resetFifoSpyFE(), FEB_v1::resetSpi(), SeqPGA::resetSpi(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), FEB_v1::testDuration(), SeqPGA::testSequence(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
elapsedTime() [1/2]
double Processus::elapsedTime () [inline], [inherited]
Definition at line 340 of file Processus.h.
References ProcState::time.
Referenced by Processus::endProcessing(), UsbFTInterfaceTest::execute(), PhaserRampExec::finalize(), and Processus::setState().
                       {
    return difftime(time(0),m_start);
  }
elapsedTime() [2/2]
double Processus::elapsedTime (time_t start) [inline], [inherited]
Definition at line 343 of file Processus.h.
References ProcState::time.
                                   {
    return ((time(0)-start));
  }
element()
Element* Processus::element () [inline], [inherited]
Get accessor to member m_element
Returns
the current value of m_element
Definition at line 231 of file Processus.h.
Referenced by UsbFTInterfaceTest::execute(), export_proc(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), TestUSB::initialize(), EmulateFE::initialize(), TestI2C::initialize(), TestSPI::initialize(), CurrentMeasurement::initialize(), initialize(), and PhaserRampExec::initialize().
                      {
    return m_element;
  }
endProcessing()
StatusCode Processus::endProcessing () [inherited]
processus standard termination function
Definition at line 115 of file Processus.cpp.
References Data::buildHistos(), Processus::closeRootFile(), Processus::elapsedTime(), Data::empty(), Processus::finalize(), ftos(), Object::info(), itos(), Processus::m_data, Processus::m_options, Processus::nErrors(), Options::nErrors(), Options::nEvt(), Processus::NOT_OK, Data::print(), Options::runNumber(), and Processus::setState().
Referenced by export_proc(), and Application::terminate().
                                    {
  setState(NOT_OK);
  //
  info("--------------------------------------------------------------------------");
  info("Processed Run Number : " + itos (m_options->
      runNumber()) , "finalize");
  info("Number of events processed : " + itos (m_options->nEvt()) , "finalize");
  info("Number of Errors : " + itos (nErrors()) , "finalize");
  info("Number of App errors : " + itos (m_options->
      nErrors()) , "finalize");
  info("Elapsed time : " + ftos (elapsedTime()) , "finalize");
  info("--------------------------------------------------------------------------");
  if (!m_data->empty())
    m_data->print();
  else
    info("No data Stored.","finalize");
  info("--------------------------------------------------------------------------");
#ifdef _NETWORK_
  if (0 != m_timerService){
    m_timerService->setRunning (false);
  }
#endif
  StatusCode sc = finalize();
  m_data->buildHistos();
  closeRootFile();
  return sc;
}
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
execute()
StatusCode ADCMeasurement::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 73 of file ADCMeasurement.cpp.
References application(), NI6008::cmd(), Processus::dataFill(), m_ai0, m_ai1, m_ao0, m_baseline, m_device, m_diA, m_diB, m_duration, m_evtNumber, m_frequency, m_maxRamp, m_minRamp, m_ramp, m_startTime, m_stepRamp, m_timestamp, m_tree, Options::nEvt(), Application::options(), StatusCode::SUCCESS, and wait().
Referenced by ~ADCMeasurement().
                                     {
  // get current
  std::string val = m_device->cmd("Dev1", "ai");
  std::istringstream sv1(val);
  std::string v0, v1, tmp;
  sv1 >> v0;
  sv1 >> v1;
  // m_ai0=toDouble(v0);
  // m_ai1=toDouble(v1);
  m_ai0 = atof(v0.c_str());
  m_ai1 = atof(v1.c_str());
  std::cout << v0 << " " << v1 << " " << m_ai0 << " " << m_ai1 << std::endl;
  dataFill(1, m_ai0);
  dataFill(2, m_ai1);
  // set ramp value and channel A
  dataFill(3, m_ramp);
  m_ao0 = m_ramp;
  char cmd[80];
  sprintf(cmd,"ao %f %f", m_ramp, 0.);
  m_device->cmd("Dev1", cmd);
  val = m_device->cmd("Dev1", "di");
  std::istringstream sv2(val);
  sv2 >> tmp;
  sv2 >> tmp;
  sv2 >> tmp;
  sv2 >> v0 >> tmp >> v1 ;
  m_diA = atoi(v0.c_str());
  dataFill(4, m_diA);
  sprintf(cmd,"ao %f %f", m_ramp, 3.3);
  m_device->cmd("Dev1", cmd);
  val = m_device->cmd("Dev1", "di");
  std::istringstream sv3(val);
  sv3 >> tmp;
  sv3 >> tmp;
  sv3 >> tmp;
  sv3 >> v0 >> tmp >> v1 ;
  m_diB = atoi(v1.c_str());
  dataFill(5, m_diB);
  
  if (m_diA>m_baseline){
    dataFill(6, m_ramp/float(m_diA-m_baseline));
  }
  else {
    dataFill(6, 0.);
  }
  if (m_diB>m_baseline){
    dataFill(7, m_ramp/float(m_diB-m_baseline));
  }
  else {
    dataFill(7, 0.);
  }
  // std::cout << "digit: " << m_ramp << " " << m_diA << " " << m_diB << std::endl;
  time_t t =time(0);
  m_duration=difftime(t, m_startTime);
  m_timestamp = t;
  dataFill(0, m_duration);
  if (application()->options()->dataStorage()){
    m_evtNumber=application()->options()->nEvt()-1;
    m_tree->Fill();
  }
  wait(m_frequency);
  m_ramp += (m_maxRamp-m_minRamp)/float(m_stepRamp);
  if (m_ramp > m_maxRamp) { m_ramp = m_minRamp; }
  return StatusCode::SUCCESS;
}
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
finalize()
StatusCode ADCMeasurement::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 146 of file ADCMeasurement.cpp.
References StatusCode::SUCCESS.
Referenced by ~ADCMeasurement().
                                      {
  return StatusCode::SUCCESS;
}
frequency()
unsigned int ADCMeasurement::frequency () [inline]
Definition at line 39 of file ADCMeasurement.h.
References m_frequency.
Referenced by BOOST_PYTHON_MODULE(), and setFrequency().
                          {
    return m_frequency;
  }
hist1d()
Histo1D* Processus::hist1d (unsigned int row) [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 138 of file Processus.h.
Referenced by export_proc().
                                   {
    return m_data->hist1d(row);
  }
hist2d()
Histo2D* Processus::hist2d (unsigned int row) [inline], [inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 146 of file Processus.h.
Referenced by export_proc().
                                   {
    return m_data->hist2d(row);
  }
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
incNErrors()
void Processus::incNErrors () [inherited]
Increment the number of Errors for that process
Definition at line 72 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
                           {
  m_state->nerrors++;
}
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), ICECALv3::bxidResynchStatus(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTInterface::close(), UsbFTMLInterface::close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), UsbFTMLInterface::help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), MSOxxxx::id(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), EmulateFE::initialize(), initialize(), CurrentMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbI2cBus::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), SeqPGA::reset(), Computer::reset(), FePGA::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), UsbFTInterface::reset(), UsbFTMLInterface::reset(), A3PE::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTMLInterface::update(), UsbFTInterface::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), ICECALv3::version(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
initialize()
StatusCode ADCMeasurement::initialize () [virtual]
Destructor.
Implements Processus.
Definition at line 35 of file ADCMeasurement.cpp.
References Processus::addDataStream(), application(), Options::dataStorage(), Processus::element(), Object::info(), m_ai0, m_ai1, m_ao0, m_baseline, m_device, m_diA, m_diB, m_duration, m_evtNumber, m_maxRamp, m_minRamp, m_ramp, m_runNumber, m_startTime, m_stepRamp, m_timestamp, m_tree, Object::name(), Application::options(), Options::runNumber(), StatusCode::SUCCESS, and Object::title().
Referenced by ~ADCMeasurement().
                                        {
  m_minRamp = 0.;
  m_maxRamp = 1.2;
  m_stepRamp = 20;
  m_baseline = 1400;
  m_ramp = m_minRamp;
  time(&m_startTime);
  m_device = dynamic_cast <NI6008*> (element());
  if (application()->options()->dataStorage()){
    m_tree = new TTree(name().c_str(), title().c_str());
    m_tree->Branch("Run",&m_runNumber,"Run/I");
    m_tree->Branch("Event",&m_evtNumber,"Event/I");
    m_tree->Branch("Time",&m_timestamp,"Time/I");
    m_tree->Branch("Duration",&m_duration,"Duration/I");
    m_tree->Branch("ai0",&m_ai0,"ai0/F");
    m_tree->Branch("ai1",&m_ai1,"ai1/F");
    m_tree->Branch("ao0",&m_ao0,"ao0/F");
    // m_tree->Branch("ao1",&m_ao1,"ao1/F");
    m_tree->Branch("di_0",&m_diA,"diA/I");
    m_tree->Branch("di_1",&m_diB,"diB/I");
  }
  info("Preparing dataStreams.");
  addDataStream("Duration","Duration");
  addDataStream("ai0", "Channel 0");
  addDataStream("ai1", "Channel 1");
  addDataStream("ao0", "Ramp Ampl");
  // addDataStream("ao1", "ADC Chan Ctrl");
  addDataStream("diA","ADC A");
  addDataStream("diB","ADC B");
  addDataStream("ratioA","ratio amplitude A");
  addDataStream("ratioB","ratio amplitude B");
  m_runNumber=application()->options()->runNumber();
  return StatusCode::SUCCESS;
}
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
logMsg()
std::string Processus::logMsg () [inline], [inherited]
Get accessor to member m_logMsg
Returns
the current value of m_logMsg
Definition at line 291 of file Processus.h.
References ProcState::state.
                      {
    return m_logMsg;
  }
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), SeqPGA::help(), NI6008::help(), Computer::help(), SpecsParallelBus::help(), UsbFTInterface::help(), UsbFTMLInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), Data::hist2d(), Croc::init(), FePGA::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), UsbMLI2cBus::reset(), UsbSpiBus::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), SpecsSlave::resetInternal(), FEB_v1::resetSpi(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), Object::setName(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
nErrors()
unsigned int Processus::nErrors () [inherited]
Get accessor to member m_nErrors
Returns
the current value of m_nErrors
Definition at line 86 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
Referenced by Processus::endProcessing().
                                {
  return (m_state->nerrors++);
}
numberOfDevices()
unsigned int ADCMeasurement::numberOfDevices () [inline]
Definition at line 43 of file ADCMeasurement.h.
References m_device, and NI6008::numberOfDevices().
                                {
    return m_device->numberOfDevices();
  }
openRootFile()
void Processus::openRootFile () [inherited]
Open Root file if needed
Definition at line 146 of file Processus.cpp.
References Options::dataFileFullName(), Options::dataStorage(), Object::info(), Processus::m_options, Processus::m_rootFile, and Object::name().
Referenced by RegisterTest::initialize(), UsbFTInterfaceTest::initialize(), PhaserRampExec::initialize(), and Processus::startProcessing().
                               {
  if (m_options->dataStorage()){
    m_rootFile = new TFile(m_options->dataFileFullName().c_str(),
                           "RECREATE",name().c_str());
        std::string mess=std::string("Opening root file ");
        mess.append(m_options->dataFileFullName());
        info(mess,"openRootFile");
  }
}
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
rootFile()
TFile* Processus::rootFile () [inline], [inherited]
Get accessor to member m_rootFile
Returns
the current value of m_rootFile
Definition at line 258 of file Processus.h.
                     {
    return m_rootFile;
  }
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setElement()
void Processus::setElement (Element * element) [inline], [inherited]
Set accessor to member m_element
Parameters
element the new value for m_element
Definition at line 217 of file Processus.h.
Referenced by export_proc(), and Application::prepare().
                                     {
    m_state = new ProcState ();
    m_state->nevent = 0;
    m_state->nerrors = 0;
    m_state->time = 0;
    strcpy(m_state->state,"");
    // setState(OK);
    m_element = element;
  }
setFrequency()
StatusCode ADCMeasurement::setFrequency (unsigned int frequency) [inline]
Definition at line 34 of file ADCMeasurement.h.
References frequency(), m_frequency, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                                 {
    m_frequency = frequency;
    return StatusCode::SUCCESS;
  }
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setLogMsg()
void Processus::setLogMsg (std::string logMsg) [inline], [inherited]
Set accessor to member m_logMsg
Parameters
logMsg the new value for m_logMsg
Definition at line 283 of file Processus.h.
                                    {
    m_logMsg = logMsg;
  }
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), FePGA::MakeRAM(), FePGA::MakeRegister(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setNErrors()
void Processus::setNErrors (unsigned int nerr) [inherited]
Set accessor to member m_nErrors
Parameters
nErrors the new value for m_nErrors
Definition at line 79 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
Referenced by Processus::startProcessing().
                                             {
  m_state->nerrors = nerr ;
}
setState()
void Processus::setState (int state) [inherited]
Set accessor to member m_state.state
Parameters
state the new value for m_state.state
Definition at line 174 of file Processus.cpp.
References application(), Processus::elapsedTime(), Processus::ERR, Object::info(), Processus::m_options, Processus::m_state, Object::msgSvc(), Object::name(), ProcState::nerrors, Options::nErrors(), ProcState::nevent, Options::nEvt(), Processus::NOT_OK, Processus::OK, ProcState::state, and ProcState::time.
Referenced by Processus::endProcessing().
                                     {
  m_state->nevent = m_options->nEvt();
  m_state->nerrors = m_options->nErrors();
  m_state->time = (float) (elapsedTime());
  switch (state){
  case OK:
    strcpy(m_state->state,"OK");
    break;
  case NOT_OK:
    strcpy(m_state->state,"NOT_OK");
    break;
  case ERR:
    strcpy(m_state->state,"ERROR");
  }
}
setStorage()
void Processus::setStorage (std::string storage) [inline], [inherited]
Set accessor to member m_storage
Parameters
storage the new value for m_storage
Definition at line 106 of file Processus.h.
Referenced by export_proc().
                                      {
    m_storage = storage;
  }
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
startChrono()
void Processus::startChrono () [inline], [inherited]
Start processus time measurement
Definition at line 275 of file Processus.h.
References ProcState::time.
Referenced by PhaserRampExec::initialize(), and Processus::startProcessing().
                    {
    m_start = time(0);
  }
startProcessing()
StatusCode Processus::startProcessing () [inherited]
processus cmdline function processus virtual command function processus standard initialize function
Definition at line 93 of file Processus.cpp.
References Object::info(), Processus::initialize(), Processus::m_data, Processus::m_options, Object::name(), Processus::openRootFile(), Data::purge(), Processus::setNErrors(), Options::setNErrors(), and Processus::startChrono().
Referenced by export_proc(), and Application::prepare().
                                      {
  info("==========================================================================");
  info(" * " + name() + " *");
  m_options->setNErrors (0);
  setNErrors (0);
  m_data->purge();
#ifdef _NETWORK_
  if (0 != m_timerService){
    m_timerService->setRunning (true);
    m_timerService->timeHandler() ;
  }
#endif
  // start measuring processus duration
  
  startChrono();
  openRootFile();
  return initialize();
}
storage()
std::string Processus::storage () [inline], [inherited]
Get accessor to member m_storage
Returns
the current value of m_storage
Definition at line 205 of file Processus.h.
Referenced by export_proc(), and Application::prepare().
                       {
    if (0 == m_storage.compare(""))
    {
      return name();
    }
    return m_storage;
  }
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), CurrentMeasurement::initialize(), initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestUSB::Plot(), TestSPI::Plot(), TestI2C::Plot(), Object::setTitle(), and Application::terminate().
{ return m_title; } // < Get Object m_title
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTInterface::read(), UsbFTMLInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), wait(), UsbFTInterface::write(), and UsbFTMLInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), Acquisition::execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), TestI2C::initialize(), EmulateFE::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsMaster::reset(), SpecsSlave::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
Member Data Documentation
m_ai0
Float_t ADCMeasurement::m_ai0 [private]
Definition at line 62 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_ai1
Float_t ADCMeasurement::m_ai1 [private]
Definition at line 63 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_ao0
Float_t ADCMeasurement::m_ao0 [private]
Definition at line 64 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_ao1
Float_t ADCMeasurement::m_ao1 [private]
Definition at line 65 of file ADCMeasurement.h.
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_baseline
Int_t ADCMeasurement::m_baseline [private]
Definition at line 72 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_device
NI6008* ADCMeasurement::m_device [private]
Definition at line 54 of file ADCMeasurement.h.
Referenced by execute(), initialize(), and numberOfDevices().
m_diA
Int_t ADCMeasurement::m_diA [private]
Definition at line 66 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_diB
Int_t ADCMeasurement::m_diB [private]
Definition at line 67 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_duration
Int_t ADCMeasurement::m_duration [private]
Definition at line 60 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_element
Element* Processus::m_element [protected], [inherited]
Definition at line 348 of file Processus.h.
Referenced by Processus::~Processus().
m_evtNumber
Int_t ADCMeasurement::m_evtNumber [private]
Definition at line 58 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_frequency
unsigned int ADCMeasurement::m_frequency [private]
Definition at line 55 of file ADCMeasurement.h.
Referenced by execute(), frequency(), and setFrequency().
m_maxRamp
Float_t ADCMeasurement::m_maxRamp [private]
Definition at line 69 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_minRamp
Float_t ADCMeasurement::m_minRamp [private]
Definition at line 68 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_ramp
Float_t ADCMeasurement::m_ramp [private]
Definition at line 71 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_rnd
TRandom* ADCMeasurement::m_rnd [private]
Definition at line 50 of file ADCMeasurement.h.
m_runNumber
Int_t ADCMeasurement::m_runNumber [private]
Definition at line 57 of file ADCMeasurement.h.
Referenced by initialize().
m_startTime
time_t ADCMeasurement::m_startTime [private]
Definition at line 61 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_stepRamp
Int_t ADCMeasurement::m_stepRamp [private]
Definition at line 70 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_timestamp
Int_t ADCMeasurement::m_timestamp [private]
Definition at line 59 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
m_tree
TTree* ADCMeasurement::m_tree [private]
Definition at line 56 of file ADCMeasurement.h.
Referenced by execute(), and initialize().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatNI/inc/proc/ADCMeasurement.h
/home/eleclhcb/LHCb/lbcat-cmake/CatNI/src/proc/ADCMeasurement.cpp