TestUSB Class Reference
#include <include/TestUSB.h>
Classes
class TestUSB
Public Member Functions
TestUSB ()
Standard constructor.
virtual ~TestUSB ()
virtual StatusCode initialize ()
Destructor.
virtual StatusCode execute ()
virtual StatusCode finalize ()
Public Attributes
p7 = fig.add_subplot(2,3,6)
plot examples
p6=fig.add_subplot(4,3,6) p6.set_title('axes title') p6.set_xlabel('xlabel') p6.set_ylabel('ylabel') p6.text(3, 8, 'boxed italics text in data coords', style='italic', bbox={'facecolor':'red', 'alpha':0.5, 'pad':10}) p6.text(2, 6, r'an equation: $E=mc^2$', fontsize=15) p6.text(3, 2, unicode('unicode: Institut f\374r Festk\366rperphysik', 'latin-1')) p6.text(0.95, 0.01, 'colored text in axes coords', verticalalignment='bottom', horizontalalignment='right', transform=p6.transAxes, color='green', fontsize=15) p6.plot([2], [1], 'o') p6.annotate('annotate', xy=(2, 1), xytext=(3, 4), arrowprops=dict(facecolor='black', shrink=0.05)) p6.axis([0, 10, 0, 10])
h7 = obj.hist1d(0)
color
Protected Member Functions
TestUSB * clone ()
Private Attributes
FEB_v1 * m_board
Register * m_reg
TRandom * m_rnd
Additional Inherited Members
Detailed Description
Author
Frederic Machefert
Date
2010-01-07
Definition at line 20 of file TestUSB.h.
Constructor & Destructor Documentation
TestUSB()
TestUSB::TestUSB ()
Standard constructor.
Definition at line 23 of file TestUSB.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
{
  setName ("TestUSB");
  setType ("FEB_v1");
  setTitle("USB interface test");
}
 TestUSB()
virtual TestUSB::~TestUSB () [inline], [virtual]
Definition at line 25 of file TestUSB.h.
References execute(), finalize(), and initialize().
{};
Member Function Documentation
clone()
TestUSB* TestUSB::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 32 of file TestUSB.h.
References TestUSB().
                  {
    return new TestUSB (*this);
  };
execute()
StatusCode TestUSB::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 60 of file TestUSB.cpp.
References Processus::dataFill(), IOdata::dataU8(), IOobject::io(), m_reg, m_rnd, IOobject::read(), IOdata::setU8(), StatusCode::SUCCESS, and IOobject::write().
Referenced by ~TestUSB().
                              {
  int value = 65536.*m_rnd->Uniform();
  dataFill(0, value);
  m_reg->io()->setU8(0,value&0xFF);
  m_reg->io()->setU8(1,(value>>8)&0xFF);
  m_reg->write();
  m_reg->read();
  int tmp = (m_reg->io()->dataU8(0))+((m_reg->io()->dataU8(1))<<8) ;
  dataFill(1, tmp);
  if (tmp!=value){
    dataFill(2, value);
    dataFill(3, tmp);
  }
  return StatusCode::SUCCESS;
}
finalize()
StatusCode TestUSB::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 79 of file TestUSB.cpp.
References StatusCode::SUCCESS.
Referenced by ~TestUSB().
                               {
  return StatusCode::SUCCESS;
}
initialize()
StatusCode TestUSB::initialize () [virtual]
Destructor.
Implements Processus.
Definition at line 33 of file TestUSB.cpp.
References Processus::addDataStream(), Processus::element(), m_board, m_reg, m_rnd, FEB_v1::seqPga(), SeqPGA::setupReg(), StatusCode::SUCCESS, and Object::warning().
Referenced by ~TestUSB().
                                 {
  m_board=dynamic_cast<FEB_v1*>(element());
  
  if (!m_board){
    warning("TestUSB","No FEB_v1 board found. Interrupt.");
    return false;
  }
  SeqPGA* seqPga = m_board->seqPga();
  if (!seqPga){
    warning("TestUSB","No SeqPga found. Interrupt.");
    return false;
  }
  
  m_reg=seqPga->setupReg();
  m_rnd =new TRandom();
  addDataStream("Input","Input value");
  addDataStream("Output","Output value");
  addDataStream("Errors","Error input value");
  addDataStream("Errors","Error output value");
  return StatusCode::SUCCESS;
}
Member Data Documentation
color
TestUSB.color
Definition at line 149 of file TestUSB.py.
h7
TestUSB.h7 = obj.hist1d(0)
Definition at line 147 of file TestUSB.py.
m_board
FEB_v1* TestUSB::m_board [private]
Definition at line 34 of file TestUSB.h.
Referenced by initialize().
m_reg
Register* TestUSB::m_reg [private]
Definition at line 38 of file TestUSB.h.
Referenced by execute(), and initialize().
m_rnd
TRandom* TestUSB::m_rnd [private]
Definition at line 39 of file TestUSB.h.
Referenced by execute(), and initialize().
p7
TestUSB.p7 = fig.add_subplot(2,3,6)
plot examples
p6=fig.add_subplot(4,3,6) p6.set_title('axes title') p6.set_xlabel('xlabel') p6.set_ylabel('ylabel') p6.text(3, 8, 'boxed italics text in data coords', style='italic', bbox={'facecolor':'red', 'alpha':0.5, 'pad':10}) p6.text(2, 6, r'an equation: $E=mc^2$', fontsize=15) p6.text(3, 2, unicode('unicode: Institut f\374r Festk\366rperphysik', 'latin-1')) p6.text(0.95, 0.01, 'colored text in axes coords', verticalalignment='bottom', horizontalalignment='right', transform=p6.transAxes, color='green', fontsize=15) p6.plot([2], [1], 'o') p6.annotate('annotate', xy=(2, 1), xytext=(3, 4), arrowprops=dict(facecolor='black', shrink=0.05)) p6.axis([0, 10, 0, 10])
Definition at line 146 of file TestUSB.py.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/proc/TestUSB.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/python/proc/TestUSB.py
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/proc/TestUSB.cpp