SpecsGlue Class Reference
#include <inc/SpecsGlue.h>
Public Member Functions
SpecsGlue ()
Standard constructor.
virtual ~SpecsGlue ()
Standard Destructor.
void help ()
bool led ()
int date ()
void setLed (bool)
void setI2cClkMode (int)
int i2cClkMode ()
Additional Inherited Members
Detailed Description
Author
Frédéric Machefert
Date
2005-05-25
Definition at line 15 of file SpecsGlue.h.
Constructor & Destructor Documentation
SpecsGlue()
SpecsGlue::SpecsGlue ()
Standard constructor.
Definition at line 21 of file SpecsGlue.cpp.
References SpecsSlave::setAddress(), Object::setName(), and Object::setType().
                       {
  setAddress(0x0);
  setName("SpecsGlue");
  setType("SpecsGlue");
}
 SpecsGlue()
SpecsGlue::~SpecsGlue () [virtual]
Standard Destructor.
Destructor
Definition at line 30 of file SpecsGlue.cpp.
{}
Member Function Documentation
date()
int SpecsGlue::date ()
Get the Specs Slave Date
Definition at line 158 of file SpecsGlue.cpp.
References SpecsInterface::specsReadRegister(), and Object::warning().
                   {
  unsigned char reg = 8 ;
#ifndef _NODEVICE_
  U16 val;
  this -> specsReadRegister(reg , val);
  val = (val&0xFF00)*100+(val&0xFF);
  return val;
#else
  warning("" , "Compilation in _NoDevice_ mode.");
#endif
  return 0;
}
help()
void SpecsGlue::help () [virtual]
Help message for the Specs Slaves
Reimplemented from SpecsInterface.
Definition at line 143 of file SpecsGlue.cpp.
References Object::info().
                    {
  info("SpecsGlue","Specs Glue Element help");
  info("","");
  info("","Address # : set slave address at #");
  info("","Reset : reset of the slave");
  info("","ResetInternal : internal reset of the slave");
  info("","RegWrite #0 #1 : write register #0 with value #1");
  info("","RegRead #0 #1 : read register #");
  info("","");
}
i2cClkMode()
int SpecsGlue::i2cClkMode ()
Definition at line 241 of file SpecsGlue.cpp.
References Object::debug(), SpecsInterface::specsReadRegister(), and Object::warning().
                            {
  unsigned char reg = 4 ;
#ifndef _NODEVICE_
  U16 val ;
  this -> specsReadRegister(reg , val);
  if (0 != (val & 0x0004)){
    debug("SpecsGlue::led","Glue I2C Mode Clk idle 0");
    return 1;
  }
#else
  warning("" , "Compilation in _NoDevice_ mode.");
  return 0;
#endif
  debug("SpecsGlue::led","Glue I2C Mode Clk idle 1");
  return 0;
}
led()
bool SpecsGlue::led ()
Get the state of the LEDs controlled by the Specs Slave
Definition at line 197 of file SpecsGlue.cpp.
References Object::debug(), SpecsInterface::specsReadRegister(), and Object::warning().
                      {
  unsigned char reg = 4 ;
#ifndef _NODEVICE_
  U16 val ;
  this -> specsReadRegister(reg , val);
  if (0 != (val & 0x0008)){
    debug("SpecsGlue::led","Glue LEDs are OFF");
    return false;
  }
#else
  warning("" , "Compilation in _NoDevice_ mode.");
  return true;
#endif
  debug("SpecsGlue::led","Glue LEDs are ON");
  return true;
}
setI2cClkMode()
void SpecsGlue::setI2cClkMode (int mode)
Definition at line 217 of file SpecsGlue.cpp.
References Object::debug(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteRegister(), and Object::warning().
                                        {
  unsigned char reg = 4 ;
#ifndef _NODEVICE_
  U16 val;
  this -> specsReadRegister(reg , val);
  if (0==mode) {
    val = (val & 0xFFFB) ;
    this -> specsWriteRegister(reg, val);
    debug("SpecsGlue::led","setting Glue I2C Mode Clk idle 1");
  }
  else {
    val = (val | 0x0004) ;
    this -> specsWriteRegister(reg , val) ;
    debug("SpecsGlue::led","setting Glue I2C Mode Clk idle 0");
  }
#else
  warning("" , "Compilation in _NoDevice_ mode.");
#endif
}
setLed()
void SpecsGlue::setLed (bool state)
Set the state of the LEDs controlled by the Specs Slave
Definition at line 174 of file SpecsGlue.cpp.
References Object::debug(), SpecsInterface::specsReadRegister(), and SpecsInterface::specsWriteRegister().
                                   {
  unsigned char reg = 4 ;
#ifndef _NODEVICE_
  U16 val;
  this -> specsReadRegister(reg , val);
  if (state) {
    val = (val & 0xFFF7) ;
    this -> specsWriteRegister(reg, val);
    debug("SpecsGlue::led","setting Glue LEDs On");
  }
  else {
    val = (val | 0x0008) ;
    this -> specsWriteRegister(reg , val) ;
    debug("SpecsGlue::led","setting Glue LEDs OFF");
  }
#else
  debug("" , "Compilation in _NoDevice_ mode.");
#endif
}
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/inc/SpecsGlue.h
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/src/SpecsGlue.cpp