var Class Reference
#include <inc/var.h>
Public Types
enum Type {
UNKNOWN,
CHAR,
INT,
FLOAT,
DOUBLE,
STRING
 }
Public Member Functions
var ()
Standard constructor.
var (char)
var (int)
var (float)
var (double)
var (std::string)
virtual ~var ()
Destructor.
char vchar ()
int vint ()
float vfloat ()
double vdouble ()
std::string vstring ()
std::vector< var > vector (const char *,...)
Private Member Functions
void verbose (std::string msg)
void debug (std::string msg)
void info (std::string msg)
void warning (std::string msg)
void fatal (std::string msg)
void verbose (std::string msg, std::string name)
void debug (std::string msg, std::string name)
void info (std::string msg, std::string name)
void warning (std::string msg, std::string name)
void fatal (std::string msg, std::string name)
Private Attributes
char m_char
int m_type
int m_int
float m_float
double m_double
std::string m_string
MsgSvc m_log
Detailed Description
Author
Date
2006-10-26
Definition at line 19 of file var.h.
Member Enumeration Documentation
Type
enum var::Type
Enumerator
UNKNOWN
CHAR
INT
FLOAT
DOUBLE
STRING
Definition at line 22 of file var.h.
            {
    UNKNOWN,
    CHAR,
    INT,
    FLOAT,
    DOUBLE,
    STRING
  };
Constructor & Destructor Documentation
var() [1/6]
var::var ()
Standard constructor.
Definition at line 21 of file var.cpp.
References m_type, and UNKNOWN.
           {
  m_type=UNKNOWN;
}
var() [2/6]
var::var (char ch)
Definition at line 33 of file var.cpp.
References CHAR, m_char, and m_type.
                  {
  m_type=CHAR;
  m_char = ch;
}
var() [3/6]
var::var (int i)
Definition at line 41 of file var.cpp.
References INT, m_int, and m_type.
                {
  m_type=INT;
  m_int = i;
}
var() [4/6]
var::var (float f)
Definition at line 49 of file var.cpp.
References cat::f, FLOAT, m_float, and m_type.
                   {
  m_type=FLOAT;
  m_float = f;
}
var() [5/6]
var::var (double d)
Definition at line 57 of file var.cpp.
References DOUBLE, m_double, and m_type.
                   {
  m_type=DOUBLE;
  m_double = d;
}
var() [6/6]
var::var (std::string str)
Definition at line 65 of file var.cpp.
References m_string, m_type, and STRING.
                        {
  m_type=STRING;
  m_string = str;
}
 var()
var::~var () [virtual]
Destructor.
Definition at line 27 of file var.cpp.
{}
Member Function Documentation
debug() [1/2]
void var::debug (std::string msg) [inline], [private]
Definition at line 61 of file var.h.
References MsgSvc::DEBUG, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , msg, std::string("var")); }
debug() [2/2]
void var::debug (std::string msg, std::string name) [inline], [private]
Definition at line 67 of file var.h.
References MsgSvc::DEBUG, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , msg, name); }
fatal() [1/2]
void var::fatal (std::string msg) [inline], [private]
Definition at line 64 of file var.h.
References MsgSvc::FATAL, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , msg, std::string("var")); }
fatal() [2/2]
void var::fatal (std::string msg, std::string name) [inline], [private]
Definition at line 70 of file var.h.
References MsgSvc::FATAL, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , msg, name); }
info() [1/2]
void var::info (std::string msg) [inline], [private]
Definition at line 62 of file var.h.
References MsgSvc::INFO, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , msg, std::string("var")); }
info() [2/2]
void var::info (std::string msg, std::string name) [inline], [private]
Definition at line 68 of file var.h.
References MsgSvc::INFO, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , msg, name); }
vchar()
char var::vchar () [inline]
Definition at line 40 of file var.h.
References m_char.
{ return m_char; }
vdouble()
double var::vdouble () [inline]
Definition at line 43 of file var.h.
References m_double.
{ return m_double; }
vector()
std::vector< var > var::vector (const char * format, ...)
Definition at line 74 of file var.cpp.
Referenced by vstring().
                                                  {
  va_list pa;
  vars varlist;
  va_start(pa, format);
/* while (*format != '\0') {
    if (*format=='%') {
      format++;
      switch (*format) {
      case 'c' : // char
        varlist.push_back(var((char)(va_arg(pa,char))));
        break;
      case 'i' : // integer
        varlist.push_back(var((int)(va_arg(pa,int))));
        break;
      case 'f' : // float
        varlist.push_back(var((float)(va_arg(pa,float))));
        break;
      case 'd' : // double
        varlist.push_back(var((double)(va_arg(pa,double))));
        break;
      case 's' : // string
        varlist.push_back(var(std::string((va_arg(pa,char*)))));
        break;
      default:
    std::cout<<"hello"<<std::endl;
    // nothing
// application()->warning("Could not figure out the type of the variable
       ("+std::string(format)+").","var::vector");
      } // end switch
      ++format;
    }
  }*/
  va_end(pa);
  return varlist;
}
verbose() [1/2]
void var::verbose (std::string msg) [inline], [private]
Definition at line 60 of file var.h.
References MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , msg, std::string("var")); }
verbose() [2/2]
void var::verbose (std::string msg, std::string name) [inline], [private]
Definition at line 66 of file var.h.
References MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , msg, name); }
vfloat()
float var::vfloat () [inline]
Definition at line 42 of file var.h.
References m_float.
{ return m_float; }
vint()
int var::vint () [inline]
Definition at line 41 of file var.h.
References m_int.
{ return m_int; }
vstring()
std::string var::vstring () [inline]
Definition at line 44 of file var.h.
References m_string, and vector().
{ return m_string; }
warning() [1/2]
void var::warning (std::string msg) [inline], [private]
Definition at line 63 of file var.h.
References MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , msg, std::string("var")); }
warning() [2/2]
void var::warning (std::string msg, std::string name) [inline], [private]
Definition at line 69 of file var.h.
References MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , msg, name); }
Member Data Documentation
m_char
char var::m_char [private]
Definition at line 51 of file var.h.
Referenced by var(), and vchar().
m_double
double var::m_double [private]
Definition at line 55 of file var.h.
Referenced by var(), and vdouble().
m_float
float var::m_float [private]
Definition at line 54 of file var.h.
Referenced by var(), and vfloat().
m_int
int var::m_int [private]
Definition at line 53 of file var.h.
Referenced by var(), and vint().
m_log
MsgSvc var::m_log [private]
Definition at line 58 of file var.h.
m_string
std::string var::m_string [private]
Definition at line 56 of file var.h.
Referenced by var(), and vstring().
m_type
int var::m_type [private]
Definition at line 52 of file var.h.
Referenced by var().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/var.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/var.cpp