A3PE_BitFlip Class Reference
#include <inc/A3PE_BitFlip.h>Inheritance diagram for A3PE_BitFlip::
Classes
class A3PE_BitFlip
Public Types
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
enum states { ERR = -1,
NOT_OK,
OK
 }
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
A3PE_BitFlip ()
Standard constructor.
virtual ~A3PE_BitFlip ()
Destructor.
virtual StatusCode initialize ()
virtual StatusCode execute ()
virtual StatusCode finalize ()
StatusCode setFile (std::string filename)
std::string file ()
A3PE * a3pe ()
StatusCode startProcessing ()
StatusCode endProcessing ()
void clean ()
void setStorage (std::string storage)
Data * data ()
std::vector< double > data (unsigned int row)
std::vector< double > data (std::string name)
Histo1D * hist1d (unsigned int row)
Histo2D * hist2d (unsigned int row)
void addDataStream (std::string name, std::string title)
void addHisto1d (TH1D *h)
void addHisto2d (TH2D *h)
StatusCode dataFill (int i, double val)
StatusCode dataFill (std::string name, double val)
std::string storage ()
void setElement (Element *element)
Element * element ()
void incNErrors ()
void setNErrors (unsigned int)
unsigned int nErrors ()
TFile * rootFile ()
void openRootFile ()
void closeRootFile ()
void startChrono ()
void setLogMsg (std::string logMsg)
std::string logMsg ()
void setState (int state)
double elapsedTime ()
double elapsedTime (time_t start)
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Member Functions
A3PE_BitFlip * clone ()
StatusCode randomValues ()
Protected Attributes
Element * m_element
std::string m_attribString [10]
Private Attributes
Proto40MHz_v1 * m_board
A3PE * m_pga
RAM * m_toAX
RAM * m_fromAX
std::string m_filename
unsigned int m_length
unsigned int m_latency
unsigned int m_latencyMin
unsigned int m_latencyMax
int m_offset
U8 * m_data
U8 * m_dataProcessed
TH1D * m_hLatency
TH1D * m_hErrorsLatency
TH1D * m_hErrorsWord
Detailed Description
Author
Date
2012-07-12
Definition at line 17 of file A3PE_BitFlip.h.
Member Typedef Documentation
typedef unsigned short A3PE_BitFlip::U16
Definition at line 20 of file A3PE_BitFlip.h.
typedef unsigned long A3PE_BitFlip::U32
Definition at line 19 of file A3PE_BitFlip.h.
typedef unsigned char A3PE_BitFlip::U8
Definition at line 21 of file A3PE_BitFlip.h.
Member Enumeration Documentation
enum Attrib::Attribut [inherited]
Enumerator:
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  ; // array m_attribString must be changed into Attrib::Attrib if this enu is m
      odified.
enum Processus::states [inherited]
Enumerator:
ERR
NOT_OK
OK
Definition at line 34 of file Processus.h.
 ERR=-1 , NOT_OK , OK ;
Constructor & Destructor Documentation
A3PE_BitFlip::A3PE_BitFlip ()
Standard constructor.
Definition at line 26 of file A3PE_BitFlip.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
                             :
  m_filename(std::string("")),
  m_offset(-6),
  m_latencyMin(1000),
  m_latencyMax(100000),
  m_hLatency (0),
  m_hErrorsLatency(0),
  m_hErrorsWord(0)
  setName ("A3PE_BitFlip");
  setType ("Proto40MHz_v1");
  setTitle("Proto40MHz_v1 A3PE_BitFlip test");
//=============================================================================
A3PE_BitFlip::~A3PE_BitFlip () [virtual]
Destructor.
Definition at line 42 of file A3PE_BitFlip.cpp.
Member Function Documentation
A3PE* A3PE_BitFlip::a3pe () [inline]
Definition at line 39 of file A3PE_BitFlip.h.
References m_pga.
return m_pga;
void Attrib::add (int attribut) [inline, inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        duplicate = true ;
      
    
    if (!duplicate)
      m_attributs.push_back(attribut);
    
  
void Processus::addDataStream (std::string name, std::string title) [inline, inherited]
Definition at line 153 of file Processus.h.
References Data::addDataStream(), and Processus::m_data.
Referenced by CurrentMeasurement::initialize(), ADCMeasurement::initialize(), TestSuite::initialize(), TestUSB::initialize(), TestSPI::initialize(), TestI2C::initialize(), UsbFTInterfaceTest::initialize(), and RegisterTest::initialize().
                                                       
    m_data->addDataStream(name, title);
  
void Processus::addHisto1d (TH1D * h) [inline, inherited]
Definition at line 160 of file Processus.h.
References Data::addHisto1d(), and Processus::m_data.
Referenced by TestSuite::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), and initialize().
                           
    m_data->addHisto1d(h);
  
void Processus::addHisto2d (TH2D * h) [inline, inherited]
Definition at line 167 of file Processus.h.
References Data::addHisto2d(), and Processus::m_data.
Referenced by TestSuite::initialize().
                           
    m_data->addHisto2d(h);
  
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj().
                            
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++index)
    if (m_attributs.size() - index > 1)
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    
    else
      output.append(m_attribString[m_attributs[index]]);
    
  
  return output;
void Processus::clean () [inline, inherited]
Definition at line 85 of file Processus.h.
References Processus::m_element, Processus::m_state, and Object::warning().
Referenced by Application::prepare().
  
    m_element=0;
    if (0!=m_state)
      delete m_state;
      m_state=0;
    
#ifdef _NETWORK_
    warning("Cleaning state service : should it be done ?","Processus::clean")
      if (0!=m_stateService)
      
        delete m_stateService;
      
#endif
  
A3PE_BitFlip* A3PE_BitFlip::clone () [inline, protected, virtual]
processus termination virtual function
Implements Processus.
Definition at line 42 of file A3PE_BitFlip.h.
References A3PE_BitFlip().
                       
    return new A3PE_BitFlip (*this);
  
void Processus::closeRootFile () [inherited]
Close Root file if already opened and requested
Definition at line 160 of file Processus.cpp.
References Options::dataFileFullName(), Options::dataStorage(), Object::info(), Processus::m_options, and Processus::m_rootFile.
Referenced by Processus::endProcessing(), UsbFTInterfaceTest::finalize(), RegisterTest::finalize(), and PhaserRampExec::finalize().
                                
  if (0!= m_rootFile && m_options->dataStorage())
    m_rootFile->Write();
        std::string mess=std::string("Closing root file ");
        mess.append(m_options->dataFileFullName());
        info(mess,"closeRootFile");
    m_rootFile->Delete();
    m_rootFile = 0;
  
std::vector<double> Processus::data (std::string name) [inline, inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 130 of file Processus.h.
References Processus::m_data, and Data::vector().
                                        
    return m_data->vector(name);
  
std::vector<double> Processus::data (unsigned int row) [inline, inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 122 of file Processus.h.
References Processus::m_data, and Data::vector().
                                          
    return m_data->vector(row);
  
Data* Processus::data () [inline, inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 114 of file Processus.h.
References Processus::m_data.
Referenced by StorageFifoAcquisition::execute(), and export_proc().
              
    return m_data;
  
StatusCode Processus::dataFill (std::string name, double val) [inline, inherited]
Set data stream with value
Returns
the StatusCode
Definition at line 189 of file Processus.h.
References StatusCode::FAILURE, Processus::m_data, Data::rowFromName(), StatusCode::SUCCESS, and Data::vectorPtr().
                                                 
    int row=m_data->rowFromName(name);
    if (row<0) return StatusCode::FAILURE;
    if (m_data->vectorPtr(row)!=0)
      m_data->vectorPtr(row)->push_back(val);
      return StatusCode::SUCCESS;
    
    else
      return StatusCode::FAILURE;
    
  
StatusCode Processus::dataFill (int i, double val) [inline, inherited]
Set data stream with value
Returns
the StatusCode
Definition at line 175 of file Processus.h.
References StatusCode::FAILURE, Processus::m_data, StatusCode::SUCCESS, and Data::vectorPtr().
Referenced by CurrentMeasurement::execute(), ADCMeasurement::execute(), TestSuite::execute(), TestUSB::execute(), TestSPI::execute(), TestI2C::execute(), and UsbFTInterfaceTest::execute().
                                        
    if (m_data->vectorPtr(i)!=0)
      m_data->vectorPtr(i)->push_back(val);
      return StatusCode::SUCCESS;
    
    else
      return StatusCode::FAILURE;
    
  
void Object::debug (std::string mymsg, std::string name) [inline, inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::DEBUG , mymsg, name);
void Object::debug (std::string mymsg) [inline, inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::checkConfigAddr(), LSDelayChipV1::checkStatusAddr(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), EmulateFE::execute(), StorageFifoAcquisition::execute(), StorageFifo::execute(), Acquisition::execute(), execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), SeqPGA::i2cRead(), FePGA::i2cRead(), SeqPGA::i2cWrite(), FePGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), initialize(), A3PE::internalAXSequence(), SpecsMezzanine::led(), SpecsGlue::led(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), ICPhaser::read(), Phaser::read(), FEB_v1::readFifoSpyFE(), SpecsSlave::reset(), SpecsMaster::reset(), FEB_v1::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::resetFifoSpyFE(), SeqPGA::resetSpi(), FEB_v1::resetSpi(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsMezzanine::setLed(), SpecsGlue::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), FEB_v1::testDuration(), SeqPGA::testSequence(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), ICPhaser::write(), Phaser::write(), and Hierarchy::~Hierarchy().
 m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name);
std::string Object::dllName () [inline, inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj().
                       
    return m_dllName;
  
double Processus::elapsedTime (time_t start) [inline, inherited]
Definition at line 343 of file Processus.h.
                                   
    return ((time(0)-start));
  
double Processus::elapsedTime () [inline, inherited]
Definition at line 340 of file Processus.h.
References Processus::m_start.
Referenced by Processus::endProcessing(), UsbFTInterfaceTest::execute(), PhaserRampExec::finalize(), and Processus::setState().
                       
    return difftime(time(0),m_start);
  
Element* Processus::element () [inline, inherited]
Get accessor to member m_element
Returns
the current value of m_element
Definition at line 231 of file Processus.h.
References Processus::m_element.
Referenced by UsbFTInterfaceTest::execute(), export_proc(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), TestUSB::initialize(), TestSPI::initialize(), TestI2C::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), initialize(), and PhaserRampExec::initialize().
                      
    return m_element;
  
StatusCode Processus::endProcessing () [inherited]
processus standard termination function
Definition at line 115 of file Processus.cpp.
References Data::buildHistos(), Processus::closeRootFile(), Processus::elapsedTime(), Data::empty(), Processus::finalize(), ftos(), Object::info(), itos(), Processus::m_data, Processus::m_options, Options::nErrors(), Processus::nErrors(), Options::nEvt(), Processus::NOT_OK, Data::print(), Options::runNumber(), and Processus::setState().
Referenced by export_proc(), and Application::terminate().
                                    
  setState(NOT_OK);
  //
  info("-------------------------------------------------------------------------
      -");
  info("Processed Run Number : " + itos (m_options->runNumber()) , "finaliz
      e");
  info("Number of events processed : " + itos (m_options->nEvt()) , "finaliz
      e");
  info("Number of Errors : " + itos (nErrors()) , "finalize")
      ;
  info("Number of App errors : " + itos (m_options->nErrors()) , "finaliz
      e");
  info("Elapsed time : " + ftos (elapsedTime()) , "finalize")
      ;
  info("-------------------------------------------------------------------------
      -");
  if (!m_data->empty())
    m_data->print();
  else
    info("No data Stored.","finalize");
  info("-------------------------------------------------------------------------
      -");
#ifdef _NETWORK_
  if (0 != m_timerService)
    m_timerService->setRunning (false);
  
#endif
  StatusCode sc = finalize();
  m_data->buildHistos();
  closeRootFile();
  return sc;
void Object::error (std::string mymsg, std::string name) [inline, inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::ERR , mymsg, name);
void Object::error (std::string mymsg) [inline, inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by ICECALv3::checkChNumber(), A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), SpecsMaster::init(), NI6008::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTMLInterface::read(), UsbFTInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
 m_log.msgSvc (MsgSvc::ERR , mymsg, m_name);
StatusCode A3PE_BitFlip::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 109 of file A3PE_BitFlip.cpp.
References Object::debug(), Object::error(), StatusCode::FAILURE, m_data, m_dataProcessed, m_filename, m_fromAX, m_hErrorsLatency, m_hErrorsWord, m_hLatency, m_latency, m_latencyMax, m_latencyMin, m_length, m_offset, m_pga, randomValues(), IOobject::read(), A3PE::setAddFromAXRam(), A3PE::setAXRamUsb(), A3PE::setLatencyAX(), A3PE::startSequenceAX(), StatusCode::SUCCESS, and Object::warning().
Referenced by BOOST_PYTHON_MODULE().
                                   
  debug("A3PE_BitFlip" , "execute");
  unsigned long latency;
  if (0==m_latency)
        latency=m_latencyMin+((float)(rand())/RAND_MAX*((float)(m_latencyMax-
      m_latencyMin)));
        m_pga->setLatencyAX(latency);
  
  else latency=m_latency;
  if (m_filename==std::string(""))
      randomValues();
  
  
  m_hLatency->Fill((float)(latency));
  m_pga->startSequenceAX();
  m_pga->setAXRamUsb(true);
  m_pga->setAddFromAXRam(0);
  m_fromAX->read();
  bool error=false;
  char line[100];
  bool errLatencySeen=false;
  for (unsigned int d=0; d<m_length; ++d)
    unsigned int position=(d+latency+m_offset)%512;
    if ((m_dataProcessed[4*d]!=m_data[4*position])||
    (m_dataProcessed[4*d+1]!=m_data[4*position+1])||
    (m_dataProcessed[4*d+2]!=m_data[4*position+2])||
    (m_dataProcessed[4*d+3]!=m_data[4*position+3]))
      
        if (!errLatencySeen)
            m_hErrorsLatency->Fill((float)(latency));
            errLatencySeen=true;
        
        m_hErrorsWord->Fill((float)(d));
    sprintf(line,"%3d -> %1d %1d %1d %1d / %1d %1d %1d %1d",
        d,
        m_dataProcessed[4*d],m_dataProcessed[1+4*d],m_dataProcessed[2+4*d],
      m_dataProcessed[3+4*d],
        m_data[4*position],m_data[1+4*position],m_data[2+4*position],m_data[3+4*p
      osition]);
    warning(line);
      error = true;
      
  
  if (error) return StatusCode::FAILURE;
  return StatusCode::SUCCESS;
void Object::fatal (std::string mymsg, std::string name) [inline, inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::FATAL , mymsg, name);
void Object::fatal (std::string mymsg) [inline, inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), SpecsSlave::init(), UsbSpiBus::init(), UsbI2cBus::init(), IOobject::init(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
 m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name);
std::string A3PE_BitFlip::file () [inline]
Definition at line 35 of file A3PE_BitFlip.h.
References m_filename.
Referenced by BOOST_PYTHON_MODULE().
                  
    return m_filename;
  
StatusCode A3PE_BitFlip::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 161 of file A3PE_BitFlip.cpp.
References m_latency, m_pga, A3PE::setLatencyAX(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                    
  if (0==m_latency) m_pga->setLatencyAX(0);
  return StatusCode::SUCCESS;
Histo1D* Processus::hist1d (unsigned int row) [inline, inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 138 of file Processus.h.
References Data::hist1d(), and Processus::m_data.
Referenced by export_proc().
                                   
    return m_data->hist1d(row);
  
Histo2D* Processus::hist2d (unsigned int row) [inline, inherited]
Get accessor to member m_data
Returns
the current value of m_data
Definition at line 146 of file Processus.h.
References Data::hist2d(), and Processus::m_data.
Referenced by export_proc().
                                   
    return m_data->hist2d(row);
  
unsigned char Object::id () [inline, inherited]
Reimplemented in MSOxxxx.
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj().
 return m_id; //< Get Object m_id
void Processus::incNErrors () [inherited]
Increment the number of Errors for that process
Definition at line 72 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
                           
  m_state->nerrors++;
void Object::info (std::string mymsg, std::string name) [inline, inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::INFO , mymsg, name);
void Object::info (std::string mymsg) [inline, inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), ICECALv3::bxidResynchStatus(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTMLInterface::close(), UsbFTInterface::close(), MSOxxxx::closeConnection(), Processus::closeRootFile(), SpecsMezzanine::cmdline(), Server::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), SpecsMezzanine::help(), SpecsMaster::help(), SpecsGlue::help(), SpecsParallelBus::help(), SpecsInterface::help(), NI6008::help(), Computer::help(), UsbSpiBus::help(), UsbI2cBus::help(), RAM::help(), IOobject::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbFTMLInterface::help(), SeqPGA::help(), ICPhaser::help(), FePGA::help(), FEB_v1::help(), CU_v1::help(), UsbFTInterface::help(), Proto40MHz_v1::help(), A3PE::help(), Phaser::help(), Croc::help(), MSOxxxx::help(), LSDelayChipV1::help(), ICECALv3::help(), MSOxxxx::id(), SpecsSlave::init(), SpecsMaster::init(), SpecsParallelBus::init(), SpecsInterface::init(), NI6008::init(), Computer::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), Croc::init(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), SpecsMaster::reset(), SpecsParallelBus::reset(), SpecsInterface::reset(), NI6008::reset(), Computer::reset(), UsbSpiBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbMLI2cBus::reset(), UsbFTMLInterface::reset(), SeqPGA::reset(), FePGA::reset(), UsbFTInterface::reset(), A3PE::reset(), Croc::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), ICPhaser::setPhase(), Phaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), SpecsParallelBus::update(), SpecsInterface::update(), NI6008::update(), Computer::update(), UsbSpiBus::update(), UsbI2cBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), UsbFTMLInterface::update(), FEB_v1::update(), CU_v1::update(), UsbFTInterface::update(), Proto40MHz_v1::update(), Croc::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), ICECALv3::version(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
 m_log.msgSvc (MsgSvc::INFO , mymsg, m_name);
StatusCode A3PE_BitFlip::initialize () [virtual]
processus initialisation virtual function
Implements Processus.
Definition at line 49 of file A3PE_BitFlip.cpp.
References Proto40MHz_v1::a3pe(), Processus::addHisto1d(), IOdata::dataU8(), Object::debug(), Processus::element(), A3PE::fromAXRam(), Object::info(), A3PE::internalAXSequence(), IOobject::io(), itos(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::loadToAX(), m_board, m_data, m_dataProcessed, m_filename, m_fromAX, m_hErrorsLatency, m_hErrorsWord, m_hLatency, m_latency, m_latencyMax, m_latencyMin, m_length, m_offset, m_pga, m_toAX, Object::name(), StatusCode::SUCCESS, A3PE::toAXRam(), Object::type(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE().
                                      
  debug("A3PE_BitFlip" , "initialize");
  info("");
  info("____________________________");
  info("A3PE bit flip test");
  info(" =>" + element()->path() + " " +
      element()->name() + " " + element()->type());
  m_board=dynamic_cast<Proto40MHz_v1*>(element());
  if (!m_board)
    warning("A3PE_BitFlip","No Proto40MHz_v1 board found. Interrupt.");
    return false;
  
  m_pga=m_board->a3pe();
  m_fromAX = m_pga->fromAXRam();
  m_toAX = m_pga->toAXRam();
  m_data =m_toAX->io()->dataU8();
  m_dataProcessed=m_fromAX->io()->dataU8();
  m_length=m_pga->lengthAX();
  m_latency=m_pga->latencyAX();
  if (m_pga->internalAXSequence())
    m_offset=-2;
  else
    m_offset=-5;
  
  if (m_filename!=std::string(""))
      m_pga->loadToAX(m_filename);
      info("Static RAM mode ["+m_filename+"].");
  
  else
    info("Dynamic Random RAM mode.");
  if (0==m_latency) info("Latency = random");
  else info("Latency ="+itos(m_latency));
  info("Length ="+itos(m_length));
  info("Offset ="+itos(m_offset));
  warning("In internal loop the offset should be -3 with a Latency of 4 at least"
      );
  warning("In external loop the offset should be -6 with a Latency of 5 at least"
      );
  warning("The offset for this run is "+itos(m_offset));
  m_hLatency=new TH1D("Latency","Latency", 100, m_latencyMin, m_latencyMax);
  m_hErrorsLatency =new TH1D("ErrorsLatency","Errors (Latency)", 100,
      m_latencyMin, m_latencyMax);
  m_hErrorsWord =new TH1D("ErrorsWord","Errors (Word)", 100, 0, m_length);
  addHisto1d(m_hLatency);
  addHisto1d(m_hErrorsLatency);
  addHisto1d(m_hErrorsWord);
  return StatusCode::SUCCESS;
bool Attrib::is (int attribut) [inline, inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        return true;
      
    
    return false;
  
std::string Processus::logMsg () [inline, inherited]
Get accessor to member m_logMsg
Returns
the current value of m_logMsg
Definition at line 291 of file Processus.h.
References Processus::m_logMsg.
                      
    return m_logMsg;
  
void Object::msg (std::string mymsg, std::string name) [inline, inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
 m_log.msgSvc (MsgSvc::NONE , mymsg, name);
void Object::msg (std::string mymsg) [inline, inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
 m_log.msgSvc (MsgSvc::NONE , mymsg, m_name);
void Object::msgSvc (int level, std::string msg, std::string name) [inline, inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), and Hierarchy::tree().
 m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg, name);
std::string Object::name () const [inline, inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), SpecsParallelBus::help(), SpecsInterface::help(), NI6008::help(), Computer::help(), UsbSpiBus::help(), UsbI2cBus::help(), RAM::help(), IOobject::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbFTMLInterface::help(), SeqPGA::help(), ICPhaser::help(), FePGA::help(), FEB_v1::help(), CU_v1::help(), UsbFTInterface::help(), Proto40MHz_v1::help(), A3PE::help(), Phaser::help(), Croc::help(), MSOxxxx::help(), LSDelayChipV1::help(), ICECALv3::help(), SpecsSlave::init(), SpecsMaster::init(), SpecsParallelBus::init(), SpecsInterface::init(), NI6008::init(), Computer::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), Croc::init(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), ICPhaser::read(), Phaser::read(), SpecsSlave::reset(), SpecsMaster::reset(), SpecsParallelBus::reset(), SpecsInterface::reset(), NI6008::reset(), Computer::reset(), UsbSpiBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbMLI2cBus::reset(), UsbFTMLInterface::reset(), FEB_v1::reset(), CU_v1::reset(), UsbFTInterface::reset(), Proto40MHz_v1::reset(), A3PE::reset(), Croc::reset(), SpecsSlave::resetInternal(), FEB_v1::resetSpi(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Processus::storage(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), SpecsParallelBus::update(), SpecsInterface::update(), NI6008::update(), Computer::update(), UsbSpiBus::update(), UsbI2cBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), UsbFTMLInterface::update(), FEB_v1::update(), CU_v1::update(), UsbFTInterface::update(), Proto40MHz_v1::update(), Croc::update(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), ICPhaser::write(), Phaser::write(), and Hierarchy::~Hierarchy().
 return m_name; //< Get Object m_name
unsigned int Processus::nErrors () [inherited]
Get accessor to member m_nErrors
Returns
the current value of m_nErrors
Definition at line 86 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
Referenced by Processus::endProcessing().
                                
  return (m_state->nerrors++);
void Processus::openRootFile () [inherited]
Open Root file if needed
Definition at line 146 of file Processus.cpp.
References Options::dataFileFullName(), Options::dataStorage(), Object::info(), Processus::m_options, Processus::m_rootFile, and Object::name().
Referenced by UsbFTInterfaceTest::initialize(), RegisterTest::initialize(), PhaserRampExec::initialize(), and Processus::startProcessing().
                               
  if (m_options->dataStorage())
    m_rootFile = new TFile(m_options->dataFileFullName().c_str(),
                           "RECREATE",name().c_str());
        std::string mess=std::string("Opening root file ");
        mess.append(m_options->dataFileFullName());
        info(mess,"openRootFile");
  
StatusCode A3PE_BitFlip::randomValues () [protected]
Definition at line 169 of file A3PE_BitFlip.cpp.
References RAM::depth(), m_data, m_pga, m_toAX, A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), StatusCode::SUCCESS, and IOobject::write().
Referenced by execute().
                                       
  m_pga->setAXRamUsb(true);
  m_pga->setAddToAXRam(0);
  int depth=m_toAX->depth();
  for (int i=0; i<depth ; ++i)
    m_data[4*i ]=(unsigned int) ((float)rand()/RAND_MAX * 255.);
    m_data[4*i+1]=(unsigned int) ((float)rand()/RAND_MAX * 255.);
    m_data[4*i+2]=(unsigned int) ((float)rand()/RAND_MAX * 255.);
    m_data[4*i+3]=(unsigned int) ((float)rand()/RAND_MAX * 255.);
  
  m_toAX->write();
  return StatusCode::SUCCESS;
void Attrib::remove (int attribut) [inline, inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        toremove = iter;
      
    
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  
TFile* Processus::rootFile () [inline, inherited]
Get accessor to member m_rootFile
Returns
the current value of m_rootFile
Definition at line 258 of file Processus.h.
References Processus::m_rootFile.
                     
    return m_rootFile;
  
void Object::setDllName (std::string dllName) [inline, inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      
    m_dllName = dllName;
  
void Processus::setElement (Element * element) [inline, inherited]
Set accessor to member m_element
Parameters
element the new value for m_element
Definition at line 217 of file Processus.h.
References Processus::m_element, Processus::m_state, ProcState::nerrors, ProcState::nevent, ProcState::state, and ProcState::time.
Referenced by export_proc(), and Application::prepare().
                                     
    m_state = new ProcState ();
    m_state->nevent = 0;
    m_state->nerrors = 0;
    m_state->time = 0;
    strcpy(m_state->state,"");
    // setState(OK);
    m_element = element;
  
StatusCode A3PE_BitFlip::setFile (std::string filename) [inline]
Definition at line 30 of file A3PE_BitFlip.h.
References m_filename, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                         
    m_filename=filename;
    return StatusCode::SUCCESS;
  ;
void Object::setId (unsigned char id) [inline, inherited]
Definition at line 53 of file Object.h.
References Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
 m_id = id ; //< Set Object m_id
void Processus::setLogMsg (std::string logMsg) [inline, inherited]
Set accessor to member m_logMsg
Parameters
logMsg the new value for m_logMsg
Definition at line 283 of file Processus.h.
References Processus::m_logMsg.
                                    
    m_logMsg = logMsg;
  
void Object::setName (std::string name) [inline, inherited]
Definition at line 51 of file Object.h.
References Object::m_name.
Referenced by A3PE::A3PE(), A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), FePGA::MakeRAM(), FePGA::MakeRegister(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
 m_name = name ; //< Set Object m_name
void Processus::setNErrors (unsigned int nerr) [inherited]
Set accessor to member m_nErrors
Parameters
nErrors the new value for m_nErrors
Definition at line 79 of file Processus.cpp.
References Processus::m_state, and ProcState::nerrors.
Referenced by Processus::startProcessing().
                                             
  m_state->nerrors = nerr ;
void Processus::setState (int state) [inherited]
Set accessor to member m_state.state
Parameters
state the new value for m_state.state
Definition at line 174 of file Processus.cpp.
References Processus::elapsedTime(), Processus::ERR, Processus::m_options, Processus::m_state, Options::nErrors(), ProcState::nerrors, ProcState::nevent, Options::nEvt(), Processus::NOT_OK, Processus::OK, ProcState::state, and ProcState::time.
Referenced by Processus::endProcessing().
                                     
  m_state->nevent = m_options->nEvt();
  m_state->nerrors = m_options->nErrors();
  m_state->time = (float) (elapsedTime());
  switch (state)
  case OK:
    strcpy(m_state->state,"OK");
    break;
  case NOT_OK:
    strcpy(m_state->state,"NOT_OK");
    break;
  case ERR:
    strcpy(m_state->state,"ERROR");
  
void Processus::setStorage (std::string storage) [inline, inherited]
Set accessor to member m_storage
Parameters
storage the new value for m_storage
Definition at line 106 of file Processus.h.
References Processus::m_storage.
Referenced by export_proc().
                                      
    m_storage = storage;
  
void Object::setTitle (std::string title) [inline, inherited]
Definition at line 54 of file Object.h.
References Object::m_title.
Referenced by A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
 m_title = title ; //< Set Object m_title
void Object::setType (std::string type) [inline, inherited]
Definition at line 52 of file Object.h.
References Object::m_type.
Referenced by A3PE::A3PE(), A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
 m_type = type ; //< Set Object m_type
void Processus::startChrono () [inline, inherited]
Start processus time measurement
Definition at line 275 of file Processus.h.
References Processus::m_start.
Referenced by PhaserRampExec::initialize(), and Processus::startProcessing().
                    
    m_start = time(0);
  
StatusCode Processus::startProcessing () [inherited]
processus cmdline function processus virtual command function processus standard initialize function
Definition at line 93 of file Processus.cpp.
References Object::info(), Processus::initialize(), Processus::m_data, Processus::m_options, Object::name(), Processus::openRootFile(), Data::purge(), Processus::setNErrors(), Options::setNErrors(), and Processus::startChrono().
Referenced by export_proc(), and Application::prepare().
                                      
  info("=========================================================================
      =");
  info(" * " + name() + " *");
  m_options->setNErrors (0);
  setNErrors (0);
  m_data->purge();
#ifdef _NETWORK_
  if (0 != m_timerService)
    m_timerService->setRunning (true);
    m_timerService->timeHandler() ;
  
#endif
  // start measuring processus duration
  
  startChrono();
  openRootFile();
  return initialize();
std::string Processus::storage () [inline, inherited]
Get accessor to member m_storage
Returns
the current value of m_storage
Definition at line 205 of file Processus.h.
References Processus::m_storage, and Object::name().
Referenced by export_proc(), and Application::prepare().
                       
    if (0 == m_storage.compare(""))
    
      return name();
    
    return m_storage;
  
std::string Object::title () [inline, inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), and Application::terminate().
 return m_title; // < Get Object m_title
std::string Object::type () [inline, inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbSpiBus::init(), UsbI2cBus::init(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), and Hierarchy::tree().
 return m_type; //< Get Object m_type
void Object::verbose (std::string mymsg, std::string name) [inline, inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
 m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name);
void Object::verbose (std::string mymsg) [inline, inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTMLInterface::read(), UsbFTInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), wait(), UsbFTMLInterface::write(), and UsbFTInterface::write().
 m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name);
void Object::warning (std::string mymsg, std::string name) [inline, inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
 m_log.msgSvc (MsgSvc::WARNING , mymsg, name);
void Object::warning (std::string mymsg) [inline, inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), Processus::clean(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsMezzanine::date(), SpecsGlue::date(), SpecsSlave::detect(), NI6008::device(), UsbFTInterfaceTest::execute(), Acquisition::execute(), execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), SpecsSlave::init(), DCU::init(), TestUSB::initialize(), TestSPI::initialize(), TestI2C::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), initialize(), SpecsMezzanine::led(), SpecsGlue::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbSpiBus::read(), UsbI2cBus::read(), ICPhaser::read(), Phaser::read(), DCU::readMode(), SpecsSlave::reset(), SpecsMaster::reset(), DCU::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbSpiBus::write(), UsbI2cBus::write(), ICPhaser::write(), Phaser::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
 m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name);
Member Data Documentation
std::string Attrib::m_attribString[10] [protected, inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
Proto40MHz_v1* A3PE_BitFlip::m_board [private]
Definition at line 50 of file A3PE_BitFlip.h.
Referenced by initialize().
U8* A3PE_BitFlip::m_data [private]
Reimplemented from Processus.
Definition at line 64 of file A3PE_BitFlip.h.
Referenced by execute(), initialize(), and randomValues().
U8* A3PE_BitFlip::m_dataProcessed [private]
Definition at line 65 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
Element* Processus::m_element [protected, inherited]
Definition at line 348 of file Processus.h.
Referenced by Processus::clean(), Processus::element(), Processus::setElement(), and Processus::~Processus().
std::string A3PE_BitFlip::m_filename [private]
Definition at line 54 of file A3PE_BitFlip.h.
Referenced by execute(), file(), initialize(), and setFile().
RAM* A3PE_BitFlip::m_fromAX [private]
Definition at line 53 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
TH1D * A3PE_BitFlip::m_hErrorsLatency [private]
Definition at line 67 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
TH1D * A3PE_BitFlip::m_hErrorsWord [private]
Definition at line 67 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
TH1D* A3PE_BitFlip::m_hLatency [private]
Definition at line 67 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
unsigned int A3PE_BitFlip::m_latency [private]
Definition at line 57 of file A3PE_BitFlip.h.
Referenced by execute(), finalize(), and initialize().
unsigned int A3PE_BitFlip::m_latencyMax [private]
Definition at line 60 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
unsigned int A3PE_BitFlip::m_latencyMin [private]
Definition at line 59 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
unsigned int A3PE_BitFlip::m_length [private]
Definition at line 56 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
int A3PE_BitFlip::m_offset [private]
Definition at line 62 of file A3PE_BitFlip.h.
Referenced by execute(), and initialize().
A3PE* A3PE_BitFlip::m_pga [private]
Definition at line 51 of file A3PE_BitFlip.h.
Referenced by a3pe(), execute(), finalize(), initialize(), and randomValues().
RAM* A3PE_BitFlip::m_toAX [private]
Definition at line 52 of file A3PE_BitFlip.h.
Referenced by initialize(), and randomValues().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/inc/proc/A3PE_BitFlip.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/src/proc/A3PE_BitFlip.cpp