SeqPGA Class Reference
#include <SeqPGA.h>
Public Types
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
SeqPGA ()
virtual ~SeqPGA ()
void help ()
Destructor.
StatusCode init ()
void reset ()
void resetUsb ()
void update ()
UsbFTMLInterface * usb ()
UsbMLI2cBus * i2c ()
UsbMLSpiBus * spi ()
Register * reg ()
Register * setupReg ()
Register * masterI2cReg ()
Register * addI2cReg ()
StatusCode testSequence ()
StatusCode setExtTrig (bool)
bool extTrig ()
StatusCode setSpiGBTSCA (bool)
bool spiGBTSCA ()
StatusCode setSpiAdd (unsigned long int)
unsigned long int spiAdd ()
StatusCode setSpiSubAdd (unsigned long int)
unsigned long int spiSubAdd ()
StatusCode spiRead (unsigned int, unsigned int, unsigned int *)
StatusCode spiWrite (unsigned int, unsigned int, unsigned int *)
PyObject * spiRead (unsigned int, unsigned int)
StatusCode spiWrite (unsigned int, unsigned int, PyObject *)
unsigned int spiRead (unsigned int)
StatusCode spiWrite (unsigned int, unsigned int)
StatusCode setI2cGBTSCA (bool)
bool i2cGBTSCA ()
StatusCode setI2cBuffer (unsigned long int)
unsigned long int i2cBuffer ()
unsigned long int i2cData ()
StatusCode setI2cAdd (unsigned long int)
unsigned long int i2cAdd ()
StatusCode setI2cSubAdd (unsigned long int)
unsigned long int i2cSubAdd ()
StatusCode i2cRead ()
StatusCode i2cWrite ()
unsigned long int i2cRead (unsigned long int)
StatusCode i2cWrite (unsigned long int, unsigned long int)
StatusCode transmitSpi ()
void recursiveInitElement ()
void recursiveInitCommunications ()
StatusCode setConnection (Hierarchy *)
Hierarchy * connection ()
void clear ()
void setParent (Hierarchy *parent)
Hierarchy * parent ()
Hierarchy * parent (std::string)
Hierarchy * origin ()
virtual void addChild (Hierarchy *element)
std::vector< Hierarchy * > children ()
Hierarchy * child (std::string)
Hierarchy * childTyped (std::string)
unsigned long numberOfChildren ()
bool hasChildren ()
void delChild (Hierarchy *)
void delChild (std::string)
std::string path (std::string=std::string(``))
std::string pathTyped (std::string=std::string(``))
void tree (std::string indent=std::string(``))
void tree ()
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
Hierarchy * m_connection
std::string m_attribString [10]
Private Attributes
UsbFTMLInterface * m_usb
UsbMLI2cBus * m_usbi2c
UsbMLSpiBus * m_usbspi
Register * m_reg
Register * m_statusReg
Register * m_setupReg
Register * m_resetReg
Register * m_testSeqReg
RAM * m_txSpiFifo
RAM * m_rxSpiFifo
Register * m_addSpiReg
Register * m_ctrlSpiReg
Register * m_transmitSpiReg
unsigned int m_spiSubAdd
unsigned int m_i2cSubAdd
unsigned int m_i2cBuffer
Register * m_masterI2cReg
Register * m_addI2cReg
Detailed Description
Definition at line 23 of file SeqPGA.h.
Member Typedef Documentation
U16
typedef unsigned short SeqPGA::U16
Definition at line 26 of file SeqPGA.h.
U32
typedef unsigned long SeqPGA::U32
Definition at line 25 of file SeqPGA.h.
U8
typedef unsigned char SeqPGA::U8
Definition at line 27 of file SeqPGA.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
Constructor & Destructor Documentation
SeqPGA()
SeqPGA::SeqPGA ()
Definition at line 29 of file SeqPGA.cpp.
References Attrib::add(), Hierarchy::addChild(), IOdata::Byte, Object::debug(), IOdata::defDataU8(), Attrib::ELEMENT, Attrib::HARDWARE, IOobject::io(), m_addI2cReg, m_addSpiReg, m_ctrlSpiReg, m_masterI2cReg, m_reg, m_resetReg, m_rxSpiFifo, m_setupReg, m_statusReg, m_testSeqReg, m_transmitSpiReg, m_txSpiFifo, m_usb, m_usbi2c, m_usbspi, IOdata::setAddress(), IOobject::setAddress(), Object::setId(), Object::setName(), RAM::setSize(), Object::setType(), and IOdata::setWordSize().
              {
  setType("SeqPGA");
  setId(0);
  add(Attrib::ELEMENT); add (Attrib::HARDWARE);
  debug("SeqPGA built.","SeqPGA::SeqPGA");
  
  m_usb = new UsbFTMLInterface();
  m_usb->setName("Usb");
  addChild(m_usb);
  
  m_usbi2c=new UsbMLI2cBus();
  m_usbi2c->setName("UsbI2c");
  m_usb->addChild(m_usbi2c);
  
  m_usbspi=new UsbMLSpiBus();
  m_usbspi->setName("UsbSpi");
  m_usb->addChild(m_usbspi);
  
  m_reg=new Register();
  m_reg->io()->defDataU8(2);
  m_reg->setName("UsbTestReg");
  m_reg->setAddress(11);
  m_usb->addChild(m_reg);
   
  m_statusReg = new Register();
  m_statusReg ->setName("StatusReg");
  m_statusReg ->io()->defDataU8(2);
  m_statusReg ->io()->setAddress(7);
  m_statusReg ->io()->setWordSize(IOdata::Byte);
  m_usb ->addChild(m_statusReg);
  m_setupReg = new Register();
  m_setupReg ->setName("SetupReg");
  m_setupReg ->io()->defDataU8(2);
  m_setupReg ->io()->setAddress(8);
  m_setupReg ->io()->setWordSize(IOdata::Byte);
  m_usb ->addChild(m_setupReg);
  m_resetReg = new Register();
  m_resetReg ->setName("ResetReg");
  m_resetReg ->io()->defDataU8(2);
  m_resetReg ->io()->setAddress(14);
  m_resetReg ->io()->setWordSize(IOdata::Byte);
  m_usb ->addChild(m_resetReg);
  m_testSeqReg = new Register();
  m_testSeqReg ->setName("TestSeqReg");
  m_testSeqReg ->io()->defDataU8(2);
  m_testSeqReg ->io()->setAddress(12);
  m_testSeqReg ->io()->setWordSize(IOdata::Byte);
  m_usb ->addChild(m_testSeqReg);
  m_txSpiFifo = new RAM();
  m_rxSpiFifo = new RAM();
  m_addSpiReg = new Register();
  m_ctrlSpiReg = new Register();
  // m_subAddSpiReg = new Register();
  m_transmitSpiReg = new Register();
  
  m_txSpiFifo ->setName("TxSpiFifo");
  m_rxSpiFifo ->setName("RxSpiFifo");
  m_addSpiReg ->setName("AddSpiReg");
  m_ctrlSpiReg ->setName("CtrlSpiReg");
  // m_subAddSpiReg ->setName("SubAddSpiReg");
  m_transmitSpiReg ->setName("TransmitSpiReg");
  
  m_txSpiFifo ->setSize(16,2);
  m_rxSpiFifo ->setSize(16,1);
  m_addSpiReg ->io()->defDataU8(2);
  m_ctrlSpiReg ->io()->defDataU8(2);
  // m_subAddSpiReg ->io()->defDataU8(2);
  m_transmitSpiReg ->io()->defDataU8(2);
  
  m_txSpiFifo ->io()->setAddress(2);
  m_rxSpiFifo ->io()->setAddress(4);
  m_addSpiReg ->io()->setAddress(6);
  m_ctrlSpiReg ->io()->setAddress(5);
  // m_subAddSpiReg ->io()->setAddress(3);
  m_transmitSpiReg ->io()->setAddress(10);
  
  m_addSpiReg ->io()->setWordSize(IOdata::Byte);
  m_ctrlSpiReg ->io()->setWordSize(IOdata::Byte);
  // m_subAddSpiReg ->io()->setWordSize(IOdata::Byte);
  m_transmitSpiReg ->io()->setWordSize(
      IOdata::Byte);
  
  m_usb->addChild(m_txSpiFifo);
  m_usb->addChild(m_rxSpiFifo);
  m_usb->addChild(m_addSpiReg);
  m_usb->addChild(m_ctrlSpiReg);
  // m_usb->addChild(m_subAddSpiReg);
  m_usb->addChild(m_transmitSpiReg);
  m_masterI2cReg = new Register();
  m_masterI2cReg ->setName("I2cMasterI2cReg");
  m_masterI2cReg ->io()->defDataU8(3);
  m_masterI2cReg ->io()->setAddress(9);
  m_masterI2cReg ->io()->setWordSize(IOdata::Byte);
  m_addI2cReg = new Register();
  m_addI2cReg ->setName("AddI2cReg");
  m_addI2cReg ->io()->defDataU8(2);
  m_addI2cReg ->io()->setAddress(1);
  m_addI2cReg ->io()->setWordSize(IOdata::Byte);
  m_usb->addChild(m_masterI2cReg);
  m_usb->addChild(m_addI2cReg);
}
 SeqPGA()
virtual SeqPGA::~SeqPGA () [inline], [virtual]
Definition at line 31 of file SeqPGA.h.
{};
Member Function Documentation
add()
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA(), TestI2C::setAddress(), TestSPI::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
addChild()
void Hierarchy::addChild (Hierarchy * element) [virtual], [inherited]
Definition at line 83 of file Hierarchy.cpp.
References Object::debug(), Hierarchy::m_children, Object::name(), and Hierarchy::setParent().
Referenced by A3PE::A3PE(), SpecsMezzanine::addBus(), SpecsSlave::addI2c(), Application::create(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Hierarchy::origin(), Phaser::Phaser(), Proto40MHz_v1::Proto40MHz_v1(), SeqPGA(), SpecsMezzanine::SpecsMezzanine(), UsbI2cBus::UsbI2cBus(), and UsbSpiBus::UsbSpiBus().
                                          {
  element->setParent(this);
  m_children.push_back(element);
  debug(element->name()+" added to the child tree.","Hierarchy::addChild");
}
addI2cReg()
Register* SeqPGA::addI2cReg () [inline]
Definition at line 94 of file SeqPGA.h.
References m_addI2cReg.
Referenced by BOOST_PYTHON_MODULE().
{ return m_addI2cReg; }
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
child()
Hierarchy * Hierarchy::child (std::string path) [inherited]
Definition at line 133 of file Hierarchy.cpp.
References Hierarchy::child(), Hierarchy::children(), Object::name(), Hierarchy::origin(), Hierarchy::parent(), Hierarchy::path(), and Object::warning().
Referenced by Application::cd(), Hierarchy::child(), Hierarchy::children(), and export_obj().
                                         {
  std::string newpath = path;
  std::string up("..");
  std::string separator(1,'/');
  Hierarchy * newcurrent = 0;
  // info("path="+path,"Hierarchy::child");
  if (path.compare("")==0 || path.compare("/")==0) {
    // debug("return origin","Hierarchy::child");
    return origin();
  }
  if (path.compare(name())==0){
    // debug("return itself","Hierarchy::child");
    return this;
  }
  if (path.compare("..")==0){
    if (0!=this->parent()) return this->parent();
    else return this;
  }
  if (path.compare("../")==0){
    if (0!=this->parent()) return this->parent();
    else return this;
  }
  int npos=path.find(separator,0);
  // info("find separator in "+itos(npos)+" of "+path,"Hierarchy::child");
  // remove last separator
  if (npos == (int)(path.size()-1)) {
    newpath = std::string(path,0,npos);
    path = newpath;
  }
  if (npos==0){
    // debug("Going back to origin and calling child","Hierarchy::child");
    newpath=std::string(path,1,path.size()-1);
    return origin()->child(newpath);
  }
  else{
    if (npos== (int)(std::string::npos)){
      // debug("Getting chid "+path+" of "+this->name(),"Hierarchy::child");
      std::vector <Hierarchy*> list = children();
      std::vector<Hierarchy*>::iterator iter;
      for (iter=list.begin();iter!=list.end();iter++){
        if ((*iter)->name().compare(path)==0){
          return *iter;
        }
      }
      warning(this->name()+std::string(" has no child '")+path+"'","Hierarchy::child");
      return this;
    }
    else
    {
      int ipos=path.find(separator,0);
      // info("default behaviour "+path+" with separator in "+itos(ipos),"Hierarchy::child");
      std::string newcurrentname=std::string(path,0,ipos);
      newpath=std::string(path,ipos+1,path.size()-1);
      // info("looking now for "+newpath+" from "+newcurrentname,"Hierarchy::child");
      if (0==newcurrentname.compare(origin()->name())){
        // info("current is computer. Looking for children"+newcurrentname,"Hierarchy::child");
        return origin()->child(newpath);
      }
      newcurrent = (Hierarchy*)0;
      std::vector <Hierarchy*> list = children();
      std::vector<Hierarchy*>::iterator iter;
      for (iter=list.begin();iter!=list.end();iter++){
        if ((*iter)->name().compare(newcurrentname)==0){
          newcurrent = (*iter);
        }
      }
      if ((Hierarchy*)0==newcurrent){
        if (newcurrentname.compare("..")==0 && 0!=parent()){
          newcurrent=this->parent();
          // debug("newcurrent was .. -> parent="+parent()->name());
        }
        else
        {
          warning(this->name()+" has no child '"+newcurrentname+"'",
              "Hierarchy::child");
          return this;
        }
      }
      // debug("recurrence call for "+newpath+" on "+newcurrent->name(),"Hierarchy::child");
      return newcurrent -> child (newpath);
    }
  }
}
children()
std::vector<Hierarchy*> Hierarchy::children () [inline], [inherited]
Definition at line 33 of file Hierarchy.h.
References Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::delChild(), Hierarchy::hasChildren(), Hierarchy::m_children, Hierarchy::numberOfChildren(), Hierarchy::path(), Hierarchy::pathTyped(), and Hierarchy::tree().
Referenced by Hierarchy::child(), Hierarchy::childTyped(), export_obj(), SpecsSlave::recursiveInitCommunications(), Element::recursiveInitCommunications(), Element::recursiveInitElement(), Application::setConfig(), and Hierarchy::tree().
{ return m_children; } //< get list of child(ren)
childTyped()
Hierarchy * Hierarchy::childTyped (std::string path) [inherited]
Definition at line 239 of file Hierarchy.cpp.
References Hierarchy::children(), Hierarchy::m_origin, Object::name(), Hierarchy::parent(), Hierarchy::path(), and Object::warning().
Referenced by Hierarchy::children(), and export_obj().
                                              {
  std::string newpath = path;
  std::string up("..");
  std::string separator(1,'/');
  std::string typeopen(1,'[');
  std::string typeclose(1,']');
  Hierarchy * newcurrent = 0;
  unsigned int npos=path.find(separator,0);
  unsigned int opos=path.find(typeopen,0);
  if (npos==std::string::npos || npos == path.size()-1){
    if (path.compare("..")==0) {
      return parent();
    }
    if (npos == path.size()-1) {
      newpath = std::string(path,0,opos);
      path = newpath;
    }
    std::vector < Hierarchy* > list = children();
    std::vector < Hierarchy* >::iterator iter;
    for (iter=list.begin();iter!=list.end();iter++){
      std::string notypepath = std::string(path,0,opos);
      if ((*iter)->name().compare(notypepath)==0){
        return *iter;
      }
    }
    warning(this->name()+std::string(" has no child ") +path,"Hierarchy::child");
    return 0;
  }
  else {
    if (std::string(path,0,3).compare(std::string("../"))==0) {
      newpath=std::string(path,3,path.size()-3);
      newcurrent = parent();
    }
    if (std::string(path,0,1).compare(std::string("/"))==0) {
      newpath=std::string(path,1,path.size()-1);
      newcurrent = (Hierarchy*) m_origin;
    }
    if ((std::string(path,0,3).compare(std::string("../")) !=0) &&
        std::string(path,0,1).compare(std::string("/"))!=0) {
      opos = path.find(typeopen,0);
      int cpos = path.find(typeclose,0);
      std::string name = std::string (path,0,opos);
      newcurrent = childTyped(name);
      if (newcurrent ==0){
        warning(path+": no child found with such a name","Hierarchy::child");
      }
      newpath = std::string (path,cpos+2,path.size()-cpos-1);
    }
    return newcurrent -> childTyped (newpath);
  }
}
clear()
void Hierarchy::clear () [inherited]
Definition at line 35 of file Hierarchy.cpp.
References Hierarchy::delChild(), Object::info(), Hierarchy::m_children, and Object::name().
Referenced by export_obj().
                     {
  std::vector<Hierarchy*> listlocale;
  std::vector<Hierarchy*>::iterator iter;
  info("loop on "+name()+" children.","Hierarchy::clear");
  for (iter=m_children.begin();iter!=m_children.end();iter++){
      info("processing "+(*iter)->name()+".","Hierarchy::clear");
/*
      (*iter)->clear();
// this->delChild((*iter));
      info("obj "+(*iter)->name()+" being cleared.","Hierarchy::clear");
      delete (*iter);
      info("Object deleted.","Hierarchy::clear");
      m_children.erase(iter);
      info("Object removed from the tree.","Hierarchy::clear");
*/
    (*iter)->clear();
    info("Adding object "+(*iter)->name()+" from the Hierarchy to the list of deleted objects.","
      Hierarchy::clear");
    listlocale.push_back((*iter));
  }
  for (iter=listlocale.begin();iter!=listlocale.end();iter++){
    info("Removing object "+(*iter)->name()+".","Hierarchy::clear");
    this->delChild(*iter);
// m_children.erase(iter);
    delete (*iter);
  }
  info("Getting out of "+name());
}
connection()
Hierarchy * Element::connection () [inherited]
Get IO interface
Definition at line 84 of file Element.cpp.
References Element::m_connection, Object::name(), and Object::warning().
Referenced by UsbSpiBus::clockDivider(), export_obj(), UsbI2cBus::read(), IOobject::read(), UsbSpiBus::read(), UsbSpiBus::setClockDivider(), Element::setConnection(), UsbI2cBus::write(), IOobject::write(), and UsbSpiBus::write().
                              {
  if (0==m_connection){
    warning("no connection defined for "+name()+".","Element::connection");
    return (Hierarchy*)0;
  }
  return m_connection;
}
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), i2cRead(), FePGA::i2cWrite(), i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), A3PE::internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), SpecsMaster::reset(), SpecsSlave::reset(), FEB_v1::resetUsb(), SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
delChild() [1/2]
void Hierarchy::delChild (Hierarchy * element) [inherited]
Definition at line 92 of file Hierarchy.cpp.
References Object::debug(), and Hierarchy::m_children.
Referenced by Hierarchy::children(), Hierarchy::clear(), export_obj(), and Hierarchy::~Hierarchy().
                                          {
  bool flag=false;
  std::vector<Hierarchy*>::iterator iter,remove;
  for (iter=m_children.begin();(iter!=m_children.end());iter++){
    if (*iter==element){
      remove=iter;
      flag=true;
    }
  }
  if (flag){
    debug("removing "+(*remove)->name()+" from the tree.","Hierarchy::delChild");
    m_children.erase(remove);
  }
}
delChild() [2/2]
void Hierarchy::delChild (std::string n) [inherited]
Definition at line 110 of file Hierarchy.cpp.
References Object::debug(), and Hierarchy::m_children.
                                   {
  bool flag=false;
  std::vector<Hierarchy*>::iterator iter,remove;
  for (iter=m_children.begin();iter!=m_children.end();iter++){
    if ((*iter)->name()==n){ remove=iter; flag=true;}
  }
  if (flag){
    debug("removing "+(*remove)->name()+" from the tree.","Hierarchy::delChild");
    m_children.erase(remove);
  }
}
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
extTrig()
bool SeqPGA::extTrig ()
Definition at line 151 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), m_setupReg, and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), FEB_v1::extTrig(), and testSequence().
                     {
  m_setupReg->read();
  /*
    if (StatusCode::SUCCESS == m_setupReg->read()) {
    error("I2c register setupReg error", "UsbMLI2cBus::spiGBTSCA");
    return false;
    }*/
  return ((m_setupReg->io()->dataU8(0) >> 3) & 1) ;
}
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
hasChildren()
bool Hierarchy::hasChildren () [inherited]
Definition at line 303 of file Hierarchy.cpp.
References Hierarchy::m_children.
Referenced by Hierarchy::children(), and export_obj().
                              {
  return (m_children.size()>0);
}
help()
void SeqPGA::help () [inline], [virtual]
Destructor.
printout help for the element
Implements Element.
Definition at line 36 of file SeqPGA.h.
References Object::info(), and Object::name().
{ info("SeqPGA "+name()+". No help.","SeqPGA::help"); };
i2c()
UsbMLI2cBus* SeqPGA::i2c () [inline]
Definition at line 79 of file SeqPGA.h.
References m_usbi2c.
Referenced by BOOST_PYTHON_MODULE().
                    {
    return m_usbi2c;
  }
i2cAdd()
unsigned long int SeqPGA::i2cAdd ()
Definition at line 450 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), m_addI2cReg, and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                                {
  m_addI2cReg->read();
  return (m_addI2cReg->io()->dataU8(0) + (m_addI2cReg->
      io()->dataU8(1)<<8)) ;
}
i2cBuffer()
unsigned long int SeqPGA::i2cBuffer ()
Definition at line 427 of file SeqPGA.cpp.
References m_i2cBuffer.
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                                   {
  return m_i2cBuffer;
}
i2cData()
unsigned long int SeqPGA::i2cData ()
Definition at line 435 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), and m_masterI2cReg.
Referenced by BOOST_PYTHON_MODULE(), i2cRead(), and testSequence().
                                 {
  // m_masterI2cReg->io()->dump(0);
  return (((m_masterI2cReg->io()->dataU8(0))&0xFF)) ;
}
i2cGBTSCA()
bool SeqPGA::i2cGBTSCA ()
Definition at line 413 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), m_setupReg, and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                       {
  m_setupReg->read();
  return (! (m_setupReg->io()->dataU8(0) & 1)) ;
}
i2cRead() [1/2]
StatusCode SeqPGA::i2cRead ()
Definition at line 472 of file SeqPGA.cpp.
References shell::data(), IOdata::dataU8(), Object::debug(), IOdata::defDataU8(), IOobject::io(), m_i2cSubAdd, m_masterI2cReg, m_setupReg, IOobject::read(), IOdata::setU8(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), TestI2C::execute(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), i2cRead(), and testSequence().
                           {
  debug("setting position of read i2c protocol","i2c read");
  m_setupReg->read();
  unsigned int data = m_setupReg->io()->dataU8()[0];
  data |= (1 << 2) ;
  m_setupReg->io()->setU8(0,data);
  m_setupReg->write();
    
  debug("setting subadd value in the frame","i2c write");
  m_masterI2cReg->io()->defDataU8(2);
  m_masterI2cReg->io()->setU8(0,m_i2cSubAdd&0xFF);
  m_masterI2cReg->io()->setU8(1,(m_i2cSubAdd>>8)&0xFF);
  // m_masterI2cReg->io()->dump(0);
  debug("i2c write of the register","i2c read");
  m_masterI2cReg->write();
  debug("i2c read of the addressed register","i2c read");
  m_masterI2cReg->io()->defDataU8(1);
  m_masterI2cReg->read();
  // m_masterI2cReg->io()->dump(0);
  return StatusCode::SUCCESS;
}
i2cRead() [2/2]
unsigned long int SeqPGA::i2cRead (unsigned long int subadd)
Definition at line 518 of file SeqPGA.cpp.
References i2cData(), i2cRead(), and setI2cSubAdd().
                                                         {
  setI2cSubAdd(subadd);
  i2cRead();
  return i2cData();
}
i2cSubAdd()
unsigned long int SeqPGA::i2cSubAdd ()
Definition at line 464 of file SeqPGA.cpp.
References m_i2cSubAdd.
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                                   {
  return m_i2cSubAdd;
}
i2cWrite() [1/2]
StatusCode SeqPGA::i2cWrite ()
Definition at line 497 of file SeqPGA.cpp.
References shell::data(), IOdata::dataU8(), Object::debug(), IOdata::defDataU8(), IOobject::io(), m_i2cBuffer, m_i2cSubAdd, m_masterI2cReg, m_setupReg, IOobject::read(), IOdata::setU8(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), TestI2C::execute(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtDLLReset(), i2cWrite(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), and testSequence().
                           {
  debug("setting position of write i2c protocol","i2c write");
  m_setupReg->read();
  unsigned int data = m_setupReg->io()->dataU8()[0];
  data &= ~(1 << 2) ;
  m_setupReg->io()->setU8(0,data);
  m_setupReg->write();
  debug("setting subadd value in the frame","i2c write");
  m_masterI2cReg->io()->defDataU8(3);
  m_masterI2cReg->io()->setU8(0,m_i2cSubAdd&0xFF);
  m_masterI2cReg->io()->setU8(1,(m_i2cSubAdd>>8)&0xFF);
  debug("setting buffer value in the frame","i2c write");
  m_masterI2cReg->io()->setU8(2,m_i2cBuffer&0xFF);
  // m_masterI2cReg->io()->dump(0);
  debug("i2c write","i2c write");
  return m_masterI2cReg->write();
}
i2cWrite() [2/2]
StatusCode SeqPGA::i2cWrite (unsigned long int subadd, unsigned long int value)
Definition at line 524 of file SeqPGA.cpp.
References i2cWrite(), setI2cBuffer(), and setI2cSubAdd().
                                                                            {
  setI2cSubAdd(subadd);
  setI2cBuffer(value);
  return i2cWrite();
}
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTMLInterface::close(), UsbFTInterface::close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), UsbFTMLInterface::help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), MSOxxxx::id(), Croc::init(), NI6008::init(), Computer::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbI2cBus::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), FePGA::reset(), reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), FEB_v1::resetFifoSpyFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), resetUsb(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FEB_v1::testDuration(), testSequence(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
init()
StatusCode SeqPGA::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 42 of file SeqPGA.h.
References StatusCode::SUCCESS.
                    {
    return StatusCode::SUCCESS;
  };
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
masterI2cReg()
Register* SeqPGA::masterI2cReg () [inline]
Definition at line 93 of file SeqPGA.h.
References m_masterI2cReg.
Referenced by BOOST_PYTHON_MODULE().
{ return m_masterI2cReg; }
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), help(), NI6008::help(), Computer::help(), SpecsParallelBus::help(), UsbFTInterface::help(), UsbFTMLInterface::help(), Phaser::help(), ICPhaser::help(), A3PE::help(), Data::hist2d(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), CU_v1::reset(), UsbSpiBus::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), A3PE::reset(), SpecsSlave::resetInternal(), FEB_v1::resetUsb(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), Object::setName(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTMLInterface::update(), UsbFTInterface::update(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
numberOfChildren()
unsigned long Hierarchy::numberOfChildren () [inherited]
Definition at line 125 of file Hierarchy.cpp.
References Hierarchy::m_children.
Referenced by Hierarchy::children(), and export_obj().
                                           {
  return m_children.size();
}
origin()
Hierarchy* Hierarchy::origin () [inline], [inherited]
Definition at line 30 of file Hierarchy.h.
References Hierarchy::addChild(), and Hierarchy::m_origin.
Referenced by Hierarchy::child(), export_obj(), and Hierarchy::setParent().
{ return m_origin; } //< Get the origin of the tree
parent() [1/2]
Hierarchy* Hierarchy::parent () [inline], [inherited]
Definition at line 28 of file Hierarchy.h.
References Hierarchy::m_parent.
Referenced by Hierarchy::child(), Hierarchy::childTyped(), export_obj(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), IOobject::init(), Hierarchy::parent(), Hierarchy::path(), Hierarchy::pathTyped(), Element::setConnection(), Hierarchy::setParent(), SpecsInterface::specsMaster(), SpecsInterface::specsMasterDevice(), SpecsInterface::specsSlave(), SpecsInterface::specsSlaveDevice(), and Hierarchy::~Hierarchy().
{ return m_parent; } //< Get Hierarchy Parent
parent() [2/2]
Hierarchy * Hierarchy::parent (std::string type) [inherited]
Definition at line 327 of file Hierarchy.cpp.
References Hierarchy::parent(), and Object::type().
                                            {
  Hierarchy *parent = this->parent();
  if (0 != parent){
    if (parent->type().compare(type)==0) {
      return parent;
    }
    else
      return parent->parent(type);
  }
  else {
    return (Hierarchy*)NULL;
  }
}
path()
std::string Hierarchy::path (std::string str = std::string(``)) [inherited]
Definition at line 344 of file Hierarchy.cpp.
References Hierarchy::m_parent, Object::name(), Hierarchy::parent(), and Hierarchy::path().
Referenced by Hierarchy::child(), Hierarchy::children(), Hierarchy::childTyped(), export_obj(), Hierarchy::path(), UsbFTMLInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), and UsbFTMLInterface::usbWriteU8().
                                      {
  str="/"+name()+str;
  Hierarchy *m_parent=parent();
  if (0!=m_parent){
    return m_parent->path(str);
  }
  return str;
}
pathTyped()
std::string Hierarchy::pathTyped (std::string str = std::string(``)) [inherited]
Definition at line 356 of file Hierarchy.cpp.
References Hierarchy::m_parent, Object::name(), Hierarchy::parent(), Hierarchy::pathTyped(), and Object::type().
Referenced by Hierarchy::children(), export_obj(), and Hierarchy::pathTyped().
                                           {
  Hierarchy *m_parent=parent();
  if (0!=m_parent){
    str="/"+name()+"["+type()+"]"+str;
    return m_parent->pathTyped(str);
  }
  return str;
}
recursiveInitCommunications()
void Element::recursiveInitCommunications () [inherited]
Triggers a recursive call to initCommunications() for the full hierarchy
Returns
void
Definition at line 44 of file Element.cpp.
References Hierarchy::children().
Referenced by export_obj().
                                         {
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::const_iterator iter;
  for (iter=list.begin();iter!=list.end();iter++){
    dynamic_cast<Element*>((*iter))->recursiveInitCommunications();
  }
}
recursiveInitElement()
void Element::recursiveInitElement () [inherited]
Triggers a recursive call to init() for the full hierarchy
Returns
void
Definition at line 32 of file Element.cpp.
References Hierarchy::children(), and Element::init().
Referenced by export_obj().
                                  {
  init();
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter){
    dynamic_cast<Element*>((*iter))->recursiveInitElement();
  }
}
reg()
Register* SeqPGA::reg () [inline]
Definition at line 87 of file SeqPGA.h.
References m_reg.
Referenced by BOOST_PYTHON_MODULE().
                 {
    return m_reg;
  }
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
reset()
void SeqPGA::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 54 of file SeqPGA.h.
References Object::info(), IOobject::io(), m_resetReg, IOdata::setU8(), and IOobject::write().
Referenced by FEB_v1::reset().
               {
    info("FEB reset.");
    m_resetReg->io()->setU8(0,1);
    m_resetReg->io()->setU8(1,0);
    m_resetReg->write();
  };
resetUsb()
void SeqPGA::resetUsb () [inline]
Definition at line 61 of file SeqPGA.h.
References IOobject::dump(), Object::info(), IOobject::io(), m_resetReg, IOdata::setU8(), and IOobject::write().
Referenced by FEB_v1::resetUsb().
                  {
    info("Usb TxRx reset.");
    m_resetReg->io()->setU8(0,2);
    m_resetReg->io()->setU8(1,0);
    m_resetReg->dump();
    m_resetReg->write();
  };
setConnection()
StatusCode Element::setConnection (Hierarchy * connection) [inherited]
Define IO interface
Definition at line 55 of file Element.cpp.
References Element::connection(), Object::debug(), StatusCode::FAILURE, Object::fatal(), Attrib::INTERFACE, Attrib::is(), Element::m_connection, Object::name(), Hierarchy::parent(), StatusCode::SUCCESS, and Object::type().
Referenced by export_obj(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), and IOobject::init().
                                                      {
  if (0==connection){
    fatal("Try to define a connection with a null pointer.",
        "Element::setConnection");
    return StatusCode::FAILURE;
  }
  if (connection->is(Attrib::INTERFACE)){
    m_connection=dynamic_cast<Hierarchy*>(connection);
    return StatusCode::SUCCESS;
  }
  else {
    debug(connection->name()+
        " is not a Attrib::INTERFACE hardware. Connection refused.",
        "Element::setConnection");
    if (0!=connection->parent()){
      return setConnection(connection->parent());
    }
    else{
      fatal("Could not find a connection for element "+
          name()+"["+type()+"].","element::setConnection");
      return StatusCode::FAILURE;
    }
  }
}
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setExtTrig()
StatusCode SeqPGA::setExtTrig (bool value)
Definition at line 142 of file SeqPGA.cpp.
References shell::data(), IOdata::dataU8(), IOobject::io(), m_setupReg, IOobject::read(), IOdata::setU8(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), FEB_v1::setExtTrig(), and testSequence().
                                         {
  m_setupReg->read();
  unsigned int data=m_setupReg->io()->dataU8()[0];
  if (value) data |= 8 ;
  else data &= ~8 ;
  m_setupReg->io()->setU8(0,data);
  return m_setupReg->write();
}
setI2cAdd()
StatusCode SeqPGA::setI2cAdd (unsigned long int value)
Definition at line 444 of file SeqPGA.cpp.
References IOobject::io(), m_addI2cReg, IOdata::setU8(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), TestI2C::initialize(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), and testSequence().
                                                     {
  m_addI2cReg->io()->setU8(0,value&0xFF);
  m_addI2cReg->io()->setU8(1,(value&0xFF00)>>8);
  return m_addI2cReg->write();
}
setI2cBuffer()
StatusCode SeqPGA::setI2cBuffer (unsigned long int value)
Definition at line 422 of file SeqPGA.cpp.
References m_i2cBuffer, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), i2cWrite(), and testSequence().
                                                        {
  m_i2cBuffer = value;
  return StatusCode::SUCCESS;
}
setI2cGBTSCA()
StatusCode SeqPGA::setI2cGBTSCA (bool value)
Definition at line 404 of file SeqPGA.cpp.
References shell::data(), IOdata::dataU8(), IOobject::io(), m_setupReg, IOobject::read(), IOdata::setU8(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                                           {
  m_setupReg->read();
  unsigned int data=m_setupReg->io()->dataU8()[0];
  if (!value) data |= 1 ;
  else data &= ~1 ;
  m_setupReg->io()->setU8(0,data);
  return m_setupReg->write();
}
setI2cSubAdd()
StatusCode SeqPGA::setI2cSubAdd (unsigned long int value)
Definition at line 459 of file SeqPGA.cpp.
References m_i2cSubAdd, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), i2cRead(), i2cWrite(), and testSequence().
                                                        {
  m_i2cSubAdd = value;
  return StatusCode::SUCCESS;
}
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setParent()
void Hierarchy::setParent (Hierarchy * parent) [inherited]
Definition at line 67 of file Hierarchy.cpp.
References Hierarchy::m_origin, Hierarchy::m_parent, Hierarchy::origin(), and Hierarchy::parent().
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Computer::Computer(), Application::create(), export_obj(), and SpecsMezzanine::SpecsMezzanine().
                                              {
  m_parent = parent;
  if ((Hierarchy*)0==parent) return;
  Hierarchy *curr = this;
  Hierarchy *prev = parent;
  while (prev != 0){
    curr = prev;
    prev = curr->parent();
  }
  if (parent->origin()!=0) m_origin=parent->origin();
}
setSpiAdd()
StatusCode SeqPGA::setSpiAdd (unsigned long int value)
Definition at line 219 of file SeqPGA.cpp.
References IOobject::io(), m_addSpiReg, IOdata::setU8(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), FEB_v1::calibCte(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), FEB_v1::clockPhaseEport(), FEB_v1::disableSubtract(), FEB_v1::enableBXIDReset(), FEB_v1::gain4(), FEB_v1::globalPseudoPMEnable(), TestSPI::initialize(), FEB_v1::injectModeFE(), FEB_v1::latency(), FEB_v1::latencyEport(), FEB_v1::latencyLLT(), FEB_v1::maskLLT(), FEB_v1::oldSubtract(), FEB_v1::probeEnable(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), FEB_v1::resetFE(), FEB_v1::resetFifoInjectFE(), FEB_v1::resetFifoSpyFE(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), FEB_v1::setClockFallingEdge(), FEB_v1::setDisableSubtract(), FEB_v1::setEnableBXIDReset(), FEB_v1::setGain4(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), FEB_v1::setLatency(), FEB_v1::setLatencyLLT(), FEB_v1::setLatencyLLTCorner(), FEB_v1::setLatencyLLTSideNb(), FEB_v1::setLatencyLLTUpNb(), FEB_v1::setMaskLLT(), FEB_v1::setMaskLLTCorner(), FEB_v1::setMaskLLTSideNb(), FEB_v1::setMaskLLTUpNb(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), FEB_v1::setSpyModeSeq(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), FEB_v1::setThreshold(), FEB_v1::spareForTrigEnable(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), FEB_v1::testDuration(), testSequence(), FEB_v1::threshold(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLT().
                                                     {
  m_addSpiReg->io()->setU8(0,value&0xFF);
  m_addSpiReg->io()->setU8(1,(value>>8) & 0xFF);
  return m_addSpiReg->write();
}
setSpiGBTSCA()
StatusCode SeqPGA::setSpiGBTSCA (bool value)
Definition at line 165 of file SeqPGA.cpp.
References shell::data(), IOdata::dataU8(), IOobject::io(), m_setupReg, IOobject::read(), IOdata::setU8(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), and testSequence().
                                           {
  m_setupReg->read();
  unsigned int data=m_setupReg->io()->dataU8()[0];
  if (!value) data |= 2 ;
  else data &= ~2 ;
  m_setupReg->io()->setU8(0,data);
  return m_setupReg->write();
}
setSpiSubAdd()
StatusCode SeqPGA::setSpiSubAdd (unsigned long int value)
Definition at line 240 of file SeqPGA.cpp.
References m_spiSubAdd.
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                                                        {
  m_spiSubAdd = value & 0x7F;
}
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
setupReg()
Register* SeqPGA::setupReg () [inline]
Definition at line 91 of file SeqPGA.h.
References m_setupReg.
Referenced by BOOST_PYTHON_MODULE(), TestUSB::initialize(), and TestI2C::initialize().
{ return m_setupReg; }
spi()
UsbMLSpiBus* SeqPGA::spi () [inline]
Definition at line 83 of file SeqPGA.h.
References m_usbspi.
Referenced by BOOST_PYTHON_MODULE().
                    {
    return m_usbspi;
  }
spiAdd()
unsigned long int SeqPGA::spiAdd ()
Definition at line 225 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), m_addSpiReg, and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                                {
  m_addSpiReg->read();
  /*
    if (StatusCode::SUCCESS == m_txSpiReg->read()) {
    error("TX register txSpiReg error", "UsbMLSpiBus::dataTx");
    return false;
    }
  */
  return (m_addSpiReg->io()->dataU8(0) + (m_addSpiReg->
      io()->dataU8(1)<<8)) ;
}
spiGBTSCA()
bool SeqPGA::spiGBTSCA ()
Definition at line 174 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), m_setupReg, and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                       {
  m_setupReg->read();
  /*
    if (StatusCode::SUCCESS == m_setupReg->read()) {
    error("I2c register setupReg error", "UsbMLI2cBus::spiGBTSCA");
    return false;
    }*/
  return (! (m_setupReg->io()->dataU8(0) & 2)) ;
}
spiRead() [1/3]
StatusCode SeqPGA::spiRead (unsigned int subadd, unsigned int nwords, unsigned int * values)
Definition at line 299 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), m_ctrlSpiReg, m_rxSpiFifo, m_transmitSpiReg, m_txSpiFifo, IOobject::read(), RAM::setSize(), IOdata::setU8(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), FEB_v1::calibCte(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), FEB_v1::clockPhaseEport(), FEB_v1::disableSubtract(), FEB_v1::enableBXIDReset(), TestSPI::execute(), FEB_v1::gain4(), FEB_v1::globalPseudoPMEnable(), FEB_v1::injectModeFE(), FEB_v1::latency(), FEB_v1::latencyEport(), FEB_v1::latencyLLT(), FEB_v1::maskLLT(), FEB_v1::oldSubtract(), FEB_v1::probeEnable(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), FEB_v1::readFifo(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), FEB_v1::setClockFallingEdge(), FEB_v1::setDisableSubtract(), FEB_v1::setEnableBXIDReset(), FEB_v1::setGain4(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), FEB_v1::setLatency(), FEB_v1::setLatencyLLT(), FEB_v1::setLatencyLLTCorner(), FEB_v1::setLatencyLLTSideNb(), FEB_v1::setLatencyLLTUpNb(), FEB_v1::setMaskLLT(), FEB_v1::setMaskLLTCorner(), FEB_v1::setMaskLLTSideNb(), FEB_v1::setMaskLLTUpNb(), FEB_v1::setOldSubtract(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), FEB_v1::setSpyModeSeq(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), FEB_v1::setThreshold(), FEB_v1::spareForTrigEnable(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), FEB_v1::testDuration(), testSequence(), and FEB_v1::threshold().
                                                                                          {
  unsigned int val = subadd | 0x80 ;
  m_txSpiFifo->setSize(16,1);
  m_rxSpiFifo->setSize(16,nwords+1);
  m_ctrlSpiReg->io()->setU8(0,(nwords+1)&0xFF);
  m_ctrlSpiReg->io()->setU8(1,((nwords+1)>>8)&0xFF);
  m_ctrlSpiReg->write();
  m_txSpiFifo->io()->setU8(0,val);
  m_txSpiFifo->io()->setU8(1,0);
  m_txSpiFifo->write();
  StatusCode status = m_transmitSpiReg->write();
  // usleep(100000);
  m_rxSpiFifo->read();
  for (int w=0; w<nwords; ++w) {
    values[w]=((m_rxSpiFifo->io()->dataU8(2*w+2))&0xFF)+
      (((m_rxSpiFifo->io()->dataU8(2*w+3))&0xFF)<<8);
  }
  return status;
}
spiRead() [2/3]
PyObject * SeqPGA::spiRead (unsigned int subadd, unsigned int nwords)
Definition at line 339 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), m_ctrlSpiReg, m_rxSpiFifo, m_transmitSpiReg, m_txSpiFifo, IOobject::read(), RAM::setSize(), IOdata::setU8(), and IOobject::write().
                                                                   {
  unsigned int val = subadd | 0x80 ;
  m_txSpiFifo->setSize(16,1);
  m_rxSpiFifo->setSize(16,nwords+1);
  m_ctrlSpiReg->io()->setU8(0,(nwords+1)&0xFF);
  m_ctrlSpiReg->io()->setU8(1,((nwords+1)>>8)&0xFF);
  m_ctrlSpiReg->write();
  // m_ctrlSpiReg->read();
  // m_ctrlSpiReg->dump();
  m_txSpiFifo->io()->setU8(0,val);
  m_txSpiFifo->io()->setU8(1,0);
  m_txSpiFifo->write();
  StatusCode status = m_transmitSpiReg->write();
  // usleep(100000);
  m_rxSpiFifo->read();
  PyObject* values = PyList_New(0);
  for (int w=0; w<nwords; ++w) {
    // m_rxSpiFifo->dump();
   PyList_Append(values,
          PyInt_FromLong((long int) (
                          ((m_rxSpiFifo->io()->dataU8(2*w+2))&0xFF) +
                          (((m_rxSpiFifo->io()->dataU8(2*w+3))&0xFF)<<8)
                          )));
  }
  return values;
}
spiRead() [3/3]
unsigned int SeqPGA::spiRead (unsigned int subadd)
Definition at line 382 of file SeqPGA.cpp.
References IOdata::dataU8(), IOobject::io(), m_ctrlSpiReg, m_rxSpiFifo, m_transmitSpiReg, m_txSpiFifo, IOobject::read(), RAM::setSize(), IOdata::setU8(), and IOobject::write().
                                                {
  unsigned int val = subadd | 0x80 ;
  m_txSpiFifo->setSize(16,1);
  m_rxSpiFifo->setSize(16,1);
  m_ctrlSpiReg->io()->setU8(0,1);
  m_ctrlSpiReg->io()->setU8(1,0);
  m_ctrlSpiReg->write();
  m_txSpiFifo->io()->setU8(0,val);
  m_txSpiFifo->io()->setU8(1,0);
  m_txSpiFifo->write();
  // m_txSpiFifo->dump();
  StatusCode status = m_transmitSpiReg->write();
  // usleep(100000);
  m_rxSpiFifo->read();
  // m_rxSpiFifo->dump();
  return ((m_rxSpiFifo->io()->dataU8(0))&0xFF) + (((
      m_rxSpiFifo->io()->dataU8(1))&0xFF)<<8);
}
spiSubAdd()
unsigned long int SeqPGA::spiSubAdd ()
Definition at line 244 of file SeqPGA.cpp.
References m_spiSubAdd.
Referenced by BOOST_PYTHON_MODULE(), and testSequence().
                                   {
  return (m_spiSubAdd) ;
}
spiWrite() [1/3]
StatusCode SeqPGA::spiWrite (unsigned int subadd, unsigned int nwords, unsigned int * values)
Definition at line 283 of file SeqPGA.cpp.
References IOobject::io(), m_ctrlSpiReg, m_transmitSpiReg, m_txSpiFifo, RAM::setSize(), IOdata::setU8(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), TestSPI::execute(), FEB_v1::resetFE(), FEB_v1::resetFifoInjectFE(), FEB_v1::resetFifoSpyFE(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), FEB_v1::setClockFallingEdge(), FEB_v1::setDisableSubtract(), FEB_v1::setEnableBXIDReset(), FEB_v1::setGain4(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), FEB_v1::setLatency(), FEB_v1::setLatencyLLT(), FEB_v1::setLatencyLLTCorner(), FEB_v1::setLatencyLLTSideNb(), FEB_v1::setLatencyLLTUpNb(), FEB_v1::setMaskLLT(), FEB_v1::setMaskLLTCorner(), FEB_v1::setMaskLLTSideNb(), FEB_v1::setMaskLLTUpNb(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), FEB_v1::setSpyModeSeq(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), FEB_v1::setThreshold(), testSequence(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), FEB_v1::writeFifoLLT(), and FEB_v1::writeFifoSpyFE().
                                                                                         {
  unsigned int val = subadd & 0x7F;
  m_txSpiFifo->setSize(16,nwords+1);
  m_ctrlSpiReg->io()->setU8(0,nwords&0xFF);
  m_ctrlSpiReg->io()->setU8(1,(nwords>>8)&0xFF);
  m_ctrlSpiReg->write();
  m_txSpiFifo->io()->setU8(0,val);
  m_txSpiFifo->io()->setU8(1,0);
  for (int w=0; w<nwords; ++w) {
    m_txSpiFifo->io()->setU8(2*w+2,values[w]&0xFF);
    m_txSpiFifo->io()->setU8(2*w+3,(values[w]>>8)&0xFF);
  }
  m_txSpiFifo->write();
  return m_transmitSpiReg->write();
}
spiWrite() [2/3]
StatusCode SeqPGA::spiWrite (unsigned int subadd, unsigned int nwords, PyObject * value)
Definition at line 319 of file SeqPGA.cpp.
References IOobject::io(), m_ctrlSpiReg, m_transmitSpiReg, m_txSpiFifo, RAM::setSize(), IOdata::setU8(), and IOobject::write().
                                                                                    {
  unsigned int val = subadd & 0x7F;
  m_txSpiFifo->setSize(16,nwords+1);
  m_ctrlSpiReg->io()->setU8(0,nwords&0xFF);
  m_ctrlSpiReg->io()->setU8(1,(nwords>>8)&0xFF);
  m_ctrlSpiReg->write();
  // m_ctrlSpiReg->read();
  // m_ctrlSpiReg->dump();
  m_txSpiFifo->io()->setU8(0,val);
  m_txSpiFifo->io()->setU8(1,0);
  for (int w=0; w<nwords; ++w) {
    val = PyInt_AsLong(PyList_GetItem(value,w));
    m_txSpiFifo->io()->setU8(2*w+2,val&0xFF);
    m_txSpiFifo->io()->setU8(2*w+3,(val>>8)&0xFF);
  }
  // m_txSpiFifo->dump();
  m_txSpiFifo->write();
  return m_transmitSpiReg->write();
}
spiWrite() [3/3]
StatusCode SeqPGA::spiWrite (unsigned int subadd, unsigned int value)
Definition at line 366 of file SeqPGA.cpp.
References IOobject::io(), m_ctrlSpiReg, m_transmitSpiReg, m_txSpiFifo, RAM::setSize(), IOdata::setU8(), and IOobject::write().
                                                                  {
  unsigned int val = subadd & 0x7F;
  m_txSpiFifo->setSize(16,2);
  m_ctrlSpiReg->io()->setU8(0,1);
  m_ctrlSpiReg->io()->setU8(1,0);
  m_ctrlSpiReg->write();
  // m_ctrlSpiReg->read();
  m_txSpiFifo->io()->setU8(0,val);
  m_txSpiFifo->io()->setU8(1,0);
  m_txSpiFifo->io()->setU8(2,value&0xFF);
  m_txSpiFifo->io()->setU8(3,(value>>8)&0xFF);
  m_txSpiFifo->write();
  // m_txSpiFifo->dump();
  return m_transmitSpiReg->write();
}
testSequence()
StatusCode SeqPGA::testSequence () [inline]
Definition at line 96 of file SeqPGA.h.
References extTrig(), i2cAdd(), i2cBuffer(), i2cData(), i2cGBTSCA(), i2cRead(), i2cSubAdd(), i2cWrite(), Object::info(), m_testSeqReg, setExtTrig(), setI2cAdd(), setI2cBuffer(), setI2cGBTSCA(), setI2cSubAdd(), setSpiAdd(), setSpiGBTSCA(), setSpiSubAdd(), spiAdd(), spiGBTSCA(), spiRead(), spiSubAdd(), spiWrite(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and FEB_v1::testSequence().
                            {
    info("SeqPGA testSequence.");
    return m_testSeqReg->write();
  };
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestUSB::Plot(), TestSPI::Plot(), TestI2C::Plot(), Object::setTitle(), and Application::terminate().
{ return m_title; } // < Get Object m_title
transmitSpi()
StatusCode SeqPGA::transmitSpi () [inline]
Definition at line 174 of file SeqPGA.h.
References m_transmitSpiReg, and IOobject::write().
                           {
    return m_transmitSpiReg->write();
  }
tree() [1/2]
void Hierarchy::tree (std::string indent = std::string(``)) [inherited]
Definition at line 310 of file Hierarchy.cpp.
References Hierarchy::children(), Object::info(), Object::msgSvc(), Object::name(), MsgSvc::NONE, and Object::type().
                                    {
  std::string line=indent+" -> "+name()+"["+type()+"] ";
  if (std::string("")==indent){
    info("Hierarchy for Object "+name()+"["+type()+"]","Hierarchy::tree");
  }
  msgSvc(MsgSvc::NONE,line,"");
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter){
    std::string tab=" ";
    (*iter)->tree(indent+tab);
  }
}
tree() [2/2]
void Hierarchy::tree () [inline], [inherited]
Definition at line 46 of file Hierarchy.h.
References Hierarchy::m_parent, and Hierarchy::tree().
Referenced by Hierarchy::children(), export_obj(), and Hierarchy::tree().
{ tree(""); }; // output tree of Hierarchy from object
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
update()
void SeqPGA::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 72 of file SeqPGA.h.
Referenced by AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
                 {
  };
usb()
UsbFTMLInterface* SeqPGA::usb () [inline]
Definition at line 75 of file SeqPGA.h.
References m_usb.
Referenced by BOOST_PYTHON_MODULE(), and FEB_v1::FEB_v1().
                         {
    return m_usb;
  }
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTInterface::read(), UsbFTMLInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), wait(), UsbFTInterface::write(), and UsbFTMLInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), Acquisition::execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), EmulateFE::initialize(), TestI2C::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsSlave::reset(), SpecsMaster::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
Member Data Documentation
m_addI2cReg
Register* SeqPGA::m_addI2cReg [private]
Definition at line 202 of file SeqPGA.h.
Referenced by addI2cReg(), i2cAdd(), SeqPGA(), and setI2cAdd().
m_addSpiReg
Register* SeqPGA::m_addSpiReg [private]
Definition at line 192 of file SeqPGA.h.
Referenced by SeqPGA(), setSpiAdd(), and spiAdd().
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_connection
Hierarchy* Element::m_connection [protected], [inherited]
Definition at line 70 of file Element.h.
Referenced by UsbSpiBus::clockDivider(), Element::connection(), Element::Element(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), IOobject::init(), UsbI2cBus::read(), UsbSpiBus::read(), UsbSpiBus::setClockDivider(), Element::setConnection(), UsbI2cBus::write(), and UsbSpiBus::write().
m_ctrlSpiReg
Register* SeqPGA::m_ctrlSpiReg [private]
Definition at line 193 of file SeqPGA.h.
Referenced by SeqPGA(), spiRead(), and spiWrite().
m_i2cBuffer
unsigned int SeqPGA::m_i2cBuffer [private]
Definition at line 199 of file SeqPGA.h.
Referenced by i2cBuffer(), i2cWrite(), and setI2cBuffer().
m_i2cSubAdd
unsigned int SeqPGA::m_i2cSubAdd [private]
Definition at line 198 of file SeqPGA.h.
Referenced by i2cRead(), i2cSubAdd(), i2cWrite(), and setI2cSubAdd().
m_masterI2cReg
Register* SeqPGA::m_masterI2cReg [private]
Definition at line 201 of file SeqPGA.h.
Referenced by i2cData(), i2cRead(), i2cWrite(), masterI2cReg(), and SeqPGA().
m_reg
Register* SeqPGA::m_reg [private]
Definition at line 183 of file SeqPGA.h.
Referenced by reg(), and SeqPGA().
m_resetReg
Register* SeqPGA::m_resetReg [private]
Definition at line 187 of file SeqPGA.h.
Referenced by reset(), resetUsb(), and SeqPGA().
m_rxSpiFifo
RAM* SeqPGA::m_rxSpiFifo [private]
Definition at line 191 of file SeqPGA.h.
Referenced by SeqPGA(), and spiRead().
m_setupReg
Register* SeqPGA::m_setupReg [private]
Definition at line 186 of file SeqPGA.h.
Referenced by extTrig(), i2cGBTSCA(), i2cRead(), i2cWrite(), SeqPGA(), setExtTrig(), setI2cGBTSCA(), setSpiGBTSCA(), setupReg(), and spiGBTSCA().
m_spiSubAdd
unsigned int SeqPGA::m_spiSubAdd [private]
Definition at line 197 of file SeqPGA.h.
Referenced by setSpiSubAdd(), and spiSubAdd().
m_statusReg
Register* SeqPGA::m_statusReg [private]
Definition at line 185 of file SeqPGA.h.
Referenced by SeqPGA().
m_testSeqReg
Register* SeqPGA::m_testSeqReg [private]
Definition at line 188 of file SeqPGA.h.
Referenced by SeqPGA(), and testSequence().
m_transmitSpiReg
Register* SeqPGA::m_transmitSpiReg [private]
Definition at line 195 of file SeqPGA.h.
Referenced by SeqPGA(), spiRead(), spiWrite(), and transmitSpi().
m_txSpiFifo
RAM* SeqPGA::m_txSpiFifo [private]
Definition at line 190 of file SeqPGA.h.
Referenced by SeqPGA(), spiRead(), and spiWrite().
m_usb
UsbFTMLInterface* SeqPGA::m_usb [private]
Definition at line 179 of file SeqPGA.h.
Referenced by SeqPGA(), and usb().
m_usbi2c
UsbMLI2cBus* SeqPGA::m_usbi2c [private]
Definition at line 180 of file SeqPGA.h.
Referenced by i2c(), and SeqPGA().
m_usbspi
UsbMLSpiBus* SeqPGA::m_usbspi [private]
Definition at line 181 of file SeqPGA.h.
Referenced by SeqPGA(), and spi().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/SeqPGA.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/SeqPGA.cpp