A3PE Class Reference
#include <A3PE.h>
Public Types
typedef unsigned long U32
typedef unsigned short U16
typedef unsigned char U8
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
A3PE ()
~A3PE ()
void help ()
StatusCode init ()
void reset ()
StatusCode resetStorageFifo ()
StatusCode resetUsbPhasers ()
StatusCode resetLatencyCounter ()
StatusCode resetAcquisitionWriteCounter ()
StatusCode resetPatternFifo ()
StatusCode resetTriggerFifo ()
StatusCode resetToAXRam ()
StatusCode resetFromAXRam ()
StatusCode resetSequenceFromToAX ()
StatusCode resetFE ()
StatusCode resetSPI ()
StatusCode setEnableADC (unsigned int, bool)
StatusCode setWriteStorageFifoUsb (bool)
bool enableADC (unsigned int)
bool writeStorageFifoUsb ()
StatusCode setReadPatternFifoUsb (bool)
bool readPatternFifoUsb ()
StatusCode setReadTriggerFifoUsb (bool)
bool readTriggerFifoUsb ()
StatusCode setReadToAXRamUsb (bool)
bool readToAXRamUsb ()
StatusCode setWriteFromAXRamUsb (bool)
bool writeFromAXRamUsb ()
StatusCode setAXRamUsb (bool)
StatusCode startSequenceAX ()
StatusCode setSoftwareTrigger (bool)
bool softwareTrigger ()
StatusCode setClockDivision (unsigned int)
StatusCode setTriggerDelay (unsigned int)
StatusCode setSeqPulseDelay (unsigned int)
StatusCode setTriggerRate (unsigned int)
StatusCode setNTrigger (unsigned int)
StatusCode setFifoLatency (unsigned short)
StatusCode setFifoDepth (unsigned int)
unsigned int clockDivision ()
unsigned int triggerDelay ()
unsigned int seqPulseDelay ()
unsigned int triggerRate ()
unsigned int nTrigger ()
unsigned int fifoLatency ()
unsigned int fifoDepth ()
StatusCode acquisition ()
StatusCode enableStorage ()
StatusCode trigger ()
bool dataReady ()
void update ()
StatusCode setInternalAXSequence (bool)
bool internalAXSequence ()
StatusCode setLengthAX (unsigned int)
unsigned int lengthAX ()
StatusCode setLatencyAX (unsigned int)
unsigned int latencyAX ()
StatusCode setPipeline (unsigned int)
unsigned int pipeline ()
Register * ctrlReg ()
Register * setupReg ()
Register * resetReg ()
Register * statusReg ()
Register * acqReg ()
Register * latencyReg ()
Register * writeLengthFifoReg ()
Register * ctrlAnaMezzReg ()
Register * clockDivisionReg ()
Register * triggerReg ()
Register * toAXReg ()
Register * fromAXReg ()
Register * spare3Reg ()
RAM * storageRam ()
RAM * patternRam ()
RAM * triggerRam ()
RAM * toAXRam ()
RAM * fromAXRam ()
RAM * testRam ()
Register * fromAXRamPtrReg ()
Register * toAXRamPtrReg ()
void dumpStorage ()
void loadStorage (std::string)
void dumpPattern ()
void loadPattern (std::string)
void dumpTrigger ()
void loadTrigger (std::string)
void dumpToAX ()
void loadToAX (std::string)
void dumpFromAX ()
void loadFromAX (std::string)
StatusCode setAddToAXRam (int)
StatusCode setAddFromAXRam (int)
void recursiveInitElement ()
void recursiveInitCommunications ()
StatusCode setConnection (Hierarchy *)
Hierarchy * connection ()
void clear ()
void setParent (Hierarchy *parent)
Hierarchy * parent ()
Hierarchy * parent (std::string)
Hierarchy * origin ()
virtual void addChild (Hierarchy *element)
std::vector< Hierarchy * > children ()
Hierarchy * child (std::string)
Hierarchy * childTyped (std::string)
unsigned long numberOfChildren ()
bool hasChildren ()
void delChild (Hierarchy *)
void delChild (std::string)
std::string path (std::string=std::string(``))
std::string pathTyped (std::string=std::string(``))
void tree (std::string indent=std::string(``))
void tree ()
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
Hierarchy * m_connection
std::string m_attribString [10]
Private Attributes
Register * m_globalUsbReset
Register * m_ctrlReg
Register * m_resetReg
Register * m_setupReg
Register * m_statusReg
Register * m_acqReg
Register * m_latencyReg
Register * m_writeLengthFifoReg
Register * m_ctrlAnaMezzReg
Register * m_clockDivisionReg
Register * m_triggerReg
Register * m_toAXReg
Register * m_fromAXReg
Register * m_spare3Reg
RAM * m_storageRam
RAM * m_patternRam
RAM * m_triggerRam
Register * m_toAXRamPtr
Register * m_fromAXRamPtr
RAM * m_toAXRam
RAM * m_fromAXRam
Register * m_latencyAX
Register * m_lengthAX
RAM * m_testRam
Detailed Description
Definition at line 20 of file A3PE.h.
Member Typedef Documentation
U16
typedef unsigned short A3PE::U16
Definition at line 23 of file A3PE.h.
U32
typedef unsigned long A3PE::U32
Definition at line 22 of file A3PE.h.
U8
typedef unsigned char A3PE::U8
Definition at line 24 of file A3PE.h.
Member Enumeration Documentation
Attribut
enum Attrib::Attribut [inherited]
Enumerator
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                {
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  }; // array m_attribString must be changed into Attrib::Attrib if this enu is modified.
Constructor & Destructor Documentation
A3PE()
A3PE::A3PE () [inline]
Definition at line 25 of file A3PE.h.
References Attrib::add(), Hierarchy::addChild(), Object::debug(), IOdata::defDataU16(), IOdata::defDataU32(), Attrib::ELEMENT, Attrib::HARDWARE, IOobject::io(), m_acqReg, m_clockDivisionReg, m_ctrlAnaMezzReg, m_ctrlReg, m_fromAXRam, m_fromAXRamPtr, m_fromAXReg, m_globalUsbReset, m_latencyAX, m_latencyReg, m_lengthAX, m_patternRam, m_resetReg, m_setupReg, m_spare3Reg, m_statusReg, m_storageRam, m_testRam, m_toAXRam, m_toAXRamPtr, m_toAXReg, m_triggerRam, m_triggerReg, m_writeLengthFifoReg, IOobject::setAddress(), Object::setId(), Object::setName(), RAM::setSize(), and Object::setType().
        {
    setType("A3PE");
    setId(0);
    add(Attrib::ELEMENT); add (Attrib::HARDWARE);
    debug("A3PE built.","A3PE::A3PE");
    m_globalUsbReset=new Register();
    addChild(m_globalUsbReset);
    m_globalUsbReset->setName("GlobalUsbReset");
    m_globalUsbReset->io()->defDataU32(1);
    m_globalUsbReset->setAddress(112);
    m_ctrlReg=new Register();
    addChild(m_ctrlReg);
    m_ctrlReg->setName("CtrlRegister");
    m_ctrlReg->io()->defDataU32(1);
    m_ctrlReg->setAddress(20);
    m_resetReg=new Register();
    addChild(m_resetReg);
    m_resetReg->setName("ResetRegister");
    m_resetReg->io()->defDataU16(1);
    m_resetReg->setAddress(1);
    m_statusReg=new Register();
    addChild(m_statusReg);
    m_statusReg->setName("StatusRegister");
    m_statusReg->io()->defDataU16(1);
    m_statusReg->setAddress(3);
    m_setupReg=new Register();
    addChild(m_setupReg);
    m_setupReg->setName("SetupRegister");
    m_setupReg->io()->defDataU16(1);
    m_setupReg->setAddress(2);
    m_acqReg=new Register();
    addChild(m_acqReg);
    m_acqReg->setName("AcqRegister");
    m_acqReg->io()->defDataU16(1);
    m_acqReg->setAddress(4);
    m_latencyReg=new Register();
    addChild(m_latencyReg);
    m_latencyReg->setName("LatencyRegister");
    m_latencyReg->io()->defDataU16(1);
    m_latencyReg->setAddress(7);
    m_writeLengthFifoReg=new Register();
    addChild(m_writeLengthFifoReg);
    m_writeLengthFifoReg->setName("WriteLengthFifoRegister");
    m_writeLengthFifoReg->io()->defDataU16(1);
    m_writeLengthFifoReg->setAddress(8);
    //ICECAL Analog Mezzanine Relays:
    m_ctrlAnaMezzReg=new Register();
    addChild(m_ctrlAnaMezzReg);
    m_ctrlAnaMezzReg->setName("CtrlAnaMezzReg");
    m_ctrlAnaMezzReg->io()->defDataU32(1);
    m_ctrlAnaMezzReg->setAddress(20);
    m_clockDivisionReg=new Register();
    addChild(m_clockDivisionReg);
    m_clockDivisionReg->setName("ClockDivisionReg");
    m_clockDivisionReg->io()->defDataU32(1);
    m_clockDivisionReg->setAddress(23);
    m_triggerReg=new Register();
    addChild(m_triggerReg);
    m_triggerReg->setName("TriggerReg");
    m_triggerReg->io()->defDataU32(1);
    m_triggerReg->setAddress(24);
    m_toAXReg=new Register();
    addChild(m_toAXReg);
    m_toAXReg->setName("ToAXReg");
    m_toAXReg->io()->defDataU32(1);
    m_toAXReg->setAddress(26);
    m_fromAXReg=new Register();
    addChild(m_fromAXReg);
    m_fromAXReg->setName("FromAXReg");
    m_fromAXReg->io()->defDataU32(1);
    m_fromAXReg->setAddress(27);
    m_spare3Reg=new Register();
    addChild(m_spare3Reg);
    m_spare3Reg->setName("Spare3Reg");
    m_spare3Reg->io()->defDataU32(1);
    m_spare3Reg->setAddress(19);
    m_storageRam=new RAM();
    addChild(m_storageRam);
    m_storageRam->setName("StorageRam");
    m_storageRam->setSize(96,512);
    m_storageRam->setAddress(6);
    m_patternRam=new RAM();
    addChild(m_patternRam);
    m_patternRam->setName("PatternRam");
    m_patternRam->setSize(96,512);
    m_patternRam->setAddress(28);
    m_triggerRam=new RAM();
    addChild(m_triggerRam);
    m_triggerRam->setName("TriggerRam");
    m_triggerRam->setSize(8,512);
    m_triggerRam->setAddress(31);
    m_toAXRamPtr=new Register();
    addChild(m_toAXRamPtr);
    m_toAXRamPtr->setName("ToAXRamPtr");
    m_toAXRamPtr->io()->defDataU16(1);
    m_toAXRamPtr->setAddress(35);
    m_toAXRam=new RAM();
    addChild(m_toAXRam);
    m_toAXRam->setName("ToAXRam");
    m_toAXRam->setSize(32,512);
    m_toAXRam->setAddress(29);
    m_fromAXRamPtr=new Register();
    addChild(m_fromAXRamPtr);
    m_fromAXRamPtr->setName("FromAXRamPtr");
    m_fromAXRamPtr->io()->defDataU16(1);
    m_fromAXRamPtr->setAddress(36);
    m_fromAXRam=new RAM();
    addChild(m_fromAXRam);
    m_fromAXRam->setName("FromAXRam");
    m_fromAXRam->setSize(32,512);
    m_fromAXRam->setAddress(30);
    m_latencyAX=new Register();
    addChild(m_latencyAX);
    m_latencyAX->setName("LatencyAX");
    m_latencyAX->io()->defDataU32(1);
    m_latencyAX->setAddress(32);
    m_lengthAX=new Register();
    addChild(m_lengthAX);
    m_lengthAX->setName("LengthAX");
    m_lengthAX->io()->defDataU16(1);
    m_lengthAX->setAddress(34);
    m_testRam=new RAM();
    addChild(m_testRam);
    m_testRam->setName("TestRam");
    m_testRam->setSize(32,50);
    m_testRam->setAddress(27);
  }
 A3PE()
A3PE::~A3PE () [inline]
Definition at line 177 of file A3PE.h.
         {
    /*
    delete m_globalUsbReset;
    delete m_ctrlReg;
    delete m_resetReg;
    delete m_setupReg;
    delete m_statusReg;
    delete m_acqReg;
    delete m_latencyReg;
    delete m_writeLengthFifoReg;
    delete m_clockDivisionReg;
    delete m_triggerReg;
    delete m_toAXReg;
    delete m_fromAXReg;
    delete m_spare3Reg;
    delete m_storageRam;
    delete m_patternRam;
    delete m_triggerRam;
    delete m_toAXRam;
    delete m_fromAXRam;
    delete m_toAXRamPtr;
    delete m_fromAXRamPtr;
    delete m_lengthAX;
    delete m_latencyAX;
    delete m_testRam;
    */
  }
Member Function Documentation
acqReg()
Register* A3PE::acqReg () [inline]
Definition at line 500 of file A3PE.h.
References m_acqReg.
Referenced by BOOST_PYTHON_MODULE().
                    {
    return m_acqReg;
  }
acquisition()
StatusCode A3PE::acquisition ()
Definition at line 417 of file A3PE.cpp.
References Object::debug(), m_acqReg, Register::setBit(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), StorageFifoAcquisition::execute(), StorageFifo::execute(), and reset().
                            {
  debug("Acquisition sequence started","A3PE::acquisition");
  warning("This acquisition trigger does not release the busy bit !",
      "A3PE::acquisition");
  return m_acqReg->setBit(3,1);
}
add()
void Attrib::add (int attribut) [inline], [inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), TestI2C::setAddress(), TestSPI::setAddress(), SpecsSlave::setAddress(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            {
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        duplicate = true ;
      }
    }
    if (!duplicate) {
      m_attributs.push_back(attribut);
    }
  }
addChild()
void Hierarchy::addChild (Hierarchy * element) [virtual], [inherited]
Definition at line 83 of file Hierarchy.cpp.
References Object::debug(), Hierarchy::m_children, Object::name(), and Hierarchy::setParent().
Referenced by A3PE(), SpecsMezzanine::addBus(), SpecsSlave::addI2c(), Application::create(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Hierarchy::origin(), Phaser::Phaser(), Proto40MHz_v1::Proto40MHz_v1(), SeqPGA::SeqPGA(), SpecsMezzanine::SpecsMezzanine(), UsbI2cBus::UsbI2cBus(), and UsbSpiBus::UsbSpiBus().
                                          {
  element->setParent(this);
  m_children.push_back(element);
  debug(element->name()+" added to the child tree.","Hierarchy::addChild");
}
attributs()
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj(), and Attrib::remove().
                            {
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++
      index) {
    if (m_attributs.size() - index > 1) {
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    }
    else {
      output.append(m_attribString[m_attributs[index]]);
    }
  }
  return output;
}
child()
Hierarchy * Hierarchy::child (std::string path) [inherited]
Definition at line 133 of file Hierarchy.cpp.
References Hierarchy::child(), Hierarchy::children(), Object::name(), Hierarchy::origin(), Hierarchy::parent(), Hierarchy::path(), and Object::warning().
Referenced by Application::cd(), Hierarchy::child(), Hierarchy::children(), and export_obj().
                                         {
  std::string newpath = path;
  std::string up("..");
  std::string separator(1,'/');
  Hierarchy * newcurrent = 0;
  // info("path="+path,"Hierarchy::child");
  if (path.compare("")==0 || path.compare("/")==0) {
    // debug("return origin","Hierarchy::child");
    return origin();
  }
  if (path.compare(name())==0){
    // debug("return itself","Hierarchy::child");
    return this;
  }
  if (path.compare("..")==0){
    if (0!=this->parent()) return this->parent();
    else return this;
  }
  if (path.compare("../")==0){
    if (0!=this->parent()) return this->parent();
    else return this;
  }
  int npos=path.find(separator,0);
  // info("find separator in "+itos(npos)+" of "+path,"Hierarchy::child");
  // remove last separator
  if (npos == (int)(path.size()-1)) {
    newpath = std::string(path,0,npos);
    path = newpath;
  }
  if (npos==0){
    // debug("Going back to origin and calling child","Hierarchy::child");
    newpath=std::string(path,1,path.size()-1);
    return origin()->child(newpath);
  }
  else{
    if (npos== (int)(std::string::npos)){
      // debug("Getting chid "+path+" of "+this->name(),"Hierarchy::child");
      std::vector <Hierarchy*> list = children();
      std::vector<Hierarchy*>::iterator iter;
      for (iter=list.begin();iter!=list.end();iter++){
        if ((*iter)->name().compare(path)==0){
          return *iter;
        }
      }
      warning(this->name()+std::string(" has no child '")+path+"'","Hierarchy::child");
      return this;
    }
    else
    {
      int ipos=path.find(separator,0);
      // info("default behaviour "+path+" with separator in "+itos(ipos),"Hierarchy::child");
      std::string newcurrentname=std::string(path,0,ipos);
      newpath=std::string(path,ipos+1,path.size()-1);
      // info("looking now for "+newpath+" from "+newcurrentname,"Hierarchy::child");
      if (0==newcurrentname.compare(origin()->name())){
        // info("current is computer. Looking for children"+newcurrentname,"Hierarchy::child");
        return origin()->child(newpath);
      }
      newcurrent = (Hierarchy*)0;
      std::vector <Hierarchy*> list = children();
      std::vector<Hierarchy*>::iterator iter;
      for (iter=list.begin();iter!=list.end();iter++){
        if ((*iter)->name().compare(newcurrentname)==0){
          newcurrent = (*iter);
        }
      }
      if ((Hierarchy*)0==newcurrent){
        if (newcurrentname.compare("..")==0 && 0!=parent()){
          newcurrent=this->parent();
          // debug("newcurrent was .. -> parent="+parent()->name());
        }
        else
        {
          warning(this->name()+" has no child '"+newcurrentname+"'",
              "Hierarchy::child");
          return this;
        }
      }
      // debug("recurrence call for "+newpath+" on "+newcurrent->name(),"Hierarchy::child");
      return newcurrent -> child (newpath);
    }
  }
}
children()
std::vector<Hierarchy*> Hierarchy::children () [inline], [inherited]
Definition at line 33 of file Hierarchy.h.
References Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::delChild(), Hierarchy::hasChildren(), Hierarchy::m_children, Hierarchy::numberOfChildren(), Hierarchy::path(), Hierarchy::pathTyped(), and Hierarchy::tree().
Referenced by Hierarchy::child(), Hierarchy::childTyped(), export_obj(), SpecsSlave::recursiveInitCommunications(), Element::recursiveInitCommunications(), Element::recursiveInitElement(), Application::setConfig(), and Hierarchy::tree().
{ return m_children; } //< get list of child(ren)
childTyped()
Hierarchy * Hierarchy::childTyped (std::string path) [inherited]
Definition at line 239 of file Hierarchy.cpp.
References Hierarchy::children(), Hierarchy::m_origin, Object::name(), Hierarchy::parent(), Hierarchy::path(), and Object::warning().
Referenced by Hierarchy::children(), and export_obj().
                                              {
  std::string newpath = path;
  std::string up("..");
  std::string separator(1,'/');
  std::string typeopen(1,'[');
  std::string typeclose(1,']');
  Hierarchy * newcurrent = 0;
  unsigned int npos=path.find(separator,0);
  unsigned int opos=path.find(typeopen,0);
  if (npos==std::string::npos || npos == path.size()-1){
    if (path.compare("..")==0) {
      return parent();
    }
    if (npos == path.size()-1) {
      newpath = std::string(path,0,opos);
      path = newpath;
    }
    std::vector < Hierarchy* > list = children();
    std::vector < Hierarchy* >::iterator iter;
    for (iter=list.begin();iter!=list.end();iter++){
      std::string notypepath = std::string(path,0,opos);
      if ((*iter)->name().compare(notypepath)==0){
        return *iter;
      }
    }
    warning(this->name()+std::string(" has no child ") +path,"Hierarchy::child");
    return 0;
  }
  else {
    if (std::string(path,0,3).compare(std::string("../"))==0) {
      newpath=std::string(path,3,path.size()-3);
      newcurrent = parent();
    }
    if (std::string(path,0,1).compare(std::string("/"))==0) {
      newpath=std::string(path,1,path.size()-1);
      newcurrent = (Hierarchy*) m_origin;
    }
    if ((std::string(path,0,3).compare(std::string("../")) !=0) &&
        std::string(path,0,1).compare(std::string("/"))!=0) {
      opos = path.find(typeopen,0);
      int cpos = path.find(typeclose,0);
      std::string name = std::string (path,0,opos);
      newcurrent = childTyped(name);
      if (newcurrent ==0){
        warning(path+": no child found with such a name","Hierarchy::child");
      }
      newpath = std::string (path,cpos+2,path.size()-cpos-1);
    }
    return newcurrent -> childTyped (newpath);
  }
}
clear()
void Hierarchy::clear () [inherited]
Definition at line 35 of file Hierarchy.cpp.
References Hierarchy::delChild(), Object::info(), Hierarchy::m_children, and Object::name().
Referenced by export_obj().
                     {
  std::vector<Hierarchy*> listlocale;
  std::vector<Hierarchy*>::iterator iter;
  info("loop on "+name()+" children.","Hierarchy::clear");
  for (iter=m_children.begin();iter!=m_children.end();iter++){
      info("processing "+(*iter)->name()+".","Hierarchy::clear");
/*
      (*iter)->clear();
// this->delChild((*iter));
      info("obj "+(*iter)->name()+" being cleared.","Hierarchy::clear");
      delete (*iter);
      info("Object deleted.","Hierarchy::clear");
      m_children.erase(iter);
      info("Object removed from the tree.","Hierarchy::clear");
*/
    (*iter)->clear();
    info("Adding object "+(*iter)->name()+" from the Hierarchy to the list of deleted objects.","
      Hierarchy::clear");
    listlocale.push_back((*iter));
  }
  for (iter=listlocale.begin();iter!=listlocale.end();iter++){
    info("Removing object "+(*iter)->name()+".","Hierarchy::clear");
    this->delChild(*iter);
// m_children.erase(iter);
    delete (*iter);
  }
  info("Getting out of "+name());
}
clockDivision()
unsigned int A3PE::clockDivision ()
Definition at line 448 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_clockDivisionReg, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                {
  if (m_clockDivisionReg->read().isFailure()){
    error("Cannot read Clock Division register "+m_clockDivisionReg->
      name(),
        "Register::setClockDivision");
    return 0;
  }
  unsigned long int data=m_clockDivisionReg->io()->
      dataU32()[0];
  return (data&(16777215)); // switch last 24 bits at 0
}
clockDivisionReg()
Register* A3PE::clockDivisionReg () [inline]
Definition at line 516 of file A3PE.h.
References m_clockDivisionReg.
Referenced by BOOST_PYTHON_MODULE().
                              {
    return m_clockDivisionReg;
  }
connection()
Hierarchy * Element::connection () [inherited]
Get IO interface
Definition at line 84 of file Element.cpp.
References Element::m_connection, Object::name(), and Object::warning().
Referenced by UsbSpiBus::clockDivider(), export_obj(), UsbI2cBus::read(), IOobject::read(), UsbSpiBus::read(), UsbSpiBus::setClockDivider(), Element::setConnection(), UsbI2cBus::write(), IOobject::write(), and UsbSpiBus::write().
                              {
  if (0==m_connection){
    warning("no connection defined for "+name()+".","Element::connection");
    return (Hierarchy*)0;
  }
  return m_connection;
}
ctrlAnaMezzReg()
Register* A3PE::ctrlAnaMezzReg () [inline]
Definition at line 512 of file A3PE.h.
References m_ctrlAnaMezzReg.
Referenced by BOOST_PYTHON_MODULE().
                            {
    return m_ctrlAnaMezzReg;
  }
ctrlReg()
Register* A3PE::ctrlReg () [inline]
Definition at line 484 of file A3PE.h.
References m_ctrlReg.
Referenced by BOOST_PYTHON_MODULE().
                     {
    return m_ctrlReg;
  }
dataReady()
bool A3PE::dataReady ()
Definition at line 406 of file A3PE.cpp.
References Object::debug(), Register::getBit(), and m_acqReg.
Referenced by BOOST_PYTHON_MODULE(), Acquisition::execute(), and reset().
                    {
  bool isReady=m_acqReg->getBit(2);
  if (isReady) {
    debug("Spying EnableStorage bit - Data Ready: NO ","A3PE::dataReady");
  }
  else {
    debug("Spying EnableStorage bit - Data Ready: YES","A3PE::dataReady");
  }
  return (!isReady);
}
debug() [1/2]
void Object::debug (std::string mymsg) [inline], [inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE(), acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), StorageFifoAcquisition::execute(), StorageFifo::execute(), A3PE_BitFlip::execute(), Acquisition::execute(), EmulateFE::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), FePGA::i2cRead(), SeqPGA::i2cRead(), FePGA::i2cWrite(), SeqPGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), internalAXSequence(), SpecsGlue::led(), SpecsMezzanine::led(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), Phaser::read(), ICPhaser::read(), FEB_v1::readFifoSpyFE(), CU_v1::reset(), FEB_v1::reset(), Proto40MHz_v1::reset(), SpecsMaster::reset(), SpecsSlave::reset(), FEB_v1::resetFifoSpyFE(), FEB_v1::resetUsb(), SeqPGA::SeqPGA(), setAddFromAXRam(), setAddToAXRam(), setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), setLatencyAX(), SpecsGlue::setLed(), SpecsMezzanine::setLed(), setLengthAX(), setReadToAXRamUsb(), SpecsMaster::setSpeed(), setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), FEB_v1::testDuration(), SeqPGA::testSequence(), trigger(), Server::updateConfig(), Server::updateState(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name); }
debug() [2/2]
void Object::debug (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::DEBUG , mymsg, name); }
delChild() [1/2]
void Hierarchy::delChild (Hierarchy * element) [inherited]
Definition at line 92 of file Hierarchy.cpp.
References Object::debug(), and Hierarchy::m_children.
Referenced by Hierarchy::children(), Hierarchy::clear(), export_obj(), and Hierarchy::~Hierarchy().
                                          {
  bool flag=false;
  std::vector<Hierarchy*>::iterator iter,remove;
  for (iter=m_children.begin();(iter!=m_children.end());iter++){
    if (*iter==element){
      remove=iter;
      flag=true;
    }
  }
  if (flag){
    debug("removing "+(*remove)->name()+" from the tree.","Hierarchy::delChild");
    m_children.erase(remove);
  }
}
delChild() [2/2]
void Hierarchy::delChild (std::string n) [inherited]
Definition at line 110 of file Hierarchy.cpp.
References Object::debug(), and Hierarchy::m_children.
                                   {
  bool flag=false;
  std::vector<Hierarchy*>::iterator iter,remove;
  for (iter=m_children.begin();iter!=m_children.end();iter++){
    if ((*iter)->name()==n){ remove=iter; flag=true;}
  }
  if (flag){
    debug("removing "+(*remove)->name()+" from the tree.","Hierarchy::delChild");
    m_children.erase(remove);
  }
}
dllName()
std::string Object::dllName () [inline], [inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj(), and Object::setDllName().
                       {
    return m_dllName;
  }
dumpFromAX()
void A3PE::dumpFromAX ()
Definition at line 896 of file A3PE.cpp.
References IOdata::dataU8(), fromAXRam(), Object::info(), IOobject::io(), itos(), lengthAX(), IOobject::read(), setAddFromAXRam(), and setAXRamUsb().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                     {
  setAXRamUsb(true);
  setAddFromAXRam(0);
  fromAXRam()->read();
  U8* val=fromAXRam()->io()->dataU8();
  unsigned int l=lengthAX();
  info("Length AX="+itos(l));
  char line[100];
  for (int d=0; d<l+2; ++d){
    sprintf(line,"%3d -> %1d %1d %1d %1d",
        d,val[4*d],val[1+4*d],val[2+4*d],val[3+4*d]);
    info(line);
  }
}
dumpPattern()
void A3PE::dumpPattern ()
Definition at line 716 of file A3PE.cpp.
References IOdata::dataU8(), RAM::depth(), Object::info(), IOobject::io(), patternRam(), IOobject::read(), and setReadPatternFifoUsb().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                      {
  RAM* fifo=patternRam();
  setReadPatternFifoUsb(true);
  fifo->read();
  setReadPatternFifoUsb(false);
  int val[12];
  char line[100];
  for (unsigned int d=0; d<fifo->depth(); ++d){
    val[0] =fifo->io()->dataU8(0+12*d);
    val[1] =fifo->io()->dataU8(1+12*d);
    val[2] =fifo->io()->dataU8(2+12*d);
    val[3] =fifo->io()->dataU8(3+12*d);
    val[4] =fifo->io()->dataU8(4+12*d);
    val[5] =fifo->io()->dataU8(5+12*d);
    val[6] =fifo->io()->dataU8(6+12*d);
    val[7] =fifo->io()->dataU8(7+12*d);
    val[8] =fifo->io()->dataU8(8+12*d);
    val[9] =fifo->io()->dataU8(9+12*d);
    val[10]=fifo->io()->dataU8(10+12*d);
    val[11]=fifo->io()->dataU8(11+12*d);
    sprintf(line,"%3d -> %4d %4d %4d %4d %4d %4d %4d %4d",
        d,
        val[0]+((val[1]&0xf)<<8),(val[1]>>4)+(val[2]<<4),
        val[3]+((val[4]&0xf)<<8),(val[4]>>4)+(val[5]<<4),
        val[6]+((val[7]&0xf)<<8),(val[7]>>4)+(val[8]<<4),
        val[9]+((val[10]&0xf)<<8),(val[10]>>4)+(val[11]<<4)
        );
    info(line);
  }
}
dumpStorage()
void A3PE::dumpStorage ()
Definition at line 641 of file A3PE.cpp.
References IOdata::dataU8(), fifoDepth(), Object::info(), IOobject::io(), IOobject::read(), and storageRam().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                      {
  RAM* fifo=storageRam();
  fifo->read();
  int val[12];
  char line[100];
  for (unsigned int d=0; d<fifoDepth(); ++d){
    val[0] =fifo->io()->dataU8(0+12*d);
    val[1] =fifo->io()->dataU8(1+12*d);
    val[2] =fifo->io()->dataU8(2+12*d);
    val[3] =fifo->io()->dataU8(3+12*d);
    val[4] =fifo->io()->dataU8(4+12*d);
    val[5] =fifo->io()->dataU8(5+12*d);
    val[6] =fifo->io()->dataU8(6+12*d);
    val[7] =fifo->io()->dataU8(7+12*d);
    val[8] =fifo->io()->dataU8(8+12*d);
    val[9] =fifo->io()->dataU8(9+12*d);
    val[10]=fifo->io()->dataU8(10+12*d);
    val[11]=fifo->io()->dataU8(11+12*d);
    sprintf(line,"%3d -> %4d %4d %4d %4d %4d %4d %4d %4d",
        d,
        val[0]+((val[1]&0xf)<<8),(val[1]>>4)+(val[2]<<4),
        val[3]+((val[4]&0xf)<<8),(val[4]>>4)+(val[5]<<4),
        val[6]+((val[7]&0xf)<<8),(val[7]>>4)+(val[8]<<4),
        val[9]+((val[10]&0xf)<<8),(val[10]>>4)+(val[11]<<4)
        );
    info(line);
  }
}
dumpToAX()
void A3PE::dumpToAX ()
Definition at line 844 of file A3PE.cpp.
References IOdata::dataU8(), RAM::depth(), Object::info(), IOobject::io(), IOobject::read(), setAddToAXRam(), setReadToAXRamUsb(), and toAXRam().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                   {
  setAddToAXRam(0);
  setReadToAXRamUsb(true);
  toAXRam()->read();
  setReadToAXRamUsb(false);
  U8* val=toAXRam()->io()->dataU8();
  char line[100];
  for (int d=0; d<toAXRam()->depth(); ++d){
    sprintf(line,"%3d -> %1d %1d %1d %1d",
        d,val[4*d],val[1+4*d],val[2+4*d],val[3+4*d]);
    info(line);
  }
}
dumpTrigger()
void A3PE::dumpTrigger ()
Definition at line 791 of file A3PE.cpp.
References IOdata::dataU8(), RAM::depth(), Object::info(), IOobject::io(), IOobject::read(), setReadTriggerFifoUsb(), and triggerRam().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                      {
  RAM* fifo=triggerRam();
  setReadTriggerFifoUsb(true);
  fifo->read();
  setReadTriggerFifoUsb(false);
  int val;
  char line[100];
  for (int d=0; d<fifo->depth(); ++d){
    val=fifo->io()->dataU8(d);
    sprintf(line,"%3d -> %1d %1d %1d %1d %1d %1d %1d %1d",
        d,
        val&0x1,(val>>1)&0x1,(val>>2)&0x1,(val>>3)&0x1,
        (val>>4)&0x1,(val>>5)&0x1,(val>>6)&0x1,(val>>7)&0x1);
    info(line);
  }
}
enableADC()
bool A3PE::enableADC (unsigned int adc)
Definition at line 265 of file A3PE.cpp.
References Register::getBit(), and m_setupReg.
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                    {
  if (adc<8){
    return m_setupReg->getBit(adc);
  }
  return false;
}
enableStorage()
StatusCode A3PE::enableStorage ()
Definition at line 383 of file A3PE.cpp.
References shell::data(), IOdata::dataU16(), Object::error(), StatusCode::FAILURE, IOobject::io(), StatusCode::isFailure(), m_acqReg, m_resetReg, Object::name(), IOobject::read(), IOdata::setU16(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), Acquisition::execute(), and reset().
                              {
  // enable data storage
  if (m_acqReg->read().isFailure()){
    error("Cannot read acquisition register "+name(),"A3P3::enableStorage");
    return StatusCode::FAILURE;
  }
  unsigned int data=m_acqReg->io()->dataU16()[0];
  // info("Value before acquisition: "+itos(data));
  data|=4;
  m_acqReg->io()->setU16(0,data);
  if (m_acqReg->write().isFailure()){
    error("Cannot write acquisition register ","A3P3::enableStorage");
    return StatusCode::FAILURE;
  }
  // reset the busy line
  m_resetReg->io()->setU16(0,8);
  if (m_resetReg->write().isFailure()){
    error("Cannot reset Busy line"+name(),"A3P3::enableStorage");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
error() [1/2]
void Object::error (std::string mymsg) [inline], [inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by clockDivision(), NI6008::cmd(), enableStorage(), A3PE_BitFlip::execute(), export_obj(), fifoDepth(), fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), NI6008::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), latencyAX(), lengthAX(), nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), pipeline(), UsbFTInterface::read(), UsbFTMLInterface::read(), MSOxxxx::recv(), reset(), MSOxxxx::send(), setAddFromAXRam(), setAddToAXRam(), ICECALv3::setAnalogCh(), setAXRamUsb(), Register::setBit(), setClockDivision(), setFifoDepth(), setFifoLatency(), setLatencyAX(), setLengthAX(), setNTrigger(), setPipeline(), setReadPatternFifoUsb(), setReadToAXRamUsb(), setReadTriggerFifoUsb(), setSoftwareTrigger(), setTriggerDelay(), setTriggerRate(), setWriteFromAXRamUsb(), setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), startSequenceAX(), triggerDelay(), triggerRate(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, m_name); }
error() [2/2]
void Object::error (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::ERR , mymsg, name); }
fatal() [1/2]
void Object::fatal (std::string mymsg) [inline], [inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), SpecsSlave::init(), IOobject::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name); }
fatal() [2/2]
void Object::fatal (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::FATAL , mymsg, name); }
fifoDepth()
unsigned int A3PE::fifoDepth ()
Definition at line 631 of file A3PE.cpp.
References shell::data(), IOdata::dataU16(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_writeLengthFifoReg, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), dumpStorage(), StorageFifo::initialize(), loadStorage(), and reset().
                            {
  if (m_writeLengthFifoReg->read().isFailure()){
    error("Cannot read writeLengthFifo register "+m_writeLengthFifoReg->
      name(),
        "Register::setFifoDepth");
    return 0;
  }
  unsigned short data=m_writeLengthFifoReg->io()->
      dataU16()[0];
  return (data&511);
}
fifoLatency()
unsigned int A3PE::fifoLatency ()
Definition at line 599 of file A3PE.cpp.
References shell::data(), IOdata::dataU16(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_latencyReg, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                              {
  if (m_latencyReg->read().isFailure()){
    error("Cannot read Latency register "+m_latencyReg->name(),
        "Register::setFifoLatency");
    return 0;
  }
  unsigned short data=m_latencyReg->io()->dataU16()[0];
  return (data&65535);
}
fromAXRam()
RAM* A3PE::fromAXRam () [inline]
Definition at line 552 of file A3PE.h.
References m_fromAXRam.
Referenced by BOOST_PYTHON_MODULE(), dumpFromAX(), A3PE_BitFlip::initialize(), and loadFromAX().
                  {
    return m_fromAXRam;
  }
fromAXRamPtrReg()
Register* A3PE::fromAXRamPtrReg () [inline]
Definition at line 560 of file A3PE.h.
References m_fromAXRamPtr.
                             {
    return m_fromAXRamPtr;
  }
fromAXReg()
Register* A3PE::fromAXReg () [inline]
Definition at line 528 of file A3PE.h.
References m_fromAXReg.
Referenced by BOOST_PYTHON_MODULE().
                       {
    return m_fromAXReg;
  }
hasChildren()
bool Hierarchy::hasChildren () [inherited]
Definition at line 303 of file Hierarchy.cpp.
References Hierarchy::m_children.
Referenced by Hierarchy::children(), and export_obj().
                              {
  return (m_children.size()>0);
}
help()
void A3PE::help () [inline], [virtual]
printout help for the element
Implements Element.
Definition at line 208 of file A3PE.h.
References Object::info(), and Object::name().
{ info("A3PE "+name()+". No help.","A3PE::help"); };
id()
unsigned char Object::id () [inline], [inherited]
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj(), and Object::setId().
{ return m_id; } //< Get Object m_id
info() [1/2]
void Object::info (std::string mymsg) [inline], [inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), ICECALv3::bxidResynchStatus(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTInterface::close(), UsbFTMLInterface::close(), Processus::closeRootFile(), Server::cmdline(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), dumpFromAX(), dumpPattern(), dumpStorage(), dumpToAX(), dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), Croc::help(), RAM::help(), SpecsGlue::help(), UsbMLI2cBus::help(), UsbMLSpiBus::help(), CU_v1::help(), UsbI2cBus::help(), UsbSpiBus::help(), FEB_v1::help(), IOobject::help(), Proto40MHz_v1::help(), SpecsMezzanine::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), SpecsMaster::help(), UsbFTMLInterface::help(), UsbFTInterface::help(), Phaser::help(), ICPhaser::help(), help(), MSOxxxx::id(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTInterface::init(), UsbFTMLInterface::init(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), EmulateFE::initialize(), ADCMeasurement::initialize(), CurrentMeasurement::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), loadFromAX(), Application::loadHistoryFile(), loadPattern(), loadStorage(), loadToAX(), loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), Croc::reset(), UsbMLI2cBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbSpiBus::reset(), FePGA::reset(), SeqPGA::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), reset(), resetAcquisitionWriteCounter(), FEB_v1::resetFE(), resetFE(), FEB_v1::resetFifoInjectFE(), resetFromAXRam(), SpecsSlave::resetInternal(), resetLatencyCounter(), resetPatternFifo(), resetSequenceFromToAX(), resetSPI(), resetStorageFifo(), resetToAXRam(), resetTriggerFifo(), SeqPGA::resetUsb(), FePGA::resetUsb(), resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), setEnableADC(), setFifoDepth(), setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), setInternalAXSequence(), FEB_v1::setLatency(), setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), Phaser::setPhase(), ICPhaser::setPhase(), setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), setReadPatternFifoUsb(), setReadTriggerFifoUsb(), setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), Processus::setState(), FEB_v1::setThreshold(), setTriggerDelay(), setTriggerRate(), setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLI2cBus::update(), UsbMLSpiBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), ICECALv3::version(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, m_name); }
info() [2/2]
void Object::info (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
{ m_log.msgSvc (MsgSvc::INFO , mymsg, name); }
init()
StatusCode A3PE::init () [inline], [virtual]
init the component
Returns
void
Implements Element.
Definition at line 214 of file A3PE.h.
References StatusCode::SUCCESS.
                    {
    return StatusCode::SUCCESS;
  };
internalAXSequence()
bool A3PE::internalAXSequence ()
Definition at line 285 of file A3PE.cpp.
References Object::debug(), Register::getBit(), and m_setupReg.
Referenced by BOOST_PYTHON_MODULE(), A3PE_BitFlip::initialize(), and update().
                             {
  debug("Get fpga loop mode","A3PE::internalAXSequence");
  return m_setupReg->getBit(12);
}
is()
bool Attrib::is (int attribut) [inline], [inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  {
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        return true;
      }
    }
    return false;
  }
latencyAX()
unsigned int A3PE::latencyAX ()
Definition at line 348 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_latencyAX, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), A3PE_BitFlip::initialize(), and update().
                            {
  if (m_latencyAX->read().isFailure()){
    error("Cannot read Latency AX register "+m_latencyAX->name(),
        "A3PE::latencyAX");
    return 0;
  }
  unsigned long int data=m_latencyAX->io()->dataU32()[0];
  return (data&0xffffff);
  return 0;
}
latencyReg()
Register* A3PE::latencyReg () [inline]
Definition at line 504 of file A3PE.h.
References m_latencyReg.
                        {
    return m_latencyReg;
  }
lengthAX()
unsigned int A3PE::lengthAX ()
Definition at line 338 of file A3PE.cpp.
References shell::data(), IOdata::dataU16(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_lengthAX, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), dumpFromAX(), A3PE_BitFlip::initialize(), and update().
                           {
  if (m_lengthAX->read().isFailure()){
    error("Cannot read Length AX register "+m_lengthAX->name(),
        "A3PE::lengthAX");
    return 0;
  }
  unsigned long int data=m_lengthAX->io()->dataU16()[0];
  return (data&0xffff);
}
loadFromAX()
void A3PE::loadFromAX (std::string filename)
Definition at line 911 of file A3PE.cpp.
References shell::data(), IOdata::dataU8(), RAM::depth(), fromAXRam(), Object::info(), IOobject::io(), itos(), setAddFromAXRam(), setWriteFromAXRamUsb(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                                       {
  setAddFromAXRam(0);
  std::ifstream ifs(filename.c_str(),std::ifstream::in);
  std::string s;
  std::string comment;
  std::istringstream instream;
  U8* data=fromAXRam()->io()->dataU8();
  int depth=fromAXRam()->depth();
  int d=0;
  int c0, c1, c2, c3;
  while (getline(ifs, s) && d<depth) { // Reads line into s
      instream.clear(); // Reset from possible previous errors.
      instream.str(s); // Use s as source of input.
      instream>>std::ws;
      if (!instream.eof()) {
        instream >> comment;
        if (comment==std::string("#")) {
          info(s);
        }
        else {
          instream.clear(); // Reset from possible previous errors.
          instream.str(s); // Use s as source of input.
          instream>>c0>>c1>>c2>>c3;
          info(itos(c0)+" "+itos(c1)+" "+itos(c2)+" "+itos(c3));
          data[ 4*d]=c0&0xff;
          data[1+4*d]=c1&0xff;
          data[2+4*d]=c2&0xff;
          data[3+4*d]=c3&0xff;
          d++;
        }
      }
  }
  ifs.close();
  setWriteFromAXRamUsb(true);
  fromAXRam()->write();
  setWriteFromAXRamUsb(false);
}
loadPattern()
void A3PE::loadPattern (std::string filename)
Definition at line 747 of file A3PE.cpp.
References shell::data(), IOdata::dataU8(), RAM::depth(), Object::info(), IOobject::io(), itos(), patternRam(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                                        {
  std::ifstream ifs(filename.c_str(),std::ifstream::in);
  std::string s;
  std::string comment;
  std::istringstream instream;
  U8* data=patternRam()->io()->dataU8();
  int depth=patternRam()->depth();
  int d=0;
  int c0, c1, c2, c3, c4, c5, c6, c7;
  while (getline(ifs, s) && d<depth) { // Reads line into s
      instream.clear(); // Reset from possible previous errors.
      instream.str(s); // Use s as source of input.
      instream>>std::ws;
      if (!instream.eof()) {
        instream >> comment;
        if (comment==std::string("#")) {
          info(s);
        }
        else {
          instream.clear(); // Reset from possible previous errors.
          instream.str(s); // Use s as source of input.
          instream>>c0>>c1>>c2>>c3>>c4>>c5>>c6>>c7;
          info(itos(c0)+" "+itos(c1)+" "+itos(c2)+" "+itos(c3)
              +" "+itos(c4)+" "+itos(c5)+" "+itos(c6)+" "+itos(c7));
          data[ 12*d]=(c0&0xff);
          data[ 1+12*d]=((c0>>8)&0xf)+((c1<<4)&0xf0);
          data[ 2+12*d]=((c1>>4)&0xff);
          data[ 3+12*d]=(c2&0xff);
          data[ 4+12*d]=((c2>>8)&0xf)+((c3<<4)&0xf0);
          data[ 5+12*d]=((c3>>4)&0xff);
          data[ 6+12*d]=(c4&0xff);
          data[ 7+12*d]=((c4>>8)&0xf)+((c5<<4)&0xf0);
          data[ 8+12*d]=((c5>>4)&0xff);
          data[ 9+12*d]=(c6&0xff);
          data[10+12*d]=((c6>>8)&0xf)+((c7<<4)&0xf0);
          data[11+12*d]=((c7>>4)&0xff);
          d++;
        }
      }
  }
  ifs.close();
  patternRam()->write();
}
loadStorage()
void A3PE::loadStorage (std::string filename)
Definition at line 670 of file A3PE.cpp.
References shell::data(), IOdata::dataU8(), fifoDepth(), Object::info(), IOobject::io(), itos(), setWriteStorageFifoUsb(), storageRam(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                                        {
  std::ifstream ifs(filename.c_str(),std::ifstream::in);
  std::string s;
  std::string comment;
  std::istringstream instream;
  U8* data=storageRam()->io()->dataU8();
  int depth=fifoDepth();
  int d=0;
  int c0, c1, c2, c3, c4, c5, c6, c7;
  while (getline(ifs, s) && d<depth) { // Reads line into s
      instream.clear(); // Reset from possible previous errors.
      instream.str(s); // Use s as source of input.
      instream>>std::ws;
      if (!instream.eof()) {
        instream >> comment;
        if (comment==std::string("#")) {
          info(s);
        }
        else {
          instream.clear(); // Reset from possible previous errors.
          instream.str(s); // Use s as source of input.
          instream>>c0>>c1>>c2>>c3>>c4>>c5>>c6>>c7;
          info(itos(c0)+" "+itos(c1)+" "+itos(c2)+" "+itos(c3)
              +" "+itos(c4)+" "+itos(c5)+" "+itos(c6)+" "+itos(c7));
          data[ 12*d]=(c0&0xff);
          data[ 1+12*d]=((c0>>8)&0xf)+((c1<<4)&0xf0);
          data[ 2+12*d]=((c1>>4)&0xff);
          data[ 3+12*d]=(c2&0xff);
          data[ 4+12*d]=((c2>>8)&0xf)+((c3<<4)&0xf0);
          data[ 5+12*d]=((c3>>4)&0xff);
          data[ 6+12*d]=(c4&0xff);
          data[ 7+12*d]=((c4>>8)&0xf)+((c5<<4)&0xf0);
          data[ 8+12*d]=((c5>>4)&0xff);
          data[ 9+12*d]=(c6&0xff);
          data[10+12*d]=((c6>>8)&0xf)+((c7<<4)&0xf0);
          data[11+12*d]=((c7>>4)&0xff);
          d++;
        }
      }
  }
  ifs.close();
  setWriteStorageFifoUsb(true);
  storageRam()->write();
  setWriteStorageFifoUsb(false);
}
loadToAX()
void A3PE::loadToAX (std::string filename)
Definition at line 858 of file A3PE.cpp.
References shell::data(), IOdata::dataU8(), RAM::depth(), Object::info(), IOobject::io(), itos(), setAddToAXRam(), setAXRamUsb(), toAXRam(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), A3PE_BitFlip::initialize(), and toAXRamPtrReg().
                                     {
  setAXRamUsb(true);
  setAddToAXRam(0);
  info("loadtoax="+filename);
  std::ifstream ifs(filename.c_str(),std::ifstream::in);
  std::string s;
  std::string comment;
  std::istringstream instream;
  U8* data=toAXRam()->io()->dataU8();
  int depth=toAXRam()->depth();
  int d=0;
  int c0, c1, c2, c3;
  while (getline(ifs, s) && d<depth) { // Reads line into s
      instream.clear(); // Reset from possible previous errors.
      instream.str(s); // Use s as source of input.
      instream>>std::ws;
      if (!instream.eof()) {
        instream >> comment;
        if (comment==std::string("#")) {
          info(s);
        }
        else {
          instream.clear(); // Reset from possible previous errors.
          instream.str(s); // Use s as source of input.
          instream>>c0>>c1>>c2>>c3;
          info(itos(c0)+" "+itos(c1)+" "+itos(c2)+" "+itos(c3));
          data[ 4*d]=c0&0xff;
          data[1+4*d]=c1&0xff;
          data[2+4*d]=c2&0xff;
          data[3+4*d]=c3&0xff;
          d++;
        }
      }
  }
  ifs.close();
  toAXRam()->write();
}
loadTrigger()
void A3PE::loadTrigger (std::string filename)
Definition at line 809 of file A3PE.cpp.
References shell::data(), IOdata::dataU8(), RAM::depth(), Object::info(), IOobject::io(), itos(), triggerRam(), Object::warning(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and toAXRamPtrReg().
                                        {
  std::ifstream ifs(filename.c_str(),std::ifstream::in);
  std::string s;
  std::string comment;
  std::istringstream instream;
  U8* data=triggerRam()->io()->dataU8();
  int depth=triggerRam()->depth();
  int d=0;
  int c0, c1, c2, c3, c4, c5, c6, c7;
  while (getline(ifs, s) && d<depth) { // Reads line into s
      instream.clear(); // Reset from possible previous errors.
      instream.str(s); // Use s as source of input.
      instream>>std::ws;
      if (!instream.eof()) {
        instream >> comment;
        if (comment==std::string("#")) {
          info(s);
        }
        else {
          instream.clear(); // Reset from possible previous errors.
          instream.str(s); // Use s as source of input.
          instream>>c0>>c1>>c2>>c3>>c4>>c5>>c6>>c7;
          info(itos(c0)+" "+itos(c1)+" "+itos(c2)+" "+itos(c3)
              +" "+itos(c4)+" "+itos(c5)+" "+itos(c6)+" "+itos(c7));
          data[d]=c0+((c1&0x1)<<1)+((c2&0x1)<<2)+((c3&0x1)<<3)+
              ((c4&0x1)<<4)+((c5&0x1)<<5)+((c6&0x1)<<6)+((c7&0x1)<<7);
          warning(itos(d)+" => "+itos(data[d]));
          d++;
        }
      }
  }
  ifs.close();
  triggerRam()->write();
}
msg() [1/2]
void Object::msg (std::string mymsg) [inline], [inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
{ m_log.msgSvc (MsgSvc::NONE , mymsg, m_name); }
msg() [2/2]
void Object::msg (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
{ m_log.msgSvc (MsgSvc::NONE , mymsg, name); }
msgSvc()
void Object::msgSvc (int level, std::string msg, std::string name) [inline], [inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), Processus::setState(), and Hierarchy::tree().
{ m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg,
      name); }
name()
std::string Object::name () const [inline], [inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), enableStorage(), export_obj(), export_proc(), fifoDepth(), fifoLatency(), Register::getBit(), Croc::help(), RAM::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbI2cBus::help(), CU_v1::help(), UsbSpiBus::help(), IOobject::help(), Proto40MHz_v1::help(), FEB_v1::help(), FePGA::help(), SeqPGA::help(), Computer::help(), NI6008::help(), SpecsParallelBus::help(), UsbFTInterface::help(), UsbFTMLInterface::help(), Phaser::help(), ICPhaser::help(), help(), Data::hist2d(), Croc::init(), Computer::init(), NI6008::init(), SpecsParallelBus::init(), SpecsSlave::init(), SpecsMaster::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), PhaserRampExec::initialize(), latencyAX(), lengthAX(), Application::network(), nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), pipeline(), TestSuite::Plot(), TestI2C::Plot(), TestSPI::Plot(), TestUSB::Plot(), Phaser::read(), ICPhaser::read(), Croc::reset(), UsbMLI2cBus::reset(), UsbMLSpiBus::reset(), UsbI2cBus::reset(), UsbSpiBus::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::reset(), Computer::reset(), SpecsParallelBus::reset(), SpecsMaster::reset(), SpecsSlave::reset(), NI6008::reset(), UsbFTMLInterface::reset(), UsbFTInterface::reset(), reset(), SpecsSlave::resetInternal(), FEB_v1::resetUsb(), setAddFromAXRam(), setAddToAXRam(), Register::setBit(), setClockDivision(), Application::setConfig(), Element::setConnection(), setFifoDepth(), setFifoLatency(), setLatencyAX(), setLengthAX(), Object::setName(), setNTrigger(), setPipeline(), SpecsMaster::setSpeed(), Processus::setState(), setTriggerDelay(), setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Application::terminate(), Hierarchy::tree(), triggerDelay(), triggerRate(), Croc::update(), UsbI2cBus::update(), UsbSpiBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), CU_v1::update(), Proto40MHz_v1::update(), Computer::update(), FEB_v1::update(), SpecsParallelBus::update(), NI6008::update(), UsbFTInterface::update(), UsbFTMLInterface::update(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), Phaser::write(), ICPhaser::write(), and Hierarchy::~Hierarchy().
{ return m_name; } //< Get Object m_name
nTrigger()
unsigned int A3PE::nTrigger ()
Definition at line 568 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_triggerReg, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                           {
  if (m_triggerReg->read().isFailure()){
    error("Cannot read Trigger register "+m_triggerReg->name(),
        "Register::setNTrigger");
    return 0;
  }
  unsigned long int data=m_triggerReg->io()->dataU32()[0];
  return ((data>>24)&255);
}
numberOfChildren()
unsigned long Hierarchy::numberOfChildren () [inherited]
Definition at line 125 of file Hierarchy.cpp.
References Hierarchy::m_children.
Referenced by Hierarchy::children(), and export_obj().
                                           {
  return m_children.size();
}
origin()
Hierarchy* Hierarchy::origin () [inline], [inherited]
Definition at line 30 of file Hierarchy.h.
References Hierarchy::addChild(), and Hierarchy::m_origin.
Referenced by Hierarchy::child(), export_obj(), and Hierarchy::setParent().
{ return m_origin; } //< Get the origin of the tree
parent() [1/2]
Hierarchy* Hierarchy::parent () [inline], [inherited]
Definition at line 28 of file Hierarchy.h.
References Hierarchy::m_parent.
Referenced by Hierarchy::child(), Hierarchy::childTyped(), export_obj(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), IOobject::init(), Hierarchy::parent(), Hierarchy::path(), Hierarchy::pathTyped(), Element::setConnection(), Hierarchy::setParent(), SpecsInterface::specsMaster(), SpecsInterface::specsMasterDevice(), SpecsInterface::specsSlave(), SpecsInterface::specsSlaveDevice(), and Hierarchy::~Hierarchy().
{ return m_parent; } //< Get Hierarchy Parent
parent() [2/2]
Hierarchy * Hierarchy::parent (std::string type) [inherited]
Definition at line 327 of file Hierarchy.cpp.
References Hierarchy::parent(), and Object::type().
                                            {
  Hierarchy *parent = this->parent();
  if (0 != parent){
    if (parent->type().compare(type)==0) {
      return parent;
    }
    else
      return parent->parent(type);
  }
  else {
    return (Hierarchy*)NULL;
  }
}
path()
std::string Hierarchy::path (std::string str = std::string(``)) [inherited]
Definition at line 344 of file Hierarchy.cpp.
References Hierarchy::m_parent, Object::name(), Hierarchy::parent(), and Hierarchy::path().
Referenced by Hierarchy::child(), Hierarchy::children(), Hierarchy::childTyped(), export_obj(), Hierarchy::path(), UsbFTMLInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), and UsbFTMLInterface::usbWriteU8().
                                      {
  str="/"+name()+str;
  Hierarchy *m_parent=parent();
  if (0!=m_parent){
    return m_parent->path(str);
  }
  return str;
}
pathTyped()
std::string Hierarchy::pathTyped (std::string str = std::string(``)) [inherited]
Definition at line 356 of file Hierarchy.cpp.
References Hierarchy::m_parent, Object::name(), Hierarchy::parent(), Hierarchy::pathTyped(), and Object::type().
Referenced by Hierarchy::children(), export_obj(), and Hierarchy::pathTyped().
                                           {
  Hierarchy *m_parent=parent();
  if (0!=m_parent){
    str="/"+name()+"["+type()+"]"+str;
    return m_parent->pathTyped(str);
  }
  return str;
}
patternRam()
RAM* A3PE::patternRam () [inline]
Definition at line 540 of file A3PE.h.
References m_patternRam.
Referenced by BOOST_PYTHON_MODULE(), dumpPattern(), and loadPattern().
                   {
    return m_patternRam;
  }
pipeline()
unsigned int A3PE::pipeline ()
Definition at line 307 of file A3PE.cpp.
References IOdata::dataU16(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_acqReg, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and update().
                           {
  if (m_acqReg->read().isFailure()){
    error("Cannot read acquisition register "+m_acqReg->name(),
      "A3PE::pipeline");
    return 0;
  }
  return (((m_acqReg->io()->dataU16()[0])>>6)&3);
}
readPatternFifoUsb()
bool A3PE::readPatternFifoUsb ()
Definition at line 253 of file A3PE.cpp.
References Register::getBit(), and m_setupReg.
Referenced by BOOST_PYTHON_MODULE(), and reset().
                             {
  if (m_setupReg->getBit(9)==1) return true;
  return false;
}
readToAXRamUsb()
bool A3PE::readToAXRamUsb ()
Definition at line 272 of file A3PE.cpp.
References Register::getBit(), and m_setupReg.
Referenced by BOOST_PYTHON_MODULE(), and reset().
                         {
  return (m_setupReg->getBit(10)==1&&m_setupReg->
      getBit(11)==1);
}
readTriggerFifoUsb()
bool A3PE::readTriggerFifoUsb ()
Definition at line 258 of file A3PE.cpp.
References Register::getBit(), and m_setupReg.
Referenced by BOOST_PYTHON_MODULE(), and reset().
                             {
  if (m_setupReg->getBit(9)==1) return true;
  return false;
}
recursiveInitCommunications()
void Element::recursiveInitCommunications () [inherited]
Triggers a recursive call to initCommunications() for the full hierarchy
Returns
void
Definition at line 44 of file Element.cpp.
References Hierarchy::children().
Referenced by export_obj().
                                         {
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::const_iterator iter;
  for (iter=list.begin();iter!=list.end();iter++){
    dynamic_cast<Element*>((*iter))->recursiveInitCommunications();
  }
}
recursiveInitElement()
void Element::recursiveInitElement () [inherited]
Triggers a recursive call to init() for the full hierarchy
Returns
void
Definition at line 32 of file Element.cpp.
References Hierarchy::children(), and Element::init().
Referenced by export_obj().
                                  {
  init();
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter){
    dynamic_cast<Element*>((*iter))->recursiveInitElement();
  }
}
remove()
void Attrib::remove (int attribut) [inline], [inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::attributs(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               {
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter) {
      if (attribut == (*iter)) {
        toremove = iter;
      }
    }
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  }
reset()
void A3PE::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Definition at line 225 of file A3PE.h.
References acquisition(), clockDivision(), dataReady(), enableADC(), enableStorage(), Object::error(), fifoDepth(), fifoLatency(), Object::info(), IOobject::io(), StatusCode::isFailure(), m_globalUsbReset, m_resetReg, Object::name(), nTrigger(), readPatternFifoUsb(), readToAXRamUsb(), readTriggerFifoUsb(), resetAcquisitionWriteCounter(), resetFE(), resetFromAXRam(), resetLatencyCounter(), resetPatternFifo(), resetSequenceFromToAX(), resetSPI(), resetStorageFifo(), resetToAXRam(), resetTriggerFifo(), resetUsbPhasers(), seqPulseDelay(), setAXRamUsb(), setClockDivision(), setEnableADC(), setFifoDepth(), setFifoLatency(), setNTrigger(), setReadPatternFifoUsb(), setReadToAXRamUsb(), setReadTriggerFifoUsb(), setSeqPulseDelay(), setSoftwareTrigger(), setTriggerDelay(), setTriggerRate(), IOdata::setU16(), setWriteFromAXRamUsb(), setWriteStorageFifoUsb(), softwareTrigger(), startSequenceAX(), trigger(), triggerDelay(), triggerRate(), IOobject::write(), writeFromAXRamUsb(), and writeStorageFifoUsb().
Referenced by BOOST_PYTHON_MODULE(), and Proto40MHz_v1::reset().
               {
        info("A3PE reset procedure.");
    info("A3PE global usb reset.","A3PE::reset");
    if (m_globalUsbReset->write().isFailure()){
      error("Cannot trigger a Global Usb reset on A3PE "+name(),"A3PE::reset");
    }
    info("A3PE global reset.","A3PE::reset");
        m_resetReg->io()->setU16(0,0xFFFF);
    if (m_resetReg->write().isFailure()){
      error("Cannot trigger a Global reset on A3PE "+name(),"A3PE::reset");
    }
  };
resetAcquisitionWriteCounter()
StatusCode A3PE::resetAcquisitionWriteCounter ()
Definition at line 42 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by reset().
                                             {
  info("Reset acquisition write counter","A3PE::resetAcquisitionWriteCounter");
  return m_resetReg->setBit(5,1);
}
resetFE()
StatusCode A3PE::resetFE ()
Definition at line 72 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                        {
  info("Reset FE triggered.","A3PE::resetFE");
  return m_resetReg->setBit(14,1);
}
resetFromAXRam()
StatusCode A3PE::resetFromAXRam ()
Definition at line 62 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                               {
  info("Reset FromAX Ram","A3PE::resetFromAXRam");
  return m_resetReg->setBit(9,1);
}
resetLatencyCounter()
StatusCode A3PE::resetLatencyCounter ()
Definition at line 37 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                    {
  info("Reset Latency counter","A3PE::resetLatencyCounter");
  return m_resetReg->setBit(4,1);
}
resetPatternFifo()
StatusCode A3PE::resetPatternFifo ()
Definition at line 47 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                 {
  info("Reset Pattern Fifo","A3PE::resetPatternFifo");
  return m_resetReg->setBit(6,1);
}
resetReg()
Register* A3PE::resetReg () [inline]
Definition at line 492 of file A3PE.h.
References m_resetReg.
Referenced by BOOST_PYTHON_MODULE().
                      {
    return m_resetReg;
  }
resetSequenceFromToAX()
StatusCode A3PE::resetSequenceFromToAX ()
Definition at line 67 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                      {
  info("Reset Sequence From-To AX","A3PE::resetSequenceFromToAX");
  return m_resetReg->setBit(10,1);
}
resetSPI()
StatusCode A3PE::resetSPI ()
Definition at line 77 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                         {
  info("Reset SPI triggered.","A3PE::resetSPI");
  return m_resetReg->setBit(15,1);
}
resetStorageFifo()
StatusCode A3PE::resetStorageFifo ()
Definition at line 27 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                 {
  info("Reset Storage Fifo","A3PE::resetStorageFifo");
  return m_resetReg->setBit(1,1);
}
resetToAXRam()
StatusCode A3PE::resetToAXRam ()
Definition at line 57 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                             {
  info("Reset ToAx Ram","A3PE::resetToAXRam");
  return m_resetReg->setBit(8,1);
}
resetTriggerFifo()
StatusCode A3PE::resetTriggerFifo ()
Definition at line 52 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                 {
  info("Reset Trigger Fifo","A3PE::resetTriggerFifo");
  return m_resetReg->setBit(7,1);
}
resetUsbPhasers()
StatusCode A3PE::resetUsbPhasers ()
Definition at line 32 of file A3PE.cpp.
References Object::info(), m_resetReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                {
  info("Reset USB Phasers","A3PE::resetUsbPhasers");
  return m_resetReg->setBit(2,1);
}
seqPulseDelay()
unsigned int A3PE::seqPulseDelay ()
Referenced by reset().
setAddFromAXRam()
StatusCode A3PE::setAddFromAXRam (int add)
Definition at line 190 of file A3PE.cpp.
References Object::debug(), Object::error(), StatusCode::FAILURE, IOobject::io(), StatusCode::isFailure(), itos(), m_fromAXRamPtr, Object::name(), IOdata::setU16(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), dumpFromAX(), A3PE_BitFlip::execute(), loadFromAX(), startSequenceAX(), and toAXRamPtrReg().
                                       {
  m_fromAXRamPtr->io()->setU16(0,(add&0x1FF));
  if (m_fromAXRamPtr->write().isFailure()){
      error("Cannot write AddFromAxRam register "+m_fromAXRamPtr->
      name(),
          "A3PE::setAddFromAXRam");
      return StatusCode::FAILURE;
  }
  debug("fromAXRamPtr register set to "+itos(add)+".","A3PE::setAddFromAXRam");
  return StatusCode::SUCCESS;
}
setAddToAXRam()
StatusCode A3PE::setAddToAXRam (int add)
Definition at line 179 of file A3PE.cpp.
References Object::debug(), Object::error(), StatusCode::FAILURE, IOobject::io(), StatusCode::isFailure(), itos(), m_toAXRamPtr, Object::name(), IOdata::setU16(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), dumpToAX(), loadToAX(), A3PE_BitFlip::randomValues(), startSequenceAX(), and toAXRamPtrReg().
                                     {
  m_toAXRamPtr->io()->setU16(0,(add&0x1FF));
  if (m_toAXRamPtr->write().isFailure()){
    error("Cannot write toAxRamPtr register "+m_toAXRamPtr->
      name(),
        "A3PE::setAddToAXRam");
    return StatusCode::FAILURE;
  }
  debug("toAXRamPtr register set to "+itos(add)+".","A3PE::setAddToAXRam");
  return StatusCode::SUCCESS;
}
setAXRamUsb()
StatusCode A3PE::setAXRamUsb (bool enable)
Definition at line 225 of file A3PE.cpp.
References Object::debug(), Object::error(), StatusCode::FAILURE, StatusCode::isFailure(), itos(), m_setupReg, Register::setBit(), and StatusCode::SUCCESS.
Referenced by dumpFromAX(), A3PE_BitFlip::execute(), loadToAX(), A3PE_BitFlip::randomValues(), reset(), and startSequenceAX().
                                       {
  if (enable) {
      if (m_setupReg->setBit(9,1).isFailure()||
          m_setupReg->setBit(11,1).isFailure()
          //||m_setupReg->setBit(12,0).isFailure()
          ){
          error("Cannot set AXRam USB clock mode","A3PE::setAXRamUsb");
          return StatusCode::FAILURE;
      }
  }
  else {
      if (m_setupReg->setBit(9,0).isFailure()||
          m_setupReg->setBit(11,0).isFailure()
          //||m_setupReg->setBit(12,1).isFailure()
          ){
        error("Cannot set AXRam acquisition clock mode","A3PE::setAXRamUsb");
        return StatusCode::FAILURE;
      }
  }
  debug("AXRam USB clock mode set to "+itos(enable),"A3PE::setAXRamUsb");
  return StatusCode::SUCCESS;
}
setClockDivision()
StatusCode A3PE::setClockDivision (unsigned int val)
Definition at line 429 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), StatusCode::FAILURE, Object::info(), IOobject::io(), StatusCode::isFailure(), itos(), m_clockDivisionReg, Object::name(), IOobject::read(), IOdata::setU32(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                                 {
  if (m_clockDivisionReg->read().isFailure()){
    error("Cannot read Clock Division register "+m_clockDivisionReg->
      name(),
        "Register::setClockDivision");
    return StatusCode::FAILURE;
  }
  unsigned long int data=m_clockDivisionReg->io()->
      dataU32()[0];
  data &= ~(16777215); // switch last 24 bits at 0
  data |= (val & 16777215); // or with the desired value
  m_clockDivisionReg->io()->setU32(0,data);
  if (m_clockDivisionReg->write().isFailure()){
    error("Cannot write Clock Division register "+m_clockDivisionReg->
      name(),
        "Register::setClockDivision");
    return StatusCode::FAILURE;
  }
  info("Clock Division set to "+itos(val),"A3PE::setClockDivision");
  return StatusCode::SUCCESS;
}
setConnection()
StatusCode Element::setConnection (Hierarchy * connection) [inherited]
Define IO interface
Definition at line 55 of file Element.cpp.
References Element::connection(), Object::debug(), StatusCode::FAILURE, Object::fatal(), Attrib::INTERFACE, Attrib::is(), Element::m_connection, Object::name(), Hierarchy::parent(), StatusCode::SUCCESS, and Object::type().
Referenced by export_obj(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), and IOobject::init().
                                                      {
  if (0==connection){
    fatal("Try to define a connection with a null pointer.",
        "Element::setConnection");
    return StatusCode::FAILURE;
  }
  if (connection->is(Attrib::INTERFACE)){
    m_connection=dynamic_cast<Hierarchy*>(connection);
    return StatusCode::SUCCESS;
  }
  else {
    debug(connection->name()+
        " is not a Attrib::INTERFACE hardware. Connection refused.",
        "Element::setConnection");
    if (0!=connection->parent()){
      return setConnection(connection->parent());
    }
    else{
      fatal("Could not find a connection for element "+
          name()+"["+type()+"].","element::setConnection");
      return StatusCode::FAILURE;
    }
  }
}
setDllName()
void Object::setDllName (std::string dllName) [inline], [inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::dllName(), and Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      {
    m_dllName = dllName;
  }
setEnableADC()
StatusCode A3PE::setEnableADC (unsigned int adc, bool enable)
Definition at line 87 of file A3PE.cpp.
References StatusCode::FAILURE, Object::info(), itos(), m_setupReg, Register::setBit(), and Object::warning().
Referenced by BOOST_PYTHON_MODULE(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), and reset().
                                                          {
  if (adc<8){
    info("Configuring ADC "+itos(adc)+" input enable to "+itos(enable));
    return m_setupReg->setBit(adc,enable);
  }
  else{
    warning("You cannot setup adc number "+itos(adc)+
        ". No action.","A3PE::setEnableADC");
    return StatusCode::FAILURE;
  }
}
setFifoDepth()
StatusCode A3PE::setFifoDepth (unsigned int val)
Definition at line 612 of file A3PE.cpp.
References shell::data(), IOdata::dataU16(), Object::error(), StatusCode::FAILURE, Object::info(), IOobject::io(), StatusCode::isFailure(), itos(), m_storageRam, m_writeLengthFifoReg, Object::name(), IOobject::read(), RAM::setSize(), IOdata::setU16(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), and reset().
                                             {
  if (m_writeLengthFifoReg->read().isFailure()){
    error("Cannot read writeLengthFifo register "+m_writeLengthFifoReg->
      name(),
        "Register::setFifoDepth");
    return StatusCode::FAILURE;
    m_storageRam->setSize(96,val);
  }
  unsigned short data=m_writeLengthFifoReg->io()->
      dataU16()[0];
  data = (val & 511);
  m_writeLengthFifoReg->io()->setU16(0,data);
  if (m_writeLengthFifoReg->write().isFailure()){
    error("Cannot write writeLengthFifo register "+m_writeLengthFifoReg->
      name(),
        "Register::setFifoDepth");
    return StatusCode::FAILURE;
  }
  info("Fifo Depth set to "+itos(val),"Register::setFifoDepth");
  return StatusCode::SUCCESS;
}
setFifoLatency()
StatusCode A3PE::setFifoLatency (unsigned short val)
Definition at line 581 of file A3PE.cpp.
References shell::data(), IOdata::dataU16(), Object::error(), StatusCode::FAILURE, Object::info(), IOobject::io(), StatusCode::isFailure(), itos(), m_latencyReg, Object::name(), IOobject::read(), IOdata::setU16(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                                 {
  if (m_latencyReg->read().isFailure()){
    error("Cannot read Latency register "+m_latencyReg->name(),
        "Register::setFifoLatency");
    return StatusCode::FAILURE;
  }
  unsigned short data=m_latencyReg->io()->dataU16()[0];
  data = (val & 65535);
  m_latencyReg->io()->setU16(0,data);
  if (m_latencyReg->write().isFailure()){
    error("Cannot write Latency register "+m_latencyReg->name(),
        "Register::setFifoLatency");
    return StatusCode::FAILURE;
  }
  info("Trigger Fifo Latency set to "+itos(val),"Register::setFifoLatency");
  return StatusCode::SUCCESS;
}
setId()
void Object::setId (unsigned char id) [inline], [inherited]
Definition at line 53 of file Object.h.
References Object::id(), and Object::m_id.
Referenced by A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface::SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
{ m_id = id ; } //< Set Object m_id
setInternalAXSequence()
StatusCode A3PE::setInternalAXSequence (bool mode)
Definition at line 280 of file A3PE.cpp.
References Object::info(), itos(), m_setupReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), and update().
                                               {
  info("Switch AX internal loop mode to "+itos(mode),"A3PE::setInternalAXSequence");
  return m_setupReg->setBit(12,mode);
}
setLatencyAX()
StatusCode A3PE::setLatencyAX (unsigned int val)
Definition at line 327 of file A3PE.cpp.
References Object::debug(), Object::error(), StatusCode::FAILURE, IOobject::io(), StatusCode::isFailure(), itos(), m_latencyAX, Object::name(), IOdata::setU32(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), A3PE_BitFlip::execute(), A3PE_BitFlip::finalize(), and update().
                                             {
  m_latencyAX->io()->setU32(0,val);
  if (m_latencyAX->write().isFailure()){
    error("Cannot write latency AX register "+m_latencyAX->name(),
        "Register::setLatencyAX");
    return StatusCode::FAILURE;
  }
  debug("LatencyAX register set to "+itos(val),"A3PE::setLatencyAX");
  return StatusCode::SUCCESS;
}
setLengthAX()
StatusCode A3PE::setLengthAX (unsigned int val)
Definition at line 316 of file A3PE.cpp.
References Object::debug(), Object::error(), StatusCode::FAILURE, IOobject::io(), StatusCode::isFailure(), itos(), m_lengthAX, Object::name(), IOdata::setU16(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and update().
                                            {
  m_lengthAX->io()->setU16(0,val&0xfff);
  if (m_lengthAX->write().isFailure()){
    error("Cannot write length AX register "+m_lengthAX->name(),
        "Register::setLengthAX");
    return StatusCode::FAILURE;
  }
  debug("LengthAX register set to "+itos(val),"A3PE::setLengthAX");
  return StatusCode::SUCCESS;
}
setName()
void Object::setName (std::string name) [inline], [inherited]
Definition at line 51 of file Object.h.
References Object::m_name, and Object::name().
Referenced by A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_name = name ; } //< Set Object m_name
setNTrigger()
StatusCode A3PE::setNTrigger (unsigned int val)
Definition at line 549 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), StatusCode::FAILURE, Object::info(), IOobject::io(), StatusCode::isFailure(), itos(), m_triggerReg, Object::name(), IOobject::read(), IOdata::setU32(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                            {
  if (m_triggerReg->read().isFailure()){
    error("Cannot read Trigger register "+m_triggerReg->name(),
        "Register::setNTrigger");
    return StatusCode::FAILURE;
  }
  unsigned long int data=m_triggerReg->io()->dataU32()[0];
  data &= ~(255<<24); // switch last 8 bits at 0
  data |= ((val & 255)<<24); // or with the desired value
  m_triggerReg->io()->setU32(0,data);
  if (m_triggerReg->write().isFailure()){
    error("Cannot write Trigger register "+m_triggerReg->name(),
        "Register::setNTrigger");
    return StatusCode::FAILURE;
  }
  info("Trigger counter set to "+itos(val),"A3PE::setNTrigger");
  return StatusCode::SUCCESS;
}
setParent()
void Hierarchy::setParent (Hierarchy * parent) [inherited]
Definition at line 67 of file Hierarchy.cpp.
References Hierarchy::m_origin, Hierarchy::m_parent, Hierarchy::origin(), and Hierarchy::parent().
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Computer::Computer(), Application::create(), export_obj(), and SpecsMezzanine::SpecsMezzanine().
                                              {
  m_parent = parent;
  if ((Hierarchy*)0==parent) return;
  Hierarchy *curr = this;
  Hierarchy *prev = parent;
  while (prev != 0){
    curr = prev;
    prev = curr->parent();
  }
  if (parent->origin()!=0) m_origin=parent->origin();
}
setPipeline()
StatusCode A3PE::setPipeline (unsigned int val)
Definition at line 290 of file A3PE.cpp.
References shell::data(), IOdata::dataU16(), Object::error(), StatusCode::FAILURE, Object::info(), IOobject::io(), StatusCode::isFailure(), itos(), m_acqReg, Object::name(), IOobject::read(), IOdata::setU16(), StatusCode::SUCCESS, Object::warning(), and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and update().
                                            {
  if (val>2) {
    warning("Cannot set pipeline to coded value "+itos(val),"A3PE::setPipeline");
    return StatusCode::FAILURE;
  }
  m_acqReg->read();
  unsigned int data=(m_acqReg->io()->dataU16()[0])&0xFF3F;
  m_acqReg->io()->setU16(0,data|(((val&3)<<6)));
  if (m_acqReg->write().isFailure()){
    error("Cannot write acquisition register "+m_acqReg->name(),
      "A3PE::setPipeline");
    return StatusCode::FAILURE;
  }
  info("Acquisition register bits set to "+itos(val),"A3PE::setPipeline");
  return StatusCode::SUCCESS;
}
setReadPatternFifoUsb()
StatusCode A3PE::setReadPatternFifoUsb (bool enable)
Definition at line 124 of file A3PE.cpp.
References Object::error(), StatusCode::FAILURE, Object::info(), StatusCode::isFailure(), m_setupReg, Register::setBit(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), dumpPattern(), and reset().
                                                 {
  if (enable){
    if (m_setupReg->setBit(9,true).isFailure()){
      error("Cannot set pattern fifo read bit",
          "A3PE::setReadPatternFifoUsb");
      return StatusCode::FAILURE;
    }
    else {
      info("Pattern Fifo Usb read mode set.",
           "A3PE::setReadPatternFifoUsb");
    }
    return StatusCode::SUCCESS;
  }
  else {
    if (m_setupReg->setBit(9,false).isFailure()){
      error("Cannot set pattern fifo read bit",
          "A3PE::setReadPatternFifoUsb");
      return StatusCode::FAILURE;
    }
    else {
      info("Pattern Fifo 40MHz read mode set.",
           "A3PE::setWritePatternFifoUsb");
    }
    return StatusCode::SUCCESS;
  }
}
setReadToAXRamUsb()
StatusCode A3PE::setReadToAXRamUsb (bool enable)
Definition at line 201 of file A3PE.cpp.
References Object::debug(), Object::error(), StatusCode::FAILURE, StatusCode::isFailure(), m_setupReg, Register::setBit(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), dumpToAX(), and reset().
                                             {
  if (m_setupReg->setBit(10,enable).isFailure()||
      m_setupReg->setBit(11,enable).isFailure()){
    error("Cannot set ToAXfifo read bit","A3PE::setReadToAXRamUsb");
    return StatusCode::FAILURE;
  }
  else {
    debug("ToAXRam read mode set.","A3PE::setReadToAXRamUsb");
  }
  return StatusCode::SUCCESS;
}
setReadTriggerFifoUsb()
StatusCode A3PE::setReadTriggerFifoUsb (bool enable)
Definition at line 152 of file A3PE.cpp.
References Object::error(), StatusCode::FAILURE, Object::info(), StatusCode::isFailure(), m_setupReg, Register::setBit(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), dumpTrigger(), and reset().
                                                 {
  if (enable){
    if (m_setupReg->setBit(11,true).isFailure()){
      error("Cannot set trigger fifo read bit",
          "A3PE::setReadtriggerFifoUsb");
      return StatusCode::FAILURE;
    }
    else {
      info("Trigger Fifo Usb read mode set.",
           "A3PE::setReadTriggerFifoUsb");
    }
    return StatusCode::SUCCESS;
  }
  else {
    if (m_setupReg->setBit(11,false).isFailure()){
      error("Cannot set trigger fifo read bit",
          "A3PE::setReadTriggerFifoUsb");
      return StatusCode::FAILURE;
    }
    else {
      info("Trigger Fifo 40MHz read mode set.",
           "A3PE::setReadTriggerFifoUsb");
    }
    return StatusCode::SUCCESS;
  }
}
setSeqPulseDelay()
StatusCode A3PE::setSeqPulseDelay (unsigned int)
Referenced by reset().
setSoftwareTrigger()
StatusCode A3PE::setSoftwareTrigger (bool enable)
Definition at line 368 of file A3PE.cpp.
References Object::error(), StatusCode::FAILURE, Object::info(), StatusCode::isFailure(), itos(), m_acqReg, Register::setBit(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), and reset().
                                              {
  if (m_acqReg->setBit(1,enable).isFailure()){
    error("Cannot set software trigger bit","A3PE::setSoftwareTrigger");
    return StatusCode::FAILURE;
  }
  else{
    info("Software trigger mode set to "+itos(enable),"A3PE::setSoftwareTrigger");
  }
  return StatusCode::SUCCESS;
}
setTitle()
void Object::setTitle (std::string title) [inline], [inherited]
Definition at line 54 of file Object.h.
References Object::m_title, and Object::title().
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
{ m_title = title ; } //< Set Object m_title
setTriggerDelay()
StatusCode A3PE::setTriggerDelay (unsigned int val)
Definition at line 461 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), StatusCode::FAILURE, Object::info(), IOobject::io(), StatusCode::isFailure(), itos(), m_triggerReg, Object::name(), IOobject::read(), IOdata::setU32(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                                {
  if (m_triggerReg->read().isFailure()){
    error("Cannot read Trigger register "+m_triggerReg->name(),
        "Register::setTriggerDelay");
    return StatusCode::FAILURE;
  }
  unsigned long int data=m_triggerReg->io()->dataU32()[0];
  data &= ~(255); // switch last 8 bits to 0
  data |= (val & 255); // or with the desired value
  m_triggerReg->io()->setU32(0,data);
  if (m_triggerReg->write().isFailure()){
    error("Cannot write Trigger register "+m_triggerReg->name(),
        "Register::setTriggerDelay");
    return StatusCode::FAILURE;
  }
  info("Trigger delay set to "+itos(val),"A3PE::setTriggerDelay");
  return StatusCode::SUCCESS;
}
setTriggerRate()
StatusCode A3PE::setTriggerRate (unsigned int val)
Definition at line 520 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), StatusCode::FAILURE, Object::info(), IOobject::io(), StatusCode::isFailure(), itos(), m_triggerReg, Object::name(), IOobject::read(), IOdata::setU32(), StatusCode::SUCCESS, and IOobject::write().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                                               {
  if (m_triggerReg->read().isFailure()){
    error("Cannot read Trigger register "+m_triggerReg->name(),
        "Register::setTriggerRate");
    return StatusCode::FAILURE;
  }
  unsigned long int data=m_triggerReg->io()->dataU32()[0];
  data &= ~(65535<<8); // switch 16 bits to 0
  data |= ((val & 65535)<<8); // or with the desired value
  m_triggerReg->io()->setU32(0,data);
  if (m_triggerReg->write().isFailure()){
    error("Cannot write Trigger register "+m_triggerReg->name(),
        "Register::setTriggerRate");
    return StatusCode::FAILURE;
  }
  info("Trigger rate set to "+itos(val),"A3PE::setTriggerRate");
  return StatusCode::SUCCESS;
}
setType()
void Object::setType (std::string type) [inline], [inherited]
Definition at line 52 of file Object.h.
References Object::m_type, and Object::type().
Referenced by A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
{ m_type = type ; } //< Set Object m_type
setupReg()
Register* A3PE::setupReg () [inline]
Definition at line 488 of file A3PE.h.
References m_setupReg.
Referenced by BOOST_PYTHON_MODULE().
                      {
    return m_setupReg;
  }
setWriteFromAXRamUsb()
StatusCode A3PE::setWriteFromAXRamUsb (bool enable)
Definition at line 213 of file A3PE.cpp.
References Object::debug(), Object::error(), StatusCode::FAILURE, StatusCode::isFailure(), m_setupReg, Register::setBit(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), loadFromAX(), and reset().
                                                {
  if (m_setupReg->setBit(10,enable).isFailure()||
      m_setupReg->setBit(11,enable).isFailure()){
    error("Cannot set usb FromAXfifo write bit","A3PE::writeFromAXFifoUsb");
    return StatusCode::FAILURE;
  }
  else {
    debug("write FromAXFifo USB Write mode set.","A3PE::writeFromAXFifoUsb");
  }
  return StatusCode::SUCCESS;
}
setWriteStorageFifoUsb()
StatusCode A3PE::setWriteStorageFifoUsb (bool enable)
Definition at line 99 of file A3PE.cpp.
References Object::error(), StatusCode::FAILURE, Object::info(), StatusCode::isFailure(), m_setupReg, Register::setBit(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), loadStorage(), and reset().
                                                  {
  if (enable) {
    if (m_setupReg->setBit(8,true).isFailure()||
        m_setupReg->setBit(9,true).isFailure()){
      error("Cannot set usb storage fifo write bit","A3PE::setWriteStorageFifoUsb");
      return StatusCode::FAILURE;
    }
    else {
      info("Storage Fifo Usb Write mode set.","A3PE::setWriteStorageFifoUsb");
    }
    return StatusCode::SUCCESS;
  }
  else {
    if (m_setupReg->setBit(8,false).isFailure()||
        m_setupReg->setBit(9,false).isFailure()){
      error("Cannot set fifo storage ADC write bit","A3PE::setWriteStorageFifoUsb");
      return StatusCode::FAILURE;
    }
    else {
      info("Storage Fifo ADC Write mode set.","A3PE::setWriteStorageFifoUsb");
    }
    return StatusCode::SUCCESS;
  }
}
softwareTrigger()
bool A3PE::softwareTrigger ()
Definition at line 379 of file A3PE.cpp.
References Register::getBit(), and m_acqReg.
Referenced by BOOST_PYTHON_MODULE(), and reset().
                          {
  return m_acqReg->getBit(1);
}
spare3Reg()
Register* A3PE::spare3Reg () [inline]
Definition at line 532 of file A3PE.h.
References m_spare3Reg.
Referenced by BOOST_PYTHON_MODULE().
                       {
    return m_spare3Reg;
  }
startSequenceAX()
StatusCode A3PE::startSequenceAX ()
Definition at line 949 of file A3PE.cpp.
References Object::error(), StatusCode::FAILURE, StatusCode::isFailure(), m_acqReg, setAddFromAXRam(), setAddToAXRam(), setAXRamUsb(), Register::setBit(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE(), A3PE_BitFlip::execute(), and reset().
                                {
  setAXRamUsb(false);
  setAddToAXRam(0);
  setAddFromAXRam(0);
  if (m_acqReg->setBit(4,1).isFailure()){
    error("Cannot set AX sequence start bit bit","A3PE::startAXSequence");
    return StatusCode::FAILURE;
  }
  return StatusCode::SUCCESS;
}
statusReg()
Register* A3PE::statusReg () [inline]
Definition at line 496 of file A3PE.h.
References m_statusReg.
Referenced by BOOST_PYTHON_MODULE().
                       {
    return m_statusReg;
  }
storageRam()
RAM* A3PE::storageRam () [inline]
Definition at line 536 of file A3PE.h.
References m_storageRam.
Referenced by BOOST_PYTHON_MODULE(), dumpStorage(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), and loadStorage().
                   {
    return m_storageRam;
  }
testRam()
RAM* A3PE::testRam () [inline]
Definition at line 556 of file A3PE.h.
References m_testRam.
Referenced by BOOST_PYTHON_MODULE().
                {
    return m_testRam;
  }
title()
std::string Object::title () [inline], [inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), Data::hist2d(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), A3PE_BitFlip::Plot(), UsbFTInterfaceTest::Plot(), TestSuite::Plot(), TestSPI::Plot(), TestUSB::Plot(), TestI2C::Plot(), Object::setTitle(), and Application::terminate().
{ return m_title; } // < Get Object m_title
toAXRam()
RAM* A3PE::toAXRam () [inline]
Definition at line 548 of file A3PE.h.
References m_toAXRam.
Referenced by BOOST_PYTHON_MODULE(), dumpToAX(), A3PE_BitFlip::initialize(), and loadToAX().
                {
    return m_toAXRam;
  }
toAXRamPtrReg()
Register* A3PE::toAXRamPtrReg () [inline]
Definition at line 564 of file A3PE.h.
References dumpFromAX(), dumpPattern(), dumpStorage(), dumpToAX(), dumpTrigger(), loadFromAX(), loadPattern(), loadStorage(), loadToAX(), loadTrigger(), m_toAXRamPtr, setAddFromAXRam(), and setAddToAXRam().
                           {
    return m_toAXRamPtr;
  }
toAXReg()
Register* A3PE::toAXReg () [inline]
Definition at line 524 of file A3PE.h.
References m_toAXReg.
Referenced by BOOST_PYTHON_MODULE().
                     {
    return m_toAXReg;
  }
tree() [1/2]
void Hierarchy::tree (std::string indent = std::string(``)) [inherited]
Definition at line 310 of file Hierarchy.cpp.
References Hierarchy::children(), Object::info(), Object::msgSvc(), Object::name(), MsgSvc::NONE, and Object::type().
                                    {
  std::string line=indent+" -> "+name()+"["+type()+"] ";
  if (std::string("")==indent){
    info("Hierarchy for Object "+name()+"["+type()+"]","Hierarchy::tree");
  }
  msgSvc(MsgSvc::NONE,line,"");
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter){
    std::string tab=" ";
    (*iter)->tree(indent+tab);
  }
}
tree() [2/2]
void Hierarchy::tree () [inline], [inherited]
Definition at line 46 of file Hierarchy.h.
References Hierarchy::m_parent, and Hierarchy::tree().
Referenced by Hierarchy::children(), export_obj(), and Hierarchy::tree().
{ tree(""); }; // output tree of Hierarchy from object
trigger()
StatusCode A3PE::trigger ()
Definition at line 363 of file A3PE.cpp.
References Object::debug(), m_acqReg, and Register::setBit().
Referenced by BOOST_PYTHON_MODULE(), Acquisition::execute(), and reset().
                        {
  debug("Trigger sequence started","A3PE::trigger");
  return m_acqReg->setBit(0,1);
}
triggerDelay()
unsigned int A3PE::triggerDelay ()
Definition at line 480 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_triggerReg, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                               {
  if (m_triggerReg->read().isFailure()){
    error("Cannot read Trigger register "+m_triggerReg->name(),
        "Register::triggerDelay");
    return 0;
  }
  unsigned long int data=m_triggerReg->io()->dataU32()[0];
  return (data&(255));
}
triggerRam()
RAM* A3PE::triggerRam () [inline]
Definition at line 544 of file A3PE.h.
References m_triggerRam.
Referenced by BOOST_PYTHON_MODULE(), dumpTrigger(), and loadTrigger().
                   {
    return m_triggerRam;
  }
triggerRate()
unsigned int A3PE::triggerRate ()
Definition at line 539 of file A3PE.cpp.
References shell::data(), IOdata::dataU32(), Object::error(), IOobject::io(), StatusCode::isFailure(), m_triggerReg, Object::name(), and IOobject::read().
Referenced by BOOST_PYTHON_MODULE(), and reset().
                              {
  if (m_triggerReg->read().isFailure()){
    error("Cannot read Trigger register "+m_triggerReg->name(),
        "Register::setTriggerRate");
    return 0;
  }
  unsigned long int data=m_triggerReg->io()->dataU32()[0];
  return (data>>8) & (65535) ;
}
triggerReg()
Register* A3PE::triggerReg () [inline]
Definition at line 520 of file A3PE.h.
References m_triggerReg.
Referenced by BOOST_PYTHON_MODULE().
                        {
    return m_triggerReg;
  }
type()
std::string Object::type () [inline], [inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), EmulateFE::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), EmulateFE::setGenerationType(), Object::setType(), and Hierarchy::tree().
{ return m_type; } //< Get Object m_type
update()
void A3PE::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Element.
Definition at line 465 of file A3PE.h.
References internalAXSequence(), latencyAX(), lengthAX(), pipeline(), setInternalAXSequence(), setLatencyAX(), setLengthAX(), and setPipeline().
Referenced by A3PE_BitFlip.A3PE_BitFlip::__init__(), Acquisition.Acquisition::__init__(), EmulateFE.EmulateFE::__init__(), AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
                 {
  };
verbose() [1/2]
void Object::verbose (std::string mymsg) [inline], [inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTInterface::read(), UsbFTMLInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::usbWriteU8(), wait(), UsbFTMLInterface::write(), and UsbFTInterface::write().
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name); }
verbose() [2/2]
void Object::verbose (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
{ m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name); }
warning() [1/2]
void Object::warning (std::string mymsg) [inline], [inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsGlue::date(), SpecsMezzanine::date(), SpecsSlave::detect(), NI6008::device(), A3PE_BitFlip::execute(), Acquisition::execute(), UsbFTInterfaceTest::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), DCU::init(), SpecsSlave::init(), StorageFifo::initialize(), StorageFifoAcquisition::initialize(), A3PE_BitFlip::initialize(), Acquisition::initialize(), TestI2C::initialize(), EmulateFE::initialize(), TestSPI::initialize(), TestUSB::initialize(), SpecsGlue::led(), SpecsMezzanine::led(), loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbI2cBus::read(), Phaser::read(), ICPhaser::read(), UsbSpiBus::read(), DCU::readMode(), DCU::reset(), SpecsMaster::reset(), SpecsSlave::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbI2cBus::write(), Phaser::write(), ICPhaser::write(), UsbSpiBus::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name); }
warning() [2/2]
void Object::warning (std::string mymsg, std::string name) [inline], [inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
{ m_log.msgSvc (MsgSvc::WARNING , mymsg, name); }
writeFromAXRamUsb()
bool A3PE::writeFromAXRamUsb ()
Definition at line 276 of file A3PE.cpp.
References Register::getBit(), and m_setupReg.
Referenced by BOOST_PYTHON_MODULE(), and reset().
                            {
  return (m_setupReg->getBit(10)==1&&m_setupReg->
      getBit(11)==1);
}
writeLengthFifoReg()
Register* A3PE::writeLengthFifoReg () [inline]
Definition at line 508 of file A3PE.h.
References m_writeLengthFifoReg.
Referenced by BOOST_PYTHON_MODULE().
                                {
    return m_writeLengthFifoReg;
  }
writeStorageFifoUsb()
bool A3PE::writeStorageFifoUsb ()
Definition at line 248 of file A3PE.cpp.
References Register::getBit(), and m_setupReg.
Referenced by BOOST_PYTHON_MODULE(), and reset().
                              {
  if (m_setupReg->getBit(8)==1&&m_setupReg->getBit(9)==1) return true;
  return false;
}
Member Data Documentation
m_acqReg
Register* A3PE::m_acqReg [private]
Definition at line 592 of file A3PE.h.
Referenced by A3PE(), acqReg(), acquisition(), dataReady(), enableStorage(), pipeline(), setPipeline(), setSoftwareTrigger(), softwareTrigger(), startSequenceAX(), and trigger().
m_attribString
std::string Attrib::m_attribString[10] [protected], [inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
m_clockDivisionReg
Register* A3PE::m_clockDivisionReg [private]
Definition at line 596 of file A3PE.h.
Referenced by A3PE(), clockDivision(), clockDivisionReg(), and setClockDivision().
m_connection
Hierarchy* Element::m_connection [protected], [inherited]
Definition at line 70 of file Element.h.
Referenced by UsbSpiBus::clockDivider(), Element::connection(), Element::Element(), UsbMLI2cBus::init(), UsbMLSpiBus::init(), UsbI2cBus::init(), UsbSpiBus::init(), IOobject::init(), UsbI2cBus::read(), UsbSpiBus::read(), UsbSpiBus::setClockDivider(), Element::setConnection(), UsbI2cBus::write(), and UsbSpiBus::write().
m_ctrlAnaMezzReg
Register* A3PE::m_ctrlAnaMezzReg [private]
Definition at line 595 of file A3PE.h.
Referenced by A3PE(), and ctrlAnaMezzReg().
m_ctrlReg
Register* A3PE::m_ctrlReg [private]
Definition at line 588 of file A3PE.h.
Referenced by A3PE(), and ctrlReg().
m_fromAXRam
RAM* A3PE::m_fromAXRam [private]
Definition at line 607 of file A3PE.h.
Referenced by A3PE(), and fromAXRam().
m_fromAXRamPtr
Register* A3PE::m_fromAXRamPtr [private]
Definition at line 605 of file A3PE.h.
Referenced by A3PE(), fromAXRamPtrReg(), and setAddFromAXRam().
m_fromAXReg
Register* A3PE::m_fromAXReg [private]
Definition at line 599 of file A3PE.h.
Referenced by A3PE(), and fromAXReg().
m_globalUsbReset
Register* A3PE::m_globalUsbReset [private]
Definition at line 587 of file A3PE.h.
Referenced by A3PE(), and reset().
m_latencyAX
Register* A3PE::m_latencyAX [private]
Definition at line 608 of file A3PE.h.
Referenced by A3PE(), latencyAX(), and setLatencyAX().
m_latencyReg
Register* A3PE::m_latencyReg [private]
Definition at line 593 of file A3PE.h.
Referenced by A3PE(), fifoLatency(), latencyReg(), and setFifoLatency().
m_lengthAX
Register* A3PE::m_lengthAX [private]
Definition at line 609 of file A3PE.h.
Referenced by A3PE(), lengthAX(), and setLengthAX().
m_patternRam
RAM* A3PE::m_patternRam [private]
Definition at line 602 of file A3PE.h.
Referenced by A3PE(), and patternRam().
m_resetReg
Register* A3PE::m_resetReg [private]
Definition at line 589 of file A3PE.h.
Referenced by A3PE(), enableStorage(), reset(), resetAcquisitionWriteCounter(), resetFE(), resetFromAXRam(), resetLatencyCounter(), resetPatternFifo(), resetReg(), resetSequenceFromToAX(), resetSPI(), resetStorageFifo(), resetToAXRam(), resetTriggerFifo(), and resetUsbPhasers().
m_setupReg
Register* A3PE::m_setupReg [private]
Definition at line 590 of file A3PE.h.
Referenced by A3PE(), enableADC(), internalAXSequence(), readPatternFifoUsb(), readToAXRamUsb(), readTriggerFifoUsb(), setAXRamUsb(), setEnableADC(), setInternalAXSequence(), setReadPatternFifoUsb(), setReadToAXRamUsb(), setReadTriggerFifoUsb(), setupReg(), setWriteFromAXRamUsb(), setWriteStorageFifoUsb(), writeFromAXRamUsb(), and writeStorageFifoUsb().
m_spare3Reg
Register* A3PE::m_spare3Reg [private]
Definition at line 600 of file A3PE.h.
Referenced by A3PE(), and spare3Reg().
m_statusReg
Register* A3PE::m_statusReg [private]
Definition at line 591 of file A3PE.h.
Referenced by A3PE(), and statusReg().
m_storageRam
RAM* A3PE::m_storageRam [private]
Definition at line 601 of file A3PE.h.
Referenced by A3PE(), setFifoDepth(), and storageRam().
m_testRam
RAM* A3PE::m_testRam [private]
Definition at line 610 of file A3PE.h.
Referenced by A3PE(), and testRam().
m_toAXRam
RAM* A3PE::m_toAXRam [private]
Definition at line 606 of file A3PE.h.
Referenced by A3PE(), and toAXRam().
m_toAXRamPtr
Register* A3PE::m_toAXRamPtr [private]
Definition at line 604 of file A3PE.h.
Referenced by A3PE(), setAddToAXRam(), and toAXRamPtrReg().
m_toAXReg
Register* A3PE::m_toAXReg [private]
Definition at line 598 of file A3PE.h.
Referenced by A3PE(), and toAXReg().
m_triggerRam
RAM* A3PE::m_triggerRam [private]
Definition at line 603 of file A3PE.h.
Referenced by A3PE(), and triggerRam().
m_triggerReg
Register* A3PE::m_triggerReg [private]
Definition at line 597 of file A3PE.h.
Referenced by A3PE(), nTrigger(), setNTrigger(), setTriggerDelay(), setTriggerRate(), triggerDelay(), triggerRate(), and triggerReg().
m_writeLengthFifoReg
Register* A3PE::m_writeLengthFifoReg [private]
Definition at line 594 of file A3PE.h.
Referenced by A3PE(), fifoDepth(), setFifoDepth(), and writeLengthFifoReg().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/inc/A3PE.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/src/A3PE.cpp