Interface Class Reference
#include <inc/Interface.h>
Public Member Functions
Interface ()
Standard constructor.
virtual ~Interface ()
Destructor.
virtual void help ()=0
virtual StatusCode init ()=0
virtual void reset ()=0
virtual void update ()=0
virtual StatusCode read (IOdata *)=0
virtual StatusCode write (IOdata *)=0
Additional Inherited Members
Detailed Description
Author
Date
2006-10-23
Definition at line 16 of file Interface.h.
Constructor & Destructor Documentation
Interface()
Interface::Interface ()
Standard constructor.
Definition at line 18 of file Interface.cpp.
References Attrib::add(), Attrib::ELEMENT, Attrib::INTERFACE, Object::setName(), and Object::setType().
                       {
  setName("Interface");
  setType("Interface");
  add(Attrib::ELEMENT); add(Attrib::INTERFACE);
}
 Interface()
Interface::~Interface () [virtual]
Destructor.
Definition at line 26 of file Interface.cpp.
{}
Member Function Documentation
help()
virtual void Interface::help () [pure virtual]
printout help for the element
Implements Element.
Implemented in UsbFTInterface, UsbFTMLInterface, SpecsInterface, SpecsParallelBus, SpecsMezzanine, UsbSpiBus, UsbI2cBus, SpecsGlue, and InterfaceWrap.
Referenced by BOOST_PYTHON_MODULE().
init()
virtual StatusCode Interface::init () [pure virtual]
init the component
Returns
void
Implements Element.
Implemented in UsbFTInterface, UsbFTMLInterface, SpecsInterface, SpecsSlave, SpecsParallelBus, UsbSpiBus, UsbI2cBus, and InterfaceWrap.
Referenced by BOOST_PYTHON_MODULE().
read()
virtual StatusCode Interface::read (IOdata *) [pure virtual]
Implemented in SpecsInterface, UsbFTInterface, UsbFTMLInterface, UsbSpiBus, UsbI2cBus, and InterfaceWrap.
Referenced by BOOST_PYTHON_MODULE(), UsbSpiBus::clockDivider(), UsbI2cBus::read(), and UsbSpiBus::read().
reset()
virtual void Interface::reset () [pure virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Element.
Implemented in UsbFTInterface, UsbFTMLInterface, SpecsInterface, SpecsSlave, SpecsParallelBus, UsbSpiBus, UsbI2cBus, and InterfaceWrap.
Referenced by BOOST_PYTHON_MODULE().
update()
virtual void Interface::update () [pure virtual]
Update the Element configuration from the actual hardware
Implements Element.
Implemented in UsbFTInterface, UsbFTMLInterface, SpecsInterface, SpecsParallelBus, UsbSpiBus, UsbI2cBus, and InterfaceWrap.
Referenced by BOOST_PYTHON_MODULE(), AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
write()
virtual StatusCode Interface::write (IOdata *) [pure virtual]
Implemented in SpecsInterface, UsbFTInterface, UsbFTMLInterface, UsbSpiBus, UsbI2cBus, and InterfaceWrap.
Referenced by BOOST_PYTHON_MODULE(), UsbI2cBus::read(), UsbSpiBus::read(), UsbSpiBus::setClockDivider(), UsbI2cBus::write(), and UsbSpiBus::write().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/inc/Interface.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/src/Interface.cpp