CurrentMeasurement Class Reference
#include <include/CurrentMeasurement.h>
Classes
class CurrentMeasurement
Public Member Functions
CurrentMeasurement ()
Standard constructor.
virtual ~CurrentMeasurement ()
virtual StatusCode initialize ()
Destructor.
virtual StatusCode execute ()
virtual StatusCode finalize ()
int numberOfDevices ()
StatusCode setFrequency (unsigned int frequency)
unsigned int frequency ()
Protected Member Functions
CurrentMeasurement * clone ()
Private Attributes
TRandom * m_rnd
unsigned int m_frequency
NI6008 * m_device
unsigned int m_numberOfDevices
TTree * m_tree
Int_t m_runNumber
Int_t m_evtNumber
Int_t m_timestamp [4]
Int_t m_duration [4]
time_t m_startTime
double m_ai0 [4]
double m_ai1 [4]
double m_ai2 [4]
double m_ai3 [4]
Additional Inherited Members
Detailed Description
Author
Frederic Machefert
Date
2010-01-07
Definition at line 23 of file CurrentMeasurement.h.
Constructor & Destructor Documentation
CurrentMeasurement()
CurrentMeasurement::CurrentMeasurement ()
Standard constructor.
Definition at line 26 of file CurrentMeasurement.cpp.
References m_device, Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
                                        {
  setName ("CurrentMeasurement");
  setType ("NI6008");
  setTitle("NI6008 current measurement");
  m_device = 0;
}
 CurrentMeasurement()
virtual CurrentMeasurement::~CurrentMeasurement () [inline], [virtual]
Definition at line 28 of file CurrentMeasurement.h.
References execute(), finalize(), and initialize().
{};
Member Function Documentation
clone()
CurrentMeasurement* CurrentMeasurement::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 67 of file CurrentMeasurement.h.
References CurrentMeasurement().
                             {
    return new CurrentMeasurement (*this);
  };
execute()
StatusCode CurrentMeasurement::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 75 of file CurrentMeasurement.cpp.
References application(), NI6008::cmd(), Processus::dataFill(), NI6008::device(), m_ai0, m_ai1, m_ai2, m_ai3, m_device, m_duration, m_evtNumber, m_frequency, m_startTime, m_timestamp, m_tree, Options::nEvt(), NI6008::numberOfDevices(), Application::options(), StatusCode::SUCCESS, and wait().
Referenced by ~CurrentMeasurement().
                                         {
  for (int i = 0; i<m_device->numberOfDevices(); ++i){
    std::string dev = m_device->device(i);
    std::string val = m_device->cmd(dev, "ai");
    std::istringstream splitval(val);
    std::string v0, v1, v2, v3;
    splitval >> v0;
    splitval >> v1;
    splitval >> v2;
    splitval >> v3;
    // m_ai0[i]=toDouble(v0);
    // m_ai1[i]=toDouble(v1);
    // m_ai2[i]=toDouble(v2);
    // m_ai3[i]=toDouble(v3);
    m_ai0[i]=atof(v0.c_str());
    m_ai1[i]=atof(v1.c_str());
    m_ai2[i]=atof(v2.c_str());
    m_ai3[i]=atof(v3.c_str());
    time_t t = time(0);
    m_timestamp[i]=t;
    m_duration[i]=difftime(t, m_startTime);
    dataFill(0+5*i, m_duration[i]);
    dataFill(1+5*i, m_ai0[i]);
    dataFill(2+5*i, m_ai1[i]);
    dataFill(3+5*i, m_ai2[i]);
    dataFill(4+5*i, m_ai3[i]);
  }
  if (application()->options()->dataStorage()){
    m_evtNumber=application()->options()->nEvt()-1;
    m_tree->Fill();
  }
  wait(m_frequency);
  return StatusCode::SUCCESS;
}
finalize()
StatusCode CurrentMeasurement::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 113 of file CurrentMeasurement.cpp.
References StatusCode::SUCCESS.
Referenced by ~CurrentMeasurement().
                                          {
  // if (application()->options()->dataStorage()){
  // m_tree->Print();
  // }
  return StatusCode::SUCCESS;
}
frequency()
unsigned int CurrentMeasurement::frequency () [inline]
Definition at line 62 of file CurrentMeasurement.h.
References m_frequency.
Referenced by BOOST_PYTHON_MODULE(), and setFrequency().
                          {
    return m_frequency;
  }
initialize()
StatusCode CurrentMeasurement::initialize () [virtual]
Destructor.
Implements Processus.
Definition at line 36 of file CurrentMeasurement.cpp.
References Processus::addDataStream(), application(), NI6008::device(), Processus::element(), Object::info(), itos(), m_ai0, m_ai1, m_ai2, m_ai3, m_device, m_duration, m_evtNumber, m_numberOfDevices, m_runNumber, m_startTime, m_timestamp, m_tree, Object::name(), NI6008::numberOfDevices(), Application::options(), Options::runNumber(), StatusCode::SUCCESS, and Object::title().
Referenced by ~CurrentMeasurement().
                                            {
  m_device = dynamic_cast <NI6008*> (element());
  m_numberOfDevices = m_device->numberOfDevices();
  time(&m_startTime);
  if (application()->options()->dataStorage()){
    m_tree = new TTree(name().c_str(), title().c_str());
    m_tree->Branch("Run",&m_runNumber,"Run/I");
    m_tree->Branch("Event",&m_evtNumber,"Event/I");
    m_tree->Branch("Time",m_timestamp,(std::string("Time[")+
                       itos(m_device->numberOfDevices())+
                       std::string("]/I")).c_str());
    m_tree->Branch("Duration",m_duration,(std::string("Duration[")+
                       itos(m_device->numberOfDevices())+
                       std::string("]/I")).c_str());
    m_tree->Branch("ai0",m_ai0,
           (std::string("ai0[")+itos(m_device->numberOfDevices())+std::string("
      ]/D")).c_str());
    m_tree->Branch("ai1",m_ai1,
           (std::string("ai1[")+itos(m_device->numberOfDevices())+std::string("
      ]/D")).c_str());
    m_tree->Branch("ai2",m_ai2,
           (std::string("ai2[")+itos(m_device->numberOfDevices())+std::string("
      ]/D")).c_str());
    m_tree->Branch("ai3",m_ai3,
           (std::string("ai3[")+itos(m_device->numberOfDevices())+std::string("
      ]/D")).c_str());
  }
  for (int i = 0; i<m_device->numberOfDevices(); ++i){
    std::string dev = m_device->device(i);
    info("Preparing dataStream for device "+dev);
    addDataStream((dev+std::string(":Duration")).c_str(),"Duration");
    addDataStream((dev+std::string(":ai0")).c_str(),"Channel 0");
    addDataStream((dev+std::string(":ai1")).c_str(),"Channel 1");
    addDataStream((dev+std::string(":ai2")).c_str(),"Channel 2");
    addDataStream((dev+std::string(":ai3")).c_str(),"Channel 3");
  }
  m_runNumber=application()->options()->runNumber();
  return StatusCode::SUCCESS;
}
numberOfDevices()
int CurrentMeasurement::numberOfDevices () [inline]
Definition at line 53 of file CurrentMeasurement.h.
References m_numberOfDevices.
Referenced by BOOST_PYTHON_MODULE(), createPlot(), and updatePlot().
                       {
    return m_numberOfDevices;
  }
setFrequency()
StatusCode CurrentMeasurement::setFrequency (unsigned int frequency) [inline]
Definition at line 57 of file CurrentMeasurement.h.
References frequency(), m_frequency, and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                                                 {
    m_frequency = frequency;
    return StatusCode::SUCCESS;
  }
Member Data Documentation
m_ai0
double CurrentMeasurement::m_ai0[4] [private]
Definition at line 82 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
m_ai1
double CurrentMeasurement::m_ai1[4] [private]
Definition at line 83 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
m_ai2
double CurrentMeasurement::m_ai2[4] [private]
Definition at line 84 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
m_ai3
double CurrentMeasurement::m_ai3[4] [private]
Definition at line 85 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
m_device
NI6008* CurrentMeasurement::m_device [private]
Definition at line 74 of file CurrentMeasurement.h.
Referenced by CurrentMeasurement(), execute(), and initialize().
m_duration
Int_t CurrentMeasurement::m_duration[4] [private]
Definition at line 80 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
m_evtNumber
Int_t CurrentMeasurement::m_evtNumber [private]
Definition at line 78 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
m_frequency
unsigned int CurrentMeasurement::m_frequency [private]
Definition at line 73 of file CurrentMeasurement.h.
Referenced by execute(), frequency(), and setFrequency().
m_numberOfDevices
unsigned int CurrentMeasurement::m_numberOfDevices [private]
Definition at line 75 of file CurrentMeasurement.h.
Referenced by initialize(), and numberOfDevices().
m_rnd
TRandom* CurrentMeasurement::m_rnd [private]
Definition at line 69 of file CurrentMeasurement.h.
m_runNumber
Int_t CurrentMeasurement::m_runNumber [private]
Definition at line 77 of file CurrentMeasurement.h.
Referenced by initialize().
m_startTime
time_t CurrentMeasurement::m_startTime [private]
Definition at line 81 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
m_timestamp
Int_t CurrentMeasurement::m_timestamp[4] [private]
Definition at line 79 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
m_tree
TTree* CurrentMeasurement::m_tree [private]
Definition at line 76 of file CurrentMeasurement.h.
Referenced by execute(), and initialize().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatNI/inc/proc/CurrentMeasurement.h
/home/eleclhcb/LHCb/lbcat-cmake/CatNI/src/proc/CurrentMeasurement.cpp