SpecsInterface Class Reference
#include <include/SpecsInterface.h>Inheritance diagram for SpecsInterface::
Public Types
enum Attribut {
UNDEFINED,
PASSIVE,
ACTIVE,
INTERFACE,
IO,
IODATA,
ELEMENT,
HARDWARE,
PROCESSUS,
SOFTWARE
 }
Public Member Functions
SpecsInterface ()
virtual ~SpecsInterface ()
virtual void help ()
virtual StatusCode init ()
virtual void reset ()
virtual void update ()
void setAddress (unsigned char)
unsigned char address ()
void setOutputSelect (unsigned char)
unsigned char outputSelect ()
virtual SpecsSlave * specsSlave ()
virtual SpecsMaster * specsMaster ()
virtual SPECSSLAVE * specsSlaveDevice ()
virtual SPECSMASTER * specsMasterDevice ()
virtual StatusCode read (IOdata *io)
virtual StatusCode write (IOdata *io)
bool specsWriteI2c (unsigned char address, unsigned char nData, U8 *data)
bool specsWriteI2c (unsigned char address, std::vector< U8 > data)
bool specsReadI2c (unsigned char address, unsigned char nOctects, U8 *i2cWords)
bool specsReadI2c (unsigned char address, std::vector< unsigned char > &specsWords)
bool specsWriteI2c (unsigned char address, unsigned char subAddress, unsigned char nData, U8 *data)
bool specsWriteI2c (unsigned char address, unsigned char outputSel, unsigned char subAddress, unsigned char nData, U8 *data)
bool specsReadI2c (unsigned char address, unsigned char subAddress, unsigned char nOctets, U8 *i2cWords)
bool specsReadI2c (unsigned char address, unsigned char outputSel, unsigned char subAddress, unsigned char nOctets, U8 *i2cWords)
bool specsWriteParallel (unsigned char address, unsigned short data)
bool specsReadParallel (unsigned char address, U16 &data)
bool specsWriteRegister (unsigned char, unsigned short)
bool specsReadRegister (unsigned char, U16 &)
void recursiveInitElement ()
void recursiveInitCommunications ()
StatusCode setConnection (Hierarchy *)
Hierarchy * connection ()
void clear ()
void setParent (Hierarchy *parent)
Hierarchy * parent ()
Hierarchy * parent (std::string)
Hierarchy * origin ()
virtual void addChild (Hierarchy *element)
std::vector< Hierarchy * > children ()
Hierarchy * child (std::string)
Hierarchy * childTyped (std::string)
unsigned long numberOfChildren ()
bool hasChildren ()
void delChild (Hierarchy *)
void delChild (std::string)
std::string path (std::string=std::string(``))
std::string pathTyped (std::string=std::string(``))
void tree (std::string indent=std::string(``))
void tree ()
std::string name () const
std::string type ()
unsigned char id ()
std::string title ()
void msgSvc (int level, std::string msg, std::string name)
void msg (std::string mymsg)
void msg (std::string mymsg, std::string name)
void verbose (std::string mymsg)
void verbose (std::string mymsg, std::string name)
void debug (std::string mymsg)
void debug (std::string mymsg, std::string name)
void info (std::string mymsg)
void info (std::string mymsg, std::string name)
void warning (std::string mymsg)
void warning (std::string mymsg, std::string name)
void error (std::string mymsg)
void error (std::string mymsg, std::string name)
void fatal (std::string mymsg)
void fatal (std::string mymsg, std::string name)
void setName (std::string name)
void setType (std::string type)
void setId (unsigned char id)
void setTitle (std::string title)
void setDllName (std::string dllName)
std::string dllName ()
bool is (int attribut)
void add (int attribut)
void remove (int attribut)
std::string attributs ()
Protected Attributes
unsigned char m_address
unsigned char m_outputSelect
Hierarchy * m_connection
std::string m_attribString [10]
Private Attributes
int m_slot
Detailed Description
Class to describe general electronics object
Author
Frederic Machefert
Date
2004-01-18
Definition at line 54 of file SpecsInterface.h.
Member Enumeration Documentation
enum Attrib::Attribut [inherited]
Enumerator:
UNDEFINED
PASSIVE
ACTIVE
INTERFACE
IO
IODATA
ELEMENT
HARDWARE
PROCESSUS
SOFTWARE
Definition at line 29 of file Attrib.h.
                
    UNDEFINED,
    PASSIVE,
    ACTIVE,
    INTERFACE,
    IO,
    IODATA,
    ELEMENT,
    HARDWARE,
    PROCESSUS,
    SOFTWARE
  ; // array m_attribString must be changed into Attrib::Attrib if this enu is m
      odified.
Constructor & Destructor Documentation
SpecsInterface::SpecsInterface ()
Definition at line 21 of file SpecsInterface.cpp.
References m_address, m_outputSelect, and Object::setId().
                              
  m_address=0;
  m_outputSelect=0x0;
  setId(0);
virtual SpecsInterface::~SpecsInterface () [inline, virtual]
Definition at line 57 of file SpecsInterface.h.
 //< Destructor
Member Function Documentation
void Attrib::add (int attribut) [inline, inherited]
Add an attribut
Definition at line 67 of file Attrib.h.
References Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by A3PE::A3PE(), Attrib::Attrib(), SpecsMezzanine::cmdline(), Computer::Computer(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Processus::Processus(), Proto40MHz_v1::Proto40MHz_v1(), Attrib::remove(), SeqPGA::SeqPGA(), SpecsMaster::SpecsMaster(), and SpecsSlave::SpecsSlave().
                            
    if (attribut!=Attrib::UNDEFINED) remove(Attrib::UNDEFINED);
    bool duplicate = false ;
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        duplicate = true ;
      
    
    if (!duplicate)
      m_attributs.push_back(attribut);
    
  
void Hierarchy::addChild (Hierarchy * element) [virtual, inherited]
Definition at line 83 of file Hierarchy.cpp.
References Object::debug(), Hierarchy::m_children, Object::name(), and Hierarchy::setParent().
Referenced by A3PE::A3PE(), SpecsMezzanine::addBus(), SpecsSlave::addI2c(), Application::create(), CU_v1::CU_v1(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), LSDelayChipV1::LSDelayChipV1(), FePGA::MakeRAM(), FePGA::MakeRegister(), Phaser::Phaser(), Proto40MHz_v1::Proto40MHz_v1(), SeqPGA::SeqPGA(), SpecsMezzanine::SpecsMezzanine(), UsbI2cBus::UsbI2cBus(), and UsbSpiBus::UsbSpiBus().
                                          
  element->setParent(this);
  m_children.push_back(element);
  debug(element->name()+" added to the child tree.","Hierarchy::addChild");
unsigned char SpecsInterface::address ()
Definition at line 33 of file SpecsInterface.cpp.
References m_address.
Referenced by BOOST_PYTHON_MODULE(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), SpecsSlave::init(), SpecsSlave::reset(), and SpecsSlave::resetInternal().
                                      
    return m_address;
std::string Attrib::attributs () [inherited]
Print the Attrib of an Object
Definition at line 54 of file Attrib.cpp.
References images::index, Attrib::m_attribString, and Attrib::m_attributs.
Referenced by export_obj().
                            
  std::string output;
  std::vector<int>::iterator iter ;
  for (unsigned int index = 0 ; index < m_attributs.size() ; ++index)
    if (m_attributs.size() - index > 1)
      output.append(m_attribString[m_attributs[index]]);
      output.append(":");
    
    else
      output.append(m_attribString[m_attributs[index]]);
    
  
  return output;
Hierarchy * Hierarchy::child (std::string path) [inherited]
Definition at line 133 of file Hierarchy.cpp.
References Hierarchy::child(), Hierarchy::children(), Object::name(), Hierarchy::origin(), Hierarchy::parent(), and Object::warning().
Referenced by Application::cd(), Hierarchy::child(), and export_obj().
                                         
  std::string newpath = path;
  std::string up("..");
  std::string separator(1,'/');
  Hierarchy * newcurrent = 0;
  // info("path="+path,"Hierarchy::child");
  if (path.compare("")==0 || path.compare("/")==0)
    // debug("return origin","Hierarchy::child");
    return origin();
  
  if (path.compare(name())==0)
    // debug("return itself","Hierarchy::child");
    return this;
  
  if (path.compare("..")==0)
    if (0!=this->parent()) return this->parent();
    else return this;
  
  if (path.compare("../")==0)
    if (0!=this->parent()) return this->parent();
    else return this;
  
  int npos=path.find(separator,0);
  // info("find separator in "+itos(npos)+" of "+path,"Hierarchy::child");
  // remove last separator
  if (npos == (int)(path.size()-1))
    newpath = std::string(path,0,npos);
    path = newpath;
  
  if (npos==0)
    // debug("Going back to origin and calling child","Hierarchy::child");
    newpath=std::string(path,1,path.size()-1);
    return origin()->child(newpath);
  
  else
    if (npos== (int)(std::string::npos))
      // debug("Getting chid "+path+" of "+this->name(),"Hierarchy::child");
      
      std::vector <Hierarchy*> list = children();
      std::vector<Hierarchy*>::iterator iter;
      for (iter=list.begin();iter!=list.end();iter++)
        if ((*iter)->name().compare(path)==0)
          return *iter;
        
      
      warning(this->name()+std::string(" has no child '")+path+"'","Hierarchy::ch
      ild");
      return this;
    
    else
    
      int ipos=path.find(separator,0);
      // info("default behaviour "+path+" with separator in "+itos(ipos),"Hi
      erarchy::child");
      std::string newcurrentname=std::string(path,0,ipos);
      newpath=std::string(path,ipos+1,path.size()-1);
      // info("looking now for "+newpath+" from "+newcurrentname,"Hierarchy:
      :child");
      if (0==newcurrentname.compare(origin()->name()))
        // info("current is computer. Looking for children"+newcurrentname
      ,"Hierarchy::child");
        return origin()->child(newpath);
      
      newcurrent = (Hierarchy*)0;
      std::vector <Hierarchy*> list = children();
      std::vector<Hierarchy*>::iterator iter;
      for (iter=list.begin();iter!=list.end();iter++)
        if ((*iter)->name().compare(newcurrentname)==0)
          newcurrent = (*iter);
        
      
      if ((Hierarchy*)0==newcurrent)
        if (newcurrentname.compare("..")==0 && 0!=parent())
          newcurrent=this->parent();
          // debug("newcurrent was .. -> parent="+parent()->name());
        
        else
        
          warning(this->name()+" has no child '"+newcurrentname+"'",
              "Hierarchy::child");
          return this;
        
      
      // debug("recurrence call for "+newpath+" on "+newcurrent->name(),"Hie
      rarchy::child");
      return newcurrent -> child (newpath);
    
  
std::vector<Hierarchy*> Hierarchy::children () [inline, inherited]
Definition at line 33 of file Hierarchy.h.
References Hierarchy::m_children.
Referenced by Hierarchy::child(), Hierarchy::childTyped(), export_obj(), SpecsSlave::recursiveInitCommunications(), Element::recursiveInitCommunications(), Element::recursiveInitElement(), Application::setConfig(), and Hierarchy::tree().
 return m_children; //< get list of child(ren)
Hierarchy * Hierarchy::childTyped (std::string path) [inherited]
Definition at line 239 of file Hierarchy.cpp.
References Hierarchy::children(), Hierarchy::m_origin, Object::name(), Hierarchy::parent(), and Object::warning().
Referenced by export_obj().
                                              
  std::string newpath = path;
  std::string up("..");
  std::string separator(1,'/');
  std::string typeopen(1,'[');
  std::string typeclose(1,']');
  Hierarchy * newcurrent = 0;
  unsigned int npos=path.find(separator,0);
  unsigned int opos=path.find(typeopen,0);
  if (npos==std::string::npos || npos == path.size()-1)
    if (path.compare("..")==0)
      return parent();
    
    if (npos == path.size()-1)
      newpath = std::string(path,0,opos);
      path = newpath;
    
    std::vector < Hierarchy* > list = children();
    std::vector < Hierarchy* >::iterator iter;
    for (iter=list.begin();iter!=list.end();iter++)
      std::string notypepath = std::string(path,0,opos);
      if ((*iter)->name().compare(notypepath)==0)
        return *iter;
      
    
    warning(this->name()+std::string(" has no child ") +path,"Hierarchy::child");
      
    return 0;
  
  else
    if (std::string(path,0,3).compare(std::string("../"))==0)
      newpath=std::string(path,3,path.size()-3);
      newcurrent = parent();
    
    if (std::string(path,0,1).compare(std::string("/"))==0)
      newpath=std::string(path,1,path.size()-1);
      newcurrent = (Hierarchy*) m_origin;
    
    if ((std::string(path,0,3).compare(std::string("../")) !=0) &&
        std::string(path,0,1).compare(std::string("/"))!=0)
      opos = path.find(typeopen,0);
      int cpos = path.find(typeclose,0);
      std::string name = std::string (path,0,opos);
      newcurrent = childTyped(name);
      if (newcurrent ==0)
        warning(path+": no child found with such a name","Hierarchy::child");
      
      newpath = std::string (path,cpos+2,path.size()-cpos-1);
    
    return newcurrent -> childTyped (newpath);
  
void Hierarchy::clear () [inherited]
Definition at line 35 of file Hierarchy.cpp.
References Hierarchy::delChild(), Object::info(), Hierarchy::m_children, and Object::name().
Referenced by export_obj().
                     
  std::vector<Hierarchy*> listlocale;
  std::vector<Hierarchy*>::iterator iter;
  info("loop on "+name()+" children.","Hierarchy::clear");
  for (iter=m_children.begin();iter!=m_children.end();iter++)
      info("processing "+(*iter)->name()+".","Hierarchy::clear");
/*
      (*iter)->clear();
// this->delChild((*iter));
      info("obj "+(*iter)->name()+" being cleared.","Hierarchy::clear");
      delete (*iter);
      info("Object deleted.","Hierarchy::clear");
      m_children.erase(iter);
      info("Object removed from the tree.","Hierarchy::clear");
*/
    (*iter)->clear();
    info("Adding object "+(*iter)->name()+" from the Hierarchy to the list of del
      eted objects.","Hierarchy::clear");
    listlocale.push_back((*iter));
  
  for (iter=listlocale.begin();iter!=listlocale.end();iter++)
    info("Removing object "+(*iter)->name()+".","Hierarchy::clear");
    this->delChild(*iter);
// m_children.erase(iter);
    delete (*iter);
  
  info("Getting out of "+name());
Hierarchy * Element::connection () [inherited]
Get IO interface
Definition at line 84 of file Element.cpp.
References Element::m_connection, Object::name(), and Object::warning().
Referenced by UsbSpiBus::clockDivider(), export_obj(), UsbSpiBus::read(), UsbI2cBus::read(), IOobject::read(), UsbSpiBus::setClockDivider(), UsbSpiBus::write(), UsbI2cBus::write(), and IOobject::write().
                              
  if (0==m_connection)
    warning("no connection defined for "+name()+".","Element::connection");
    return (Hierarchy*)0;
  
  return m_connection;
void Object::debug (std::string mymsg, std::string name) [inline, inherited]
Definition at line 45 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::DEBUG , mymsg, name);
void Object::debug (std::string mymsg) [inline, inherited]
Definition at line 37 of file Object.h.
References MsgSvc::DEBUG, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by A3PE::A3PE(), A3PE::acquisition(), SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), LSDelayChipV1::checkConfigAddr(), LSDelayChipV1::checkStatusAddr(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), A3PE::dataReady(), DCU::DCU(), Hierarchy::delChild(), SpecsSlave::detect(), EmulateFE::execute(), StorageFifoAcquisition::execute(), StorageFifo::execute(), Acquisition::execute(), A3PE_BitFlip::execute(), export_obj(), FePGA::FePGA(), SpecsGlue::i2cClkMode(), SeqPGA::i2cRead(), FePGA::i2cRead(), SeqPGA::i2cWrite(), FePGA::i2cWrite(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), SpecsSlave::init(), SpecsMaster::init(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), A3PE::internalAXSequence(), SpecsMezzanine::led(), SpecsGlue::led(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Phaser::Phaser(), Data::purge(), ICPhaser::read(), Phaser::read(), FEB_v1::readFifoSpyFE(), SpecsSlave::reset(), SpecsMaster::reset(), FEB_v1::reset(), CU_v1::reset(), Proto40MHz_v1::reset(), FEB_v1::resetFifoSpyFE(), SeqPGA::resetSpi(), FEB_v1::resetSpi(), SeqPGA::SeqPGA(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), Element::setConnection(), SpecsGlue::setI2cClkMode(), A3PE::setLatencyAX(), SpecsMezzanine::setLed(), SpecsGlue::setLed(), A3PE::setLengthAX(), A3PE::setReadToAXRamUsb(), SpecsMaster::setSpeed(), A3PE::setWriteFromAXRamUsb(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), LSDelayChipV1::spiBERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), FEB_v1::testDuration(), SeqPGA::testSequence(), A3PE::trigger(), Server::updateConfig(), Server::updateState(), ICPhaser::write(), Phaser::write(), and Hierarchy::~Hierarchy().
 m_log.msgSvc (MsgSvc::DEBUG , mymsg, m_name);
void Hierarchy::delChild (std::string n) [inherited]
Definition at line 110 of file Hierarchy.cpp.
References Object::debug(), and Hierarchy::m_children.
                                   
  bool flag=false;
  std::vector<Hierarchy*>::iterator iter,remove;
  for (iter=m_children.begin();iter!=m_children.end();iter++)
    if ((*iter)->name()==n) remove=iter; flag=true;
  
  if (flag)
    debug("removing "+(*remove)->name()+" from the tree.","Hierarchy::delChild");
      
    m_children.erase(remove);
  
void Hierarchy::delChild (Hierarchy * element) [inherited]
Definition at line 92 of file Hierarchy.cpp.
References Object::debug(), and Hierarchy::m_children.
Referenced by Hierarchy::clear(), export_obj(), and Hierarchy::~Hierarchy().
                                          
  bool flag=false;
  std::vector<Hierarchy*>::iterator iter,remove;
  for (iter=m_children.begin();(iter!=m_children.end());iter++)
    if (*iter==element)
      remove=iter;
      flag=true;
    
  
  if (flag)
    debug("removing "+(*remove)->name()+" from the tree.","Hierarchy::delChild");
      
    m_children.erase(remove);
  
std::string Object::dllName () [inline, inherited]
Get accessor to member m_dllName
Returns
the current value of m_dllName
Definition at line 74 of file Object.h.
References Object::m_dllName.
Referenced by export_obj().
                       
    return m_dllName;
  
void Object::error (std::string mymsg, std::string name) [inline, inherited]
Definition at line 48 of file Object.h.
References MsgSvc::ERR, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::ERR , mymsg, name);
void Object::error (std::string mymsg) [inline, inherited]
Definition at line 40 of file Object.h.
References MsgSvc::ERR, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by ICECALv3::checkChNumber(), A3PE::clockDivision(), NI6008::cmd(), A3PE::enableStorage(), A3PE_BitFlip::execute(), export_obj(), A3PE::fifoDepth(), A3PE::fifoLatency(), FEB_v1::gbtStatus(), Register::getBit(), MSOxxxx::getStatistics(), SpecsMaster::init(), NI6008::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), A3PE::latencyAX(), A3PE::lengthAX(), A3PE::nTrigger(), MSOxxxx::open(), ICECALv3::parseParameterList(), A3PE::pipeline(), UsbFTMLInterface::read(), UsbFTInterface::read(), MSOxxxx::recv(), A3PE::reset(), MSOxxxx::send(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), ICECALv3::setAnalogCh(), A3PE::setAXRamUsb(), Register::setBit(), A3PE::setClockDivision(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), A3PE::setReadPatternFifoUsb(), A3PE::setReadToAXRamUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteFromAXRamUsb(), A3PE::setWriteStorageFifoUsb(), ICECALv3::spiFERTest(), ICECALv3::spiWriteSafe(), A3PE::startSequenceAX(), A3PE::triggerDelay(), A3PE::triggerRate(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), UsbFTMLInterface::write(), and UsbFTInterface::write().
 m_log.msgSvc (MsgSvc::ERR , mymsg, m_name);
void Object::fatal (std::string mymsg, std::string name) [inline, inherited]
Definition at line 49 of file Object.h.
References MsgSvc::FATAL, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::FATAL , mymsg, name);
void Object::fatal (std::string mymsg) [inline, inherited]
Definition at line 41 of file Object.h.
References MsgSvc::FATAL, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by export_obj(), SpecsSlave::init(), UsbSpiBus::init(), UsbI2cBus::init(), IOobject::init(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), and Element::setConnection().
 m_log.msgSvc (MsgSvc::FATAL , mymsg, m_name);
bool Hierarchy::hasChildren () [inherited]
Definition at line 303 of file Hierarchy.cpp.
References Hierarchy::m_children.
Referenced by export_obj().
                              
  return (m_children.size()>0);
virtual void SpecsInterface::help () [inline, virtual]
printout help for the element
Implements Interface.
Reimplemented in SpecsGlue, SpecsMezzanine, and SpecsParallelBus.
Definition at line 63 of file SpecsInterface.h.
References Object::info(), and Object::name().
Referenced by BOOST_PYTHON_MODULE().
 info("SpecsInterface "+name()+". No help.","SpecsInterface::help"); ;
unsigned char Object::id () [inline, inherited]
Reimplemented in MSOxxxx.
Definition at line 30 of file Object.h.
References Object::m_id.
Referenced by export_obj().
 return m_id; //< Get Object m_id
void Object::info (std::string mymsg, std::string name) [inline, inherited]
Definition at line 46 of file Object.h.
References MsgSvc::INFO, Object::m_log, and MsgSvc::msgSvc().
 m_log.msgSvc (MsgSvc::INFO , mymsg, name);
void Object::info (std::string mymsg) [inline, inherited]
Definition at line 38 of file Object.h.
References MsgSvc::INFO, Object::m_log, Object::m_name, and MsgSvc::msgSvc().
Referenced by NI6008::addDevice(), ICECALv3::bxidResynchStatus(), FEB_v1::calibCte(), checkCmd(), Hierarchy::clear(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTMLInterface::close(), UsbFTInterface::close(), MSOxxxx::closeConnection(), Processus::closeRootFile(), SpecsMezzanine::cmdline(), Server::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), A3PE::dumpPattern(), A3PE::dumpStorage(), A3PE::dumpToAX(), A3PE::dumpTrigger(), Processus::endProcessing(), PhaserRampExec::execute(), export_obj(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), ICECALv3::getAnalogCh(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), SpecsMezzanine::help(), SpecsMaster::help(), SpecsGlue::help(), SpecsParallelBus::help(), help(), NI6008::help(), Computer::help(), UsbSpiBus::help(), UsbI2cBus::help(), RAM::help(), IOobject::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbFTMLInterface::help(), SeqPGA::help(), ICPhaser::help(), FePGA::help(), FEB_v1::help(), CU_v1::help(), UsbFTInterface::help(), Proto40MHz_v1::help(), A3PE::help(), Phaser::help(), Croc::help(), MSOxxxx::help(), LSDelayChipV1::help(), ICECALv3::help(), MSOxxxx::id(), SpecsSlave::init(), SpecsMaster::init(), SpecsParallelBus::init(), init(), NI6008::init(), Computer::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), Croc::init(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), PhaserRampExec::initialize(), FEB_v1::injectModeFE(), isInt(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Application::network(), FEB_v1::oldSubtract(), MSOxxxx::open(), Processus::openRootFile(), Data::print(), FEB_v1::probeEnable(), ProcDataBase::ProcDataBase(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), FEB_v1::readFifoInjectFE(), FEB_v1::readFifoLLT(), FEB_v1::readFifoLLTFE(), FEB_v1::readFifoSpyFE(), MSOxxxx::recv(), SpecsMaster::reset(), SpecsParallelBus::reset(), reset(), NI6008::reset(), Computer::reset(), UsbSpiBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbMLI2cBus::reset(), UsbFTMLInterface::reset(), SeqPGA::reset(), FePGA::reset(), UsbFTInterface::reset(), A3PE::reset(), Croc::reset(), A3PE::resetAcquisitionWriteCounter(), FEB_v1::resetFE(), A3PE::resetFE(), FEB_v1::resetFifoInjectFE(), A3PE::resetFromAXRam(), SpecsSlave::resetInternal(), A3PE::resetLatencyCounter(), A3PE::resetPatternFifo(), A3PE::resetSequenceFromToAX(), A3PE::resetSPI(), A3PE::resetStorageFifo(), A3PE::resetToAXRam(), A3PE::resetTriggerFifo(), FePGA::resetUsb(), A3PE::resetUsbPhasers(), MSOxxxx::send(), Server::Server(), Application::server(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), ICPhaser::setPhase(), Phaser::setPhase(), A3PE::setPipeline(), FEB_v1::setProbeEnable(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), A3PE::setReadPatternFifoUsb(), A3PE::setReadTriggerFifoUsb(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), FEB_v1::setSpyModeFE(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), A3PE::setWriteStorageFifoUsb(), LSDelayChipV1::showConfig(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), ICECALv3::spiFERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server::start(), Processus::startProcessing(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Application::svcRunning(), Application::terminate(), FePGA::testSequence(), FEB_v1::threshold(), Hierarchy::tree(), SpecsParallelBus::update(), update(), NI6008::update(), Computer::update(), UsbSpiBus::update(), UsbI2cBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), UsbFTMLInterface::update(), FEB_v1::update(), CU_v1::update(), UsbFTInterface::update(), Proto40MHz_v1::update(), Croc::update(), UsbFTInterface::UsbFTInterface(), UsbFTMLInterface::UsbFTMLInterface(), ICECALv3::version(), UsbSpiBus::write(), FEB_v1::writeDataFifoInjectFE(), FEB_v1::writeFifoInjectFE(), and NI6008::~NI6008().
 m_log.msgSvc (MsgSvc::INFO , mymsg, m_name);
virtual StatusCode SpecsInterface::init () [inline, virtual]
init the component
Returns
void
Implements Interface.
Reimplemented in SpecsParallelBus, and SpecsSlave.
Definition at line 69 of file SpecsInterface.h.
References Object::info(), Object::name(), and StatusCode::SUCCESS.
Referenced by BOOST_PYTHON_MODULE().
                            
    info("SpecsInterface "+name()+" initialization.","SpecsInterface::init");
    return StatusCode::SUCCESS;
  ;
bool Attrib::is (int attribut) [inline, inherited]
Test for an attribut
Definition at line 50 of file Attrib.h.
References Attrib::m_attributs.
Referenced by export_obj(), and Element::setConnection().
  
    std::vector<int>::const_iterator iter ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        return true;
      
    
    return false;
  
void Object::msg (std::string mymsg, std::string name) [inline, inherited]
Definition at line 43 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::NONE.
 m_log.msgSvc (MsgSvc::NONE , mymsg, name);
void Object::msg (std::string mymsg) [inline, inherited]
Definition at line 35 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::NONE.
Referenced by export_obj().
 m_log.msgSvc (MsgSvc::NONE , mymsg, m_name);
void Object::msgSvc (int level, std::string msg, std::string name) [inline, inherited]
Definition at line 33 of file Object.h.
References Object::m_log, and MsgSvc::msgSvc().
Referenced by Application::banner(), export_obj(), SpecsMezzanine::help(), DCU::readMode(), DCU::setHIR(), DCU::setLIR(), and Hierarchy::tree().
 m_log.msgSvc ((MsgSvc::MsgLevel)(level), msg, name);
std::string Object::name () const [inline, inherited]
Definition at line 28 of file Object.h.
References Object::m_name.
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Hierarchy::child(), Hierarchy::childTyped(), Hierarchy::clear(), A3PE::clockDivision(), UsbFTMLInterface::close(), UsbFTInterface::close(), Element::connection(), SpecsSlave::detect(), IOdata::dump(), A3PE::enableStorage(), export_obj(), export_proc(), A3PE::fifoDepth(), A3PE::fifoLatency(), Register::getBit(), SpecsParallelBus::help(), help(), NI6008::help(), Computer::help(), UsbSpiBus::help(), UsbI2cBus::help(), RAM::help(), IOobject::help(), UsbMLSpiBus::help(), UsbMLI2cBus::help(), UsbFTMLInterface::help(), SeqPGA::help(), ICPhaser::help(), FePGA::help(), FEB_v1::help(), CU_v1::help(), UsbFTInterface::help(), Proto40MHz_v1::help(), A3PE::help(), Phaser::help(), Croc::help(), MSOxxxx::help(), LSDelayChipV1::help(), ICECALv3::help(), SpecsSlave::init(), SpecsMaster::init(), SpecsParallelBus::init(), init(), NI6008::init(), Computer::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), Croc::init(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), PhaserRampExec::initialize(), A3PE::latencyAX(), A3PE::lengthAX(), Application::network(), A3PE::nTrigger(), Processus::openRootFile(), Hierarchy::path(), Hierarchy::pathTyped(), A3PE::pipeline(), ICPhaser::read(), Phaser::read(), SpecsSlave::reset(), SpecsMaster::reset(), SpecsParallelBus::reset(), reset(), NI6008::reset(), Computer::reset(), UsbSpiBus::reset(), UsbI2cBus::reset(), UsbMLSpiBus::reset(), UsbMLI2cBus::reset(), UsbFTMLInterface::reset(), FEB_v1::reset(), CU_v1::reset(), UsbFTInterface::reset(), Proto40MHz_v1::reset(), A3PE::reset(), Croc::reset(), SpecsSlave::resetInternal(), FEB_v1::resetSpi(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), Register::setBit(), A3PE::setClockDivision(), Application::setConfig(), Element::setConnection(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), A3PE::setPipeline(), SpecsMaster::setSpeed(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsParallelBus::SpecsParallelBus(), Server::start(), Processus::startProcessing(), Processus::storage(), Application::terminate(), Hierarchy::tree(), A3PE::triggerDelay(), A3PE::triggerRate(), SpecsParallelBus::update(), update(), NI6008::update(), Computer::update(), UsbSpiBus::update(), UsbI2cBus::update(), UsbMLSpiBus::update(), UsbMLI2cBus::update(), UsbFTMLInterface::update(), FEB_v1::update(), CU_v1::update(), UsbFTInterface::update(), Proto40MHz_v1::update(), Croc::update(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), ICPhaser::write(), Phaser::write(), and Hierarchy::~Hierarchy().
 return m_name; //< Get Object m_name
unsigned long Hierarchy::numberOfChildren () [inherited]
Definition at line 125 of file Hierarchy.cpp.
References Hierarchy::m_children.
Referenced by export_obj().
                                           
  return m_children.size();
Hierarchy* Hierarchy::origin () [inline, inherited]
Definition at line 30 of file Hierarchy.h.
References Hierarchy::m_origin.
Referenced by Hierarchy::child(), export_obj(), and Hierarchy::setParent().
 return m_origin; //< Get the origin of the tree
unsigned char SpecsInterface::outputSelect ()
Definition at line 41 of file SpecsInterface.cpp.
References m_outputSelect.
Referenced by BOOST_PYTHON_MODULE(), specsReadI2c(), and specsWriteI2c().
                                           
    return m_outputSelect;
Hierarchy * Hierarchy::parent (std::string type) [inherited]
Definition at line 327 of file Hierarchy.cpp.
References Hierarchy::parent(), and Object::type().
                                            
  Hierarchy *parent = this->parent();
  if (0 != parent)
    if (parent->type().compare(type)==0)
      return parent;
    
    else
      return parent->parent(type);
  
  else
    return (Hierarchy*)NULL;
  
Hierarchy* Hierarchy::parent () [inline, inherited]
Definition at line 28 of file Hierarchy.h.
References Hierarchy::m_parent.
Referenced by Hierarchy::child(), Hierarchy::childTyped(), export_obj(), UsbSpiBus::init(), UsbI2cBus::init(), IOobject::init(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), Hierarchy::parent(), Hierarchy::path(), Hierarchy::pathTyped(), Element::setConnection(), Hierarchy::setParent(), specsMaster(), specsMasterDevice(), specsSlave(), specsSlaveDevice(), and Hierarchy::~Hierarchy().
 return m_parent; //< Get Hierarchy Parent
std::string Hierarchy::path (std::string str = std::string(``)) [inherited]
Definition at line 344 of file Hierarchy.cpp.
References Hierarchy::m_parent, Object::name(), Hierarchy::parent(), and Hierarchy::path().
Referenced by export_obj(), Hierarchy::path(), UsbFTMLInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTMLInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), and UsbFTMLInterface::usbWriteU8().
                                      
  str="/"+name()+str;
  Hierarchy *m_parent=parent();
  if (0!=m_parent)
    return m_parent->path(str);
  
  return str;
std::string Hierarchy::pathTyped (std::string str = std::string(``)) [inherited]
Definition at line 356 of file Hierarchy.cpp.
References Hierarchy::m_parent, Object::name(), Hierarchy::parent(), Hierarchy::pathTyped(), and Object::type().
Referenced by export_obj(), and Hierarchy::pathTyped().
                                           
  Hierarchy *m_parent=parent();
  if (0!=m_parent)
    str="/"+name()+"["+type()+"]"+str;
    return m_parent->pathTyped(str);
  
  return str;
virtual StatusCode SpecsInterface::read (IOdata * io) [inline, virtual]
Implements Interface.
Definition at line 124 of file SpecsInterface.h.
References StatusCode::SUCCESS.
 return StatusCode::SUCCESS; ;
void Element::recursiveInitCommunications () [inherited]
Triggers a recursive call to initCommunications() for the full hierarchy
Returns
void
Reimplemented in SpecsSlave.
Definition at line 44 of file Element.cpp.
References Hierarchy::children().
Referenced by export_obj().
                                         
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::const_iterator iter;
  for (iter=list.begin();iter!=list.end();iter++)
    dynamic_cast<Element*>((*iter))->recursiveInitCommunications();
  
void Element::recursiveInitElement () [inherited]
Triggers a recursive call to init() for the full hierarchy
Returns
void
Definition at line 32 of file Element.cpp.
References Hierarchy::children(), and Element::init().
Referenced by export_obj().
                                  
  init();
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter)
    dynamic_cast<Element*>((*iter))->recursiveInitElement();
  
void Attrib::remove (int attribut) [inline, inherited]
Remove an attribut
Definition at line 86 of file Attrib.h.
References Attrib::add(), Attrib::m_attributs, and Attrib::UNDEFINED.
Referenced by export_obj().
                               
    std::vector<int>::iterator iter , toremove ;
    for (iter = m_attributs.begin() ;
          iter != m_attributs.end() ;
          ++iter)
      if (attribut == (*iter))
        toremove = iter;
      
    
    m_attributs.erase (toremove);
    if(0==m_attributs.size()) add(Attrib::UNDEFINED);
  
virtual void SpecsInterface::reset () [inline, virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Interface.
Reimplemented in SpecsParallelBus, and SpecsSlave.
Definition at line 81 of file SpecsInterface.h.
References Object::info(), and Object::name().
Referenced by BOOST_PYTHON_MODULE().
 info("SpecsInterface "+name()+" reset.","SpecsInterface::reset");;
void SpecsInterface::setAddress (unsigned char address)
Reimplemented in SpecsSlave.
Definition at line 29 of file SpecsInterface.cpp.
References m_address.
Referenced by BOOST_PYTHON_MODULE().
                                                    
    m_address=address;
StatusCode Element::setConnection (Hierarchy * connection) [inherited]
Define IO interface
Definition at line 55 of file Element.cpp.
References Object::debug(), StatusCode::FAILURE, Object::fatal(), Attrib::INTERFACE, Attrib::is(), Element::m_connection, Object::name(), Hierarchy::parent(), StatusCode::SUCCESS, and Object::type().
Referenced by export_obj(), UsbSpiBus::init(), UsbI2cBus::init(), IOobject::init(), UsbMLSpiBus::init(), and UsbMLI2cBus::init().
                                                      
  if (0==connection)
    fatal("Try to define a connection with a null pointer.",
        "Element::setConnection");
    return StatusCode::FAILURE;
  
  if (connection->is(Attrib::INTERFACE))
    m_connection=dynamic_cast<Hierarchy*>(connection);
    return StatusCode::SUCCESS;
  
  else
    debug(connection->name()+
        " is not a Attrib::INTERFACE hardware. Connection refused.",
        "Element::setConnection");
    if (0!=connection->parent())
      return setConnection(connection->parent());
    
    else
      fatal("Could not find a connection for element "+
          name()+"["+type()+"].","element::setConnection");
      return StatusCode::FAILURE;
    
  
void Object::setDllName (std::string dllName) [inline, inherited]
Set accessor to member m_dllName
Parameters
dllName the new value for m_dllName
Definition at line 66 of file Object.h.
References Object::m_dllName.
Referenced by DLL::createElement(), DLL::createProcessus(), and Object::Object().
                                      
    m_dllName = dllName;
  
void Object::setId (unsigned char id) [inline, inherited]
Definition at line 53 of file Object.h.
References Object::m_id.
Referenced by A3PE::A3PE(), DCU::DCU(), export_obj(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), Object::Object(), Phaser::Phaser(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsI2c::SpecsI2c(), SpecsInterface(), SpecsMaster::SpecsMaster(), SpecsParallelBus::SpecsParallelBus(), and SpecsSlave::SpecsSlave().
 m_id = id ; //< Set Object m_id
void Object::setName (std::string name) [inline, inherited]
Definition at line 51 of file Object.h.
References Object::m_name.
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Application::create(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), FePGA::MakeRAM(), FePGA::MakeRegister(), Application::network(), NI6008::NI6008(), Object::Object(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
 m_name = name ; //< Set Object m_name
void SpecsInterface::setOutputSelect (unsigned char outputSelect)
Definition at line 37 of file SpecsInterface.cpp.
References m_outputSelect.
Referenced by BOOST_PYTHON_MODULE().
                                                              
    m_outputSelect=outputSelect;
void Hierarchy::setParent (Hierarchy * parent) [inherited]
Definition at line 67 of file Hierarchy.cpp.
References Hierarchy::m_origin, Hierarchy::m_parent, Hierarchy::origin(), and Hierarchy::parent().
Referenced by SpecsMezzanine::addBus(), Hierarchy::addChild(), SpecsSlave::addI2c(), Computer::Computer(), Application::create(), export_obj(), and SpecsMezzanine::SpecsMezzanine().
                                              
  m_parent = parent;
  if ((Hierarchy*)0==parent) return;
  Hierarchy *curr = this;
  Hierarchy *prev = parent;
  while (prev != 0)
    curr = prev;
    prev = curr->parent();
  
  if (parent->origin()!=0) m_origin=parent->origin();
void Object::setTitle (std::string title) [inline, inherited]
Definition at line 54 of file Object.h.
References Object::m_title.
Referenced by A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), CurrentMeasurement::CurrentMeasurement(), EmulateFE::EmulateFE(), export_obj(), Histo1D::Histo1D(), Histo2D::Histo2D(), Object::Object(), PhaserRampExec::PhaserRampExec(), RegisterTest::RegisterTest(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), and UsbFTInterfaceTest::UsbFTInterfaceTest().
 m_title = title ; //< Set Object m_title
void Object::setType (std::string type) [inline, inherited]
Definition at line 52 of file Object.h.
References Object::m_type.
Referenced by A3PE::A3PE(), A3PE_BitFlip::A3PE_BitFlip(), Acquisition::Acquisition(), ADCMeasurement::ADCMeasurement(), Computer::Computer(), Croc::Croc(), CU_v1::CU_v1(), CurrentMeasurement::CurrentMeasurement(), DCU::DCU(), EmulateFE::EmulateFE(), export_obj(), FEB_v1::FEB_v1(), FePGA::FePGA(), ICECALv3::ICECALv3(), ICPhaser::ICPhaser(), Application::initialize(), Interface::Interface(), IOdata::IOdata(), IOobject::IOobject(), LSDelayChipV1::LSDelayChipV1(), MSOxxxx::MSOxxxx(), NI6008::NI6008(), Object::Object(), Phaser::Phaser(), PhaserRampExec::PhaserRampExec(), Proto40MHz_v1::Proto40MHz_v1(), RAM::RAM(), Register::Register(), RegisterTest::RegisterTest(), SeqPGA::SeqPGA(), SpecsBus::SpecsBus(), SpecsGlue::SpecsGlue(), SpecsI2c::SpecsI2c(), SpecsMaster::SpecsMaster(), SpecsMezzanine::SpecsMezzanine(), SpecsParallelBus::SpecsParallelBus(), SpecsSlave::SpecsSlave(), StorageFifo::StorageFifo(), StorageFifoAcquisition::StorageFifoAcquisition(), TestI2C::TestI2C(), TestSPI::TestSPI(), TestSuite::TestSuite(), TestUSB::TestUSB(), UsbFTInterface::UsbFTInterface(), UsbFTInterfaceTest::UsbFTInterfaceTest(), UsbFTMLInterface::UsbFTMLInterface(), UsbI2cBus::UsbI2cBus(), UsbMLI2cBus::UsbMLI2cBus(), UsbMLSpiBus::UsbMLSpiBus(), and UsbSpiBus::UsbSpiBus().
 m_type = type ; //< Set Object m_type
SpecsMaster * SpecsInterface::specsMaster () [virtual]
Get the closest master in the element hierarchy
Returns
SpecsMaster
Definition at line 57 of file SpecsInterface.cpp.
References Hierarchy::parent(), and specsMaster().
Referenced by BOOST_PYTHON_MODULE(), SpecsSlave::detect(), and specsMaster().
                                        
    if (0!=parent())
    SpecsInterface* tmp = dynamic_cast <SpecsInterface*> (parent());
    if (0 != tmp) return tmp->specsMaster();
  
  return (SpecsMaster*)NULL;
SPECSMASTER * SpecsInterface::specsMasterDevice () [virtual]
Get the closest master in the element hierarchy
Returns
SPECSMASTER*
Definition at line 76 of file SpecsInterface.cpp.
References Hierarchy::parent(), and specsMasterDevice().
Referenced by SpecsSlave::detect(), SpecsSlave::init(), and specsMasterDevice().
                                              
    if (0!=parent())
    SpecsInterface* tmp = dynamic_cast <SpecsInterface*> (parent());
    if (0 != tmp) return tmp->specsMasterDevice();
    
  return (SPECSMASTER*)NULL;
bool SpecsInterface::specsReadI2c (unsigned char address, unsigned char outputSel, unsigned char subAddress, unsigned char nOctets, U8 * i2cWords)
Read nOctets from i2c slave address at subAddress. specsWords contains nSpecsWords containing the i2c data.
Returns
bool
Parameters
$\leftarrow$ address i2c Slave address
$\leftarrow$ outputSel i2c Slave output select
$\leftarrow$ nOctect number of octets to read
$\leftarrow$ nSpecsWords number of specs words to retrieve
$\rightarrow$ specsWords contains the specs words with the i2c data
Definition at line 263 of file SpecsInterface.cpp.
References itos(), specsSlaveDevice(), Object::verbose(), and Object::warning().
                                             
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper Specs Master and/or Slave.",
            "SpecsInterface::specsReadI2c");
    return false;
  
  SpecsError status = specs_i2c_read_sub (specsSlv, outputSel ,
                                           i2cAdd , subAdd ,
                                           nOctets , i2cWords);
  if (0!=status)
    warning("failure at address " + itos (i2cAdd) + "/ subAddress " + itos(subAdd
      ) +
            " [code=" + itos(status) + "]",
            "specsReadI2c");
    // specsMaster() -> reset();
  
  else
    verbose(itos(nOctets) + " words read at address " + itos(i2cAdd) +
            "/ subAddress " + itos(subAdd),
            "SpecsReadI2c");
  
#else
  verbose("Compilation in _NODEVICE_ mode.","SpecsInterface::specsReadI2c");
#endif
  return true;
bool SpecsInterface::specsReadI2c (unsigned char address, unsigned char subAddress, unsigned char nOctets, U8 * i2cWords)
Read nOctets from i2c slave address at subAddress. specsWords contains nSpecsWords containing the i2c data.
Returns
bool
Parameters
$\leftarrow$ address i2c Slave address
$\leftarrow$ nOctect number of octets to read
$\leftarrow$ nSpecsWords number of specs words to retrieve
$\rightarrow$ specsWords contains the specs words with the i2c data
Definition at line 235 of file SpecsInterface.cpp.
References itos(), outputSelect(), specsSlaveDevice(), Object::verbose(), and Object::warning().
                                             
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper Specs Master and/or Slave.","SpecsInterface::
      specsReadI2c");
    return false;
  
  SpecsError status = specs_i2c_read_sub (specsSlv, outputSelect() , i2cAdd , su
      bAdd , nOctets , i2cWords);
  if (0!=status)
    warning("failure at address " + itos (i2cAdd) + "/ subAddress " + itos(subAdd
      ) +
            " [code=" + itos(status) + "]" ,
            "specsReadI2c");
    // specsMaster() -> reset();
  
  else
    verbose(itos(nOctets) + " words read at address " + itos(i2cAdd) +
            "/ subAddress " + itos(subAdd),
            "SpecsReadI2c");
  
#else
  verbose("Compilation in _NODEVICE_ mode.","SpecsInterface::specsReadI2c");
#endif
  return true;
bool SpecsInterface::specsReadI2c (unsigned char address, std::vector< unsigned char > & specsWords)
Read a vector of given size from i2c slave address.
Returns
bool (false if vector of size 0 or reading error)
Parameters
$\leftarrow$ address i2c Slave address
$\rightarrow$ specsWords contains the specs words with the i2c data
Definition at line 216 of file SpecsInterface.cpp.
References specsReadI2c(), and Object::warning().
                                                                       
  int nOctets = specsWords.size();
  if(nOctets==0)
    warning("The vector of data to read should have a non-zero size",
            "SpecsInterface::specsReadI2c");
    return false;
  
  U8 BufferSource[50];
 
  bool status = specsReadI2c(address, nOctets, BufferSource);
  for(int j=0; j<nOctets; ++j) specsWords[j] = static_cast<unsigned char>(BufferS
      ource[j]);
  return status;
bool SpecsInterface::specsReadI2c (unsigned char address, unsigned char nOctects, U8 * i2cWords)
Read nOctets from i2c slave address. specsWords contains nSpecsWords containing the i2c data.
Returns
bool
Parameters
$\leftarrow$ address i2c Slave address
$\leftarrow$ nOctect number of octets to read
$\leftarrow$ nSpecsWords number of specs words to retrieve
$\rightarrow$ specsWords contains the specs words with the i2c data
Definition at line 191 of file SpecsInterface.cpp.
References itos(), outputSelect(), specsSlaveDevice(), Object::verbose(), and Object::warning().
Referenced by SpecsMezzanine::cmdline(), and specsReadI2c().
                                              
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper Specs Master and/or Slave.",
            "SpecsInterface::specsReadI2c");
    return false;
  
  SpecsError status = specs_i2c_read (specsSlv, outputSelect() , i2cAdd , nOctet
      s , i2cWords);
  if (0!=status)
    warning("failure at address " + itos (i2cAdd) + "[code=" + itos(status) + "]"
      ,
            "specsReadI2c");
    // specsMaster() -> reset();
  
  else
    verbose(itos(nOctets) + " words read at address " + itos(i2cAdd),"SpecsReadI2
      c");
  
#else
  verbose("Compilation in _NODEVICE_ mode.","SpecsInterface::specsReadI2c");
#endif
  return true;
bool SpecsInterface::specsReadParallel (unsigned char address, U16 & data)
Read data at address on parallel bus
Returns
bool
Parameters
$\leftarrow$ address address bus
$\leftarrow$ data data bus
Definition at line 323 of file SpecsInterface.cpp.
References itos(), specsSlaveDevice(), Object::verbose(), and Object::warning().
                                                      
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper SpecsSlave/Master.","SpecsInterface::specsRea
      dI2c");
    return false;
  
  SpecsError status = specs_parallel_read(specsSlv , add , 1 , &parallelBus);
  if (0!=status)
    warning("failure at address " + itos (add) +
            " [code=" + itos(status) + "]",
            "specsReadParallel");
    // specsMaster() -> reset();
  
  else
    verbose("Word " + itos(parallelBus) +
            " successfully read at address " + itos(add),
            "SpecsReadParallel");
  
#else
  verbose("Compilation in _NODEVICE_ mode.",
          "SpecsReadParallel");
#endif
  return true;
bool SpecsInterface::specsReadRegister (unsigned char reg, U16 & value)
Read Register data
Returns
bool
Parameters
$\leftarrow$ register register number
$\leftarrow$ data data
Definition at line 383 of file SpecsInterface.cpp.
References itos(), specsSlaveDevice(), Object::verbose(), and Object::warning().
Referenced by SpecsMezzanine::cmdline(), SpecsMezzanine::date(), SpecsGlue::date(), SpecsGlue::i2cClkMode(), SpecsMezzanine::led(), SpecsGlue::led(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), and SpecsGlue::setLed().
                                                 
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper SpecsSlave/Master.",
            "SpecsInterface::specsReadRegister");
    return false;
  
  
  SpecsError status ;
  status = specs_register_read (specsSlv , reg , &value);
  if (0!=status)
    warning("failure at register " + itos (reg) +
            " [code=" + itos(status) + "]" ,
            "specsReadRegister");
    // specsMaster() -> reset();
    return false;
  
  else
    verbose("register " + itos(reg) +
            " successfully read with value " + itos(value),
            "SpecsReadRegister");
  
#else
  verbose("Compilation in _NODEVICE_ mode.",
          "SpecsInterface::specsReadRegister");
#endif
  return true;
SpecsSlave * SpecsInterface::specsSlave () [virtual]
Get the closest slave in the element hierarchy
Returns
SpecsSlave
Definition at line 49 of file SpecsInterface.cpp.
References Hierarchy::parent(), and specsSlave().
Referenced by BOOST_PYTHON_MODULE(), SpecsSlave::detect(), SpecsSlave::init(), SpecsSlave::setAddress(), specsSlave(), and SpecsSlave::specsSlaveDevice().
                                      
    if (0!=parent())
    SpecsInterface* tmp = dynamic_cast <SpecsInterface*> (parent());
    if (0 != tmp) return tmp->specsSlave();
  
  return (SpecsSlave*)NULL;
SPECSSLAVE * SpecsInterface::specsSlaveDevice () [virtual]
Get the closest slave in the element hierarchy
Returns
SPECSSLAVE*
Reimplemented in SpecsSlave.
Definition at line 66 of file SpecsInterface.cpp.
References Hierarchy::parent(), and specsSlaveDevice().
Referenced by specsReadI2c(), specsReadParallel(), specsReadRegister(), specsSlaveDevice(), specsWriteI2c(), specsWriteParallel(), and specsWriteRegister().
                                            
    if (0!=parent())
    SpecsInterface* tmp = dynamic_cast <SpecsInterface*> (parent());
    if (0 != tmp) return tmp->specsSlaveDevice();
    
  return (SPECSSLAVE*)NULL;
bool SpecsInterface::specsWriteI2c (unsigned char address, unsigned char outputSel, unsigned char subAddress, unsigned char nData, U8 * data)
Write nData stored in data to i2c slave address at subAddress
Returns
bool
Parameters
$\leftarrow$ address i2c Slave address
$\leftarrow$ outputSel i2c Slave output select
$\leftarrow$ nData number of octets to send
$\leftarrow$ data contains the data to send
Definition at line 159 of file SpecsInterface.cpp.
References itos(), specsSlaveDevice(), Object::verbose(), and Object::warning().
                                            
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper Specs Master and/or Slave.",
            "SpecsInterface::specsWriteI2c");
    return false;
  
  SpecsError status = specs_i2c_write_sub (specsSlv, outputSel ,
                                            i2cAdd , subAdd ,
                                            nWord , data);
  if (0!=status)
    warning("failure at address " + itos (i2cAdd) + "/ subAddress " + itos(subAdd
      ) +
            " [code=" + itos(status) + "]" ,
            "specsWriteI2c");
    // specsMaster() -> reset();
  
  else
    verbose(itos(nWord) + " words written at address " + itos(i2cAdd) +
            "/ subAddress " + itos(subAdd),
            "SpecsWriteI2c");
  
#else
  verbose("Compilation in _NODEVICE_ mode.","SpecsInterface::specsWriteI2c");
#endif
  return true;
bool SpecsInterface::specsWriteI2c (unsigned char address, unsigned char subAddress, unsigned char nData, U8 * data)
Write nData stored in data to i2c slave address at subAddress
Returns
bool
Parameters
$\leftarrow$ address i2c Slave address
$\leftarrow$ nData number of octets to send
$\leftarrow$ data contains the data to send
Definition at line 129 of file SpecsInterface.cpp.
References itos(), outputSelect(), specsSlaveDevice(), Object::verbose(), and Object::warning().
                                            
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper Specs Master and/or Slave.","SpecsInterface::
      specsWriteI2c");
    return false;
  
  SpecsError status = specs_i2c_write_sub (specsSlv, outputSelect() , i2cAdd , s
      ubAdd , nWord , data);
  if (0!=status)
    warning("failure at address " + itos (i2cAdd) + "/ subAddress " + itos(subAdd
      ) +
            " [code=" + itos(status) + "]","specsWriteI2c");
    // specsMaster() -> reset();
  
  else
    verbose(itos(nWord) +
            " words written at address " +
            itos(i2cAdd) +
            "/ subAddress " +
            itos(subAdd),
            "SpecsWriteI2c");
  
#else
  verbose("Compilation in _NODEVICE_ mode.","SpecsInterface::specsWriteI2c");
#endif
  return true;
bool SpecsInterface::specsWriteI2c (unsigned char address, std::vector< U8 > data)
Write data to i2c slave address
Returns
bool
Parameters
$\leftarrow$ address i2c Slave address
$\leftarrow$ data contains the data to send
Definition at line 111 of file SpecsInterface.cpp.
References specsWriteI2c(), and Object::warning().
                                                      
  unsigned char nword = static_cast<unsigned int>(data.size());
  if (nword == 0)
    warning("Request to write data of size 0","SpecsInterface::specsWriteI2c");
    return false;
  
  unsigned char* new_data = new unsigned char[nword];
  for(unsigned int i=0; i<data.size(); ++i) new_data[i] = data[i];
 
  bool status = specsWriteI2c(address, nword, new_data);
  delete [] new_data;
  return status;
  return true;
bool SpecsInterface::specsWriteI2c (unsigned char address, unsigned char nData, U8 * data)
Write nData stored in data to i2c slave address
Returns
bool
Parameters
$\leftarrow$ address i2c Slave address
$\leftarrow$ nData number of octets to send
$\leftarrow$ data contains the data to send
Definition at line 85 of file SpecsInterface.cpp.
References itos(), outputSelect(), specsSlaveDevice(), Object::verbose(), and Object::warning().
Referenced by SpecsMezzanine::cmdline(), and specsWriteI2c().
                                          
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper Specs Master and/or Slave.","SpecsInterface::
      specsWriteI2c");
    return false;
  
  SpecsError status = specs_i2c_write (specsSlv, outputSelect() , i2cAdd , nWord
       , data);
  if (0!=status)
    warning("failure at address " + itos (i2cAdd) + "[code=" + itos(status) + "]"
       ,
            "specsWriteI2c");
    // specsMaster() -> reset();
  
  else
    verbose(itos(nWord) + " words written at address " + itos(i2cAdd),
            "SpecsWriteI2c");
  
#else
  verbose("Compilation in _NODEVICE_ mode.","SpecsInterface::specsWriteI2c");
#endif
  return true;
bool SpecsInterface::specsWriteParallel (unsigned char address, unsigned short data)
Write address / data on parallel bus
Returns
bool
Parameters
$\leftarrow$ address address bus
$\leftarrow$ data data bus
Definition at line 295 of file SpecsInterface.cpp.
References itos(), specsSlaveDevice(), Object::verbose(), and Object::warning().
                                                
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper Specs Master and/or Slave.",
            "SpecsInterface::specsWriteParallel");
    return false;
  
  SpecsError status = specs_parallel_write(specsSlv , add , 1 , &value);
  if (0!=status)
    warning("failure at address " + itos (add) +
            " [code=" + itos(status) + "]" ,
            "specsWriteParallel");
    // specsMaster() -> reset();
  
  else
    verbose("Word " + itos(value) +
            " successfully written at address " + itos(add),
            "SpecsWriteParallel");
  
#else
  verbose("Compilation in _NODEVICE_ mode.",
          "SpecsWriteParallel");
#endif
  return true;
bool SpecsInterface::specsWriteRegister (unsigned char reg, unsigned short value)
Write Register data
Returns
bool
Parameters
$\leftarrow$ register register number
$\leftarrow$ data data bus
Definition at line 351 of file SpecsInterface.cpp.
References itos(), specsSlaveDevice(), Object::verbose(), and Object::warning().
Referenced by SpecsMezzanine::cmdline(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), and SpecsGlue::setLed().
                                                           
#ifndef _NODEVICE_
  SPECSSLAVE *specsSlv=specsSlaveDevice();
  if (0==specsSlv)
    warning("Could not reach proper SpecsSlave/Master.",
            "SpecsInterface::specsWriteRegister");
    return false;
  
  
  SpecsError status ;
  status = specs_register_write (specsSlv , reg , value);
  if (0 != status)
    warning("failure at register " + itos (reg) +
            " [code=" + itos(status) + "]" ,
            "specsWriteRegister");
    // specsMaster() -> reset();
    return false;
  
  else
    verbose("register " + itos(reg) +
            " successfully written with value " + itos (value),
            "SpecsWriteRegister");
  
#else
  verbose("Compilation in _NODEVICE_ mode.",
          "SpecsInterface::specsWriteRegister");
#endif
  return true;
std::string Object::title () [inline, inherited]
Definition at line 31 of file Object.h.
References Object::m_title.
Referenced by export_obj(), export_proc(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), StorageFifoAcquisition::initialize(), Acquisition::initialize(), and Application::terminate().
 return m_title; // < Get Object m_title
void Hierarchy::tree () [inline, inherited]
Definition at line 46 of file Hierarchy.h.
References Hierarchy::tree().
Referenced by export_obj(), and Hierarchy::tree().
 tree(""); ; // output tree of Hierarchy from object
void Hierarchy::tree (std::string indent = std::string(``)) [inherited]
Definition at line 310 of file Hierarchy.cpp.
References Hierarchy::children(), Object::info(), Object::msgSvc(), Object::name(), MsgSvc::NONE, and Object::type().
                                    
  std::string line=indent+" -> "+name()+"["+type()+"] ";
  if (std::string("")==indent)
    info("Hierarchy for Object "+name()+"["+type()+"]","Hierarchy::tree");
  
  msgSvc(MsgSvc::NONE,line,"");
  std::vector<Hierarchy*> list = children();
  std::vector<Hierarchy*>::iterator iter;
  for (iter=list.begin() ; iter!=list.end() ; ++iter)
    std::string tab=" ";
    (*iter)->tree(indent+tab);
  
std::string Object::type () [inline, inherited]
Definition at line 29 of file Object.h.
References Object::m_type.
Referenced by DLLMgr::destroy(), DLL::destroy(), IOdata::dump(), export_obj(), UsbSpiBus::init(), UsbI2cBus::init(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), PhaserRampExec::initialize(), ProcDataBase::list(), Hierarchy::parent(), Hierarchy::pathTyped(), DLL::print(), ProcDataBase::procList(), Application::setConfig(), Element::setConnection(), and Hierarchy::tree().
 return m_type; //< Get Object m_type
virtual void SpecsInterface::update () [inline, virtual]
Update the Element configuration from the actual hardware
Implements Interface.
Reimplemented in SpecsParallelBus.
Definition at line 86 of file SpecsInterface.h.
References Object::info(), and Object::name().
Referenced by BOOST_PYTHON_MODULE().
info("SpecsInterface "+name()+". Nothing to do.","SpecsInterface::update");;
void Object::verbose (std::string mymsg, std::string name) [inline, inherited]
Definition at line 44 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
 m_log.msgSvc (MsgSvc::VERBOSE , mymsg, name);
void Object::verbose (std::string mymsg) [inline, inherited]
Definition at line 36 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::VERBOSE.
Referenced by DCU::acquire(), export_obj(), DCU::init(), Application::prepare(), UsbFTMLInterface::read(), UsbFTInterface::read(), DCU::readMode(), DCU::reset(), DCU::setHIR(), DCU::setLIR(), specsReadI2c(), specsReadParallel(), specsReadRegister(), specsWriteI2c(), specsWriteParallel(), specsWriteRegister(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), wait(), UsbFTMLInterface::write(), and UsbFTInterface::write().
 m_log.msgSvc (MsgSvc::VERBOSE , mymsg, m_name);
void Object::warning (std::string mymsg, std::string name) [inline, inherited]
Definition at line 47 of file Object.h.
References Object::m_log, MsgSvc::msgSvc(), and MsgSvc::WARNING.
 m_log.msgSvc (MsgSvc::WARNING , mymsg, name);
void Object::warning (std::string mymsg) [inline, inherited]
Definition at line 39 of file Object.h.
References Object::m_log, Object::m_name, MsgSvc::msgSvc(), and MsgSvc::WARNING.
Referenced by DCU::acquire(), A3PE::acquisition(), Plot::add(), Application::bookkeeping(), checkCmd(), Hierarchy::child(), Hierarchy::childTyped(), Processus::clean(), UsbSpiBus::clockDivider(), LSDelayChipV1::configRegBulkRead(), LSDelayChipV1::configRegBulkWrite(), Element::connection(), DCU::convert(), Application::create(), SpecsMezzanine::date(), SpecsGlue::date(), SpecsSlave::detect(), NI6008::device(), UsbFTInterfaceTest::execute(), Acquisition::execute(), A3PE_BitFlip::execute(), export_obj(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtClockStrength(), FEB_v1::gbtDLLReset(), LSDelayChipV1::getConfigReg(), SpecsGlue::i2cClkMode(), SpecsSlave::init(), DCU::init(), TestUSB::initialize(), TestSPI::initialize(), TestI2C::initialize(), EmulateFE::initialize(), StorageFifoAcquisition::initialize(), StorageFifo::initialize(), Acquisition::initialize(), A3PE_BitFlip::initialize(), SpecsMezzanine::led(), SpecsGlue::led(), A3PE::loadTrigger(), Application::loop(), Application::makeDir(), Data::name(), Application::prepare(), UsbSpiBus::read(), UsbI2cBus::read(), ICPhaser::read(), Phaser::read(), DCU::readMode(), SpecsSlave::reset(), SpecsMaster::reset(), DCU::reset(), ICPhaser::reset(), SpecsSlave::resetInternal(), Server::Server(), FEB_v1::setCalibCte(), StorageFifoAcquisition::setChannels(), Acquisition::setChannels(), UsbSpiBus::setClockDivider(), FEB_v1::setClockFallingEdge(), Application::setConfig(), LSDelayChipV1::setConfigReg(), StorageFifoAcquisition::setDepth(), Acquisition::setDepth(), A3PE::setEnableADC(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), DCU::setHIR(), SpecsGlue::setI2cClkMode(), SpecsMezzanine::setLed(), DCU::setLIR(), FEB_v1::setOutputEport(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), SpecsMaster::setSpeed(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), TestSuite::sigma(), specsReadI2c(), specsReadParallel(), specsReadRegister(), specsWriteI2c(), specsWriteParallel(), specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), ICECALv3::spiFERTest(), ICECALv3::spiRead(), ICECALv3::spiWrite(), ICECALv3::spiWriteSafe(), Server::start(), ICPhaser::status(), Application::svcPlot(), Application::svcRunning(), Data::title(), Server::updateConfig(), Server::updateState(), Data::vectorPtr(), UsbSpiBus::write(), UsbI2cBus::write(), ICPhaser::write(), Phaser::write(), FEB_v1::writeFifoInjectFE(), and FEB_v1::writeFifoLLTFE().
 m_log.msgSvc (MsgSvc::WARNING , mymsg, m_name);
virtual StatusCode SpecsInterface::write (IOdata * io) [inline, virtual]
Implements Interface.
Definition at line 125 of file SpecsInterface.h.
References StatusCode::SUCCESS.
 return StatusCode::SUCCESS; ;
Member Data Documentation
unsigned char SpecsInterface::m_address [protected]
Definition at line 268 of file SpecsInterface.h.
Referenced by address(), SpecsSlave::setAddress(), setAddress(), and SpecsInterface().
std::string Attrib::m_attribString[10] [protected, inherited]
Definition at line 105 of file Attrib.h.
Referenced by Attrib::Attrib(), and Attrib::attributs().
Hierarchy* Element::m_connection [protected, inherited]
Definition at line 70 of file Element.h.
Referenced by UsbSpiBus::clockDivider(), Element::connection(), Element::Element(), UsbSpiBus::init(), UsbI2cBus::init(), IOobject::init(), UsbMLSpiBus::init(), UsbMLI2cBus::init(), UsbSpiBus::read(), UsbI2cBus::read(), UsbSpiBus::setClockDivider(), Element::setConnection(), UsbSpiBus::write(), and UsbI2cBus::write().
unsigned char SpecsInterface::m_outputSelect [protected]
Definition at line 269 of file SpecsInterface.h.
Referenced by outputSelect(), setOutputSelect(), and SpecsInterface().
int SpecsInterface::m_slot [private]
Definition at line 266 of file SpecsInterface.h.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/inc/SpecsInterface.h
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/src/SpecsInterface.cpp