MsgSvc Class Reference
#include <inc/MsgSvc.h>
Public Types
enum MsgLevel {
VERBOSE =-6,
DEBUG,
INFO,
WARNING,
ERR,
FATAL,
NONE
 }
enum MsgColor {
BLUE,
GREEN,
WHITE,
MAGENTA,
YELLOW,
RED,
CYAN
 }
Public Member Functions
MsgSvc ()
Standard constructor.
virtual ~MsgSvc ()
Destructor.
void msgSvc (MsgSvc::MsgLevel, std::string, std::string call=std::string(``))
void setLineLength (int linelength)
void setCallSize (int callSize)
Protected Member Functions
void log (MsgSvc::MsgLevel, std::string, std::string)
Private Member Functions
std::string logtime ()
Private Attributes
std::vector< std::string > colors
int m_callSize
int m_lineLength
std::string m_origin
Detailed Description
Author
Frederic Machefert
Date
2009-12-30
Definition at line 21 of file MsgSvc.h.
Member Enumeration Documentation
MsgColor
enum MsgSvc::MsgColor
Enumerator
BLUE
GREEN
WHITE
MAGENTA
YELLOW
RED
CYAN
Definition at line 25 of file MsgSvc.h.
{BLUE, GREEN, WHITE, MAGENTA, YELLOW, RED, CYAN};
MsgLevel
enum MsgSvc::MsgLevel
Enumerator
VERBOSE
DEBUG
INFO
WARNING
ERR
FATAL
NONE
Definition at line 24 of file MsgSvc.h.
{VERBOSE=-6, DEBUG, INFO, WARNING, ERR, FATAL,
      NONE};
Constructor & Destructor Documentation
MsgSvc()
MsgSvc::MsgSvc ()
Standard constructor.
Definition at line 19 of file MsgSvc.cpp.
References colors.
                 :
  m_callSize (18),
  m_lineLength (200){
  colors.push_back(std::string("\033[94m"));
  colors.push_back(std::string("\033[92m"));
  colors.push_back(std::string("\033[93m"));
  colors.push_back(std::string("\033[95m"));
// colors.push_back(std::string("\033[47m \033[7m \033[45m"));
  colors.push_back(std::string("\033[33m"));
  colors.push_back(std::string("\033[91m"));
// colors.push_back(std::string("\033[41m"));
  colors.push_back(std::string("\033[0m"));
}
 MsgSvc()
MsgSvc::~MsgSvc () [virtual]
Destructor.
Definition at line 36 of file MsgSvc.cpp.
                {
}
Member Function Documentation
log()
void MsgSvc::log (MsgSvc::MsgLevel level, std::string msg, std::string call) [protected]
Definition at line 69 of file MsgSvc.cpp.
References application(), BLUE, colors, CYAN, DEBUG, ERR, FATAL, GREEN, INFO, logtime(), m_callSize, MAGENTA, RED, VERBOSE, WARNING, WHITE, and YELLOW.
Referenced by msgSvc(), and setCallSize().
                                  {
  bool isFatal=false;
  
  //#ifndef WIN32
  std::string output(colors[BLUE]);
  output+=std::string(call,0,m_callSize);
  //#else
  // std::string output=std::string(call,0,m_callSize);
  //#endif
  int clen=call.length();
  if (clen>0)
  {
    if (clen>m_callSize) output.replace(m_callSize+5-3,3,"...");
    if (clen<m_callSize) output.insert (clen+5,m_callSize-clen,' ');
  }
  
  std::string color;
  
  switch(level) {
  case VERBOSE:
#ifndef WIN32
    color=colors[BLUE];
    output+=color;
#endif
    output+=" VERBOSE ";
    break;
  case DEBUG:
#ifndef WIN32
    color=colors[BLUE];
    output+=color;
#endif
    output+=" DEBUG ";
    break;
  case INFO:
#ifndef WIN32
    color=colors[GREEN];
    output+=color;
#endif
    output+=" INFO ";
    break;
  case WARNING:
#ifndef WIN32
    color=colors[YELLOW];
    output+=color;
#endif
    output+=" WARNING ";
    break;
  case ERR:
#ifndef WIN32
    color=colors[MAGENTA];
    output+=color;
#endif
    output+=" ERROR ";
    break;
  case FATAL:
#ifndef WIN32
    color=colors[RED];
    output+=color;
#endif
    output+=" FATAL ";
    isFatal=true;
    break;
  default:
#ifndef WIN32
    color = colors[CYAN];
    output+=color;
#endif
    output = call;
    break;
  }
#ifndef WIN32
  output+=colors[WHITE];
#endif
  output+=logtime();
#ifndef WIN32
  output+=color;
#endif
  output+=msg;
#ifndef WIN32
  output+=colors[WHITE];
#endif
  /*
    int linereturn=output.length();
    while (linereturn>m_lineLength){
    output.insert(m_lineLength,"\n");
    output.insert(m_lineLength+1,9+m_callSize,' ');
    linereturn-=m_lineLength;
    }
  */
  
  std::cout << output << std::endl;
  (*application() -> options() -> stream ()) << output << std::endl; ;
  if (isFatal) {exit(0);}
}
logtime()
std::string MsgSvc::logtime () [private]
Definition at line 54 of file MsgSvc.cpp.
Referenced by log().
                         {
  time_t rawtime;
  struct tm * timeinfo;
  
  time (&rawtime);
  timeinfo = localtime (&rawtime);
  char* timechar = asctime (timeinfo) ;
  std::string timing = std::string(timechar,24) + " ";
  return timing;
}
msgSvc()
void MsgSvc::msgSvc (MsgSvc::MsgLevel level, std::string msg, std::string call = std::string(``))
Definition at line 42 of file MsgSvc.cpp.
References application(), log(), and Application::options().
Referenced by Object::debug(), var::debug(), DLLMgr::debug(), DLL::debug(), Object::error(), export_base(), Object::fatal(), var::fatal(), DLLMgr::fatal(), DLL::fatal(), Object::info(), var::info(), DLLMgr::info(), DLL::info(), Object::msg(), DLL::msg(), Object::msgSvc(), Options::print(), Object::verbose(), var::verbose(), DLLMgr::verbose(), DLL::verbose(), Object::warning(), var::warning(), DLLMgr::warning(), and DLL::warning().
                                     {
  Options *opt = application() ->options() ;
  const int OUTLEVEL = opt -> logOutputLevel();
  if (level<OUTLEVEL) return;
  log (level, msg, call);
}
setCallSize()
void MsgSvc::setCallSize (int callSize) [inline]
Definition at line 33 of file MsgSvc.h.
References log(), and m_callSize.
Referenced by export_base().
{ m_callSize = callSize ; } //< Set Msg call field size
setLineLength()
void MsgSvc::setLineLength (int linelength) [inline]
Definition at line 32 of file MsgSvc.h.
References m_lineLength.
Referenced by export_base().
{ m_lineLength = linelength ; } //< Set Msg line length
Member Data Documentation
colors
std::vector<std::string> MsgSvc::colors [private]
Definition at line 40 of file MsgSvc.h.
Referenced by log(), and MsgSvc().
m_callSize
int MsgSvc::m_callSize [private]
Definition at line 41 of file MsgSvc.h.
Referenced by log(), and setCallSize().
m_lineLength
int MsgSvc::m_lineLength [private]
Definition at line 42 of file MsgSvc.h.
Referenced by setLineLength().
m_origin
std::string MsgSvc::m_origin [private]
Definition at line 45 of file MsgSvc.h.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/MsgSvc.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/MsgSvc.cpp