RegisterTest Class Reference
#include <include/RegisterTest.h>
Public Member Functions
RegisterTest ()
Standard constructor.
virtual ~RegisterTest ()
virtual StatusCode initialize ()
Destructor.
virtual StatusCode execute ()
virtual StatusCode finalize ()
StatusCode setAddress (long int address)
StatusCode setParam (int size, double mean, double sigma)
double mean ()
double sigma ()
Protected Member Functions
RegisterTest * clone ()
Private Attributes
TRandom * m_rnd
TH1D * m_write
TH1D * m_read
TH1D * m_error
unsigned int m_address
unsigned int m_size
double m_mean
double m_sigma
Additional Inherited Members
Detailed Description
Author
Frederic Machefert
Date
2010-01-07
Definition at line 18 of file RegisterTest.h.
Constructor & Destructor Documentation
RegisterTest()
RegisterTest::RegisterTest ()
Standard constructor.
Definition at line 23 of file RegisterTest.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
                             :
  m_mean (30000.),
  m_sigma(10000.)
  {
  setName ("RegisterTest");
  setType ("Register");
  setTitle("Register test");
}
 RegisterTest()
virtual RegisterTest::~RegisterTest () [inline], [virtual]
Definition at line 23 of file RegisterTest.h.
References execute(), finalize(), and initialize().
{};
Member Function Documentation
clone()
RegisterTest* RegisterTest::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 50 of file RegisterTest.h.
References RegisterTest().
                       {
    return new RegisterTest (*this);
  }
execute()
StatusCode RegisterTest::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 54 of file RegisterTest.cpp.
References StatusCode::SUCCESS.
Referenced by ~RegisterTest().
                                   {
  /*
  // fetch the usb interface
  Register *reg=dynamic_cast<Register*>(element());
  IOdata::WordSize size=reg->io()->wordSize();
  if(IOdata::Byte!=size){
    warning("Cannot perform test on a ");
    return StatusCode::FAILURE;
  }
  U8 *buffer=reg->io()->dataU8(write);
  // prepare vector to be written
  U8 write[m_size];
  U8 read[m_size];
  for (unsigned int i=0; i<m_size; ++i){
    write[i]=(U16)(m_rnd->Gaus(m_mean,m_sigma));
  }
  // write / read and measure times
  float tw,tr;
  clock_t start;
  start=clock();
  reg->write()
  tw=elapsedTime(start);
  start=clock();
  reg->read()
  tr=elapsedTime(start);
  dataFill("TimeWrite",tw);
  dataFill("TimeRead",tr);
  // store values and check errors
  float w,r;
  for (unsigned int i=0; i<m_size; ++i){
    w=write[i];
    r=read[i];
    dataFill("Write",w);
    m_write->Fill(w);
    m_read->Fill(r);
    if (w!=r){
      warning("Error!");
      m_error->Fill(w);
      dataFill("ErrorWrite",w);
      dataFill("ErrorRead",r);
    }
  }
  */
  return StatusCode::SUCCESS;
}
finalize()
StatusCode RegisterTest::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 106 of file RegisterTest.cpp.
References Processus::closeRootFile(), and StatusCode::SUCCESS.
Referenced by ~RegisterTest().
                                    {
  closeRootFile(); // Deletes the histos -> do not make it yourself !!!
  return StatusCode::SUCCESS;
}
initialize()
StatusCode RegisterTest::initialize () [virtual]
Destructor.
Implements Processus.
Definition at line 35 of file RegisterTest.cpp.
References Processus::addDataStream(), m_error, m_read, m_rnd, m_write, Processus::openRootFile(), and StatusCode::SUCCESS.
Referenced by ~RegisterTest().
                                      {
  openRootFile ();
  m_write=new TH1D("Write" , "Write" , 1000 , 0. , 65535.);
  m_read =new TH1D("Read" , "Read" , 1000 , 0. , 65535.);
  m_error=new TH1D("Error" , "Error" , 1000 , 0. , 65535.);
  m_rnd =new TRandom();
  addDataStream("Write","Written values");
  addDataStream("ErrorWrite","Error - Written values if Error");
  addDataStream("ErrorRead","Error - Read values if Error");
  addDataStream("TimeWrite","Time to write");
  addDataStream("TimeRead","Time to read");
  // addHisto1d(m_write);
  // addHisto1d(m_read);
  return StatusCode::SUCCESS;
}
mean()
double RegisterTest::mean () [inline]
Definition at line 41 of file RegisterTest.h.
References m_mean.
Referenced by setParam().
               {
    return m_mean;
  }
setAddress()
StatusCode RegisterTest::setAddress (long int address) [inline]
Definition at line 29 of file RegisterTest.h.
References m_address, and StatusCode::SUCCESS.
                                           {
    m_address=address;
    return StatusCode::SUCCESS;
  }
setParam()
StatusCode RegisterTest::setParam (int size, double mean, double sigma) [inline]
Definition at line 34 of file RegisterTest.h.
References m_mean, m_sigma, m_size, mean(), sigma(), cat::size, and StatusCode::SUCCESS.
                                                            {
    m_size=size;
    m_mean=mean;
    m_sigma=sigma;
    return StatusCode::SUCCESS;
  }
sigma()
double RegisterTest::sigma () [inline]
Definition at line 45 of file RegisterTest.h.
References m_mean.
Referenced by setParam().
                {
    return m_mean;
  }
Member Data Documentation
m_address
unsigned int RegisterTest::m_address [private]
Definition at line 57 of file RegisterTest.h.
Referenced by setAddress().
m_error
TH1D * RegisterTest::m_error [private]
Definition at line 56 of file RegisterTest.h.
Referenced by initialize().
m_mean
double RegisterTest::m_mean [private]
Definition at line 58 of file RegisterTest.h.
Referenced by mean(), setParam(), and sigma().
m_read
TH1D * RegisterTest::m_read [private]
Definition at line 56 of file RegisterTest.h.
Referenced by initialize().
m_rnd
TRandom* RegisterTest::m_rnd [private]
Definition at line 55 of file RegisterTest.h.
Referenced by initialize().
m_sigma
double RegisterTest::m_sigma [private]
Definition at line 58 of file RegisterTest.h.
Referenced by setParam().
m_size
unsigned int RegisterTest::m_size [private]
Definition at line 57 of file RegisterTest.h.
Referenced by setParam().
m_write
TH1D* RegisterTest::m_write [private]
Definition at line 56 of file RegisterTest.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/inc/proc/RegisterTest.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloProto40MHz/src/proc/RegisterTest.cpp