Options Class Reference
#include <Options.h>
Public Member Functions
Options ()
~Options ()
void setLogOutputLevel (MsgSvc::MsgLevel logOutputLevel)
MsgSvc::MsgLevel logOutputLevel ()
void setPrintFreq (unsigned long printFreq)
unsigned long printFreq ()
void setPlotFreq (unsigned long plotFreq)
unsigned long plotFreq ()
void setStopOnError (bool stopOnError)
bool stopOnError ()
void setRunNumber (unsigned long runNumber)
unsigned long runNumber ()
void setRunNumberManagement (bool runNumberManagement)
bool runNumberManagement ()
void setCurrentPath (std::string currentPath)
std::string currentPath ()
void setStoragePath (std::string storagePath)
std::string storagePath ()
std::string storageFullPath ()
void setStorageDir (std::string filename)
std::string storageDir ()
void setStorageFile (std::string filename=std::string(``))
std::string storageFile ()
std::string storageFileFullName ()
std::string dataFileFullName ()
std::string dataFile ()
std::string logFile ()
void setDataStorage (bool dataStorage)
bool dataStorage ()
void setLogStorage (bool logStorage)
bool logStorage ()
void setLogDefFile (std::string defFile)
std::string logDefFile ()
void setDefFile (std::string def)
std::string defFile ()
void setNEvt (unsigned long nEvt)
unsigned long nEvt ()
void setNEvtMax (int nEvtMax)
int nEvtMax ()
void setTimeMax (unsigned long timeMax)
unsigned long timeMax ()
void setNErrors (unsigned long nErrors)
unsigned long nErrors ()
void incRunNumber ()
void incNEvt ()
void incNErrors ()
std::ofstream * stream ()
void setStream (std::string file=std::string(``))
void print ()
Private Attributes
MsgSvc m_log
MsgSvc::MsgLevel m_logOutputLevel
std::string m_currentPath
bool m_dataStorage
bool m_logStorage
std::string m_storageDir
std::string m_storageFile
std::string m_storageDefault
std::string m_storagePath
std::string m_defFile
bool m_stopOnError
unsigned long m_nEvt
unsigned long m_nErrors
unsigned long m_printFreq
unsigned long m_plotFreq
int m_nEvtMax
int m_timeMax
unsigned long m_runNumber
bool m_runNumberManagement
bool m_batch
std::ofstream * m_stream
std::ofstream * m_logStream
std::ofstream * m_logDefStream
std::string m_logDefFile
Detailed Description
Definition at line 25 of file Options.h.
Constructor & Destructor Documentation
Options()
Options::Options ()
Definition at line 19 of file Options.cpp.
References MsgSvc::INFO, m_logDefStream, m_logStream, m_storageDefault, m_stream, setCurrentPath(), setDataStorage(), setLogDefFile(), setLogOutputLevel(), setLogStorage(), setNErrors(), setNEvt(), setNEvtMax(), setPlotFreq(), setPrintFreq(), setRunNumber(), setRunNumberManagement(), setStorageDir(), setStorageFile(), setStoragePath(), setStream(), and setTimeMax().
                   {
  m_logStream = 0;
  m_logDefStream = 0;
  m_stream = 0;
  setLogDefFile("session.log");
  setStream();
  setLogOutputLevel(MsgSvc::INFO);
  setNEvtMax (100);
  setTimeMax (100);
  setNEvt (0);
  setNErrors (0);
  setRunNumber (0);
  setPrintFreq (0);
  setPlotFreq (0);
  setRunNumberManagement(true);
  setStorageDir("Run");
  m_storageDefault=std::string("run");
  setStorageFile();
  setDataStorage (false);
  setLogStorage (false);
#ifdef WIN32
  char buffer[_MAX_PATH];
  getcwd(buffer,_MAX_PATH);
  setStoragePath(std::string(buffer));
#else
  char buffer[256];
  getcwd(buffer,256);
  setStoragePath(std::string(buffer)+std::string("/data"));
#endif
  setCurrentPath(std::string(buffer));
}
 Options()
Options::~Options ()
Definition at line 63 of file Options.cpp.
References m_logDefStream.
                  {
  if (0!=m_logDefStream){
    m_logDefStream->close();
    delete m_logDefStream;
    m_logDefStream=0;
  }
}
Member Function Documentation
currentPath()
std::string Options::currentPath () [inline]
Get accessor to member m_currentPath
Returns
the current value of m_currentPath
Definition at line 135 of file Options.h.
References m_currentPath.
Referenced by export_base(), and setCurrentPath().
                                 {
                return m_currentPath;
        }
dataFile()
std::string Options::dataFile ()
Get accessor to member m_dataFile
Returns
the current value of m_dataFile
Definition at line 83 of file Options.cpp.
References m_storageFile.
Referenced by dataFileFullName(), and export_base().
                             {
  std::string id;
  id.append(std::string(".root"));
  std::string file = m_storageFile+id;
  return file;
}
dataFileFullName()
std::string Options::dataFileFullName () [inline]
Get accessor to member m_storageFile
Returns
the current value of m_storageFile
Definition at line 219 of file Options.h.
References dataFile(), logFile(), m_storageFile, and storageFullPath().
Referenced by Processus::closeRootFile(), export_base(), and Processus::openRootFile().
                                     {
                std::string file = storageFullPath();
                file.append("/");
                file.append(m_storageFile);
                file.append(".root");
                // std::cout << " OPTIONS ->" << file << " " << storageFullPath()<< " " << m_storageFile
        << std::endl;
                return file;
        }
dataStorage()
bool Options::dataStorage () [inline]
Get accessor to member m_dataStorage
Returns
the current value of m_dataStorage
Definition at line 252 of file Options.h.
References m_dataStorage.
Referenced by Processus::closeRootFile(), EmulateFE::execute(), export_base(), EmulateFE::initialize(), ADCMeasurement::initialize(), Processus::openRootFile(), Application::prepare(), and setDataStorage().
                            {
                return m_dataStorage;
        }
defFile()
std::string Options::defFile () [inline]
Get accessor to member m_defFile
Returns
the current value of m_defFile
Definition at line 301 of file Options.h.
References m_defFile.
Referenced by export_base(), and setLogDefFile().
                             {
                return m_defFile;
        }
incNErrors()
void Options::incNErrors () [inline]
Incrementation of the current number of errors
Definition at line 384 of file Options.h.
References nErrors(), and setNErrors().
Referenced by export_base(), and Application::loop().
                          {
                setNErrors (nErrors() + 1);
        }
incNEvt()
void Options::incNEvt () [inline]
Incrementation of the current evt number
Definition at line 377 of file Options.h.
References nEvt(), and setNEvt().
Referenced by export_base(), and Application::loop().
                       {
                setNEvt (nEvt() + 1);
        }
incRunNumber()
void Options::incRunNumber ()
Incrementation of the current Run number
Definition at line 74 of file Options.cpp.
References runNumber(), and setRunNumber().
Referenced by export_base(), nErrors(), and Application::terminate().
                             {
  setRunNumber(runNumber()+1);
}
logDefFile()
std::string Options::logDefFile () [inline]
Get accessor to member m_logDefStorage
Returns
the current value of m_logDefStorage
Definition at line 285 of file Options.h.
References m_logDefFile.
Referenced by export_base().
                                {
                return m_logDefFile;
        }
logFile()
std::string Options::logFile ()
Get accessor to member m_logFile
Returns
the current value of m_logFile
Definition at line 95 of file Options.cpp.
References m_storageFile.
Referenced by dataFileFullName(), and export_base().
                            {
  std::string id;
  id.append(std::string(".log"));
  std::string file = m_storageFile+id;
  return file;
}
logOutputLevel()
MsgSvc::MsgLevel Options::logOutputLevel () [inline]
Get accessor to member m_logOutputLevel
Returns
the current value of m_logOutputLevel
Definition at line 42 of file Options.h.
References m_logOutputLevel.
Referenced by export_base(), and setLogOutputLevel().
                                         {
                return m_logOutputLevel;
        }
logStorage()
bool Options::logStorage () [inline]
Get accessor to member m_logStorage
Returns
the current value of m_logStorage
Definition at line 268 of file Options.h.
References m_logStorage.
Referenced by export_base(), Application::prepare(), setLogStorage(), setStream(), and Application::terminate().
                           {
                return m_logStorage;
        }
nErrors()
unsigned long Options::nErrors () [inline]
Get accessor to member m_nErrors
Returns
the current value of m_nErrors
Definition at line 365 of file Options.h.
References incRunNumber(), and m_nErrors.
Referenced by Processus::endProcessing(), export_base(), incNErrors(), Application::loop(), setNErrors(), Application::setState(), and Processus::setState().
                                 {
                return m_nErrors;
        }
nEvt()
unsigned long Options::nEvt () [inline]
Get accessor to member m_nEvt
Returns
the current value of m_nEvt
Definition at line 317 of file Options.h.
References m_nEvt.
Referenced by Processus::endProcessing(), Acquisition::execute(), ADCMeasurement::execute(), CurrentMeasurement::execute(), export_base(), incNEvt(), Application::loop(), setNEvt(), Application::setState(), Processus::setState(), Application::svcRunning(), and Application::terminate().
                              {
                return m_nEvt;
        }
nEvtMax()
int Options::nEvtMax () [inline]
Get accessor to member m_nEvtMax
Returns
the current value of m_nEvtMax
Definition at line 333 of file Options.h.
References m_nEvtMax.
Referenced by export_base(), setNEvtMax(), Application::setState(), and Application::svcRunning().
                       {
                return m_nEvtMax;
        }
plotFreq()
unsigned long Options::plotFreq () [inline]
Get accessor to member m_plotFreq
Returns
the current value of m_plotFreq
Definition at line 74 of file Options.h.
References m_plotFreq.
Referenced by export_base(), and setPlotFreq().
                                  {
                return m_plotFreq;
        }
print()
void Options::print ()
Definition at line 107 of file Options.cpp.
References MsgSvc::INFO, m_batch, m_currentPath, m_dataStorage, m_defFile, m_log, m_logDefFile, m_logStorage, m_nErrors, m_nEvt, m_nEvtMax, m_plotFreq, m_printFreq, m_runNumber, m_runNumberManagement, m_stopOnError, m_storageDefault, m_storageDir, m_storageFile, m_storagePath, and MsgSvc::msgSvc().
Referenced by export_base(), and setStream().
                   {
  char output[250];
  sprintf(output,"Events to process : %ld",m_nEvtMax);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< number of events to process
  sprintf(output,"Current run number : %ld",m_runNumber);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< Current Run Number
  sprintf(output,"Events processed : %ld",m_nEvt);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< number of events processed
  sprintf(output,"Number of errors : %ld",m_nErrors);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< number of errors in present
       process
  sprintf(output,"Stop on error flag : %i",m_stopOnError);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");
  sprintf(output,"Printout frequency : %ld",m_printFreq);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< Evt Number Output Frequency
  sprintf(output,"Plot update frequency : %ld",m_plotFreq);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< Evt Number plot Frequency
  sprintf(output,"Automatic run number flag : %i",m_runNumberManagement);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< Run Number Automatically
       Managed
  sprintf(output,"Storage flag : %i",m_dataStorage);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");
  sprintf(output,"Storage filename : %s",m_storageFile.c_str());
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< data & log file name for
       storage
  sprintf(output,"Storage directory : %s",m_storageDir.c_str());
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< data & log directory name for
       storage
  sprintf(output,"Storage default filename : %s",m_storageDefault.c_str());
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< data & log default file name
       for storage
  sprintf(output,"Storage path : %s",m_storagePath.c_str());
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< data & log file path for
       storage
  sprintf(output,"Log Storage flag : %i",m_logStorage);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< Log Storage boolean
  sprintf(output,"Log default filename : %s",m_logDefFile.c_str());
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< default log file name for
       storage
  sprintf(output,"Application current path : %s",m_currentPath.c_str());
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");
  sprintf(output,"Current definition filename : %s",m_defFile.c_str());
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< Definition file
  sprintf(output,"Batch run flag : %i",m_batch);
      m_log.msgSvc(MsgSvc::INFO,output,"Options::help");//< batch mode
}
printFreq()
unsigned long Options::printFreq () [inline]
Get accessor to member m_printFreq
Returns
the current value of m_printFreq
Definition at line 58 of file Options.h.
References m_printFreq.
Referenced by export_base(), Application::loop(), and setPrintFreq().
                                   {
                return m_printFreq;
        }
runNumber()
unsigned long Options::runNumber () [inline]
Get accessor to member m_runNumber
Returns
the current value of m_runNumber
Definition at line 107 of file Options.h.
References m_runNumber.
Referenced by Application::bookkeeping(), Processus::endProcessing(), export_base(), incRunNumber(), Acquisition::initialize(), CurrentMeasurement::initialize(), ADCMeasurement::initialize(), setRunNumber(), and Application::setState().
                                   {
                return m_runNumber;
        }
runNumberManagement()
bool Options::runNumberManagement () [inline]
Get accessor to member m_runNumberManagement
Returns
the current value of m_runNumberManagement
Definition at line 123 of file Options.h.
References m_runNumberManagement.
Referenced by export_base(), setRunNumberManagement(), and Application::terminate().
                                    {
                return m_runNumberManagement;
        }
setCurrentPath()
void Options::setCurrentPath (std::string currentPath) [inline]
Definition at line 127 of file Options.h.
References currentPath(), and m_currentPath.
Referenced by export_base(), and Options().
                                                    {
                m_currentPath = currentPath;
        }
setDataStorage()
void Options::setDataStorage (bool dataStorage) [inline]
Set accessor to member m_dataStorage
Parameters
dataStorage the new value for m_dataStorage
Definition at line 244 of file Options.h.
References dataStorage(), and m_dataStorage.
Referenced by export_base(), and Options().
                                               {
                m_dataStorage = dataStorage;
        }
setDefFile()
void Options::setDefFile (std::string def) [inline]
Set accessor to member m_defFile
Parameters
defFile the new value for m_defFile
Definition at line 293 of file Options.h.
References m_defFile.
Referenced by export_base().
                                        {
                m_defFile = def;
        }
setLogDefFile()
void Options::setLogDefFile (std::string defFile) [inline]
Set accessor to member m_logDefFile
Parameters
logDefStorage the new value for m_logDefFile
Definition at line 276 of file Options.h.
References defFile(), m_logDefFile, and m_logDefStream.
Referenced by export_base(), and Options().
                                               {
                m_logDefFile = defFile;
                m_logDefStream = new std::ofstream(defFile.c_str());
        }
setLogOutputLevel()
void Options::setLogOutputLevel (MsgSvc::MsgLevel logOutputLevel) [inline]
Set accessor to member m_logOutputLevel
Parameters
logOutputLevel the new value for m_logOutputLevel
Definition at line 34 of file Options.h.
References logOutputLevel(), and m_logOutputLevel.
Referenced by export_base(), and Options().
                                                               {
                m_logOutputLevel = logOutputLevel;
        }
setLogStorage()
void Options::setLogStorage (bool logStorage) [inline]
Set accessor to member m_logStorage
Parameters
logStorage the new value for m_logStorage
Definition at line 260 of file Options.h.
References logStorage(), and m_logStorage.
Referenced by export_base(), and Options().
                                             {
                m_logStorage = logStorage;
        }
setNErrors()
void Options::setNErrors (unsigned long nErrors) [inline]
Set accessor to member m_nErrors
Parameters
nErrors the new value for m_nErrors
Definition at line 357 of file Options.h.
References m_nErrors, and nErrors().
Referenced by export_base(), incNErrors(), Options(), Application::prepare(), and Processus::startProcessing().
                                                {
                m_nErrors = nErrors;
        }
setNEvt()
void Options::setNEvt (unsigned long nEvt) [inline]
Set accessor to member m_nEvt
Parameters
nEvt the new value for m_nEvt
Definition at line 309 of file Options.h.
References m_nEvt, and nEvt().
Referenced by export_base(), incNEvt(), Options(), Application::prepare(), and Application::terminate().
                                          {
                m_nEvt = nEvt;
        }
setNEvtMax()
void Options::setNEvtMax (int nEvtMax) [inline]
Set accessor to member m_nEvtMax
Parameters
nEvtMax the new value for m_nEvtMax
Definition at line 325 of file Options.h.
References m_nEvtMax, and nEvtMax().
Referenced by export_base(), Options(), and Application::prepare().
                                      {
                m_nEvtMax = nEvtMax;
        }
setPlotFreq()
void Options::setPlotFreq (unsigned long plotFreq) [inline]
Set accessor to member m_plotFreq
Parameters
plotFreq the new value for m_plotFreq
Definition at line 66 of file Options.h.
References m_plotFreq, and plotFreq().
Referenced by export_base(), and Options().
                                                  {
                m_plotFreq = plotFreq;
        }
setPrintFreq()
void Options::setPrintFreq (unsigned long printFreq) [inline]
Set accessor to member m_printFreq
Parameters
PrintFreq the new value for m_PrintFreq
Definition at line 50 of file Options.h.
References m_printFreq, and printFreq().
Referenced by export_base(), and Options().
                                                    {
                m_printFreq = printFreq;
        }
setRunNumber()
void Options::setRunNumber (unsigned long runNumber) [inline]
Set accessor to member m_runNumber
Parameters
runNumber the new value for m_runNumber
Definition at line 99 of file Options.h.
References m_runNumber, and runNumber().
Referenced by export_base(), incRunNumber(), Application::loadHistoryFile(), and Options().
                                                    {
                m_runNumber = runNumber;
        }
setRunNumberManagement()
void Options::setRunNumberManagement (bool runNumberManagement) [inline]
Set accessor to member m_runNumberManagement
Parameters
runNumberManagement the new value for m_runNumberManagement
Definition at line 115 of file Options.h.
References m_runNumberManagement, and runNumberManagement().
Referenced by export_base(), and Options().
                                                               {
                m_runNumberManagement = runNumberManagement;
        }
setStopOnError()
void Options::setStopOnError (bool stopOnError) [inline]
Set accessor to member m_stopOnError
Parameters
stopOnError the new value for m_stopOnError
Definition at line 83 of file Options.h.
References m_stopOnError, and stopOnError().
Referenced by export_base().
                                               {
                m_stopOnError = stopOnError;
        }
setStorageDir()
void Options::setStorageDir (std::string filename) [inline]
Set accessor to member m_storageDir
Parameters
StorageDir the new value for m_storageDir
Definition at line 172 of file Options.h.
References m_storageDir.
Referenced by export_base(), and Options().
                                               {
                m_storageDir = filename;
        }
setStorageFile()
void Options::setStorageFile (std::string filename = std::string(``)) [inline]
Set accessor to member m_StorageFile
Parameters
StorageFile the new value for m_StorageFile
Definition at line 188 of file Options.h.
References m_storageDefault, and m_storageFile.
Referenced by export_base(), Options(), Application::prepare(), and setStream().
                                                              {
                if (std::string("")==filename) {
                        m_storageFile = m_storageDefault;
                        return;
                }
                m_storageFile = filename;
        }
setStoragePath()
void Options::setStoragePath (std::string storagePath) [inline]
Set accessor to member m_storagePath
Parameters
storagePath the new value for m_storagePath
Definition at line 143 of file Options.h.
References m_storagePath, and storagePath().
Referenced by export_base(), and Options().
                                                    {
                m_storagePath = storagePath;
        }
setStream()
void Options::setStream (std::string file = std::string(``)) [inline]
Set accessor to member m_nEvt
Parameters
nEvt the new value for m_nEvt
Definition at line 400 of file Options.h.
References logStorage(), m_logDefStream, m_logStream, m_stream, print(), setStorageFile(), and storageFileFullName().
Referenced by export_base(), Options(), Application::prepare(), and Application::terminate().
                                                        {
                if (file.compare("")==0) {
                        if (m_stream == m_logStream && 0!=
      m_logStream) {
                                m_logStream->close();
                                delete m_logStream;
                                m_logStream = 0;
                        }
                        m_stream=m_logDefStream;
                }
                else {
                        if (!logStorage ()) {
                                setStorageFile (file);
                        }
                        else {
                                if (0!=m_logStream) {
                                        m_logStream->close();
                                        delete m_logStream;
                                        m_logStream=0;
                                }
                                setStorageFile(file);
                                std::string name = storageFileFullName();
                                name.append(".log");
                                m_logStream = new std::ofstream(name.c_str());
                                m_stream=m_logStream;
                        }
                }
        }
setTimeMax()
void Options::setTimeMax (unsigned long timeMax) [inline]
Set accessor to member m_timeMax
Parameters
timeMax the new value for m_timeMax
Definition at line 341 of file Options.h.
References m_timeMax, and timeMax().
Referenced by Options(), and Application::prepare().
                                                {
                m_timeMax = timeMax;
        }
stopOnError()
bool Options::stopOnError () [inline]
Get accessor to member m_stopOnError
Returns
the current value of m_stopOnError
Definition at line 91 of file Options.h.
References m_stopOnError.
Referenced by export_base(), Application::loop(), and setStopOnError().
                            {
                return m_stopOnError;
        }
storageDir()
std::string Options::storageDir () [inline]
Get accessor to member m_storageDir
Returns
the current value of m_storageDir
Definition at line 180 of file Options.h.
References m_storageDir.
Referenced by export_base().
                               {
                return m_storageDir;
        }
storageFile()
std::string Options::storageFile () [inline]
Get accessor to member m_storageFile
Returns
the current value of m_storageFile
Definition at line 200 of file Options.h.
References m_storageFile.
Referenced by export_base(), and Application::prepare().
                                {
                return m_storageFile;
        }
storageFileFullName()
std::string Options::storageFileFullName () [inline]
Get accessor to member m_storageFile
Returns
the current value of m_storageFile
Definition at line 208 of file Options.h.
References m_storageFile, and storageFullPath().
Referenced by export_base(), and setStream().
                                        {
                std::string file = storageFullPath();
                file.append("/");
                file.append(m_storageFile);
                return file;
        }
storageFullPath()
std::string Options::storageFullPath () [inline]
Get accessor to member m_storagePath
Returns
the current value of m_storagePath
Definition at line 159 of file Options.h.
References itos(), m_runNumber, m_storageDir, and m_storagePath.
Referenced by dataFileFullName(), export_base(), EmulateFE::generateFile(), Application::prepare(), and storageFileFullName().
                                     {
                std::string path = m_storagePath;
                path.append("/");
                path.append(m_storageDir);
                path.append("_");
                path.append(itos(m_runNumber));
                return path;
        }
storagePath()
std::string Options::storagePath () [inline]
Get accessor to member m_storagePath
Returns
the current value of m_storagePath
Definition at line 151 of file Options.h.
References m_storagePath.
Referenced by export_base(), and setStoragePath().
                                 {
                return m_storagePath;
        }
stream()
std::ofstream* Options::stream () [inline]
Get accessor to member m_logStream
Returns
the current value of m_logStream
Definition at line 392 of file Options.h.
References m_stream.
                               {
                return m_stream;
        }
timeMax()
unsigned long Options::timeMax () [inline]
Get accessor to member m_timeMax
Returns
the current value of m_timeMax
Definition at line 349 of file Options.h.
References m_timeMax.
Referenced by setTimeMax().
                                 {
                return m_timeMax;
        }
Member Data Documentation
m_batch
bool Options::m_batch [private]
Definition at line 456 of file Options.h.
Referenced by print().
m_currentPath
std::string Options::m_currentPath [private]
Definition at line 438 of file Options.h.
Referenced by currentPath(), print(), and setCurrentPath().
m_dataStorage
bool Options::m_dataStorage [private]
Definition at line 439 of file Options.h.
Referenced by dataStorage(), print(), and setDataStorage().
m_defFile
std::string Options::m_defFile [private]
Definition at line 445 of file Options.h.
Referenced by defFile(), print(), and setDefFile().
m_log
MsgSvc Options::m_log [private]
Definition at line 435 of file Options.h.
Referenced by print().
m_logDefFile
std::string Options::m_logDefFile [private]
Definition at line 461 of file Options.h.
Referenced by logDefFile(), print(), and setLogDefFile().
m_logDefStream
std::ofstream* Options::m_logDefStream [private]
Definition at line 460 of file Options.h.
Referenced by Options(), setLogDefFile(), setStream(), and ~Options().
m_logOutputLevel
MsgSvc::MsgLevel Options::m_logOutputLevel [private]
Definition at line 436 of file Options.h.
Referenced by logOutputLevel(), and setLogOutputLevel().
m_logStorage
bool Options::m_logStorage [private]
Definition at line 440 of file Options.h.
Referenced by logStorage(), print(), and setLogStorage().
m_logStream
std::ofstream* Options::m_logStream [private]
Definition at line 459 of file Options.h.
Referenced by Options(), and setStream().
m_nErrors
unsigned long Options::m_nErrors [private]
Definition at line 448 of file Options.h.
Referenced by nErrors(), print(), and setNErrors().
m_nEvt
unsigned long Options::m_nEvt [private]
Definition at line 447 of file Options.h.
Referenced by nEvt(), print(), and setNEvt().
m_nEvtMax
int Options::m_nEvtMax [private]
Definition at line 451 of file Options.h.
Referenced by nEvtMax(), print(), and setNEvtMax().
m_plotFreq
unsigned long Options::m_plotFreq [private]
Definition at line 450 of file Options.h.
Referenced by plotFreq(), print(), and setPlotFreq().
m_printFreq
unsigned long Options::m_printFreq [private]
Definition at line 449 of file Options.h.
Referenced by print(), printFreq(), and setPrintFreq().
m_runNumber
unsigned long Options::m_runNumber [private]
Definition at line 453 of file Options.h.
Referenced by print(), runNumber(), setRunNumber(), and storageFullPath().
m_runNumberManagement
bool Options::m_runNumberManagement [private]
Definition at line 455 of file Options.h.
Referenced by print(), runNumberManagement(), and setRunNumberManagement().
m_stopOnError
bool Options::m_stopOnError [private]
Definition at line 446 of file Options.h.
Referenced by print(), setStopOnError(), and stopOnError().
m_storageDefault
std::string Options::m_storageDefault [private]
Definition at line 443 of file Options.h.
Referenced by Options(), print(), and setStorageFile().
m_storageDir
std::string Options::m_storageDir [private]
Definition at line 441 of file Options.h.
Referenced by print(), setStorageDir(), storageDir(), and storageFullPath().
m_storageFile
std::string Options::m_storageFile [private]
Definition at line 442 of file Options.h.
Referenced by dataFile(), dataFileFullName(), logFile(), print(), setStorageFile(), storageFile(), and storageFileFullName().
m_storagePath
std::string Options::m_storagePath [private]
Definition at line 444 of file Options.h.
Referenced by print(), setStoragePath(), storageFullPath(), and storagePath().
m_stream
std::ofstream* Options::m_stream [private]
Definition at line 458 of file Options.h.
Referenced by Options(), setStream(), and stream().
m_timeMax
int Options::m_timeMax [private]
Definition at line 452 of file Options.h.
Referenced by setTimeMax(), and timeMax().
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/Options.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Options.cpp