TestI2C Class Reference
#include <include/TestI2C.h>
Classes
class TestI2C
Public Member Functions
TestI2C ()
Standard constructor.
virtual ~TestI2C ()
virtual StatusCode initialize ()
Destructor.
virtual StatusCode execute ()
virtual StatusCode finalize ()
void setAddress (int)
void setSubAddress (int)
Public Attributes
p7 = fig.add_subplot(2,3,6)
plot examples
p6=fig.add_subplot(4,3,6) p6.set_title('axes title') p6.set_xlabel('xlabel') p6.set_ylabel('ylabel') p6.text(3, 8, 'boxed italics text in data coords', style='italic', bbox={'facecolor':'red', 'alpha':0.5, 'pad':10}) p6.text(2, 6, r'an equation: $E=mc^2$', fontsize=15) p6.text(3, 2, unicode('unicode: Institut f\374r Festk\366rperphysik', 'latin-1')) p6.text(0.95, 0.01, 'colored text in axes coords', verticalalignment='bottom', horizontalalignment='right', transform=p6.transAxes, color='green', fontsize=15) p6.plot([2], [1], 'o') p6.annotate('annotate', xy=(2, 1), xytext=(3, 4), arrowprops=dict(facecolor='black', shrink=0.05)) p6.axis([0, 10, 0, 10])
h7 = obj.hist1d(0)
color
Protected Member Functions
TestI2C * clone ()
Private Attributes
FEB_v1 * m_board
SeqPGA * m_seqPga
TRandom * m_rnd
int m_add
int m_subadd
Additional Inherited Members
Detailed Description
Author
Frederic Machefert
Date
2010-01-07
Definition at line 20 of file TestI2C.h.
Constructor & Destructor Documentation
TestI2C()
TestI2C::TestI2C ()
Standard constructor.
Definition at line 23 of file TestI2C.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
{
  setName ("TestI2C");
  setType ("FEB_v1");
  setTitle("I2C interface test");
}
 TestI2C()
virtual TestI2C::~TestI2C () [inline], [virtual]
Definition at line 25 of file TestI2C.h.
References execute(), finalize(), initialize(), setAddress(), and setSubAddress().
{};
Member Function Documentation
clone()
TestI2C* TestI2C::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 35 of file TestI2C.h.
References TestI2C().
                  {
    return new TestI2C (*this);
  };
execute()
StatusCode TestI2C::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 62 of file TestI2C.cpp.
References application(), Processus::dataFill(), SeqPGA::i2cRead(), SeqPGA::i2cWrite(), m_rnd, m_seqPga, m_subadd, and StatusCode::SUCCESS.
Referenced by ~TestI2C().
                              {
  int value = (0xFF)*m_rnd->Uniform();
  dataFill(0, value);
  m_seqPga->i2cWrite(m_subadd, value);
  int tmp = m_seqPga->i2cRead(m_subadd);
  dataFill(1, tmp);
  if (tmp!=value){
    dataFill(2, value);
    dataFill(3, application()->options()->nEvt());
  }
  return StatusCode::SUCCESS;
}
finalize()
StatusCode TestI2C::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 78 of file TestI2C.cpp.
References StatusCode::SUCCESS.
Referenced by ~TestI2C().
                               {
  return StatusCode::SUCCESS;
}
initialize()
StatusCode TestI2C::initialize () [virtual]
Destructor.
Implements Processus.
Definition at line 33 of file TestI2C.cpp.
References Processus::addDataStream(), Processus::element(), m_add, m_board, m_rnd, m_seqPga, FEB_v1::seqPga(), SeqPGA::setI2cAdd(), SeqPGA::setupReg(), StatusCode::SUCCESS, and Object::warning().
Referenced by ~TestI2C().
                                 {
  m_board=dynamic_cast<FEB_v1*>(element());
  
  if (!m_board){
    warning("TestI2C","No FEB_v1 board found. Interrupt.");
    return false;
  }
  m_seqPga = m_board->seqPga();
  if (!m_seqPga){
    warning("TestI2C","No SeqPga found. Interrupt.");
    return false;
  }
  
  m_seqPga->setupReg();
  m_rnd =new TRandom();
  m_seqPga->setI2cAdd(m_add);
  
  addDataStream("Input","Input value");
  addDataStream("Output","Output value");
  addDataStream("Errors","Error input value");
  addDataStream("EventErr","Event Error");
  return StatusCode::SUCCESS;
}
setAddress()
void TestI2C::setAddress (int add)
Definition at line 85 of file TestI2C.cpp.
References Attrib::add(), and m_add.
Referenced by BOOST_PYTHON_MODULE(), and ~TestI2C().
                               {
  m_add = add;
}
setSubAddress()
void TestI2C::setSubAddress (int subadd)
Definition at line 89 of file TestI2C.cpp.
References m_subadd.
Referenced by BOOST_PYTHON_MODULE(), and ~TestI2C().
                                     {
  m_subadd = subadd;
}
Member Data Documentation
color
TestI2C.color
Definition at line 149 of file TestI2C.py.
h7
TestI2C.h7 = obj.hist1d(0)
Definition at line 147 of file TestI2C.py.
m_add
int TestI2C::m_add [private]
Definition at line 43 of file TestI2C.h.
Referenced by initialize(), and setAddress().
m_board
FEB_v1* TestI2C::m_board [private]
Definition at line 37 of file TestI2C.h.
Referenced by initialize().
m_rnd
TRandom* TestI2C::m_rnd [private]
Definition at line 42 of file TestI2C.h.
Referenced by execute(), and initialize().
m_seqPga
SeqPGA* TestI2C::m_seqPga [private]
Definition at line 41 of file TestI2C.h.
Referenced by execute(), and initialize().
m_subadd
int TestI2C::m_subadd [private]
Definition at line 44 of file TestI2C.h.
Referenced by execute(), and setSubAddress().
p7
TestI2C.p7 = fig.add_subplot(2,3,6)
plot examples
p6=fig.add_subplot(4,3,6) p6.set_title('axes title') p6.set_xlabel('xlabel') p6.set_ylabel('ylabel') p6.text(3, 8, 'boxed italics text in data coords', style='italic', bbox={'facecolor':'red', 'alpha':0.5, 'pad':10}) p6.text(2, 6, r'an equation: $E=mc^2$', fontsize=15) p6.text(3, 2, unicode('unicode: Institut f\374r Festk\366rperphysik', 'latin-1')) p6.text(0.95, 0.01, 'colored text in axes coords', verticalalignment='bottom', horizontalalignment='right', transform=p6.transAxes, color='green', fontsize=15) p6.plot([2], [1], 'o') p6.annotate('annotate', xy=(2, 1), xytext=(3, 4), arrowprops=dict(facecolor='black', shrink=0.05)) p6.axis([0, 10, 0, 10])
Definition at line 146 of file TestI2C.py.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/inc/proc/TestI2C.h
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/python/proc/TestI2C.py
/home/eleclhcb/LHCb/lbcat-cmake/CatCaloUpgrade/src/proc/TestI2C.cpp