SpecsI2c Class Reference
#include <include/SpecsI2c.h>
Public Member Functions
SpecsI2c ()
SpecsI2c (unsigned char i)
~SpecsI2c ()
Additional Inherited Members
Detailed Description
Describe a i2c bus
Author
Frédéric Machefert
Date
2004-01-18
Definition at line 29 of file SpecsI2c.h.
Constructor & Destructor Documentation
SpecsI2c() [1/2]
SpecsI2c::SpecsI2c () [inline]
Definition at line 31 of file SpecsI2c.h.
References Object::debug(), Object::name(), Object::setId(), Object::setName(), and Object::setType().
            {
    setName("SpecsI2c");
    setType("SpecsI2c");
    setId(0);
    debug("SpecsI2c::SpecsI2c",name()+" built.");
  }
SpecsI2c() [2/2]
SpecsI2c::SpecsI2c (unsigned char i) [inline]
Definition at line 38 of file SpecsI2c.h.
References Object::info(), itos(), Object::name(), Object::setId(), Object::setName(), and Object::setType().
                           {
    setName("SpecsI2c"+itos(i));
    setType("SpecsI2c");
    setId(i);
    info("SpecsI2c::SpecsI2c",name()+" built.");
  }
 SpecsI2c()
SpecsI2c::~SpecsI2c () [inline]
Definition at line 44 of file SpecsI2c.h.
{;} ;
The documentation for this class was generated from the following file:
/home/eleclhcb/LHCb/lbcat-cmake/CatSpecs/inc/SpecsI2c.h