TestSuite Class Reference
#include <include/TestSuite.h>
Classes
class TestSuite
Public Member Functions
TestSuite ()
Standard constructor.
virtual ~TestSuite ()
virtual StatusCode initialize ()
Destructor.
virtual StatusCode execute ()
virtual StatusCode finalize ()
StatusCode setSigma (double m1, double m2, double m3, double m4)
double sigma (int i)
Public Attributes
p7 = fig.add_subplot(2,3,6)
plot examples
p6=fig.add_subplot(4,3,6) p6.set_title('axes title') p6.set_xlabel('xlabel') p6.set_ylabel('ylabel') p6.text(3, 8, 'boxed italics text in data coords', style='italic', bbox={'facecolor':'red', 'alpha':0.5, 'pad':10}) p6.text(2, 6, r'an equation: $E=mc^2$', fontsize=15) p6.text(3, 2, unicode('unicode: Institut f\374r Festk\366rperphysik', 'latin-1')) p6.text(0.95, 0.01, 'colored text in axes coords', verticalalignment='bottom', horizontalalignment='right', transform=p6.transAxes, color='green', fontsize=15) p6.plot([2], [1], 'o') p6.annotate('annotate', xy=(2, 1), xytext=(3, 4), arrowprops=dict(facecolor='black', shrink=0.05)) p6.axis([0, 10, 0, 10])
h7 = obj.hist1d(0)
color
Protected Member Functions
TestSuite * clone ()
Private Attributes
TRandom * m_rnd
TH1D * m_h1
TH1D * m_h2
TH1D * m_h3
TH1D * m_h4
TH2D * m_h5
double m_m1
double m_m2
double m_m3
double m_m4
std::vector< double > m_val
Additional Inherited Members
Detailed Description
Author
Frederic Machefert
Date
2010-01-07
Definition at line 18 of file TestSuite.h.
Constructor & Destructor Documentation
TestSuite()
TestSuite::TestSuite ()
Standard constructor.
Definition at line 23 of file TestSuite.cpp.
References Object::setName(), Object::setTitle(), and Object::setType().
Referenced by clone().
                       :
  m_m1(2.),
  m_m2(2.),
  m_m3(2.),
  m_m4(2.),
  m_h1(0),
  m_h2(0),
  m_h3(0),
  m_h4(0)
{
  setName ("TestSuite");
  setType ("Computer");
  setTitle("CAT processing test suite");
}
 TestSuite()
virtual TestSuite::~TestSuite () [inline], [virtual]
Definition at line 23 of file TestSuite.h.
References execute(), finalize(), and initialize().
{};
Member Function Documentation
clone()
TestSuite* TestSuite::clone () [inline], [protected], [virtual]
processus termination virtual function
Implements Processus.
Definition at line 59 of file TestSuite.h.
References TestSuite().
                    {
    return new TestSuite (*this);
  };
execute()
StatusCode TestSuite::execute () [virtual]
processus execution virtual function
Implements Processus.
Definition at line 61 of file TestSuite.cpp.
References Processus::dataFill(), m_h1, m_h2, m_h3, m_h4, m_h5, m_m1, m_m2, m_m3, m_m4, m_rnd, and StatusCode::SUCCESS.
Referenced by ~TestSuite().
                                {
  double g1=(m_rnd->Gaus(5., m_m1));
  double g2=(m_rnd->Gaus(10.,m_m2));
  dataFill(0,g1);
  dataFill(1,g2);
  double a1=m_rnd->Gaus(15.,m_m3);
  double a2=m_rnd->Gaus(20.,m_m4);
  m_h1->Fill(g1);
  m_h2->Fill(g2);
  m_h3->Fill(a1);
  m_h4->Fill(a2);
  m_h5->Fill(a1,a2);
  // wait(100);
  return StatusCode::SUCCESS;
}
finalize()
StatusCode TestSuite::finalize () [virtual]
processus termination virtual function
Implements Processus.
Definition at line 85 of file TestSuite.cpp.
References StatusCode::SUCCESS.
Referenced by ~TestSuite().
                                 {
  return StatusCode::SUCCESS;
}
initialize()
StatusCode TestSuite::initialize () [virtual]
Destructor.
Implements Processus.
Definition at line 41 of file TestSuite.cpp.
References Processus::addDataStream(), Processus::addHisto1d(), Processus::addHisto2d(), m_h1, m_h2, m_h3, m_h4, m_h5, m_rnd, and StatusCode::SUCCESS.
Referenced by ~TestSuite().
                                   {
  m_h1=new TH1D("Error1" , "Data values with sigma 1" , 25 , 0. , 25.);
  m_h2=new TH1D("Error2" , "Data values with sigma 2" , 25 , 0. , 25.);
  m_h3=new TH1D("Error3" , "Data values with sigma 3" , 25 , 0. , 25.);
  m_h4=new TH1D("Error4" , "Data values with sigma 4" , 25 , 0. , 25.);
  m_h5=new TH2D("Error34", "Data values with sigma 3/4" , 25 , 0. , 25. , 25, 0., 25.);
  addDataStream("g1","First Gaussian");
  addDataStream("g2","Second Gaussian");
  addHisto1d(m_h1);
  addHisto1d(m_h2);
  addHisto1d(m_h3);
  addHisto1d(m_h4);
  addHisto2d(m_h5);
  m_rnd =new TRandom();
  return StatusCode::SUCCESS;
}
setSigma()
StatusCode TestSuite::setSigma (double m1, double m2, double m3, double m4) [inline]
Definition at line 29 of file TestSuite.h.
References m_m1, m_m2, m_m3, m_m4, and StatusCode::SUCCESS.
Referenced by export_proc(), and TestSuite.TestSuite::onApply().
                                                                  {
    m_m1 = m1;
    m_m2 = m2;
    m_m3 = m3;
    m_m4 = m4;
    return StatusCode::SUCCESS;
  };
sigma()
double TestSuite::sigma (int i) [inline]
Definition at line 37 of file TestSuite.h.
References itos(), m_m1, m_m2, m_m3, m_m4, and Object::warning().
Referenced by export_proc(), and TestSuite.TestSuite::update().
                        {
    switch (i)
    {
    case 0 :
      return m_m1;
      break;
    case 1 :
      return m_m2;
      break;
    case 2 :
      return m_m3;
      break;
    case 3 :
      return m_m4;
      break;
    default:
      warning("Wrong index for sigma ["+itos(i)+"]. Expected in [0,3] range.","TestSuite");
    };
    return -1.;
  };
Member Data Documentation
color
TestSuite.color
Definition at line 143 of file TestSuite.py.
h7
TestSuite.h7 = obj.hist1d(0)
Definition at line 141 of file TestSuite.py.
m_h1
TH1D* TestSuite::m_h1 [private]
Definition at line 65 of file TestSuite.h.
Referenced by execute(), and initialize().
m_h2
TH1D * TestSuite::m_h2 [private]
Definition at line 65 of file TestSuite.h.
Referenced by execute(), and initialize().
m_h3
TH1D * TestSuite::m_h3 [private]
Definition at line 65 of file TestSuite.h.
Referenced by execute(), and initialize().
m_h4
TH1D * TestSuite::m_h4 [private]
Definition at line 65 of file TestSuite.h.
Referenced by execute(), and initialize().
m_h5
TH2D* TestSuite::m_h5 [private]
Definition at line 66 of file TestSuite.h.
Referenced by execute(), and initialize().
m_m1
double TestSuite::m_m1 [private]
Definition at line 67 of file TestSuite.h.
Referenced by execute(), setSigma(), and sigma().
m_m2
double TestSuite::m_m2 [private]
Definition at line 67 of file TestSuite.h.
Referenced by execute(), setSigma(), and sigma().
m_m3
double TestSuite::m_m3 [private]
Definition at line 67 of file TestSuite.h.
Referenced by execute(), setSigma(), and sigma().
m_m4
double TestSuite::m_m4 [private]
Definition at line 67 of file TestSuite.h.
Referenced by execute(), setSigma(), and sigma().
m_rnd
TRandom* TestSuite::m_rnd [private]
Definition at line 61 of file TestSuite.h.
Referenced by execute(), and initialize().
m_val
std::vector< double > TestSuite::m_val [private]
Definition at line 68 of file TestSuite.h.
p7
TestSuite.p7 = fig.add_subplot(2,3,6)
plot examples
p6=fig.add_subplot(4,3,6) p6.set_title('axes title') p6.set_xlabel('xlabel') p6.set_ylabel('ylabel') p6.text(3, 8, 'boxed italics text in data coords', style='italic', bbox={'facecolor':'red', 'alpha':0.5, 'pad':10}) p6.text(2, 6, r'an equation: $E=mc^2$', fontsize=15) p6.text(3, 2, unicode('unicode: Institut f\374r Festk\366rperphysik', 'latin-1')) p6.text(0.95, 0.01, 'colored text in axes coords', verticalalignment='bottom', horizontalalignment='right', transform=p6.transAxes, color='green', fontsize=15) p6.plot([2], [1], 'o') p6.annotate('annotate', xy=(2, 1), xytext=(3, 4), arrowprops=dict(facecolor='black', shrink=0.05)) p6.axis([0, 10, 0, 10])
Definition at line 140 of file TestSuite.py.
The documentation for this class was generated from the following files:
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/inc/proc/TestSuite.h
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/python/proc/TestSuite.py
/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/proc/TestSuite.cpp