cat Namespace Reference
Functions
def reset_file
def safe_getsize
def main
Variables
tuple hist_file = os.path.expandvars(`$CATPATH/.cathistory`)
int max_size_bytes = 10000
int max_size_lines = 100
int lines = 0
tuple size = safe_getsize(hist_file)
tuple f = open(hist_file,'a')
Function Documentation
def cat::main (argv = None)
Definition at line 67 of file cat.py.
                   :
  if argv is None:
    argv = sys.argv
    args=arguments(argv)
  if (args.shellMode):
    print 'starting shell...'
    cat=Application()
    shell(cat,args)
  else:
    import gui
    print 'starting gui...'
    gui.main(args)
if __name__ == "__main__":
def cat::reset_file (size, max_size, reason)
Definition at line 22 of file cat.py.
                                    :
        try:
                print "Resetting history file %s because it exceeded %s %s; it ha
      s %s." % (hist_file,max_size,reason,size,)
                f = open(hist_file,'w')
                f.close()
        except IOError, e:
                print "Couldn't reset history file %s [%s]." % (hist_file,e,)
def safe_getsize(hist_file):
def cat::safe_getsize (hist_file)
Definition at line 30 of file cat.py.
                           :
        try:
                size = getsize(hist_file)
        except OSError:
                size = 0
        return size
lines = 0
Variable Documentation
tuple cat::f = open(hist_file,'a')
Definition at line 54 of file cat.py.
tuple cat::hist_file = os.path.expandvars(`$CATPATH/.cathistory`)
Definition at line 11 of file cat.py.
tuple cat::lines = 0
Definition at line 37 of file cat.py.
int cat::max_size_bytes = 10000
Definition at line 12 of file cat.py.
int cat::max_size_lines = 100
Definition at line 13 of file cat.py.
tuple cat::size = safe_getsize(hist_file)
Definition at line 38 of file cat.py.
Referenced by checkCmd(), Server_NI6008::cmd(), and stoi().