tree Namespace Reference
Classes
class MyTreeCtrl
class TreeCtrlPanel
Functions
def GetItem (self)
self.root = self.tree.AddRoot(`The Root Item`) self.tree.SetPyData(self.root, None) self.tree.SetItemImage(self.root, fldridx, wx.TreeItemIcon_Normal) self.tree.SetItemImage(self.root, fldropenidx, wx.TreeItemIcon_Expanded)
def OnRightDown (self, event)
def OnRightUp (self, event)
def OnBeginEdit (self, event)
def OnEndEdit (self, event)
def OnLeftDClick (self, event)
def OnSize (self, event)
def OnExpand (self)
def OnCollapse (self)
def OnItemExpanded (self, event)
def OnItemCollapsed (self, event)
def OnSelChanged (self, event)
def OnActivate (self, event)
def RecreateTree (self, myElements, myProcessus)
def SetTreeModified (self, modified)
def GetItemIdentity (self, item)
def ExpandAll (self)
def CollapseAll (self)
Variables
item
root
TreeItem
Function Documentation
CollapseAll()
def tree.CollapseAll (self)
Definition at line 301 of file tree.py.
Referenced by AppFrame.AppFrame.onCollapse().
    def CollapseAll(self):
        self.tree.CollapseAll()
ExpandAll()
def tree.ExpandAll (self)
Definition at line 298 of file tree.py.
Referenced by AppFrame.AppFrame.onExpand().
    def ExpandAll(self):
        self.tree.ExpandAll()
GetItem()
def tree.GetItem (self)
self.root = self.tree.AddRoot(`The Root Item`) self.tree.SetPyData(self.root, None) self.tree.SetItemImage(self.root, fldridx, wx.TreeItemIcon_Normal) self.tree.SetItemImage(self.root, fldropenidx, wx.TreeItemIcon_Expanded)
for x in range(15): child = self.tree.AppendItem(self.root, `Item %d` % x) self.tree.SetPyData(child, None) self.tree.SetItemImage(child, fldridx, wx.TreeItemIcon_Normal) self.tree.SetItemImage(child, fldropenidx, wx.TreeItemIcon_Expanded) for y in range(5): last = self.tree.AppendItem(child, `item %d-%s` % (x, chr(ord(`a`)+y))) self.tree.SetPyData(last, None) self.tree.SetItemImage(last, fldridx, wx.TreeItemIcon_Normal) self.tree.SetItemImage(last, fldropenidx, wx.TreeItemIcon_Expanded) for z in range(5): item = self.tree.AppendItem(last, `item %d-%s-%d` % (x, chr(ord(`a`)+y), z)) self.tree.SetPyData(item, None) self.tree.SetItemImage(item, fileidx, wx.TreeItemIcon_Normal)
Definition at line 89 of file tree.py.
Referenced by AppFrame.AppFrame.deleteHardware(), and AppFrame.AppFrame.onEdit().
    def GetItem(self):
        def getType():
            item=self.item
            while self.tree.GetItemParent(item)!=self.root:
                item=self.tree.GetItemParent(item)
            return str(self.tree.GetItemText(item))
        def getElement():
            item=self.item
            path=str(self.tree.GetItemText(item))
            while str(self.tree.GetItemText(self.tree.GetItemParent(item)))!='Elements':
                item=self.tree.GetItemParent(item)
                path=str(self.tree.GetItemText(item))+'/'+path
            path='/'+path
            return path
        def getProcessus():
            item=self.item
            return str(self.tree.GetItemText(item))
        objtype=getType()
        if (objtype=='Elements'):
            objtype='Element'
            obj=getElement()
            return [obj,objtype]
        if (objtype=='Processus'):
            obj=getProcessus()
            return [obj,objtype]
GetItemIdentity()
def tree.GetItemIdentity (self, item)
Definition at line 295 of file tree.py.
    def GetItemIdentity(self, item):
        return self.tree.GetPyData(item)
            
OnActivate()
def tree.OnActivate (self, event)
Definition at line 217 of file tree.py.
    def OnActivate(self, event):
        if self.tree.IsExpanded(event.GetItem()):
            self.tree.Collapse(event.GetItem())
        else:
            self.tree.Expand(event.GetItem())
OnBeginEdit()
def tree.OnBeginEdit (self, event)
Definition at line 138 of file tree.py.
    def OnBeginEdit(self, event):
# self.log.WriteText("OnBeginEdit\n")
        # show how to prevent edit...
        item = event.GetItem()
        if item and self.tree.GetItemText(item) == "The Root Item":
            wx.Bell()
# self.log.WriteText("You can't edit this one...\n")
            # Lets just see what's visible of its children
            cookie = 0
            root = event.GetItem()
            (child, cookie) = self.tree.GetFirstChild(root)
            while child.IsOk():
# self.log.WriteText("Child [%s] visible = %d" %
# (self.tree.GetItemText(child),
# self.tree.IsVisible(child)))
                (child, cookie) = self.tree.GetNextChild(root, cookie)
            event.Veto()
OnCollapse()
def tree.OnCollapse (self)
Definition at line 190 of file tree.py.
    def OnCollapse(self):
        self.tree.Collapse(event.GetItem())
OnEndEdit()
def tree.OnEndEdit (self, event)
Definition at line 160 of file tree.py.
    def OnEndEdit(self, event):
# self.log.WriteText("OnEndEdit: %s %s\n" %
# (event.IsEditCancelled(), event.GetLabel()))
        # show how to reject edit, we'll not allow any digits
        for x in event.GetLabel():
            if x in string.digits:
# self.log.WriteText("You can't enter digits...\n")
                event.Veto()
                return
OnExpand()
def tree.OnExpand (self)
Definition at line 187 of file tree.py.
    def OnExpand(self):
        self.tree.Expand(event.GetItem())
OnItemCollapsed()
def tree.OnItemCollapsed (self, event)
Definition at line 198 of file tree.py.
    def OnItemCollapsed(self, event):
        item = event.GetItem()
# if item:
# self.log.WriteText("OnItemCollapsed: %s\n" % self.tree.GetItemText(item))
OnItemExpanded()
def tree.OnItemExpanded (self, event)
Definition at line 193 of file tree.py.
    def OnItemExpanded(self, event):
        item = event.GetItem()
# if item:
# self.log.WriteText("OnItemCollapsed: %s\n" % self.tree.GetItemText(item))
OnLeftDClick()
def tree.OnLeftDClick (self, event)
Definition at line 171 of file tree.py.
    def OnLeftDClick(self, event):
        pt = event.GetPosition();
        item, flags = self.tree.HitTest(pt)
        if item:
# self.log.WriteText("OnLeftDClick: %s\n" % self.tree.GetItemText(item))
            parent = self.tree.GetItemParent(item)
            if parent.IsOk():
                self.tree.SortChildren(parent)
        event.Skip()
OnRightDown()
def tree.OnRightDown (self, event)
Definition at line 119 of file tree.py.
    def OnRightDown(self, event):
        pt = event.GetPosition();
        item, flags = self.tree.HitTest(pt)
        if item:
# self.log.WriteText("OnRightClick: %s, %s, %s\n" %
# (self.tree.GetItemText(item), type(item), item.__class__))
            self.tree.SelectItem(item)
OnRightUp()
def tree.OnRightUp (self, event)
Definition at line 128 of file tree.py.
    def OnRightUp(self, event):
        pt = event.GetPosition();
        item, flags = self.tree.HitTest(pt)
        if item:
# self.log.WriteText("OnRightUp: %s (manually starting label edit)\n"
# % self.tree.GetItemText(item))
            self.tree.EditLabel(item)
OnSelChanged()
def tree.OnSelChanged (self, event)
Definition at line 203 of file tree.py.
    def OnSelChanged(self, event):
        self.item = event.GetItem()
# print "onselchanged"
# print self.tree.GetItemText(self.item), type(self.item), self.item.__class__
# if self.item:
# self.log.WriteText("OnSelChanged: %s\n" % self.tree.GetItemText(self.item))
# if wx.Platform == '__WXMSW__':
# self.log.WriteText("BoundingRect: %s\n" %
# self.tree.GetBoundingRect(self.item, True))
            #items = self.tree.GetSelections()
            #print map(self.tree.GetItemText, items)
        event.Skip()
OnSize()
def tree.OnSize (self, event)
Definition at line 182 of file tree.py.
    def OnSize(self, event):
        w,h = self.GetClientSizeTuple()
        self.tree.SetDimensions(0, 0, w, h)
RecreateTree()
def tree.RecreateTree (self, myElements, myProcessus)
Definition at line 224 of file tree.py.
    def RecreateTree(self, myElements, myProcessus):
        def makeHierarchy(parent, children, image):
# print "call with ",self.tree.GetItemText(parent)," ",children
            for child in range(len(children)):
                if type(children[child])==list:
# print "recurcive list found "
                    makeHierarchy(nChild,children[child],image)
                else:
# print "add item ", children[child], " at ", self.tree.GetItemText(parent)
             
                    nChild=self.tree.AppendItem(parent, children[child], image)
                    self.tree.SetItemPyData(nChild, image)
                    self.TreeItem.append(nChild)
        _treeList = [
                     ('Elements', myElements),
                     ('Processus', myProcessus),
                     ('Data', []),
                     ('Documents', []),
                     ]
# self.tree.Freeze()
        self.tree.DeleteAllItems()
        self.root = self.tree.AddRoot("Objects")
        self.tree.SetItemPyData(self.root, None)
        self.tree.SetItemImage(self.root, self.fldridx, wx.TreeItemIcon_Normal)
        self.tree.SetItemImage(self.root, self.fldropenidx, wx.TreeItemIcon_Expanded)
        treeFont = self.tree.GetFont()
        catFont = self.tree.GetFont()
        # The old native treectrl on MSW has a bug where it doesn't
        # draw all of the text for an item if the font is larger than
        # the default. It seems to be clipping the item's label as if
        # it was the size of the same label in the default font.
        if 'wxMSW' not in wx.PlatformInfo or wx.GetApp().GetComCtl32Version() >= 600:
            treeFont.SetPointSize(treeFont.GetPointSize()+2)
            treeFont.SetWeight(wx.BOLD)
            catFont.SetWeight(wx.BOLD)
        self.tree.SetItemFont(self.root, treeFont)
        firstChild = None
        selectItem = None
        count = 0
        self.TreeItem=[self.root]
        for category, items in _treeList:
            count += 1
            child = self.tree.AppendItem(self.root, category, image=count)
# self.tree.SetItemFont(child, catFont)
            self.tree.SetItemPyData(child, count)
            self.tree.SetItemImage(child, self.fldridx, wx.TreeItemIcon_Normal)
            self.tree.SetItemImage(child, self.fldropenidx, wx.TreeItemIcon_Expanded)
            
            if not firstChild: firstChild = child
            makeHierarchy(child, items, count)
        self.tree.Expand(self.root)
        self.item=self.root
SetTreeModified()
def tree.SetTreeModified (self, modified)
Definition at line 287 of file tree.py.
    def SetTreeModified(self, modified):
        item = self.tree.GetSelection()
        if modified:
            image = len(_objectTypes)
        else:
            image = self.tree.GetItemPyData(item)
        self.tree.SetItemImage(item, image)
Variable Documentation
item
tree.item
Definition at line 204 of file tree.py.
root
tree.root
Definition at line 246 of file tree.py.
TreeItem
tree.TreeItem
Definition at line 271 of file tree.py.