plotter Namespace Reference
Classes
class plotter
Functions
def h1d (fig, histo, alpha=0.5, facecolor='green', edgecolor='yellow', linestyle='dashed')
Function Documentation
h1d()
def plotter.h1d (fig, histo, alpha = 0.5, facecolor = 'green', edgecolor = 'yellow', linestyle = 'dashed')
Definition at line 51 of file plotter.py.
Referenced by plotter.plotter.destroy(), A3PE_BitFlip.Plot(), StorageFifoAcquisition.Plot(), StorageFifo.Plot(), TestSuite.Plot(), TestI2C.Plot(), TestSPI.Plot(), TestUSB.Plot(), and Acquisition.Plot().
        linestyle='dashed'):
        import numpy as np
        left=np.array(histo.edges()[:-1])
        right=np.array(histo.edges()[1:])
        bottom = np.zeros(len(left))
        top=bottom+histo.bins()
        nrects=len(left)
        nverts = nrects*(1+3+1)
        verts = np.zeros((nverts, 2))
        codes = np.ones(nverts, int) * Path.LINETO
        codes[0::5] = Path.MOVETO
        codes[4::5] = Path.CLOSEPOLY
        verts[0::5,0] = left
        verts[0::5,1] = bottom
        verts[1::5,0] = left
        verts[1::5,1] = top
        verts[2::5,0] = right
        verts[2::5,1] = top
        verts[3::5,0] = right
        verts[3::5,1] = bottom
        barpath = Path(verts, codes)
        patch = patches.PathPatch(barpath,
                                  facecolor=facecolor,
                                  edgecolor=edgecolor,
                                  alpha=alpha,
                                  linestyle=linestyle)
        max=histo.maxY()
        fig.add_patch(patch)
        fig.set_xlim(histo.minX(), histo.maxX())
        if (max>0):
                fig.set_ylim(0.,max*1.05)
        else:
                fig.set_ylim(max*1.05,0.)
                