images Namespace Reference
Classes
class ImageClass
Functions
def getMondrianData ()
def getMondrianBitmap ()
def getMondrianImage ()
def getMondrianIcon ()
def getSmallUpArrowData ()
def getSmallUpArrowBitmap ()
def getSmallUpArrowImage ()
def getSmallDnArrowData ()
def getSmallDnArrowBitmap ()
def getSmallDnArrowImage ()
def getNoIconData ()
def getNoIconBitmap ()
def getNoIconImage ()
def getCarrotData ()
def getCarrotBitmap ()
def getCarrotImage ()
def getPointyData ()
def getPointyBitmap ()
def getPointyImage ()
def getPencilData ()
def getPencilBitmap ()
def getPencilImage ()
def get_rt_alignleftData ()
def get_rt_alignleftBitmap ()
def get_rt_alignleftImage ()
def get_rt_alignrightData ()
def get_rt_alignrightBitmap ()
def get_rt_alignrightImage ()
def get_rt_boldData ()
def get_rt_boldBitmap ()
def get_rt_boldImage ()
def get_rt_centreData ()
def get_rt_centreBitmap ()
def get_rt_centreImage ()
def get_rt_colourData ()
def get_rt_colourBitmap ()
def get_rt_colourImage ()
def get_rt_copyData ()
def get_rt_copyBitmap ()
def get_rt_copyImage ()
def get_rt_cutData ()
def get_rt_cutBitmap ()
def get_rt_cutImage ()
def get_rt_fontData ()
def get_rt_fontBitmap ()
def get_rt_fontImage ()
def get_rt_ideaData ()
def get_rt_ideaBitmap ()
def get_rt_ideaImage ()
def get_rt_indentlessData ()
def get_rt_indentlessBitmap ()
def get_rt_indentlessImage ()
def get_rt_indentmoreData ()
def get_rt_indentmoreBitmap ()
def get_rt_indentmoreImage ()
def get_rt_italicData ()
def get_rt_italicBitmap ()
def get_rt_italicImage ()
def get_rt_openData ()
def get_rt_openBitmap ()
def get_rt_openImage ()
def get_rt_pasteData ()
def get_rt_pasteBitmap ()
def get_rt_pasteImage ()
def get_rt_redoData ()
def get_rt_redoBitmap ()
def get_rt_redoImage ()
def get_rt_sampleData ()
def get_rt_sampleBitmap ()
def get_rt_sampleImage ()
def get_rt_saveData ()
def get_rt_saveBitmap ()
def get_rt_saveImage ()
def get_rt_smileyData ()
def get_rt_smileyBitmap ()
def get_rt_smileyImage ()
def get_rt_underlineData ()
def get_rt_underlineBitmap ()
def get_rt_underlineImage ()
def get_rt_undoData ()
def get_rt_undoBitmap ()
def get_rt_undoImage ()
def get_bp_btn1Data ()
def get_bp_btn1Bitmap ()
def get_bp_btn1Image ()
def get_bp_btn2Data ()
def get_bp_btn2Bitmap ()
def get_bp_btn2Image ()
def get_bp_btn3Data ()
def get_bp_btn3Bitmap ()
def get_bp_btn3Image ()
def get_bp_btn4Data ()
def get_bp_btn4Bitmap ()
def get_bp_btn4Image ()
def get_book_redData ()
def get_book_redBitmap ()
def get_book_redImage ()
def get_book_greenData ()
def get_book_greenBitmap ()
def get_book_greenImage ()
def get_book_blueData ()
def get_book_blueBitmap ()
def get_book_blueImage ()
def getDocData ()
def getDocBitmap ()
def getDocImage ()
def getDataData ()
def getDataBitmap ()
def getDataImage ()
def getOverviewData ()
def getOverviewBitmap ()
def getOverviewImage ()
def getProcessusData ()
def getProcessusBitmap ()
def getProcessusImage ()
def getMainData ()
def getMainBitmap ()
def getMainImage ()
def getdeleteperspectiveData ()
def getdeleteperspectiveBitmap ()
def getdeleteperspectiveImage ()
def getdemoData ()
def getdemoBitmap ()
def getdemoImage ()
def getexitData ()
def getexitBitmap ()
def getexitImage ()
def getexpansionData ()
def getexpansionBitmap ()
def getexpansionImage ()
def getfindData ()
def getfindBitmap ()
def getfindImage ()
def getfindnextData ()
def getfindnextBitmap ()
def getfindnextImage ()
def getinspectData ()
def getinspectBitmap ()
def getinspectImage ()
def getmodifiedexistsData ()
def getmodifiedexistsBitmap ()
def getmodifiedexistsImage ()
def getmoredialogData ()
def getmoredialogBitmap ()
def getmoredialogImage ()
def getpyshellData ()
def getpyshellBitmap ()
def getpyshellImage ()
def getrecentData ()
def getrecentBitmap ()
def getrecentImage ()
def getsaveperspectiveData ()
def getsaveperspectiveBitmap ()
def getsaveperspectiveImage ()
def getcustomcontrolData ()
def getcustomcontrolBitmap ()
def getcustomcontrolImage ()
Variables
dictionary catalog = {}
list index = []
Function Documentation
get_book_blueBitmap()
def images.get_book_blueBitmap ()
Definition at line 1010 of file images.py.
References get_book_blueImage().
def get_book_blueBitmap():
    return BitmapFromImage(get_book_blueImage())
get_book_blueData()
def images.get_book_blueData ()
Definition at line 979 of file images.py.
Referenced by get_book_blueImage().
def get_book_blueData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\x82IDAT8\x8d\x8d\x93KHTa\x14\xc7\x7f\xf7\xce\x1d\xc7y\xdc\x19G\xd4L\
\x1bS\xc7Wi\x90\xe4\xa3\x87A\xb6\x88H\x08\xb2U\x11\xd4\xae\x16\xed\x8a\x16-j\
\xdb\xa6u\xd0\xaeE\x9b\xa2\x16\x82\xf6 #\x12E"\xf1\x85`\xf8`\xd4&\x1cu\xd4q\
\xee\xdc\x87w\xe6\xde\x16\x8dbJ\x8f\xff\xea\x1c\xce9?\xce\xf9\xbes\x04\xfe.a\
\x87m\xff+A\x80\x17"W\x1cu$\x85\x16\xdc\xdefd\xff1\xb4\r\x95\x9e\xfb\xd7I\
\x0c\xc5\x00c/\xe0\xf6\xc2Y\x04\xf3\x02rn\x13.\xb5\x11\xdc~D7\xa8\x1a":\x96-\
\xc1\xf8\xc77t\xdf\xba\x07\xc6\xd4n\x88#t\xe9\xceH\xb1l\xb7\'C\x07\xca=K+\
\xae#>\x83\x16\x7f\x8a\x8eCN:\xeb=,&\x0cb\x14U\xe3\x0e\xcb\xcc\xbd\x1d\x05\
\x92\x80\xb5\x05\x10\x17\xd65\xc1\x99\x9fO\xd1J\x14=#\xd0^\xef\xa5\xae\\&\
\xcf-\xb1\xa6\xc1\xd12\x1fH\x12T\x9d\xbaF\xe3\x83\x9b@\t mw@\xd1\xf93fkC\xd8\
53O\xca\x1b`1\xa60\x11\xcb\xf0z,E\xdfH\x82\xd1oq\xd0S`g\x04\xe4P\x0b\xa6\xb4\
\xcc\xea\xf04\xa0\x02\xb6\x03gm\\\xf7\x85\xaf\xe6\xd6V\n\xf2\xf7\x19"\x8a\
\xc4Z\xc2\x00\xc3\x00{\x132&\xa4\xd3\xbf|\xcb\x12qW\x9c@K\xcc\xa2LG\x00Md\
\xfca\x1f\x83\x9fz\x96,\x11]t\x12\x946\xc14\xc0L\x83a\x82\x91\x01\xc5\x84%\
\x15\xa2q\x1aK4\x8f d\x1a\x80\n G\x02T\xa6\x06\x1e\xd1W}.\xd1\xde\xea\x0c\
\xf6\x0f\x80\xe9\x865\r\x94$\xfb\xfck\x1c/Mq\xb2\xddAk\x8d\x87P\xa8X\r?{\xef\
\x02\xbc\x80(\x01\x16\xd1\'C\x8c\x1f~\x9e\x0e\xd7\xde\xd0f\x87i)\xd2ik\x80\
\xa6\x83"\x81\x80\x0f9\x10\xc0\xe7\xf5\x11\xcc\x93Q=\xfb=\x94^\xce!\xfaJ\x03\
\xac\xad\xd7\xd4\xf9\xf1\xf91\xdd\x85\x9d\x1d\xc5]\xfe\xe6\xbaz*\xabk\xf0\
\xcb^t\xdb\xc3\x87\x88\x9b\xfe\x88\x83\xde\xc9\x94\xc6\xdc\xbb1,\x04 \x08\
\xb8\xb6\x006\x8b/\xa7(8\xfdT\x15\n\xeeN,\xf9\xe8\x9e\x11\xf8\x1a\xb1\xacdly\
\x8a\xe4\x97I6\x06WIM\x9b\xd8f\x12\x98\x07R\x80\xfd\xfb*\x07\x9b\xcb(\xbc\
\xd8\x85\xa9$\x89\xf7\xce\xa2N\x1a\xa4\x15\rX\x06\xa2\xc0\x02\xb0\x08\xacg\
\x17J\xd9\t\x00p\x02U@\x1b\x90\x9b-\x88\x02q@\xc9\xfe\xbd\x0ed\xc8\x1e\xd7n\
\x00\xd9\xc2`6\xa6\x02\x1a\xb0\xb9=\xea\x7fJ\xf8\x03|\x8f~\x02x\xb0\xfe\xe3\
\xe93\x0e\xf5\x00\x00\x00\x00IEND\xaeB`\x82'
get_book_blueImage()
def images.get_book_blueImage ()
Definition at line 1013 of file images.py.
References get_book_blueData().
Referenced by get_book_blueBitmap().
def get_book_blueImage():
    stream = cStringIO.StringIO(get_book_blueData())
    return ImageFromStream(stream)
# ***************** Catalog starts here *******************
get_book_greenBitmap()
def images.get_book_greenBitmap ()
Definition at line 971 of file images.py.
References get_book_greenImage().
def get_book_greenBitmap():
    return BitmapFromImage(get_book_greenImage())
get_book_greenData()
def images.get_book_greenData ()
Definition at line 940 of file images.py.
Referenced by get_book_greenImage().
def get_book_greenData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\x86IDAT8\x8d\x8d\x93KO\x13\x01\x14\x85\xbf\x99\xd2\x16;}\xd2\xa0\
\x04\xca\xa3\x14\x14\x8d\x90\xa0<\x95\x88\xba\xc0\x84\xc4\xc4\x10W\xb8\xd0\
\x95\xbf@]\xf8\x0b\xdc\xb81\xae\xdc\x1b\xf6\x1a\x90\x95\x90\x08\xf8\x08\x04$\
\x014\x95RD\x9em\xa1\xf41\xd3i;3nF\x82\x10\x1fgu\x93{\xef\x97\xdc\x9cs\x05\
\xfe.\xe1Pm\xfck@`\x10\x91f\x9a\xc8\xd0!:h?\xe5w^\xcc\xc8\x059\xfdL\xbdK\x94\
m@=\x0e\x18\xe2:\x1a\xfd\x95\x92\xa7\xcd\'Z[\xfd6\xbb\xdb\xeb\xb4\xa1\xcay,y\
\'\x05)\xc7\xf8\xf0\xea\x9b\xc2s\x1e\xa1\x12>\n\xb1\xf4\xde\xaf\x9f\x0b\x9d\
\xa8\xbd\xd6W_S\xa7\xc5\xad\xf6ZK\x13U\xfa9:+\xfa\xb8T\xd5Gb?\x0e\x81T\xe3\
\xa6-\xebb\x96\xcf@\x1a\xd0\x0f\x00\xe57\x1d\x8f\xeb\x02n{"!\xa0\xe4S\xdc\
\xa8\xbb\x85\xdfS\x8edw\xa2\x14\xb3H6\x89Hf\x11)X\xda\x12C.\xb0\xc0\x12\x90\
\xfd\x05\xb1d[\xf2W\xfb\xbb\x1aB\x13\xe1\x1fTT8X\xddZ#*\x87\x19\xdf\x1aa<6\
\xcalr\x16U3\x10\xad\xa2`\xad\xb1t\xa4\xf7\xd5\x18+|\x03d\xc0\xb0\xa8\x15ZB\
\xf4\x19\x83\xcd\x8d\xe5\xc2r4GZ\xda$^\x88\xa1\x1a\x1a\x026tD\x8a\xba\x81Z,"\
:\x0c\xb1X]\xec\xce\xaf\x19\x11\xb6\x89\x02\x8a\xc8\x10\xef\xa6&\xd7G\xec\
\x86\x81\xaaeq\ne\x14u\x01\r\x03U\xd0PD\x95=}\x9f\xc8N\x92\x95\xf9\x14g\xb3\
\xad\x0e\x04\xce\x03A\xc0V\x02\xc8\xea\\\xf1\xc9X0\xda\xd7\xdb\x1b\xb4\x8e\
\xcd\xed`9\xa9\xb2\x11\xdbco\x07\x02\xe9J\xda\xf4+\\\xf6\xf7\xd0}\xa6\x8b\
\xda@\xb5\x1cz\x18\xb2\x03\x12 \x96\x00:o\x99\xf9\x1a\x8c\xbf\x0c5\xb8\xefm~\
\xd8\xa5\xdev\x9a;\xde\x1e:\xca\xda\xf1\xd5yqy\\8\x9d\x12^\x8f\x0f\xd1\xa7;\
\xe8\xc4\xc6G\x14@/1\xdd\xc8iK<}=\x1a\x19\x18X\xbd\xed\xeen\xe9"TS\x8f\xcb\
\xe5\xa6`Q\xf9\x94\x9b`z\xeb=\x93\xf1\te#\x9a\x9c7\x03\xe8\x03\xec\xbf\x00\
\x06S\x84i\xe4E^\xca=X\xcc/0\xb2<\xcc\x8c<\xad\xa7v\xd3a"|a\x99]\xb6)\xa0\
\x91\x06\xbe\x9bV\x1a\xbfG9D\r\x17x\x85B\x9aE"l\xa0\x92C\x01b\xc0:\xb0\x06l\
\x01I3P\x99\xc3\x00\x00+\xd0\x00\xf4\x00\xa5\xe6\xc2:\x90\x002\xa6\xf79@\xc3\
|\xae\xa3\x00\xccE\x9f\xd9\x93\x01\x05\xc8\x1f\x9c\xfa\x9f\x12\xfe\x00?\xa6\
\x9f\x16\xa0\x0c\xe8\xa4\xc9\xa8\x14\x00\x00\x00\x00IEND\xaeB`\x82'
get_book_greenImage()
def images.get_book_greenImage ()
Definition at line 974 of file images.py.
References get_book_greenData().
Referenced by get_book_greenBitmap().
def get_book_greenImage():
    stream = cStringIO.StringIO(get_book_greenData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_book_redBitmap()
def images.get_book_redBitmap ()
Definition at line 932 of file images.py.
References get_book_redImage().
def get_book_redBitmap():
    return BitmapFromImage(get_book_redImage())
get_book_redData()
def images.get_book_redData ()
Definition at line 901 of file images.py.
Referenced by get_book_redImage().
def get_book_redData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\x93IDAT8\x8d\x85\x93IL\x13\x01\x14\x86\xbf\x99i;]hiA\x10\xa4\xac\
\x01!F\xa0\x88V0\xe8\x81\x8b&x0&xr\xbb\xe8\xd9\x03^8\x18\xaf&\xc6\xab\x07o\\\
\x8d1j\x0c\xd1\xb8DM\x10\x8d\xa0\x18\x16\x03H*K(e\x11\xbaMg\xa63\xe3\xc1bPP\
\xff\xe4%\xef\xf0\xde\x97\xbc\xf7\xbf\'\xf0o\t[r\xeb\x7f\x05\xc2u\x10\xba\
\x83\xd4\x9b\x1aa\xc1\xcd!\xf7\xae@kZQ\xb5Kc\xe9\xf3o!\n\xa8\xdb\x00J\x88\
\xa3\x96C\xec\x12\xf3\xfd\x07E\xa7\xbb\xd5t\xb9\xfdr\x9e\x0bL\x13\x1c2d\x15\
\xfa\x9fM<95k^\xd5`\xf2O\x88t\xad%8h+\xad<\xe1h9P#\x19\xa63[V\x8b^Z\x8b\xd1t\
\x0c#\xd4\x89M\xcbP\'&k\xcb\x97\xd6}\x0f\x14F\x808`\xfe\x02\xf4\x04\xed=r\
\xbe7/\xab\x0bHj\x82D\xb8\x0b\xb1p7\xa2+\x0f\x9b\xa1#\xcaNX\x9c\xa2)`o\xb4\
\xcf\xc6\xf5\x97\x06\xe3@j\x13"]t\xa8\x1dE\xf5\xe5\r\x89\xaf\xb38KK\xb0E#H\
\xd1o\xc8\xc3\xcf\x11\x07\xfba\xfc\x03\xe8*\x82\xc3&\x84\xf2\xed\xe1\xb5\xf9\
\xf4\xf2\x90\xc54\x90\x06,\xa9M\xb7\x96\xf7\xc9\xda9W\xb0XH\xac\xa5qgV\x91V\
\x97@\xd7@\x94~\xee\xd94\xc1\xd0\x91=\x82xX\xca\xb6\x8f-\x1b3\xd3\x10\x01\
\x14\xf1l\x9cw\xe3S+\xf7\x05K%\xb3\xf2\x1d<\x01\xb0L0\x0c0t\xc8*\x90Z\'9\xb9\
\xc4\xd8@\x8c\x91\x92f\xb7!\x8a\xfb\x81j\xc0a\x03\x94\xc7\xcb\xdc\xa8\x18\
\x9d\xef*n\xaev\xaeGb\xf8\xbd\x1a,\xae\x10\x8d\x1a\x8c\x17\x941S\xd9\x8e~\
\xa1\x03g\xb8\x9d`e\x85\xf2to\xb5\x0cx\x00\xd1\x06\x98\xbd*\xa3\x8d3\xa9\xbe\
\x93\xe5\xb1\xcb\xaf")V\x82\r\xac\xb7\x9dAk\t\xe3\xf3\xfb\xf1y\xbd\x14x<\xb8\
\xbd~\x8a%\xcb\xd5S\x8c\xe3f\x0c\x050m972w7\xb8U\xf6"\xd6}\xe7\xf8\xe9@y\xeb\
\x11\xea\xaa*)\xf4\xe5\x13\x10\xb2\xd4.|\xa4h\xe2=\xfe\xa1\xd7\xca\xd0\xec\
\xc2\'\xd1\x00\xc0\x0f\xc8\x9b\x00\xab\x0f"\x9d)nWY\x99\xdeP|\x8a\xb6\x817\
\x14\x8c\x0e[\xc9\xa9\xb9\xc9{k|y\xa4\xb3:d`h\x16\x1b\xc0\\\xceJ\xeb\xb7S\
\x0e\xc1\x9e+.\x1ej\xa0\xf6)L\x7f\x065\x0e\x19 \x06\xcc\xe7b\x11\xd8\x00\x12\
@r+\x00\xc0\x0e\xd4\x00\x1d\x80{K\xd3*\x90\xccy\x9f\x01\x0cr\xcf\xf5\'\x00@\
\x06\x02\x80\x98kP\x00ms\xd4\x1d\xeaw\x94\xf0\x17\xf86\xfd\x00\x8a\x84\x08\
\xee\xfb\x9c!f\x00\x00\x00\x00IEND\xaeB`\x82'
get_book_redImage()
def images.get_book_redImage ()
Definition at line 935 of file images.py.
References get_book_redData().
Referenced by get_book_redBitmap().
def get_book_redImage():
    stream = cStringIO.StringIO(get_book_redData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_bp_btn1Bitmap()
def images.get_bp_btn1Bitmap ()
Definition at line 714 of file images.py.
References get_bp_btn1Image().
def get_bp_btn1Bitmap():
    return BitmapFromImage(get_bp_btn1Image())
get_bp_btn1Data()
def images.get_bp_btn1Data ()
Definition at line 661 of file images.py.
Referenced by get_bp_btn1Image().
def get_bp_btn1Data():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x16\x00\x00\x00\x16\x08\x06\
\x00\x00\x00\xc4\xb4l;\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x04\xb9IDAT8\x8d\x8d\x95[l\x14U\x18\xc7\x7fgn;;\xbb\xdbv/\x14[J\xa1\\*\xb7\
\x16\xe5"E@\xd2\x82\x12!\r\x12\x02\xc6H\x82D\x8d\x89\x89\x89\xf8 \x89\x89\
\xf0\x82\x0f\xea\x8b\x86\x07/\x81\x17\x13#JH$"P\xc1\xa8\x14\x11)5`\xb17*mi\
\xa1\xf4\xc2\x96vw\xbb;\xbb\xb33>\x0ctA.z\x92\xefe\xce\x9c\xdf\xf9\xce\xf7\
\xff\x9f\xf3\t\xfesl\xf7\xa2\xa7"\xd8\x9a\x01\x96\x83l%HjC\xb0\xc7|\xd8*\xf1\
\xc0\x19\xcf\xf6j\x1c^F\xd6\x9f\xc2\x93W\x84\xe6U\x00H\'\xd2\x98\xb1\x1e\xb2\
\xa9\x13\xc8\xec%\xf9\xd1\xb9\xff\x076\xde)"\x9b\xfa\x18\xa3pSx\xce\x12\x16U\
\x95S1;\xc4\x84\xa0\x86\x95\x85\xab\x03&\xe7/\x0e\xd1\xd4\xd0B\xac\xe3w\x9b\
\xe4\xf0\xe7\xf8\xad\x1dD\xf7\x8c>\x18\xec\xdbQA\xd6>d\x94//{~\xeb*^Z\xe7\
\xa3l\x02X\x16\xa4\xd2\x90\xb5\xdd\xdf\xcc,\\\xec\x81/\x0e\x0fs\xf2\xdb:\xac\
\x9es\x8d\x08\xf99\x92\x1f\xf4\xde\x0b\xd6\xdf\x9a\x8c\x90\xeb#\x8bk\xa7\xec\
~w\x05\x1b\x97\xc0\xf5a\xe8\xec\x87\x84\xe9B%\x01\xb2\x04\x92\x04>\x0f \xc1\
\x81S\xb0\x7f\xdfQ\x92\xad?6b\xa4kng.\x8f\x83\xe5\xaa/\xfd\xb3k\x9ex\x7f\xf7\
j\xd6/\x82\xd6^\x18\x8aA&\x0b\xaa\x02s&\xbb\x1bD\xe3\x90\xb6 \x96\x82\xb1\
\x14\x94O\x02+8\x93\x8e\x8eh\xb1=\xd8\x17${\xe6\xfb\x1cX{s=y\xa5;\xb7m\xdf\
\xcc\xd6U\n\x17\xba`d\x0c\xcc\x0ch\n\xd4TBI\x18\xf2\r\xf8\xe3\xb2\x0bN[\xee|\
\xd2\x84\xe20\\1\'1\xd8\xd1\xb4\x001\xff\x08\xd6\x99k\x12\x00\x92\xf2Z\xc9\
\x82\'\xd9\\\xa3\xd3\xda\x0b\x83\xa3\x10K\x82*Cu\x05\xf8u\xf7P\xcd\xdd\x16#\
\t\x88\xa7r1\x9a\x84\xac\x05\x15s\x83\x18eU\x12B\xbc\n\xa0\x90\xb7+\x84\xaa-\
\xadZV\x8e\xae@{\x8f\x9b\xcd\xa4\x10<\xf3\xf8\xadZ\x02G\xcf\x9a\xd4\xfd\xa9\
\xa0(DN !\xb9\xb5\x8f\x04 8}6\xa9\xaeS\xab\xed\xfc]\x86\x84\x9c-\x92\x0b\
\x1e)\x985=\x9f\xe6+\xd0\xd2\x0b\xb2\x80\xb5\x0bs\xd0\x86\xb64\xbf]R\x08\xe5\
\xc9\xe4\xfb\xdc\xef\x86\xc7\x15q$\x01\xa3cn\xd6y\xe1\x08J T\x82\x99\x9d\xa2\
(\xaa\xc8\xf3\x04\x82\x08Y\xe2|\xa7\x9b\xcd\x96\x95\xe0\xd5r.\xac\x9c\xa6\
\xf1\xd8\x8c\x9c\x85l\x07\x1c\xc7u\xca\'u\xd0\xd8\xe1\n,\xab\x1a\xb2\x91\xaf\
)\xe9\x1b\x11\x05\xc5\x8b\xeaQH\xa4\xe1\xea0\x94\x84\x9c[5\xcd9\xd1\xa3\xdes\
\x8d\xc6G\xd8\xef0\x14\x17\x8ce \xed\x80\xeaQqdM(B\xf7\xc4!\xcdX\xc6\xe1FR\
\xd0\xd9\x01\xef\x1d\xcc\xb0s\xb3:\x0e\xafo\xcep\xa6\xdd&\xe0u3\xb5\x1d\xb0m\
\xd79\xc7\x9b\x15F\x922\x08\xd0=\x16\x02+#k\xc6\xb0\xe2\x91\x94\xeb\x96\x19\
\x8b\xdf\x8c\x8d\xf9#!\x1f\xe9a\xc1\xa1\x8b*\xba\xd7\xe2\xedZ\x05\x10TNU\xf9\
\xba\xc1\xe1d\x03x\x14\x17|[>\x8f\n>?h*\x8c\x0e\xc6\xb0m\xf3zBR\xba\xe5t\xf4\
\xd8\x98Z\xb8n\x8d\x11\x998u\xda\x8c \x89\x0c\x18\x86\xa0\xa5_b4aQ5]BW\x05\
\xd5s\x05\xdd\xc3\x82aS\xe0\xf7\t\x0c\xaf\xc0\xf0\x82\xc7\xe3F\xc0\x0f\xfd\
\x1d\x9d\x8c\\\xeb:\x9cn}\xe3+\t@\x92\xe5\xbdW\xda:\xc8:6\xc5\x110|\x10\n\n\
\xea\xfeV\xd8{\xca\x02\x1c\xbc*\xbc\xb8\x14\xbc>\xf0\xdd\x11\x86\x0f&\x86\
\x01\xcb$\xda}\tY\xd3\xf6\x8d\xdf\xbc\xf4\x8a-\x7fI}\xb1Uh\xde\xd2Ys\xc3\xa8\
282\x18\xba\xa0\xfd\x86D<i\x111\xe0x\xbb\xc3@RB\xd7AUA\xd5 \x92\x07\xba\x0eM\
\xbf63\xd4\xd3s`\xa4a\xdb\x87wI\x1f\\\xb9\x7f\x9e"+\xf5\x8b\xd7,-X\xb4\xa4\
\x98t\x06FR`\xd9`e\x1ddll!\xa1H\x02\x07P%(\xf0\xba\x0f\xd1\xe9\x9f;i\xfa\xa5\
\xf1\xb2\xb0\xa5\xe5C\xf5\x1b\xfb\xee\xf6\x14\x10\xae\xf9\xb6ZQ\xa5\x83\x95\
\xcb+\x82\xcbV\x94R\x10\x90\x183!\x99\xc9=\x99\x8a\x04\x86\x06\xba\x06\x83Q\
\x8b\x93?u\xd2z\xb6\xb9[\xe0\xd4\x0e\x9c\xd8\xd0\x94\x93\xf5_c\xe2\xd3\xdf\
\xcds$>-,-Z6\x7f\xe1d\x1e\x9dY@8_Cu\xfb\x07f\xc6a(j\xd2\xd2v\x93\x0b\xe7\xba\
\x88\xf6\r\x1dV\x85\xf5\xfa\xb5\x1f6\xf4\xdc\xc9\xb9\x7fk\xda\xf4\x8d\\\x98\
\xf0\xbf \x84\xf4\x8a\x11\xf0.,\x08\x05\xfc\x86O\xc7q\x1c\x12\xf1$7\xa3\xb1\
\x91d<u\x1a\xf8l\xe0\xc8\xb3\x87\xee\x87xp\xcf\xbb}\x82\xda\xba2\xdb\x16\xe5\
6v\x04[vd\xd9\xe9W-\xab\xed\xea\xb1\xb5\xbd\x0f[\xf7\x0f@\x01\xd7\x0c\xb0\
\xdfs2\x00\x00\x00\x00IEND\xaeB`\x82'
get_bp_btn1Image()
def images.get_bp_btn1Image ()
Definition at line 717 of file images.py.
References get_bp_btn1Data().
Referenced by get_bp_btn1Bitmap().
def get_bp_btn1Image():
    stream = cStringIO.StringIO(get_bp_btn1Data())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_bp_btn2Bitmap()
def images.get_bp_btn2Bitmap ()
Definition at line 775 of file images.py.
References get_bp_btn2Image().
def get_bp_btn2Bitmap():
    return BitmapFromImage(get_bp_btn2Image())
get_bp_btn2Data()
def images.get_bp_btn2Data ()
Definition at line 722 of file images.py.
Referenced by get_bp_btn2Image().
def get_bp_btn2Data():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x16\x00\x00\x00\x16\x08\x06\
\x00\x00\x00\xc4\xb4l;\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x04\xb8IDAT8\x8d\x8d\x94Yl\x94U\x18\x86\x9f\xf3\xaf\xb3\xb43\x9d\xa5\xed\
\xb4\x82-X\xdaR\xa0\x0b["!\r\x18\x13 \xc1\xe2B\x04\x12\x83 7\xb8\x05\x134\
\x1a/$\x90\x10\xe3\x85\x17.Qbb\xc0h\x0c7"\x11\x13$QjP\xa4\x91U@\xec\x02-]\
\xe8:3\xedl\x9d\xce?\xf3\xff\xbf\x17\x83\x05\xd4\x8aor\x92\x93\x9c|\xef\xf7\
\xe6=\xef\xf7\t\xfe\x17\xf6(0\xa4\xe5\xefe\x06\xec\xcd\xdd\xafB\xcc\xf8\xe2\
\xdf\xe3!1\xfe\x04\xc8\xeb\x91\xf5\x05\xc8\xaa\x17\x003\x1b\xc3\xcc\xfc\x0e\
\xd61\n\xad\xa3D?\x88\xff\x7fb}\xd76\x84\xe3-QR=\xe7\xc1\xba\x85\xcc\xab-\
\xa7\xb4\xd8\x85e\xc3\xf0\xc8$]\x1d\x83\xdcj\xbf\x8a=\xd6\xd1\x83\x95\xd9G\
\xe6\xbdC\xf7!\xde\xa3\xe0\x88\x1d\xa0\xb0rG\xe3\xbau\xec\xd8TM\xf3"\xf0\xba\
\xc04!g\x82a\xc2h\x1cN]\x81\xc3_w\xd2\xd1z\x1c\xe27?e\xca\xbb\xf3n\x8b\xe4{\
\x956\x1d\x94B\r\xdb\xb7\xed\xde\xca\xfb\xbbC,\x9c\r\x83\x11\xe8\x1d\x85\xfe\
0\x8cL\xc0D\x12,\x13\xaa\xcba\xc5\xb2\x00\x13\xeezzz"\x8b\xedto%f\xdb\xd1\
\x7f\x12\xeb\xaf\xbc\x8co\xde\x1b;^{\x86}\xdb\\\xc4\x92ps\x14R\x19HNAY\x11\
\xd86\x84\xe30\x95\x85\xf1\x14\xd8\x16\xd4W\xa9D\xb4\x1a\xfa\xba\xfa\x1a0\
\xaa\xa3\x98m\xbf\xde!v\xbeX\x8e(8\xfc\xf0\xa6-\xae\xb7_\x082\x14\x81\xfe\
\x08X\x16\xc4\'!\xe4\x83G\x16\xc1\xdcR\x18\x89\xc1\xad0\xe4,H\x1b\x90\xcb\
\xc1\x03\xa5*]\xb1\x12b7./E]\xf2\x05\xd9\xb6\xa4\x04\x80\xadn\xd5+\x9a\x82\
\xcf=]A"\x05\xdd#0e@8\x01\xbda\x18\x0c\x9b\xd8\x96\x8d"\xc3\xda&\xa8(\x81h\
\x02\x92i\x98H\x81*A\xc3\xe2\n\xb4Y\r\xc5Xb+@\x9eXq\xb5\xd4.k\xa0v\x16\xb4\
\x0f\xe4\x95\xc4\xd3y+\x12i\xf8\xadW\xe2\xf3\x1f\x0cL\xd3F\x96`\xc3r\x98W\
\x9eo\x1cOC,\x05\xe5~(\xaajD8\x9c\x1b\x00\x14|\xaf{\xd1\xbc5\x0b\xeaB\x8c\
\x8e\xc3\x1f\x03y\xcbU%\xafZ\x92@Q\x04\x17\xfb5\x94SY6\xafR\x91%\xc1\xe6\x95\
`\xe4\xe0L\x07hJ\xbe\xa6\xb04\xc4\xb8\xcb[\x93U_\r)\xb8\xe5\x02E\xf5\x14x<\
\x0e.v\xc3`\x14\x9e_\x0b\xf3g\xdd\xfe]\xe9N2MK\x03;\x1fRI\xc0\xb3\xab`,\x06\
\x97z@Q@\xd5\x1d\xc8nO\x01\xf1D@q\xda\x1ea\xe9\xba0\x91\xe8\x8b\x80$\xdb,\
\x99\x0b\x9a:\xf3PN\xb7\x12\x10(\xb4\x89\xa6\x04\x93Y0\x85\x84\xa2\xe9\xc2T5\
I\x91\xdd\xca\x14\xb2\x95\x994\xb2j\xd4P\x18\x1e\x17\xbc\xf9\xa5Ac\xa5\r\xe4\
\x95IB\x90\xc9\xd9\xb8uhY\xae\xa1)\xf9\xa6\xadWr\x1c\xfcI\x90\x98\x92\xb1\
\x01]\xcb"\xc9VF\x92\xd5\x84\x92,\xec\x8c9\xd3M\x03\xd1\x89d\xad\xbf\xdcI$\r\
?\xde\xd08\xd9e#D^\x95m\x83K\x87\xfd\x1b\x99&=\xdd\x9ec\xef7\x02C\xc8\xb8\
\xdd\xa0\xaa\x10\x1bNb\xdb\xd9\x81\x8c\xea\x1a\x928\xffIV\x92h\x1d\xe8\x1b\
\xc4\xeb\x01\xaf\x07\xfc>\x08\x06\x04\x01\xbf\xc0\xe7\x13\x94\x95\x08\xde\
\xd9"h\xae\xcd\x93\x9e\xed\xce\xb1\xff;\x81\xec\x90\xf1z\xa0\xb0\x10\x8a\x8a\
`j|\x10\xcb\xa6\x95\xeb\xbb2\x12\x80\xac+\x87\x86\xbb;\xedx2\xcd\xecRp\xb9\
\xc1]\x90?\x9a\x03\x9aka\xc5Cy_/\xf5\xe5x\xb7U\xa08e<\x1ep\x15@I\x00\xecl\
\x9aho\xa7-\xcb\xca\xa1\xe9\xc9\xcb\x0c\x1d\xbb\xa5\x95\xb6TfL\xa5q~}\x08\
\x87\x0e\x96\x04\x9a\x06\xba\x0e&\x16\x95^\x8b\x1ba\x8b\x8f\xdb\x049Y\xc6\
\xa9\x83\xaaA\xd0\x03\x0e\x07\\>}\x8d\xe8\xc0\xe0g\xb1\x0b\xdb?\xbagW(U\x1bO\
\xa7\xc2\x13-\x96\xe2\x0c\xd6\xce\xf7Q\xe4\x06[\x06E\x03\x03\xc1\x99~\x9b\
\xf3\xc3\x12\x92&\xa3\xeb\xe0r@\xa8\x08\x9cN8\xf7K7\xdd\x17\xae\xb6\x1b\xaa\
\xbd\xc5\xe8=2\x99\x0f\xe7]\x08\xac>Z#\xcb|[\xbd\xac\xae\xaayu%%\x01\x95\xb4\
q{\'X\xb7\x05H\xe0\xd2\xc0\xa1\xc1h4\xcb\xa9\x937\xe9<{\xed\xbai\xb2>\xd2\
\xfax\xc7\x9d\xd4\xff\r\xc15_\x95ai\x1f\xfaC\xfe\'\xeb\x97\xce\xa1\xae\xc6G\
\xd0\xafO\xe7\xda\xc8\xda\x84\xa3\x19\xaeu\x8cs\xf9\\\x0f\xd1\xe1\xe8\x11$\
\xe3\xa5\xf0\x89\xa7\x86\xee\xc9\xf8L\xe1/^s|\r\xb2\xb4\xd3\xe5VWz|\x05Aw\
\x81\x13\x80T2M|<\x19\x9eLe~\xc6\xe4\xc0\xd8\x89u\'\xfeuxf"\xfe\x0b%\x8f}_j\
\xe7\xcc*\x0b\xbb\x18@B\x8c\tE\xbe>z\xec\xd1\x91\xff\xaa\xfb\x13)}\xd4EY\xc6\
\xa7X\x00\x00\x00\x00IEND\xaeB`\x82'
get_bp_btn2Image()
def images.get_bp_btn2Image ()
Definition at line 778 of file images.py.
References get_bp_btn2Data().
Referenced by get_bp_btn2Bitmap().
def get_bp_btn2Image():
    stream = cStringIO.StringIO(get_bp_btn2Data())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_bp_btn3Bitmap()
def images.get_bp_btn3Bitmap ()
Definition at line 832 of file images.py.
References get_bp_btn3Image().
def get_bp_btn3Bitmap():
    return BitmapFromImage(get_bp_btn3Image())
get_bp_btn3Data()
def images.get_bp_btn3Data ()
Definition at line 783 of file images.py.
Referenced by get_bp_btn3Image().
def get_bp_btn3Data():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x16\x00\x00\x00\x16\x08\x06\
\x00\x00\x00\xc4\xb4l;\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x04\\IDAT8\x8d\xb5\x95[lTU\x14\x86\xbf}93\xd3a\x98V\x18-\x97^(\x08\x8a\xe1R\
n&-\xb1@\x94\x07\x05#%&j4&*\xc6\x07\x85\xc4HT0\x88\x08\x0f\x92\x90\xa8\xc8\
\x83\x11\x13\xf1\x82\xc6\x10\xf0\x16\x08\xb1&\x16\x1f*$\x96T\xaa\xa8\xc5\x96\
\xd2N[:\x9d\x9evf:\xd39\xd3\x99\xb3}\x18JhK}c%;\xd9\xc9\xca\xfa\xf6\x9f\x7f\
\xad\xec%\x8c1\xdc\x8a\xd0\xa3\x17\xef\xc63u\xa1\xa9\xbe\xfb\x1c\xa3\rJ\xc9\
\xa4#\x87\xd3X\xfb\xf0\x15\x1c\xc0*\x00\xcb\x07\xd2\x02!\xf2\x059\xf1\x0cZ\
\x1d@\xe9\xa0\x14\xc2h\x85\xc9\xba\x9c\xcf\xbdO\xd5\x18\xb0%t\xf5\xebO\xcd\
\xf1\xde\xb3h\x1a\x7f\xdb.\x17\xdb\x1c\xcf\xd1\x1f\xfa\xf6\xc7\x92\xb92,\xb6\
\x01p\x8dI\x96]EA\xf9\xa6\xd1Z;9A\xe9\x1d\xf9T[7\xcbGyr\xf4\x92t\xe5\x9eC\
\xc7#\xd9x$\xcd\xda\xf9^\x96\xdc\x15\xa4\xf6\xc1\xd9rz\xc8\xbf\x95\x11\xf7\
\x04\x00\x06\x18\xe1\xc3\xb9\xc5jO\xf9\x0cK\x0b%\x98S\x0c\x1e\r]\x11\xdcl\
\x8ewGyb\xd4cQ{\x0e\x1c\xfdX0Ppd\xd7\xd3\xb3|+\x96\x16\xf1S+4\xb5\xe58\xdb\
\x94\xc0\x1e\xa2\x0e\xedI,+\xb7j\xfdS,\xd1|\x15\x8ao\x03c\xa0\xa3\x87\x91L\
\x8e\xedH\x0e\x9a\x83\xe3<\xc6\x00~\xf5u<+\x86\xde\xf8\xcc>\xfa\xf2\xa3\xb2p\
\xed\xca \xd1\xb8bfi\x10\xa7+\xb3\xde\xa0H\xb8\x16\x97{!T\x04\x99\x11\xe8\
\x8c\x90r]^@\xf2\xc5M\x9b\x87\x94y\x13\xbd\xf2d\x06u\xef\xfe\xe3\xc9z;\xa5fn\
X\xed\'\x1a\x97\x84m\x1f\xa94t\x0e\xc2\xec\x10\xa4\x1d\xe8\xe9c\xc0\xc0F$\r\
\xd7\xfd\x1f\xef1\x89~p\x92 \x14xd\x0b\x05\xba\xeap\xddH\xcbG\xa73<\xbe\xdc\
\xb0\xaa\x02r&\x0f\x8d\'\xa1\xbb\x8f.#\xa9A\xd1\x80$_\x1b\xef\xbb\x89\xe2\
\xd1D\x7f;\x94,\x01\x9d\xbd\x82w\xfa\xb2S\x8d\xa2n\xd0\xa1\xfa\xb9\xfb!T\x08\
\xdf\xff\x06\xa9\x14\x17P\xac\x83\x9c\x8d\xe3@\xbc\x1b\xdc\xec\xb5Q\xbc}\xbc\
\x15\x1a\x8c\x0b\xc3\th\xfd5o\xcd\xcc\xc5)JV\xadih\x11\'\xe2\x0e\x0f[\x1eH%9\
\x83r\x1f"i\xa7H\xf6\xc3p\x1c\xb4\x07\x94\x07\xb4u\x13\xc5\x98\xfc\x8bB\xe6\
\x8f\xb2 z\t\x94\'KY\xe5\xa6?\xba\xd8\t\xf8\xb1x\x9bhG\x9aX8/F{\xaf\xd5\x8c\
\xf5\xf8\x0605$3\xb5d2\x02\x8d\xc2+\xc3\x04\xbc\x87\xb1[m\x94v)Y\xb4\x0f\x80\
\xdeVH\xf4\x80\xd4\x01\x10\xcf\xe2\xe6\xe6cd\x0e\x0c(N\x01?\x8e\x01\xfbq\xbe\
[\xbfi^\x91\xb2<\x0c\xa5\x05\xed\x9dqZ\xfe\xb1\x9f\xc0\xef}\x80\xc1\xce(R\
\x81\xd2\x90\xe8\x05\xa1\xa5p\xcdI\x11\x08\xd6\x18o\x90\x80_Q\xe0\x15\xd8vz\
\x0b\x10\x18\x03N\x0f\x0e\xf4\x97\x17W\x14m}q\x15\xe1!A\xe3_\x19\xbe\xfa\xf2\
\xc2\xd2\xc6sW\x9a\xd0r#C\x91&\x94\x06WUx\xa4{\xba\xec\xce\xe2\x05\xfd\x05\
\xe5h\x9f\xa64\x04v\xcf }v6>a\xdc\\\xa8>x\xe8\xfc\xc5\x9d{\x1b\xf0\x99\x0c\
\xb3\x8a=\xd4lXI\xe5\x9aE\xb3\x05\xa6\x1e\xc42\x8c,\rxiX\xb1\xbcd\x81\t\xcdE\
y5\xb3\n]\xae\xb6Gio\x8bu\x18\xc4\xea\x89sl\xe9\x08ES\xaa\x8e\x1dk=\xbbc\xf7\
YBV\x8a\xbbK\xa1b\xe9\x02**\x17\x16b\xc4/\n\xd3\\YY>\xc3\xf6\x95\xd1\xef\x08\
\x8a\x03Y\xc2m}t\x87\x87\xfeD\xabj\x84\xb8<\xb1yR\x80W\xc7\x81\xaa\xfa\x9f{\
\xbf\x1d\x18n|d\xcf\xab\x95\xac]<\x95\x8eh9\xd3r\x81\x80\x9314%C\xf8\xfc0#\
\x90!\xdc\x1a%60R\x8fV\xeb\xae\x7f\xa7\x13\x14C\xfeG\x11@\xd0\xda\xf4{s\xe2\
\xe3\xedo5\x9b"\x13\xe3\xc9\x1a\x10S\xa7\x93T!\xfc~(\xb4\xd2t^\x8a\x10\x8be\
\xbe\xc1\xa3\xd6!\xc7\xcd\xda\x04\xf0\x8d\xe1\xd7\xcf\xff{\xc5\xd9\xfd\xca\
\xbe\x96\xacL\x0c\xb0c3,,\x07O6I\xb8%\xe2&\x93\xd9\x0fPj3\x93,\xa0\xc9\xc1\
\x00\x01\xbd7\x1aw\xb7\xec~\xaf\xd3\x89\xf7\x0e\xb0f^\x92pk_\xd6\xc9\xb8\xaf\
\xa1\xe56\xfeg\xad\xe9I3\x90\xb7\xc6\'?\x8d\xb9\xd2~\xe7H\xf4\x13\x8f\xcf\
\xb2\x10\xe2%\xa4\xf8|2\xa5\xa3!n\xd52\xfd\x0f\xde]\xc0!W\x86\x86C\x00\x00\
\x00\x00IEND\xaeB`\x82'
get_bp_btn3Image()
def images.get_bp_btn3Image ()
Definition at line 835 of file images.py.
References get_bp_btn3Data().
Referenced by get_bp_btn3Bitmap().
def get_bp_btn3Image():
    stream = cStringIO.StringIO(get_bp_btn3Data())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_bp_btn4Bitmap()
def images.get_bp_btn4Bitmap ()
Definition at line 893 of file images.py.
References get_bp_btn4Image().
def get_bp_btn4Bitmap():
    return BitmapFromImage(get_bp_btn4Image())
get_bp_btn4Data()
def images.get_bp_btn4Data ()
Definition at line 840 of file images.py.
Referenced by get_bp_btn4Image().
def get_bp_btn4Data():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x16\x00\x00\x00\x16\x08\x06\
\x00\x00\x00\xc4\xb4l;\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x04\xb5IDAT8\x8du\x95[l\x15U\x18\x85\xbf\xbdg\xcf\xcc\xe99\x96Rl\x01+\xa5\
\x08\x14\n\xa5\xb55@\xaa4\xd6\x98H\x1411\xc4\x18M\x94\xa8\x18%>\xa8\xf1\x12c\
4\x9a\xa81\x06}0\x9ahD\xc3\x9bAn\x89\x06\xbc\xa1&4\x12\n(Bi\x83\x15\xb0b\xa9\
\xf6B\xaf\xf4\x9c\xd3sff\xef\xed\xc3T\x0b\xb4\xfeO3\x93\xd9+k\xad\x7f\xad\
\x19a\xad\x05@\xac\xdc\n\x00\xda\x82\x14 \x01cA\x08\xb0\xa0\x948\x94\x90\xb2\
.=2\xfe.\xae|\x05)"\xb0 \x9d\xf8\xdd\x9c\x06Wb\x8fo\x06\xe2G\xff?\x16\x88\
\x0cD\xda\xf3|\xb5\xf4\xed-k\x0b6\xdc\xb3\xe2E\xb4\xed&\x1f=\x8c\xb1\xff{tz`\
\x01\x08$\xc6\xce!2\xe5D\xb6"\xc8FvFi\x11\x9b\x9e\xbf\x85\x97\xb7l\x98\xb3\
\xb8v\xfe6B{\x92 lD\x88\xf8\xcc%\xa3\xa6\xa1\xa9\xc8\xe9\x97\xc0<\x94,\xf4\
\xae.H\xb8\x8e\xd1\x16\xdfU\x05\xa7{,&\x0b\xc9\x05\xd7\xb0\xf1\x85\xf5\xfcr\
\xf0\x8f\x9a\xc3_\x1fk\xee=\xd7w\x00+\x1e\xc5\x91\x7f\xfc\xc7\xed2\x8f-\xb3\
\xc9\xe5\x9b+W\x94U\xad\xbe\xad\x86\x19sJQ\xae\x8b\x9d\x90&\xbd$}Y\x19{\xeeB\
A\x12t&O_k\x07\'\x9a\xdb\xf2\x7f\xf5\xa5\xb7\x9a_6?y%cE>\xdf\xbcdMMU\xf5\xba\
5\xf4\x87.]\x17AN\x98%\x04\x14\x02\x83\xe3\xf1n\'\xf8\xe0\xf8>%\xf5\xd7S\x93\
H\xf8\x03\x9f5?\x0e\\\x01\x9c\x0f^\x9b\xb5`^U\xf5\xba\x9b\xc9E\x92\x84\x03\
\xb9\xd1!\xc6\x86\xc7@\x80#\x05%\x0b\xcb\x98\x91T`\xc0K\x80\xf2`\xb0{\x98\
\x1f\xf7\x1e\xe7B\xc7\xd9^\xe1\xd8g\xa7z,\xe4\xfd\rkkYV!1\x06Z\xf6\xb5\xd2\
\xf2yK\x10i\xdd\x8fE*_\xcd]\xf9\xea\xbdr\xe1\xdcb|\x17\x86\x07\xb2\x1c\xfd\
\xbe\x9d\xd6\x03m\x99\xfc\xc5\xf4\x87\xb8\xee\xf3VNf\xe1?\xe0\xc2\xc2DY\xc3\
\xca\x99,\x9a\x07\x9dg\x87\xf8\xe9\xcb\xa3&\x8a\xccz\x12\xeewh\xeb\t\xa5\xba\
\x97T\xb8\xa5\xc5%\x86o\xbf\xf8\x95\xfd\xbb\x8fG\x83\xdd\x83\xbb\xf0\xdd\xa7\
\xf1\xbd\xfe\xc98]\x01<\x1ej\xfd\xc9\x96\xef\xf1<e\xd3\x99\xbc\xc8\x86\xa6\
\x1f_}\x87\x05\x8c\xc5\xf5\xa4\xf3\xe7\xa9\xf3l\xfb\xea7\xdbv\xb8\xeb(\xbez\
\x94\xa4\xdf\x8e1\x93\xa5\xba$r\x97\xa4\xe2\xa3&\xd2\xc1lB\xa3\xf1\x94K\xca=\
\x87\xe0\x089\rJ\x82\x12\xef:\x81n\xd2\xb9\xe8-R\xee\x0e\x98hg`@\x9b\x18\xd8\
w\xb0??>%\xc7\xcd82\x8e\x81\x92\xf1\xdaM\xcc\x96 \xaa\'\xa0J\xfb\xaa\x99\x94\
\xbf\x031QuX\x821\x15h\x13a\xa5\xc22\x04\x1c\xbb\x1c\xd8\x02\xae\x13_H\x11\
\xb3\x08\xa2\x99\x04\xe6\xfdy\x95%\xf7\xddvW\x95\xda\xb5\xb3\xbd1=<\xfe\x06J\
\x0e\x00`\xec\xde\xa2\xd2\xd4\xe2T\xca\xb7\x916bh0\x9b%N\xe5\xa5\x8cE|g\x00C\
\x82\\\xf8\xa2_\x94|\xb6\xe9\x8e\xea\xd4\x86\x07\xea1\x06\xb6\x7fz\xd2\xe0`\
\x90@\xa8\xafq\xb5\x99\xbf\xe9\x99u\xb2nU9\x7f\x9f\x1f\xe1\x9d\x17\xf6\x16L\
\x8d\x1b\xff\xca\x0e\x1e\x91J\xbd\xbe\xb4\xa9\xba\xac\xf1\xce\x1b(\xbf\xae\
\x98\xbf\xd20\xdas\x11\x9d\x0bR\xe4\xc3\xc3H\x11b(\xafY{}"YVN\xe7\x058}f\x9c\
\xe1\xd1\xec\xe84\xc0\xf6&B\xfb\xe1\x8c\x8a\x8a\xda\xea[WR\xbe\xecZF\x0c\xf4\
v\xc4b\x92\xa2\x80\xba\xbbo\x95Qd+\xad\xb5\x14\x14]\xc5\xdc\x85e\xb4\x9e\x83\
D\x12Z\xbelG\xe7\xc3\x1f\xa6\x00{\x8e\xfd\xa6\xf1\xbe\x1b\x0bS\xb5u\x8c\x8eA\
w\xdf\x84\xef"\x162\xab\xc0%UY\x896\x13\xe2L\\\xef\xe2\x94\xe5\xcc\x81\x13t\
\xb7\x9f\x19\xc0w\x9f\x9a\x02\x1c\x86bg\xe7\x91\x8e\x8d\xf5I\xe5VV-\xc5&\\\
\xb2\x190:\xb6}n\xd2\xe2\xba\x01\xdaX\x84\x00\x13Y\xc6.\x0c\xd2\xf6u;\'\x0f\
\xfd>\x88r\xd6#D\xcf\xd4\x1c\xd7\x7f\x04\xb9p9\xc2|<\xaf\xb2\xac\xa1\xe1\x8e\
Ur\xc5\xear\xa4\x92dr\xe0\x8f\xa7\xd9\xf3\xde>r\xf90\x90\x8e$3\x1e\xd9\x9e\
\xfeL\xda\x06z?\t\xef\t\x1c1\x82\x05\xfb\xf3c\xd3,\xcf\x95\xa7\xf0\xbc5\xddg\
{\xd7\xee~o\xdf\x07\xed7,Xt\xef\x83\xabhX=\x9b\xb1>8\xdd5\x96\tGr\xb7c\xec\
\x00\x9e\x03)\xb7\x0b\xc7\xc92\xcd\\\xfe\x07\xb1\xc4\xc5\xf0\xd5~\x1c\x16w\
\x1c\xeb|\xf2\xf5\xe7\xf6\x0cm\x7f\xff v,M"\xe5BRu\x90P\x1d8\xa2\x03\x98\x16\
t\xaa\x15\x91\x06\xcf\x89\xb7eL\xdc.m\x92D\xf6\xcd\x99%\xa9\xcd\x99Pw\x87\
\xa1^\x0e"@\x9b\xc9\x86\xc2\xc4Gz\xd2\x8a\x7f\x00E\xb8\x1e\xc0\xd9\xc98\xaa\
\x00\x00\x00\x00IEND\xaeB`\x82'
get_bp_btn4Image()
def images.get_bp_btn4Image ()
Definition at line 896 of file images.py.
References get_bp_btn4Data().
Referenced by get_bp_btn4Bitmap().
def get_bp_btn4Image():
    stream = cStringIO.StringIO(get_bp_btn4Data())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_alignleftBitmap()
def images.get_rt_alignleftBitmap ()
Definition at line 200 of file images.py.
References get_rt_alignleftImage().
def get_rt_alignleftBitmap():
    return BitmapFromImage(get_rt_alignleftImage())
get_rt_alignleftData()
def images.get_rt_alignleftData ()
Definition at line 191 of file images.py.
Referenced by get_rt_alignleftImage().
def get_rt_alignleftData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00BIDAT8\x8dcddbf\xa0\x040Q\xa4\x9b\x81\x81\x81\x85\x81\x81\x81\xc1\
\xc7\xdb\xeb?9\x9a\xb7l\xdd\xc6\xc8H\xa9\x17Hr\xc1\x96\xad\xdb\x18\xd1\xc5\
\xe8\xeb\x02l.\x1a\r\x83a\x11\x06\x14g&\x8a\r\x00\x00\x90v\x18Pe\xb5\xde\x18\
\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_alignleftImage()
def images.get_rt_alignleftImage ()
Definition at line 203 of file images.py.
References get_rt_alignleftData().
Referenced by get_rt_alignleftBitmap().
def get_rt_alignleftImage():
    stream = cStringIO.StringIO(get_rt_alignleftData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_alignrightBitmap()
def images.get_rt_alignrightBitmap ()
Definition at line 216 of file images.py.
References get_rt_alignrightImage().
def get_rt_alignrightBitmap():
    return BitmapFromImage(get_rt_alignrightImage())
get_rt_alignrightData()
def images.get_rt_alignrightData ()
Definition at line 208 of file images.py.
Referenced by get_rt_alignrightImage().
def get_rt_alignrightData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00<IDAT8\x8dcddbf\xa0\x040Q\xa4\x9b\x81\x81\x81\x85\x81\x81\x81\xc1\
\xc7\xdb\xeb?9\x9a\xb7l\xdd\xc6\xc8H\xa9\x17X\xb0\t\x12\xeb"\xea\xb9`4\x0cF|\
\x18P\x9c\x99(6\x00\x00\xd0g\x18P\x14m1\xc6\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_alignrightImage()
def images.get_rt_alignrightImage ()
Definition at line 219 of file images.py.
References get_rt_alignrightData().
Referenced by get_rt_alignrightBitmap().
def get_rt_alignrightImage():
    stream = cStringIO.StringIO(get_rt_alignrightData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_boldBitmap()
def images.get_rt_boldBitmap ()
Definition at line 233 of file images.py.
References get_rt_boldImage().
def get_rt_boldBitmap():
    return BitmapFromImage(get_rt_boldImage())
get_rt_boldData()
def images.get_rt_boldData ()
Definition at line 224 of file images.py.
Referenced by get_rt_boldImage().
def get_rt_boldData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00KIDAT8\x8d\xcdRA\n\x00 \x0c\xca\xad\xff\xff\xb8\xd65\x0c\x16cA\xf3(\
\xd3\x89\x08\x88\xb6\x0c$\xa5~a\xd0\x99\xb09\xcc\x13@\x14n\x02>\x80(v\x8e\
\x1f\x14\xec\x80\xc1\x91\xaf\x1d0\xeaw\x00\x9ert\x07\x87A\x14\xff;H\x1b,\xb5\
t\x14I\xb8\x7f\xfd3\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_boldImage()
def images.get_rt_boldImage ()
Definition at line 236 of file images.py.
References get_rt_boldData().
Referenced by get_rt_boldBitmap().
def get_rt_boldImage():
    stream = cStringIO.StringIO(get_rt_boldData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_centreBitmap()
def images.get_rt_centreBitmap ()
Definition at line 250 of file images.py.
References get_rt_centreImage().
def get_rt_centreBitmap():
    return BitmapFromImage(get_rt_centreImage())
get_rt_centreData()
def images.get_rt_centreData ()
Definition at line 241 of file images.py.
Referenced by get_rt_centreImage().
def get_rt_centreData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00BIDAT8\x8dcddbf\xa0\x040Q\xa4\x9b\x81\x81\x81\x85\x81\x81\x81\xc1\
\xc7\xdb\xeb?9\x9a\xb7l\xdd\xc6\xc8H\xa9\x17X\x909\xc4\xbad\xcb\xd6m\x8c06u\
\\0\x1a\x06#>\x0c(\xceL\x14\x1b\x00\x000v\x18P\x0f8\x82\xa8\x00\x00\x00\x00I\
END\xaeB`\x82'
get_rt_centreImage()
def images.get_rt_centreImage ()
Definition at line 253 of file images.py.
References get_rt_centreData().
Referenced by get_rt_centreBitmap().
def get_rt_centreImage():
    stream = cStringIO.StringIO(get_rt_centreData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_colourBitmap()
def images.get_rt_colourBitmap ()
Definition at line 274 of file images.py.
References get_rt_colourImage().
def get_rt_colourBitmap():
    return BitmapFromImage(get_rt_colourImage())
get_rt_colourData()
def images.get_rt_colourData ()
Definition at line 258 of file images.py.
Referenced by get_rt_colourImage().
def get_rt_colourData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00\xf6IDAT8\x8dcddbf\xa0\x04\xb0\xe0\x92\xf8\xc7.\xf6\x1f\x9b8\xd3\xcf\
W\x8c(|B\x9a\xdf\xb2\xf3\xe35\x98\x11\xdd\x0b\xb8l\xc6\xe5\x12\xac. \x05\x0c\
B\x03\x96T\xf31lm\xc8bx\xca%\x8a\xa1\xf8\x1f\x0b$\xd2\x90c\x02%\x10\xdd\xfe\
\x1a\xffg````\x99\xe5\xc0 \xf2\xfd#\x83\xef\x82\xf7\x0c\xba\xcf\x1f2\xb0\xfd\
\xfb\xcd\xf0\x98]\x81a\x83X0\xc3\xe5_Q(\x86\xc2\r\x80i\x16\x7f%\xc3\xf0\xea\
\xfd\x1f\x86\xff\xea/\x188\xbe\xfdc\x08\xeb\xf9\xcc\xf0of\n\xc3J\xe9 \x86\
\x9f?e\x19\x18\xfe\xb1b\x1a\x00\xd3\x8c\x15|\xe2e\xf8\xe7\xbd\x96\x81\xe93/\
\xc3\xbf\xbf\x98A\xc6\x84W3\x03\x03\xc3\xff\xb7B\x0c\x0c\xffp\x875\xe1X\xf8\
\xcb\xcc\xc0\xc0\xf2\x13\xab\xedD\x19\xc0(\xfa\x96\x81A\xf69\x05.\xe0\xff\
\xc8\xc0h|\x1e\xb7\x05\x04\x03\x91\x81\x81a\x17\xf3YF\x17\xad?X\xd5\x00\x00\
\xac\x08RO\x1e0;\xef\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_colourImage()
def images.get_rt_colourImage ()
Definition at line 277 of file images.py.
References get_rt_colourData().
Referenced by get_rt_colourBitmap().
def get_rt_colourImage():
    stream = cStringIO.StringIO(get_rt_colourData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_copyBitmap()
def images.get_rt_copyBitmap ()
Definition at line 300 of file images.py.
References get_rt_copyImage().
def get_rt_copyBitmap():
    return BitmapFromImage(get_rt_copyImage())
get_rt_copyData()
def images.get_rt_copyData ()
Definition at line 282 of file images.py.
Referenced by get_rt_copyImage().
def get_rt_copyData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x0f\x08\x06\
\x00\x00\x00\xedsO/\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x019IDAT(\x91\x85\x93\xbdN\xc30\x14F\x8f\xed\xa4M\x80v(b\x00\t\x90X\xd8\x8a\
X\x80\xa9\x0c\x88g@H\xbc\x03O\x80J\xc5\xc0\xcc; !\xc4\xc4\x03t\x006\xc6n]3\
\x10\x06*\xa4RAE\xd3\x86\x81\xda\xc4IH\xeftm_\x9f\xfb}\xfe\x11B*\xce\xae\xdb\
1\xa9\xb8\xefU\x00\xe8\x9c\xee\x88\xf4Z2\xa4N\x96\xd76)/m0XX%P+\x00\x9c7\xd6\
\xa9_=g\xe0\xb9\x80\xaa\xa7\xa8\xf9.\x8b\xbeK\xcdW\xa6`\x16Dh\x0b{[u\xde\xbf\
"\xfa\xc31a\xd0-j\xca\xc5\xc9\x81\xb1\xe5\xe8\xa4\xe2\xfdu\r\x81\xd6\xf1>\
\x9d\x97O\xfa\xc3\x88\xb7\xc1\x88\xd7\x8f\x11a\xd0\xa5y\xd4\x00\xda\xb1\x86\
\x18@\xd53)yP\r\x06,\x88\xd9\xe5\xbb2\xc9\x03\xa0\xac\x04\xa4 \xad\xdbGklv\
\xcc\x97dz\x8a\xb9\x92\x82\xef\xb1\x81\x1c\xeen[v\xacjG\t<W\x90\xb8\x18\\%\
\x0c$J)\xd4v\x12\n\xb4\xd4\x89)R\x12`\n\xc9\x8a\xb6GJ&!\xd39!@\xc6\x85\x90\
\xec\xd1[\x80_\x05\xf9\x90\x14\xe0\xf2\xee)\xb3(\xa5\x80I\\\x08q\xc0~Y\x80\
\xf5\xb9fA\xfe\xb5\xd0\xbcy(rg\xe2\x07P\xd3Y\x1e\x1a\xf3j]\x00\x00\x00\x00IE\
ND\xaeB`\x82'
get_rt_copyImage()
def images.get_rt_copyImage ()
Definition at line 303 of file images.py.
References get_rt_copyData().
Referenced by get_rt_copyBitmap().
def get_rt_copyImage():
    stream = cStringIO.StringIO(get_rt_copyData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_cutBitmap()
def images.get_rt_cutBitmap ()
Definition at line 331 of file images.py.
References get_rt_cutImage().
def get_rt_cutBitmap():
    return BitmapFromImage(get_rt_cutImage())
get_rt_cutData()
def images.get_rt_cutData ()
Definition at line 308 of file images.py.
Referenced by get_rt_cutImage().
def get_rt_cutData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x0f\x08\x06\
\x00\x00\x00\xedsO/\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x01\xb0IDAT(\x91\x9d\x93AK\x1bQ\x10\xc7\x7f\xef\xa5\x17o\xee\xc1\xb8\xf4"\
\x98\xc6\xf4\xa6T<$\xa5\xde\xfc\x00\xb6\xd2J\x14$mO5\x82\xe0\x07\xf0\x13x\
\x10M\n\x1aP\x90\xe6 \x08\xa2&\x88\xc1`\x0f\xdd\xb8\xb4YvK[Z\xb6Y\xf1\xa6\'\
\xc9\xa1W_O\xbb\xecjZ\xc4\x81\xc7\xf0f\xfe\xf3\x9b\x99\x07\x0f!c\xf8\'?7\xaf\
\xde\xafo\xaap,\x9cs]\xf7VN\x12\xb2\xb8\x94|\xffj\xe38\x8e\n\xc7?\x19\r\x050\
\x90z,\xb8a\x11\xc0\xe2\xca\xb2\x88K\xc9\xdaZ)"*\x7f(\xdf\xac\xeb\x0c\xf0-\
\x95JR\xab\xd5\x14@\xb5RQ\x00\xaf&\'\xef\x06X\\Y\x16Wn\x8b\xdd\xdd=<\xefLU\
\xaa\x87\x00\x8c>{zk|\x80\x07\x9d\x82Z2\xc1H"\xc1\xc1\xc1\xfe?G\xff\xef\nWn\
\x8b\x8b\xcb\x0b\xf2\xb3\xef\xee\x07\xd0\x92\t\xf4^\x9d\xd5B\x91\xec\xcc\x9b\
\xfbM\xf0\xf9\xf0\x88\xa1\xc1A~}k\x12\x97\x1de\x00\x08!c\x00|\xa9\xd7\x95W\
\xda\x02 m\xd842C\xbc,o\x88\xedlN\xf9w\x80G\x0by\x9e\x0c\x0f\x07\x0f*\xfd\
\xe2\xde\xd7\x0bH\xef\x9c\xb6\xe5\x04\xc2\xb0o[\x0e\xd2;\xa7\xe7\xc5[\xacfSE\
\x00^i\x0bS\xd7\x988\xad\x0b5\xfd\x1c \xe8\xe2\xfb\x87\xb39&N\xeb\xc2\xd45~/\
\xadF\xdf m\xd8\\\xf7\xf7\x01\xd0\xfd\xa3\x85\xa9k\x91=M]\xe3O\xc3\x02\xe0\
\xba\xbf\x8f\xb4aG\x01\xa6\xae\xd1\xb6\x1c\xfc}\xbb\xa6\xc6#\x80\xae\xa9q\
\xd2\x86\xcdv6\xa7\xda\x96\x13m d\x8c\x9f\xc7\'j\'3\xa6v2c\xaaZ(v\xfc\x8d\
\xd5B1\xd04O>\x06\x9a\xbfO\xcc\xa84\xa1\x9d\xc6\x7f\x00\x00\x00\x00IEND\xaeB\
`\x82'
get_rt_cutImage()
def images.get_rt_cutImage ()
Definition at line 334 of file images.py.
References get_rt_cutData().
Referenced by get_rt_cutBitmap().
def get_rt_cutImage():
    stream = cStringIO.StringIO(get_rt_cutData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_fontBitmap()
def images.get_rt_fontBitmap ()
Definition at line 351 of file images.py.
References get_rt_fontImage().
def get_rt_fontBitmap():
    return BitmapFromImage(get_rt_fontImage())
get_rt_fontData()
def images.get_rt_fontData ()
Definition at line 339 of file images.py.
Referenced by get_rt_fontImage().
def get_rt_fontData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00\x8aIDAT8\x8d\xb5\x93\xc1\r\x80 \x0cE)\x8c\xa7\x0c\xc0\x81\xe9\xd4\
\xb2\x00\xcc\x87\x07\x82\x81JQ$6!$m\xfa\xda\xff\x03\x00R\x89\x99\x90S\xddo\
\x00\xeb\xb2\xc5\xcf\x80cO\xcd\xf9\x1e\x068W\xdfC\x00:\x95\xdb\x82\x05\xe4\
\xa9>X\xe8m\xd1\x04\xe4i\xb9\xb9\xb7\x05\xb4\xdeA\xcfy\n\x15 Uu\x101j\x8d\
\x91\xe6\xb5Ny\xc4\xbav\x93\xc0i5\xa6]\xaf\x00\x9cv\x1a\xa5\x17\x97\x07Tw\t\
\xe1<\xf1\xc1B\xd3\xc4\x91\xf8\xff3=\xc5\t\xa2\xed@\x80\nB\x85Z\x00\x00\x00\
\x00IEND\xaeB`\x82'
get_rt_fontImage()
def images.get_rt_fontImage ()
Definition at line 354 of file images.py.
References get_rt_fontData().
Referenced by get_rt_fontBitmap().
def get_rt_fontImage():
    stream = cStringIO.StringIO(get_rt_fontData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_ideaBitmap()
def images.get_rt_ideaBitmap ()
Definition at line 378 of file images.py.
References get_rt_ideaImage().
def get_rt_ideaBitmap():
    return BitmapFromImage(get_rt_ideaImage())
get_rt_ideaData()
def images.get_rt_ideaData ()
Definition at line 359 of file images.py.
Referenced by get_rt_ideaImage().
def get_rt_ideaData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x01[ID\
ATX\x85\xed\x97aN\xc2@\x10\x85\xdf.\xde\x00\t\xa7Q\x17\xb9\x01\x01\xaec\x94\
\xdb\x80\xf1\x06\xda\x16\x8e`<\x04\tW\xb0\xeb\x0f\\\xd8\xdav;oD\x89\x89\xefO\
\x13\xa6t\xbe};\x9d\x9d\x1ac{8\xa7.4\x7fZ\xaeJ\xff\xf5\xb7\xf9\xcc\x1a\xcd\
\xb3\x0c\xe3@H<\x9d\xdc\xd4b\x8fO\x85\nD\x04\x90J\x1ck\xbb+\xb0Y\x83\x02\xe9\
\x04X\xaeJ_M\x9c\x01\x18%!\x00`\xb3\x96AX\t\xe51q5\xb91\xaev\xd7\xf02\xed\
\x12\x05p\\}V\x8b\x85\xe4M\x10\x00pu\xdd\\\xac\x14@]\xed\xd6\xc7b\\h\x05H\
\xad^\n!q\x81p@\xb6zV\x82F\xa4O\xbc\xdf\x8a"y\x0fY\x03\x9c\xc2+y\x16\x00I\
\xf2$\xc0|fMh\xafZI\x9a\x91\xda\x01\xef\xf3\xcaU+E+\xeeV8\x13$\xadXu\x1c\x03\
\xd5\x0e\x18\xbb \xdd\xfb\xa0\xce-`j\x81=\x88\x00b\x1e\x90l\x05c}\x10U\x84)\
\'\xe2Y\x80\x91\x18 \xb5*\xcd \x12D\x15\xe1\xdb\xeb\x1d\x06}\xd7\x18\x1b\xf4\
\x81<\xcf\x01,\x98G\xf2o\xc1>\xc9\xe9D\x038\xe7Zc\x1a\xb8\x7f\x07(\x80\xfb\
\x87\x85\x01\xd0:\xe1|\xc6)Q\x1f&\xb1\xb2\x97\xe7\x03\xc8\xe8v\xac\xfa*\xfa\
\x16\x80/\xdf\x0f\x00\xc6\xf6~\x1f\xe0T\xfa\xd1\x91\xecO\x00|\x00\x0e\x85\
\x8c7\xc5\x108|\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_ideaImage()
def images.get_rt_ideaImage ()
Definition at line 381 of file images.py.
References get_rt_ideaData().
Referenced by get_rt_ideaBitmap().
def get_rt_ideaImage():
    stream = cStringIO.StringIO(get_rt_ideaData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_indentlessBitmap()
def images.get_rt_indentlessBitmap ()
Definition at line 397 of file images.py.
References get_rt_indentlessImage().
def get_rt_indentlessBitmap():
    return BitmapFromImage(get_rt_indentlessImage())
get_rt_indentlessData()
def images.get_rt_indentlessData ()
Definition at line 386 of file images.py.
Referenced by get_rt_indentlessImage().
def get_rt_indentlessData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00tIDAT8\x8d\xcd\x92o\n\x80 \x0c\xc5\xf7\xb6NW\xed\x08\x9d.\xe8\x04\
\xda\xf5\xec\x93"\xa6b)\xd1\x03a\xf8\xf6\xe7\xe7\x90\xc0B\xa5\xa3\xaa\xae\
\xe6\x83\x85\x00\x16\xea\xd1\xe4\x83u\x99]l\x18{"\xbd\xcbi$\xc1\xee\x8c\xdd\
\x10\x9b-\x04\xec\x8b\xdf\x12@\xf5\xb8\x15\xa7$\xd5\x06`\t\x04\xadO0\xf6\x0c\
y\xfctb\x96\xa0G\xbf\xfa\x07e\x82xi\xc3\t\xb8f~\xb2\x83\x0b\xf1\xae.\x0fLGF\
\xad\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_indentlessImage()
def images.get_rt_indentlessImage ()
Definition at line 400 of file images.py.
References get_rt_indentlessData().
Referenced by get_rt_indentlessBitmap().
def get_rt_indentlessImage():
    stream = cStringIO.StringIO(get_rt_indentlessData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_indentmoreBitmap()
def images.get_rt_indentmoreBitmap ()
Definition at line 416 of file images.py.
References get_rt_indentmoreImage().
def get_rt_indentmoreBitmap():
    return BitmapFromImage(get_rt_indentmoreImage())
get_rt_indentmoreData()
def images.get_rt_indentmoreData ()
Definition at line 405 of file images.py.
Referenced by get_rt_indentmoreImage().
def get_rt_indentmoreData():
    return \
"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00yIDAT8\x8d\xcd\x92a\n\x80 \x0c\x85\xb7\xd9\xe9\xaa\x1d\xa1\xd3\t\x9d\
\xc0y=\xfbeLM\x93\x92\xe8\x81 >\xdf\xf69\x04$\x03\xb5\xc5\xcc\xa1\xe5#\x19@$\
\x03o4\xc5\xcd\xba\xccA\x1bN<\xe6gW\x1aI`\x83\x93\r\xb5\xd9C@i\xc0\xde\x06r!\
\xf3^\x84r\x92f\x818\x83\xd8]\x87kOp\xe2\xcf;\x94\x1a\xfd\x9d\x0b\x82\xa7\
\xfa\xd5?\xa8\x13\xe8\xa1\r'\xa0\x96\xf9\xc9\x0c\x0e\xc1\xae.\x0f\xf2\xb3\
\x80G\x00\x00\x00\x00IEND\xaeB`\x82"
get_rt_indentmoreImage()
def images.get_rt_indentmoreImage ()
Definition at line 419 of file images.py.
References get_rt_indentmoreData().
Referenced by get_rt_indentmoreBitmap().
def get_rt_indentmoreImage():
    stream = cStringIO.StringIO(get_rt_indentmoreData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_italicBitmap()
def images.get_rt_italicBitmap ()
Definition at line 434 of file images.py.
References get_rt_italicImage().
def get_rt_italicBitmap():
    return BitmapFromImage(get_rt_italicImage())
get_rt_italicData()
def images.get_rt_italicData ()
Definition at line 424 of file images.py.
Referenced by get_rt_italicImage().
def get_rt_italicData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00gIDAT8\x8d\xd5\x93Q\x0e\x800\x08C\x0bx\xffc\xf4\x96\x8a_K\xa6\x0e\
\x82\xc1\x1f\x97\xecg\xb4\xaf$0\x115t\x8e\xb6\xdc_\x00\xb6\xac\xe8\xc7\xee\
\xf77Q\x93r\x07\xb3\x98\xe4\xc3<D\xe1%\xe9\x00\x1c\x80G\x9a\x140\xcc$\xdf\
\x03*\xe9)\xa0\x92\x1e\x02\xaa\xe9!\xa0\x9a.j\x90y\x95Ws_\xcd\xfeR\xfb\xff_h\
\x03N\xae\x87)\x94\x8d\x1e\xc5*\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_italicImage()
def images.get_rt_italicImage ()
Definition at line 437 of file images.py.
References get_rt_italicData().
Referenced by get_rt_italicBitmap().
def get_rt_italicImage():
    stream = cStringIO.StringIO(get_rt_italicData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_openBitmap()
def images.get_rt_openBitmap ()
Definition at line 466 of file images.py.
References get_rt_openImage().
def get_rt_openBitmap():
    return BitmapFromImage(get_rt_openImage())
get_rt_openData()
def images.get_rt_openData ()
Definition at line 442 of file images.py.
Referenced by get_rt_openImage().
def get_rt_openData():
    return \
"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x0f\x08\x06\
\x00\x00\x00\xedsO/\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x01\xbaIDAT(\x91\xa5\x93=H[Q\x14\xc7\x7fW\xdf3Q\x83\x01A1\xa0\xa8CK\x05'\
\x07\xe9 (\x01q\xc8$A\tN!E\x84\xd2RBU4\xb4)hT\xd0\xa8X-\xe8\xa0\xa0\x83\x1aA\
p\xb0\x83\x1fXGu\xe8 -\xa5\xa5\x83.\xe2\xe2\xe0\xd3\xf8\xf2\xf2\x02\xcfA\xf2\
\xf0\x19\xe3\xe2\x99\xce\xfd\x9f{~\xe7\xe3r\x85\xc8\xc9\xe59&=&\xd6\x07\x06\
\x8c\xfb\xe7\xa3\x85\xb0\xc8\n\xa8\xf2\xf6\x1a\x0f\xc5\xa3\x85\xb0\xa8\x0f\
\x0c\x18\xabQ\x0f\x00>0\xb2A$\x80w\x9e&\x8b\xb8UQfD\xfc\x1e|\xdd1\xa6\xc3/X\
\x8dz\xb2BDu[\xbf\xf1\x10\xa0h:\x8ar\xc5u\xe2\x86\xe3\xd3s\xbe|tP\xe3j\xc4\
\xdd\x193\xef\x9c\xac\x8f\n\x80\x9c\xc7\xda*\xb2\xc9\x94\x97\x14\xf3\xaa\xa2\
<#6\xfd\xa1#s\x04\x80\x99\xef\xfb\x96@\xa9\xd3a\xfa\xaa\xf1\x07h\x04\xe0\xfd\
\xd42\x00U\xde^\xa3\xb6\xd2e}\x85\xafo}\xd8e\x19\x9bM\xa6gn\x8d7\xc3?\x01\
\xb8\x00v\x92\x83\xf4\x7f\x83\xe6\xbc\xcf\xb8;c\xfc]\x19\xc2\xdb7s7\x82\xa2\
\xaa\x00\xc4U\x8d\x84\xae\xa3i:c]\xed\xcc\x87\xea,]\xa5\x93\x7f-\x86\xd9>\
\xf8\x8d\xb9\x83\xa5\xbdC\x02-\r\\\xdd$,\x90\x88\xbf\xd5\x84\xa4\x93\x0fgChz\
\x8a\xb9\x8d\x1flN\x04\x859B\x81$\xa1i\xba\xa5\xa2]\x96\x89\xf8[\xf9\x14\x82\
\x91\xcb\x18;\xe3A\x92\xa9$\x90g]\xe2\xeb\x97\xd5(\xaaJ\x11\xf9\x19[OC\x9c\
\xc5\x85\xc4\xd5\xbb\x02\xffN\xcf\xac\x00\x87=\x17]K\xa1\x90\x1d\x92\x88'\
\xa1\x10Parm\x8b\xcd\x89\xa0\x00\x90\x9c\x05vv\x8f\xffg$=e\xb5\x95.\xd3\x17\
\xcf\xfd\x8d\xb7\xd2\xb4\x9d\xba\x05\xf7F\xcb\x00\x00\x00\x00IEND\xaeB`\x82"\
get_rt_openImage()
def images.get_rt_openImage ()
Definition at line 469 of file images.py.
References get_rt_openData().
Referenced by get_rt_openBitmap().
def get_rt_openImage():
    stream = cStringIO.StringIO(get_rt_openData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_pasteBitmap()
def images.get_rt_pasteBitmap ()
Definition at line 494 of file images.py.
References get_rt_pasteImage().
def get_rt_pasteBitmap():
    return BitmapFromImage(get_rt_pasteImage())
get_rt_pasteData()
def images.get_rt_pasteData ()
Definition at line 474 of file images.py.
Referenced by get_rt_pasteImage().
def get_rt_pasteData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x0f\x08\x06\
\x00\x00\x00\xedsO/\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x01sIDAT(\x91\x85\x93;/DA\x18\x86\x9f\xef\xcc9\xd6X{\xb1v{\t\x8d\xdf\xb0D\
\xa3\xd8\x82B\x14*\xa1\xd5*\xd6%B\x88\xb8\x15~\x81\x88d\x13\xa2Q)\x14\x12\
\x14\xfe\x05\t\xb5\xb5\xd6u#.\xa3X\xc6\x1e\xe7\x9cx\x9b\xc97\x99\xef\x99\xf7\
\xfd&#\xe2(~\x94/\x96\x0c!:\xdf\x18\x95\xb0}\x00\x11G\x91/\x96\xccX\xf2\x9a\
\xab\xea\x0b\xcb\xebK\xbe\x03sS\xf3\x00\x9c9\xdd\xa1 \'_,\x99\x93\xfeO\x80@\
\xf3\xcf^G\xba\x85\xc3\xf6\xe3P\x87nc\xb1\xb5\xba\x16\xe54R\xd23\xbdkN\x873\
\x98\xfb2\x00\x1f\x95\x1b\x00\xccM\x8d\xd7\x97\x0b\x06n\xfb\x03M\x8dQ\x1cKJe\
\x01P\x99\\\xbd\xceib-]\x00lN\x0c2;Z\x00\xe0hq\xc4\x17\xc5\x01\x90D[$\x04 \
\xad]\xb2\xad\x9eu\xd0\x08\xb13\x90D\x1b\xe6\xf1\x0eIe1\xf7eT&g\xe3\xa4\xf4\
\xefS\x17\x16\xf6}q\\\x00\x89\'1\xcf\x0f\xa1\x10\x80&\xe5\x90\xd2\xb0=9D\xb5\
\xf6N\xf9\xe9\x8d\x95\xd2\xd1/\x00\x9d@ \x14\x02\xd0\xec\tP\x87\xfc\x95\x1d"\
:\x81\xc4\x936\x8eo&"4{\xf2\xedD\x91\xd6\xae\x1f \x9e\x8e\x84\x00xJ,$\xde\
\xa4|3\xa9\xa3b1\xc4U\x98\xdaS \x0eT\xe8\x9d\xd9\x0bz\xf7\x01\x9c\xfa"\xba\
\x15\xde?0`!g\xe3\x9d\xf6p\xdf\xcee\xe0?\xb8\x00\xbd\xf3\x07\x917\xfc\xa7/\
\xbf\rv\xe9ib\xe3\x0c\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_pasteImage()
def images.get_rt_pasteImage ()
Definition at line 497 of file images.py.
References get_rt_pasteData().
Referenced by get_rt_pasteBitmap().
def get_rt_pasteImage():
    stream = cStringIO.StringIO(get_rt_pasteData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_redoBitmap()
def images.get_rt_redoBitmap ()
Definition at line 528 of file images.py.
References get_rt_redoImage().
def get_rt_redoBitmap():
    return BitmapFromImage(get_rt_redoImage())
get_rt_redoData()
def images.get_rt_redoData ()
Definition at line 502 of file images.py.
Referenced by get_rt_redoImage().
def get_rt_redoData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x0f\x08\x06\
\x00\x00\x00\xedsO/\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x02\x0eIDAT(\x91\x9d\x92\xbfkSQ\x1c\xc5?\xf7\xbd\xbc\xf6\xbd\xf4\xbd\xdb\
\x8a\x91\xa6j)Vb,\x14%\x83\x88Y\x02\x01q\xec\xe4 \xe8&\xa4\xab$\x83\xfe\x05.\
m\\,4\x10p\xe8\xe0PT\x82\xe0\xe0P\xb5P"bI-\xed\x10\xbbhj["\x8d1?j\xd2\x9f\
\xd7\xa1\xf4G\x9a\xda\xc1\x03\xdf\xe5\xdcs\xcf=\xf7\xdc+\x84\xa6\xb3\x87\xf1\
\xc9\x19\xf545\xc5b\xa1\xb4\xcf\x85\xaf\xfaH>\xb8-\xf8\x07\xc4\x9eA4\x91R\
\xaf\xd2\xf3\xb4\x9b-M\xa2R}\x83\xeb\xfen\x9e?\xba\xd7`\x14M\xa4\x94\x10\x9a\
N\xfc\xe5{5\xf6\xf63\x1eS\x03`}[\xa3\xb2\xb9\x85c\xb8h\xd5w\x1a\xb8\xcchL\
\x1c>P\x08M\'\x14\x1dQ\x1e]a\xe8:\xd9\xe2\x1a\xe1\x80\x8f\xfe\x9eN\xe6\xbe\
\xe7\x99\xc8,\xd0+M\x0c]\xa7R\xdfa\xb9V\xe3rO\'K\xcb\x05*\x9b[\xb8\x00\xcak5\
|]\x92j}\x9bp\xc0\xc7pd\xa0\xf1\xce\x83C\xca\x7f\xaa\x8d\xae\x0e\x03\xc7\xd4\
\xd8(\x96\xb8\xe4q3\xbdRF\x03p\x0c\x17\xb6\xe9\xc66u\xce\x9dio\xea 3\x1a\x13\
\xd9\xe2\x1a\x00\xde\x0e\x87\xee\xd3\x1d\xd8\xa6\x1b`7\x01\x80\x94\x0e\xd2\
\xb6HM\xcd\x1f\xdb\xb6l\xb3\xb0M7R:\xfb\x9cc\xac\xee\x1a\\\xeb\xbf@\xb5^\xe3\
\xac#\xf1\xb44\xbfX`pH\x85z\xbdH\xcbjZ\xd3\x00\x86#\x03b:W@\xda\x16\xb7\x02}\
\x84\xa2#jOp\xe7\xf1\x98\x02X\xc8\xaf\x92\xfb]\xa0\\\xab!m\x0bi[\x88\x16\xe3\
\xe0\x1f\xdc\x7f2\xae\xa4\xb6M\xd0\x7f\x91_\xe5*\xcf>~%\x1d\x8f4\xc4\x19\x9f\
\x9cQ\xd9\xc5<\xf3\xb9\x9f,-\x17\xf8Q\xf9s`\x00p\xf3aB\xdd\xbd\xd1\xc7\xf9N\
\x0f+\xf9"#\x1f\xe6\x9aL\x9a 4\xbda\x82\xb1\xa4z11\xabf\xb3\xdf\xd4\xebw_T0\
\x96TG5\x87G;j\x98\x8eG\xc4\xf0\x9bO\xac\x96\xd6\xb9\xe2\xef&\xe8\xf7\x9e\
\x18\xc0u\x1c\x99\x8eGD\xdcN*i\xb5\x9e\xb8\x19h\xec\xe0\x7f\xf0\x17QL\xb6\
\x0e:\xc2\x0cm\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_redoImage()
def images.get_rt_redoImage ()
Definition at line 531 of file images.py.
References get_rt_redoData().
Referenced by get_rt_redoBitmap().
def get_rt_redoImage():
    stream = cStringIO.StringIO(get_rt_redoData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_sampleBitmap()
def images.get_rt_sampleBitmap ()
Definition at line 550 of file images.py.
References get_rt_sampleImage().
def get_rt_sampleBitmap():
    return BitmapFromImage(get_rt_sampleImage())
get_rt_sampleData()
def images.get_rt_sampleData ()
Definition at line 536 of file images.py.
Referenced by get_rt_sampleImage().
def get_rt_sampleData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x00\
\xc3IDATX\x85\xed\x97K\x1a\xc2 \x0c\x84g(7i\xaf\xa8\x87\xa8W\xa4GQ\\(\x0b\
\x95j\x88\xe9\x17\x16\xcc\x9a\x84\x9f\xbc\x002L\xf0Tp\xdd}\x00\xf4\x00\x10\
\x7f-\xc8\xb7k\xd68f\x98h\x02\x00\x00\xf3|j\xda|\xdb.\xe2\xb5\xee)\x10\x03\
\xa4\xb4"\xa5\xd5\x0f\xe0(\xb9\x03\x88\x8aP\xa2\xf7\xc2\x93v\x8f\x19\x00\x00\
\xe4\xc6\x86%\x81\xa8\xeds+E\x00\xf8F \x9a&/*\xded\x96\x1d\x15aI \xeb\xe4\
\xcbr>\x04\xc0=\x02D9\xfbN\x04Zj\xe0\xe9HlIJn\xc3\x9a!>o;m7\xb9\xa7\xc0\x1d\
\xc0t\x12>\xd469:\x8a\xc0N\xff\xb7H\xe3\xc2,\x05\xd27`\x15\xe0\xff\xb3\xeb\
\xc5\xf15\x1b\x00\xde\x00w\xa7\xdb(\xe7d\x95\xec\xc5\x00\x00\x00\x00IEND\xae\
B`\x82'
get_rt_sampleImage()
def images.get_rt_sampleImage ()
Definition at line 553 of file images.py.
References get_rt_sampleData().
Referenced by get_rt_sampleBitmap().
def get_rt_sampleImage():
    stream = cStringIO.StringIO(get_rt_sampleData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_saveBitmap()
def images.get_rt_saveBitmap ()
Definition at line 575 of file images.py.
References get_rt_saveImage().
def get_rt_saveBitmap():
    return BitmapFromImage(get_rt_saveImage())
get_rt_saveData()
def images.get_rt_saveData ()
Definition at line 558 of file images.py.
Referenced by get_rt_saveImage().
def get_rt_saveData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x0f\x08\x06\
\x00\x00\x00\xedsO/\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x01\rIDAT(\x91c\x8cO\xcb\xfd\xcf@&X4g\x1a#\x0b\x03\x03\x03\xc3\x9e{\xbf\x18\
\xbc\xec\xcd\x18f\xd5$\x11\xd4\x14W;\x85a\xdf\x89+\x0c.Jl\x0c\x0c\x0c\x0c\
\x0c,\x0c\x0c\x0c\x0c\xf1>\xae\x0c\xaf?\x7fd````\xd8\xbbo?N\xcd\xceN\x8e\x0c\
0\xf5O\xaf\x1dD\x18\x80M\x11\xb1\x00\xc3\x00b\\\x80\xd7\x00\xb2] \xca\xcb\
\xcf\x10W;\x85\xa0\x06Y\x11I\xdc.@\x97$\xc9\x050\xb0\xed\xfcU\xbc\x1a\xbc\
\x0c\xb5q\x1b\xb0\xed\xfcU\x86\xd2@K8_\x88\x9f\x97\x81\x9f\x97\x87\x81\x87\
\x97\x97\x81\x9f\x97\x8fANR\x90\xc10\xa1\t\xc5\x10\x0c\x170000\x94MY\xcb\xa0\
\xa9\xa6\xca\xc0\xc0\xc0\xc0\xd0\x94\xe4\x8e\xd7ELxe\x19\x18\x18~\xfd\xfe\
\xc7\xc0\xfc\xf7\x07\xc3\xef?\x7f\xc83\x80\xf9\xdfw\x86\xaf\x7fX\x18~\xfd\
\xfd\x8bU\x1e\xc3\x0br\xa2|\x0c+\x1a\x13\x19\x84\xa5\xe4\x194\x15$\x08\x99\
\xcf\xc0\xc8\xc8\xc4\xcc\x10\x97\x92Er\x8e\\4g\x1a#\x03\x03\x03\x03\x00\xb7\
\xa8?\xb7)\xf6\xbb\xdc\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_saveImage()
def images.get_rt_saveImage ()
Definition at line 578 of file images.py.
References get_rt_saveData().
Referenced by get_rt_saveBitmap().
def get_rt_saveImage():
    stream = cStringIO.StringIO(get_rt_saveData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_smileyBitmap()
def images.get_rt_smileyBitmap ()
Definition at line 601 of file images.py.
References get_rt_smileyImage().
def get_rt_smileyBitmap():
    return BitmapFromImage(get_rt_smileyImage())
get_rt_smileyData()
def images.get_rt_smileyData ()
Definition at line 583 of file images.py.
Referenced by get_rt_smileyImage().
def get_rt_smileyData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x01:ID\
ATX\x85\xedW\xd1\x16\xc2 \x08E\xd7\x87\xed\xd3\xf7cE\x0f\xc6"\x07^4w\xd6C\
\xbcT\x83\xee\xbd\x03EL)/t\xa5\xddF\xfe\xc4\x8f;\xd7\xcfR^\xd2\xa9\x024)\x1f\
\xe8\x89Rz\xfb{\xc4$T\x02!\xb6H}\xd0\xb8\x90\x8c\xc8\x99\xfb\xc8\x89J<\xb3]\
\xaa\xda\xcc\x0c\x8c\xbc\xb5O\xf0\xfat\xb2\xe1f`\x06\xb9\xe0\xb4\xb2q\x10 i\
\xb7,\x81\x8a"?\x14\x80\xc8\x99}\x12\xe4\xf7\xb2\xd0\\\x845\xb8\x00\xd5$\xc8\
\xdf\x12\xb1\x0b\xf0\xde^\x83k \xf4;Z\x0e\x98\x01\r\xde\xb3\x06\xa2\x8b8T\
\x823-\x13\xb5\x17\x9f6\x14\x13\xc5\xd0\xeb\xe072\xf0\x17\x80\xac\xb7\xc3\
\xf5\xc4g\xa2rPD\xb6\xd8\xb4\x18u0\x85\x07\x92M\x01\x10\xd9\xfdAb\xd6(hT\x80\
t\xb6\xcd\x10\xa2\x89\x85\xbcoxQ\xf3\x00\xea\x07"\xc2\xb3\x08\xf9p\t\x88>{\
\xbc\x16\xb2*\x7f\x0fyyVMD\xd1\xae\xd8\xdb\xf7-r"c\x1bFv\x84\x90\x8e\xcc\x8b\
P\xc0.dh\xca\xb7q\xbc\xb7/\xfe\xc6X\x1e-G\x93\x1c\x8c\xe6\xcdN(\xe5\x18\xe9\
\x84\x11\xf2\x12\x1b\xbc\x1b\xe2\x9b\x91\xfa>\xf3f\x84\xc4\x8c\x90~-`\xa6]~\
\x1c?\x01\xdf=\xae\x9f\xe1\xb5v\x06\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_smileyImage()
def images.get_rt_smileyImage ()
Definition at line 604 of file images.py.
References get_rt_smileyData().
Referenced by get_rt_smileyBitmap().
def get_rt_smileyImage():
    stream = cStringIO.StringIO(get_rt_smileyData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_underlineBitmap()
def images.get_rt_underlineBitmap ()
Definition at line 619 of file images.py.
References get_rt_underlineImage().
def get_rt_underlineBitmap():
    return BitmapFromImage(get_rt_underlineImage())
get_rt_underlineData()
def images.get_rt_underlineData ()
Definition at line 609 of file images.py.
Referenced by get_rt_underlineImage().
def get_rt_underlineData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00WIDAT8\x8dcddbf\xa0\x040Q\xa4\x9b\x1a\x06\xb0\xa0\x0b\xfc\xff\xf7\
\xf7?2\x9f\x91\x89\x99\x11\x9b\x18N\x17 K\xc2\xd8\xd8\xc4p\x1a@*\x185\x80\
\x80\x01K\x97,\xfe\x8fLc\x03\x8c\xb8\x922z\xdc30`F!^\x03\x88\x05\x04S"6\x80\
\x92\xb0\x06<7\x02\x00\xcev\x16+\x82\x11y\x82\x00\x00\x00\x00IEND\xaeB`\x82'\
get_rt_underlineImage()
def images.get_rt_underlineImage ()
Definition at line 622 of file images.py.
References get_rt_underlineData().
Referenced by get_rt_underlineBitmap().
def get_rt_underlineImage():
    stream = cStringIO.StringIO(get_rt_underlineData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
get_rt_undoBitmap()
def images.get_rt_undoBitmap ()
Definition at line 653 of file images.py.
References get_rt_undoImage().
def get_rt_undoBitmap():
    return BitmapFromImage(get_rt_undoImage())
get_rt_undoData()
def images.get_rt_undoData ()
Definition at line 627 of file images.py.
Referenced by get_rt_undoImage().
def get_rt_undoData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x0f\x08\x06\
\x00\x00\x00\xedsO/\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\
\x02\x15IDAT(\x91\x8d\x92\xcbk\x13Q\x18\xc5\x7f3\x99\xc4\x99d2i\xda\xb4\x8d}\
(6\xd8 \rb\x16"\x8dh\xc0\x8d\xcb\xe2\xc2Eq[hAW&\x7f\x81\x9b\xbah\xebJh\xb0\
\xbbv\'*\xc1\xc7F\x88\x8a\xd4\xa0"!\xa5EC\xb0\xf6a\xab\x81\x846\xa16iK\xb9.\
\xea\xa4/\x1b\xfd\xe0[\xdc{\xcf9\xf7\xdes>I\x92-\x1cU}\xf7\x1e\x8aD:[]\xb77\
\xb8\xb8\xd5s\x91\xeb\x97\xcfI\xe6\x9e\x14}\xf0L\x0c\xf7\xf7H{\x89\xbd\x83\
\xe3\xe2}f\x11\x97j;$Z\xaclr\xad\xbb\x0b\x93#?I\xce\x10\x89\xc5\x85\t\x08\
\x0e\x0c\x89\xa5\xe5\x02\xbe:\x15\x8f*\xe3\xb4*\x008\xad\n\x1eU\xc6W\xa7\x92\
He\x19y\xfcZ\x00(.\xd5\xc6\xc7\xe9o\xf4\x0e\x8e\x8b/\xf39Z4\r\xa7*\xb3\xb5\
\xbd\xcdl\xa9\xc2\x95\xa0\x8f\xc0\xc9f\xa6\xe7s$RY\xfcn\x07\x86m\x9b\xf8\xe4\
\x0c\x00\n@\xa7\xc7\xce\xcaJ\x11\xbf\xdb\x81\xaeZX\xab\xec\x90S\xa3Q)\xb5\
\xe7\xf9\x91X\\,\xcd-\xe3v\xd8\x98\xfdQ\xda\x15\xd0U;\xbaj\x07`\xad\xb2Nf\
\xe5\x17\xa9\xd1\xe8>_\x00Z\x1b]\x14\x7f\xe6\xd0U;N\xeb\xfa\x8e\x80\xd3\xaa`\
\x18\xce}@\xc3\xb1\xf5\xd7T\xe2\x933\x84;\xbc +@\x1e\x00\x19\xc08f\xadv[c=\
\xe1\x0e/\xc1\x81!qP\xc0c\x9304\x8d\xb5\xcd2\xe7\x03\xa7v\x04$\x9b\x15C\xd70\
t\x8dR\xb9\xcc\xc2j\x81l._\x8d\xd3$\x87#\xf7\xc5\xd5\xe0\x19\x0c]\xe3\xd3B\
\xa1\x1a\xa3\xb2X(2\xf16MkK\x03]\'\x9a\xb8\xd4\xee\xab\x0e\x8ai`\xf7\xed\x98\
\xb8q\xa1\x93zC\xe7]\xe6+\xa7\xdb\x9ax\xf3\xe7L\xaa5\x89&\xf9f8\xc0\xf1f7\
\xdfsy&\x92\x9fyy\xb7\x7f\xd7`I\xb6\x1c\xd9\xa1\xe8\x98x\xfa*-\xa62s\xe2QbJ\
\x84\xa2c\xe2 F\xaeu{\xc8\xef\xe5\xac\xbf\x9d|q\x83\xe1\x17\x1fH\x8e\xf4\x1f\
\x8a\xb6\xe6\x17L\x13K\xe5\r\x9e\xdf\xe9;D\xfe/\x0f\xfeU\xbf\x01\xf6\t\xb0_}\
e\xc8\x99\x00\x00\x00\x00IEND\xaeB`\x82'
get_rt_undoImage()
def images.get_rt_undoImage ()
Definition at line 656 of file images.py.
References get_rt_undoData().
Referenced by get_rt_undoBitmap().
def get_rt_undoImage():
    stream = cStringIO.StringIO(get_rt_undoData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
getCarrotBitmap()
def images.getCarrotBitmap ()
Definition at line 111 of file images.py.
References getCarrotImage().
def getCarrotBitmap():
    return BitmapFromImage(getCarrotImage())
getCarrotData()
def images.getCarrotData ()
Definition at line 85 of file images.py.
Referenced by getCarrotImage().
def getCarrotData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x01\
\xf4IDATX\x85\xc5W\xdb\x91\x830\x0c\\\xd9\xd7\x11\xa9%%\xd0\x025\xd0\x02%P\
\x0b\x94\x94\xf8>@f\xfd\x0c\xaf\xcb\xed\x0c\x13\x93\x18v%\xad\x04\x111\x16w\
\xc1\xbd_N\xd7b\xac\xf09C\x8c\x15\xbf\xbeK\x80{\xbf\x9ck\x89d\x000f6\xce\x00\
\xfaM\xc4\xcf_\x90\'\x841:\xc0\xf5/\'\xc6\xcae\x01J.\x03\xc0"\\\x0b\xc8s!C\
\x9f\nP\\\x12\xa0\xe4\xb9 \xbd\x88\x1ei)\x9e\xdb\xf2\x92\x078\xf53\x80G\x94\
\x05O2D_\x8c\x8b\x081VN\x0b\xa8\xd6=\xc2\x0c\xa0\xc1\x96\xa9\xc7*H\x8c\x15s\
\x8a\xfd\x038b%\x07}2N\t`\xe3\xe50\xd1oJ:#\xef\x95\xc3\x02J\xa9g1\r\x16/(\
\xa1\xfa\x03\xfaI\xa6\xbcT\x02\x8e\x94\xd7\xf3*H\xeb\xde\xac\xbf?\x06,-H\xa9\
8$ \x8e^o\xacd\xa5\xb5\xcf@G\x17\xae\xd8\xdd\x05\xa5\x81\xc3\xd0\xc0\xb8\xee\
\x9azt\x08[\xa1?\xd9\x05S\xc5|J\xae\x86\x0b\xc8y\x03a\x97\x00\x8e^\r\xc6`\
\xc7\x07\xbd\xde\x85\xfbx\x02*\x0e\x8d\xe2R\xea\xb3Y\xe1g\x00+\x8b\xf01\x03\
\xb9\xb6\x8b\xc9\xd4t\x9ex%\xe7\xe7~\tU\x01\xa5\x81\xa3\x11s\xdb=x\xcfNr`g\t\
\xa6\xc8\xfd\x1c\xb1\xd0\\/\xbd\x01\xd5P\xcc@\xcdxBSM\x8c\x95 \xda&\xbc\x07F\
\xa4\xf5\xa7=\xd5\x12\xccH\x8d7c\x9bj{\xd3\x0c |)yn\xd7f\x05h\xf4\xdc\xb2\
\xec\x83\xc3\xe4\x15$\x1e\xc8M<\x8d\x9a\xeb}\x079P\xc8\x00\xa7\xbeZ\xef\xd2\
\xc5G \xc6\xfa\x03\x80s\xedr\x00pS\xbb\x1c\x00\x1c\xef\xab\x1d\xbc\x17\x80\
\xc3\xb8]\x1f\x9f\x8b\xb1[\t\xe2\xf7;\xff\xf8\xc4\xbd)\x8f\x91\x94\xe0p\xca/\
B\xc4\xd8\xe4\xf5\xfa\x8a\xcb\xdd{\xf9\xc3\x11\xcc\x80>\x1cT|\xef\xa0\x0b\
\xbe\x91\xf2\x1c\xbc\xe9\xf6\x1am\xaf\x19c\x03\xc6&\x15ca\xb4\xe7\xbf\x1d\
\xb5\xc2\xfc\'9\x00\xfc\x026\x8c\x17\xf6I\x95Du\x00\x00\x00\x00IEND\xaeB`\
\x82'
getCarrotImage()
def images.getCarrotImage ()
Definition at line 114 of file images.py.
References getCarrotData().
Referenced by getCarrotBitmap().
def getCarrotImage():
    stream = cStringIO.StringIO(getCarrotData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
getcustomcontrolBitmap()
def images.getcustomcontrolBitmap ()
Definition at line 1857 of file images.py.
References getcustomcontrolImage().
def getcustomcontrolBitmap():
    return BitmapFromImage(getcustomcontrolImage())
getcustomcontrolData()
def images.getcustomcontrolData ()
Definition at line 1826 of file images.py.
Referenced by getcustomcontrolImage().
def getcustomcontrolData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02tIDAT8\x8d\xa5\x93OoTe\x14\xc6\x7f\xe7}\xef\xcc\xb4\xd3\x99\xb6\x8c\
\xb4\xa6-\xd04\x91\xc0BL\nD\xd0\x8d\xb8"nH`c\xdc\xb90!a\xc3\'0\xee\xdc`\xa2\
\x89\x9f\xc0\x95n\xfc\x00\x86\xc0\nea4F\x8db\x90\x90\x0c0@\x85\xc20\x93\xb9s\
\xef}\xcf9.n\xf9\x13\xe3\xc6\xf8lNr\x92\xf3\xe4\xfcN\x9e\x03\xffS\xb2\xb6y\
\xe1\xc2\xf1c\xaf\x7f\xe0\x96$)$\x15TA\x15\x92\xed\xd4\x04j\xcf{\xa6\x81\xbc\
4\xef\xff\xfa\xd9\xc7\xd9\xc1\x8d]\xef\x9c{wcq<)\xc9\x0b\x98\x16\xb2S\xa1\
\xa8`:\x85\xbc\x80\xa2\x84|*\xe4\x15TU`{d\xdc\xbb\xb9\xfaV\xd6]h\x16k+-\xd4\
\x9a\x98\x81\x19 B\x04\xca\xe4\xb8\t\xd3\xe4\xa8\x05\xcc\x1c5\xc1=Pj\xc6\xad\
\xdfc\xca\x1a\x8d\xc0\xeaJ\x87\xee|\xfb\x19\xd7\xfd\xc7\x15\xdf\xf6+\x8e\xae\
\xb7\x98T\xce\xe1\xe5\x0cpp\xc3\xdd\x01(\xab\xc8\xc2\x9c\x90\x01\xec\xf4\x00\
\xb8rc\xca\x0f\x03\xe5\xa1\n\x97\xaem\xd1\x9c\x99\xe1\x8d\xf56\xaf-\t\xfb\
\x97\x03ee\xb8\xd7xI\xb56xQ\x97\x7f\x1b\xb2\xd5\xea\xd0\xdc~\xc8\x83?\xfa\
\xdc\x1a&\xae\xae\xed\xe3\xc8\x81\x97\xf9\xf4D\xc4\x05\xd4\xbcFu%\xbc8\xbc=V\
\xfaE\x8b=/\xcdr\xe6\xd82_~\xf8&\x9f\x9f;\xccj\xcb\xb92P>\xf9>\xa1I\xc1\x1dS\
\xc3\xed\x1f\x06A\xe0\xf2\xcf\x03\xae^\x7fD\xdeh\x11\xc49\xf2J\x9b\xf3\'\xf7\
\xb2{W\x87\x9bCC\x93aV\x1b\x98[m "\x00,\xb4#_\xbc\xb7\x87^#\xf0\xe7\x18.\xde\
\x0e\xf4\x1f9ss\x81\x03K\x8252\xb6\xc6^o\xe0\x0e\xa6d\x01!\xc6X\xa7J\xa07\
\xdf\xe0\xda`\xc8\x8d\x07\x13\x8enty\xb2\x7f\x9eQ\xe1\xcc\x87\x82\xef\xae\
\xdf%\x1e\xda\x8d\xaa\xed\x1c\xde\xea#\x86X\x93\xb8;\xeb\xbd&\xef\x1f\x9a\
\x01U\xee\x149m\x9b\xe1\x9b\x9f\xb6X\\\xec\xf2\xd1\xdb=zm\x98V\x86\x99\x00J\
\x16\xb3(\xad\xe6\xd3\r\x84\xcel\xe0\xec\x89%0\xe5\xab\x1f\xc7\x84i\xc9\xa9\
\x83]\x86ybs\xef,fF\x16\x9d\x10\x02\x12D\xb2\xe1\xa8\x92\xed\x91\x10#h\xaa\
\x93h\xaa\x98;\xc7W\xda5\xa7\x04\xdc#\xc3Q\xc2\xcc\x10\x81I^0\x1eM\xa2\xc4\
\xce\xab\xa7W\xf7m\x9e\tbb\xf64Q\x86\x01\x010\xad\xc0\x15Lq\x12xBP\xca\xaa\
\xe4\xaf\xc1/_\xff\xb7\xdf\xfd\x17\xfd\r*\xb1L*W\n\xe5H\x00\x00\x00\x00IEND\
\xaeB`\x82'
getcustomcontrolImage()
def images.getcustomcontrolImage ()
Definition at line 1860 of file images.py.
References getcustomcontrolData().
Referenced by getcustomcontrolBitmap().
def getcustomcontrolImage():
    stream = cStringIO.StringIO(getcustomcontrolData())
    return ImageFromStream(stream)
index.append('customcontrol')
catalog['customcontrol'] = ImageClass()
catalog['customcontrol'].getData = getcustomcontrolData
catalog['customcontrol'].getImage = getcustomcontrolImage
catalog['customcontrol'].getBitmap = getcustomcontrolBitmap
getDataBitmap()
def images.getDataBitmap ()
Definition at line 1096 of file images.py.
References getDataImage().
def getDataBitmap():
    return BitmapFromImage(getDataImage())
getDataData()
def images.getDataData ()
Definition at line 1066 of file images.py.
Referenced by getDataImage().
def getDataData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02VIDAT8\x8d\xa5\x93MHTa\x14\x86\x9f\xef\xce\x1du\x9c\xd44Mq\xd0\n5mc\
\xe5\xa2\xc0\xd0~p\x91n\xfa\x816%b\x89\x14\xb9Q\x83"(\x97\xd1"pS\x81N\x7f\
\x12\x04A\x9b\x88\x82\xca\n\xd4\x8a\x10\x89\x12khB-\xb5)E\xa7\x99\xb93\xa3\
\x8e\xf7\x9e\x16\x85\x84\x8d\xb4\xf0\xc0\xbb9\xe7=pxx\x8f\x12\x11VR\xda\xff\
\x0cI\r\xbem\x8e\xfa\xc13\xcb\x1aD$\xae\xb4\xc6\x85\xbc\xa6W\xb3\xd2\x19\x12\
q\x1b"i\x87\x07\xba\xe2\xf9\xe2.g\x1c\xbc~\xac\xca+rdX\xa4\xf6\x8f\xeaFE2\
\x1a\xc6{\x96z\xf5xW\xd9-\xbb\xde\x9d\x08\xa9\x1f!\xb8\x00\x08\x14\xa5C\xe5E\
W\x85J\xdc\xec\x90\xb9w\xd1\xf8\x0c\xf6\xab]\xe1\xd3\x1bF\xf4\x98\xc4\x08B\
\xd0\x05e:\xec(\x01W.\xdc\xff\x0e\xdc\xf9T\xf1\x0f\x03\xb3\x8aT\xcb}\xc0\x90\
\xe1\xa7"\xde\'\xd2u\xaa\xd5\xe2\xa5\x08}"\xa5\xfd"\xb6>\x11\xd5+\xc2\x0b\
\x91\x0e\xb9,\xf6\xaby\xcd\x8b\xac\xe6\x1b\xd3\xefim\x97\x02\xaa`\xbb\x93\
\xcf\xfd\xe0}C\xdd\xee4u\xf2\xf6\r\xf0\x83\x15\x02\xd3\x0f\x12\x82uw{\x99\
\x8a\x04h\xa9\xabm_\xd5\x99\x7f\r@7\xf5\x04\x07#\x0f\xe1\xc30\xe8\xab\xc0\
\x14\x08\xf8\xb9\x92\x93\xc3\xcc\x85\xc1\xe8\xfb\xb3\xed\x8e\xf4n\x0f[N\xb4\
\xe0hv\xf2z\x02,eQ\xb8\xd3\xd5\xa0\xd7\xa7x\xb4p\xd4\x82\xa9\x00\xac\xcd\x82\
\xb1\xaf`\x18P}\x14\xb6\xec\xa5x\xd2=`O\xad\x19\xf57m\xc5g~\xe3\xd1\xd0s\x1e\
{z0\xf4 {2*\xd1\xfc\x92\xad\x1b\xb3\x16\x99\xd3\xe1\xdf@6\x96\x808a\xb0\x1f\
\xa6\xbf\x10\x8dZ`\x9b\x9fc\xca\x8e\x87\x11\xca\x8b\xca0\xccy\x8c\x9fst\xf8n\
A\xccDoz6\xd3\xf6`MJ\x8d\x16\x8bA\x14\x98\x9e\x00\x11P\x8ap\xc4\xd4F\xbdcoYm\
+Fi\x8c\x87\xa7\x19\x8b\xf8\x10\xb1@\x81\xdd4Q"B~\x82*\x1c:\x94\xebM\xb1+\
\xf0\x05\x99\x8ciT\xf5\x04\xef\x0c\x9ar\\D\x0cgk\xf6\xcd\xe8&U\xefJ\xc9f<\
\xf4\x03\xa5\x14\xb6\x81\xe0\xd8\x82;R\xbd\x98(\'dz\x0e\xac\x97\xfdN\xad\x17\
\xc8Y\x9a\xb8\x84}\xc9\xe7\n\xdc\xe5\x92|>+B\x12\xd5q\xa3\x0c\xd8\x96\xfb\
\x8d?\xf3R@\xfb\xbb\xa7V\xfa\xce\xbf\x00\xbe\xd8\x909\xec\xce\xb6\xb3\x00\
\x00\x00\x00IEND\xaeB`\x82'
getDataImage()
def images.getDataImage ()
Definition at line 1099 of file images.py.
References getDataData().
Referenced by getDataBitmap().
def getDataImage():
    stream = cStringIO.StringIO(getDataData())
    return ImageFromStream(stream)
index.append('Data')
catalog['Data'] = ImageClass()
catalog['Data'].getData = getDataData
catalog['Data'].getImage = getDataImage
catalog['Data'].getBitmap = getDataBitmap
#----------------------------------------------------------------------
getdeleteperspectiveBitmap()
def images.getdeleteperspectiveBitmap ()
Definition at line 1308 of file images.py.
References getdeleteperspectiveImage().
def getdeleteperspectiveBitmap():
    return BitmapFromImage(getdeleteperspectiveImage())
getdeleteperspectiveData()
def images.getdeleteperspectiveData ()
Definition at line 1278 of file images.py.
Referenced by getdeleteperspectiveImage().
def getdeleteperspectiveData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02~IDAT8\x8d}\x93KHTQ\x1c\xc6\x7f\xe7\xdc{\xee\xd5\x19\xf3\x91\xf6\xb0\
\xa4\xe8m\x85 -$($\xa4\xa0E\xb5\xb2E\xeb\x82"\n\xca \xa2 jc\x0f\x88 \x91\xa2\
MD\x9b@\x08"\x08\x85\xa4\xa2\xac\x90\x1e\x9b^\x9a\xaf\xf2=\x9a:\xceL\x8c\xf7\
\xde9\xa7E3\xa90\xf5_\x9d\xc5\xe1;\xdf\xf7\xfb\xfeG\xb4\xb5\x7f\x1e/\xcc\xcf\
s\xb51dF\x1bH&g\xf0=\x9f\xf1\x89\xa8\x0c|=\x19\x8b\xc5w[\xb6\xfdQJ\xc9\xb7\
\xce\x0e.\x9c;\x02\x80\xed:Nx\xe3\xfa\xb2\x1c\xe6\x8c1\x86\xa4\xa7I\x05\xd0\
\xdd\xdbO^87\xd4\xdd7\xfct`ht\xbf\xeb\xba\xcf\xe6\xde\x95d\x19!\x04R\x82\x90\
\x1aiI\x96\x96\x96\xb0c[E\xc9\x86u+[\x94m\xd7\xeaY\xb3\xd8\xd9\x04\x0c \x00\
\xc7\xb1\xe9\xed\xeb\'2:J(\x9cC\xe0\xa7\x9c\xe9\xe8T\x93\xd6\xba\x0e\xb8\xfe\
O\x07\x00B\n\xa4\x80E%\x0b\xf1\xb4`t$JWw?N\x8eC<>U\xff_\x07\x02\x90B\x10\xf8\
\x01\x15\x95\xe5xI\x9f\xf1\xd8\x0c\x13\xc3\xc3(\xe5\xd0\xfe\xa6-\x0b\x03\x9d\
\x82/\xed\xd0\xf1\x0e\r\x04\x06\x02\xa5\x88\xf7\xf4 \xaf\xd6\xa1Z\x1f\xa0Ba\
\x1cGaYV\x16\x06\x03\x9d\xf0\xba\x19\x12S\x98\x1f=$\xb6\xd7b\xbewPt\xe3,nk3\
\xb9+^\xe1o\xaeB.^\x8e\x10\xd9 \x96\xae\x81\x95\x1b\xe0\xc9\x03\xac\x8e;\x84\
\xdf\xb6!\xbb\xbaP/\x9e\xe3/[\xcd\xe4\xb1\x8bX%KPB\xa7Cf\x04\xd2\xe7\xa4\xb4\
\x11\xd5\xb5\x88_3\xa8\xfb\xb7p?=\x82\xc8$\xfe\xa6J&\xce7\xe2\xaf*\xc7\x8a\
\xc7\xb1l\x1b1\xc7\x82\x9d\x81\x10\xa4@(\x0b[\xe6 \x06#04\x06\xb1$\x0c\xfeDh\
\x81p\x14\x96\x00Kd\x8aNC\xd4\x19\xf2\xbe\x87s\xaf\x01\xf7\xca\x19\x18\x8b\
\x92\xda\xb2\x15\x1d.F\xbd\xfbJ\xf1\x9e]\xb8\x8f\x1fAn(\xfd\xfa\xac\x83\xbf-\
\xd8/\x9bQ\x8d\x97ad\x1c\xef\xc0Abw[H\\\xbb\x8d\xc9/\xc0\x8aD(<u\x1c\x19\x19\
\xc1(g^\xe5\xb3\x11\xaaj\x105\xfb0ek\xf1\x0e\x9d\xc4\x18\x83\xbfw/SM\x0f\t\
\x9d>A\xe2\xf0Q\xf4\x82\x02,?\x98\x17\xc1\xce\xecu\xb8(\x1f.\xdd\xc4\x00\nH\
\xa5\xc0\x18H\xed\xac\xc6\xfb\xf0\x1e\xe1\x1b\xc2\t\x0f\xdbV\xf3!F\xa7\xa7\
\x13\xf5W\x1a\x02)\xff4j\xd0\x08$\xc6h\x8c\x01\x93\xfe\x19\xc6\x180\x06!$\
\xf1\xe9\xd8LF\xe07^\x86\x00n~\xcd\x9b\x1b\x00\x00\x00\x00IEND\xaeB`\x82'
getdeleteperspectiveImage()
def images.getdeleteperspectiveImage ()
Definition at line 1311 of file images.py.
References getdeleteperspectiveData().
Referenced by getdeleteperspectiveBitmap().
def getdeleteperspectiveImage():
    stream = cStringIO.StringIO(getdeleteperspectiveData())
    return ImageFromStream(stream)
index.append('deleteperspective')
catalog['deleteperspective'] = ImageClass()
catalog['deleteperspective'].getData = getdeleteperspectiveData
catalog['deleteperspective'].getImage = getdeleteperspectiveImage
catalog['deleteperspective'].getBitmap = getdeleteperspectiveBitmap
#----------------------------------------------------------------------
getdemoBitmap()
def images.getdemoBitmap ()
Definition at line 1358 of file images.py.
References getdemoImage().
def getdemoBitmap():
    return BitmapFromImage(getdemoImage())
getdemoData()
def images.getdemoData ()
Definition at line 1323 of file images.py.
Referenced by getdemoImage().
def getdemoData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\xe8IDAT8\x8d\xad\x93\xcdO\x9b\x05\x00\x87\x9f\xb7\xed\xcb\xdb\x8f\
\x14F\xe8\x07lL\n\x1d-/k\xb72\xdan\x0b\xb8\xc4lx\xd8\x8c\x01\x13\x13c\xdc\
\xc1\xc4\x7f\x80\xf3\xfe\x00\xb9x\xd6\xc3\xa2x\x14\x8d\x1e\x14\xb3\x83\xd9e\
\xc8\xd6I\x0blmRR\x9b\xdab\xbf?^k)\xed\xdb/\xbc\xee\xe0a\x89>\xe7_~\xa7\xe7\
\x81\xff\x88\xf0\x1a\x1b\xbd\xcf\xe7\x9b\xf1\xfb\xfdWo\xddZ\xbeY\xad*\xcd\
\xf5\xf5\xf5\x07\xc0\xe0_\x0f&\'\'/\x04\x02\x81\xf9`\xd0\x1fXX\xb8\xe6\x9f\
\x9arxM&\xf3\x94\xda9\x13;\x1d\x95y\xd9\x89,\xcb\xdex<\x1e\x05\xd0\xcd\xce\
\xce\xce\xac\xac\xac\xdc^^\xbe\x11\xf4z./\xd8l\xe3\x97z\x03\xddH\xa1\xdc\xe2\
\xa4^ \x97\xcb\xd3l\x15\xa85M\xe4rE&\xc6\xc7X]]\xbd\xb7\xb1\xb1\x11\x05\x10\
\xb6\xb6\xb6~\xb9{\xef\x9d\xdb?=\xda#\x1a/\x93-\xaa\x08\xa2\x85\xc5\xcb&\xde\
\x0c\xda\xb0\xda. \xea4\xb4\xdb\xa7<\t\xa5\xb1\x9e\xeb3b\xea>\x0b\x04o.\x01\
\x03M2\x99(d\xb3\x05\x1e|\xfa\x98\xcdoS\x1c\xc4{\x88\xa2\x1e\xafl\xa1=\xb0\
\x93\xce\xf7H\xfd\xa9RV@v\xbdA\xbe\xd4dN\x96\x17\x9dN\xa7\x0c\xa05\x18\x8c\
\x13\x1f}\xf8\xfe\xdd\xdf\x0e\xf2T\x94\x1e\xfdA\x1f\xfb\xe8)&\xf38\x99\xc2\
\x19\x85b\x95z\xa3MUQ\xa9T\x15\xca\x95\x06\xcei\x8b\xf6\xefz\xf5\x8f\xdd\xdd\
\xa7\xbb\xdav\xbb-\xde\xbf\xff\xc1\xc7\xd9BS8\x88)\xf4{\x1d$m\x9d\x93S\x1d\
\x85\xca\x19\xc3f=\xad\xd6\t\xb9\x82B\xb1X\xe1\xc7G\x87\xe8\x87\x06\xdcy\xeb\
\xaa\xe9\xe1\xc3/\xbf\xd2d2\x99\xa3d2\x95\xbf2oG/\x19\xb9x\xd1I{`g\xdcj\xe0\
\xbcM\x87\xddb\xc0\xe7\x9dAvM \n\'4NE\x9e\xefgq\xbb\xe7\xfc.\x97\xcb\xad\x01\
\xaa\xe1\xc8al\xd6ae\xcc\xd1\xe0Ll0v\xceC\xb6:\x8ce\xd4\xc8y\x9b\x8eQs\x87^+\
G\xbf\x95\xe0\xed%\x91\xeb\x8b\x93\x18\x8d\xc3Ckkk\xefi\x00\xc2\xe1\xc8\xde\
\xa8YD\xf69\xf9k\xe9Wj\x8emF\x8c\x1a\x1a\xcd\x16\x89\xdf\xd3\x84\xc3\x11\xcc\
\xc6\x017\xae_\xa3|\xfc\x04]?E6\x9bUJ\xa5\x92 \x00x<\x9e\xd5\xef\xbf\xfb\xe6\
\x87\x97GZv\xcc?s\xc5\xec\xc0\xdd\xf5`\xb5I\x0c\x9b%4\x1aP\x14\xa5\xb7\xbf\
\x7f\x98\xda\xdc\xfc:\x99H$\xeet\xbb\xdd\xc7\xe9t\xfa]\x01@\x92\xa4K\xdb\xdb\
\xdb/\xa6\xa7\x1d\x06\t#\x08=\xca\xf5"GG\x89\xe3\xbd\xbd\xc8\xcbP(\xf44\x16\
\x8b\x85j\xb5Z\x14(K\x92\xf4\x89^\xaf\xff\xbc^\xaf\x7f\xa6\x03PU5\xb3\xb3\
\xb3\xb3\xaf(\xb5\xb9P\xe8\xf9a$\x12\tE\xa3\xd1g\xa5R\xe9\x05p\x0c\xf4^\xd5]\
U\xd5/\xba\xdd\xee\x90 \x08\x96W[p\x03C@\x02h\xbf^\x8b\xff\x03\xff\x00|\xf0C\
\xbc\xa9\xb6yV\x00\x00\x00\x00IEND\xaeB`\x82'
getdemoImage()
def images.getdemoImage ()
Definition at line 1361 of file images.py.
References getdemoData().
Referenced by getdemoBitmap().
def getdemoImage():
    stream = cStringIO.StringIO(getdemoData())
    return ImageFromStream(stream)
index.append('demo')
catalog['demo'] = ImageClass()
catalog['demo'].getData = getdemoData
catalog['demo'].getImage = getdemoImage
catalog['demo'].getBitmap = getdemoBitmap
#----------------------------------------------------------------------
getDocBitmap()
def images.getDocBitmap ()
Definition at line 1052 of file images.py.
References getDocImage().
def getDocBitmap():
    return BitmapFromImage(getDocImage())
getDocData()
def images.getDocData ()
Definition at line 1026 of file images.py.
Referenced by getDocImage().
def getDocData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\x15IDAT8\x8d\xa5\x931k\x14A\x14\xc7\x7f\'{\xc9y\x90\xbb\x8d\xa2\xd1\
$\x8aJ\x161\x04-N\xbb\x83\x10\xc1\x08b\xa1\x85\xdf becec%\xf8\x01$\x9dB\x8a\
\x94b\x11P!6b\xa5\x86D\x82\xb1\xf1\x0e1r\x85\xc8\xa5\xb9u\x03\xd9y\xef\xedX\
\\\xf6H\xe0\x02\x82\x03\xc3\xc0\xbcy\xff\xf7\x9b\xff\xbc)x\xef\xf9\x9f\x11\
\x00\xdc}\xbeR\xcb723lw.\xde\x9f^\x03\xb8\xfd\xe4UME\x10\x11D\x1c\xe2\xba\
\xeb\x87\xf9{k\x85\xb9g\x9fj\xc0\xea\xe9\xa3e\xb2\xcc0\xcb\xc8\xccH\x9d\xf0\
\xe3w\xe7\xa2\x8a06|\xf8\x0b\xdePUT\x04U\xe5\xeb\xf7_\x0c\x96\x06/\x07>\xb3U\
\n\x87xx\xf3|\x0f+\xcb2\x96?\xff\xa4\xd1j/\xab\x08\xd7.E\xdc\xb8rn\x1fzm\xee\
)\x03\xc5\xe2j\x00`f\x00lll`\xd6\xad435\xc5\xd9#\xc1\xc9\xa1\xa1\n\xa7F\x86Y\
__\xc7\xccH\x92\x84z\xbd\x8es)\xe2\x06\xba\x1e\xa8*\x00Q\x14af\x88\x08\xadV\
\x8b\xd6\xe6&\x93\x93\x93\xa4i\x99(\x8a\x10\x11\xe28\x06\xc0\xa5)np\x80\xc0{\
P\x11\x00\x1a\x8d\x06Y\x96!"T\xabU\xe28&M\xd3^LUI\x92\x84\xd1\xd1Q\x9cs\x88s\
\x04\x99)\xb2+\x10EQ\xd7(U\xda\xed6{\x9fxbb\x02U\xa5\xd3\xe9\x00 \xce!"\x04\
\xaa\x8a8\x87\xf7\x9ef\xb3\xd9\xf3\xa0R\xa9\xf4\x92\xf3XN0>>\xde\x15p{\x04\
\xf6\x128\xe7\xd8\xda\xda\xc2{\xdf\xa3\xc8\tr\x0fD\x04\x15G\xa0\xd2M\x00(\
\x95J\xbd\x8a\xe5r\x990\x0c\t\xc3\x90 \x08(\x16\x8b\xfb\x04\xf3\xab\x06"\x0e\
\x97\xa6L?X\xe8uX\x8ew\xab~\x01\xef=\x8bo>v+\xaab\xbb\x89f\x86\x8a\x12\x88\
\x08g\xc6\x8e\xf5\xed\xf3\x97\xefWPQ\xae\xcf\xce\xf4\x8d/-\xbd&\xd8\xd9\xd9a\
3\xfe\xb3\xaf\xc7s\x82\x13#\xc713\x96\xdf\xbe\xebK\x90\x99Q8\xe87Fw\x1e/lo\'\
WU\x84j8\xfc\xad\xf9\xe2\xd1l\xbfs\x07\n\xfc\xeb\xf8\x0b\x86F\x9b\xeen\xf6F\
\xb3\x00\x00\x00\x00IEND\xaeB`\x82'
getDocImage()
def images.getDocImage ()
Definition at line 1055 of file images.py.
References getDocData().
Referenced by getDocBitmap().
def getDocImage():
    stream = cStringIO.StringIO(getDocData())
    return ImageFromStream(stream)
index.append('Doc')
catalog['Doc'] = ImageClass()
catalog['Doc'].getData = getDocData
catalog['Doc'].getImage = getDocImage
catalog['Doc'].getBitmap = getDocBitmap
#----------------------------------------------------------------------
getexitBitmap()
def images.getexitBitmap ()
Definition at line 1409 of file images.py.
References getexitImage().
def getexitBitmap():
    return BitmapFromImage(getexitImage())
getexitData()
def images.getexitData ()
Definition at line 1373 of file images.py.
Referenced by getexitImage().
def getexitData():
    return \
"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\xecIDAT8\x8d\xa5\x92\xdfoSe\x18\xc7?\xef9o\x7f\xd8\xb5s\x1b+e?\xcc\
\xea4\x82\x9aH\x14\x1d\x86\x1fj\x14CB\x8ch\xe2\xad\x17^(7\x06\x8d\xd1D\xe3\
\xa5\x11\x07M\xa6w\xea\xa5\x89bDp\x98\xc5\x12\xc2\xc5\xd4\x10\x983\xc5\xad\
\xba9*\x1bc\xae[\xbb\x1e\xca`=\xa7\xed\xe9y\xcf\xeb\xc5f\xf9\x03\xf8\xde=\
\xc9\x93\xcf\xf3}\xbe\xcf#\xb4\xd6\xdc\x89$\xc0wB\xa0\x01\x05x\xb0M\x9a\xc6[\
\xb1d\xdf\xc1h__\xa7\xefy\x94\xaf]+\x17\x96\x96\xd3v\xc3\xfbT\xc1\x9f\xb5\
\x8d\xdeO\xb4^\x07\xfc/\x05\x87z\x07v\x0cm=|8\xb2\xe5\xd9\xe7\xb0\n\x05\xfc\
\x15\x8b\xb8\xf6\x12\xf9\x9fG_\x1b\x1f>\xfd\xeatn\xf6C`h}\xd6\x86\x03\xbd^\
\x1d\xda\xf6\xcaK_<\xf6\xf9\x97\xc8\xce\xcd\xdcZX\xe0jv\n\xe5\xd6\x91\x81\
\x00\xc9\x9d\xbb\xe8\xbe\xbb]\xc6\xbe?q\xf4\xd7?\xb2\x00\xc7\x00\x84\xd6\x9a\
\xaf\x85x\xa8k\xe7\x13\x99\xa7GF\xc22\x9e\xa0<9Iu~\x1e\x1d\x8f\xa3\x01gx\x98\
\x16\xad\x89\xf9\x9a\xc8\xcd2\xdf\x9c9\xa3\xb2\xcb\xc5\x81!\xad/\x19\x00B\
\x887\x1f|\xe7\xed\xb0\x8c'\xb8r\xea\x14\xf3\x99\x0c\xf9\xf1q\x84\xe7a\xb8.\
\xa5|\x1ek\xfbv\xae\xcc\xcd\xa2\x8a\x16\xbb\xba{Li\x1a\x1f\x00\x18\x00\xb1\
\xde\xc4\xcb\t\xb7\xc4\x8d\xd1\xb3\xf8\x86\xc9\xfd\xfb\xf6A~\x11\x1a\r\x84R\
\xe8\xc5E\x92{\xf6\xd0\xfe\xfa\x1b\xcc\xfd\x95E\xfa5\xda\xa2\xd1\xe7\x9b\x19\
D\xba\xbb6\xf9\xe9\x93\x14\xae\xae\xb1\xe5\xf49\xac\x93'\xe8\xd9\x14G\x86\
\xc3`\x9atUl\x8aG\x07\xe9=\x96\xe2b[\x07\x91\x7f\xe7\x88\x05d\xb4\t\xf0}M\
\xbdRE\x84\x83h\xd7E\xfd>\x86\xa1}\xea\x7f_\x064\xda\xb9Eml\x0cUu\x08&\x93\
\xd4sS\xa8p\xe4\xf6\x1f\xac\x96Wo\xd4\xef\xbdg\xb3\x99/a\xb6\xb7\xe1Ye\x16\
\xce\xa6Q\xe7~\xc4k\x80}\xdd\xa6c\xf7^d\xb4\x15],\xa2\x85\xc1\xaa\xdbp\x9a\
\x19\x94\xf2\x85\xb4eD\x91\xd7Wp\xcf_ \xf1\xf1 \x81D\x0f\xb5e\x1b\xc7\xb2i\
\xe9\xe8\xa4?\x95\xa2>3\x8d3y\t\xe7\xae\x10K\xb5\xfa/\xcd3\xa6\x84x$\xf9\xf0\
\xd6\xcc\xee\xfb\xe2\xb2\x92[\xa2\xeb\x874*\x16\xc1\x1e\x1eA+E\xeb\x8b/\x10\
\x08\x06\x998p\x80\xfa\xfc?\xfc\x86\xe1O\xae\xd9{\x8fk}\xc1\xd8\xd8#;3u\xf9\
\xfd\xccR\x85@g\x0b\x85\x83\xfbq\x8f\x7fK\xcb\x8eG\x89=9@\xf5\xa7\x11\xa6\
\x9fy\x8a\xc6l\x8e\x9c!\x99X\xb3\x8fH\xb8\xd8t\xf0\x99\x10\xd8 \x1dx\xb7\xbf\
\xbf\xef\xc8\x03\xd1\xa0h]\xb1\x90\xca\xc7\xf7\x14kv\x95R \xc0\x8c0\x98\xa88\
\x83\x1a>\n\x81\xf3\x95\xd6\xb7\x01\x0e\xe0\x00Ux\xdc\x0c\x85\xde\xeb\x08\
\x87\xf6\x87\xf0\xa3J)V\x95vV\x1a\x8d\xd1\x9b\x9eJ\x19p^\x00\x01\xa0\t\xb8\
\x13\xfd\x07\xd6\xc1c\x17\x8b?][\x00\x00\x00\x00IEND\xaeB`\x82"
getexitImage()
def images.getexitImage ()
Definition at line 1412 of file images.py.
References getexitData().
Referenced by getexitBitmap().
def getexitImage():
    stream = cStringIO.StringIO(getexitData())
    return ImageFromStream(stream)
index.append('exit')
catalog['exit'] = ImageClass()
catalog['exit'].getData = getexitData
catalog['exit'].getImage = getexitImage
catalog['exit'].getBitmap = getexitBitmap
#----------------------------------------------------------------------
getexpansionBitmap()
def images.getexpansionBitmap ()
Definition at line 1454 of file images.py.
References getexpansionImage().
def getexpansionBitmap():
    return BitmapFromImage(getexpansionImage())
getexpansionData()
def images.getexpansionData ()
Definition at line 1424 of file images.py.
Referenced by getexpansionImage().
def getexpansionData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02UIDAT8\x8d\x95\x92=o\\e\x10\x85\x9f\xf7c\xf7nlcol\x85\xc8\x05\x14HX\
\xa2\x08XH\x81"Q\xa4H\x06\x916\xa1\x87\x86"\x12?\x00\x89\x1f\xc0\x7f\xa0w\
\x83D\x85hh\\\xd0@\x83\x85\x14\x89\x84\xc2\x92\x8b4\xb6\xacX^\xef\xde\xbd\
\xf7}gN\x8a\xdd`>*N33\xc593gf\xc2\xado\x8e\x7f\xda\x1a7\xf7k/\xfai\xa5o\x8d\
\xbe\xad\xf4\xb3\xab\xbc\xcc\x8d~f\x94\xb6P;\xc7\xbb\x8a\xea\x1c\xb5\xc7\x07\
\xf9\xe6\x8d\xd5{\xbb;\x9b\xf9\xfc\x1c./`:\x85\xc9\x05L/\x16\xb5\x02\x14\x03\
\x8b\xd0\x1bx\x07\x08\x08\x80~\xbc\x977G\xa1\xbc\xbdF3\tP\xd6\xe0r\x02\xf3\r\
h\xe70o\xa1\x9d-c\x0b\xed\x14\xfa\x0e\\\x10\x11\x7f\xfe\x9eK\xde\xd9\x12\x9f\
\xbf\x0b\xa7\xa7g\x1c\x1e\xfe\xc6\xde\'\x1f\xc1\xb2\ti\xd1I\x02/`\xd517\xbc\
\x8af\x00\x9f}\x1d\xc9\t\x18D\x18\x04\xc3\xfa\x19\xcd\x80+\x9c=\x81\xd9\x19\
\x84\x80^\x7f\x1f\x1f\xadP\xab\xf0,\x9a\x049\x8a\x8c\x1b\x00.\x91R\xe6\xef\
\x98\x7f\xff\x05\xf6\xc7\xaf\x90 \x7f\xf93z\xe3\x0eV\x85\xbb\x88\x80\x99\xc8\
\xb6\xe0\xd34\rGGG\xec\xef\xef\xd3u\x1d\xbb\xb7\xef\xb2;\xde\xa2[m &D\xa2\
\x1a\xc8\x1d3\xc7\x03\xb8\x9c\x8c\x04@)\x85\xed\xedm\xf6\xf6\xf6\x90\xc4\xb5\
\x95U\xea\xd3\x15X\xd9\x80\x980\x12ra\xe6\x98\x89\x8apw\xb2\x96\x02\x92\x18\
\x0e\x87\x8c\xc7\xe3e\r\xf5\xd3\xef\x88\x80W\xf0\xae\xa7\xb63\xdc\x17\x16*B\
\x12\xd9]\xfc\x1b\x12\xd4\xe2\xd80"\xa0\xc4\xc5\xe9\xbc\n\x93\xe3\xeeD-\x05p\
\xff\x8b\x18\xc2\x95\x80\x06\x11\xfd\xf0\x18\x8e\x7f!\xa5\x84}\xfc-\xb6y\x0b\
\xef\xa6\x98\x89\xe8B\xe2j\x07\x00\x93\xc9%\'\'\'\xf4}\xa1\xd9\xd8\xe4\xb5\
\xd3g\xe8\xf9\x13bJh>\xc1=b\xb6\xb0\xe0Q \x91_\xf1\xd7\xd7\xd7iF#\x0e\x0e\
\x0e\xe8\xba\x9e\x9d\xf7>\xe4v,\xd4b\xe0\x86\xb9a\x0e\xeeZL\x80# \xa7\xc5\
\xcf1\x1a\x8dx\xf4\xf0\xe1?vQ\xc2c\xc2[\x0f\x10\x81\xe6\xfa\x9b$fX2<\xc20\
\x8bA\n\x84\x0f\xbe:|\xf1\xcev^\xebf\x85\xdaWj\xd7SK\xa1v\x86\xa9\xa1\xd4@\
\xed\x0b\xde\xbe\x00\xaf\xbc2\x9cb\xe0\xe9\xd1\xf9e\x90\xfe{\x85\xff\x83\x97\
\x08{\x81\x04G\xd2\xe2\xfd\x00\x00\x00\x00IEND\xaeB`\x82'
getexpansionImage()
def images.getexpansionImage ()
Definition at line 1457 of file images.py.
References getexpansionData().
Referenced by getexpansionBitmap().
def getexpansionImage():
    stream = cStringIO.StringIO(getexpansionData())
    return ImageFromStream(stream)
index.append('expansion')
catalog['expansion'] = ImageClass()
catalog['expansion'].getData = getexpansionData
catalog['expansion'].getImage = getexpansionImage
catalog['expansion'].getBitmap = getexpansionBitmap
#----------------------------------------------------------------------
getfindBitmap()
def images.getfindBitmap ()
Definition at line 1504 of file images.py.
References getfindImage().
def getfindBitmap():
    return BitmapFromImage(getfindImage())
getfindData()
def images.getfindData ()
Definition at line 1469 of file images.py.
Referenced by getfindImage().
def getfindData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\xdeIDAT8\x8dU\x93Mo\x1bU\x14\x86\x9f;\x1fwf\xec\x19\x7f\xc6\x934Np\
\x8d\x92\x96\x80\x04\x95@\xa5U%\x84 \nH]\xb0-\x9b\xee\x80MYA\xc5/h\x17\xb0*\
bC\x85\xb2`\xc1\x8a\rEE\x08\xa8\x00U\x88@iB\xa2@\x92\xa6\x89\xd26\xa8qj\xc73\
\x89\x9d\xf1\xcce\x91\xc6\x89_\xe9HW\xe7\xdc\xfb\xe8\xd59\xe7\n\xa5\x14\x00W\
\x7f\xb9\xed\xe6\xb3\xce\xcd\xfeBj(I\x926\x8f\x14+h\xed j\x0f\x03k~a\xfe\x93\
\xad \xbc\xe0\xa4\\VVW\xb9\xf8\xd19\x8c\xfd\x8bJ\xe4]\xcb\xab\x0efl\xc0\xde\
\xcb\'@=\x84D\xc1\xf1\xe7\x9e\xf9\xf0\xd6\xd4\x9c\xdd\x0c\xc2\xf7\xf7\xea\
\x1a\x07\x94\x1c8+\xa5PJ\xa1\x01\xd2\xdc\xcd\r\x14,N\x8f?\x7f\xde\xf7K\x9f&I\
,\x80}\x07\xa641\rA+\xdcfr\xf2_\xda;\x11v\xcab` \xcf\xc0p\x19\xcf\xb5\x99]\
\xb8G\x0ch\xa6\xf3\x8e\x10F\x068\xdb\x05\xac\xcc/\xd3ix\\[\\\xa2X=\xccHu\x08\
\xc7\x10\xdc\xaf5Y\xfbo\x96\xca\xe8\x08\xa5\xbe\x12\x8bw\xee\xa10\x10B\x7fS%\
\xc9\xe3]\xc0O\xdf\\\xf3\xfd\xa1A\xfb\xc8+\xaf1\xf6b\x95\xa2\t\x12\xb0+\xfd\
\xac\xcc\xae\xb2\xbcp\x9bt\xb1\x9f\x8c\x97\xc6\x90\x0e\x96e\x08\x85\xd2\xba\
\x80\x9dv\xeb\\\xcb;\x9cu+U6\x1eB\xe4\x80\xd4\xa0\xa5`\xd3=D\xe7\xee\x06\x87\
\xe4&\xae\xebaH\x0bS\x9a\n\x85\xda\x9fB\x1c?\xbd\xbe\x9da}\r\xcc6\x04\xe9\
\xdd\xae6[\xb0\x11h8Q\x9a\x8a\x01\xb6-1\xa5\x85\xa1k\xbdS\x08\xc3\xad\x9a\
\x95lRHAVB\xc1\x02O\x82\xa5@t\x04\xaa\x1d\xa0\t\r\xdb\x928\xb6\x89\xa1\x89^\
\xc0f\xa3\xf9ec\xf1\xf7\x8e\x16\xd59:\x02\xa3e\x18\x1b\x86#U(\xe9\x0fp\xe2\
\x06\xe9B\t\xdd0\xd05\x10\x9a\xde\x0b\x18?\xf3\xfa\x8d\xb1\x11\xbf\xf6\xc3\
\xc4\x15f~\x9bC\x04\xdb\x88`\x9b\xbb\xd3\xff\xb0t\xe3:a\x10\xc1\xf2\xb7\x88\
\x9d:\xba\t\xe2\xd1\xbbn\x0f^zc\x9cr\x9f\xc3\x9d\xe9i\xbe\xff\xfa;n\xfe\x98\
\xc1vl\n\xb9,\xe5\xfe"\x0f&\xbf\xc0\xf3k\xe8\xed\xeb\xc4\xc7>F\x18V/ \x0cB\
\x92\x9c\xe4\xd5\xd3\xa7x\xe1\xe5\x13l4B\x94\xd2\xc8\xe4\\\xb6\x9au\xfe\xfc\
\xeb=\xf2\xb2\x88=j\xd2\x9c\xfd\x80Nx\\\x81\x16\xf7\xac\xf2\x9e-[\xea\x0c\
\x962\x94}\x97\xb4\x84\xbeb\x8e\xa7\xde\xbd\xca\xad_\xebDs\x7f\x90\x19KqR\
\xff\xdc\x1e\xce)\xbf\xeb@\x1a\xa6\x9a[Z\r\xa7\xfe\x9eJ\x14z[\x01q\x02J\xed\
\x860=\xd6J\x17\x98\x998\xaf\xbf\xad\x12y\xf2\xd9\xc7\xec\x13G\xf3ou\x01\xb9\
\\>\xb8\xf2\xd9\xa5S_M\\\xce\x818\xf8\xaf\x0eH\x8f*Y\xfch\xfd\xe7\xcb\xd1\
\x13g\x8f\xcdl=\xd9\xfc\x1f\xfc\xf7\x0c{\xf4\xc4\x89e\x00\x00\x00\x00IEND\
\xaeB`\x82'
getfindImage()
def images.getfindImage ()
Definition at line 1507 of file images.py.
References getfindData().
Referenced by getfindBitmap().
def getfindImage():
    stream = cStringIO.StringIO(getfindData())
    return ImageFromStream(stream)
index.append('find')
catalog['find'] = ImageClass()
catalog['find'].getData = getfindData
catalog['find'].getImage = getfindImage
catalog['find'].getBitmap = getfindBitmap
#----------------------------------------------------------------------
getfindnextBitmap()
def images.getfindnextBitmap ()
Definition at line 1554 of file images.py.
References getfindnextImage().
def getfindnextBitmap():
    return BitmapFromImage(getfindnextImage())
getfindnextData()
def images.getfindnextData ()
Definition at line 1519 of file images.py.
Referenced by getfindnextImage().
def getfindnextData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\xedIDAT8\x8dm\x93Il\x1bu\x14\x87\xbfY=Nl\xcf8n\x9c\xc8I\x9c\xb8Y\
\x9c\xb0\xa9\x05\t\x1a\x02\x08A\xca*\xc1\x81\x03\x17\x10(\'\x96\x0b\x07$Z\tq\
\x05q\x888\xd0SEU\xe5\x80\x10\\\xb8P\xa9,\x05\x03QZH)4\x04\xc2\x92\x14**\xda\
\x12\'vg\xc6\x9e\xf1,\x7f\x0eML"\xf1\x93\x9e\xf4\x0e\xef}\xfa\xe9-\x92\x10\
\x02\x80\x13_\xaf\xa5\xb2f\xf2\\OWG\x7f\x1c\xc7>[\x8a\x04XGg\xcd8\x0c\xc5\
\xc5\xce\xdc\xe9;^}\xf9NvH\xfe\xafPH\xd9T"]*d\x8c\xe1~\xcb\xdc\x8e\x91\x01\
\xcb\x0c}\x1fc\xff~\xa9\x887y\xe6\xd0kg\xff\x17\x00\x10\xef\xc8\x85\x10\x08!\
\x90\x81\xd0u\x11a\x88^,R\x08\x1b\xb7\x9e\x9ey\xee\xe7C\xaf\x1f\x97\x00\xd4\
\xed\x06M\xd7\xd0T\t\xcfm\xb2\xb8\xf8+~+\xc0\xe8H\xd0\xdb\x9bEm6\x89=\x8f\
\xd0q\xd0\x87\x87\xe9\xae~3>\xf5\xd9\x07\xab\x1c~vo\x1bp\xf1\xb7?\t\xebiN\
\xae^ W\x1ab\xa4\xd4OR\x95\xf8\xbbj\xd3[\xaf\x13y\x1e\xadj\x15\x00\xbd\\f\
\xef\x95+\xa5S\x85\xc2\xa56\xe0\x8b\x8fN\xe6\xf3\xfd\x05c\xec\xe0CL\xdc["\
\xa7\x81\x0e\x18\x83=\xb4j5b\xdf\'\xb2m$MC\x02\xe2f\x93V\x14\xad\xb4\x01-\
\xdf\x9b\xf1\xd2Cfj\xb0\xc4\xc6&\x04I\xd0e\xf0\x04\x18[\x0e\x00PU6+\x15~\x17\
\x89`\xe6\xea\xd5\xe7\xdb\x80(\x8anYofX\xbf\x0c\x9a\x0fN\xe7\xf5\xa9\xda\x1e\
\x94k5B\xc7A\xd246+\x15\xdc\xa1q\xd6\xee~\xaca\x7f\xf9I\xd4\xde\x82\xeb6\xaa\
\x89\xf8\x1a]\x1d`\xea\xd0\x95\x80\xb4\x0e\t\x01A\xa3\x81\xf0<6\xe7\xe7\xf1F\
ob\xe0\xad\xa3\xa8\xb2\xb4{\x8d\xd7\xea\xf6\xbb\xf5\xd5oC9\xa8Q\x1e\x81\xd1>\
\x98\x18\x80\xb1\x12DB\xb0\xbe\xb0\x803v3=o\xbc\x8d"\x83$+\xbb\x01\xd3\x8f?\
\xb201\x92\xaf\x9e\x9a;\xc6\xf2\x99\x15$\xa7\x89\xe44\xb9\xb4\xf4\x0b^\x14\
\xb1f\xf6\xd1=3\x8d\xd4\xaa\xa1h m\xf5\xb5gp\xdf\xa3\xd3\xf4\xedI\xf2\xc7\
\xd2\x12\x9f~\xf81\xe7>\xcf`$\r\xba,\x13c\xf6=\xfeY<\xce]\x1b\xc7P\xfc\n\xd1\
\xbeY$5\xb1\x1b\xe0:.\xb1\xa5\xf3\xc0\xc3S\xdcs\xff\x016\xea.B\xc8d\xac\x14\
\r\xbb\xc6w\xdf\xbfHV\xcfa\x8cj\xd8?\xbdB\xe8\xde.@\x8ev\x9d\xf2\xb6-CW(tg\
\xe8\xcb\xa7\xe8\xd4aO\xce\xe2\xc6\x17N\xf0\xc3|\x8d`\xe5,\x99\x89\x0e&\x95w\
\x8c\x01K\xe4\xdb\x0etU\x13+\x17\xfer\xcf\xffx>\x16(\xbe\x00\xa2\x18\x84\xb8\
\x1e\x92\x96\xe6r\xf7a\x96\xe7^R\x9e\x16\xb1>y[\xd18P\xce>\xd1\x06<8Yt\x9e|\
\xe6\xcd\xa9\xf7\xe7\x8eX \xed\xfc\xab\x1dR\x82A\x93|\xb0\xfe\xd5\x91`\xfc\
\xa9}\xcb\x8d\x1b\xec\x7f\x01\x00\x016\x03\x14F\xf4\xdc\x00\x00\x00\x00IEND\
\xaeB`\x82'
getfindnextImage()
def images.getfindnextImage ()
Definition at line 1557 of file images.py.
References getfindnextData().
Referenced by getfindnextBitmap().
def getfindnextImage():
    stream = cStringIO.StringIO(getfindnextData())
    return ImageFromStream(stream)
index.append('findnext')
catalog['findnext'] = ImageClass()
catalog['findnext'].getData = getfindnextData
catalog['findnext'].getImage = getfindnextImage
catalog['findnext'].getBitmap = getfindnextBitmap
#----------------------------------------------------------------------
getinspectBitmap()
def images.getinspectBitmap ()
Definition at line 1604 of file images.py.
References getinspectImage().
def getinspectBitmap():
    return BitmapFromImage(getinspectImage())
getinspectData()
def images.getinspectData ()
Definition at line 1570 of file images.py.
Referenced by getinspectImage().
def getinspectData():
    return \
"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\xbcIDAT8\x8d\xa5\x93[H\xd3Q\x1c\xc7\xbfg\xff\xddt\x17\xafs*s\x16&\
\x16\xe6\x15\xd34\xb7d\x19\x96\x05\x12\n\x15I\x84\x08\xf5\xe2\xa5\xdbCD\x81\
\xe5\x9b\x0fj>\x85a\x05\x05\x95>J\x84Q\x16M\tGF\xa1\xcbk\xe56un\xfb\xdb\x96\
\xee\xe2\x9c\xff\xd3C\xcb\xe6\xc0'\x0f\x1c8\xfc~\xe7\xf7\xe3\xf3\xfd\x9d\xef\
!\x94R\xecd\xf1vT\r\x80\x1f\x1e\xa0\x1c\xf2;\xdb_<\xb0\xcc\xcf\xe5\x05\x02\
\x1cX\x87\x1d\x02\xa1\xc8x\xa7\xb5!W\xa5J\\\x0f\xbfOB%\x94i\xabcj\xaak\x96K\
\xb59\xfey\x93\xc9;\xf8\xea\xbd[\xaf\xff\xe4/\xd6\x1dS-.\xfe\xe4\xcb\xa4\xf1\
\xe9\xdd=\xb7g\xb6%\xd8\xb77wyn\xf6\xebR\xed\xb9\x13rU|r\xc03&\x9a\xe0\xc7\
\xab\x1c\x86\xfe\xb7\xf3\x19G\xf2\xb3\xac6\xd34\x00\x12Z\xc3\x03\x00\x8dFC.7\
\xb6\xd7\x18\x86\xde\x98\x0e\xa4i\x17\x8d\xef\xcc\x93\x0bS\xac\xd5\xed\xf2\
\xb8\x00\xac\x14\xa7V\xcc}{m\x18/(\xd0\xe1JS\xfb]B\x08o\x0b\x81^\xaf\xe7\x97\
\x95^\xe8t.\xb0\xab\x93/\xed\xe3\xd3\x0c\xeb'\x11\x1c\xcb\xc8\x03\xbf]^\xd6%\
\x16D*\x0b\xd4:j\xb3\x983\xe4qqM\x00Z\x01\xacm\x12\x00\x10\xf9|\xee\xa4xi\
\xe2*\x8f\xf0\xd77\x02\x9c\xd3a\xb3\xcf\x0c\x8f\x0c\xe9g\xd8\xb1Q\x8f\x7fe\
\x9aG\x18;k\xb5\xba\xf6g\x16\xc9\x00\x08\xb7H\x00\xc0\x88\xc5\x92>\x97\xef\
\x97\x98!L\x80!\x8c_\xc0\x08\xdd\x04`\xd76\xbc6!?\xc2I\x08\xd6\xb2\xf2r\xa4\
\xc9\x89\xea\x91\xd0\xd9\xfd;\xd0\xee\x9e\x96.\x99 \xfa\xa9\xc3\xb3\x18\x99 \
Q\xb9\xe5\xe2\xb8\xe8\xc2\x94r%\xa5\\\x80\x10\x12=\xfcc \xad\xff\xe6#E\xf1!\
\xdd%\x004\x9c`}\xc9f\xb6W\x9d\xa9\x9fx6\xdaUhs[b\xa5By\xb2\\\x14\x93\x15%\
\x8e\xcd1\xda\x0c\x87koUi\x8d\x93\xdf\xbf|\x1c\x19\x9c\x01\xb0\xe9\x07B)\x05\
!\x84\x01\xa0\x00\xa0\xbe\xda\xdcymj\xec\xb3n\xdc`\xb0\x88y\x91^\xb9R&\xed\
\x1dx\xb2g\xd9\xf8p6;\x96d\xaaO\xddK\xb7,,\xcdq\x1c\xb7\xbe\xc5H\x84\x90H\
\x00\xca\xe0F\xc5\xd1\xd3\xf9\x89JI\x82\xc7\xe7v\xf4\xf6=\x1f\x05\xc04V\xee>\
_Y\xae\xa9\x9fr\x8aS\x1bZ\xee\x9b\xfe\x8a\xa7\x14\xc1&<\x00\x12\x00)\x00\xb2\
\x01\x14\x01(\x01p\x10@\x1e\x80]\x00\xa47\xaa\xd3\xbb\xda.j\xa9y\xec\xc3qJ\
\xe9\xff\x06\x94R\xb4\xb5\xb5\x91\xe0\x13\xc9\x01$\x00H\n\x12E\x01\x10\xd6\
\xd5\xd5\x11J)jK\x14=\xd7\xcf\x96\xd0\x8e\xe6\x93\x1dd\xbb\xef\x1c\xea6J)\
\x17\x9e\xaf\xc8U<vz\x02e\x7f\x00\rI)O\x04\xf4\x8b/\x00\x00\x00\x00IEND\xaeB\
`\x82"
getinspectImage()
def images.getinspectImage ()
Definition at line 1607 of file images.py.
References getinspectData().
Referenced by getinspectBitmap().
def getinspectImage():
    stream = cStringIO.StringIO(getinspectData())
    return ImageFromStream(stream)
index.append('inspect')
catalog['inspect'] = ImageClass()
catalog['inspect'].getData = getinspectData
catalog['inspect'].getImage = getinspectImage
catalog['inspect'].getBitmap = getinspectBitmap
#----------------------------------------------------------------------
getMainBitmap()
def images.getMainBitmap ()
Definition at line 1236 of file images.py.
References getMainImage().
def getMainBitmap():
    return BitmapFromImage(getMainImage())
getMainData()
def images.getMainData ()
Definition at line 1210 of file images.py.
Referenced by getMainImage().
def getMainData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\x00IDAT8\x8d\xad\x91?k\x14Q\x14\xc5\x7f\xf3f6f\xb3k`\xdd` \xec\x86\
\x80\x12-TP\xc4R\xc1T6\xe2\x17\xb0\x11\xfc\x06\x01S\xf8\xa7\x15\x02!\xc1\xc2\
JK+\xf1\x13\x18\xb1\xb2\x08\x16\x11\x115.\x88Q\x82\xc9B\xd6\x1d7\x19g\xe6\
\xdd{-\xd6\xac\t\x1bm\xf4t\x97\xfb\xce\x8f\xf3\xee\x81\x7fT\xf0\xa7\xc5\xdc\
\xdc\xdc\xb1\xe1\xe1\xe1\xc7f&\xedv\xfb\xf2\xf4\xf4\xf4\xea_\x01\xf9\xbd\x13\
ST\xeaw\x8d`\xb2\xa9\xd5p\xf3\xe8\xd5\xe2\xd0\xe8\x11W(\x14\xd8l,I\xe5\xed\
\xfd\x1f\x15\xbf&\xe6YI\x93\xad\x99\xc37W\x17\x01\xa2\x1ejd|\xd6U\xab\xa7\
\xddH\x99w\xcdK\\8w\x91<\xcf\x01\x18\x1b\xbb\x12>O\xa3\xd2\x94<\xc4o\'g\xe5\
\xf3\xc7Y\xe0\xcc\x1e\x80j0\x19\x1d*\xf3\xe0\xe5I^\xbfy\xca\x8b\xa5W\x88\x08\
\x00\xce9\x9a\x1bM>\x1d?\xcf\xb5\xda3|\xa6\x93;\xbe\x1e\xc0DAr\x8aC%\xe6\xe7\
\x17\xf6\xfcS\x04\xbc\x87\xdb\xb7f\xa0\x1e \xe2\xe9\x03\xa8)x\x8f\x99\xd2\
\xe9x\x1a\x8dm\xc20"\x8e\xd7i\xb7\xd7\xa8\xd5j\x98\x01\xaa\xe4\xbf\x92\xed\
\x05d\x19H\x8e\xaaQ.G\x8c\x8f\x1f \x08\x1ci:J\x92T\x18\x1c<\xb8\x93\x15\xdd\
\x17 \xde!\x8a\x99\xd1j\t\xcb\xcb\t\x03\x03\x05:\x9du\xe2\xf8\x0b\x13\x13\
\xf5\x9e)\xf3b\xfd7\xd04\xc0{D\x0c\x11\xc5\xb9\x143\xc19%\x0c!\x08\x1c` \x8a\
\xa9h\x1f@\xf2\x1cD03\x92$\'\x8e\xbfR(D\xe4\xf9\x16Y\xf6\x9d,\xcbv\xea"\xff\
\xed\xdf]cN7A\x80sCT*%\xc2\xd0\xe1}D\xb1\x18Q*U\xbbG4Cu\x9f\x16\xf0\xdd\x04\
\xa4-\x16\xe6ot\x1f\xef\x92\x19\xd4\xab%\x10A\xf7M\xe0\xfdJ\xda\x8eO]\xaf-B=\
\x00Uz\x14\xd5\xde\xdc\xdah\x82\xd9\x87>@\'\xfevG\xcc?\x11o\x81\x99\x80\x19^\
\x15\x11\xc5\x8b\xe0E\x10\x11\xbc\xca\xfb I\x1f\xf1\xbf\xf4\x132b+ao\xc1`\
\xed\x00\x00\x00\x00IEND\xaeB`\x82'
getMainImage()
def images.getMainImage ()
Definition at line 1239 of file images.py.
References getMainData().
Referenced by getMainBitmap().
def getMainImage():
    stream = cStringIO.StringIO(getMainData())
    return ImageFromStream(stream)
index.append('Main')
catalog['Main'] = ImageClass()
catalog['Main'].getData = getMainData
catalog['Main'].getImage = getMainImage
catalog['Main'].getBitmap = getMainBitmap
#----------------------------------------------------------------------
getmodifiedexistsBitmap()
def images.getmodifiedexistsBitmap ()
Definition at line 1639 of file images.py.
References getmodifiedexistsImage().
def getmodifiedexistsBitmap():
    return BitmapFromImage(getmodifiedexistsImage())
getmodifiedexistsData()
def images.getmodifiedexistsData ()
Definition at line 1619 of file images.py.
Referenced by getmodifiedexistsImage().
def getmodifiedexistsData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\t\x00\x00\x00\x0e\x08\x06\
\x00\x00\x00\xfd\x946\xa8\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x01aIDAT(\x91e\x90K+\x84a\x18\x86\xaf\xf7}?c\xc6\xf8\x8c\xe93\xa7\x9cBV\
\xe2\x07)~\x80&\x1b\x94\x85\x85\xb2 \x0b{\xf9\r\nKC\x96\xb2\xb5\xb1QV$\x87$\
\x8d\xc6L\x86\x91\x9c\xc6ga\x90\xc7\x02\x83\xdc\xf5\xac\x9e\xab\xee\xbb\x0b\
\xa5\r\xdfW\xe2\x94J\xb0;,\xc4\xb4L\xccLJ\xf1\xa7\xb4\x01`xvD\x02\xf1\x08\
\xe7&\xc7\x99\x9bAm\xbe\xd0\xbe\xd3\xca\xdc\xfc\x82\xd2\x00\xb5\r5\xd2<\xd8B\
y\xd4\xa6\xb2\xa4\x02\xbb1\x00\xf5\x86\xe5\x95e\x004\x80(\xe1\xc4\x9cq\xcc)\
\xb7Owd\xb8\xe0\xf1"O\xbc/\x0e\x80\x05\xe0/\xf3\x93\xcc&q\x1b\n\x987\xc8\xe3\
\xf2\xbc}Ebi_\x15!m4\xb9\xf7k\xde\xb3p\x1b\xcb\xe3\xec\x96\xe3\xae>\xf2\x1d\
\r\xe0\xf3\xfb0\xf7\n\xef\xb5E(\x1d\xc0I\xd9D\xec\xf0_\xc8\t:\x18W\xf1Vx\xc5\
\xca\xc2\xcdF\x8e\xc1\xfe\x81"TT\x10\xea\x89J\xb0#\x8c\xbb\xf7@\xe82\xc0\xc1\
\xce\xa1\xfa\xa1\xbe\x84\x8dN\x8f\tM\x968ma\xf9-Xi\xf3Yg:\xbc\xe2\x99r\x18Z\
\x1f\xc5\xbbU\x87\xd5\xee\x13~E\x03\xf4v\xf6\x90L%I=e\xf0\xa4\x155\x91j&\xa6\
\xc6\xe5\xcf\xa6hKL\xbc\x89\x18\xf7\x95.\xf6\x91\x07k\xb1@z\xed\xf4\xff&_U\
\x99Pg\xc4\xe9\x8a\xfe\xdb\xf4\x01\xb4\xabp\xe3-6"\xdb\x00\x00\x00\x00IEND\
\xaeB`\x82'
getmodifiedexistsImage()
def images.getmodifiedexistsImage ()
Definition at line 1642 of file images.py.
References getmodifiedexistsData().
Referenced by getmodifiedexistsBitmap().
def getmodifiedexistsImage():
    stream = cStringIO.StringIO(getmodifiedexistsData())
    return ImageFromStream(stream)
index.append('modifiedexists')
catalog['modifiedexists'] = ImageClass()
catalog['modifiedexists'].getData = getmodifiedexistsData
catalog['modifiedexists'].getImage = getmodifiedexistsImage
catalog['modifiedexists'].getBitmap = getmodifiedexistsBitmap
#----------------------------------------------------------------------
getMondrianBitmap()
def images.getMondrianBitmap ()
Definition at line 18 of file images.py.
References getMondrianImage().
Referenced by getMondrianIcon().
def getMondrianBitmap():
    return BitmapFromImage(getMondrianImage())
getMondrianData()
def images.getMondrianData ()
Definition at line 8 of file images.py.
Referenced by getMondrianImage().
def getMondrianData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x00qID\
ATX\x85\xed\xd6;\n\x800\x10E\xd1{\xc5\x8d\xb9r\x97\x16\x0b\xad$\x8a\x82:\x16\
o\xda\x84pB2\x1f\x81Fa\x8c\x9c\x08\x04Z{\xcf\xa72\xbcv\xfa\xc5\x08 \x80r\x80\
\xfc\xa2\x0e\x1c\xe4\xba\xfaX\x1d\xd0\xde]S\x07\x02\xd8>\xe1wa-`\x9fQ\xe9\
\x86\x01\x04\x10\x00\\(Dk\x1b-\x04\xdc\x1d\x07\x14\x98;\x0bS\x7f\x7f\xf9\x13\
\x04\x10@\xf9X\xbe\x00\xc9 \x14K\xc1<={\x00\x00\x00\x00IEND\xaeB`\x82'
getMondrianIcon()
def images.getMondrianIcon ()
Definition at line 25 of file images.py.
References getMondrianBitmap().
def getMondrianIcon():
    icon = EmptyIcon()
    icon.CopyFromBitmap(getMondrianBitmap())
    return icon
#----------------------------------------------------------------------
getMondrianImage()
def images.getMondrianImage ()
Definition at line 21 of file images.py.
References getMondrianData().
Referenced by getMondrianBitmap().
def getMondrianImage():
    stream = cStringIO.StringIO(getMondrianData())
    return ImageFromStream(stream)
getmoredialogBitmap()
def images.getmoredialogBitmap ()
Definition at line 1677 of file images.py.
References getmoredialogImage().
def getmoredialogBitmap():
    return BitmapFromImage(getmoredialogImage())
getmoredialogData()
def images.getmoredialogData ()
Definition at line 1655 of file images.py.
Referenced by getmoredialogImage().
def getmoredialogData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x01\xafIDAT8\x8d\x9d\x92\xcdk\x13Q\x14\xc5\x7fo2-bE\x83m\n\rC\x105](~P\
\xdc\x8c\xe4\x8f\xb0R\xe8? \xda\xee\xbb\x1b\n\xb6\xa4\xab\xee\xbb)~,u\xd1\
\xbd(\xe8"af\xe1\xc6.\xc4FbH\x16\xbaP\xacZH?\x06_\x8f\x8b&\xe9D\x13\x83\x1ex\
\xdc\xc7\xbd\xf7\xdcw\xce{\x0fI\x0cZ\xa9)g:\xb3tf3\xb3\x94\xdeLM9\xd3\xc9\
\x9a).\x17\xc5\x00T>V\xb8z\xe72V\x96w\x0f+\xe4\xb3\x93\x00\x04\x8b\x81q[\x1b\
\x8cY\xe9;\xe0\xc4\xb8%\x7f7\xc6\xca\xf2t\xc3\xb2\xf79\xc0\x18C\xb0\x18\xe0\
\x02}\xc8q+\x1aHYv\xed\x17\xac,&e1\xe6\xfeQ\xc5\x98\x11\x17@\n\xfe\xa0\x9f[\
\xf7\xb8\xe1]\xc71bX w\x08\xc9r\xeb\xc1w\x9a\x94\xa97.\xf2\xe1\xb0\xf1\xc9M\
\x92\xa2r\x84_\xf0\x89\xca\x11\x17F\xc7\xb9\x99?\x0fN\xccO\x9a|\xdd\xddF\xb2\
\\\x99L\x13[q)w\x96go\xe3\xd3n/\xb2_\xf0y}\xafJ\xfd\xcd\x0f\xf6\xf7\xf69p\
\x0e\x98\x99\xcd!\x0eY\x7f\x141vj\x8cZ\xad\x06ClS\\.\xaa\x8d\xb0\x14\xf6\x8c\
\x0b+\x0b\x9a\xab\x8eh\xaezRkO\xd6\x14\x96B\x01\x92D_\x05\xc9\x98\xcde\x19N_\
\x03\x03[\xef\xb7\x98\x9f\x9d?\xf6\x9dT\x90\x04\xd0Q\xb0\xfaxU\xb7_z\x9ay\
\xe5\x89\x0c]\n:\x03~\x97\xddjPX\n\xb5\xd3\xdc\xd1\xf3\xe8\x85\xea\xdf\x1a\
\x9a\xf0&\x92\xf5c\x0b~\xc1\xc7\x18\xd3\xf5\x94m\x1b\xbd\xf2m8\xc9\xa4$\xc2R\
\xd8\x89\xed;\xe8\x95o\xa3\xf5\x13\xbbO\xf8\x17\x98#;\xff\x0fgp\xcb\xdf\xf1\
\x0b\xf3\xebQ\xc0\xa7\x02\t\xc4\x00\x00\x00\x00IEND\xaeB`\x82'
getmoredialogImage()
def images.getmoredialogImage ()
Definition at line 1680 of file images.py.
References getmoredialogData().
Referenced by getmoredialogBitmap().
def getmoredialogImage():
    stream = cStringIO.StringIO(getmoredialogData())
    return ImageFromStream(stream)
index.append('moredialog')
catalog['moredialog'] = ImageClass()
catalog['moredialog'].getData = getmoredialogData
catalog['moredialog'].getImage = getmoredialogImage
catalog['moredialog'].getBitmap = getmoredialogBitmap
#----------------------------------------------------------------------
getNoIconBitmap()
def images.getNoIconBitmap ()
Definition at line 77 of file images.py.
References getNoIconImage().
def getNoIconBitmap():
    return BitmapFromImage(getNoIconImage())
getNoIconData()
def images.getNoIconData ()
Definition at line 65 of file images.py.
Referenced by getNoIconImage().
def getNoIconData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x00\
\x8cIDATX\x85\xed\x95K\n\xc0 \x0cD\x93\xd8\xfb\xdf\xb8\xb5+!\x95\xd4j?\x8c\
\xd0\xc9F2j|`>\xaa\x96\x04i\x06}\x9d\x00\x04\x10\x91e\xe4p\xde\xd6\xec}\xb5\
\xa4\xd1\x9e\xd7_\x05\x88\x1eUKZ\xd6Z\xef\x89\x07\xff\x02\x02\x0c\xe7@d%\x0f\
\xbc\xdf}\x97\xb3\x80\x00S\x03\xd4\xad\xf7\x0b\x83WA\xb3\x0f\xf8\x9e\x1e\xd5\
\xf9\x95\xe6\xf5[\x00\x11\xc8\x99\xe6\xfd\x91\xc14w\x12\xfe\x02\xa0+\x07\xa2\
a\xf3d\x00\x1db\xa3\xcb\x10\xfe\x05\x04 \x00\x1c`\x07L\xe6D}\xe9\xac\x02\xc0\
\x00\x00\x00\x00IEND\xaeB`\x82'
getNoIconImage()
def images.getNoIconImage ()
Definition at line 80 of file images.py.
References getNoIconData().
Referenced by getNoIconBitmap().
def getNoIconImage():
    stream = cStringIO.StringIO(getNoIconData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
getOverviewBitmap()
def images.getOverviewBitmap ()
Definition at line 1139 of file images.py.
References getOverviewImage().
def getOverviewBitmap():
    return BitmapFromImage(getOverviewImage())
getOverviewData()
def images.getOverviewData ()
Definition at line 1110 of file images.py.
Referenced by getOverviewImage().
def getOverviewData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02FIDAT8\x8d}\x91ILSQ\x14\x86\xbf\xfb\xfah\xfbJ- \xa5\x0f(\xc4!\x06\
\x03\x1b\x12\x1c!&MH\\\xb8\xab\x89F\xbb\xea\n\x87\xb8t\xe7\xc2\x95;\xd6\x86\
\xc4H\xe2\xc6\x8d&\x0e\xc1Dqh\x88H\x08 D\x84\x04\xad\x860\xa8\xa5\xa5\xb6\
\x85\xd0\x89\xf6\xbd\xe7\x82BZ\n\xfe\xc9\xcd\xb9\xc39\xff\xf9\xffs\x05\x05\
\x04\x02\x81\xac\xae\xeb9\xf6\x80$I\xa6p8<\xe9\xf3\xf9.\x01+e\tv\xbb\xfdb>\
\x9f7\xf6[\xe9t\xda\x08\x06\x83F\x7f\x7f\xff8\xe0(!/Dc\xaf\xce\xc5H&\x93\xf8\
\xfd\xfeS}}}o\x00\xe7n\x82\xffB\x96e\xf2\xf9<\xd1h\x94\x9e\x9e\x9e\xce\xde\
\xde\xde\x01\xa0\x1e@\x14,x\x13\x89\xc4\xf3\xed\x82\x95\xe8\x1aO^O\xb1\x1aOa\
`P\xebPhi0\xe1V\xab\xd14\x8d\x9a\x9a\x1a<\x1e\xcf\xf5P(\xf4@.\xeed\x18\x06\
\x1fF\xe7\x18\x9e\x8e\xe0\xf7vq\xb4Q!\xbdi\xf0{5\xc3\xa3\x17\xa3\x9c\x96\xe1\
|W\x1b\x8a\xa2 \x840\x95Y\x88\xad\xa5x9\xbc\xc8\x89\xf6\x16F\xbe,\x91L\xe5\
\x98\xf9\x11fhr\x81\xae\x8e\xe3\xbc\x9d\x88\x90\xd8\xc8\x96\xda+>\x0c\x0c\
\xcd"\x94\x83\xbc\x9bX\xc2n\xab \xf2\xea;\xeb\x1bYV\xd72\x0c\x8e-\xb3\x10J\
\xf1\xec\xfd,\xb7|\xe7\xf6&\x98\xfe\x19e\xe6\x8f\x85\\^\xa3\xc1U\xc9\xed+\
\xed\x0cN\xfe\xe2\xe1\xfd\xcfh\xb9\x1c\x92d\xe2\xeb|l\x7f\x05&\xb3\xcc|4\x83\
\x00\x82\xe1\x18\xdfB\x1bh@\x16\x19\xe5\x80\x15\x80\n\xf3\x96k]\xd7)\x9bAg\
\xab\x8ad1c\xb6Z\xa9rTb\xae\x90\xb1\xca\x12U\xd5v\x14\x9b\x15Y\xb1p\xa6\xd5\
\xb5\xbf\x82\xee\x93\x87\xe9\xf8\xf4\x97\xb8\xa8\xc7e\xd3\xa8\xb2\x08\x9ak\
\x15\xda\x9a\x1d$\x8dJ\xecz\x84\x0bg\x8f\x94\x10H\x00\x9a\xa6\x15di\xdc\xf1\
\xbapg\xc6i\xaa\xab\xe6\xe9h\x9a\xc0\x9c\xe0X\x93\x8a{s\x8a\xbb^\'Bl}\xf7vM\
\x89\x02]\xd7q7\xd4q\xeff7\x1fG\xc6X^\\GH\x82\x0e\xd5\x81\xe7\x86\x07\x9b\
\xcd\x86a\x18;\xfe\xcb\x08\x9cN\xe7\xce\xe3\xd5\xcb\x8d%\xc4%\xc36\x99v\xf6\
\xa2\x10\x0f\xa9\xaazM/\xca\xdc]Tt/\x00\xe2\xf1\xf8c`\xee\x1f\xc2\xda\x00/<\
\xcd4>\x00\x00\x00\x00IEND\xaeB`\x82'
getOverviewImage()
def images.getOverviewImage ()
Definition at line 1142 of file images.py.
References getOverviewData().
Referenced by getOverviewBitmap().
def getOverviewImage():
    stream = cStringIO.StringIO(getOverviewData())
    return ImageFromStream(stream)
index.append('Overview')
catalog['Overview'] = ImageClass()
catalog['Overview'].getData = getOverviewData
catalog['Overview'].getImage = getOverviewImage
catalog['Overview'].getBitmap = getOverviewBitmap
#----------------------------------------------------------------------
getPencilBitmap()
def images.getPencilBitmap ()
Definition at line 183 of file images.py.
References getPencilImage().
def getPencilBitmap():
    return BitmapFromImage(getPencilImage())
getPencilData()
def images.getPencilData ()
Definition at line 150 of file images.py.
Referenced by getPencilImage().
def getPencilData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x02\
\xb9IDATX\x85\xc5\x97\xabn\xdc@\x14\x86?\'\x95\x02Z\xe2\x07\x08\x19\xb2\xb4\
\xd2Y\x10\xa9 Mv\xf3\n!\x05a\xce\x03\x84\xe4\x15\xfa\x08\x1e\x14P\x14VP\xe6\
\\\x0c"\x15\xe4H\x91\n\xa2\x10+\xa0\xbc(`\xc1\xee\x14\xf8\xb2\xb6w\xf6\xe6\
\xdd\xaaG2\x98\xf1\xd8\xdf?\xff93c\x07\xc1\xce.\xff3\xdem\xf3en2v\xbe\xfe`g7\
\xf8\xa7\x02J\xb0\x93\xc8{?P\xeb\xe6\x89\x086MA\t\x8f\xe3\x18\x80$I\xb8\xceB\
\x88\xf26\xf6\xbc\x14\xe1ub#\x01n2v\xf7\xf7\xf7\x00\xec\xef\xef\x03`\x8c\xc1\
Z;\x15R\x87yD\xecl\x0bn\x8c\xc1\x18C\x9a\xa6\xf4z=\x86\xc3!\xa7\xe6O\xe3\x99\
X\xa2\x99:\xe9T\x03%\xfc\xf0\xd3\xc7\xaa/M\xd3\xc6\x98^\xaf\xc7\xde\xde{N\
\x7f|\xe7:\x0b\xb1s\xde\xb5\xb6\x80r\x06\x87/\x9f\xe1\xa5\x80\xf7r1\xe9\xc3S\
5\xee\xf5\xf57\xa3\xd1\xdb\xd2\xf7\xad\x95\x027\x19\xbbG\x07\x8f\x0e4\xca/\
\x80\x0f\x17\x17\xe8\xc1\xa0\xe1\xc8h\xf4F\x96e\x18c\x08t\xde\xfc\xd7p\xa0\
\x84\xd7C,\x109\x84\xbc\xae\xf4`\xc0\xe1\xcf\x1b\xd2\x87\'\xb2,\xcb\xfbTkO\
\xcc\nY\xc9\x81Ep\xec\xb4\xa8%R\xf4`P\xb5U\xb5\x12\x02\x96\x86\x96"\x96.\xc3\
U\xe1\xf5P+\\\x86a\x05\xcf\xb2\x8c\x88|\xfe\xe5j\xb9\xb9\xbd\x0b`\x89\x03]\
\xe0\x00\x97aH\x92$P\x00}18>r\x83\xe3#7W@W\xb8\xad\xd9l\x8cAD\xf2~ \x0c\xc3\
\x99\xf1\xde"t\x93\xb1\x8bcAl+i\xab\xc0U\xa0\xe0\x88HU\x84a\x18z\x05\xcc8P\
\xc2#\x11\x90(\xbf\x8a\xd0\xf3>\xaa\xb2\x10.2\x15\xad\xaa$I\xd2\x80\xb7S\xe2\
u *lS\xc9\x0f\x94\x12\xa9(\xe2\xa9\xe4&|*p\x19\xfc\xe6\xf6.\x98[\x03%\xbc-L\
\x85\x86\x0bm\xf8e6-\xc0ep\xf0\xa4 \x8e\xfd\x16\xd7E\xcc\x83\xd7c\x158\xb4R\
\xe0&cW\x07\x00\x88\x9e\xcf\x88P\x01l>\xae\x01WHt\xb9\xed\xf5\xb67\x05U\xee=\
p\x98\xba\xd0\x86\xf7U\xd7\x82C\xcb\x81\xd2\xfey\xe02\xacj\x81\xdd\x0c\x0e\
\xb5\xad\xb8\xfe\xa1\xe0\x1e\xfd\xdfv%\x1c\x8aMI6\x83C\xcb\x81\xab\xabo<?\
\xff"\xe8\x7f\xf5\n\xa9\xe0ZX\xbf!\xbc!`8\x1crv\xf6\x85 \x98\x1dok\xc7\x98\
\xa8\x16U\xb89\xbc\x12\xe0&c\'"\x9c\x9c\x9c4n\x06}\xdbX\x96\xa2J\xdf\x02,\
\xde^W\x85W\x02`\xbam\xb6Cl>\xd32\xdaP\xdfi\xb7*\x1c\x8a"\x9c\xf7G\xb3\x0e\
\xb4\x0b\x1c\x16|\x92\xad\x03\xed\n\xaf\x04\xf8\xfeXDd\xa1+\xdb\x80W\x02\xba\
FWhg\x01\xdb\x00\xb6\xe3/\xda\xb1\x84\x8dh\xb0\xbb\xe2\x00\x00\x00\x00IEND\
\xaeB`\x82'
getPencilImage()
def images.getPencilImage ()
Definition at line 186 of file images.py.
References getPencilData().
Referenced by getPencilBitmap().
def getPencilImage():
    stream = cStringIO.StringIO(getPencilData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
getPointyBitmap()
def images.getPointyBitmap ()
Definition at line 142 of file images.py.
References getPointyImage().
def getPointyBitmap():
    return BitmapFromImage(getPointyImage())
getPointyData()
def images.getPointyData ()
Definition at line 119 of file images.py.
Referenced by getPointyImage().
def getPointyData():
    return \
"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x01\
\xa9IDATX\x85\xc5\x97a\x92\x83 \x0c\x85\x1fto$g\x923\xd13\xc1\x914\xfbc\r\
\x1b$ \xda\xdaf\x86i+\xc5\xf7\xf1Bbk\x00\x10\xc5\x00\xe3<\x8c}\x18|8,\xbf\
\xa1\x18@\xebB_\x03\xf8\x16\x84\x05\x00\xe3\xfc\xd7 \xac\x96\xf7OB\xe4\x14H\
\x17$\xc4\xdd \xc6\xd8\xc7\x9f\xe0&D1\xd4_\xba\xb1B\xfe\x1d\xd8\x04\xf6N0\
\xd4]Nd\x07\xb2\x98\xe2DJ\t\x00\xe0\xfc\xb3\x80\xbd\x05@B\xc40\x17\xc2\x0c\
\xc5.\xbd\x05\xc4\xd8\x87:\x00\x10\x0f\x8a\x81b\x98\x8b\xcf\x14\x03\x01\xa0\
\xd6\xfa\xd1\xf1\xd3\xda=\xef8\xa5\x94w,\xd3\x92\xaf\xad\x0b\xbd\xe2D\x01 \
\xf3\x7f(\\^\xbb\x0cQ\x9c\x01Z\x17\x8aa\xaer\xde\x12.nt\xb1T+\x80\xb3\xc2\
\x00\x80i\x02\x84cg@\xaa3pJX\x88c\x9ad\x95\x0c\xa7\xc4\xf6&\x9b]Q6\xabM<\xbf\
\xe2\\\xe3\xea\x02t\x85e\xbc\x001\x0c\xa0\x01\xbd\x03b\x08\xc08\x8f\x18\xe6\
\xdc\x19\xd5\x90\xe2\nD\x0b\xa4Y\x05\xadC\x98R\xcaeZ\xcd\xef!\x94\x8d\xec\
\x0f\xa7\xea\x00\xef8/\x12\xf9\x9f\xb6\x9d\xf1|\x92B\x8a\x032\xb4\x94\x14\
\x00\x92\xce\xf9g\x16\xd9\xc3\xc8TH7\x8e\x1c\xd0 \xd4\xa7!\x80\x8a\x94;$[.\
\x1f\xd11\xcc\xd9\x99\x9ex\xb1\xd9-\x1dM\x80# \tRA\x0c\x86q\xbe\xed\xc0(L\
\xef\xd9p\xd4E\x8d\xf3\xedV\xdc]\xb8\x9d\x15Z\x17j6'\xfc\xb9s\xe4\xca\xe5F\
\xc4 \xda\xe0y\xe7\x9fe\x95h\xf7\xb8\x92\x82\xd1\x90?\xed\xf6N\xf0!|\xc9\x81\
\xa3`7zN\xdc\xea\x80\x8c}\x15\xe5\xbf\x01\x9f\x02h\xc5/QAWy\x02\x12)=\x00\
\x00\x00\x00IEND\xaeB`\x82"
getPointyImage()
def images.getPointyImage ()
Definition at line 145 of file images.py.
References getPointyData().
Referenced by getPointyBitmap().
def getPointyImage():
    stream = cStringIO.StringIO(getPointyData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
getProcessusBitmap()
def images.getProcessusBitmap ()
Definition at line 1196 of file images.py.
References getProcessusImage().
def getProcessusBitmap():
    return BitmapFromImage(getProcessusImage())
getProcessusData()
def images.getProcessusData ()
Definition at line 1154 of file images.py.
Referenced by getProcessusImage().
def getProcessusData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x03xIDAT8\x8d]\x93_lSu\x14\xc7\xbf\xf7\xde\xdf\xdd\xed\xfd\xc3\xee\xed\
\xbd\xfd\xb3-\xfb\xdb\xd2.\xa6\xac\x13F\xec\\T2GC\xcc\x1e0S`}\xf1\xc1\x10\
\x88{0&\xb0\x98\x10\x8c\t\xce\x07\x8cA\xd4\x10\xf72c\xf0\x8dhB\x10\x12\xcc@\
\x1d+\xa5\x9dK::G\xc7Z\xba\xc6\xbae\xb8\xd9\xae\xb4\xde\xeeOo\xe7\x83\xc3?;\
\xaf\xe7|?999\x1f`Gi\x9a\x0f\x14\xc5\xa1\xad\xad\xef\x0b\xbf\x7f\xa8 \xcb\
\xce\x80\xd9\xec\xf0\x1f9r~v`\xe0\xd3\x9f(\x8a\xb5\xfcw\x9e\xda\t0\x9b;`\xb5\
:.\xed\xde\xed\x1b\x90e\x1e\x84TA\x92DX\xad\xbbPWgE(\xf4}\xe8\xf2\xe5s\xaf\
\x01\xc6\xd2\xff\x00\x1c\xa7\xee\xd9\xb7/\xf0\xb5\xae\x1b\xb4\xaa\xd6{\x1d\
\x0e\x1bdY\x82$\x89\xe0y\x13X\x96\x81\xd3i\x83a\xb0\x18\x1c|\xf7\x87\xf9\xf9\
k\xbd\x00\xd6\x99\xa7\x00\x8f\'0*I\x8d\xed\xb5\xb5V\xfb\xd1\xa3/\xe1\xe0\xc1\
g\xe1r\xd5A\x10x\x18F\x05\x82\xc0\x81\xa6)P\x14\xc0q\xbc6;;yw}\xbd8\xcf\xfc\
\xbb\xfa\x9e\xb7\x1c\x8e\x16\xfb\x89\x13\x87\xa0i\xd5\x08\x87S\x08\x06\x1f"\
\x1c\x8e\xa1\xb6VA}\xbd\x05\x0cCCU\x05\xf4\xf4<\xc7\x11\xd2\xd0\x15\x89\xfc8\
\xc6\x00@s\xb3\xff\xb3\xd6\xd6\xe7_\xe9\xef?\xc0\x88\xa2\x80[\xb7\xe2\x08\
\x85~\xde\x8c\xc5\xc2\x8f\x82\xc1K\xa7\x0b\x852\xe9\xea\xeav\xcb2\x07\x9e\'\
\x90e\x0e[[\x92\x16\x0c\xde\xcd\x93\xf6\xf6\xd7\x87\xdd\xee\x97O64\x98\xd1\
\xd8h\xc1\xed\xdb\xb3\x88F\x7f\xd9\x0c\x85F>.\x16\x7f\xbd\n \xa6\xeb\x05/\
\xcb\xb2P\x94\xbfo\xb1\xb8\xb8\n\x86\xa9\xa0\xb3\xb3\xff4q\xbb{NZ\xad\x12\
\x9a\x9a\xec\xc8\xe5J\x98\x9e\x9e\xc3\xf8\xf8\xf0E]\xcf\\\x01\x10S\xd5\x16_ \
\xf0f_M\r\x0f\x96\xa5\x91\xc9\xe4\x10\x8f/`q1\x87\xd5\xd5\\\x89\xce\xe7\xe7\
\xc79\x8e\x83aT\x90\xcf\xeb\xc8\xe5V\xa1\xeb\xbfE\x00L)J\xe3\xfe\xb3g\x87o\
\xf6\xf6\xbe\xd8\xa4(U(\x97\r<x\xb0\x80\xa9\xa9\x14"\x91\xc9\xe2\xc4\xc4\x97\
\xe7\xe8;w\xbez\x1f\xa0!\x08<66\x0c\xa8\xea\xae5\x8e\xd34\x9f\xaf\xff\xa33g>\
\xbf\xee\xf7\xef\xaf\xa6\xa8MH\x12\x87\xba:\x19O\x9e\xe8\x98\x9b\x8b\xe7\x13\
\x89o>,\x16\x17n\x10\xa7\xd3\xd3\xaa(\x028\x8e\x80\xe7Y\x1c>\xfc\x02ii\xb90\
\xd4\xd3s\xc0j\xb3\x99 \x8a\x14L&\x11\x8a\xc2\xc30\xb6\xc0q\x14\x92\xc9\x1b#\
\xb9\\\xea\x1a\x80E\xe6\xd8\xb1\xb7\xcf{<m-v\xbb\x04\x96e \xcb\x02\xed\xf5\
\xb6\x8a\x16K\x15\x08\xa1\xb0\xb6\xb6\tM\x13Q.W06\x96D\xa5B\xb0\xb2\xb2\xa6\
\xa6\xd3\x91\x11\x00\x7f0\x13\x13\xa3\xdf\x89\xa2\xdd\xe7ry\x9b\t\xa1`\xb7\
\xcb\xe0y\x1a\x84\xd0H$~G$\x92B4\x9aA6\xbb\x81\xc7\x8f\x8b\x88FS\x98\x99\x89\
\x95VV\xa6\xaf\x00\xc8m\xbf2m\xdd\xbb\xf7\x8d\xabnw{\xe7\xf1\xe3\x87*\x1d\
\x1d.23\x93\xc1\xbd{\x8fp\xff~\n\x89\xc4\xc3\x92,\x93\xa5l6K\x97J\xebT:}\xf3\
\xa2\xae/_\x07\x90\xfe\xc7\x05\x8ab\x9d&S\xcd\xab\r\r\xb5\xa6S\xa7.\x0c\x99\
\xcd\xd5\x08\x85\xe2\x88D&\xffL&\xbf\xfd`y95\n\xa0\xbc\xed\x8f\x0e`\t@a\xa7\
\x8cU\x00\x04\x9b\xcd\xfbN_\xdf\'\x85\xee\xee\xf7\xb2\x82`\x1f\x04\xf0\x0c\
\x00\xf3v\xbf\n\x00y\x1a\xf8\x0b\x05\x8e<\x8eoA1\x93\x00\x00\x00\x00IEND\xae\
B`\x82'
getProcessusImage()
def images.getProcessusImage ()
Definition at line 1199 of file images.py.
References getProcessusData().
Referenced by getProcessusBitmap().
def getProcessusImage():
    stream = cStringIO.StringIO(getProcessusData())
    return ImageFromStream(stream)
index.append('Processus')
catalog['Processus'] = ImageClass()
catalog['Processus'].getData = getProcessusData
catalog['Processus'].getImage = getProcessusImage
catalog['Processus'].getBitmap = getProcessusBitmap
#----------------------------------------------------------------------
getpyshellBitmap()
def images.getpyshellBitmap ()
Definition at line 1719 of file images.py.
References getpyshellImage().
def getpyshellBitmap():
    return BitmapFromImage(getpyshellImage())
getpyshellData()
def images.getpyshellData ()
Definition at line 1691 of file images.py.
Referenced by getpyshellImage().
def getpyshellData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x02\'IDAT8\x8d\xa5\x92OH\xd3a\x18\xc7\xbf\xcf\xfb\x1b\xdbl\xbf6\xa7\xb6\
)m\xceF\x87\x15\xde:\x97R\x87.\x81\x05\xfd\xa1.V\x10\x08%\xfd9\x05RA\x97\x02\
\t\xac\xa4\xc3\xa0:)X\r\xa6u\xb0":h\x88\xa7$R3\x7f\x99\x92\xc3\x84t\xa8c,\
\xf7\xfb\xed\xdbanLC\x90zN\xef\xfb\xfc\xf9\xbc\xdf\xf7y\x1e!\x89\xff1Uz\xb9\
\xd0\xde\xce\xdaX,\x175\x0c\x86\xba\xbb)"=[\x06\x88HK(\xb5\xc2#}}\xa2\x0f\
\x0e\xc2\xdd\xd6\x86\xdex\xfc\xe4\xd6\x15\x84w\xb5\x1c;w^\xaa\x1a\x1b\xf1!\
\xbb\x8a\x91\xd1Q\xdc\x9d\xffI\xc7\x95V\x8a\x88}3\x80\x90\x84\xe6\xf1,\x96\
\x0f\x0f{=\x9a C\xe0\xd7\xc2"\xec\xe94\x1c\xe9\x14\xd4\xdez$\x1b\x0e\xc0\x9c\
M\xc8\xa6\n*\xdf\xbf\xf5\xee\xfb:\x81\x05M\x83>\x9b\x80CS\xc8\xdc\xbc\x81L\
\xe7#X\xa6\x05\x9a\xe6\xdf/\x8b\xe4\xbbO\x12$\x11\x01\xa8\x80y\x00cz\xd7c\
\xfa\x87\x06\x18\xfa1Co\xff+\x02\xa8+\xe4\x91\x84\xf3\xe0~V\xde\xbfC\x92y\
\xc0\x9e\x8a\n>\x08\x87YH\xf0\xbd\xebg\xe8\xdb$+?\x8dP\x85\x82\x1fK\x8b\xe1r\
=\xf7>\x89\x12\x80\xbd\x08\x00@\x00\xd3k\xe7i\xff\xf8\x18k\x8dI\xea\x1d\xf7\
\x08 P(V\x1e\xf7\x9b\xc0\\\xc2R\xde\xf2gE`)\x9d$\xbc\xd1N\xd6M\x19\xf4\x8d\
\x8f\x11\x9a\x8a\x97\xc6v\xf4\xc6\xb8\xedj+K}jCc\x9e\xba\x1a\x0eAS\x82\xec\
\xd0\x00hZG\xd7u\xae.\x88\xed\xcd\xcd\x10\x91\xb3E_Q\x8aR\xb7\xab?\x8f\xe4v\
\xcfLq\xa7a\x10\xc0\xe8Fu\x9a\xdf?\x1f6\xbe\xd0y\xea\x04\x01(\x92\xf9=\x10\
\x11\xbd\xec\xda\xe5\x15\xdf\xc5K\xb0\xdblH\xbe\xec\xc1rW\x1c\xa2\xbb\xd6\
\xcf\xce4Qu\xeb:r\xd5A\xccE\xea#$\'l\xc5\xe0j\x06\xbf-\x0b9\x11\x945\x9dFY\
\xd3\x19`\xc3\xfcI"k\x99Xz\xd8\x01\x00\x89\xe2&\xae\xfd_\x87[\x7f\x81\x9a\
\x9a\xc3\x00\xe0\t\x06\xb0\xb4\xb8\x00\xcd\xe1\x84\x95\\\x06h\x01Y\x13\x98\
\xfa\xfe\x1a\xc0q\x92\xa9u\x80\x7f\xb5?\xa0\xbfG\xab\xac\xdc\x93\x9b\x00\x00\
\x00\x00IEND\xaeB`\x82'
getpyshellImage()
def images.getpyshellImage ()
Definition at line 1722 of file images.py.
References getpyshellData().
Referenced by getpyshellBitmap().
def getpyshellImage():
    stream = cStringIO.StringIO(getpyshellData())
    return ImageFromStream(stream)
index.append('pyshell')
catalog['pyshell'] = ImageClass()
catalog['pyshell'].getData = getpyshellData
catalog['pyshell'].getImage = getpyshellImage
catalog['pyshell'].getBitmap = getpyshellBitmap
#----------------------------------------------------------------------
getrecentBitmap()
def images.getrecentBitmap ()
Definition at line 1753 of file images.py.
References getrecentImage().
def getrecentBitmap():
    return BitmapFromImage(getrecentImage())
getrecentData()
def images.getrecentData ()
Definition at line 1734 of file images.py.
Referenced by getrecentImage().
def getrecentData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x01?IDAT8\x8d\xed\x92=K\xc3p\x10\xc6\x7fi\xd3\x1ah\x16]\xda\xcdE\xc5\
\xc1E\x1d\xda]g\xc1\xd9Q\xb1(up(\xfd\x04\x0e\xa6\x8b \xd2E\x10t\xd2\x0e\x82\
\x9b\x0en*\xe8\x07\x88-\x82V|\x89C\xe2[kK\xb09\x87\x84\xd8\xce]\x1c<8\xee\
\xe1\xfe\xf7<w\x7f\xee\x14\x11\xa1\x17\x8b\xf4\xc4\xfe\x13\x02*Ee\rX\x02J\
\x80\x1b\xe0\xbd >\x01\xef\xc0]\xf0>\x14\xf0\xb4\x90#\x06\x8e4\x1d\x91\xfdi\
\x11\x03K\xea\x96\x8f\xdd\xba\x88S\x15y\xbe\x12\xb9.\x8bl\xe8"\xc7\x8b\xbe\
\x1b\x98b\x9b"[)Q\x01\rU\x83\x99\x03\xd8\x1c\xd0\x89\xeb\x90\x9a\x04\xb7\x0e\
\xdb#/\xc4\xf5$\xd9\x1a\x8c\xe7`p\xca\xef\xdfz\x1b%\xa6C\xc3zP\x01\x0f\xf1\
\xa0R\x86t!\x11~N\xeb\x87\x85j\x92\xa6\r7G0\x91\x83\xef\x16D\xfb ]\x00\xdb\
\x040\xd5\x90p\x92m\xb0\xe2\xfc\n\xb4^\xfd\t\xe0\x16%\x9aa\xf5\x0b\xeeO\xc1\
\xfd\x84\xe1Y\xd8\x19\x03(uo\xe1r\x1db\x89\xee\t\xe6.2H\xbb\x89\xb4\xe1\xa3\
\x06\x8fg\x10Q\xc1\xa9@^\x0e\x151(vl!\xd1\x81\xe7\x81\x1a`\x03\xe7A~\x17\xf0\
\xc2\x9a\xbc,+\xff\xa7\xdc\xbb\xc0\x0f\xa8\x17\x8a\x92\xa1;\xffs\x00\x00\x00\
\x00IEND\xaeB`\x82'
getrecentImage()
def images.getrecentImage ()
Definition at line 1756 of file images.py.
References getrecentData().
Referenced by getrecentBitmap().
def getrecentImage():
    stream = cStringIO.StringIO(getrecentData())
    return ImageFromStream(stream)
index.append('recent')
catalog['recent'] = ImageClass()
catalog['recent'].getData = getrecentData
catalog['recent'].getImage = getrecentImage
catalog['recent'].getBitmap = getrecentBitmap
#----------------------------------------------------------------------
getsaveperspectiveBitmap()
def images.getsaveperspectiveBitmap ()
Definition at line 1811 of file images.py.
References getsaveperspectiveImage().
def getsaveperspectiveBitmap():
    return BitmapFromImage(getsaveperspectiveImage())
getsaveperspectiveData()
def images.getsaveperspectiveData ()
Definition at line 1768 of file images.py.
Referenced by getsaveperspectiveImage().
def getsaveperspectiveData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x03\xa2IDAT8\x8d]\xcckL[e\x00\xc6\xf1\xe7}O[\xe9\x95B)-\xb4\xd2\x96K\
\xd9\x8aPG\x8d\xd0\xce\xb1%\x8e\xa5\xc9\xa4\n!\xce\x05\xd4y\t\x18\x12c\xb2(\
\x89\xf3\x8bA\x13\x9d\x8bn\xde\x96,nK\xd4-\x93\xc8\x8c\x1b\xba\xba\xe9&\x0e\
\xeb\xd8\x04\x1d\t\x0e\x17@`\xb4PHC\x81B{\xda\x9es^?\x91\x18\x7f\xc9\xff\xcb\
\xf3\xe1!\x1d\x1d\x1d`\x8c\x01\x00\x08!\x90$\t\xa2(j\x0c\x86\x82\xe0\x8d\x1b\
\xbf\r\x87B\xa1\xd7\x00\x08\xad\xad\xad(,4!\x99\xdc\xd0\x1b\x8d\xc67\x9dNW\
\xfb\xd1\xa3\x1f\\\xa0\xa9T\n\xc9d\x12\xeb\xeb\xeb\xe0y\x1e\xcb\xcb\xcbX[K<\
\xe2\xf7\xef\xf5y}\xbb\xba\x00\x94\x02\x00\xcf\xf3\xe0\xf9\x14\xccf\xd3;\xdd\
\xdd\x87^\xd1\xe9\x8a\rKK\x8b\x95\x94\x10\x82\xcd\x04A\x84\\.\xab\xdf\xf7T\
\xfb9Qb\x14\xe9{\xf22\xbb\xf5`\x81\xc1\x00\xc6$\x88b\xd6\xe9r\xb9\xdb\x06\
\x7f\xfd\x1d\xc7\x8e\xbd\xbb\x11\x8b-\xf5pn\xb7\x1b\x8c1\x08\x82\x00\x85B\
\xde\xf0D\xf3\x93A\x9d6/7\xbe0\x8c\x97\xbaZHM\xf5\xfd\x9ePhL\xab\xd1\xe9\xe7\
\xfd\xfe\xc0\xf5\x91\x91\xdb\xfaC\xaf\x1f\xbc4;;\xd9\r\xe0\x07\xce\xedv#\x9b\
\xcd\x82\xe3\xe8\xce\xa6\xa6\xd6~\x8d:O\xb7\x12\x1dB \xe0\x83ZeB\x99\xa3\x88\
XL\xeaz\x99\xb2\xfc\xc0\x9d\xf1\t\xed\xc9\x93\x1f\x9f\x10\x84L\x1b\xa5t\x821\
\x06*\x8a"\xe4r\xd9\xce@`\xffE\xb5Z\xaf[\x9c\xfe\x11~\xff6\xa84"\x84\x8d\x19\
\x0c\x86\xc2\xd0\x16x\xa8\xbdH\xa5\xbez\xe9\xcb\xbfDQ\xe8R*d\x90$\t\x84\x00\
\x9c\xd7\xebki\n\xec\xfbF\xa5Vkb3\xbf\xa0\xb2"\x1f\x1a\x99\x027\x8f\x0715\
\xcf#\x9d\xef\xc0\xe8\xf0\x18v\xd4\x19\xf0\xd8n\x97q|t\xa2\x880\xe9\xfb\xf8F\
\x1ar\x19\x05\xe7p8\x9e]Y\xcd\xee\x90\xd6\xbe\xa2m\xadf\x98\xca\x1b\x11\xf9s\
\n\xec\x9f\x04VnO`2r\x17\x8f\xb7oG&-GU\xf5\x16\xf2\xd0\x03F\xcf\x95\x9f\x86\
\xad\xd1x\xb2_\xceQp)&\r\x05\xfb\xfb\xfa#\x91\x98\xbe\xee\xe1\xf4\x16\x84WIl\
X\x80\xddjB&\x18\xc4\xbd\x81\xabp=\xd3\x02\xa7]\x81\xd4\x06\x85\xd5\xb9\x95x\
\xcau\xb53\xe3\x13\xb6h<y\x81\xdb.\x8a\x99|\x9e\x8f\xd0\x18\xff\xf5\xdc\xcd\
\xcc\x8b\xde\n_\xae\xbd\xa0\x18\xd3\xa7Oa2\xbb\x0c\xcb\x81\xe7aq0\xe4)\x170;\
\x97\xc0\xb9\xe0"<\xb5v\xec\xf6\x96l\x0b\r\x8eV\xc8\xca\xe3q\x94\x00\xb2r\
\x9b\xf5r\xf3\x1bo[\x8d\x1a\x15\xc2\x1f\x1dAx=\x8ct\xcfg\xb0\xd6\x96\xc0\xaa\
\xb8\x83\xc4j\x02V[\tJg\xfe\x00\xa36\xb0\x0c\x8f\xac(z87\x90\xe3(\xb5\x0f<w\
\xe2\xd3\x06S\x0e%\xf1\xe3\xef\xe3\xfa\xc8(>\xd7)\xd36\x8b\x82\xee\xf1\x14\
\x93\x95h\x18g\x06\x80\\\xcc\xa0aO\x15\xa6F\xfe\xc6\xfe\xce\xc3\xd3c\xe1\xc4\
\xd3\xe81\x17\x9e\x9e?\x7f\x96\t\xc1>\xb6\xbc\xb7\x8e]6+\xd9\xd6\x9c\x9c9\
\x00\x8f\xdasi\xf7w\x9f\xbc\x90\xcdD/\xb2k\xbd\xaf\xb2\xd5\xbb\xa7\xd8\xado\
\x0f\xb3J\x93v\x1a\x80\x0b\x00p\xab\xad9\xc3\xae\xf42\xa1\xc5\xc7~6\xdd\xc7\
\x1eT\xc8\x17\x00\xd4Q\x02\x00\x80Y\x89\x97\xfb\x8e\xb4eXj\x80\r\x9d\x7f\x8b\
U\x16\xaa&\x018\xb1\xe9\xc3\xb2\xa2h\xa4\xb1\x9a\xf5\x9a\x95\xcc\xc9\xd1I\
\x00\x1e\x00\xa0\x04PQ\n\x00\xb0hI\xe7{\x9d^\xbe\xc6\xa6\x9f\x06P\x81\xff\
\xaa\x02\xea\xab\x81k\xb9\x84|\x01\xc0\xb2\xb9o\x1e(\t@\x01\xc8\x80F\x005\
\xf8\x9f\x7f\x01\xffc\x82t\x0c\xb6\x936\x00\x00\x00\x00IEND\xaeB`\x82'
getsaveperspectiveImage()
def images.getsaveperspectiveImage ()
Definition at line 1814 of file images.py.
References getsaveperspectiveData().
Referenced by getsaveperspectiveBitmap().
def getsaveperspectiveImage():
    stream = cStringIO.StringIO(getsaveperspectiveData())
    return ImageFromStream(stream)
index.append('saveperspective')
catalog['saveperspective'] = ImageClass()
catalog['saveperspective'].getData = getsaveperspectiveData
catalog['saveperspective'].getImage = getsaveperspectiveImage
catalog['saveperspective'].getBitmap = getsaveperspectiveBitmap
#----------------------------------------------------------------------
getSmallDnArrowBitmap()
def images.getSmallDnArrowBitmap ()
Definition at line 57 of file images.py.
References getSmallDnArrowImage().
def getSmallDnArrowBitmap():
    return BitmapFromImage(getSmallDnArrowImage())
getSmallDnArrowData()
def images.getSmallDnArrowData ()
Definition at line 48 of file images.py.
Referenced by getSmallDnArrowImage().
def getSmallDnArrowData():
    return \
"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00HIDAT8\x8dcddbf\xa0\x040Q\xa4{\xd4\x00\x06\x06\x06\x06\x06\x16t\x81\
\xff\xff\xfe\xfe'\xa4\x89\x91\x89\x99\x11\xa7\x0b\x90%\ti\xc6j\x00>C\xb0\x89\
\xd3.\x10\xd1m\xc3\xe5*\xbc.\x80i\xc2\x17.\x8c\xa3y\x81\x01\x00\xa1\x0e\x04e\
?\x84B\xef\x00\x00\x00\x00IEND\xaeB`\x82"
getSmallDnArrowImage()
def images.getSmallDnArrowImage ()
Definition at line 60 of file images.py.
References getSmallDnArrowData().
Referenced by getSmallDnArrowBitmap().
def getSmallDnArrowImage():
    stream = cStringIO.StringIO(getSmallDnArrowData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
getSmallUpArrowBitmap()
def images.getSmallUpArrowBitmap ()
Definition at line 40 of file images.py.
References getSmallUpArrowImage().
def getSmallUpArrowBitmap():
    return BitmapFromImage(getSmallUpArrowImage())
getSmallUpArrowData()
def images.getSmallUpArrowData ()
Definition at line 31 of file images.py.
Referenced by getSmallUpArrowImage().
def getSmallUpArrowData():
    return \
'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\
\x00\x00\x00\x1f\xf3\xffa\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\
\x00\x00<IDAT8\x8dcddbf\xa0\x040Q\xa4{h\x18\xf0\xff\xdf\xdf\xffd\x1b\x00\xd3\
\x8c\xcf\x10\x9c\x06\xa0k\xc2e\x08m\xc2\x00\x97m\xd8\xc41\x0c \x14h\xe8\xf2\
\x8c\xa3)q\x10\x18\x00\x00R\xd8#\xec\xb2\xcd\xc1Y\x00\x00\x00\x00IEND\xaeB`\
\x82'
getSmallUpArrowImage()
def images.getSmallUpArrowImage ()
Definition at line 43 of file images.py.
References getSmallUpArrowData().
Referenced by getSmallUpArrowBitmap().
def getSmallUpArrowImage():
    stream = cStringIO.StringIO(getSmallUpArrowData())
    return ImageFromStream(stream)
#----------------------------------------------------------------------
Variable Documentation
catalog
dictionary images.catalog = {}
Definition at line 1020 of file images.py.
index
list images.index = []
Definition at line 1021 of file images.py.
Referenced by Attrib.attributs(), checkCmd(), Run.decodeInfo(), and Data.print().