shell Namespace Reference
Functions
def opts ()
def obj ()
def get (path)
def cd (path='')
def load (filename)
def reload ()
def ls (path='')
def ll (path='')
def pwd ()
def tree (path='')
def view (path='', indent=' ')
def create (object, type)
def process (object)
def data (object, stream=None)
def app ()
def clear (path='')
def delete (path='')
def outputLevel (level='INFO')
def init ()
def network ()
def reset (path='')
def prompt ()
def loadDll (name)
def run (processus, element, nevt)
def shell (app, args)
Variables
args = arguments()
shellMode
Function Documentation
app()
def shell.app ()
Definition at line 168 of file shell.py.
def app():
  return cat
cd()
def shell.cd (path = '')
Definition at line 34 of file shell.py.
References prompt().
def cd(path=''):
  cat.cd(path)
  prompt()
clear()
def shell.clear (path = '')
Definition at line 172 of file shell.py.
Referenced by delete(), AppFrame.AppFrame.onDelete(), and reload().
def clear(path=''):
  if path == '':
    element = cat.current()
  else:
    element = cat.current().child(path)
  if type(element) != None:
    element.clear()
create()
def shell.create (object, type)
Definition at line 131 of file shell.py.
Referenced by Application.hostname().
def create(object, type):
  if cat.create(object, type).isFailure():
    cat.fatal("Could not make object " +
              object + " of type " + type, "CAT")
#----------------------------------------------------------------------------
data()
def shell.data (object, stream = None)
Definition at line 150 of file shell.py.
Referenced by A3PE.clockDivision(), Server_NI6008.cmd(), SpecsMezzanine.cmdline(), Data.Data(), A3PE.enableStorage(), A3PE.fifoDepth(), A3PE.fifoLatency(), Register.getBit(), FePGA.i2cRead(), SeqPGA.i2cRead(), FePGA.i2cWrite(), SeqPGA.i2cWrite(), A3PE.latencyAX(), A3PE.lengthAX(), A3PE.loadFromAX(), A3PE.loadPattern(), A3PE.loadStorage(), A3PE.loadToAX(), A3PE.loadTrigger(), A3PE.nTrigger(), RAM.raz(), UsbFTMLInterface.read(), UsbFTInterface.read(), Register.setBit(), A3PE.setClockDivision(), LSDelayChipV1.setConfigReg(), Data.setData(), IOdata.setDataU16(), IOdata.setDataU32(), IOdata.setDataU8(), SeqPGA.setExtTrig(), A3PE.setFifoDepth(), A3PE.setFifoLatency(), FePGA.setI2cGBTSCA(), SeqPGA.setI2cGBTSCA(), SeqPGA.setLedEnable(), A3PE.setNTrigger(), A3PE.setPipeline(), SeqPGA.setSpiEnable(), SeqPGA.setSpiGBTSCA(), FePGA.setSpiGBTSCA(), A3PE.setTriggerDelay(), A3PE.setTriggerRate(), A3PE.triggerDelay(), A3PE.triggerRate(), UsbFTInterface.usbRead(), UsbFTMLInterface.usbRead(), UsbFTInterface.usbWrite(), UsbFTMLInterface.usbWrite(), UsbFTMLInterface.write(), SpecsInterface.write(), and UsbFTInterface.write().
def data(object, stream=None):
  ok = False
  list = cat.procDb().list()
  for p in range(len(list)):
    if (list[p].name() == object):
      ok = True
      if (stream == None):
        list[p].data().info()
      else:
        return list[p].data().vector(stream)
  if (ok == False):
    cat.warning("Could not find processus " + object + ".", "CAT")
    return
#----------------------------------------------------------------------------
# application settings
delete()
def shell.delete (path = '')
Definition at line 181 of file shell.py.
References clear().
def delete(path=''):
  if path == '*':
    cat.current().clear()
  else:
    cat.current().delChild(path)
get()
def shell.get (path)
Definition at line 30 of file shell.py.
Referenced by run().
def get(path):
  return cat.current().child(path)
init()
def shell.init ()
Definition at line 203 of file shell.py.
Referenced by AppFrame.AppFrame.onInit().
def init():
  cat.computer().recursiveInitCommunications()
  cat.computer().recursiveInitElement()
ll()
def shell.ll (path = '')
Definition at line 70 of file shell.py.
def ll(path=''):
  if path == '':
    element = cat.current()
  else:
    element = cat.current().child(path)
  if type(element) != None:
    lproc = cat.procDb().list(element)
    nproc = len(lproc)
    if (nproc) > 0:
      cat.info("- Processus: ", "CAT")
    for p in range(nproc):
      cat.info(" " + lproc[p].name() +
               " : " + lproc[p].title(), "CAT")
    l = element.children()
    if (len(l)) > 0:
      cat.info("- Element(s): ", "CAT")
    for iter in range(len(l)):
      cat.info(" " + l[iter].name() +
               " [" + l[iter].type() + "]", "CAT")
      lproc = cat.procDb().list(l[iter])
      for p in range(len(lproc)):
        cat.info(" . " + lproc[p].name() +
                 " : " + lproc[p].title(), "CAT")
      cat.info(element.name() + " : " + str(len(l)) + " child(ren) found [" +
               str(nproc) + " processus].", "CAT")
load()
def shell.load (filename)
Definition at line 39 of file shell.py.
References prompt().
Referenced by loadDll(), and reload().
def load(filename):
  if (os.path.exists(filename) == False):
    filename = filename + ".py"
  if (os.path.exists(filename)):
    execfile(filename)
    prompt()
    cat.options().setDefFile(filename)
  else:
    cat.warning("File " + filename + " does not exist.", "CAT")
loadDll()
def shell.loadDll (name)
Definition at line 230 of file shell.py.
References load().
def loadDll(name):
  cat.dllMgr().load(name)
#----------------------------------------------------------------------------
# processing
ls()
def shell.ls (path = '')
Definition at line 56 of file shell.py.
def ls(path=''):
  if path == '':
    element = cat.current()
  else:
    element = cat.current().child(path)
  if type(element) != None:
    l = element.children()
    for iter in range(len(l)):
      cat.info(" " + l[iter].name() +
               " [" + l[iter].type() + "]", "CAT")
    cat.info(element.name() + " : " + str(len(l)) +
             " child(ren) found.", "CAT")
network()
def shell.network ()
Definition at line 208 of file shell.py.
Referenced by Application.status().
def network():
  cat.fatal("Not implemented.", "CAT")
obj()
def shell.obj ()
Definition at line 26 of file shell.py.
Referenced by Application.create().
def obj():
  return cat.current()
opts()
def shell.opts ()
Definition at line 19 of file shell.py.
Referenced by run().
def opts():
  return cat.options()
#----------------------------------------------------------------------------
# tree/object navigation
outputLevel()
def shell.outputLevel (level = 'INFO')
Definition at line 188 of file shell.py.
Referenced by shell().
def outputLevel(level='INFO'):
  levels = {'VERBOSE': MsgLevel.VERBOSE,
            'DEBUG': MsgLevel.DEBUG,
            'INFO': MsgLevel.INFO,
            'WARNING': MsgLevel.WARNING,
            'FATAL': MsgLevel.FATAL}
  outLevel = levels.get(level)
  if outLevel != None:
    cat.options().setLogOutputLevel(outLevel)
  else:
    cat.warning("Output Level should be 'VERBOSE', 'DEBUG', 'INFO', 'WARNING' or 'FATAL'",
                "CAT")
    cat.warning("'" + level + "' level output not understood.", "CAT")
process()
def shell.process (object)
Definition at line 139 of file shell.py.
Referenced by Application.prepare().
def process(object):
  ok = False
  list = cat.procDb().list()
  for p in range(len(list)):
    if (list[p].name() == object):
      return list[p]
  if (ok == False):
    cat.warning("Could not find processus " + object + ".", "CAT")
    return None
prompt()
def shell.prompt ()
Definition at line 221 of file shell.py.
Referenced by cd(), load(), and shell().
def prompt():
  current = cat.current()
  if current != None:
    sys.ps1 = "\033[92m" + current.name() + "\033[0m[\033[93m" + \
        current.type() + "\033[0m] > "
  else:
    sys.ps1 = "\033[91mInvalid\033[0m[\033[95mNone\033[0m] > "
pwd()
def shell.pwd ()
Definition at line 97 of file shell.py.
def pwd():
  cat.info(cat.current().name() + " [" + cat.current().type() + "]", "CAT")
reload()
def shell.reload ()
Definition at line 50 of file shell.py.
References clear(), and load().
Referenced by AppFrame.AppFrame.onReLoad().
def reload():
  filename = cat.options().defFile()
  cat.computer().clear()
  load(filename)
reset()
def shell.reset (path = '')
Definition at line 212 of file shell.py.
Referenced by BOOST_PYTHON_MODULE(), MSOxxxx.init(), ICECALv3.init(), LSDelayChipV1.init(), and ProtoFEB_v1.ProtoFEB_v1.onGlobalReset().
def reset(path=''):
  if path == '':
    element = cat.current()
  else:
    element = cat.current().child(path)
  if type(element) != None:
    element.reset()
run()
def shell.run (processus, element, nevt)
Definition at line 237 of file shell.py.
References get(), and opts().
Referenced by Run.Run(), MSOxxxx.setDebugMode(), and Run.setNumber().
def run(processus, element, nevt):
  if (type(element) == str):
    element = get(element)
    if (element == None):
      return Code.FAILURE
  ok = False
  proc = None
  list = cat.procDb().list(element)
  for p in range(len(list)):
    if (list[p].name() == processus):
      proc = list[p]
      ok = True
  if (ok == False):
    cat.warning("Could not find processus " + processus + ".", "CAT")
    return Code.FAILURE
  nrun = opts().runNumber()
  if (cat.prepare(processus, element, nevt).isFailure()):
    cat.warning("Could not prepare the processus " +
                processus + ".", "CAT")
    return Code.FAILURE
  evt = nevt
  width = 50
  plts = None
  module = None
  wrap = wrapper(cat, proc, "proc")
  online = cat.options().plotFreq()
  if (wrap.ok):
    module = wrap.GetActive()
    proc.setElement(element)
    if module and (online != 0):
      plts = module.createPlots(cat, proc, nrun)
    
  p = progressbar.AnimatedProgressBar(
      processus, end=abs(evt), width=width, fill='▣', blank='-')
  timing = -1.
  ievt = 0
  if (evt<0): timing = time.time()
  evt = abs(evt)
  stop = False
  try:
    while (not stop):
      ievt+=1
      if timing>=0:
        elapsed = time.time() - timing
        p.set(elapsed)
        if elapsed > evt : stop = True
      else :
        p + 1
        if ievt>=evt : stop = True
      p.show_progress()
      if (cat.loop().isFailure()):
        cat.warning("Error detected during processing.", "CAT")
      if online>0 and plt:
        if ievt%online==0:
          if module :
            module.updatePlots(plts, proc)
  except KeyboardInterrupt:
    pass
  cat.terminate()
  if module and online==0:
    plts = module.createPlots(cat, proc, nrun)
    module.updatePlots(plts, proc)
  # Plot(processus, nrun)
# def plot(processus, nrun):
# p = proc(processus)
# if (p != None):
# wrap = wrapper(cat, p, "proc")
# if (wrap.ok):
# module = wrap.GetActive()
# plot = module.Plot(cat, p, None, nrun)
# if plot:
# plot.current().show()
# return Code.SUCCESS
# def finalplot(processus, nrun):
# p = proc(processus)
# if (p != None):
# wrap = wrapper(cat, p, "proc")
# if (wrap.ok):
# module = wrap.GetActive()
# plot = module.FinalPlot(cat, p, None, nrun)
# if plot:
# plot.current().show()
# return Code.SUCCESS
shell()
def shell.shell (app, args)
Definition at line 328 of file shell.py.
References outputLevel(), and prompt().
def shell(app, args):
  import version
  global cat
  global figid
  figid = 0
  if (app == None):
    cat = Application()
  else:
    cat = app
  outputLevel(args.output)
  vers = version.version()
  vers.info()
  cat.initialize()
  if ("" <> args.file):
    if (os.path.exists(args.file)):
      execfile(args.file)
      cat.options().setDefFile(args.file)
    else:
      cat.fatal("Cannot execute init file " +
                args.file + ". Abort.", "CAT")
      return -1
  prompt()
# main
tree()
def shell.tree (path = '')
Definition at line 101 of file shell.py.
def tree(path=''):
  if path == '':
    element = cat.current()
  else:
    element = cat.current().child(path)
  if type(element) != None:
    element.tree()
view()
def shell.view (path = '', indent = ' ')
Definition at line 110 of file shell.py.
def view(path='', indent=' '):
  if path == '':
    element = cat.current()
  else:
    element = cat.current().child(path)
  line = indent + ' -> ' + \
      element.name() + '[' + element.type() + \
      ' - ' + element.attributs() + ']'
  print line
  l = element.children()
  for iter in range(len(l)):
    lproc = cat.procDb().list(l[iter])
    for p in range(len(lproc)):
      print indent + " ." + lproc[p].name() + "(" + lproc[p].title() + ") - " + lproc[p].attributs()
    view(l[iter].path(''), indent + ' ')
 # def com(objecgt):
 # while connection!=None:
 # print connection()
Variable Documentation
args
shell.args = arguments()
Definition at line 354 of file shell.py.
shellMode
shell.shellMode
Definition at line 355 of file shell.py.