TestSPI Namespace Reference
Functions
def Edit (cat, obj, panel, path)
def createPlots (cat, obj, run)
def updatePlots (figs, obj)
def Plot (cat, obj, parent, id)
Function Documentation
createPlots()
def TestSPI.createPlots (cat, obj, run)
Definition at line 45 of file TestSPI.py.
def createPlots(cat, obj, run):
    fig = plt.figure(figsize=(10,10))
    fig.suptitle("Run "+str(run), fontsize=14, fontweight='bold')
    for vplot in [1,2]:
        ax = fig.add_subplot(2,1,vplot)
    fig.show()
    return [fig]
Edit()
def TestSPI.Edit (cat, obj, panel, path)
Definition at line 40 of file TestSPI.py.
def Edit (cat, obj, panel, path):
    return TestSPI(cat, obj, panel, path)
#----------------------------------------------------------------------
Plot()
def TestSPI.Plot (cat, obj, parent, id)
Definition at line 89 of file TestSPI.py.
References plotter.h1d(), Object.name(), and Object.title().
def Plot(cat, obj, parent, id):
    from mpl_toolkits.mplot3d import Axes3D
    from matplotlib import cm
    import matplotlib as mpl
    import matplotlib.pyplot as plt
    import numpy as np
    plot=plotter(parent,id)
    fig=plot.current()
    fig.suptitle('TestSuite - Plot capabilities', fontsize=14, fontweight='bold')
    
    # plot of data set 0
    p1=fig.add_subplot(2,3,1)
    p1.plot(obj.data(0), 'bo', obj.data().vector(1),'k')
    p1.set_title(r'$\sigma_0='+str(obj.sigma(0))+'$')
    
    # plot of data set 1
    p2=fig.add_subplot(2,3,2)
    p2.plot(obj.data(1), 'r--')
    p2.set_title(r'$\sigma_1='+str(obj.sigma(1))+'$')
    
    # plot of data set 0 (histogram)
    plt.subplot(2,3,3)
    n, bins, h=plt.hist(obj.data().vector(0), 10)
    plt.title(obj.data().title(0))
    plt.grid(True)
    # plot of data set 1 (histogram)
    plt.subplot(2,3,4)
    plt.hist(obj.data().vector(1), 20)
    plt.title(obj.data().name(1)+" : "+obj.data().title(1))
    plt.grid(True)
    # plot histo root
    p5=fig.add_subplot(2,3,5)
    h1=h1d(p5, obj.hist1d(0), facecolor='red',linestyle='dashed')
    p5.grid(True)
updatePlots()
def TestSPI.updatePlots (figs, obj)
Definition at line 53 of file TestSPI.py.
def updatePlots(figs, obj):
    fig = figs[0]
    ax1 = fig.add_subplot(2,1,1)
    lines, = ax1.plot([],[], 'bo')
    #Autoscale on unknown axis and known lims on the other
    ax1.set_autoscaley_on(True)
# ax.set_xlim(self.min_x, self.max_x)
    #Other stuff
    ax1.grid()
    lines.set_xdata(obj.data(0))
    lines.set_ydata(obj.data(1))
    #Need both of these in order to rescale
    ax1.relim()
    ax1.autoscale_view()
    ax2 = fig.add_subplot(2,1,2)
    lines, = ax2.plot([],[], 'bo')
    #Autoscale on unknown axis and known lims on the other
    ax2.set_autoscaley_on(True)
# ax.set_xlim(self.min_x, self.max_x)
    #Other stuff
    ax2.grid()
    lines.set_xdata(obj.data(2))
    lines.set_ydata(obj.data(3))
    #Need both of these in order to rescale
    ax2.relim()
    ax2.autoscale_view()
    #We need to draw *and* flush
    fig.canvas.draw()
    fig.canvas.flush_events()
    fig.show()
    return fig
    
#----------------------------------------------------------------------