/home/eleclhcb/LHCb/lbcat-cmake/CatNI/inc/Server_NI6008.h File Reference
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <vector>
#include <string.h>
#include <time.h>
#include <algorithm>
#include <sys/utsname.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <NIDAQmxBase.h>
Classes
class Server_NI6008
Defines
#define INC_SERVER_NI6008_H 1
Functions
std::string itos (int i)
std::string ftos (float f)
const std::string & hostName ()
Host name.
const std::string & osName ()
OS name.
const std::string & osVersion ()
OS version.
const std::string & machineType ()
Machine type.
const std::string & accountName ()
User login name.
Define Documentation
#define INC_SERVER_NI6008_H 1
Definition at line 3 of file Server_NI6008.h.
Function Documentation
const std::string& accountName ()
User login name.
Definition at line 85 of file Server_NI6008.h.
Referenced by Application::Application(), and Server_NI6008::Server_NI6008().
                               
  static std::string account = "";
  if (account == "")
    const char* acct = ::getlogin();
    if (0 == acct) acct = ::getenv("LOGNAME");
    if (0 == acct) acct = ::getenv("USER");
    account = (acct) ? acct : "Unknown";
  
  return account;
std::string ftos (float)
Conversion from float to std::string
Definition at line 28 of file Server_NI6008.h.
Referenced by Processus::endProcessing(), PhaserRampExec::finalize(), Server_NI6008::setAIRange(), Server_NI6008::setAORange(), Server_NI6008::status(), and ICECALv3::version().
                       
  char val[20];
  sprintf(val,"%f",f);
  std::string str(val);
  return str;
const std::string& hostName ()
Host name.
Definition at line 36 of file Server_NI6008.h.
Referenced by Application::Application(), Computer::Computer(), and Server_NI6008::Server_NI6008().
                            
  static std::string host = "";
  if (host == "")
    char buffer[512];
    memset(buffer,0,sizeof(buffer));
    ::gethostname(buffer, sizeof(buffer));
    host = buffer;
  
  return host;
std::string itos (int)
Conversion from int (long) to std::string
Definition at line 21 of file Server_NI6008.h.
Referenced by DCU::acquire(), btos(), FEB_v1::calibCte(), MSOxxxx::channelDisplay(), MSOxxxx::channelDisplayName(), MSOxxxx::channelOffset(), MSOxxxx::channelScale(), ICECALv3::checkChNumber(), LSDelayChipV1::checkConfigAddr(), LSDelayChipV1::checkStatusAddr(), FEB_v1::clock80MHzFallingEdge(), FEB_v1::clockFallingEdge(), UsbFTMLInterface::close(), UsbFTInterface::close(), SpecsMezzanine::cmdline(), SpecsSlave::detect(), FEB_v1::disableSubtract(), IOdata::dump(), A3PE::dumpFromAX(), Processus::endProcessing(), Acquisition::execute(), PhaserRampExec::execute(), FEB_v1::FEB_v1(), PhaserRampExec::finalize(), FEB_v1::gain4(), FEB_v1::gbt80MHzClkEport(), FEB_v1::gbtAcknowledgeConfig(), FEB_v1::gbtDataPath(), FEB_v1::gbtDLLEport(), FEB_v1::gbtDLLReset(), FEB_v1::gbtEnableEport(), FEB_v1::gbtMode(), FEB_v1::gbtStatus(), FEB_v1::gbtTermEport(), FEB_v1::gbtTrackMode(), EmulateFE::generateFile(), ICECALv3::getAnalogCh(), LSDelayChipV1::getConfigReg(), ICECALv3::getDelayLineCh(), ICECALv3::getMainReg(), FEB_v1::globalPseudoPMEnable(), SpecsSlave::init(), SpecsMaster::init(), NI6008::init(), UsbFTMLInterface::init(), UsbFTInterface::init(), CurrentMeasurement::initialize(), A3PE_BitFlip::initialize(), FEB_v1::injectModeFE(), FEB_v1::latency(), FEB_v1::latencyLLT(), A3PE::loadFromAX(), Application::loadHistoryFile(), A3PE::loadPattern(), A3PE::loadStorage(), A3PE::loadToAX(), A3PE::loadTrigger(), Application::loop(), FEB_v1::maskLLT(), Data::name(), FEB_v1::oldSubtract(), MSOxxxx::open(), DLL::print(), FEB_v1::probeEnable(), FEB_v1::pseudoADCEnable(), FEB_v1::pseudoPMEnable(), UsbSpiBus::read(), UsbFTMLInterface::read(), ICPhaser::read(), UsbFTInterface::read(), Phaser::read(), SpecsSlave::reset(), SpecsMaster::reset(), FEB_v1::resetFE(), FEB_v1::resetFifoInjectFE(), FEB_v1::resetFifoSpyFE(), SpecsSlave::resetInternal(), Server_NI6008::Server_NI6008(), A3PE::setAddFromAXRam(), A3PE::setAddToAXRam(), A3PE::setAXRamUsb(), FEB_v1::setCalibCte(), FEB_v1::setClock80MHzFallingEdge(), A3PE::setClockDivision(), FEB_v1::setClockFallingEdge(), LSDelayChipV1::setConfigReg(), UsbSpiBus::setDataLength(), FEB_v1::setDisableSubtract(), A3PE::setEnableADC(), A3PE::setFifoDepth(), A3PE::setFifoLatency(), FEB_v1::setGain4(), FEB_v1::setGbt80MHzClkEport(), FEB_v1::setGbtClockStrength(), FEB_v1::setGbtDataPath(), FEB_v1::setGbtDLLEport(), FEB_v1::setGbtEnableEport(), FEB_v1::setGbtMode(), FEB_v1::setGbtTermEport(), FEB_v1::setGbtTrackMode(), FEB_v1::setGlobalPseudoPMEnable(), FEB_v1::setInjectModeFE(), A3PE::setInternalAXSequence(), FEB_v1::setLatency(), A3PE::setLatencyAX(), A3PE::setLengthAX(), A3PE::setNTrigger(), FEB_v1::setOldSubtract(), FEB_v1::setOutputEport(), ICPhaser::setPhase(), Phaser::setPhase(), A3PE::setPipeline(), FEB_v1::setPseudoADCEnable(), FEB_v1::setPseudoPMEnable(), RAM::setSize(), A3PE::setSoftwareTrigger(), FEB_v1::setSpareForTrigEnable(), SpecsMaster::setSpeed(), FEB_v1::setSpyModeFE(), FEB_v1::setStopInjLoop(), FEB_v1::setTestDuration(), FEB_v1::setThreshold(), A3PE::setTriggerDelay(), A3PE::setTriggerRate(), IOdata::setU16(), IOdata::setU32(), IOdata::setU8(), MSOxxxx::setupAvgVoltage(), MSOxxxx::setupDeltaTime(), MSOxxxx::setupJitter(), LSDelayChipV1::showConfig(), TestSuite::sigma(), FEB_v1::spareForTrigEnable(), SpecsI2c::SpecsI2c(), SpecsInterface::specsReadI2c(), SpecsInterface::specsReadParallel(), SpecsInterface::specsReadRegister(), SpecsInterface::specsWriteI2c(), SpecsInterface::specsWriteParallel(), SpecsInterface::specsWriteRegister(), ICECALv3::spiAddressScan(), LSDelayChipV1::spiBERTest(), FEB_v1::spyModeFE(), FEB_v1::spyModeSeq(), Server_NI6008::status(), FEB_v1::statusRegister(), FEB_v1::stopInjLoop(), Options::storageFullPath(), Application::terminate(), FEB_v1::testDuration(), FEB_v1::threshold(), Data::title(), MSOxxxx::triggerConfig(), UsbFTMLInterface::usbRead(), UsbFTInterface::usbRead(), UsbFTMLInterface::usbReadU16(), UsbFTInterface::usbReadU16(), UsbFTMLInterface::usbReadU32(), UsbFTInterface::usbReadU32(), UsbFTMLInterface::usbReadU8(), UsbFTInterface::usbReadU8(), UsbFTMLInterface::usbWrite(), UsbFTInterface::usbWrite(), UsbFTMLInterface::usbWriteRead(), UsbFTInterface::usbWriteRead(), UsbFTMLInterface::usbWriteU16(), UsbFTInterface::usbWriteU16(), UsbFTMLInterface::usbWriteU32(), UsbFTInterface::usbWriteU32(), UsbFTMLInterface::usbWriteU8(), UsbFTInterface::usbWriteU8(), Data::vectorPtr(), ICECALv3::version(), wait(), MSOxxxx::waveformCapture(), UsbSpiBus::write(), UsbFTMLInterface::write(), ICPhaser::write(), UsbFTInterface::write(), and Phaser::write().
                     
  char val[20];
  sprintf(val,"%d",i);
  std::string str(val);
  return str;
const std::string& machineType ()
Machine type.
Definition at line 73 of file Server_NI6008.h.
                               
  static std::string mach = "";
  struct utsname ut;
  if (uname(&ut) == 0)
    mach = ut.machine;
   else
    mach = "UNKNOWN";
  
  return mach;
const std::string& osName ()
OS name.
Definition at line 48 of file Server_NI6008.h.
Referenced by Application::Application(), and Server_NI6008::Server_NI6008().
                          
  static std::string osname = "";
  struct utsname ut;
  if (uname(&ut) == 0)
    osname = ut.sysname;
   else
    osname = "UNKNOWN";
  
  return osname;
const std::string& osVersion ()
OS version.
Definition at line 61 of file Server_NI6008.h.
Referenced by Application::Application(), and Server_NI6008::Server_NI6008().
                             
  static std::string osver = "";
  struct utsname ut;
  if (uname(&ut) == 0)
    osver = ut.release;
   else
    osver = "UNKNOWN";
  
  return osver;