InterfaceWrap Struct Reference
Public Member Functions
void help ()
StatusCode init ()
void reset ()
void update ()
StatusCode read (IOdata *)
StatusCode write (IOdata *)
Additional Inherited Members
Detailed Description
Definition at line 17 of file Python.cpp.
Member Function Documentation
help()
void InterfaceWrap::help () [inline], [virtual]
printout help for the element
Implements Interface.
Definition at line 19 of file Python.cpp.
{this->get_override("help")();};
init()
StatusCode InterfaceWrap::init () [inline], [virtual]
init the component
Returns
void
Implements Interface.
Definition at line 20 of file Python.cpp.
{return this->get_override("init")();};
read()
StatusCode InterfaceWrap::read (IOdata *) [inline], [virtual]
Implements Interface.
Definition at line 23 of file Python.cpp.
{return this->get_override("read")();};
reset()
void InterfaceWrap::reset () [inline], [virtual]
Resets the Element so that is is in a standard and safe situation. Different from Element::init which configure the Element. Element::reset() is more an Emergency pull. It is often/usually called by the recursiveInitElement method at the start of the program.
Implements Interface.
Definition at line 21 of file Python.cpp.
{this->get_override("reset")();};
update()
void InterfaceWrap::update () [inline], [virtual]
Update the Element configuration from the actual hardware
Implements Interface.
Definition at line 22 of file Python.cpp.
Referenced by AppFrame.AppFrame::deleteHardware(), ConfFrame.ConfFrame::onChange(), GraphFrame.GraphFrame::onChange(), CfgFrame.CfgFrame::onChange(), ConfFrame.ConfFrame::onEdit(), AppFrame.AppFrame::onLoad(), ConfFrame.ConfFrame::onReLoad(), GraphFrame.GraphFrame::onReLoad(), CfgFrame.CfgFrame::onReLoad(), and AppFrame.AppFrame::onReLoad().
{this->get_override("update")();};
write()
StatusCode InterfaceWrap::write (IOdata *) [inline], [virtual]
Implements Interface.
Definition at line 24 of file Python.cpp.
{return this->get_override("write")();};
The documentation for this struct was generated from the following file:
/home/eleclhcb/LHCb/lbcat-cmake/CatCore/src/Python.cpp