/home/eleclhcb/LHCb/lbcat-cmake/CatKernel/src/Tools.cpp File Reference
#include <stdlib.h>
#include <iostream>
#include <string>
#include <math.h>
#include <unistd.h>
#include `Application.h`
#include `Options.h`
#include `Tools.h`
Macros
#define __FCT_CPP_
Functions
void setApplication (Application *cat)
Application * application ()
std::string itos (int i)
std::string ftos (float f)
std::string dtos (double d)
std::string btos (std::vector< bool > bits)
std::vector< bool > itob (int val, int nbit)
int stoi (std::string value)
double toDouble (std::string s)
StatusCode checkCmd (std::string format, commands instruction, vars &varlist)
bool isFloat (const char *chain)
bool isInt (const char *chain)
bool askSvc (std::string msg)
bool graphSvc ()
std::string inputSvc (std::string msg)
void wait (int n)
Variables
Application * gApp
Macro Definition Documentation
__FCT_CPP_
#define __FCT_CPP_
Definition at line 14 of file Tools.cpp.
Function Documentation
application()
Application* application ()
return entry point for the application
Definition at line 42 of file Tools.cpp.
References gApp.
Referenced by Application::bookkeeping(), checkCmd(), Computer::Computer(), Acquisition::execute(), TestI2C::execute(), ADCMeasurement::execute(), CurrentMeasurement::execute(), DLL::init(), Acquisition::initialize(), ADCMeasurement::initialize(), CurrentMeasurement::initialize(), isInt(), Application::loadHistoryFile(), MsgSvc::log(), MsgSvc::msgSvc(), Application::network(), NI6008::NI6008(), DLL::print(), ProcDataBase::ProcDataBase(), Server::Server(), Processus::setState(), Server::start(), wait(), and Computer::~Computer().
                           {
  return gApp;
}
askSvc()
bool askSvc (std::string msg)
Definition at line 242 of file Tools.cpp.
                             {
  /*
  AskPrinter asker = application() -> options() -> askPrinter ();
  return asker (msg);
  */
  return false;
}
btos()
std::string btos (std::vector< bool >)
Conversion from binary (std::vector<std::string>) to std::string
Definition at line 67 of file Tools.cpp.
References itos().
Referenced by IOdata::dump().
                                    {
  int i=bits.size()-1;
  std::string output;
  while(i>=0){
    output+=itos(bits[i]);
    i--;
  }
  return output;
}
checkCmd()
StatusCode checkCmd (std::string , commands , vars &)
check the format of an instruction
Definition at line 126 of file Tools.cpp.
References application(), StatusCode::FAILURE, images::index, Object::info(), isFloat(), isInt(), cat::size, StatusCode::SUCCESS, and Object::warning().
                                                                              {
  int size = instruction.size();
  if (size<=0){
    return StatusCode::FAILURE;
  }
  // line is empty
  if (format.empty() || std::string::npos==format.find_first_not_of(' ')) {
    return StatusCode::FAILURE;
  }
  // split the format in a vector of strings
  // decode the main command
  std::string line = std::string (format,
                  format.find_first_not_of(' ') ,
                  format.size());
  std::vector<std::string> cmd;
  std::string separator(1,' ');
  unsigned int ipos = line.find(separator);
  cmd.push_back (std::string(line, 0, ipos));
  if (0!=std::string (line , 0 , ipos).compare(instruction[0])){
    application()->info(std::string (line , 0 , ipos)+" "+instruction[0],"");
    return StatusCode::FAILURE;
  }
  unsigned int pos ;
  std::string str = line;
  while (ipos!=std::string::npos){
    std::string tmp = std::string (str, ipos , str.size());
    str = tmp;
    pos=str.find_first_not_of(' ');
    if (pos == std::string::npos) {
      break;
    }
    std::string arg;
    ipos = str.find(separator,pos);
  
    if (ipos==std::string::npos){
      arg = std::string(str , pos);
    }
    else {
      arg = std::string(str , pos, ipos - 1);
    }
    cmd.push_back(arg);
  }
  // check parameter number
  if (instruction.size() != cmd.size()){
    application()->info("wrong number of parameter. a enelver !!!!","");
    return StatusCode::FAILURE;
  }
  // no parameter
  if (1==cmd.size()){
    return StatusCode::SUCCESS;
  }
  // decode the format
  for (unsigned int index = 1; index < cmd.size() ; ++index){
    // int ?
    if (0==cmd[index].compare("%i") || 0==cmd[index].compare("%I")){
      if (!isInt (instruction[index].c_str())) {
    application()->warning("We expect an integer parameter ["+instruction[
      index]+"]","checkCmd");
    return StatusCode::FAILURE;
      }
      varlist.push_back (var(atoi(instruction[index].c_str())));
    }
    // float ?
    if (0==cmd[index].compare("%f") || 0==cmd[index].compare("%F")){
      if (!isFloat (instruction[index].c_str())) {
    application()->warning("We expect a float parameter ["+instruction[
      index]+"]","checkCmd");
    return StatusCode::FAILURE;
      }
      varlist.push_back(var (atof(instruction[index].c_str())));
    }
  }
  return StatusCode::SUCCESS;
}
dtos()
std::string dtos (double d)
Definition at line 60 of file Tools.cpp.
                        {
  char val[20];
  sprintf(val,"%f",d);
  std::string str(val);
  return str;
}
ftos()
std::string ftos (float)
Conversion from float to std::string
Definition at line 53 of file Tools.cpp.
                       {
  char val[20];
  sprintf(val,"%f",f);
  std::string str(val);
  return str;
}
graphSvc()
bool graphSvc ()
Definition at line 250 of file Tools.cpp.
                {
  // GraphPrinter graph = application() -> options() -> graphPrinter ();
  // return graph ();
  return false;
}
inputSvc()
std::string inputSvc (std::string msg)
Definition at line 259 of file Tools.cpp.
                                    {
  /*
  InputSvc inp = application() -> options() -> inputSvc ();
  return inp (msg);
  */
  return std::string("not implemented.");
}
isFloat()
bool isFloat (const char *)
check if string is compatible with float
Definition at line 206 of file Tools.cpp.
Referenced by checkCmd().
                                  {
  const char *pChain = chain;
  while (*pChain!='\0') {
    if (*pChain!='0' && *pChain!='1' && *pChain!='2' && *pChain!='3' &&
     *pChain!='4' && *pChain!='5' && *pChain!='6' && *pChain!='7' &&
     *pChain!='8' && *pChain!='9' && *pChain!='+' && *pChain!='-' &&
     *pChain!='.'){
      return false;
    }
    pChain++;
  }
  return true;
}
isInt()
bool isInt (const char *)
check if string is compatible with int
Definition at line 223 of file Tools.cpp.
References application(), and Object::info().
Referenced by checkCmd().
                                {
  const char *pChain = chain;
  bool first = true;
  while (*pChain!='\0') {
    if ((*pChain<'0' || *pChain>'9')){
      application()->info(chain,"");
      if (!first || *pChain!='-'){
    return false;
      }
    }
    first = false;
    pChain++;
  }
  return true;
}
itob()
std::vector<bool> itob (int , int)
Conversion from integer to binary (std::string)
Definition at line 77 of file Tools.cpp.
Referenced by IOdata::dump().
                                      {
  int i=nbit-1;
  int power;
  std::vector<bool> bits(nbit);
  // int limit=1<<(nbit-1);
  //int vsat=(val<limit)?val:int(limit-1); //saturation
  int vsat=val;
  while(i>=0){
    power=1<<i;
    bits[i]=(vsat/power==1);
    vsat=vsat%power;
    i--;
  }
  return bits;
}
itos()
std::string itos (int)
Conversion from int (long) to std::string
Definition at line 46 of file Tools.cpp.
Referenced by btos(), and wait().
                     {
  char val[20];
  sprintf(val,"%d",i);
  std::string str(val);
  return str;
}
setApplication()
void setApplication (Application *)
Define entry point for the application
Definition at line 38 of file Tools.cpp.
References gui::cat.
Referenced by Application::Application().
                                      {
  gApp = cat;
}
stoi()
int stoi (std::string)
Conversion from binary (std::string) to integer
Definition at line 93 of file Tools.cpp.
References cat::size.
                         {
  const unsigned int codage=2;
  int result=0;
  char h[codage]={'0','1'};
  const unsigned int size=value.size();
  const char* word=value.c_str();
  unsigned int pos=0;
  while (pos<size){
    bool isSeen=false;
    for (unsigned int j=0; j<codage && !isSeen; j++){
      if (h[j]==word[pos]){
    result+=int(j*pow(2.,(int)(size-pos-1)));
    isSeen=true;
      }
    }
    pos++;
  }
  return result;
}
toDouble()
double toDouble (std::string)
Conversion from string (potentially with a comma) to a double
Definition at line 113 of file Tools.cpp.
                            {
    // do not use a reference, since we're going to modify this string
    // If you do not care about ',' or '.' in your string use a
    // reference instead.
    size_t found = s.find(",");
    if(found != std::string::npos)
        s[found]='.'; // Change ',' to '.'
    return atof(s.c_str());
}
wait()
void wait (int nbr_ms)
system wait for a few seconds
Definition at line 271 of file Tools.cpp.
References application(), itos(), and Object::verbose().
Referenced by ADCMeasurement::execute(), CurrentMeasurement::execute(), UsbFTInterface::init(), and UsbFTMLInterface::init().
{
  application()->verbose("wait for "+itos(n)+" ms.","Tools::wait");
#ifdef WIN32
  Sleep(n);
#else
  usleep(1000 * n);
#endif
}
Variable Documentation
gApp
Application* gApp
Definition at line 36 of file Tools.cpp.
Referenced by application().